export const weapons = [
  { label: 'Grave Wand', value: 'Grave Wand' },
  { label: 'Quarterstaff', value: 'Quarterstaff' },
  { label: 'Falchion', value: 'Falchion' },
  { label: 'Katana', value: 'Katana' },
  { label: 'Tome', value: 'Tome' },
  { label: 'Scimitar', value: 'Scimitar' },
  { label: 'Maul', value: 'Maul' },
  { label: 'Grimoire', value: 'Grimoire' },
  { label: 'Short Sword', value: 'Short Sword' },
  { label: 'Chronicle', value: 'Chronicle' },
  { label: 'Book', value: 'Book' },
  { label: 'Long Sword', value: 'Long Sword' },
  { label: 'Mace', value: 'Mace' },
  { label: 'Wand', value: 'Wand' },
  { label: 'Bone Wand', value: 'Bone Wand' },
  { label: 'Ghost Wand', value: 'Ghost Wand' },
  { label: 'Warhammer', value: 'Warhammer' },
  { label: 'Club', value: 'Club' },
  { label: 'Falchion of Fury', value: 'Falchion of Fury' },
  { label: 'Falchion of Reflection', value: 'Falchion of Reflection' },
  { label: 'Mace of Vitriol', value: 'Mace of Vitriol' },
  { label: 'Bone Wand of Power', value: 'Bone Wand of Power' },
  { label: 'Chronicle of Detection', value: 'Chronicle of Detection' },
  { label: 'Warhammer of Titans', value: 'Warhammer of Titans' },
  { label: 'Bone Wand of Titans', value: 'Bone Wand of Titans' },
  { label: 'Bone Wand of Fury', value: 'Bone Wand of Fury' },
  { label: 'Falchion of the Fox', value: 'Falchion of the Fox' },
  { label: 'Mace of Giants', value: 'Mace of Giants' },
  { label: 'Mace of the Twins', value: 'Mace of the Twins' },
  { label: 'Chronicle of Protection', value: 'Chronicle of Protection' },
  { label: 'Chronicle of Rage', value: 'Chronicle of Rage' },
  { label: 'Mace of Skill', value: 'Mace of Skill' },
  { label: 'Warhammer of Power', value: 'Warhammer of Power' },
  { label: 'Mace of Detection', value: 'Mace of Detection' },
  { label: 'Chronicle of the Twins', value: 'Chronicle of the Twins' },
  { label: 'Falchion of Enlightenment', value: 'Falchion of Enlightenment' },
  { label: 'Short Sword of the Twins', value: 'Short Sword of the Twins' },
  { label: 'Warhammer of Anger', value: 'Warhammer of Anger' },
  { label: 'Bone Wand of Reflection', value: 'Bone Wand of Reflection' },
  { label: 'Book of Protection', value: 'Book of Protection' },
  { label: 'Chronicle of Giants', value: 'Chronicle of Giants' },
  { label: 'Grimoire of Reflection', value: 'Grimoire of Reflection' },
  { label: 'Mace of Brilliance', value: 'Mace of Brilliance' },
  { label: 'Mace of Protection', value: 'Mace of Protection' },
  { label: 'Warhammer of Reflection', value: 'Warhammer of Reflection' },
  { label: 'Bone Wand of the Fox', value: 'Bone Wand of the Fox' },
  { label: 'Chronicle of Vitriol', value: 'Chronicle of Vitriol' },
  { label: 'Falchion of Power', value: 'Falchion of Power' },
  { label: 'Short Sword of Giants', value: 'Short Sword of Giants' },
  { label: 'Short Sword of Protection', value: 'Short Sword of Protection' },
  { label: 'Short Sword of Skill', value: 'Short Sword of Skill' },
  { label: 'Tome of the Fox', value: 'Tome of the Fox' },
  { label: 'Warhammer of Fury', value: 'Warhammer of Fury' },
  { label: 'Warhammer of Perfection', value: 'Warhammer of Perfection' },
  { label: 'Warhammer of the Fox', value: 'Warhammer of the Fox' },
  { label: 'Bone Wand of Perfection', value: 'Bone Wand of Perfection' },
  { label: 'Club of Reflection', value: 'Club of Reflection' },
  { label: 'Falchion of Anger', value: 'Falchion of Anger' },
  { label: 'Katana of Brilliance', value: 'Katana of Brilliance' },
  { label: 'Long Sword of the Fox', value: 'Long Sword of the Fox' },
  { label: 'Bone Wand of Enlightenment', value: 'Bone Wand of Enlightenment' },
  { label: 'Falchion of Titans', value: 'Falchion of Titans' },
  { label: 'Grimoire of the Fox', value: 'Grimoire of the Fox' },
  { label: 'Katana of Skill', value: 'Katana of Skill' },
  { label: 'Long Sword of Power', value: 'Long Sword of Power' },
  { label: 'Mace of Rage', value: 'Mace of Rage' },
  { label: 'Short Sword of Brilliance', value: 'Short Sword of Brilliance' },
  { label: 'Short Sword of Rage', value: 'Short Sword of Rage' },
  { label: 'Book of Giants', value: 'Book of Giants' },
  { label: 'Ghost Wand of Titans', value: 'Ghost Wand of Titans' },
  { label: 'Grave Wand of Protection', value: 'Grave Wand of Protection' },
  { label: 'Grimoire of Power', value: 'Grimoire of Power' },
  { label: 'Scimitar of Giants', value: 'Scimitar of Giants' },
  { label: 'Short Sword of Detection', value: 'Short Sword of Detection' },
  { label: 'Short Sword of Vitriol', value: 'Short Sword of Vitriol' },
  { label: 'Wand of Brilliance', value: 'Wand of Brilliance' },
  { label: 'Wand of Rage', value: 'Wand of Rage' },
  { label: 'Bone Wand of Anger', value: 'Bone Wand of Anger' },
  { label: 'Club of Perfection', value: 'Club of Perfection' },
  { label: 'Club of Power', value: 'Club of Power' },
  { label: 'Ghost Wand of Anger', value: 'Ghost Wand of Anger' },
  { label: 'Grimoire of Enlightenment', value: 'Grimoire of Enlightenment' },
  { label: 'Katana of Protection', value: 'Katana of Protection' },
  { label: 'Long Sword of Fury', value: 'Long Sword of Fury' },
  { label: 'Long Sword of Reflection', value: 'Long Sword of Reflection' },
  { label: 'Quarterstaff of Brilliance', value: 'Quarterstaff of Brilliance' },
  { label: 'Quarterstaff of Protection', value: 'Quarterstaff of Protection' },
  { label: 'Tome of Power', value: 'Tome of Power' },
  { label: 'Wand of Protection', value: 'Wand of Protection' },
  { label: 'Wand of Skill', value: 'Wand of Skill' },
  { label: 'Book of Brilliance', value: 'Book of Brilliance' },
  { label: 'Book of Rage', value: 'Book of Rage' },
  { label: 'Chronicle of Brilliance', value: 'Chronicle of Brilliance' },
  { label: 'Chronicle of Skill', value: 'Chronicle of Skill' },
  { label: 'Club of Anger', value: 'Club of Anger' },
  { label: 'Grave Wand of Giants', value: 'Grave Wand of Giants' },
  { label: 'Grave Wand of the Twins', value: 'Grave Wand of the Twins' },
  { label: 'Maul of Anger', value: 'Maul of Anger' },
  { label: 'Maul of Fury', value: 'Maul of Fury' },
  { label: 'Maul of Reflection', value: 'Maul of Reflection' },
  { label: 'Maul of Titans', value: 'Maul of Titans' },
  { label: 'Quarterstaff of Vitriol', value: 'Quarterstaff of Vitriol' },
  { label: 'Scimitar of Detection', value: 'Scimitar of Detection' },
  { label: 'Tome of Enlightenment', value: 'Tome of Enlightenment' },
  { label: 'Tome of Fury', value: 'Tome of Fury' },
  { label: 'Warhammer of Enlightenment', value: 'Warhammer of Enlightenment' },
  { label: 'Club of Titans', value: 'Club of Titans' },
  { label: 'Ghost Wand of Perfection', value: 'Ghost Wand of Perfection' },
  { label: 'Grimoire of Perfection', value: 'Grimoire of Perfection' },
  { label: 'Katana of the Twins', value: 'Katana of the Twins' },
  { label: 'Long Sword of Perfection', value: 'Long Sword of Perfection' },
  { label: 'Quarterstaff of Rage', value: 'Quarterstaff of Rage' },
  { label: 'Quarterstaff of the Twins', value: 'Quarterstaff of the Twins' },
  { label: 'Scimitar of Vitriol', value: 'Scimitar of Vitriol' },
  { label: 'Tome of Perfection', value: 'Tome of Perfection' },
  { label: 'Wand of Detection', value: 'Wand of Detection' },
  { label: 'Wand of the Twins', value: 'Wand of the Twins' },
  { label: 'Book of Skill', value: 'Book of Skill' },
  { label: 'Book of Vitriol', value: 'Book of Vitriol' },
  { label: 'Ghost Wand of Enlightenment', value: 'Ghost Wand of Enlightenment' },
  { label: 'Ghost Wand of Fury', value: 'Ghost Wand of Fury' },
  { label: 'Grave Wand of Brilliance', value: 'Grave Wand of Brilliance' },
  { label: 'Grave Wand of Skill', value: 'Grave Wand of Skill' },
  { label: 'Grimoire of Fury', value: 'Grimoire of Fury' },
  { label: 'Grimoire of Titans', value: 'Grimoire of Titans' },
  { label: 'Long Sword of Titans', value: 'Long Sword of Titans' },
  { label: 'Maul of Perfection', value: 'Maul of Perfection' },
  { label: 'Maul of Power', value: 'Maul of Power' },
  { label: 'Scimitar of Protection', value: 'Scimitar of Protection' },
  { label: 'Tome of Titans', value: 'Tome of Titans' },
  { label: 'Wand of Giants', value: 'Wand of Giants' },
  { label: 'Book of Detection', value: 'Book of Detection' },
  { label: 'Falchion of Perfection', value: 'Falchion of Perfection' },
  { label: 'Ghost Wand of Power', value: 'Ghost Wand of Power' },
  { label: 'Ghost Wand of Reflection', value: 'Ghost Wand of Reflection' },
  { label: 'Grave Wand of Detection', value: 'Grave Wand of Detection' },
  { label: 'Grimoire of Anger', value: 'Grimoire of Anger' },
  { label: 'Katana of Giants', value: 'Katana of Giants' },
  { label: 'Katana of Rage', value: 'Katana of Rage' },
  { label: 'Katana of Vitriol', value: 'Katana of Vitriol' },
  { label: 'Long Sword of Enlightenment', value: 'Long Sword of Enlightenment' },
  { label: 'Maul of Enlightenment', value: 'Maul of Enlightenment' },
  { label: 'Quarterstaff of Skill', value: 'Quarterstaff of Skill' },
  { label: 'Scimitar of Brilliance', value: 'Scimitar of Brilliance' },
  { label: 'Scimitar of Rage', value: 'Scimitar of Rage' },
  { label: 'Scimitar of Skill', value: 'Scimitar of Skill' },
  { label: 'Tome of Reflection', value: 'Tome of Reflection' },
  { label: 'Wand of Vitriol', value: 'Wand of Vitriol' },
  { label: 'Club of Enlightenment', value: 'Club of Enlightenment' },
  { label: 'Club of the Fox', value: 'Club of the Fox' },
  { label: 'Ghost Wand of the Fox', value: 'Ghost Wand of the Fox' },
  { label: 'Grave Wand of Rage', value: 'Grave Wand of Rage' },
  { label: 'Katana of Detection', value: 'Katana of Detection' },
  { label: 'Long Sword of Anger', value: 'Long Sword of Anger' },
  { label: 'Quarterstaff of Detection', value: 'Quarterstaff of Detection' },
  { label: 'Scimitar of the Twins', value: 'Scimitar of the Twins' },
  { label: 'Demon Peak Grimoire of Enlightenment +1', value: 'Demon Peak Grimoire of Enlightenment +1' },
  { label: 'Maul of the Fox', value: 'Maul of the Fox' },
  { label: 'Tome of Anger', value: 'Tome of Anger' },
  { label: 'Apocalypse Root Quarterstaff of Vitriol', value: 'Apocalypse Root Quarterstaff of Vitriol' },
  { label: 'Blight Moon Book of the Twins +1', value: 'Blight Moon Book of the Twins +1' },
  { label: 'Book of the Twins', value: 'Book of the Twins' },
  { label: 'Carrion Whisper Ghost Wand of Enlightenment', value: 'Carrion Whisper Ghost Wand of Enlightenment' },
  { label: 'Club of Fury', value: 'Club of Fury' },
  { label: 'Foe Moon Book of Vitriol +1', value: 'Foe Moon Book of Vitriol +1' },
  { label: 'Gloom Grasp Katana of Brilliance +1', value: 'Gloom Grasp Katana of Brilliance +1' },
  { label: 'Grave Wand of Vitriol', value: 'Grave Wand of Vitriol' },
  { label: 'Grim Bite Maul of Enlightenment +1', value: 'Grim Bite Maul of Enlightenment +1' },
  { label: 'Maelstrom Glow Scimitar of Rage', value: 'Maelstrom Glow Scimitar of Rage' },
  { label: 'Quarterstaff of Giants', value: 'Quarterstaff of Giants' },
  { label: 'Woe Grasp Katana of Rage +1', value: 'Woe Grasp Katana of Rage +1' },
  { label: 'Apocalypse Roar Club of Anger', value: 'Apocalypse Roar Club of Anger' },
  { label: 'Apocalypse Root Quarterstaff of Skill', value: 'Apocalypse Root Quarterstaff of Skill' },
  { label: 'Armageddon Moon Book of the Twins +1', value: 'Armageddon Moon Book of the Twins +1' },
  { label: 'Behemoth Glow Scimitar of Detection', value: 'Behemoth Glow Scimitar of Detection' },
  { label: 'Behemoth Root Quarterstaff of Rage', value: 'Behemoth Root Quarterstaff of Rage' },
  { label: 'Behemoth Whisper Ghost Wand of Anger', value: 'Behemoth Whisper Ghost Wand of Anger' },
  { label: 'Blight Grasp Katana of Vitriol +1', value: 'Blight Grasp Katana of Vitriol +1' },
  { label: 'Brimstone Bender Long Sword of Titans +1', value: 'Brimstone Bender Long Sword of Titans +1' },
  { label: 'Brimstone Moon Book of Giants +1', value: 'Brimstone Moon Book of Giants +1' },
  { label: 'Carrion Glow Scimitar of the Twins', value: 'Carrion Glow Scimitar of the Twins' },
  { label: 'Carrion Roar Club of Power', value: 'Carrion Roar Club of Power' },
  { label: 'Carrion Root Quarterstaff of Vitriol', value: 'Carrion Root Quarterstaff of Vitriol' },
  { label: 'Cataclysm Moon Book of Rage +1', value: 'Cataclysm Moon Book of Rage +1' },
  { label: 'Cataclysm Shout Grave Wand of Rage +1', value: 'Cataclysm Shout Grave Wand of Rage +1' },
  { label: 'Corpse Root Quarterstaff of Giants', value: 'Corpse Root Quarterstaff of Giants' },
  { label: 'Corpse Tear Wand of Rage', value: 'Corpse Tear Wand of Rage' },
  { label: 'Corruption Bite Maul of Reflection +1', value: 'Corruption Bite Maul of Reflection +1' },
  { label: 'Corruption Moon Book of the Twins +1', value: 'Corruption Moon Book of the Twins +1' },
  { label: 'Corruption Peak Grimoire of Enlightenment +1', value: 'Corruption Peak Grimoire of Enlightenment +1' },
  { label: 'Corruption Peak Grimoire of Fury +1', value: 'Corruption Peak Grimoire of Fury +1' },
  { label: 'Corruption Peak Grimoire of the Fox +1', value: 'Corruption Peak Grimoire of the Fox +1' },
  { label: 'Demon Grasp Katana of Skill +1', value: 'Demon Grasp Katana of Skill +1' },
  { label: 'Demon Grasp Katana of the Twins +1', value: 'Demon Grasp Katana of the Twins +1' },
  { label: 'Demon Moon Book of Rage +1', value: 'Demon Moon Book of Rage +1' },
  { label: 'Dragon Roar Club of Reflection', value: 'Dragon Roar Club of Reflection' },
  { label: 'Dread Bender Long Sword of Perfection +1', value: 'Dread Bender Long Sword of Perfection +1' },
  { label: 'Eagle Bite Maul of Titans +1', value: 'Eagle Bite Maul of Titans +1' },
  { label: 'Eagle Grasp Katana of Rage +1', value: 'Eagle Grasp Katana of Rage +1' },
  { label: 'Eagle Shout Grave Wand of the Twins +1', value: 'Eagle Shout Grave Wand of the Twins +1' },
  { label: 'Fate Glow Scimitar of Brilliance', value: 'Fate Glow Scimitar of Brilliance' },
  { label: 'Fate Glow Scimitar of Giants', value: 'Fate Glow Scimitar of Giants' },
  { label: 'Foe Bender Long Sword of Perfection +1', value: 'Foe Bender Long Sword of Perfection +1' },
  { label: 'Ghoul Sun Tome of the Fox', value: 'Ghoul Sun Tome of the Fox' },
  { label: 'Gloom Peak Grimoire of Reflection +1', value: 'Gloom Peak Grimoire of Reflection +1' },
  { label: 'Golem Sun Tome of Enlightenment', value: 'Golem Sun Tome of Enlightenment' },
  { label: 'Golem Tear Wand of Vitriol', value: 'Golem Tear Wand of Vitriol' },
  { label: 'Golem Whisper Ghost Wand of Fury', value: 'Golem Whisper Ghost Wand of Fury' },
  { label: 'Grim Moon Book of Protection +1', value: 'Grim Moon Book of Protection +1' },
  { label: 'Grim Shout Grave Wand of Protection +1', value: 'Grim Shout Grave Wand of Protection +1' },
  { label: 'Grim Shout Grave Wand of Skill +1', value: 'Grim Shout Grave Wand of Skill +1' },
  { label: 'Havoc Root Quarterstaff of Rage', value: 'Havoc Root Quarterstaff of Rage' },
  { label: 'Honour Bite Maul of Reflection +1', value: 'Honour Bite Maul of Reflection +1' },
  { label: 'Honour Grasp Katana of Protection +1', value: 'Honour Grasp Katana of Protection +1' },
  { label: 'Honour Grasp Katana of Vitriol +1', value: 'Honour Grasp Katana of Vitriol +1' },
  { label: 'Hypnotic Roar Club of Anger', value: 'Hypnotic Roar Club of Anger' },
  { label: 'Hypnotic Roar Club of Perfection', value: 'Hypnotic Roar Club of Perfection' },
  { label: 'Kraken Grasp Katana of Detection +1', value: 'Kraken Grasp Katana of Detection +1' },
  { label: "Light's Root Quarterstaff of Brilliance", value: "Light's Root Quarterstaff of Brilliance" },
  { label: "Light's Whisper Ghost Wand of Power", value: "Light's Whisper Ghost Wand of Power" },
  { label: 'Maelstrom Tear Wand of Skill', value: 'Maelstrom Tear Wand of Skill' },
  { label: 'Maelstrom Whisper Ghost Wand of Anger', value: 'Maelstrom Whisper Ghost Wand of Anger' },
  { label: 'Maelstrom Whisper Ghost Wand of Power', value: 'Maelstrom Whisper Ghost Wand of Power' },
  { label: 'Mind Moon Book of Skill +1', value: 'Mind Moon Book of Skill +1' },
  { label: 'Mind Peak Grimoire of the Fox +1', value: 'Mind Peak Grimoire of the Fox +1' },
  { label: 'Morbid Roar Club of the Fox', value: 'Morbid Roar Club of the Fox' },
  { label: 'Oblivion Bender Long Sword of Power +1', value: 'Oblivion Bender Long Sword of Power +1' },
  { label: 'Oblivion Peak Grimoire of Fury +1', value: 'Oblivion Peak Grimoire of Fury +1' },
  { label: 'Pain Sun Tome of Power', value: 'Pain Sun Tome of Power' },
  { label: 'Pain Tear Wand of Rage', value: 'Pain Tear Wand of Rage' },
  { label: 'Pandemonium Grasp Katana of Rage +1', value: 'Pandemonium Grasp Katana of Rage +1' },
  { label: 'Pandemonium Moon Book of Giants +1', value: 'Pandemonium Moon Book of Giants +1' },
  { label: 'Plague Tear Wand of Protection', value: 'Plague Tear Wand of Protection' },
  { label: 'Plague Tear Wand of Rage', value: 'Plague Tear Wand of Rage' },
  { label: 'Rune Root Quarterstaff of Giants', value: 'Rune Root Quarterstaff of Giants' },
  { label: 'Shimmering Grasp Katana of Rage +1', value: 'Shimmering Grasp Katana of Rage +1' },
  { label: 'Skull Moon Book of Vitriol +1', value: 'Skull Moon Book of Vitriol +1' },
  { label: 'Sorrow Bite Maul of Perfection +1', value: 'Sorrow Bite Maul of Perfection +1' },
  { label: 'Sorrow Grasp Katana of Skill +1', value: 'Sorrow Grasp Katana of Skill +1' },
  { label: 'Sorrow Moon Book of Detection +1', value: 'Sorrow Moon Book of Detection +1' },
  { label: 'Soul Roar Club of Power', value: 'Soul Roar Club of Power' },
  { label: 'Soul Root Quarterstaff of Skill', value: 'Soul Root Quarterstaff of Skill' },
  { label: 'Soul Sun Tome of Fury', value: 'Soul Sun Tome of Fury' },
  { label: 'Storm Sun Tome of Power', value: 'Storm Sun Tome of Power' },
  { label: 'Storm Tear Wand of Detection', value: 'Storm Tear Wand of Detection' },
  { label: 'Tempest Bite Maul of Enlightenment +1', value: 'Tempest Bite Maul of Enlightenment +1' },
  { label: 'Tempest Bite Maul of the Fox +1', value: 'Tempest Bite Maul of the Fox +1' },
  { label: 'Tempest Peak Grimoire of Reflection +1', value: 'Tempest Peak Grimoire of Reflection +1' },
  { label: 'Tempest Shout Grave Wand of Skill +1', value: 'Tempest Shout Grave Wand of Skill +1' },
  { label: 'Vengeance Glow Scimitar of Vitriol', value: 'Vengeance Glow Scimitar of Vitriol' },
  { label: 'Vengeance Roar Club of Reflection', value: 'Vengeance Roar Club of Reflection' },
  { label: 'Vortex Tear Wand of Brilliance', value: 'Vortex Tear Wand of Brilliance' },
  { label: 'Vortex Whisper Ghost Wand of Reflection', value: 'Vortex Whisper Ghost Wand of Reflection' },
  { label: 'Woe Bender Long Sword of Fury +1', value: 'Woe Bender Long Sword of Fury +1' },
  { label: 'Woe Bender Long Sword of the Fox +1', value: 'Woe Bender Long Sword of the Fox +1' },
  { label: 'Woe Grasp Katana of Detection +1', value: 'Woe Grasp Katana of Detection +1' },
  { label: 'Woe Moon Book of the Twins +1', value: 'Woe Moon Book of the Twins +1' },
  { label: 'Apocalypse Glow Scimitar of Detection', value: 'Apocalypse Glow Scimitar of Detection' },
  { label: 'Apocalypse Glow Scimitar of Vitriol', value: 'Apocalypse Glow Scimitar of Vitriol' },
  { label: 'Apocalypse Roar Club of Enlightenment', value: 'Apocalypse Roar Club of Enlightenment' },
  { label: 'Apocalypse Roar Club of Fury', value: 'Apocalypse Roar Club of Fury' },
  { label: 'Apocalypse Roar Club of Perfection', value: 'Apocalypse Roar Club of Perfection' },
  { label: 'Apocalypse Roar Club of Power', value: 'Apocalypse Roar Club of Power' },
  { label: 'Apocalypse Roar Club of the Fox', value: 'Apocalypse Roar Club of the Fox' },
  { label: 'Apocalypse Sun Tome of Enlightenment', value: 'Apocalypse Sun Tome of Enlightenment' },
  { label: 'Apocalypse Sun Tome of Fury', value: 'Apocalypse Sun Tome of Fury' },
  { label: 'Apocalypse Sun Tome of Perfection', value: 'Apocalypse Sun Tome of Perfection' },
  { label: 'Apocalypse Tear Wand of Brilliance', value: 'Apocalypse Tear Wand of Brilliance' },
  { label: 'Apocalypse Tear Wand of Detection', value: 'Apocalypse Tear Wand of Detection' },
  { label: 'Apocalypse Tear Wand of Protection', value: 'Apocalypse Tear Wand of Protection' },
  { label: 'Apocalypse Tear Wand of Vitriol', value: 'Apocalypse Tear Wand of Vitriol' },
  { label: 'Apocalypse Whisper Ghost Wand of Fury', value: 'Apocalypse Whisper Ghost Wand of Fury' },
  { label: 'Apocalypse Whisper Ghost Wand of the Fox', value: 'Apocalypse Whisper Ghost Wand of the Fox' },
  { label: 'Armageddon Bender Long Sword of Enlightenment +1', value: 'Armageddon Bender Long Sword of Enlightenment +1' },
  { label: 'Armageddon Bite Maul of Anger +1', value: 'Armageddon Bite Maul of Anger +1' },
  { label: 'Armageddon Bite Maul of Perfection +1', value: 'Armageddon Bite Maul of Perfection +1' },
  { label: 'Armageddon Grasp Katana of Detection +1', value: 'Armageddon Grasp Katana of Detection +1' },
  { label: 'Armageddon Grasp Katana of Giants +1', value: 'Armageddon Grasp Katana of Giants +1' },
  { label: 'Armageddon Grasp Katana of Rage +1', value: 'Armageddon Grasp Katana of Rage +1' },
  { label: 'Armageddon Grasp Katana of the Twins +1', value: 'Armageddon Grasp Katana of the Twins +1' },
  { label: 'Armageddon Moon Book of Giants +1', value: 'Armageddon Moon Book of Giants +1' },
  { label: 'Armageddon Moon Book of Rage +1', value: 'Armageddon Moon Book of Rage +1' },
  { label: 'Armageddon Moon Book of Vitriol +1', value: 'Armageddon Moon Book of Vitriol +1' },
  { label: 'Armageddon Peak Grimoire of Enlightenment +1', value: 'Armageddon Peak Grimoire of Enlightenment +1' },
  { label: 'Armageddon Peak Grimoire of the Fox +1', value: 'Armageddon Peak Grimoire of the Fox +1' },
  { label: 'Armageddon Shout Grave Wand of Detection +1', value: 'Armageddon Shout Grave Wand of Detection +1' },
  { label: 'Armageddon Shout Grave Wand of Protection +1', value: 'Armageddon Shout Grave Wand of Protection +1' },
  { label: 'Armageddon Shout Grave Wand of Skill +1', value: 'Armageddon Shout Grave Wand of Skill +1' },
  { label: 'Behemoth Glow Scimitar of Brilliance', value: 'Behemoth Glow Scimitar of Brilliance' },
  { label: 'Behemoth Glow Scimitar of Giants', value: 'Behemoth Glow Scimitar of Giants' },
  { label: 'Behemoth Glow Scimitar of Protection', value: 'Behemoth Glow Scimitar of Protection' },
  { label: 'Behemoth Glow Scimitar of Vitriol', value: 'Behemoth Glow Scimitar of Vitriol' },
  { label: 'Behemoth Roar Club of Fury', value: 'Behemoth Roar Club of Fury' },
  { label: 'Behemoth Root Quarterstaff of Brilliance', value: 'Behemoth Root Quarterstaff of Brilliance' },
  { label: 'Behemoth Root Quarterstaff of Detection', value: 'Behemoth Root Quarterstaff of Detection' },
  { label: 'Behemoth Root Quarterstaff of Vitriol', value: 'Behemoth Root Quarterstaff of Vitriol' },
  { label: 'Behemoth Sun Tome of Anger', value: 'Behemoth Sun Tome of Anger' },
  { label: 'Behemoth Sun Tome of Perfection', value: 'Behemoth Sun Tome of Perfection' },
  { label: 'Behemoth Sun Tome of Reflection', value: 'Behemoth Sun Tome of Reflection' },
  { label: 'Behemoth Tear Wand of Brilliance', value: 'Behemoth Tear Wand of Brilliance' },
  { label: 'Behemoth Tear Wand of Detection', value: 'Behemoth Tear Wand of Detection' },
  { label: 'Behemoth Tear Wand of Protection', value: 'Behemoth Tear Wand of Protection' },
  { label: 'Behemoth Tear Wand of Skill', value: 'Behemoth Tear Wand of Skill' },
  { label: 'Behemoth Whisper Ghost Wand of Reflection', value: 'Behemoth Whisper Ghost Wand of Reflection' },
  { label: 'Blight Bender Long Sword of Reflection +1', value: 'Blight Bender Long Sword of Reflection +1' },
  { label: 'Blight Bite Maul of Enlightenment +1', value: 'Blight Bite Maul of Enlightenment +1' },
  { label: 'Blight Bite Maul of Power +1', value: 'Blight Bite Maul of Power +1' },
  { label: 'Blight Grasp Katana of Brilliance +1', value: 'Blight Grasp Katana of Brilliance +1' },
  { label: 'Blight Grasp Katana of Detection +1', value: 'Blight Grasp Katana of Detection +1' },
  { label: 'Blight Grasp Katana of Rage +1', value: 'Blight Grasp Katana of Rage +1' },
  { label: 'Blight Grasp Katana of Skill +1', value: 'Blight Grasp Katana of Skill +1' },
  { label: 'Blight Peak Grimoire of Anger +1', value: 'Blight Peak Grimoire of Anger +1' },
  { label: 'Blight Peak Grimoire of Enlightenment +1', value: 'Blight Peak Grimoire of Enlightenment +1' },
  { label: 'Blight Peak Grimoire of Perfection +1', value: 'Blight Peak Grimoire of Perfection +1' },
  { label: 'Blight Shout Grave Wand of Giants +1', value: 'Blight Shout Grave Wand of Giants +1' },
  { label: 'Blight Shout Grave Wand of Vitriol +1', value: 'Blight Shout Grave Wand of Vitriol +1' },
  { label: 'Bramble Glow Scimitar of Giants', value: 'Bramble Glow Scimitar of Giants' },
  { label: 'Bramble Glow Scimitar of Vitriol', value: 'Bramble Glow Scimitar of Vitriol' },
  { label: 'Bramble Roar Club of Anger', value: 'Bramble Roar Club of Anger' },
  { label: 'Bramble Roar Club of Reflection', value: 'Bramble Roar Club of Reflection' },
  { label: 'Bramble Roar Club of Titans', value: 'Bramble Roar Club of Titans' },
  { label: 'Bramble Root Quarterstaff of Rage', value: 'Bramble Root Quarterstaff of Rage' },
  { label: 'Bramble Sun Tome of Anger', value: 'Bramble Sun Tome of Anger' },
  { label: 'Bramble Sun Tome of Reflection', value: 'Bramble Sun Tome of Reflection' },
  { label: 'Bramble Tear Wand of Detection', value: 'Bramble Tear Wand of Detection' },
  { label: 'Bramble Tear Wand of Giants', value: 'Bramble Tear Wand of Giants' },
  { label: 'Bramble Tear Wand of the Twins', value: 'Bramble Tear Wand of the Twins' },
  { label: 'Bramble Whisper Ghost Wand of Power', value: 'Bramble Whisper Ghost Wand of Power' },
  { label: 'Brimstone Bender Long Sword of Fury +1', value: 'Brimstone Bender Long Sword of Fury +1' },
  { label: 'Brimstone Bite Maul of Enlightenment +1', value: 'Brimstone Bite Maul of Enlightenment +1' },
  { label: 'Brimstone Grasp Katana of Protection +1', value: 'Brimstone Grasp Katana of Protection +1' },
  { label: 'Brimstone Grasp Katana of Rage +1', value: 'Brimstone Grasp Katana of Rage +1' },
  { label: 'Brimstone Grasp Katana of the Twins +1', value: 'Brimstone Grasp Katana of the Twins +1' },
  { label: 'Brimstone Grasp Katana of Vitriol +1', value: 'Brimstone Grasp Katana of Vitriol +1' },
  { label: 'Brimstone Moon Book of Detection +1', value: 'Brimstone Moon Book of Detection +1' },
  { label: 'Brimstone Moon Book of Skill +1', value: 'Brimstone Moon Book of Skill +1' },
  { label: 'Brimstone Moon Book of the Twins +1', value: 'Brimstone Moon Book of the Twins +1' },
  { label: 'Brimstone Shout Grave Wand of Detection +1', value: 'Brimstone Shout Grave Wand of Detection +1' },
  { label: 'Brimstone Shout Grave Wand of Rage +1', value: 'Brimstone Shout Grave Wand of Rage +1' },
  { label: 'Carrion Glow Scimitar of Giants', value: 'Carrion Glow Scimitar of Giants' },
  { label: 'Carrion Glow Scimitar of Protection', value: 'Carrion Glow Scimitar of Protection' },
  { label: 'Carrion Glow Scimitar of Rage', value: 'Carrion Glow Scimitar of Rage' },
  { label: 'Carrion Roar Club of Reflection', value: 'Carrion Roar Club of Reflection' },
  { label: 'Carrion Root Quarterstaff of Brilliance', value: 'Carrion Root Quarterstaff of Brilliance' },
  { label: 'Carrion Sun Tome of Power', value: 'Carrion Sun Tome of Power' },
  { label: 'Carrion Tear Wand of Giants', value: 'Carrion Tear Wand of Giants' },
  { label: 'Carrion Tear Wand of the Twins', value: 'Carrion Tear Wand of the Twins' },
  { label: 'Carrion Whisper Ghost Wand of Titans', value: 'Carrion Whisper Ghost Wand of Titans' },
  { label: 'Cataclysm Bender Long Sword of Anger +1', value: 'Cataclysm Bender Long Sword of Anger +1' },
  { label: 'Cataclysm Bender Long Sword of Perfection +1', value: 'Cataclysm Bender Long Sword of Perfection +1' },
  { label: 'Cataclysm Bite Maul of Enlightenment +1', value: 'Cataclysm Bite Maul of Enlightenment +1' },
  { label: 'Cataclysm Bite Maul of Titans +1', value: 'Cataclysm Bite Maul of Titans +1' },
  { label: 'Cataclysm Grasp Katana of Rage +1', value: 'Cataclysm Grasp Katana of Rage +1' },
  { label: 'Cataclysm Grasp Katana of Skill +1', value: 'Cataclysm Grasp Katana of Skill +1' },
  { label: 'Cataclysm Moon Book of Detection +1', value: 'Cataclysm Moon Book of Detection +1' },
  { label: 'Cataclysm Peak Grimoire of Fury +1', value: 'Cataclysm Peak Grimoire of Fury +1' },
  { label: 'Cataclysm Peak Grimoire of Power +1', value: 'Cataclysm Peak Grimoire of Power +1' },
  { label: 'Cataclysm Peak Grimoire of the Fox +1', value: 'Cataclysm Peak Grimoire of the Fox +1' },
  { label: 'Cataclysm Shout Grave Wand of Brilliance +1', value: 'Cataclysm Shout Grave Wand of Brilliance +1' },
  { label: 'Cataclysm Shout Grave Wand of Giants +1', value: 'Cataclysm Shout Grave Wand of Giants +1' },
  { label: 'Cataclysm Shout Grave Wand of Protection +1', value: 'Cataclysm Shout Grave Wand of Protection +1' },
  { label: 'Cataclysm Shout Grave Wand of Skill +1', value: 'Cataclysm Shout Grave Wand of Skill +1' },
  { label: 'Cataclysm Shout Grave Wand of Vitriol +1', value: 'Cataclysm Shout Grave Wand of Vitriol +1' },
  { label: 'Corpse Glow Scimitar of Detection', value: 'Corpse Glow Scimitar of Detection' },
  { label: 'Corpse Roar Club of Enlightenment', value: 'Corpse Roar Club of Enlightenment' },
  { label: 'Corpse Root Quarterstaff of Detection', value: 'Corpse Root Quarterstaff of Detection' },
  { label: 'Corpse Root Quarterstaff of the Twins', value: 'Corpse Root Quarterstaff of the Twins' },
  { label: 'Corpse Root Quarterstaff of Vitriol', value: 'Corpse Root Quarterstaff of Vitriol' },
  { label: 'Corpse Sun Tome of the Fox', value: 'Corpse Sun Tome of the Fox' },
  { label: 'Corpse Sun Tome of Titans', value: 'Corpse Sun Tome of Titans' },
  { label: 'Corpse Tear Wand of Protection', value: 'Corpse Tear Wand of Protection' },
  { label: 'Corpse Tear Wand of Vitriol', value: 'Corpse Tear Wand of Vitriol' },
  { label: 'Corpse Whisper Ghost Wand of Anger', value: 'Corpse Whisper Ghost Wand of Anger' },
  { label: 'Corpse Whisper Ghost Wand of Power', value: 'Corpse Whisper Ghost Wand of Power' },
  { label: 'Corpse Whisper Ghost Wand of Titans', value: 'Corpse Whisper Ghost Wand of Titans' },
  { label: 'Corruption Bender Long Sword of Titans +1', value: 'Corruption Bender Long Sword of Titans +1' },
  { label: 'Corruption Bite Maul of Enlightenment +1', value: 'Corruption Bite Maul of Enlightenment +1' },
  { label: 'Corruption Bite Maul of Fury +1', value: 'Corruption Bite Maul of Fury +1' },
  { label: 'Corruption Grasp Katana of Brilliance +1', value: 'Corruption Grasp Katana of Brilliance +1' },
  { label: 'Corruption Moon Book of Brilliance +1', value: 'Corruption Moon Book of Brilliance +1' },
  { label: 'Corruption Peak Grimoire of Reflection +1', value: 'Corruption Peak Grimoire of Reflection +1' },
  { label: 'Corruption Peak Grimoire of Titans +1', value: 'Corruption Peak Grimoire of Titans +1' },
  { label: 'Corruption Shout Grave Wand of Giants +1', value: 'Corruption Shout Grave Wand of Giants +1' },
  { label: 'Death Glow Scimitar of the Twins', value: 'Death Glow Scimitar of the Twins' },
  { label: 'Death Roar Club of Fury', value: 'Death Roar Club of Fury' },
  { label: 'Death Roar Club of Perfection', value: 'Death Roar Club of Perfection' },
  { label: 'Death Root Quarterstaff of Brilliance', value: 'Death Root Quarterstaff of Brilliance' },
  { label: 'Death Root Quarterstaff of Protection', value: 'Death Root Quarterstaff of Protection' },
  { label: 'Death Sun Tome of Enlightenment', value: 'Death Sun Tome of Enlightenment' },
  { label: 'Death Tear Wand of Giants', value: 'Death Tear Wand of Giants' },
  { label: 'Death Tear Wand of Rage', value: 'Death Tear Wand of Rage' },
  { label: 'Death Whisper Ghost Wand of Enlightenment', value: 'Death Whisper Ghost Wand of Enlightenment' },
  { label: 'Death Whisper Ghost Wand of Fury', value: 'Death Whisper Ghost Wand of Fury' },
  { label: 'Demon Bender Long Sword of the Fox +1', value: 'Demon Bender Long Sword of the Fox +1' },
  { label: 'Demon Bite Maul of Anger +1', value: 'Demon Bite Maul of Anger +1' },
  { label: 'Demon Grasp Katana of Brilliance +1', value: 'Demon Grasp Katana of Brilliance +1' },
  { label: 'Demon Grasp Katana of Detection +1', value: 'Demon Grasp Katana of Detection +1' },
  { label: 'Demon Grasp Katana of Giants +1', value: 'Demon Grasp Katana of Giants +1' },
  { label: 'Demon Moon Book of Brilliance +1', value: 'Demon Moon Book of Brilliance +1' },
  { label: 'Demon Moon Book of Detection +1', value: 'Demon Moon Book of Detection +1' },
  { label: 'Demon Peak Grimoire of Fury +1', value: 'Demon Peak Grimoire of Fury +1' },
  { label: 'Demon Peak Grimoire of Reflection +1', value: 'Demon Peak Grimoire of Reflection +1' },
  { label: 'Demon Shout Grave Wand of Protection +1', value: 'Demon Shout Grave Wand of Protection +1' },
  { label: 'Demon Shout Grave Wand of Vitriol +1', value: 'Demon Shout Grave Wand of Vitriol +1' },
  { label: 'Dragon Roar Club of Anger', value: 'Dragon Roar Club of Anger' },
  { label: 'Dragon Roar Club of Perfection', value: 'Dragon Roar Club of Perfection' },
  { label: 'Dragon Root Quarterstaff of Skill', value: 'Dragon Root Quarterstaff of Skill' },
  { label: 'Dragon Root Quarterstaff of the Twins', value: 'Dragon Root Quarterstaff of the Twins' },
  { label: 'Dragon Sun Tome of Fury', value: 'Dragon Sun Tome of Fury' },
  { label: 'Dragon Sun Tome of Reflection', value: 'Dragon Sun Tome of Reflection' },
  { label: 'Dragon Sun Tome of the Fox', value: 'Dragon Sun Tome of the Fox' },
  { label: 'Dragon Tear Wand of Giants', value: 'Dragon Tear Wand of Giants' },
  { label: 'Dragon Whisper Ghost Wand of Perfection', value: 'Dragon Whisper Ghost Wand of Perfection' },
  { label: 'Dragon Whisper Ghost Wand of Reflection', value: 'Dragon Whisper Ghost Wand of Reflection' },
  { label: 'Dragon Whisper Ghost Wand of the Fox', value: 'Dragon Whisper Ghost Wand of the Fox' },
  { label: 'Dread Bender Long Sword of Titans +1', value: 'Dread Bender Long Sword of Titans +1' },
  { label: 'Dread Bite Maul of Anger +1', value: 'Dread Bite Maul of Anger +1' },
  { label: 'Dread Bite Maul of Enlightenment +1', value: 'Dread Bite Maul of Enlightenment +1' },
  { label: 'Dread Grasp Katana of Detection +1', value: 'Dread Grasp Katana of Detection +1' },
  { label: 'Dread Moon Book of Giants +1', value: 'Dread Moon Book of Giants +1' },
  { label: 'Dread Moon Book of the Twins +1', value: 'Dread Moon Book of the Twins +1' },
  { label: 'Dread Peak Grimoire of the Fox +1', value: 'Dread Peak Grimoire of the Fox +1' },
  { label: 'Dread Shout Grave Wand of Brilliance +1', value: 'Dread Shout Grave Wand of Brilliance +1' },
  { label: 'Dread Shout Grave Wand of Detection +1', value: 'Dread Shout Grave Wand of Detection +1' },
  { label: 'Dread Shout Grave Wand of the Twins +1', value: 'Dread Shout Grave Wand of the Twins +1' },
  { label: 'Dusk Glow Scimitar of Detection', value: 'Dusk Glow Scimitar of Detection' },
  { label: 'Dusk Glow Scimitar of Vitriol', value: 'Dusk Glow Scimitar of Vitriol' },
  { label: 'Dusk Roar Club of Perfection', value: 'Dusk Roar Club of Perfection' },
  { label: 'Dusk Roar Club of Power', value: 'Dusk Roar Club of Power' },
  { label: 'Dusk Roar Club of Reflection', value: 'Dusk Roar Club of Reflection' },
  { label: 'Dusk Root Quarterstaff of Giants', value: 'Dusk Root Quarterstaff of Giants' },
  { label: 'Dusk Root Quarterstaff of Skill', value: 'Dusk Root Quarterstaff of Skill' },
  { label: 'Dusk Root Quarterstaff of the Twins', value: 'Dusk Root Quarterstaff of the Twins' },
  { label: 'Dusk Root Quarterstaff of Vitriol', value: 'Dusk Root Quarterstaff of Vitriol' },
  { label: 'Dusk Sun Tome of Perfection', value: 'Dusk Sun Tome of Perfection' },
  { label: 'Dusk Sun Tome of the Fox', value: 'Dusk Sun Tome of the Fox' },
  { label: 'Dusk Tear Wand of Brilliance', value: 'Dusk Tear Wand of Brilliance' },
  { label: 'Dusk Tear Wand of Giants', value: 'Dusk Tear Wand of Giants' },
  { label: 'Dusk Tear Wand of Vitriol', value: 'Dusk Tear Wand of Vitriol' },
  { label: 'Dusk Whisper Ghost Wand of Power', value: 'Dusk Whisper Ghost Wand of Power' },
  { label: 'Dusk Whisper Ghost Wand of the Fox', value: 'Dusk Whisper Ghost Wand of the Fox' },
  { label: 'Eagle Bender Long Sword of Perfection +1', value: 'Eagle Bender Long Sword of Perfection +1' },
  { label: 'Eagle Bender Long Sword of Reflection +1', value: 'Eagle Bender Long Sword of Reflection +1' },
  { label: 'Eagle Bite Maul of Enlightenment +1', value: 'Eagle Bite Maul of Enlightenment +1' },
  { label: 'Eagle Bite Maul of Fury +1', value: 'Eagle Bite Maul of Fury +1' },
  { label: 'Eagle Bite Maul of Perfection +1', value: 'Eagle Bite Maul of Perfection +1' },
  { label: 'Eagle Moon Book of Brilliance +1', value: 'Eagle Moon Book of Brilliance +1' },
  { label: 'Eagle Moon Book of Detection +1', value: 'Eagle Moon Book of Detection +1' },
  { label: 'Eagle Moon Book of Giants +1', value: 'Eagle Moon Book of Giants +1' },
  { label: 'Eagle Moon Book of Protection +1', value: 'Eagle Moon Book of Protection +1' },
  { label: 'Eagle Moon Book of the Twins +1', value: 'Eagle Moon Book of the Twins +1' },
  { label: 'Eagle Peak Grimoire of Enlightenment +1', value: 'Eagle Peak Grimoire of Enlightenment +1' },
  { label: 'Fate Glow Scimitar of Vitriol', value: 'Fate Glow Scimitar of Vitriol' },
  { label: 'Fate Roar Club of the Fox', value: 'Fate Roar Club of the Fox' },
  { label: 'Fate Root Quarterstaff of Protection', value: 'Fate Root Quarterstaff of Protection' },
  { label: 'Fate Root Quarterstaff of the Twins', value: 'Fate Root Quarterstaff of the Twins' },
  { label: 'Fate Sun Tome of Anger', value: 'Fate Sun Tome of Anger' },
  { label: 'Fate Sun Tome of Perfection', value: 'Fate Sun Tome of Perfection' },
  { label: 'Fate Sun Tome of Reflection', value: 'Fate Sun Tome of Reflection' },
  { label: 'Fate Tear Wand of Brilliance', value: 'Fate Tear Wand of Brilliance' },
  { label: 'Fate Tear Wand of Skill', value: 'Fate Tear Wand of Skill' },
  { label: 'Fate Tear Wand of the Twins', value: 'Fate Tear Wand of the Twins' },
  { label: 'Fate Whisper Ghost Wand of Perfection', value: 'Fate Whisper Ghost Wand of Perfection' },
  { label: 'Fate Whisper Ghost Wand of Power', value: 'Fate Whisper Ghost Wand of Power' },
  { label: 'Fate Whisper Ghost Wand of the Fox', value: 'Fate Whisper Ghost Wand of the Fox' },
  { label: 'Foe Bender Long Sword of Anger +1', value: 'Foe Bender Long Sword of Anger +1' },
  { label: 'Foe Bender Long Sword of Fury +1', value: 'Foe Bender Long Sword of Fury +1' },
  { label: 'Foe Bender Long Sword of Titans +1', value: 'Foe Bender Long Sword of Titans +1' },
  { label: 'Foe Bite Maul of Fury +1', value: 'Foe Bite Maul of Fury +1' },
  { label: 'Foe Bite Maul of the Fox +1', value: 'Foe Bite Maul of the Fox +1' },
  { label: 'Foe Grasp Katana of Protection +1', value: 'Foe Grasp Katana of Protection +1' },
  { label: 'Foe Grasp Katana of Skill +1', value: 'Foe Grasp Katana of Skill +1' },
  { label: 'Foe Grasp Katana of the Twins +1', value: 'Foe Grasp Katana of the Twins +1' },
  { label: 'Foe Peak Grimoire of Fury +1', value: 'Foe Peak Grimoire of Fury +1' },
  { label: 'Foe Peak Grimoire of Perfection +1', value: 'Foe Peak Grimoire of Perfection +1' },
  { label: 'Foe Peak Grimoire of Power +1', value: 'Foe Peak Grimoire of Power +1' },
  { label: 'Foe Peak Grimoire of the Fox +1', value: 'Foe Peak Grimoire of the Fox +1' },
  { label: 'Foe Shout Grave Wand of Giants +1', value: 'Foe Shout Grave Wand of Giants +1' },
  { label: 'Foe Shout Grave Wand of the Twins +1', value: 'Foe Shout Grave Wand of the Twins +1' },
  { label: 'Ghoul Glow Scimitar of Brilliance', value: 'Ghoul Glow Scimitar of Brilliance' },
  { label: 'Ghoul Glow Scimitar of Skill', value: 'Ghoul Glow Scimitar of Skill' },
  { label: 'Ghoul Glow Scimitar of the Twins', value: 'Ghoul Glow Scimitar of the Twins' },
  { label: 'Ghoul Roar Club of Reflection', value: 'Ghoul Roar Club of Reflection' },
  { label: 'Ghoul Root Quarterstaff of Brilliance', value: 'Ghoul Root Quarterstaff of Brilliance' },
  { label: 'Ghoul Root Quarterstaff of Giants', value: 'Ghoul Root Quarterstaff of Giants' },
  { label: 'Ghoul Sun Tome of Anger', value: 'Ghoul Sun Tome of Anger' },
  { label: 'Ghoul Sun Tome of Perfection', value: 'Ghoul Sun Tome of Perfection' },
  { label: 'Ghoul Sun Tome of Titans', value: 'Ghoul Sun Tome of Titans' },
  { label: 'Ghoul Tear Wand of Rage', value: 'Ghoul Tear Wand of Rage' },
  { label: 'Ghoul Tear Wand of Vitriol', value: 'Ghoul Tear Wand of Vitriol' },
  { label: 'Ghoul Whisper Ghost Wand of Anger', value: 'Ghoul Whisper Ghost Wand of Anger' },
  { label: 'Ghoul Whisper Ghost Wand of Fury', value: 'Ghoul Whisper Ghost Wand of Fury' },
  { label: 'Ghoul Whisper Ghost Wand of Perfection', value: 'Ghoul Whisper Ghost Wand of Perfection' },
  { label: 'Ghoul Whisper Ghost Wand of Titans', value: 'Ghoul Whisper Ghost Wand of Titans' },
  { label: 'Gloom Bender Long Sword of Enlightenment +1', value: 'Gloom Bender Long Sword of Enlightenment +1' },
  { label: 'Gloom Bender Long Sword of Fury +1', value: 'Gloom Bender Long Sword of Fury +1' },
  { label: 'Gloom Bender Long Sword of Power +1', value: 'Gloom Bender Long Sword of Power +1' },
  { label: 'Gloom Bender Long Sword of Reflection +1', value: 'Gloom Bender Long Sword of Reflection +1' },
  { label: 'Gloom Bite Maul of Enlightenment +1', value: 'Gloom Bite Maul of Enlightenment +1' },
  { label: 'Gloom Bite Maul of Titans +1', value: 'Gloom Bite Maul of Titans +1' },
  { label: 'Gloom Grasp Katana of Skill +1', value: 'Gloom Grasp Katana of Skill +1' },
  { label: 'Gloom Grasp Katana of the Twins +1', value: 'Gloom Grasp Katana of the Twins +1' },
  { label: 'Gloom Moon Book of Detection +1', value: 'Gloom Moon Book of Detection +1' },
  { label: 'Gloom Peak Grimoire of Enlightenment +1', value: 'Gloom Peak Grimoire of Enlightenment +1' },
  { label: 'Gloom Peak Grimoire of the Fox +1', value: 'Gloom Peak Grimoire of the Fox +1' },
  { label: 'Gloom Shout Grave Wand of Brilliance +1', value: 'Gloom Shout Grave Wand of Brilliance +1' },
  { label: 'Gloom Shout Grave Wand of Detection +1', value: 'Gloom Shout Grave Wand of Detection +1' },
  { label: 'Golem Glow Scimitar of Brilliance', value: 'Golem Glow Scimitar of Brilliance' },
  { label: 'Golem Glow Scimitar of the Twins', value: 'Golem Glow Scimitar of the Twins' },
  { label: 'Golem Roar Club of Fury', value: 'Golem Roar Club of Fury' },
  { label: 'Golem Roar Club of Power', value: 'Golem Roar Club of Power' },
  { label: 'Golem Roar Club of Reflection', value: 'Golem Roar Club of Reflection' },
  { label: 'Golem Root Quarterstaff of Rage', value: 'Golem Root Quarterstaff of Rage' },
  { label: 'Golem Sun Tome of Anger', value: 'Golem Sun Tome of Anger' },
  { label: 'Golem Sun Tome of the Fox', value: 'Golem Sun Tome of the Fox' },
  { label: 'Golem Tear Wand of Detection', value: 'Golem Tear Wand of Detection' },
  { label: 'Golem Tear Wand of the Twins', value: 'Golem Tear Wand of the Twins' },
  { label: 'Golem Whisper Ghost Wand of Perfection', value: 'Golem Whisper Ghost Wand of Perfection' },
  { label: 'Golem Whisper Ghost Wand of Power', value: 'Golem Whisper Ghost Wand of Power' },
  { label: 'Grim Bite Maul of Anger +1', value: 'Grim Bite Maul of Anger +1' },
  { label: 'Grim Bite Maul of Reflection +1', value: 'Grim Bite Maul of Reflection +1' },
  { label: 'Grim Grasp Katana of Brilliance +1', value: 'Grim Grasp Katana of Brilliance +1' },
  { label: 'Grim Grasp Katana of Rage +1', value: 'Grim Grasp Katana of Rage +1' },
  { label: 'Grim Grasp Katana of Skill +1', value: 'Grim Grasp Katana of Skill +1' },
  { label: 'Grim Moon Book of Brilliance +1', value: 'Grim Moon Book of Brilliance +1' },
  { label: 'Grim Moon Book of Giants +1', value: 'Grim Moon Book of Giants +1' },
  { label: 'Grim Moon Book of Skill +1', value: 'Grim Moon Book of Skill +1' },
  { label: 'Grim Peak Grimoire of Anger +1', value: 'Grim Peak Grimoire of Anger +1' },
  { label: 'Grim Peak Grimoire of the Fox +1', value: 'Grim Peak Grimoire of the Fox +1' },
  { label: 'Grim Shout Grave Wand of Detection +1', value: 'Grim Shout Grave Wand of Detection +1' },
  { label: 'Havoc Glow Scimitar of Brilliance', value: 'Havoc Glow Scimitar of Brilliance' },
  { label: 'Havoc Glow Scimitar of Giants', value: 'Havoc Glow Scimitar of Giants' },
  { label: 'Havoc Roar Club of Enlightenment', value: 'Havoc Roar Club of Enlightenment' },
  { label: 'Havoc Roar Club of Fury', value: 'Havoc Roar Club of Fury' },
  { label: 'Havoc Roar Club of Perfection', value: 'Havoc Roar Club of Perfection' },
  { label: 'Havoc Roar Club of Titans', value: 'Havoc Roar Club of Titans' },
  { label: 'Havoc Root Quarterstaff of Protection', value: 'Havoc Root Quarterstaff of Protection' },
  { label: 'Havoc Root Quarterstaff of the Twins', value: 'Havoc Root Quarterstaff of the Twins' },
  { label: 'Havoc Root Quarterstaff of Vitriol', value: 'Havoc Root Quarterstaff of Vitriol' },
  { label: 'Havoc Sun Tome of Power', value: 'Havoc Sun Tome of Power' },
  { label: 'Havoc Tear Wand of Detection', value: 'Havoc Tear Wand of Detection' },
  { label: 'Havoc Tear Wand of Rage', value: 'Havoc Tear Wand of Rage' },
  { label: 'Havoc Tear Wand of the Twins', value: 'Havoc Tear Wand of the Twins' },
  { label: 'Havoc Whisper Ghost Wand of Anger', value: 'Havoc Whisper Ghost Wand of Anger' },
  { label: 'Havoc Whisper Ghost Wand of Enlightenment', value: 'Havoc Whisper Ghost Wand of Enlightenment' },
  { label: 'Honour Bender Long Sword of Power +1', value: 'Honour Bender Long Sword of Power +1' },
  { label: 'Honour Bite Maul of the Fox +1', value: 'Honour Bite Maul of the Fox +1' },
  { label: 'Honour Bite Maul of Titans +1', value: 'Honour Bite Maul of Titans +1' },
  { label: 'Honour Grasp Katana of Detection +1', value: 'Honour Grasp Katana of Detection +1' },
  { label: 'Honour Peak Grimoire of Enlightenment +1', value: 'Honour Peak Grimoire of Enlightenment +1' },
  { label: 'Honour Peak Grimoire of the Fox +1', value: 'Honour Peak Grimoire of the Fox +1' },
  { label: 'Honour Shout Grave Wand of the Twins +1', value: 'Honour Shout Grave Wand of the Twins +1' },
  { label: 'Honour Shout Grave Wand of Vitriol +1', value: 'Honour Shout Grave Wand of Vitriol +1' },
  { label: 'Hypnotic Roar Club of Fury', value: 'Hypnotic Roar Club of Fury' },
  { label: 'Hypnotic Root Quarterstaff of Detection', value: 'Hypnotic Root Quarterstaff of Detection' },
  { label: 'Hypnotic Root Quarterstaff of Rage', value: 'Hypnotic Root Quarterstaff of Rage' },
  { label: 'Hypnotic Root Quarterstaff of the Twins', value: 'Hypnotic Root Quarterstaff of the Twins' },
  { label: 'Hypnotic Tear Wand of Brilliance', value: 'Hypnotic Tear Wand of Brilliance' },
  { label: 'Hypnotic Tear Wand of Detection', value: 'Hypnotic Tear Wand of Detection' },
  { label: 'Hypnotic Whisper Ghost Wand of Power', value: 'Hypnotic Whisper Ghost Wand of Power' },
  { label: 'Hypnotic Whisper Ghost Wand of Titans', value: 'Hypnotic Whisper Ghost Wand of Titans' },
  { label: 'Kraken Bender Long Sword of Anger +1', value: 'Kraken Bender Long Sword of Anger +1' },
  { label: 'Kraken Bite Maul of Perfection +1', value: 'Kraken Bite Maul of Perfection +1' },
  { label: 'Kraken Bite Maul of Reflection +1', value: 'Kraken Bite Maul of Reflection +1' },
  { label: 'Kraken Grasp Katana of Giants +1', value: 'Kraken Grasp Katana of Giants +1' },
  { label: 'Kraken Grasp Katana of Protection +1', value: 'Kraken Grasp Katana of Protection +1' },
  { label: 'Kraken Moon Book of Brilliance +1', value: 'Kraken Moon Book of Brilliance +1' },
  { label: 'Kraken Moon Book of Protection +1', value: 'Kraken Moon Book of Protection +1' },
  { label: 'Kraken Moon Book of Skill +1', value: 'Kraken Moon Book of Skill +1' },
  { label: 'Kraken Peak Grimoire of Fury +1', value: 'Kraken Peak Grimoire of Fury +1' },
  { label: 'Kraken Shout Grave Wand of Brilliance +1', value: 'Kraken Shout Grave Wand of Brilliance +1' },
  { label: 'Kraken Shout Grave Wand of Protection +1', value: 'Kraken Shout Grave Wand of Protection +1' },
  { label: 'Kraken Shout Grave Wand of Rage +1', value: 'Kraken Shout Grave Wand of Rage +1' },
  { label: 'Kraken Shout Grave Wand of the Twins +1', value: 'Kraken Shout Grave Wand of the Twins +1' },
  { label: "Light's Glow Scimitar of the Twins", value: "Light's Glow Scimitar of the Twins" },
  { label: "Light's Roar Club of Anger", value: "Light's Roar Club of Anger" },
  { label: "Light's Roar Club of Reflection", value: "Light's Roar Club of Reflection" },
  { label: "Light's Roar Club of the Fox", value: "Light's Roar Club of the Fox" },
  { label: "Light's Root Quarterstaff of Rage", value: "Light's Root Quarterstaff of Rage" },
  { label: "Light's Sun Tome of Perfection", value: "Light's Sun Tome of Perfection" },
  { label: "Light's Sun Tome of Power", value: "Light's Sun Tome of Power" },
  { label: "Light's Tear Wand of Brilliance", value: "Light's Tear Wand of Brilliance" },
  { label: "Light's Tear Wand of Detection", value: "Light's Tear Wand of Detection" },
  { label: "Light's Tear Wand of Giants", value: "Light's Tear Wand of Giants" },
  { label: "Light's Tear Wand of Skill", value: "Light's Tear Wand of Skill" },
  { label: "Light's Tear Wand of Vitriol", value: "Light's Tear Wand of Vitriol" },
  { label: "Light's Whisper Ghost Wand of Fury", value: "Light's Whisper Ghost Wand of Fury" },
  { label: 'Maelstrom Roar Club of Enlightenment', value: 'Maelstrom Roar Club of Enlightenment' },
  { label: 'Maelstrom Roar Club of Titans', value: 'Maelstrom Roar Club of Titans' },
  { label: 'Maelstrom Root Quarterstaff of Skill', value: 'Maelstrom Root Quarterstaff of Skill' },
  { label: 'Maelstrom Sun Tome of Anger', value: 'Maelstrom Sun Tome of Anger' },
  { label: 'Maelstrom Sun Tome of Enlightenment', value: 'Maelstrom Sun Tome of Enlightenment' },
  { label: 'Maelstrom Sun Tome of Fury', value: 'Maelstrom Sun Tome of Fury' },
  { label: 'Maelstrom Sun Tome of Perfection', value: 'Maelstrom Sun Tome of Perfection' },
  { label: 'Maelstrom Tear Wand of the Twins', value: 'Maelstrom Tear Wand of the Twins' },
  { label: 'Maelstrom Whisper Ghost Wand of the Fox', value: 'Maelstrom Whisper Ghost Wand of the Fox' },
  { label: 'Mind Bender Long Sword of Fury +1', value: 'Mind Bender Long Sword of Fury +1' },
  { label: 'Mind Bender Long Sword of Reflection +1', value: 'Mind Bender Long Sword of Reflection +1' },
  { label: 'Mind Bite Maul of Perfection +1', value: 'Mind Bite Maul of Perfection +1' },
  { label: 'Mind Grasp Katana of Detection +1', value: 'Mind Grasp Katana of Detection +1' },
  { label: 'Mind Grasp Katana of Rage +1', value: 'Mind Grasp Katana of Rage +1' },
  { label: 'Mind Grasp Katana of Skill +1', value: 'Mind Grasp Katana of Skill +1' },
  { label: 'Mind Moon Book of Brilliance +1', value: 'Mind Moon Book of Brilliance +1' },
  { label: 'Mind Moon Book of Detection +1', value: 'Mind Moon Book of Detection +1' },
  { label: 'Mind Peak Grimoire of Reflection +1', value: 'Mind Peak Grimoire of Reflection +1' },
  { label: 'Mind Shout Grave Wand of Brilliance +1', value: 'Mind Shout Grave Wand of Brilliance +1' },
  { label: 'Mind Shout Grave Wand of Detection +1', value: 'Mind Shout Grave Wand of Detection +1' },
  { label: 'Mind Shout Grave Wand of Skill +1', value: 'Mind Shout Grave Wand of Skill +1' },
  { label: 'Mind Shout Grave Wand of the Twins +1', value: 'Mind Shout Grave Wand of the Twins +1' },
  { label: 'Mind Shout Grave Wand of Vitriol +1', value: 'Mind Shout Grave Wand of Vitriol +1' },
  { label: 'Morbid Glow Scimitar of Skill', value: 'Morbid Glow Scimitar of Skill' },
  { label: 'Morbid Glow Scimitar of the Twins', value: 'Morbid Glow Scimitar of the Twins' },
  { label: 'Morbid Roar Club of Power', value: 'Morbid Roar Club of Power' },
  { label: 'Morbid Root Quarterstaff of Brilliance', value: 'Morbid Root Quarterstaff of Brilliance' },
  { label: 'Morbid Root Quarterstaff of Protection', value: 'Morbid Root Quarterstaff of Protection' },
  { label: 'Morbid Root Quarterstaff of the Twins', value: 'Morbid Root Quarterstaff of the Twins' },
  { label: 'Morbid Sun Tome of Power', value: 'Morbid Sun Tome of Power' },
  { label: 'Morbid Tear Wand of Detection', value: 'Morbid Tear Wand of Detection' },
  { label: 'Morbid Tear Wand of Protection', value: 'Morbid Tear Wand of Protection' },
  { label: 'Morbid Whisper Ghost Wand of Titans', value: 'Morbid Whisper Ghost Wand of Titans' },
  { label: 'Oblivion Bender Long Sword of Anger +1', value: 'Oblivion Bender Long Sword of Anger +1' },
  { label: 'Oblivion Grasp Katana of Brilliance +1', value: 'Oblivion Grasp Katana of Brilliance +1' },
  { label: 'Oblivion Grasp Katana of Giants +1', value: 'Oblivion Grasp Katana of Giants +1' },
  { label: 'Oblivion Grasp Katana of the Twins +1', value: 'Oblivion Grasp Katana of the Twins +1' },
  { label: 'Oblivion Grasp Katana of Vitriol +1', value: 'Oblivion Grasp Katana of Vitriol +1' },
  { label: 'Oblivion Moon Book of Detection +1', value: 'Oblivion Moon Book of Detection +1' },
  { label: 'Oblivion Moon Book of the Twins +1', value: 'Oblivion Moon Book of the Twins +1' },
  { label: 'Oblivion Peak Grimoire of Anger +1', value: 'Oblivion Peak Grimoire of Anger +1' },
  { label: 'Oblivion Shout Grave Wand of Detection +1', value: 'Oblivion Shout Grave Wand of Detection +1' },
  { label: 'Pain Glow Scimitar of Brilliance', value: 'Pain Glow Scimitar of Brilliance' },
  { label: 'Pain Glow Scimitar of Detection', value: 'Pain Glow Scimitar of Detection' },
  { label: 'Pain Glow Scimitar of Giants', value: 'Pain Glow Scimitar of Giants' },
  { label: 'Pain Glow Scimitar of Rage', value: 'Pain Glow Scimitar of Rage' },
  { label: 'Pain Glow Scimitar of Vitriol', value: 'Pain Glow Scimitar of Vitriol' },
  { label: 'Pain Roar Club of Anger', value: 'Pain Roar Club of Anger' },
  { label: 'Pain Root Quarterstaff of the Twins', value: 'Pain Root Quarterstaff of the Twins' },
  { label: 'Pain Sun Tome of Fury', value: 'Pain Sun Tome of Fury' },
  { label: 'Pain Sun Tome of Titans', value: 'Pain Sun Tome of Titans' },
  { label: 'Pain Tear Wand of the Twins', value: 'Pain Tear Wand of the Twins' },
  { label: 'Pain Whisper Ghost Wand of Anger', value: 'Pain Whisper Ghost Wand of Anger' },
  { label: 'Pain Whisper Ghost Wand of Perfection', value: 'Pain Whisper Ghost Wand of Perfection' },
  { label: 'Pain Whisper Ghost Wand of Power', value: 'Pain Whisper Ghost Wand of Power' },
  { label: 'Pain Whisper Ghost Wand of the Fox', value: 'Pain Whisper Ghost Wand of the Fox' },
  { label: 'Pandemonium Bender Long Sword of Power +1', value: 'Pandemonium Bender Long Sword of Power +1' },
  { label: 'Pandemonium Bender Long Sword of Reflection +1', value: 'Pandemonium Bender Long Sword of Reflection +1' },
  { label: 'Pandemonium Bender Long Sword of Titans +1', value: 'Pandemonium Bender Long Sword of Titans +1' },
  { label: 'Pandemonium Bite Maul of Enlightenment +1', value: 'Pandemonium Bite Maul of Enlightenment +1' },
  { label: 'Pandemonium Bite Maul of the Fox +1', value: 'Pandemonium Bite Maul of the Fox +1' },
  { label: 'Pandemonium Grasp Katana of Giants +1', value: 'Pandemonium Grasp Katana of Giants +1' },
  { label: 'Pandemonium Moon Book of Brilliance +1', value: 'Pandemonium Moon Book of Brilliance +1' },
  { label: 'Pandemonium Moon Book of Skill +1', value: 'Pandemonium Moon Book of Skill +1' },
  { label: 'Pandemonium Peak Grimoire of Power +1', value: 'Pandemonium Peak Grimoire of Power +1' },
  { label: 'Pandemonium Peak Grimoire of Titans +1', value: 'Pandemonium Peak Grimoire of Titans +1' },
  { label: 'Plague Glow Scimitar of Detection', value: 'Plague Glow Scimitar of Detection' },
  { label: 'Plague Roar Club of Enlightenment', value: 'Plague Roar Club of Enlightenment' },
  { label: 'Plague Sun Tome of Anger', value: 'Plague Sun Tome of Anger' },
  { label: 'Plague Sun Tome of Enlightenment', value: 'Plague Sun Tome of Enlightenment' },
  { label: 'Plague Tear Wand of Vitriol', value: 'Plague Tear Wand of Vitriol' },
  { label: 'Plague Whisper Ghost Wand of Fury', value: 'Plague Whisper Ghost Wand of Fury' },
  { label: 'Plague Whisper Ghost Wand of the Fox', value: 'Plague Whisper Ghost Wand of the Fox' },
  { label: 'Rage Bender Long Sword of Anger +1', value: 'Rage Bender Long Sword of Anger +1' },
  { label: 'Rage Bender Long Sword of Titans +1', value: 'Rage Bender Long Sword of Titans +1' },
  { label: 'Rage Bite Maul of Anger +1', value: 'Rage Bite Maul of Anger +1' },
  { label: 'Rage Bite Maul of Fury +1', value: 'Rage Bite Maul of Fury +1' },
  { label: 'Rage Bite Maul of Titans +1', value: 'Rage Bite Maul of Titans +1' },
  { label: 'Rage Grasp Katana of Giants +1', value: 'Rage Grasp Katana of Giants +1' },
  { label: 'Rage Moon Book of Brilliance +1', value: 'Rage Moon Book of Brilliance +1' },
  { label: 'Rage Moon Book of Protection +1', value: 'Rage Moon Book of Protection +1' },
  { label: 'Rage Moon Book of Vitriol +1', value: 'Rage Moon Book of Vitriol +1' },
  { label: 'Rage Peak Grimoire of Anger +1', value: 'Rage Peak Grimoire of Anger +1' },
  { label: 'Rage Peak Grimoire of Titans +1', value: 'Rage Peak Grimoire of Titans +1' },
  { label: 'Rage Shout Grave Wand of Brilliance +1', value: 'Rage Shout Grave Wand of Brilliance +1' },
  { label: 'Rage Shout Grave Wand of Giants +1', value: 'Rage Shout Grave Wand of Giants +1' },
  { label: 'Rage Shout Grave Wand of Rage +1', value: 'Rage Shout Grave Wand of Rage +1' },
  { label: 'Rune Glow Scimitar of Vitriol', value: 'Rune Glow Scimitar of Vitriol' },
  { label: 'Rune Roar Club of the Fox', value: 'Rune Roar Club of the Fox' },
  { label: 'Rune Root Quarterstaff of Protection', value: 'Rune Root Quarterstaff of Protection' },
  { label: 'Rune Sun Tome of Fury', value: 'Rune Sun Tome of Fury' },
  { label: 'Rune Sun Tome of Reflection', value: 'Rune Sun Tome of Reflection' },
  { label: 'Rune Tear Wand of Giants', value: 'Rune Tear Wand of Giants' },
  { label: 'Rune Whisper Ghost Wand of Anger', value: 'Rune Whisper Ghost Wand of Anger' },
  { label: 'Rune Whisper Ghost Wand of Enlightenment', value: 'Rune Whisper Ghost Wand of Enlightenment' },
  { label: 'Rune Whisper Ghost Wand of Power', value: 'Rune Whisper Ghost Wand of Power' },
  { label: 'Shimmering Bender Long Sword of Power +1', value: 'Shimmering Bender Long Sword of Power +1' },
  { label: 'Shimmering Bender Long Sword of Titans +1', value: 'Shimmering Bender Long Sword of Titans +1' },
  { label: 'Shimmering Bite Maul of Enlightenment +1', value: 'Shimmering Bite Maul of Enlightenment +1' },
  { label: 'Shimmering Bite Maul of Fury +1', value: 'Shimmering Bite Maul of Fury +1' },
  { label: 'Shimmering Grasp Katana of Detection +1', value: 'Shimmering Grasp Katana of Detection +1' },
  { label: 'Shimmering Grasp Katana of Giants +1', value: 'Shimmering Grasp Katana of Giants +1' },
  { label: 'Shimmering Grasp Katana of the Twins +1', value: 'Shimmering Grasp Katana of the Twins +1' },
  { label: 'Shimmering Peak Grimoire of Enlightenment +1', value: 'Shimmering Peak Grimoire of Enlightenment +1' },
  { label: 'Shimmering Peak Grimoire of Perfection +1', value: 'Shimmering Peak Grimoire of Perfection +1' },
  { label: 'Shimmering Shout Grave Wand of Vitriol +1', value: 'Shimmering Shout Grave Wand of Vitriol +1' },
  { label: 'Skull Bender Long Sword of Enlightenment +1', value: 'Skull Bender Long Sword of Enlightenment +1' },
  { label: 'Skull Bite Maul of Power +1', value: 'Skull Bite Maul of Power +1' },
  { label: 'Skull Bite Maul of Reflection +1', value: 'Skull Bite Maul of Reflection +1' },
  { label: 'Skull Grasp Katana of Giants +1', value: 'Skull Grasp Katana of Giants +1' },
  { label: 'Skull Grasp Katana of Vitriol +1', value: 'Skull Grasp Katana of Vitriol +1' },
  { label: 'Skull Moon Book of Skill +1', value: 'Skull Moon Book of Skill +1' },
  { label: 'Skull Peak Grimoire of Titans +1', value: 'Skull Peak Grimoire of Titans +1' },
  { label: 'Skull Shout Grave Wand of Detection +1', value: 'Skull Shout Grave Wand of Detection +1' },
  { label: 'Skull Shout Grave Wand of Protection +1', value: 'Skull Shout Grave Wand of Protection +1' },
  { label: 'Skull Shout Grave Wand of the Twins +1', value: 'Skull Shout Grave Wand of the Twins +1' },
  { label: 'Sorrow Bender Long Sword of the Fox +1', value: 'Sorrow Bender Long Sword of the Fox +1' },
  { label: 'Sorrow Bite Maul of Anger +1', value: 'Sorrow Bite Maul of Anger +1' },
  { label: 'Sorrow Bite Maul of Fury +1', value: 'Sorrow Bite Maul of Fury +1' },
  { label: 'Sorrow Bite Maul of Reflection +1', value: 'Sorrow Bite Maul of Reflection +1' },
  { label: 'Sorrow Grasp Katana of Detection +1', value: 'Sorrow Grasp Katana of Detection +1' },
  { label: 'Sorrow Grasp Katana of Protection +1', value: 'Sorrow Grasp Katana of Protection +1' },
  { label: 'Sorrow Moon Book of Giants +1', value: 'Sorrow Moon Book of Giants +1' },
  { label: 'Sorrow Moon Book of Skill +1', value: 'Sorrow Moon Book of Skill +1' },
  { label: 'Sorrow Moon Book of the Twins +1', value: 'Sorrow Moon Book of the Twins +1' },
  { label: 'Sorrow Peak Grimoire of Enlightenment +1', value: 'Sorrow Peak Grimoire of Enlightenment +1' },
  { label: 'Sorrow Shout Grave Wand of Giants +1', value: 'Sorrow Shout Grave Wand of Giants +1' },
  { label: 'Sorrow Shout Grave Wand of Skill +1', value: 'Sorrow Shout Grave Wand of Skill +1' },
  { label: 'Soul Roar Club of the Fox', value: 'Soul Roar Club of the Fox' },
  { label: 'Soul Root Quarterstaff of Brilliance', value: 'Soul Root Quarterstaff of Brilliance' },
  { label: 'Soul Sun Tome of Power', value: 'Soul Sun Tome of Power' },
  { label: 'Soul Sun Tome of Reflection', value: 'Soul Sun Tome of Reflection' },
  { label: 'Soul Tear Wand of Protection', value: 'Soul Tear Wand of Protection' },
  { label: 'Soul Tear Wand of the Twins', value: 'Soul Tear Wand of the Twins' },
  { label: 'Soul Whisper Ghost Wand of the Fox', value: 'Soul Whisper Ghost Wand of the Fox' },
  { label: 'Storm Glow Scimitar of Giants', value: 'Storm Glow Scimitar of Giants' },
  { label: 'Storm Roar Club of Anger', value: 'Storm Roar Club of Anger' },
  { label: 'Storm Roar Club of Enlightenment', value: 'Storm Roar Club of Enlightenment' },
  { label: 'Storm Root Quarterstaff of Skill', value: 'Storm Root Quarterstaff of Skill' },
  { label: 'Storm Sun Tome of Enlightenment', value: 'Storm Sun Tome of Enlightenment' },
  { label: 'Storm Sun Tome of Fury', value: 'Storm Sun Tome of Fury' },
  { label: 'Storm Sun Tome of the Fox', value: 'Storm Sun Tome of the Fox' },
  { label: 'Storm Tear Wand of Skill', value: 'Storm Tear Wand of Skill' },
  { label: 'Storm Whisper Ghost Wand of Enlightenment', value: 'Storm Whisper Ghost Wand of Enlightenment' },
  { label: 'Storm Whisper Ghost Wand of Reflection', value: 'Storm Whisper Ghost Wand of Reflection' },
  { label: 'Tempest Bender Long Sword of Anger +1', value: 'Tempest Bender Long Sword of Anger +1' },
  { label: 'Tempest Bender Long Sword of Fury +1', value: 'Tempest Bender Long Sword of Fury +1' },
  { label: 'Tempest Bender Long Sword of Perfection +1', value: 'Tempest Bender Long Sword of Perfection +1' },
  { label: 'Tempest Grasp Katana of Giants +1', value: 'Tempest Grasp Katana of Giants +1' },
  { label: 'Tempest Grasp Katana of Protection +1', value: 'Tempest Grasp Katana of Protection +1' },
  { label: 'Tempest Grasp Katana of the Twins +1', value: 'Tempest Grasp Katana of the Twins +1' },
  { label: 'Tempest Grasp Katana of Vitriol +1', value: 'Tempest Grasp Katana of Vitriol +1' },
  { label: 'Tempest Moon Book of Rage +1', value: 'Tempest Moon Book of Rage +1' },
  { label: 'Tempest Moon Book of the Twins +1', value: 'Tempest Moon Book of the Twins +1' },
  { label: 'Tempest Peak Grimoire of Anger +1', value: 'Tempest Peak Grimoire of Anger +1' },
  { label: 'Tempest Shout Grave Wand of Brilliance +1', value: 'Tempest Shout Grave Wand of Brilliance +1' },
  { label: 'Tempest Shout Grave Wand of Giants +1', value: 'Tempest Shout Grave Wand of Giants +1' },
  { label: 'Tempest Shout Grave Wand of Protection +1', value: 'Tempest Shout Grave Wand of Protection +1' },
  { label: 'Tempest Shout Grave Wand of Rage +1', value: 'Tempest Shout Grave Wand of Rage +1' },
  { label: 'Tempest Shout Grave Wand of Vitriol +1', value: 'Tempest Shout Grave Wand of Vitriol +1' },
  { label: 'Vengeance Glow Scimitar of Skill', value: 'Vengeance Glow Scimitar of Skill' },
  { label: 'Vengeance Root Quarterstaff of Detection', value: 'Vengeance Root Quarterstaff of Detection' },
  { label: 'Vengeance Root Quarterstaff of Skill', value: 'Vengeance Root Quarterstaff of Skill' },
  { label: 'Vengeance Sun Tome of Anger', value: 'Vengeance Sun Tome of Anger' },
  { label: 'Vengeance Sun Tome of Perfection', value: 'Vengeance Sun Tome of Perfection' },
  { label: 'Vengeance Sun Tome of the Fox', value: 'Vengeance Sun Tome of the Fox' },
  { label: 'Vengeance Tear Wand of Brilliance', value: 'Vengeance Tear Wand of Brilliance' },
  { label: 'Vengeance Tear Wand of Detection', value: 'Vengeance Tear Wand of Detection' },
  { label: 'Vengeance Tear Wand of Protection', value: 'Vengeance Tear Wand of Protection' },
  { label: 'Vengeance Tear Wand of Skill', value: 'Vengeance Tear Wand of Skill' },
  { label: 'Vengeance Whisper Ghost Wand of Anger', value: 'Vengeance Whisper Ghost Wand of Anger' },
  { label: 'Vengeance Whisper Ghost Wand of the Fox', value: 'Vengeance Whisper Ghost Wand of the Fox' },
  { label: 'Victory Bender Long Sword of Fury +1', value: 'Victory Bender Long Sword of Fury +1' },
  { label: 'Victory Bender Long Sword of Reflection +1', value: 'Victory Bender Long Sword of Reflection +1' },
  { label: 'Victory Bite Maul of Enlightenment +1', value: 'Victory Bite Maul of Enlightenment +1' },
  { label: 'Victory Grasp Katana of Giants +1', value: 'Victory Grasp Katana of Giants +1' },
  { label: 'Victory Moon Book of Brilliance +1', value: 'Victory Moon Book of Brilliance +1' },
  { label: 'Victory Moon Book of Giants +1', value: 'Victory Moon Book of Giants +1' },
  { label: 'Victory Moon Book of Skill +1', value: 'Victory Moon Book of Skill +1' },
  { label: 'Victory Peak Grimoire of Enlightenment +1', value: 'Victory Peak Grimoire of Enlightenment +1' },
  { label: 'Victory Peak Grimoire of Reflection +1', value: 'Victory Peak Grimoire of Reflection +1' },
  { label: 'Vortex Glow Scimitar of Brilliance', value: 'Vortex Glow Scimitar of Brilliance' },
  { label: 'Vortex Roar Club of Perfection', value: 'Vortex Roar Club of Perfection' },
  { label: 'Vortex Roar Club of Titans', value: 'Vortex Roar Club of Titans' },
  { label: 'Vortex Root Quarterstaff of Detection', value: 'Vortex Root Quarterstaff of Detection' },
  { label: 'Vortex Root Quarterstaff of Protection', value: 'Vortex Root Quarterstaff of Protection' },
  { label: 'Vortex Sun Tome of Titans', value: 'Vortex Sun Tome of Titans' },
  { label: 'Vortex Tear Wand of Skill', value: 'Vortex Tear Wand of Skill' },
  { label: 'Vortex Tear Wand of the Twins', value: 'Vortex Tear Wand of the Twins' },
  { label: 'Vortex Whisper Ghost Wand of the Fox', value: 'Vortex Whisper Ghost Wand of the Fox' },
  { label: 'Woe Bite Maul of Anger +1', value: 'Woe Bite Maul of Anger +1' },
  { label: 'Woe Bite Maul of Perfection +1', value: 'Woe Bite Maul of Perfection +1' },
  { label: 'Woe Peak Grimoire of Enlightenment +1', value: 'Woe Peak Grimoire of Enlightenment +1' },
  { label: 'Woe Peak Grimoire of Fury +1', value: 'Woe Peak Grimoire of Fury +1' },
  { label: 'Woe Peak Grimoire of Perfection +1', value: 'Woe Peak Grimoire of Perfection +1' },
  { label: 'Woe Shout Grave Wand of Protection +1', value: 'Woe Shout Grave Wand of Protection +1' },
  { label: 'Woe Shout Grave Wand of Skill +1', value: 'Woe Shout Grave Wand of Skill +1' },
  { label: 'Woe Shout Grave Wand of Vitriol +1', value: 'Woe Shout Grave Wand of Vitriol +1' },
];
