export const chests = [
  { label: 'Linen Robe', value: 'Linen Robe' },
  { label: 'Studded Leather Armor', value: 'Studded Leather Armor' },
  { label: 'Divine Robe', value: 'Divine Robe' },
  { label: 'Chain Mail', value: 'Chain Mail' },
  { label: 'Plate Mail', value: 'Plate Mail' },
  { label: 'Robe', value: 'Robe' },
  { label: 'Leather Armor', value: 'Leather Armor' },
  { label: 'Ornate Chestplate', value: 'Ornate Chestplate' },
  { label: 'Demon Husk', value: 'Demon Husk' },
  { label: 'Hard Leather Armor', value: 'Hard Leather Armor' },
  { label: 'Shirt', value: 'Shirt' },
  { label: 'Holy Chestplate', value: 'Holy Chestplate' },
  { label: 'Silk Robe', value: 'Silk Robe' },
  { label: 'Ring Mail', value: 'Ring Mail' },
  { label: 'Dragonskin Armor', value: 'Dragonskin Armor' },
  { label: 'Plate Mail of Brilliance', value: 'Plate Mail of Brilliance' },
  { label: 'Robe of Anger', value: 'Robe of Anger' },
  { label: 'Leather Armor of Protection', value: 'Leather Armor of Protection' },
  { label: 'Plate Mail of Reflection', value: 'Plate Mail of Reflection' },
  { label: 'Plate Mail of Detection', value: 'Plate Mail of Detection' },
  { label: 'Leather Armor of Skill', value: 'Leather Armor of Skill' },
  { label: 'Divine Robe of Rage', value: 'Divine Robe of Rage' },
  { label: 'Dragonskin Armor of Power', value: 'Dragonskin Armor of Power' },
  { label: 'Leather Armor of the Fox', value: 'Leather Armor of the Fox' },
  { label: 'Leather Armor of Titans', value: 'Leather Armor of Titans' },
  { label: 'Plate Mail of Giants', value: 'Plate Mail of Giants' },
  { label: 'Plate Mail of Rage', value: 'Plate Mail of Rage' },
  { label: 'Leather Armor of Perfection', value: 'Leather Armor of Perfection' },
  { label: 'Dragonskin Armor of Fury', value: 'Dragonskin Armor of Fury' },
  { label: 'Plate Mail of Fury', value: 'Plate Mail of Fury' },
  { label: 'Dragonskin Armor of Enlightenment', value: 'Dragonskin Armor of Enlightenment' },
  { label: 'Dragonskin Armor of Perfection', value: 'Dragonskin Armor of Perfection' },
  { label: 'Dragonskin Armor of Protection', value: 'Dragonskin Armor of Protection' },
  { label: 'Dragonskin Armor of Giants', value: 'Dragonskin Armor of Giants' },
  { label: 'Plate Mail of Vitriol', value: 'Plate Mail of Vitriol' },
  { label: 'Plate Mail of Power', value: 'Plate Mail of Power' },
  { label: 'Ring Mail of Giants', value: 'Ring Mail of Giants' },
  { label: 'Robe of Brilliance', value: 'Robe of Brilliance' },
  { label: 'Robe of Titans', value: 'Robe of Titans' },
  { label: 'Studded Leather Armor of Giants', value: 'Studded Leather Armor of Giants' },
  { label: 'Ornate Chestplate of Detection', value: 'Ornate Chestplate of Detection' },
  { label: 'Dragonskin Armor of the Fox', value: 'Dragonskin Armor of the Fox' },
  { label: 'Divine Robe of Protection', value: 'Divine Robe of Protection' },
  { label: 'Leather Armor of Vitriol', value: 'Leather Armor of Vitriol' },
  { label: 'Leather Armor of Rage', value: 'Leather Armor of Rage' },
  { label: 'Robe of Enlightenment', value: 'Robe of Enlightenment' },
  { label: 'Robe of Power', value: 'Robe of Power' },
  { label: 'Divine Robe of Brilliance', value: 'Divine Robe of Brilliance' },
  { label: 'Chain Mail of Protection', value: 'Chain Mail of Protection' },
  { label: 'Dragonskin Armor of Rage', value: 'Dragonskin Armor of Rage' },
  { label: 'Plate Mail of Protection', value: 'Plate Mail of Protection' },
  { label: 'Divine Robe of Vitriol', value: 'Divine Robe of Vitriol' },
  { label: 'Leather Armor of Anger', value: 'Leather Armor of Anger' },
  { label: 'Divine Robe of Giants', value: 'Divine Robe of Giants' },
  { label: 'Divine Robe of Titans', value: 'Divine Robe of Titans' },
  { label: 'Divine Robe of Fury', value: 'Divine Robe of Fury' },
  { label: 'Robe of Reflection', value: 'Robe of Reflection' },
  { label: 'Robe of Vitriol', value: 'Robe of Vitriol' },
  { label: 'Hard Leather Armor of Detection', value: 'Hard Leather Armor of Detection' },
  { label: 'Holy Chestplate of Brilliance', value: 'Holy Chestplate of Brilliance' },
  { label: 'Leather Armor of the Twins', value: 'Leather Armor of the Twins' },
  { label: 'Divine Robe of Perfection', value: 'Divine Robe of Perfection' },
  { label: 'Holy Chestplate of Titans', value: 'Holy Chestplate of Titans' },
  { label: 'Leather Armor of Giants', value: 'Leather Armor of Giants' },
  { label: 'Plate Mail of the Twins', value: 'Plate Mail of the Twins' },
  { label: 'Plate Mail of the Fox', value: 'Plate Mail of the Fox' },
  { label: 'Robe of the Twins', value: 'Robe of the Twins' },
  { label: 'Robe of Skill', value: 'Robe of Skill' },
  { label: 'Dragonskin Armor of Detection', value: 'Dragonskin Armor of Detection' },
  { label: 'Divine Robe of Enlightenment', value: 'Divine Robe of Enlightenment' },
  { label: 'Divine Robe of Reflection', value: 'Divine Robe of Reflection' },
  { label: 'Silk Robe of Perfection', value: 'Silk Robe of Perfection' },
  { label: 'Leather Armor of Power', value: 'Leather Armor of Power' },
  { label: 'Silk Robe of the Twins', value: 'Silk Robe of the Twins' },
  { label: 'Chain Mail of Giants', value: 'Chain Mail of Giants' },
  { label: 'Plate Mail of Anger', value: 'Plate Mail of Anger' },
  { label: 'Linen Robe of Rage', value: 'Linen Robe of Rage' },
  { label: 'Robe of Protection', value: 'Robe of Protection' },
  { label: 'Robe of Detection', value: 'Robe of Detection' },
  { label: 'Robe of Fury', value: 'Robe of Fury' },
  { label: 'Hard Leather Armor of Enlightenment', value: 'Hard Leather Armor of Enlightenment' },
  { label: 'Studded Leather Armor of Detection', value: 'Studded Leather Armor of Detection' },
  { label: 'Studded Leather Armor of the Twins', value: 'Studded Leather Armor of the Twins' },
  { label: 'Dragonskin Armor of Brilliance', value: 'Dragonskin Armor of Brilliance' },
  { label: 'Hard Leather Armor of Anger', value: 'Hard Leather Armor of Anger' },
  { label: 'Holy Chestplate of the Fox', value: 'Holy Chestplate of the Fox' },
  { label: 'Dragonskin Armor of Anger', value: 'Dragonskin Armor of Anger' },
  { label: 'Chain Mail of Perfection', value: 'Chain Mail of Perfection' },
  { label: 'Divine Robe of the Twins', value: 'Divine Robe of the Twins' },
  { label: 'Holy Chestplate of Skill', value: 'Holy Chestplate of Skill' },
  { label: 'Chain Mail of the Fox', value: 'Chain Mail of the Fox' },
  { label: 'Linen Robe of Vitriol', value: 'Linen Robe of Vitriol' },
  { label: 'Ring Mail of the Fox', value: 'Ring Mail of the Fox' },
  { label: 'Chain Mail of Anger', value: 'Chain Mail of Anger' },
  { label: 'Chain Mail of Power', value: 'Chain Mail of Power' },
  { label: 'Chain Mail of Rage', value: 'Chain Mail of Rage' },
  { label: 'Ring Mail of Anger', value: 'Ring Mail of Anger' },
  { label: 'Ring Mail of Fury', value: 'Ring Mail of Fury' },
  { label: 'Robe of Giants', value: 'Robe of Giants' },
  { label: 'Shirt of Rage', value: 'Shirt of Rage' },
  { label: 'Robe of Rage', value: 'Robe of Rage' },
  { label: 'Studded Leather Armor of Brilliance', value: 'Studded Leather Armor of Brilliance' },
  { label: 'Studded Leather Armor of Perfection', value: 'Studded Leather Armor of Perfection' },
  { label: 'Hard Leather Armor of Protection', value: 'Hard Leather Armor of Protection' },
  { label: 'Studded Leather Armor of the Fox', value: 'Studded Leather Armor of the Fox' },
  { label: 'Leather Armor of Enlightenment', value: 'Leather Armor of Enlightenment' },
  { label: 'Studded Leather Armor of Power', value: 'Studded Leather Armor of Power' },
  { label: 'Holy Chestplate of Protection', value: 'Holy Chestplate of Protection' },
  { label: 'Holy Chestplate of Reflection', value: 'Holy Chestplate of Reflection' },
  { label: 'Studded Leather Armor of Rage', value: 'Studded Leather Armor of Rage' },
  { label: 'Chain Mail of Enlightenment', value: 'Chain Mail of Enlightenment' },
  { label: 'Hard Leather Armor of Rage', value: 'Hard Leather Armor of Rage' },
  { label: 'Demon Husk of Protection', value: 'Demon Husk of Protection' },
  { label: 'Divine Robe of Detection', value: 'Divine Robe of Detection' },
  { label: 'Holy Chestplate of Anger', value: 'Holy Chestplate of Anger' },
  { label: 'Linen Robe of Brilliance', value: 'Linen Robe of Brilliance' },
  { label: 'Linen Robe of Perfection', value: 'Linen Robe of Perfection' },
  { label: 'Linen Robe of Protection', value: 'Linen Robe of Protection' },
  { label: 'Linen Robe of Reflection', value: 'Linen Robe of Reflection' },
  { label: 'Chain Mail of Detection', value: 'Chain Mail of Detection' },
  { label: 'Holy Chestplate of Fury', value: 'Holy Chestplate of Fury' },
  { label: 'Linen Robe of the Fox', value: 'Linen Robe of the Fox' },
  { label: 'Linen Robe of Titans', value: 'Linen Robe of Titans' },
  { label: 'Plate Mail of Titans', value: 'Plate Mail of Titans' },
  { label: 'Silk Robe of the Fox', value: 'Silk Robe of the Fox' },
  { label: 'Shirt of Reflection', value: 'Shirt of Reflection' },
  { label: 'Silk Robe of Titans', value: 'Silk Robe of Titans' },
  { label: 'Robe of Perfection', value: 'Robe of Perfection' },
  { label: 'Shirt of Detection', value: 'Shirt of Detection' },
  { label: 'Shirt of Skill', value: 'Shirt of Skill' },
  { label: 'Studded Leather Armor of Protection', value: 'Studded Leather Armor of Protection' },
  { label: 'Hard Leather Armor of the Twins', value: 'Hard Leather Armor of the Twins' },
  { label: 'Ornate Chestplate of Protection', value: 'Ornate Chestplate of Protection' },
  { label: 'Ornate Chestplate of Reflection', value: 'Ornate Chestplate of Reflection' },
  { label: 'Dragonskin Armor of Reflection', value: 'Dragonskin Armor of Reflection' },
  { label: 'Studded Leather Armor of Anger', value: 'Studded Leather Armor of Anger' },
  { label: 'Studded Leather Armor of Skill', value: 'Studded Leather Armor of Skill' },
  { label: 'Dragonskin Armor of the Twins', value: 'Dragonskin Armor of the Twins' },
  { label: 'Hard Leather Armor of Vitriol', value: 'Hard Leather Armor of Vitriol' },
  { label: 'Hard Leather Armor of Titans', value: 'Hard Leather Armor of Titans' },
  { label: 'Ornate Chestplate of the Fox', value: 'Ornate Chestplate of the Fox' },
  { label: 'Ornate Chestplate of Vitriol', value: 'Ornate Chestplate of Vitriol' },
  { label: 'Dragonskin Armor of Vitriol', value: 'Dragonskin Armor of Vitriol' },
  { label: 'Hard Leather Armor of Power', value: 'Hard Leather Armor of Power' },
  { label: 'Ornate Chestplate of Giants', value: 'Ornate Chestplate of Giants' },
  { label: 'Plate Mail of Enlightenment', value: 'Plate Mail of Enlightenment' },
  { label: 'Dragonskin Armor of Titans', value: 'Dragonskin Armor of Titans' },
  { label: 'Hard Leather Armor of Fury', value: 'Hard Leather Armor of Fury' },
  { label: 'Leather Armor of Detection', value: 'Leather Armor of Detection' },
  { label: 'Dragonskin Armor of Skill', value: 'Dragonskin Armor of Skill' },
  { label: 'Ornate Chestplate of Fury', value: 'Ornate Chestplate of Fury' },
  { label: 'Chain Mail of Brilliance', value: 'Chain Mail of Brilliance' },
  { label: 'Plate Mail of Perfection', value: 'Plate Mail of Perfection' },
  { label: 'Linen Robe of the Twins', value: 'Linen Robe of the Twins' },
  { label: 'Silk Robe of Protection', value: 'Silk Robe of Protection' },
  { label: 'Ring Mail of the Twins', value: 'Ring Mail of the Twins' },
  { label: 'Chain Mail of Titans', value: 'Chain Mail of Titans' },
  { label: 'Divine Robe of Anger', value: 'Divine Robe of Anger' },
  { label: 'Divine Robe of Power', value: 'Divine Robe of Power' },
  { label: 'Ring Mail of Vitriol', value: 'Ring Mail of Vitriol' },
  { label: 'Chain Mail of Skill', value: 'Chain Mail of Skill' },
  { label: 'Demon Husk of Power', value: 'Demon Husk of Power' },
  { label: 'Demon Husk of Skill', value: 'Demon Husk of Skill' },
  { label: 'Linen Robe of Anger', value: 'Linen Robe of Anger' },
  { label: 'Ring Mail of Titans', value: 'Ring Mail of Titans' },
  { label: 'Chain Mail of Fury', value: 'Chain Mail of Fury' },
  { label: 'Ring Mail of Power', value: 'Ring Mail of Power' },
  { label: 'Silk Robe of Anger', value: 'Silk Robe of Anger' },
  { label: 'Silk Robe of Fury', value: 'Silk Robe of Fury' },
  { label: 'Robe of the Fox', value: 'Robe of the Fox' },
  { label: 'Shirt of Titans', value: 'Shirt of Titans' },
  { label: 'Studded Leather Armor of Enlightenment', value: 'Studded Leather Armor of Enlightenment' },
  { label: 'Hard Leather Armor of Brilliance', value: 'Hard Leather Armor of Brilliance' },
  { label: 'Holy Chestplate of Enlightenment', value: 'Holy Chestplate of Enlightenment' },
  { label: 'Studded Leather Armor of Fury', value: 'Studded Leather Armor of Fury' },
  { label: 'Holy Chestplate of Detection', value: 'Holy Chestplate of Detection' },
  { label: 'Leather Armor of Brilliance', value: 'Leather Armor of Brilliance' },
  { label: 'Linen Robe of Enlightenment', value: 'Linen Robe of Enlightenment' },
  { label: 'Holy Chestplate of Vitriol', value: 'Holy Chestplate of Vitriol' },
  { label: 'Ornate Chestplate of Power', value: 'Ornate Chestplate of Power' },
  { label: 'Ornate Chestplate of Skill', value: 'Ornate Chestplate of Skill' },
  { label: 'Ring Mail of Enlightenment', value: 'Ring Mail of Enlightenment' },
  { label: 'Ornate Chestplate of Rage', value: 'Ornate Chestplate of Rage' },
  { label: 'Chain Mail of Reflection', value: 'Chain Mail of Reflection' },
  { label: 'Demon Husk of Brilliance', value: 'Demon Husk of Brilliance' },
  { label: 'Demon Husk of Reflection', value: 'Demon Husk of Reflection' },
  { label: 'Chain Mail of the Twins', value: 'Chain Mail of the Twins' },
  { label: 'Holy Chestplate of Rage', value: 'Holy Chestplate of Rage' },
  { label: 'Ring Mail of Protection', value: 'Ring Mail of Protection' },
  { label: 'Ring Mail of Reflection', value: 'Ring Mail of Reflection' },
  { label: 'Ring Mail of Detection', value: 'Ring Mail of Detection' },
  { label: 'Silk Robe of Detection', value: 'Silk Robe of Detection' },
  { label: 'Demon Husk of Vitriol', value: 'Demon Husk of Vitriol' },
  { label: 'Leather Armor of Fury', value: 'Leather Armor of Fury' },
  { label: 'Silk Robe of Vitriol', value: 'Silk Robe of Vitriol' },
  { label: 'Demon Husk of Anger', value: 'Demon Husk of Anger' },
  { label: 'Plate Mail of Skill', value: 'Plate Mail of Skill' },
  { label: 'Shirt of Brilliance', value: 'Shirt of Brilliance' },
  { label: 'Shirt of the Twins', value: 'Shirt of the Twins' },
  { label: 'Silk Robe of Skill', value: 'Silk Robe of Skill' },
  { label: 'Shirt of Anger', value: 'Shirt of Anger' },
  { label: 'Maelstrom Sun Studded Leather Armor of Fury', value: 'Maelstrom Sun Studded Leather Armor of Fury' },
  { label: 'Studded Leather Armor of Reflection', value: 'Studded Leather Armor of Reflection' },
  { label: 'Ornate Chestplate of Enlightenment', value: 'Ornate Chestplate of Enlightenment' },
  { label: 'Hard Leather Armor of Reflection', value: 'Hard Leather Armor of Reflection' },
  { label: 'Studded Leather Armor of Vitriol', value: 'Studded Leather Armor of Vitriol' },
  { label: 'Studded Leather Armor of Titans', value: 'Studded Leather Armor of Titans' },
  { label: 'Hard Leather Armor of Giants', value: 'Hard Leather Armor of Giants' },
  { label: 'Holy Chestplate of the Twins', value: 'Holy Chestplate of the Twins' },
  { label: 'Demon Husk of Enlightenment', value: 'Demon Husk of Enlightenment' },
  { label: 'Leather Armor of Reflection', value: 'Leather Armor of Reflection' },
  { label: 'Ornate Chestplate of Titans', value: 'Ornate Chestplate of Titans' },
  { label: 'Ornate Chestplate of Anger', value: 'Ornate Chestplate of Anger' },
  { label: 'Holy Chestplate of Giants', value: 'Holy Chestplate of Giants' },
  { label: 'Demon Husk of Perfection', value: 'Demon Husk of Perfection' },
  { label: 'Holy Chestplate of Power', value: 'Holy Chestplate of Power' },
  { label: 'Demon Husk of the Twins', value: 'Demon Husk of the Twins' },
  { label: 'Ring Mail of Brilliance', value: 'Ring Mail of Brilliance' },
  { label: 'Silk Robe of Reflection', value: 'Silk Robe of Reflection' },
  { label: 'Shirt of Enlightenment', value: 'Shirt of Enlightenment' },
  { label: 'Chain Mail of Vitriol', value: 'Chain Mail of Vitriol' },
  { label: 'Demon Husk of the Fox', value: 'Demon Husk of the Fox' },
  { label: 'Demon Husk of Titans', value: 'Demon Husk of Titans' },
  { label: 'Divine Robe of Skill', value: 'Divine Robe of Skill' },
  { label: 'Shirt of Protection', value: 'Shirt of Protection' },
  { label: 'Silk Robe of Giants', value: 'Silk Robe of Giants' },
  { label: 'Demon Husk of Fury', value: 'Demon Husk of Fury' },
  { label: 'Silk Robe of Power', value: 'Silk Robe of Power' },
  { label: 'Shirt of Vitriol', value: 'Shirt of Vitriol' },
  { label: 'Shirt of Giants', value: 'Shirt of Giants' },
  { label: 'Shirt of Power', value: 'Shirt of Power' },
  { label: 'Shirt of Fury', value: 'Shirt of Fury' },
  { label: 'Shimmering Shout Ornate Chestplate of Giants +1', value: 'Shimmering Shout Ornate Chestplate of Giants +1' },
  { label: 'Demon Moon Hard Leather Armor of Brilliance +1', value: 'Demon Moon Hard Leather Armor of Brilliance +1' },
  { label: 'Armageddon Bite Linen Robe of Reflection +1', value: 'Armageddon Bite Linen Robe of Reflection +1' },
  { label: 'Corruption Grasp Demon Husk of the Twins +1', value: 'Corruption Grasp Demon Husk of the Twins +1' },
  { label: 'Hypnotic Whisper Silk Robe of Enlightenment', value: 'Hypnotic Whisper Silk Robe of Enlightenment' },
  { label: 'Mind Peak Hard Leather Armor of the Fox +1', value: 'Mind Peak Hard Leather Armor of the Fox +1' },
  { label: 'Pain Tear Studded Leather Armor of Vitriol', value: 'Pain Tear Studded Leather Armor of Vitriol' },
  { label: 'Tempest Peak Hard Leather Armor of Fury +1', value: 'Tempest Peak Hard Leather Armor of Fury +1' },
  { label: 'Armageddon Peak Linen Robe of the Fox +1', value: 'Armageddon Peak Linen Robe of the Fox +1' },
  { label: 'Foe Bite Ornate Chestplate of Power +1', value: 'Foe Bite Ornate Chestplate of Power +1' },
  { label: 'Skull Peak Linen Robe of Reflection +1', value: 'Skull Peak Linen Robe of Reflection +1' },
  { label: 'Sorrow Moon Ring Mail of Brilliance +1', value: 'Sorrow Moon Ring Mail of Brilliance +1' },
  { label: 'Foe Moon Linen Robe of Brilliance +1', value: 'Foe Moon Linen Robe of Brilliance +1' },
  { label: 'Ghoul Roar Chain Mail of Reflection', value: 'Ghoul Roar Chain Mail of Reflection' },
  { label: 'Ghoul Sun Holy Chestplate of Power', value: 'Ghoul Sun Holy Chestplate of Power' },
  { label: 'Maelstrom Tear Shirt of Protection', value: 'Maelstrom Tear Shirt of Protection' },
  { label: 'Honour Peak Demon Husk of Fury +1', value: 'Honour Peak Demon Husk of Fury +1' },
  { label: 'Hard Leather Armor of Perfection', value: 'Hard Leather Armor of Perfection' },
  { label: "Light's Root Shirt of Protection", value: "Light's Root Shirt of Protection" },
  { label: 'Ornate Chestplate of Brilliance', value: 'Ornate Chestplate of Brilliance' },
  { label: 'Ornate Chestplate of Perfection', value: 'Ornate Chestplate of Perfection' },
  { label: 'Woe Moon Demon Husk of Skill +1', value: 'Woe Moon Demon Husk of Skill +1' },
  { label: "Light's Sun Chain Mail of Fury", value: "Light's Sun Chain Mail of Fury" },
  { label: 'Hard Leather Armor of the Fox', value: 'Hard Leather Armor of the Fox' },
  { label: 'Holy Chestplate of Perfection', value: 'Holy Chestplate of Perfection' },
  { label: 'Plague Sun Silk Robe of Fury', value: 'Plague Sun Silk Robe of Fury' },
  { label: 'Hard Leather Armor of Skill', value: 'Hard Leather Armor of Skill' },
  { label: 'Silk Robe of Enlightenment', value: 'Silk Robe of Enlightenment' },
  { label: 'Demon Husk of Detection', value: 'Demon Husk of Detection' },
  { label: 'Linen Robe of Detection', value: 'Linen Robe of Detection' },
  { label: 'Ring Mail of Perfection', value: 'Ring Mail of Perfection' },
  { label: 'Demon Husk of Giants', value: 'Demon Husk of Giants' },
  { label: 'Linen Robe of Giants', value: 'Linen Robe of Giants' },
  { label: 'Linen Robe of Power', value: 'Linen Robe of Power' },
  { label: 'Linen Robe of Skill', value: 'Linen Robe of Skill' },
  { label: 'Shirt of Perfection', value: 'Shirt of Perfection' },
  { label: 'Demon Husk of Rage', value: 'Demon Husk of Rage' },
  { label: 'Linen Robe of Fury', value: 'Linen Robe of Fury' },
  { label: 'Ring Mail of Rage', value: 'Ring Mail of Rage' },
  { label: 'Silk Robe of Rage', value: 'Silk Robe of Rage' },
  { label: 'Shirt of the Fox', value: 'Shirt of the Fox' },
  { label: 'Maelstrom Whisper Studded Leather Armor of Enlightenment', value: 'Maelstrom Whisper Studded Leather Armor of Enlightenment' },
  { label: 'Pandemonium Bender Ornate Chestplate of Enlightenment +1', value: 'Pandemonium Bender Ornate Chestplate of Enlightenment +1' },
  { label: 'Brimstone Bender Ornate Chestplate of Enlightenment +1', value: 'Brimstone Bender Ornate Chestplate of Enlightenment +1' },
  { label: 'Corruption Peak Hard Leather Armor of Enlightenment +1', value: 'Corruption Peak Hard Leather Armor of Enlightenment +1' },
  { label: 'Pandemonium Bender Hard Leather Armor of Reflection +1', value: 'Pandemonium Bender Hard Leather Armor of Reflection +1' },
  { label: 'Brimstone Bite Hard Leather Armor of Enlightenment +1', value: 'Brimstone Bite Hard Leather Armor of Enlightenment +1' },
  { label: 'Corruption Peak Ornate Chestplate of Enlightenment +1', value: 'Corruption Peak Ornate Chestplate of Enlightenment +1' },
  { label: 'Cataclysm Bender Hard Leather Armor of Reflection +1', value: 'Cataclysm Bender Hard Leather Armor of Reflection +1' },
  { label: 'Cataclysm Bite Ornate Chestplate of Enlightenment +1', value: 'Cataclysm Bite Ornate Chestplate of Enlightenment +1' },
  { label: 'Golem Whisper Studded Leather Armor of Enlightenment', value: 'Golem Whisper Studded Leather Armor of Enlightenment' },
  { label: 'Hypnotic Whisper Studded Leather Armor of Reflection', value: 'Hypnotic Whisper Studded Leather Armor of Reflection' },
  { label: 'Pandemonium Bite Hard Leather Armor of Perfection +1', value: 'Pandemonium Bite Hard Leather Armor of Perfection +1' },
  { label: 'Apocalypse Glow Studded Leather Armor of Protection', value: 'Apocalypse Glow Studded Leather Armor of Protection' },
  { label: "Light's Whisper Studded Leather Armor of Perfection", value: "Light's Whisper Studded Leather Armor of Perfection" },
  { label: 'Armageddon Bite Ornate Chestplate of Reflection +1', value: 'Armageddon Bite Ornate Chestplate of Reflection +1' },
  { label: 'Cataclysm Grasp Ornate Chestplate of Protection +1', value: 'Cataclysm Grasp Ornate Chestplate of Protection +1' },
  { label: 'Corruption Moon Hard Leather Armor of Detection +1', value: 'Corruption Moon Hard Leather Armor of Detection +1' },
  { label: 'Armageddon Moon Ornate Chestplate of the Twins +1', value: 'Armageddon Moon Ornate Chestplate of the Twins +1' },
  { label: 'Brimstone Grasp Ornate Chestplate of Detection +1', value: 'Brimstone Grasp Ornate Chestplate of Detection +1' },
  { label: 'Cataclysm Bender Hard Leather Armor of the Fox +1', value: 'Cataclysm Bender Hard Leather Armor of the Fox +1' },
  { label: 'Cataclysm Shout Ornate Chestplate of Detection +1', value: 'Cataclysm Shout Ornate Chestplate of Detection +1' },
  { label: 'Cataclysm Shout Ornate Chestplate of the Twins +1', value: 'Cataclysm Shout Ornate Chestplate of the Twins +1' },
  { label: 'Honour Bender Hard Leather Armor of Reflection +1', value: 'Honour Bender Hard Leather Armor of Reflection +1' },
  { label: 'Maelstrom Whisper Studded Leather Armor of Titans', value: 'Maelstrom Whisper Studded Leather Armor of Titans' },
  { label: 'Oblivion Bite Hard Leather Armor of Perfection +1', value: 'Oblivion Bite Hard Leather Armor of Perfection +1' },
  { label: 'Oblivion Grasp Ornate Chestplate of Brilliance +1', value: 'Oblivion Grasp Ornate Chestplate of Brilliance +1' },
  { label: 'Oblivion Shout Hard Leather Armor of Detection +1', value: 'Oblivion Shout Hard Leather Armor of Detection +1' },
  { label: 'Pandemonium Bender Demon Husk of Enlightenment +1', value: 'Pandemonium Bender Demon Husk of Enlightenment +1' },
  { label: 'Pandemonium Grasp Hard Leather Armor of Giants +1', value: 'Pandemonium Grasp Hard Leather Armor of Giants +1' },
  { label: 'Apocalypse Whisper Holy Chestplate of Perfection', value: 'Apocalypse Whisper Holy Chestplate of Perfection' },
  { label: 'Armageddon Bender Demon Husk of Enlightenment +1', value: 'Armageddon Bender Demon Husk of Enlightenment +1' },
  { label: 'Armageddon Bender Hard Leather Armor of Power +1', value: 'Armageddon Bender Hard Leather Armor of Power +1' },
  { label: 'Armageddon Moon Hard Leather Armor of Vitriol +1', value: 'Armageddon Moon Hard Leather Armor of Vitriol +1' },
  { label: 'Carrion Tear Studded Leather Armor of Brilliance', value: 'Carrion Tear Studded Leather Armor of Brilliance' },
  { label: 'Carrion Whisper Holy Chestplate of Enlightenment', value: 'Carrion Whisper Holy Chestplate of Enlightenment' },
  { label: 'Corruption Grasp Ornate Chestplate of Vitriol +1', value: 'Corruption Grasp Ornate Chestplate of Vitriol +1' },
  { label: 'Gloom Bender Hard Leather Armor of Reflection +1', value: 'Gloom Bender Hard Leather Armor of Reflection +1' },
  { label: 'Kraken Grasp Hard Leather Armor of Protection +1', value: 'Kraken Grasp Hard Leather Armor of Protection +1' },
  { label: 'Oblivion Bender Hard Leather Armor of the Fox +1', value: 'Oblivion Bender Hard Leather Armor of the Fox +1' },
  { label: 'Pain Whisper Studded Leather Armor of Perfection', value: 'Pain Whisper Studded Leather Armor of Perfection' },
  { label: 'Pandemonium Grasp Hard Leather Armor of Skill +1', value: 'Pandemonium Grasp Hard Leather Armor of Skill +1' },
  { label: 'Armageddon Grasp Ornate Chestplate of Giants +1', value: 'Armageddon Grasp Ornate Chestplate of Giants +1' },
  { label: 'Blight Moon Hard Leather Armor of Brilliance +1', value: 'Blight Moon Hard Leather Armor of Brilliance +1' },
  { label: 'Blight Moon Hard Leather Armor of Protection +1', value: 'Blight Moon Hard Leather Armor of Protection +1' },
  { label: 'Blight Peak Hard Leather Armor of Perfection +1', value: 'Blight Peak Hard Leather Armor of Perfection +1' },
  { label: 'Brimstone Bender Hard Leather Armor of Anger +1', value: 'Brimstone Bender Hard Leather Armor of Anger +1' },
  { label: 'Cataclysm Bender Hard Leather Armor of Power +1', value: 'Cataclysm Bender Hard Leather Armor of Power +1' },
  { label: 'Corruption Peak Hard Leather Armor of Titans +1', value: 'Corruption Peak Hard Leather Armor of Titans +1' },
  { label: 'Dread Grasp Hard Leather Armor of Brilliance +1', value: 'Dread Grasp Hard Leather Armor of Brilliance +1' },
  { label: 'Gloom Grasp Hard Leather Armor of Protection +1', value: 'Gloom Grasp Hard Leather Armor of Protection +1' },
  { label: 'Honour Bite Hard Leather Armor of Perfection +1', value: 'Honour Bite Hard Leather Armor of Perfection +1' },
  { label: 'Kraken Grasp Hard Leather Armor of Detection +1', value: 'Kraken Grasp Hard Leather Armor of Detection +1' },
  { label: 'Kraken Shout Ornate Chestplate of Protection +1', value: 'Kraken Shout Ornate Chestplate of Protection +1' },
  { label: 'Morbid Root Studded Leather Armor of Protection', value: 'Morbid Root Studded Leather Armor of Protection' },
  { label: 'Morbid Tear Studded Leather Armor of Brilliance', value: 'Morbid Tear Studded Leather Armor of Brilliance' },
  { label: 'Armageddon Grasp Ornate Chestplate of Skill +1', value: 'Armageddon Grasp Ornate Chestplate of Skill +1' },
  { label: 'Behemoth Roar Holy Chestplate of Enlightenment', value: 'Behemoth Roar Holy Chestplate of Enlightenment' },
  { label: 'Blight Bender Hard Leather Armor of the Fox +1', value: 'Blight Bender Hard Leather Armor of the Fox +1' },
  { label: 'Blight Grasp Ornate Chestplate of the Twins +1', value: 'Blight Grasp Ornate Chestplate of the Twins +1' },
  { label: 'Blight Shout Ornate Chestplate of Detection +1', value: 'Blight Shout Ornate Chestplate of Detection +1' },
  { label: 'Cataclysm Bender Ornate Chestplate of Power +1', value: 'Cataclysm Bender Ornate Chestplate of Power +1' },
  { label: 'Corpse Glow Studded Leather Armor of the Twins', value: 'Corpse Glow Studded Leather Armor of the Twins' },
  { label: 'Eagle Shout Hard Leather Armor of Detection +1', value: 'Eagle Shout Hard Leather Armor of Detection +1' },
  { label: 'Foe Peak Ornate Chestplate of Enlightenment +1', value: 'Foe Peak Ornate Chestplate of Enlightenment +1' },
  { label: 'Golem Whisper Holy Chestplate of Enlightenment', value: 'Golem Whisper Holy Chestplate of Enlightenment' },
  { label: 'Honour Peak Ornate Chestplate of Reflection +1', value: 'Honour Peak Ornate Chestplate of Reflection +1' },
  { label: 'Hypnotic Whisper Holy Chestplate of Reflection', value: 'Hypnotic Whisper Holy Chestplate of Reflection' },
  { label: 'Kraken Peak Ornate Chestplate of Perfection +1', value: 'Kraken Peak Ornate Chestplate of Perfection +1' },
  { label: 'Maelstrom Roar Studded Leather Armor of Titans', value: 'Maelstrom Roar Studded Leather Armor of Titans' },
  { label: 'Morbid Whisper Studded Leather Armor of Titans', value: 'Morbid Whisper Studded Leather Armor of Titans' },
  { label: 'Oblivion Bite Hard Leather Armor of the Fox +1', value: 'Oblivion Bite Hard Leather Armor of the Fox +1' },
  { label: 'Pandemonium Bender Demon Husk of Perfection +1', value: 'Pandemonium Bender Demon Husk of Perfection +1' },
  { label: 'Pandemonium Grasp Ornate Chestplate of Rage +1', value: 'Pandemonium Grasp Ornate Chestplate of Rage +1' },
  { label: 'Apocalypse Roar Holy Chestplate of Perfection', value: 'Apocalypse Roar Holy Chestplate of Perfection' },
  { label: 'Behemoth Glow Studded Leather Armor of Giants', value: 'Behemoth Glow Studded Leather Armor of Giants' },
  { label: 'Brimstone Bender Ornate Chestplate of Fury +1', value: 'Brimstone Bender Ornate Chestplate of Fury +1' },
  { label: 'Corruption Bender Linen Robe of Perfection +1', value: 'Corruption Bender Linen Robe of Perfection +1' },
  { label: 'Death Sun Studded Leather Armor of Perfection', value: 'Death Sun Studded Leather Armor of Perfection' },
  { label: 'Demon Peak Ornate Chestplate of Perfection +1', value: 'Demon Peak Ornate Chestplate of Perfection +1' },
  { label: 'Dusk Glow Studded Leather Armor of Brilliance', value: 'Dusk Glow Studded Leather Armor of Brilliance' },
  { label: 'Dusk Whisper Holy Chestplate of Enlightenment', value: 'Dusk Whisper Holy Chestplate of Enlightenment' },
  { label: 'Eagle Grasp Ornate Chestplate of Detection +1', value: 'Eagle Grasp Ornate Chestplate of Detection +1' },
  { label: 'Eagle Moon Hard Leather Armor of the Twins +1', value: 'Eagle Moon Hard Leather Armor of the Twins +1' },
  { label: 'Ghoul Sun Studded Leather Armor of Reflection', value: 'Ghoul Sun Studded Leather Armor of Reflection' },
  { label: 'Gloom Moon Hard Leather Armor of Detection +1', value: 'Gloom Moon Hard Leather Armor of Detection +1' },
  { label: 'Grim Shout Hard Leather Armor of the Twins +1', value: 'Grim Shout Hard Leather Armor of the Twins +1' },
  { label: 'Havoc Glow Studded Leather Armor of the Twins', value: 'Havoc Glow Studded Leather Armor of the Twins' },
  { label: 'Hypnotic Glow Studded Leather Armor of Giants', value: 'Hypnotic Glow Studded Leather Armor of Giants' },
  { label: 'Kraken Moon Ornate Chestplate of the Twins +1', value: 'Kraken Moon Ornate Chestplate of the Twins +1' },
  { label: 'Apocalypse Whisper Holy Chestplate of Titans', value: 'Apocalypse Whisper Holy Chestplate of Titans' },
  { label: 'Armageddon Grasp Demon Husk of Protection +1', value: 'Armageddon Grasp Demon Husk of Protection +1' },
  { label: 'Armageddon Shout Linen Robe of Brilliance +1', value: 'Armageddon Shout Linen Robe of Brilliance +1' },
  { label: 'Blight Grasp Hard Leather Armor of Giants +1', value: 'Blight Grasp Hard Leather Armor of Giants +1' },
  { label: 'Blight Grasp Ornate Chestplate of Vitriol +1', value: 'Blight Grasp Ornate Chestplate of Vitriol +1' },
  { label: 'Brimstone Bite Ornate Chestplate of Power +1', value: 'Brimstone Bite Ornate Chestplate of Power +1' },
  { label: 'Corruption Grasp Demon Husk of Brilliance +1', value: 'Corruption Grasp Demon Husk of Brilliance +1' },
  { label: 'Corruption Grasp Linen Robe of Brilliance +1', value: 'Corruption Grasp Linen Robe of Brilliance +1' },
  { label: 'Dusk Root Studded Leather Armor of the Twins', value: 'Dusk Root Studded Leather Armor of the Twins' },
  { label: 'Fate Sun Studded Leather Armor of Reflection', value: 'Fate Sun Studded Leather Armor of Reflection' },
  { label: 'Grim Shout Ornate Chestplate of the Twins +1', value: 'Grim Shout Ornate Chestplate of the Twins +1' },
  { label: 'Honour Bender Demon Husk of Enlightenment +1', value: 'Honour Bender Demon Husk of Enlightenment +1' },
  { label: 'Honour Grasp Ornate Chestplate of Vitriol +1', value: 'Honour Grasp Ornate Chestplate of Vitriol +1' },
  { label: 'Oblivion Moon Ornate Chestplate of Giants +1', value: 'Oblivion Moon Ornate Chestplate of Giants +1' },
  { label: 'Pain Tear Studded Leather Armor of the Twins', value: 'Pain Tear Studded Leather Armor of the Twins' },
  { label: 'Blight Moon Ornate Chestplate of Vitriol +1', value: 'Blight Moon Ornate Chestplate of Vitriol +1' },
  { label: 'Blight Peak Hard Leather Armor of Titans +1', value: 'Blight Peak Hard Leather Armor of Titans +1' },
  { label: 'Brimstone Shout Linen Robe of Protection +1', value: 'Brimstone Shout Linen Robe of Protection +1' },
  { label: 'Carrion Tear Studded Leather Armor of Skill', value: 'Carrion Tear Studded Leather Armor of Skill' },
  { label: 'Cataclysm Bender Ring Mail of Perfection +1', value: 'Cataclysm Bender Ring Mail of Perfection +1' },
  { label: 'Cataclysm Grasp Linen Robe of Protection +1', value: 'Cataclysm Grasp Linen Robe of Protection +1' },
  { label: 'Corpse Sun Studded Leather Armor of the Fox', value: 'Corpse Sun Studded Leather Armor of the Fox' },
  { label: 'Corruption Grasp Linen Robe of the Twins +1', value: 'Corruption Grasp Linen Robe of the Twins +1' },
  { label: 'Eagle Bender Hard Leather Armor of Anger +1', value: 'Eagle Bender Hard Leather Armor of Anger +1' },
  { label: 'Eagle Grasp Ornate Chestplate of Vitriol +1', value: 'Eagle Grasp Ornate Chestplate of Vitriol +1' },
  { label: 'Foe Moon Hard Leather Armor of the Twins +1', value: 'Foe Moon Hard Leather Armor of the Twins +1' },
  { label: 'Ghoul Root Studded Leather Armor of Vitriol', value: 'Ghoul Root Studded Leather Armor of Vitriol' },
  { label: 'Honour Grasp Ornate Chestplate of Giants +1', value: 'Honour Grasp Ornate Chestplate of Giants +1' },
  { label: 'Hypnotic Tear Holy Chestplate of Brilliance', value: 'Hypnotic Tear Holy Chestplate of Brilliance' },
  { label: 'Hypnotic Tear Studded Leather Armor of Rage', value: 'Hypnotic Tear Studded Leather Armor of Rage' },
  { label: 'Kraken Bender Hard Leather Armor of Fury +1', value: 'Kraken Bender Hard Leather Armor of Fury +1' },
  { label: 'Kraken Bite Hard Leather Armor of Titans +1', value: 'Kraken Bite Hard Leather Armor of Titans +1' },
  { label: 'Kraken Moon Ornate Chestplate of Vitriol +1', value: 'Kraken Moon Ornate Chestplate of Vitriol +1' },
  { label: 'Kraken Shout Ornate Chestplate of Giants +1', value: 'Kraken Shout Ornate Chestplate of Giants +1' },
  { label: "Light's Glow Studded Leather Armor of Skill", value: "Light's Glow Studded Leather Armor of Skill" },
  { label: 'Maelstrom Root Holy Chestplate of Detection', value: 'Maelstrom Root Holy Chestplate of Detection' },
  { label: 'Oblivion Peak Ornate Chestplate of Power +1', value: 'Oblivion Peak Ornate Chestplate of Power +1' },
  { label: 'Apocalypse Glow Holy Chestplate of Vitriol', value: 'Apocalypse Glow Holy Chestplate of Vitriol' },
  { label: 'Apocalypse Sun Chain Mail of Enlightenment', value: 'Apocalypse Sun Chain Mail of Enlightenment' },
  { label: 'Bramble Roar Holy Chestplate of Perfection', value: 'Bramble Roar Holy Chestplate of Perfection' },
  { label: 'Bramble Root Holy Chestplate of Brilliance', value: 'Bramble Root Holy Chestplate of Brilliance' },
  { label: 'Brimstone Grasp Ring Mail of Protection +1', value: 'Brimstone Grasp Ring Mail of Protection +1' },
  { label: 'Cataclysm Peak Linen Robe of Reflection +1', value: 'Cataclysm Peak Linen Robe of Reflection +1' },
  { label: 'Cataclysm Shout Ring Mail of Protection +1', value: 'Cataclysm Shout Ring Mail of Protection +1' },
  { label: 'Demon Shout Ornate Chestplate of Giants +1', value: 'Demon Shout Ornate Chestplate of Giants +1' },
  { label: 'Dragon Glow Studded Leather Armor of Skill', value: 'Dragon Glow Studded Leather Armor of Skill' },
  { label: 'Dragon Root Studded Leather Armor of Skill', value: 'Dragon Root Studded Leather Armor of Skill' },
  { label: 'Eagle Shout Ornate Chestplate of Giants +1', value: 'Eagle Shout Ornate Chestplate of Giants +1' },
  { label: 'Havoc Glow Studded Leather Armor of Giants', value: 'Havoc Glow Studded Leather Armor of Giants' },
  { label: 'Honour Peak Hard Leather Armor of Power +1', value: 'Honour Peak Hard Leather Armor of Power +1' },
  { label: 'Hypnotic Root Holy Chestplate of the Twins', value: 'Hypnotic Root Holy Chestplate of the Twins' },
  { label: 'Kraken Moon Hard Leather Armor of Skill +1', value: 'Kraken Moon Hard Leather Armor of Skill +1' },
  { label: "Light's Roar Holy Chestplate of Reflection", value: "Light's Roar Holy Chestplate of Reflection" },
  { label: "Light's Root Holy Chestplate of Protection", value: "Light's Root Holy Chestplate of Protection" },
  { label: "Light's Tear Holy Chestplate of Brilliance", value: "Light's Tear Holy Chestplate of Brilliance" },
  { label: 'Morbid Roar Studded Leather Armor of Anger', value: 'Morbid Roar Studded Leather Armor of Anger' },
  { label: 'Oblivion Peak Ornate Chestplate of Fury +1', value: 'Oblivion Peak Ornate Chestplate of Fury +1' },
  { label: 'Oblivion Shout Demon Husk of Brilliance +1', value: 'Oblivion Shout Demon Husk of Brilliance +1' },
  { label: 'Pain Whisper Holy Chestplate of Perfection', value: 'Pain Whisper Holy Chestplate of Perfection' },
  { label: 'Apocalypse Sun Holy Chestplate of the Fox', value: 'Apocalypse Sun Holy Chestplate of the Fox' },
  { label: 'Bramble Sun Holy Chestplate of Reflection', value: 'Bramble Sun Holy Chestplate of Reflection' },
  { label: 'Bramble Tear Holy Chestplate of the Twins', value: 'Bramble Tear Holy Chestplate of the Twins' },
  { label: 'Corpse Glow Studded Leather Armor of Rage', value: 'Corpse Glow Studded Leather Armor of Rage' },
  { label: 'Corpse Tear Holy Chestplate of Brilliance', value: 'Corpse Tear Holy Chestplate of Brilliance' },
  { label: 'Demon Moon Hard Leather Armor of Skill +1', value: 'Demon Moon Hard Leather Armor of Skill +1' },
  { label: 'Demon Peak Ornate Chestplate of Titans +1', value: 'Demon Peak Ornate Chestplate of Titans +1' },
  { label: 'Dusk Sun Studded Leather Armor of the Fox', value: 'Dusk Sun Studded Leather Armor of the Fox' },
  { label: 'Gloom Bite Ornate Chestplate of Titans +1', value: 'Gloom Bite Ornate Chestplate of Titans +1' },
  { label: 'Grim Bender Ornate Chestplate of Anger +1', value: 'Grim Bender Ornate Chestplate of Anger +1' },
  { label: 'Grim Bender Ornate Chestplate of Power +1', value: 'Grim Bender Ornate Chestplate of Power +1' },
  { label: 'Honour Bite Ring Mail of Enlightenment +1', value: 'Honour Bite Ring Mail of Enlightenment +1' },
  { label: 'Hypnotic Whisper Chain Mail of Perfection', value: 'Hypnotic Whisper Chain Mail of Perfection' },
  { label: 'Hypnotic Whisper Chain Mail of Reflection', value: 'Hypnotic Whisper Chain Mail of Reflection' },
  { label: "Light's Root Holy Chestplate of the Twins", value: "Light's Root Holy Chestplate of the Twins" },
  { label: "Light's Whisper Holy Chestplate of Titans", value: "Light's Whisper Holy Chestplate of Titans" },
  { label: 'Maelstrom Tear Holy Chestplate of Vitriol', value: 'Maelstrom Tear Holy Chestplate of Vitriol' },
  { label: 'Morbid Roar Holy Chestplate of Perfection', value: 'Morbid Roar Holy Chestplate of Perfection' },
  { label: 'Morbid Root Studded Leather Armor of Rage', value: 'Morbid Root Studded Leather Armor of Rage' },
  { label: 'Morbid Tear Studded Leather Armor of Rage', value: 'Morbid Tear Studded Leather Armor of Rage' },
  { label: 'Oblivion Shout Demon Husk of the Twins +1', value: 'Oblivion Shout Demon Husk of the Twins +1' },
  { label: 'Pandemonium Bite Linen Robe of the Fox +1', value: 'Pandemonium Bite Linen Robe of the Fox +1' },
  { label: 'Apocalypse Glow Chain Mail of Protection', value: 'Apocalypse Glow Chain Mail of Protection' },
  { label: 'Armageddon Grasp Linen Robe of Giants +1', value: 'Armageddon Grasp Linen Robe of Giants +1' },
  { label: 'Armageddon Shout Linen Robe of Giants +1', value: 'Armageddon Shout Linen Robe of Giants +1' },
  { label: 'Behemoth Roar Holy Chestplate of the Fox', value: 'Behemoth Roar Holy Chestplate of the Fox' },
  { label: 'Corpse Sun Holy Chestplate of Reflection', value: 'Corpse Sun Holy Chestplate of Reflection' },
  { label: 'Corpse Whisper Holy Chestplate of Titans', value: 'Corpse Whisper Holy Chestplate of Titans' },
  { label: 'Corruption Grasp Ring Mail of Vitriol +1', value: 'Corruption Grasp Ring Mail of Vitriol +1' },
  { label: 'Corruption Moon Linen Robe of Vitriol +1', value: 'Corruption Moon Linen Robe of Vitriol +1' },
  { label: 'Death Root Holy Chestplate of Protection', value: 'Death Root Holy Chestplate of Protection' },
  { label: 'Dragon Root Holy Chestplate of the Twins', value: 'Dragon Root Holy Chestplate of the Twins' },
  { label: 'Dragon Tear Holy Chestplate of the Twins', value: 'Dragon Tear Holy Chestplate of the Twins' },
  { label: 'Dusk Sun Studded Leather Armor of Titans', value: 'Dusk Sun Studded Leather Armor of Titans' },
  { label: 'Fate Root Studded Leather Armor of Skill', value: 'Fate Root Studded Leather Armor of Skill' },
  { label: 'Foe Bender Ring Mail of Enlightenment +1', value: 'Foe Bender Ring Mail of Enlightenment +1' },
  { label: 'Foe Bite Ornate Chestplate of the Fox +1', value: 'Foe Bite Ornate Chestplate of the Fox +1' },
  { label: 'Foe Grasp Hard Leather Armor of Skill +1', value: 'Foe Grasp Hard Leather Armor of Skill +1' },
  { label: 'Foe Peak Ornate Chestplate of the Fox +1', value: 'Foe Peak Ornate Chestplate of the Fox +1' },
  { label: 'Ghoul Root Studded Leather Armor of Rage', value: 'Ghoul Root Studded Leather Armor of Rage' },
  { label: 'Ghoul Sun Studded Leather Armor of Anger', value: 'Ghoul Sun Studded Leather Armor of Anger' },
  { label: 'Gloom Bender Demon Husk of Reflection +1', value: 'Gloom Bender Demon Husk of Reflection +1' },
  { label: 'Golem Roar Holy Chestplate of Reflection', value: 'Golem Roar Holy Chestplate of Reflection' },
  { label: 'Golem Root Holy Chestplate of Brilliance', value: 'Golem Root Holy Chestplate of Brilliance' },
  { label: 'Golem Root Studded Leather Armor of Rage', value: 'Golem Root Studded Leather Armor of Rage' },
  { label: 'Golem Sun Studded Leather Armor of Anger', value: 'Golem Sun Studded Leather Armor of Anger' },
  { label: 'Golem Sun Studded Leather Armor of Power', value: 'Golem Sun Studded Leather Armor of Power' },
  { label: 'Grim Bite Hard Leather Armor of Power +1', value: 'Grim Bite Hard Leather Armor of Power +1' },
  { label: 'Grim Peak Demon Husk of Enlightenment +1', value: 'Grim Peak Demon Husk of Enlightenment +1' },
  { label: 'Honour Shout Linen Robe of Protection +1', value: 'Honour Shout Linen Robe of Protection +1' },
  { label: 'Kraken Bender Ring Mail of Perfection +1', value: 'Kraken Bender Ring Mail of Perfection +1' },
  { label: 'Kraken Moon Ornate Chestplate of Rage +1', value: 'Kraken Moon Ornate Chestplate of Rage +1' },
  { label: 'Maelstrom Whisper Shirt of Enlightenment', value: 'Maelstrom Whisper Shirt of Enlightenment' },
  { label: 'Mind Bite Ornate Chestplate of Titans +1', value: 'Mind Bite Ornate Chestplate of Titans +1' },
  { label: 'Morbid Root Holy Chestplate of the Twins', value: 'Morbid Root Holy Chestplate of the Twins' },
  { label: 'Morbid Sun Studded Leather Armor of Fury', value: 'Morbid Sun Studded Leather Armor of Fury' },
  { label: 'Morbid Whisper Holy Chestplate of Titans', value: 'Morbid Whisper Holy Chestplate of Titans' },
  { label: 'Pain Glow Studded Leather Armor of Skill', value: 'Pain Glow Studded Leather Armor of Skill' },
  { label: 'Pandemonium Grasp Ring Mail of Giants +1', value: 'Pandemonium Grasp Ring Mail of Giants +1' },
  { label: 'Apocalypse Root Chain Mail of Detection', value: 'Apocalypse Root Chain Mail of Detection' },
  { label: 'Apocalypse Sun Holy Chestplate of Anger', value: 'Apocalypse Sun Holy Chestplate of Anger' },
  { label: 'Apocalypse Tear Holy Chestplate of Rage', value: 'Apocalypse Tear Holy Chestplate of Rage' },
  { label: 'Armageddon Bite Demon Husk of Titans +1', value: 'Armageddon Bite Demon Husk of Titans +1' },
  { label: 'Armageddon Peak Ring Mail of the Fox +1', value: 'Armageddon Peak Ring Mail of the Fox +1' },
  { label: 'Blight Grasp Ring Mail of Protection +1', value: 'Blight Grasp Ring Mail of Protection +1' },
  { label: 'Corruption Grasp Linen Robe of Skill +1', value: 'Corruption Grasp Linen Robe of Skill +1' },
  { label: 'Death Tear Holy Chestplate of Detection', value: 'Death Tear Holy Chestplate of Detection' },
  { label: 'Demon Bender Ring Mail of Reflection +1', value: 'Demon Bender Ring Mail of Reflection +1' },
  { label: 'Dread Moon Ornate Chestplate of Rage +1', value: 'Dread Moon Ornate Chestplate of Rage +1' },
  { label: 'Dread Shout Linen Robe of Brilliance +1', value: 'Dread Shout Linen Robe of Brilliance +1' },
  { label: 'Dusk Root Holy Chestplate of Protection', value: 'Dusk Root Holy Chestplate of Protection' },
  { label: 'Eagle Shout Demon Husk of Brilliance +1', value: 'Eagle Shout Demon Husk of Brilliance +1' },
  { label: 'Eagle Shout Demon Husk of Protection +1', value: 'Eagle Shout Demon Husk of Protection +1' },
  { label: 'Eagle Shout Linen Robe of Brilliance +1', value: 'Eagle Shout Linen Robe of Brilliance +1' },
  { label: 'Havoc Glow Holy Chestplate of the Twins', value: 'Havoc Glow Holy Chestplate of the Twins' },
  { label: 'Honour Grasp Demon Husk of the Twins +1', value: 'Honour Grasp Demon Husk of the Twins +1' },
  { label: 'Kraken Bite Linen Robe of Perfection +1', value: 'Kraken Bite Linen Robe of Perfection +1' },
  { label: 'Kraken Peak Demon Husk of Perfection +1', value: 'Kraken Peak Demon Husk of Perfection +1' },
  { label: 'Kraken Shout Linen Robe of Detection +1', value: 'Kraken Shout Linen Robe of Detection +1' },
  { label: "Light's Whisper Silk Robe of Perfection", value: "Light's Whisper Silk Robe of Perfection" },
  { label: 'Mind Bender Demon Husk of Reflection +1', value: 'Mind Bender Demon Husk of Reflection +1' },
  { label: 'Morbid Whisper Chain Mail of Reflection', value: 'Morbid Whisper Chain Mail of Reflection' },
  { label: 'Oblivion Shout Linen Robe of Vitriol +1', value: 'Oblivion Shout Linen Robe of Vitriol +1' },
  { label: 'Pain Glow Holy Chestplate of Protection', value: 'Pain Glow Holy Chestplate of Protection' },
  { label: 'Apocalypse Whisper Chain Mail of Power', value: 'Apocalypse Whisper Chain Mail of Power' },
  { label: 'Armageddon Bite Demon Husk of Power +1', value: 'Armageddon Bite Demon Husk of Power +1' },
  { label: 'Behemoth Roar Holy Chestplate of Anger', value: 'Behemoth Roar Holy Chestplate of Anger' },
  { label: 'Blight Moon Demon Husk of the Twins +1', value: 'Blight Moon Demon Husk of the Twins +1' },
  { label: 'Blight Moon Linen Robe of Detection +1', value: 'Blight Moon Linen Robe of Detection +1' },
  { label: 'Brimstone Grasp Ring Mail of Giants +1', value: 'Brimstone Grasp Ring Mail of Giants +1' },
  { label: 'Cataclysm Bite Demon Husk of Titans +1', value: 'Cataclysm Bite Demon Husk of Titans +1' },
  { label: 'Cataclysm Peak Ring Mail of the Fox +1', value: 'Cataclysm Peak Ring Mail of the Fox +1' },
  { label: 'Corruption Bite Demon Husk of Anger +1', value: 'Corruption Bite Demon Husk of Anger +1' },
  { label: 'Corruption Peak Demon Husk of Anger +1', value: 'Corruption Peak Demon Husk of Anger +1' },
  { label: 'Demon Moon Demon Husk of Brilliance +1', value: 'Demon Moon Demon Husk of Brilliance +1' },
  { label: 'Demon Moon Demon Husk of Protection +1', value: 'Demon Moon Demon Husk of Protection +1' },
  { label: 'Demon Peak Linen Robe of Perfection +1', value: 'Demon Peak Linen Robe of Perfection +1' },
  { label: 'Demon Shout Linen Robe of the Twins +1', value: 'Demon Shout Linen Robe of the Twins +1' },
  { label: 'Dragon Root Holy Chestplate of Vitriol', value: 'Dragon Root Holy Chestplate of Vitriol' },
  { label: 'Dragon Whisper Silk Robe of Perfection', value: 'Dragon Whisper Silk Robe of Perfection' },
  { label: 'Dusk Sun Studded Leather Armor of Fury', value: 'Dusk Sun Studded Leather Armor of Fury' },
  { label: 'Eagle Grasp Linen Robe of the Twins +1', value: 'Eagle Grasp Linen Robe of the Twins +1' },
  { label: 'Eagle Shout Linen Robe of the Twins +1', value: 'Eagle Shout Linen Robe of the Twins +1' },
  { label: 'Ghoul Whisper Holy Chestplate of Anger', value: 'Ghoul Whisper Holy Chestplate of Anger' },
  { label: 'Gloom Grasp Demon Husk of Detection +1', value: 'Gloom Grasp Demon Husk of Detection +1' },
  { label: 'Golem Whisper Holy Chestplate of Anger', value: 'Golem Whisper Holy Chestplate of Anger' },
  { label: 'Havoc Whisper Holy Chestplate of Anger', value: 'Havoc Whisper Holy Chestplate of Anger' },
  { label: 'Honour Moon Demon Husk of Detection +1', value: 'Honour Moon Demon Husk of Detection +1' },
  { label: 'Hypnotic Glow Holy Chestplate of Skill', value: 'Hypnotic Glow Holy Chestplate of Skill' },
  { label: 'Hypnotic Tear Chain Mail of Brilliance', value: 'Hypnotic Tear Chain Mail of Brilliance' },
  { label: 'Kraken Bender Linen Robe of the Fox +1', value: 'Kraken Bender Linen Robe of the Fox +1' },
  { label: 'Maelstrom Roar Silk Robe of Reflection', value: 'Maelstrom Roar Silk Robe of Reflection' },
  { label: 'Maelstrom Root Silk Robe of Brilliance', value: 'Maelstrom Root Silk Robe of Brilliance' },
  { label: 'Maelstrom Tear Holy Chestplate of Rage', value: 'Maelstrom Tear Holy Chestplate of Rage' },
  { label: 'Maelstrom Whisper Chain Mail of Titans', value: 'Maelstrom Whisper Chain Mail of Titans' },
  { label: 'Mind Shout Linen Robe of Protection +1', value: 'Mind Shout Linen Robe of Protection +1' },
  { label: 'Oblivion Bite Demon Husk of the Fox +1', value: 'Oblivion Bite Demon Husk of the Fox +1' },
  { label: 'Armageddon Bite Linen Robe of Fury +1', value: 'Armageddon Bite Linen Robe of Fury +1' },
  { label: 'Behemoth Root Silk Robe of Brilliance', value: 'Behemoth Root Silk Robe of Brilliance' },
  { label: 'Bramble Roar Holy Chestplate of Power', value: 'Bramble Roar Holy Chestplate of Power' },
  { label: 'Bramble Root Holy Chestplate of Skill', value: 'Bramble Root Holy Chestplate of Skill' },
  { label: 'Bramble Tear Holy Chestplate of Skill', value: 'Bramble Tear Holy Chestplate of Skill' },
  { label: 'Brimstone Peak Demon Husk of Anger +1', value: 'Brimstone Peak Demon Husk of Anger +1' },
  { label: 'Brimstone Shout Linen Robe of Rage +1', value: 'Brimstone Shout Linen Robe of Rage +1' },
  { label: 'Cataclysm Peak Linen Robe of Anger +1', value: 'Cataclysm Peak Linen Robe of Anger +1' },
  { label: 'Cataclysm Shout Ring Mail of Skill +1', value: 'Cataclysm Shout Ring Mail of Skill +1' },
  { label: 'Corruption Peak Linen Robe of Fury +1', value: 'Corruption Peak Linen Robe of Fury +1' },
  { label: 'Death Root Holy Chestplate of Vitriol', value: 'Death Root Holy Chestplate of Vitriol' },
  { label: 'Demon Moon Linen Robe of Detection +1', value: 'Demon Moon Linen Robe of Detection +1' },
  { label: 'Dread Bite Ring Mail of Perfection +1', value: 'Dread Bite Ring Mail of Perfection +1' },
  { label: 'Dread Moon Ring Mail of Protection +1', value: 'Dread Moon Ring Mail of Protection +1' },
  { label: 'Eagle Moon Linen Robe of the Twins +1', value: 'Eagle Moon Linen Robe of the Twins +1' },
  { label: 'Eagle Moon Ring Mail of Protection +1', value: 'Eagle Moon Ring Mail of Protection +1' },
  { label: 'Ghoul Sun Chain Mail of Enlightenment', value: 'Ghoul Sun Chain Mail of Enlightenment' },
  { label: 'Grim Peak Linen Robe of Reflection +1', value: 'Grim Peak Linen Robe of Reflection +1' },
  { label: 'Havoc Whisper Holy Chestplate of Fury', value: 'Havoc Whisper Holy Chestplate of Fury' },
  { label: 'Hypnotic Roar Silk Robe of Perfection', value: 'Hypnotic Roar Silk Robe of Perfection' },
  { label: 'Hypnotic Sun Chain Mail of Reflection', value: 'Hypnotic Sun Chain Mail of Reflection' },
  { label: 'Hypnotic Sun Holy Chestplate of Power', value: 'Hypnotic Sun Holy Chestplate of Power' },
  { label: "Light's Root Chain Mail of Brilliance", value: "Light's Root Chain Mail of Brilliance" },
  { label: 'Mind Grasp Ring Mail of Brilliance +1', value: 'Mind Grasp Ring Mail of Brilliance +1' },
  { label: 'Mind Peak Demon Husk of Reflection +1', value: 'Mind Peak Demon Husk of Reflection +1' },
  { label: 'Behemoth Roar Shirt of Enlightenment', value: 'Behemoth Roar Shirt of Enlightenment' },
  { label: 'Blight Moon Linen Robe of Vitriol +1', value: 'Blight Moon Linen Robe of Vitriol +1' },
  { label: 'Bramble Sun Chain Mail of Perfection', value: 'Bramble Sun Chain Mail of Perfection' },
  { label: 'Bramble Tear Chain Mail of Detection', value: 'Bramble Tear Chain Mail of Detection' },
  { label: 'Bramble Tear Holy Chestplate of Rage', value: 'Bramble Tear Holy Chestplate of Rage' },
  { label: 'Carrion Roar Silk Robe of Reflection', value: 'Carrion Roar Silk Robe of Reflection' },
  { label: 'Carrion Sun Holy Chestplate of Anger', value: 'Carrion Sun Holy Chestplate of Anger' },
  { label: 'Corpse Roar Holy Chestplate of Anger', value: 'Corpse Roar Holy Chestplate of Anger' },
  { label: 'Corpse Sun Holy Chestplate of Titans', value: 'Corpse Sun Holy Chestplate of Titans' },
  { label: 'Corruption Bite Ring Mail of Fury +1', value: 'Corruption Bite Ring Mail of Fury +1' },
  { label: 'Demon Grasp Linen Robe of Vitriol +1', value: 'Demon Grasp Linen Robe of Vitriol +1' },
  { label: 'Dragon Roar Chain Mail of Reflection', value: 'Dragon Roar Chain Mail of Reflection' },
  { label: 'Dread Bender Ring Mail of the Fox +1', value: 'Dread Bender Ring Mail of the Fox +1' },
  { label: 'Dread Shout Linen Robe of Vitriol +1', value: 'Dread Shout Linen Robe of Vitriol +1' },
  { label: 'Eagle Bender Linen Robe of Titans +1', value: 'Eagle Bender Linen Robe of Titans +1' },
  { label: 'Foe Bite Demon Husk of Perfection +1', value: 'Foe Bite Demon Husk of Perfection +1' },
  { label: 'Havoc Whisper Shirt of Enlightenment', value: 'Havoc Whisper Shirt of Enlightenment' },
  { label: 'Honour Grasp Demon Husk of Giants +1', value: 'Honour Grasp Demon Husk of Giants +1' },
  { label: 'Honour Peak Demon Husk of the Fox +1', value: 'Honour Peak Demon Husk of the Fox +1' },
  { label: 'Hypnotic Whisper Shirt of Reflection', value: 'Hypnotic Whisper Shirt of Reflection' },
  { label: 'Kraken Peak Linen Robe of the Fox +1', value: 'Kraken Peak Linen Robe of the Fox +1' },
  { label: 'Kraken Shout Ring Mail of Vitriol +1', value: 'Kraken Shout Ring Mail of Vitriol +1' },
  { label: "Light's Tear Chain Mail of Detection", value: "Light's Tear Chain Mail of Detection" },
  { label: 'Mind Bite Ring Mail of Reflection +1', value: 'Mind Bite Ring Mail of Reflection +1' },
  { label: 'Mind Moon Demon Husk of the Twins +1', value: 'Mind Moon Demon Husk of the Twins +1' },
  { label: 'Mind Peak Ring Mail of Reflection +1', value: 'Mind Peak Ring Mail of Reflection +1' },
  { label: 'Morbid Root Holy Chestplate of Skill', value: 'Morbid Root Holy Chestplate of Skill' },
  { label: 'Apocalypse Glow Shirt of Brilliance', value: 'Apocalypse Glow Shirt of Brilliance' },
  { label: 'Blight Shout Demon Husk of Skill +1', value: 'Blight Shout Demon Husk of Skill +1' },
  { label: 'Bramble Sun Silk Robe of Perfection', value: 'Bramble Sun Silk Robe of Perfection' },
  { label: 'Bramble Whisper Shirt of Reflection', value: 'Bramble Whisper Shirt of Reflection' },
  { label: 'Carrion Tear Silk Robe of Detection', value: 'Carrion Tear Silk Robe of Detection' },
  { label: 'Carrion Whisper Chain Mail of Anger', value: 'Carrion Whisper Chain Mail of Anger' },
  { label: 'Corpse Glow Holy Chestplate of Rage', value: 'Corpse Glow Holy Chestplate of Rage' },
  { label: 'Corpse Tear Silk Robe of Protection', value: 'Corpse Tear Silk Robe of Protection' },
  { label: 'Death Whisper Chain Mail of the Fox', value: 'Death Whisper Chain Mail of the Fox' },
  { label: 'Dragon Root Chain Mail of Detection', value: 'Dragon Root Chain Mail of Detection' },
  { label: 'Dragon Sun Holy Chestplate of Anger', value: 'Dragon Sun Holy Chestplate of Anger' },
  { label: 'Dragon Tear Chain Mail of Detection', value: 'Dragon Tear Chain Mail of Detection' },
  { label: 'Fate Sun Silk Robe of Enlightenment', value: 'Fate Sun Silk Robe of Enlightenment' },
  { label: 'Foe Grasp Ring Mail of the Twins +1', value: 'Foe Grasp Ring Mail of the Twins +1' },
  { label: 'Ghoul Roar Holy Chestplate of Power', value: 'Ghoul Roar Holy Chestplate of Power' },
  { label: 'Golem Glow Chain Mail of Protection', value: 'Golem Glow Chain Mail of Protection' },
  { label: 'Havoc Roar Chain Mail of Perfection', value: 'Havoc Roar Chain Mail of Perfection' },
  { label: 'Honour Bite Ring Mail of the Fox +1', value: 'Honour Bite Ring Mail of the Fox +1' },
  { label: 'Kraken Peak Demon Husk of Titans +1', value: 'Kraken Peak Demon Husk of Titans +1' },
  { label: "Light's Whisper Chain Mail of Anger", value: "Light's Whisper Chain Mail of Anger" },
  { label: "Light's Whisper Shirt of Reflection", value: "Light's Whisper Shirt of Reflection" },
  { label: "Light's Whisper Silk Robe of Titans", value: "Light's Whisper Silk Robe of Titans" },
  { label: 'Mind Bender Ring Mail of the Fox +1', value: 'Mind Bender Ring Mail of the Fox +1' },
  { label: 'Oblivion Peak Linen Robe of Fury +1', value: 'Oblivion Peak Linen Robe of Fury +1' },
  { label: 'Pain Roar Holy Chestplate of Titans', value: 'Pain Roar Holy Chestplate of Titans' },
  { label: 'Apocalypse Sun Shirt of Reflection', value: 'Apocalypse Sun Shirt of Reflection' },
  { label: 'Death Root Holy Chestplate of Rage', value: 'Death Root Holy Chestplate of Rage' },
  { label: 'Death Tear Chain Mail of the Twins', value: 'Death Tear Chain Mail of the Twins' },
  { label: 'Demon Bender Linen Robe of Fury +1', value: 'Demon Bender Linen Robe of Fury +1' },
  { label: 'Demon Bite Linen Robe of Titans +1', value: 'Demon Bite Linen Robe of Titans +1' },
  { label: 'Dragon Root Silk Robe of Detection', value: 'Dragon Root Silk Robe of Detection' },
  { label: 'Dread Bender Demon Husk of Fury +1', value: 'Dread Bender Demon Husk of Fury +1' },
  { label: 'Dusk Sun Holy Chestplate of Titans', value: 'Dusk Sun Holy Chestplate of Titans' },
  { label: 'Fate Tear Holy Chestplate of Skill', value: 'Fate Tear Holy Chestplate of Skill' },
  { label: 'Foe Grasp Linen Robe of Vitriol +1', value: 'Foe Grasp Linen Robe of Vitriol +1' },
  { label: 'Ghoul Sun Chain Mail of Perfection', value: 'Ghoul Sun Chain Mail of Perfection' },
  { label: 'Ghoul Tear Silk Robe of Protection', value: 'Ghoul Tear Silk Robe of Protection' },
  { label: 'Gloom Bender Ring Mail of Anger +1', value: 'Gloom Bender Ring Mail of Anger +1' },
  { label: 'Gloom Peak Demon Husk of Titans +1', value: 'Gloom Peak Demon Husk of Titans +1' },
  { label: 'Gloom Peak Linen Robe of Titans +1', value: 'Gloom Peak Linen Robe of Titans +1' },
  { label: 'Golem Sun Chain Mail of Perfection', value: 'Golem Sun Chain Mail of Perfection' },
  { label: 'Grim Bender Demon Husk of Power +1', value: 'Grim Bender Demon Husk of Power +1' },
  { label: 'Havoc Tear Silk Robe of Protection', value: 'Havoc Tear Silk Robe of Protection' },
  { label: 'Honour Peak Demon Husk of Anger +1', value: 'Honour Peak Demon Husk of Anger +1' },
  { label: 'Kraken Peak Demon Husk of Anger +1', value: 'Kraken Peak Demon Husk of Anger +1' },
  { label: 'Mind Bender Demon Husk of Anger +1', value: 'Mind Bender Demon Husk of Anger +1' },
  { label: 'Mind Grasp Demon Husk of Giants +1', value: 'Mind Grasp Demon Husk of Giants +1' },
  { label: 'Pain Glow Chain Mail of Brilliance', value: 'Pain Glow Chain Mail of Brilliance' },
  { label: 'Pain Roar Chain Mail of Perfection', value: 'Pain Roar Chain Mail of Perfection' },
  { label: 'Pain Sun Holy Chestplate of Titans', value: 'Pain Sun Holy Chestplate of Titans' },
  { label: 'Behemoth Glow Shirt of Brilliance', value: 'Behemoth Glow Shirt of Brilliance' },
  { label: 'Bramble Glow Silk Robe of Vitriol', value: 'Bramble Glow Silk Robe of Vitriol' },
  { label: 'Bramble Sun Chain Mail of the Fox', value: 'Bramble Sun Chain Mail of the Fox' },
  { label: 'Carrion Glow Silk Robe of Vitriol', value: 'Carrion Glow Silk Robe of Vitriol' },
  { label: 'Corpse Tear Chain Mail of Vitriol', value: 'Corpse Tear Chain Mail of Vitriol' },
  { label: 'Death Sun Silk Robe of Reflection', value: 'Death Sun Silk Robe of Reflection' },
  { label: 'Demon Bite Demon Husk of Power +1', value: 'Demon Bite Demon Husk of Power +1' },
  { label: 'Demon Bite Linen Robe of Power +1', value: 'Demon Bite Linen Robe of Power +1' },
  { label: 'Dragon Roar Chain Mail of the Fox', value: 'Dragon Roar Chain Mail of the Fox' },
  { label: 'Dread Bite Demon Husk of Power +1', value: 'Dread Bite Demon Husk of Power +1' },
  { label: 'Dread Shout Linen Robe of Rage +1', value: 'Dread Shout Linen Robe of Rage +1' },
  { label: 'Dusk Root Holy Chestplate of Rage', value: 'Dusk Root Holy Chestplate of Rage' },
  { label: 'Dusk Tear Holy Chestplate of Rage', value: 'Dusk Tear Holy Chestplate of Rage' },
  { label: 'Dusk Tear Silk Robe of Protection', value: 'Dusk Tear Silk Robe of Protection' },
  { label: 'Eagle Moon Demon Husk of Skill +1', value: 'Eagle Moon Demon Husk of Skill +1' },
  { label: 'Eagle Shout Linen Robe of Rage +1', value: 'Eagle Shout Linen Robe of Rage +1' },
  { label: 'Foe Shout Ring Mail of Vitriol +1', value: 'Foe Shout Ring Mail of Vitriol +1' },
  { label: 'Gloom Bite Ring Mail of Titans +1', value: 'Gloom Bite Ring Mail of Titans +1' },
  { label: 'Gloom Moon Demon Husk of Skill +1', value: 'Gloom Moon Demon Husk of Skill +1' },
  { label: 'Golem Sun Holy Chestplate of Fury', value: 'Golem Sun Holy Chestplate of Fury' },
  { label: 'Grim Grasp Demon Husk of Skill +1', value: 'Grim Grasp Demon Husk of Skill +1' },
  { label: 'Grim Shout Ring Mail of Giants +1', value: 'Grim Shout Ring Mail of Giants +1' },
  { label: 'Havoc Glow Silk Robe of the Twins', value: 'Havoc Glow Silk Robe of the Twins' },
  { label: 'Honour Moon Ring Mail of Skill +1', value: 'Honour Moon Ring Mail of Skill +1' },
  { label: 'Hypnotic Roar Shirt of Perfection', value: 'Hypnotic Roar Shirt of Perfection' },
  { label: 'Kraken Bite Ring Mail of Anger +1', value: 'Kraken Bite Ring Mail of Anger +1' },
  { label: 'Kraken Grasp Ring Mail of Rage +1', value: 'Kraken Grasp Ring Mail of Rage +1' },
  { label: 'Maelstrom Roar Silk Robe of Power', value: 'Maelstrom Roar Silk Robe of Power' },
  { label: 'Mind Shout Demon Husk of Skill +1', value: 'Mind Shout Demon Husk of Skill +1' },
  { label: 'Morbid Roar Chain Mail of the Fox', value: 'Morbid Roar Chain Mail of the Fox' },
  { label: 'Pain Glow Silk Robe of Protection', value: 'Pain Glow Silk Robe of Protection' },
  { label: 'Bramble Roar Shirt of Perfection', value: 'Bramble Roar Shirt of Perfection' },
  { label: 'Bramble Roar Shirt of Reflection', value: 'Bramble Roar Shirt of Reflection' },
  { label: 'Bramble Root Silk Robe of Giants', value: 'Bramble Root Silk Robe of Giants' },
  { label: 'Bramble Tear Chain Mail of Skill', value: 'Bramble Tear Chain Mail of Skill' },
  { label: 'Carrion Glow Shirt of Protection', value: 'Carrion Glow Shirt of Protection' },
  { label: 'Carrion Root Chain Mail of Skill', value: 'Carrion Root Chain Mail of Skill' },
  { label: 'Dragon Glow Chain Mail of Giants', value: 'Dragon Glow Chain Mail of Giants' },
  { label: 'Dragon Glow Silk Robe of Vitriol', value: 'Dragon Glow Silk Robe of Vitriol' },
  { label: 'Dusk Sun Holy Chestplate of Fury', value: 'Dusk Sun Holy Chestplate of Fury' },
  { label: 'Eagle Grasp Ring Mail of Rage +1', value: 'Eagle Grasp Ring Mail of Rage +1' },
  { label: 'Foe Bite Ring Mail of the Fox +1', value: 'Foe Bite Ring Mail of the Fox +1' },
  { label: 'Foe Moon Linen Robe of Giants +1', value: 'Foe Moon Linen Robe of Giants +1' },
  { label: 'Gloom Bite Demon Husk of Fury +1', value: 'Gloom Bite Demon Husk of Fury +1' },
  { label: 'Gloom Peak Demon Husk of Fury +1', value: 'Gloom Peak Demon Husk of Fury +1' },
  { label: 'Hypnotic Root Silk Robe of Skill', value: 'Hypnotic Root Silk Robe of Skill' },
  { label: "Light's Glow Shirt of Protection", value: "Light's Glow Shirt of Protection" },
  { label: 'Mind Bite Linen Robe of Anger +1', value: 'Mind Bite Linen Robe of Anger +1' },
  { label: 'Mind Grasp Ring Mail of Skill +1', value: 'Mind Grasp Ring Mail of Skill +1' },
  { label: 'Mind Peak Ring Mail of Titans +1', value: 'Mind Peak Ring Mail of Titans +1' },
  { label: 'Behemoth Whisper Shirt of Power', value: 'Behemoth Whisper Shirt of Power' },
  { label: 'Bramble Glow Shirt of the Twins', value: 'Bramble Glow Shirt of the Twins' },
  { label: 'Bramble Roar Chain Mail of Fury', value: 'Bramble Roar Chain Mail of Fury' },
  { label: 'Bramble Sun Silk Robe of Titans', value: 'Bramble Sun Silk Robe of Titans' },
  { label: 'Carrion Glow Chain Mail of Rage', value: 'Carrion Glow Chain Mail of Rage' },
  { label: 'Carrion Tear Chain Mail of Rage', value: 'Carrion Tear Chain Mail of Rage' },
  { label: 'Corpse Glow Shirt of Brilliance', value: 'Corpse Glow Shirt of Brilliance' },
  { label: 'Corpse Sun Silk Robe of the Fox', value: 'Corpse Sun Silk Robe of the Fox' },
  { label: 'Death Roar Silk Robe of the Fox', value: 'Death Roar Silk Robe of the Fox' },
  { label: 'Dragon Glow Chain Mail of Skill', value: 'Dragon Glow Chain Mail of Skill' },
  { label: 'Dragon Glow Silk Robe of Giants', value: 'Dragon Glow Silk Robe of Giants' },
  { label: 'Dragon Root Shirt of Brilliance', value: 'Dragon Root Shirt of Brilliance' },
  { label: 'Fate Roar Chain Mail of the Fox', value: 'Fate Roar Chain Mail of the Fox' },
  { label: 'Fate Sun Shirt of Enlightenment', value: 'Fate Sun Shirt of Enlightenment' },
  { label: 'Foe Bite Linen Robe of Anger +1', value: 'Foe Bite Linen Robe of Anger +1' },
  { label: 'Foe Moon Linen Robe of Skill +1', value: 'Foe Moon Linen Robe of Skill +1' },
  { label: 'Foe Moon Ring Mail of Giants +1', value: 'Foe Moon Ring Mail of Giants +1' },
  { label: 'Golem Tear Silk Robe of Vitriol', value: 'Golem Tear Silk Robe of Vitriol' },
  { label: 'Havoc Whisper Silk Robe of Fury', value: 'Havoc Whisper Silk Robe of Fury' },
  { label: "Light's Glow Silk Robe of Skill", value: "Light's Glow Silk Robe of Skill" },
  { label: "Light's Sun Shirt of Perfection", value: "Light's Sun Shirt of Perfection" },
  { label: 'Morbid Roar Silk Robe of Titans', value: 'Morbid Roar Silk Robe of Titans' },
  { label: 'Pain Glow Chain Mail of Vitriol', value: 'Pain Glow Chain Mail of Vitriol' },
  { label: 'Behemoth Whisper Shirt of Fury', value: 'Behemoth Whisper Shirt of Fury' },
  { label: 'Bramble Sun Silk Robe of Power', value: 'Bramble Sun Silk Robe of Power' },
  { label: 'Bramble Tear Silk Robe of Rage', value: 'Bramble Tear Silk Robe of Rage' },
  { label: 'Death Roar Chain Mail of Power', value: 'Death Roar Chain Mail of Power' },
  { label: 'Death Root Silk Robe of Giants', value: 'Death Root Silk Robe of Giants' },
  { label: 'Dragon Tear Shirt of the Twins', value: 'Dragon Tear Shirt of the Twins' },
  { label: 'Fate Whisper Silk Robe of Fury', value: 'Fate Whisper Silk Robe of Fury' },
  { label: 'Foe Moon Linen Robe of Rage +1', value: 'Foe Moon Linen Robe of Rage +1' },
  { label: 'Ghoul Root Chain Mail of Skill', value: 'Ghoul Root Chain Mail of Skill' },
  { label: 'Ghoul Root Shirt of Protection', value: 'Ghoul Root Shirt of Protection' },
  { label: 'Golem Glow Chain Mail of Skill', value: 'Golem Glow Chain Mail of Skill' },
  { label: 'Golem Glow Shirt of Protection', value: 'Golem Glow Shirt of Protection' },
  { label: 'Grim Bite Ring Mail of Fury +1', value: 'Grim Bite Ring Mail of Fury +1' },
  { label: 'Hypnotic Glow Shirt of Vitriol', value: 'Hypnotic Glow Shirt of Vitriol' },
  { label: 'Morbid Root Shirt of the Twins', value: 'Morbid Root Shirt of the Twins' },
  { label: 'Morbid Tear Shirt of Detection', value: 'Morbid Tear Shirt of Detection' },
  { label: 'Ornate Chestplate of the Twins', value: 'Ornate Chestplate of the Twins' },
  { label: 'Pain Whisper Silk Robe of Fury', value: 'Pain Whisper Silk Robe of Fury' },
  { label: 'Apocalypse Tear Shirt of Rage', value: 'Apocalypse Tear Shirt of Rage' },
  { label: 'Carrion Whisper Shirt of Fury', value: 'Carrion Whisper Shirt of Fury' },
  { label: 'Corpse Glow Silk Robe of Rage', value: 'Corpse Glow Silk Robe of Rage' },
  { label: 'Corpse Root Silk Robe of Rage', value: 'Corpse Root Silk Robe of Rage' },
  { label: 'Corpse Sun Chain Mail of Fury', value: 'Corpse Sun Chain Mail of Fury' },
  { label: 'Death Sun Chain Mail of Anger', value: 'Death Sun Chain Mail of Anger' },
  { label: 'Dragon Sun Chain Mail of Fury', value: 'Dragon Sun Chain Mail of Fury' },
  { label: 'Dragon Whisper Shirt of Power', value: 'Dragon Whisper Shirt of Power' },
  { label: 'Dusk Roar Shirt of Reflection', value: 'Dusk Roar Shirt of Reflection' },
  { label: 'Fate Glow Chain Mail of Skill', value: 'Fate Glow Chain Mail of Skill' },
  { label: 'Fate Roar Shirt of Perfection', value: 'Fate Roar Shirt of Perfection' },
  { label: 'Golem Tear Chain Mail of Rage', value: 'Golem Tear Chain Mail of Rage' },
  { label: 'Havoc Glow Chain Mail of Rage', value: 'Havoc Glow Chain Mail of Rage' },
  { label: 'Maelstrom Tear Shirt of Skill', value: 'Maelstrom Tear Shirt of Skill' },
  { label: 'Morbid Tear Silk Robe of Rage', value: 'Morbid Tear Silk Robe of Rage' },
  { label: 'Pain Glow Shirt of Brilliance', value: 'Pain Glow Shirt of Brilliance' },
  { label: 'Behemoth Roar Shirt of Power', value: 'Behemoth Roar Shirt of Power' },
  { label: 'Corpse Sun Silk Robe of Fury', value: 'Corpse Sun Silk Robe of Fury' },
  { label: 'Dusk Glow Silk Robe of Skill', value: 'Dusk Glow Silk Robe of Skill' },
  { label: 'Dusk Roar Silk Robe of Anger', value: 'Dusk Roar Silk Robe of Anger' },
  { label: 'Dusk Root Chain Mail of Rage', value: 'Dusk Root Chain Mail of Rage' },
  { label: 'Fate Roar Silk Robe of Power', value: 'Fate Roar Silk Robe of Power' },
  { label: 'Fate Sun Chain Mail of Power', value: 'Fate Sun Chain Mail of Power' },
  { label: 'Golem Sun Silk Robe of Power', value: 'Golem Sun Silk Robe of Power' },
  { label: 'Havoc Sun Chain Mail of Fury', value: 'Havoc Sun Chain Mail of Fury' },
  { label: 'Hypnotic Roar Shirt of Anger', value: 'Hypnotic Roar Shirt of Anger' },
  { label: "Light's Root Shirt of Giants", value: "Light's Root Shirt of Giants" },
  { label: 'Maelstrom Tear Shirt of Rage', value: 'Maelstrom Tear Shirt of Rage' },
  { label: 'Morbid Root Shirt of Vitriol', value: 'Morbid Root Shirt of Vitriol' },
  { label: 'Pain Roar Silk Robe of Anger', value: 'Pain Roar Silk Robe of Anger' },
  { label: 'Bramble Roar Shirt of Power', value: 'Bramble Roar Shirt of Power' },
  { label: 'Ghoul Sun Silk Robe of Fury', value: 'Ghoul Sun Silk Robe of Fury' },
  { label: 'Ghoul Whisper Shirt of Fury', value: 'Ghoul Whisper Shirt of Fury' },
  { label: 'Maelstrom Sun Shirt of Fury', value: 'Maelstrom Sun Shirt of Fury' },
  { label: 'Pain Whisper Shirt of Anger', value: 'Pain Whisper Shirt of Anger' },
  { label: 'Bramble Sun Shirt of Anger', value: 'Bramble Sun Shirt of Anger' },
  { label: 'Carrion Root Shirt of Rage', value: 'Carrion Root Shirt of Rage' },
  { label: 'Death Roar Shirt of Titans', value: 'Death Roar Shirt of Titans' },
  { label: 'Dragon Tear Shirt of Skill', value: 'Dragon Tear Shirt of Skill' },
  { label: 'Fate Roar Shirt of the Fox', value: 'Fate Roar Shirt of the Fox' },
  { label: 'Havoc Glow Shirt of Giants', value: 'Havoc Glow Shirt of Giants' },
  { label: 'Hypnotic Sun Shirt of Fury', value: 'Hypnotic Sun Shirt of Fury' },
  { label: 'Pain Glow Shirt of Vitriol', value: 'Pain Glow Shirt of Vitriol' },
  { label: 'Pain Root Shirt of Vitriol', value: 'Pain Root Shirt of Vitriol' },
  { label: 'Fate Sun Shirt of the Fox', value: 'Fate Sun Shirt of the Fox' },
  { label: 'Ghoul Sun Shirt of Titans', value: 'Ghoul Sun Shirt of Titans' },
  { label: 'Ghoul Tear Shirt of Skill', value: 'Ghoul Tear Shirt of Skill' },
  { label: 'Death Sun Shirt of Power', value: 'Death Sun Shirt of Power' },
  { label: 'Dragon Sun Shirt of Fury', value: 'Dragon Sun Shirt of Fury' },
  { label: 'Fate Roar Shirt of Anger', value: 'Fate Roar Shirt of Anger' },
  { label: 'Pain Roar Shirt of Power', value: 'Pain Roar Shirt of Power' },
  { label: 'Pain Sun Shirt of Titans', value: 'Pain Sun Shirt of Titans' },
  { label: 'Fate Sun Shirt of Anger', value: 'Fate Sun Shirt of Anger' },
  { label: 'Divine Robe of the Fox', value: 'Divine Robe of the Fox' },
  { label: 'Pandemonium Moon Demon Husk of Detection +1', value: 'Pandemonium Moon Demon Husk of Detection +1' },
  { label: 'Pandemonium Moon Demon Husk of Rage +1', value: 'Pandemonium Moon Demon Husk of Rage +1' },
  { label: 'Pandemonium Moon Linen Robe of the Twins +1', value: 'Pandemonium Moon Linen Robe of the Twins +1' },
  { label: 'Pandemonium Peak Hard Leather Armor of Anger +1', value: 'Pandemonium Peak Hard Leather Armor of Anger +1' },
  { label: 'Pandemonium Peak Ornate Chestplate of Fury +1', value: 'Pandemonium Peak Ornate Chestplate of Fury +1' },
  { label: 'Pandemonium Peak Ring Mail of Perfection +1', value: 'Pandemonium Peak Ring Mail of Perfection +1' },
  { label: 'Pandemonium Shout Hard Leather Armor of the Twins +1', value: 'Pandemonium Shout Hard Leather Armor of the Twins +1' },
  { label: 'Pandemonium Shout Ornate Chestplate of Detection +1', value: 'Pandemonium Shout Ornate Chestplate of Detection +1' },
  { label: 'Plague Glow Chain Mail of Protection', value: 'Plague Glow Chain Mail of Protection' },
  { label: 'Plague Glow Holy Chestplate of Giants', value: 'Plague Glow Holy Chestplate of Giants' },
  { label: 'Plague Glow Silk Robe of Skill', value: 'Plague Glow Silk Robe of Skill' },
  { label: 'Plague Roar Chain Mail of Fury', value: 'Plague Roar Chain Mail of Fury' },
  { label: 'Plague Roar Chain Mail of Titans', value: 'Plague Roar Chain Mail of Titans' },
  { label: 'Plague Root Chain Mail of Detection', value: 'Plague Root Chain Mail of Detection' },
  { label: 'Plague Root Silk Robe of Vitriol', value: 'Plague Root Silk Robe of Vitriol' },
  { label: 'Plague Sun Studded Leather Armor of Fury', value: 'Plague Sun Studded Leather Armor of Fury' },
  { label: 'Plague Tear Shirt of Skill', value: 'Plague Tear Shirt of Skill' },
  { label: 'Plague Whisper Chain Mail of Perfection', value: 'Plague Whisper Chain Mail of Perfection' },
  { label: 'Plague Whisper Chain Mail of Reflection', value: 'Plague Whisper Chain Mail of Reflection' },
  { label: 'Plague Whisper Studded Leather Armor of Titans', value: 'Plague Whisper Studded Leather Armor of Titans' },
  { label: 'Rage Bender Demon Husk of Anger +1', value: 'Rage Bender Demon Husk of Anger +1' },
  { label: 'Rage Bender Ornate Chestplate of Enlightenment +1', value: 'Rage Bender Ornate Chestplate of Enlightenment +1' },
  { label: 'Rage Bender Ornate Chestplate of Titans +1', value: 'Rage Bender Ornate Chestplate of Titans +1' },
  { label: 'Rage Bite Demon Husk of Perfection +1', value: 'Rage Bite Demon Husk of Perfection +1' },
  { label: 'Rage Bite Hard Leather Armor of Power +1', value: 'Rage Bite Hard Leather Armor of Power +1' },
  { label: 'Rage Bite Linen Robe of Anger +1', value: 'Rage Bite Linen Robe of Anger +1' },
  { label: 'Rage Grasp Hard Leather Armor of Protection +1', value: 'Rage Grasp Hard Leather Armor of Protection +1' },
  { label: 'Rage Grasp Linen Robe of Brilliance +1', value: 'Rage Grasp Linen Robe of Brilliance +1' },
  { label: 'Rage Grasp Ornate Chestplate of Giants +1', value: 'Rage Grasp Ornate Chestplate of Giants +1' },
  { label: 'Rage Moon Ring Mail of the Twins +1', value: 'Rage Moon Ring Mail of the Twins +1' },
  { label: 'Rage Peak Demon Husk of Perfection +1', value: 'Rage Peak Demon Husk of Perfection +1' },
  { label: 'Rage Peak Linen Robe of Reflection +1', value: 'Rage Peak Linen Robe of Reflection +1' },
  { label: 'Rage Shout Demon Husk of Vitriol +1', value: 'Rage Shout Demon Husk of Vitriol +1' },
  { label: 'Rage Shout Ornate Chestplate of Detection +1', value: 'Rage Shout Ornate Chestplate of Detection +1' },
  { label: 'Rage Shout Ring Mail of the Twins +1', value: 'Rage Shout Ring Mail of the Twins +1' },
  { label: 'Ring Mail of Skill', value: 'Ring Mail of Skill' },
  { label: 'Rune Glow Chain Mail of Skill', value: 'Rune Glow Chain Mail of Skill' },
  { label: 'Rune Glow Holy Chestplate of Giants', value: 'Rune Glow Holy Chestplate of Giants' },
  { label: 'Rune Glow Shirt of Giants', value: 'Rune Glow Shirt of Giants' },
  { label: 'Rune Glow Shirt of Rage', value: 'Rune Glow Shirt of Rage' },
  { label: 'Rune Roar Silk Robe of Fury', value: 'Rune Roar Silk Robe of Fury' },
  { label: 'Rune Root Chain Mail of the Twins', value: 'Rune Root Chain Mail of the Twins' },
  { label: 'Rune Root Shirt of Skill', value: 'Rune Root Shirt of Skill' },
  { label: 'Rune Tear Chain Mail of Protection', value: 'Rune Tear Chain Mail of Protection' },
  { label: 'Rune Tear Studded Leather Armor of Detection', value: 'Rune Tear Studded Leather Armor of Detection' },
  { label: 'Rune Tear Studded Leather Armor of Giants', value: 'Rune Tear Studded Leather Armor of Giants' },
  { label: 'Rune Whisper Chain Mail of Reflection', value: 'Rune Whisper Chain Mail of Reflection' },
  { label: 'Shimmering Bender Demon Husk of Fury +1', value: 'Shimmering Bender Demon Husk of Fury +1' },
  { label: 'Shimmering Bender Hard Leather Armor of the Fox +1', value: 'Shimmering Bender Hard Leather Armor of the Fox +1' },
  { label: 'Shimmering Bender Hard Leather Armor of Titans +1', value: 'Shimmering Bender Hard Leather Armor of Titans +1' },
  { label: 'Shimmering Bite Demon Husk of Perfection +1', value: 'Shimmering Bite Demon Husk of Perfection +1' },
  { label: 'Shimmering Grasp Demon Husk of Giants +1', value: 'Shimmering Grasp Demon Husk of Giants +1' },
  { label: 'Shimmering Grasp Ring Mail of Vitriol +1', value: 'Shimmering Grasp Ring Mail of Vitriol +1' },
  { label: 'Shimmering Moon Hard Leather Armor of the Twins +1', value: 'Shimmering Moon Hard Leather Armor of the Twins +1' },
  { label: 'Shimmering Moon Ornate Chestplate of Rage +1', value: 'Shimmering Moon Ornate Chestplate of Rage +1' },
  { label: 'Shimmering Moon Ring Mail of Protection +1', value: 'Shimmering Moon Ring Mail of Protection +1' },
  { label: 'Shimmering Peak Demon Husk of Fury +1', value: 'Shimmering Peak Demon Husk of Fury +1' },
  { label: 'Shimmering Peak Demon Husk of the Fox +1', value: 'Shimmering Peak Demon Husk of the Fox +1' },
  { label: 'Shimmering Peak Linen Robe of Power +1', value: 'Shimmering Peak Linen Robe of Power +1' },
  { label: 'Shimmering Shout Demon Husk of Brilliance +1', value: 'Shimmering Shout Demon Husk of Brilliance +1' },
  { label: 'Shimmering Shout Demon Husk of Detection +1', value: 'Shimmering Shout Demon Husk of Detection +1' },
  { label: 'Shimmering Shout Demon Husk of the Twins +1', value: 'Shimmering Shout Demon Husk of the Twins +1' },
  { label: 'Shimmering Shout Ornate Chestplate of Brilliance +1', value: 'Shimmering Shout Ornate Chestplate of Brilliance +1' },
  { label: 'Shimmering Shout Ornate Chestplate of Protection +1', value: 'Shimmering Shout Ornate Chestplate of Protection +1' },
  { label: 'Shimmering Shout Ring Mail of Detection +1', value: 'Shimmering Shout Ring Mail of Detection +1' },
  { label: 'Silk Robe of Brilliance', value: 'Silk Robe of Brilliance' },
  { label: 'Skull Bender Ornate Chestplate of Reflection +1', value: 'Skull Bender Ornate Chestplate of Reflection +1' },
  { label: 'Skull Bite Ornate Chestplate of Power +1', value: 'Skull Bite Ornate Chestplate of Power +1' },
  { label: 'Skull Grasp Hard Leather Armor of Vitriol +1', value: 'Skull Grasp Hard Leather Armor of Vitriol +1' },
  { label: 'Skull Grasp Linen Robe of Rage +1', value: 'Skull Grasp Linen Robe of Rage +1' },
  { label: 'Skull Moon Demon Husk of Skill +1', value: 'Skull Moon Demon Husk of Skill +1' },
  { label: 'Skull Moon Hard Leather Armor of Detection +1', value: 'Skull Moon Hard Leather Armor of Detection +1' },
  { label: 'Skull Moon Ornate Chestplate of Giants +1', value: 'Skull Moon Ornate Chestplate of Giants +1' },
  { label: 'Skull Moon Ring Mail of Brilliance +1', value: 'Skull Moon Ring Mail of Brilliance +1' },
  { label: 'Skull Peak Demon Husk of Power +1', value: 'Skull Peak Demon Husk of Power +1' },
  { label: 'Skull Peak Hard Leather Armor of the Fox +1', value: 'Skull Peak Hard Leather Armor of the Fox +1' },
  { label: 'Skull Shout Hard Leather Armor of the Twins +1', value: 'Skull Shout Hard Leather Armor of the Twins +1' },
  { label: 'Sorrow Bender Hard Leather Armor of Enlightenment +1', value: 'Sorrow Bender Hard Leather Armor of Enlightenment +1' },
  { label: 'Sorrow Bender Linen Robe of Fury +1', value: 'Sorrow Bender Linen Robe of Fury +1' },
  { label: 'Sorrow Bender Linen Robe of Perfection +1', value: 'Sorrow Bender Linen Robe of Perfection +1' },
  { label: 'Sorrow Bender Ornate Chestplate of Power +1', value: 'Sorrow Bender Ornate Chestplate of Power +1' },
  { label: 'Sorrow Bender Ring Mail of Perfection +1', value: 'Sorrow Bender Ring Mail of Perfection +1' },
  { label: 'Sorrow Bite Hard Leather Armor of Power +1', value: 'Sorrow Bite Hard Leather Armor of Power +1' },
  { label: 'Sorrow Bite Ring Mail of the Fox +1', value: 'Sorrow Bite Ring Mail of the Fox +1' },
  { label: 'Sorrow Grasp Ornate Chestplate of Vitriol +1', value: 'Sorrow Grasp Ornate Chestplate of Vitriol +1' },
  { label: 'Sorrow Moon Hard Leather Armor of Giants +1', value: 'Sorrow Moon Hard Leather Armor of Giants +1' },
  { label: 'Sorrow Moon Hard Leather Armor of Vitriol +1', value: 'Sorrow Moon Hard Leather Armor of Vitriol +1' },
  { label: 'Sorrow Moon Linen Robe of Giants +1', value: 'Sorrow Moon Linen Robe of Giants +1' },
  { label: 'Sorrow Peak Linen Robe of Enlightenment +1', value: 'Sorrow Peak Linen Robe of Enlightenment +1' },
  { label: 'Sorrow Peak Ring Mail of Reflection +1', value: 'Sorrow Peak Ring Mail of Reflection +1' },
  { label: 'Sorrow Shout Ring Mail of the Twins +1', value: 'Sorrow Shout Ring Mail of the Twins +1' },
  { label: 'Soul Glow Silk Robe of Skill', value: 'Soul Glow Silk Robe of Skill' },
  { label: 'Soul Glow Studded Leather Armor of Rage', value: 'Soul Glow Studded Leather Armor of Rage' },
  { label: 'Soul Glow Studded Leather Armor of the Twins', value: 'Soul Glow Studded Leather Armor of the Twins' },
  { label: 'Soul Roar Shirt of Anger', value: 'Soul Roar Shirt of Anger' },
  { label: 'Soul Roar Shirt of Fury', value: 'Soul Roar Shirt of Fury' },
  { label: 'Soul Roar Shirt of Titans', value: 'Soul Roar Shirt of Titans' },
  { label: 'Soul Roar Silk Robe of Enlightenment', value: 'Soul Roar Silk Robe of Enlightenment' },
  { label: 'Soul Roar Silk Robe of Power', value: 'Soul Roar Silk Robe of Power' },
  { label: 'Soul Root Holy Chestplate of Giants', value: 'Soul Root Holy Chestplate of Giants' },
  { label: 'Soul Sun Chain Mail of Fury', value: 'Soul Sun Chain Mail of Fury' },
  { label: 'Soul Sun Silk Robe of Enlightenment', value: 'Soul Sun Silk Robe of Enlightenment' },
  { label: 'Soul Tear Chain Mail of Protection', value: 'Soul Tear Chain Mail of Protection' },
  { label: 'Soul Tear Holy Chestplate of Giants', value: 'Soul Tear Holy Chestplate of Giants' },
  { label: 'Soul Tear Holy Chestplate of Skill', value: 'Soul Tear Holy Chestplate of Skill' },
  { label: 'Soul Tear Studded Leather Armor of Brilliance', value: 'Soul Tear Studded Leather Armor of Brilliance' },
  { label: 'Soul Tear Studded Leather Armor of the Twins', value: 'Soul Tear Studded Leather Armor of the Twins' },
  { label: 'Soul Tear Studded Leather Armor of Vitriol', value: 'Soul Tear Studded Leather Armor of Vitriol' },
  { label: 'Soul Whisper Holy Chestplate of Titans', value: 'Soul Whisper Holy Chestplate of Titans' },
  { label: 'Soul Whisper Silk Robe of Anger', value: 'Soul Whisper Silk Robe of Anger' },
  { label: 'Soul Whisper Studded Leather Armor of Fury', value: 'Soul Whisper Studded Leather Armor of Fury' },
  { label: 'Storm Glow Shirt of Rage', value: 'Storm Glow Shirt of Rage' },
  { label: 'Storm Glow Silk Robe of Rage', value: 'Storm Glow Silk Robe of Rage' },
  { label: 'Storm Glow Silk Robe of Skill', value: 'Storm Glow Silk Robe of Skill' },
  { label: 'Storm Glow Studded Leather Armor of Giants', value: 'Storm Glow Studded Leather Armor of Giants' },
  { label: 'Storm Glow Studded Leather Armor of Skill', value: 'Storm Glow Studded Leather Armor of Skill' },
  { label: 'Storm Roar Chain Mail of Anger', value: 'Storm Roar Chain Mail of Anger' },
  { label: 'Storm Roar Silk Robe of Titans', value: 'Storm Roar Silk Robe of Titans' },
  { label: 'Storm Roar Studded Leather Armor of Power', value: 'Storm Roar Studded Leather Armor of Power' },
  { label: 'Storm Root Chain Mail of Rage', value: 'Storm Root Chain Mail of Rage' },
  { label: 'Storm Root Chain Mail of Skill', value: 'Storm Root Chain Mail of Skill' },
  { label: 'Storm Root Shirt of Detection', value: 'Storm Root Shirt of Detection' },
  { label: 'Storm Sun Silk Robe of Titans', value: 'Storm Sun Silk Robe of Titans' },
  { label: 'Storm Tear Studded Leather Armor of the Twins', value: 'Storm Tear Studded Leather Armor of the Twins' },
  { label: 'Storm Whisper Holy Chestplate of Enlightenment', value: 'Storm Whisper Holy Chestplate of Enlightenment' },
  { label: 'Storm Whisper Shirt of Enlightenment', value: 'Storm Whisper Shirt of Enlightenment' },
  { label: 'Storm Whisper Studded Leather Armor of Anger', value: 'Storm Whisper Studded Leather Armor of Anger' },
  { label: 'Tempest Bender Hard Leather Armor of Reflection +1', value: 'Tempest Bender Hard Leather Armor of Reflection +1' },
  { label: 'Tempest Bender Ring Mail of Anger +1', value: 'Tempest Bender Ring Mail of Anger +1' },
  { label: 'Tempest Bite Ornate Chestplate of Anger +1', value: 'Tempest Bite Ornate Chestplate of Anger +1' },
  { label: 'Tempest Moon Demon Husk of Detection +1', value: 'Tempest Moon Demon Husk of Detection +1' },
  { label: 'Tempest Moon Hard Leather Armor of Brilliance +1', value: 'Tempest Moon Hard Leather Armor of Brilliance +1' },
  { label: 'Tempest Moon Hard Leather Armor of the Twins +1', value: 'Tempest Moon Hard Leather Armor of the Twins +1' },
  { label: 'Tempest Moon Linen Robe of Detection +1', value: 'Tempest Moon Linen Robe of Detection +1' },
  { label: 'Tempest Moon Linen Robe of Skill +1', value: 'Tempest Moon Linen Robe of Skill +1' },
  { label: 'Tempest Moon Ornate Chestplate of Rage +1', value: 'Tempest Moon Ornate Chestplate of Rage +1' },
  { label: 'Tempest Peak Demon Husk of Perfection +1', value: 'Tempest Peak Demon Husk of Perfection +1' },
  { label: 'Tempest Peak Ornate Chestplate of Power +1', value: 'Tempest Peak Ornate Chestplate of Power +1' },
  { label: 'Tempest Shout Demon Husk of Detection +1', value: 'Tempest Shout Demon Husk of Detection +1' },
  { label: 'Vengeance Glow Studded Leather Armor of the Twins', value: 'Vengeance Glow Studded Leather Armor of the Twins' },
  { label: 'Vengeance Roar Chain Mail of Anger', value: 'Vengeance Roar Chain Mail of Anger' },
  { label: 'Vengeance Roar Chain Mail of Power', value: 'Vengeance Roar Chain Mail of Power' },
  { label: 'Vengeance Roar Shirt of Enlightenment', value: 'Vengeance Roar Shirt of Enlightenment' },
  { label: 'Vengeance Roar Shirt of Power', value: 'Vengeance Roar Shirt of Power' },
  { label: 'Vengeance Roar Silk Robe of Titans', value: 'Vengeance Roar Silk Robe of Titans' },
  { label: 'Vengeance Root Chain Mail of Protection', value: 'Vengeance Root Chain Mail of Protection' },
  { label: 'Vengeance Root Studded Leather Armor of the Twins', value: 'Vengeance Root Studded Leather Armor of the Twins' },
  { label: 'Vengeance Sun Chain Mail of Perfection', value: 'Vengeance Sun Chain Mail of Perfection' },
  { label: 'Vengeance Sun Shirt of Anger', value: 'Vengeance Sun Shirt of Anger' },
  { label: 'Vengeance Sun Silk Robe of Enlightenment', value: 'Vengeance Sun Silk Robe of Enlightenment' },
  { label: 'Vengeance Sun Silk Robe of Fury', value: 'Vengeance Sun Silk Robe of Fury' },
  { label: 'Vengeance Tear Chain Mail of Brilliance', value: 'Vengeance Tear Chain Mail of Brilliance' },
  { label: 'Vengeance Tear Silk Robe of Vitriol', value: 'Vengeance Tear Silk Robe of Vitriol' },
  { label: 'Vengeance Whisper Chain Mail of Power', value: 'Vengeance Whisper Chain Mail of Power' },
  { label: 'Victory Bender Linen Robe of Fury +1', value: 'Victory Bender Linen Robe of Fury +1' },
  { label: 'Victory Bender Ornate Chestplate of Titans +1', value: 'Victory Bender Ornate Chestplate of Titans +1' },
  { label: 'Victory Bender Ring Mail of Power +1', value: 'Victory Bender Ring Mail of Power +1' },
  { label: 'Victory Grasp Linen Robe of the Twins +1', value: 'Victory Grasp Linen Robe of the Twins +1' },
  { label: 'Victory Grasp Ornate Chestplate of Brilliance +1', value: 'Victory Grasp Ornate Chestplate of Brilliance +1' },
  { label: 'Victory Moon Demon Husk of Brilliance +1', value: 'Victory Moon Demon Husk of Brilliance +1' },
  { label: 'Victory Moon Demon Husk of Skill +1', value: 'Victory Moon Demon Husk of Skill +1' },
  { label: 'Victory Moon Hard Leather Armor of Skill +1', value: 'Victory Moon Hard Leather Armor of Skill +1' },
  { label: 'Victory Moon Hard Leather Armor of Vitriol +1', value: 'Victory Moon Hard Leather Armor of Vitriol +1' },
  { label: 'Victory Moon Ornate Chestplate of Skill +1', value: 'Victory Moon Ornate Chestplate of Skill +1' },
  { label: 'Victory Moon Ring Mail of Detection +1', value: 'Victory Moon Ring Mail of Detection +1' },
  { label: 'Victory Peak Hard Leather Armor of Reflection +1', value: 'Victory Peak Hard Leather Armor of Reflection +1' },
  { label: 'Victory Shout Hard Leather Armor of Protection +1', value: 'Victory Shout Hard Leather Armor of Protection +1' },
  { label: 'Vortex Glow Chain Mail of Brilliance', value: 'Vortex Glow Chain Mail of Brilliance' },
  { label: 'Vortex Glow Chain Mail of Giants', value: 'Vortex Glow Chain Mail of Giants' },
  { label: 'Vortex Glow Holy Chestplate of Skill', value: 'Vortex Glow Holy Chestplate of Skill' },
  { label: 'Vortex Glow Shirt of Vitriol', value: 'Vortex Glow Shirt of Vitriol' },
  { label: 'Vortex Roar Chain Mail of Reflection', value: 'Vortex Roar Chain Mail of Reflection' },
  { label: 'Vortex Roar Silk Robe of Anger', value: 'Vortex Roar Silk Robe of Anger' },
  { label: 'Vortex Roar Studded Leather Armor of Perfection', value: 'Vortex Roar Studded Leather Armor of Perfection' },
  { label: 'Vortex Root Chain Mail of Protection', value: 'Vortex Root Chain Mail of Protection' },
  { label: 'Vortex Root Studded Leather Armor of Giants', value: 'Vortex Root Studded Leather Armor of Giants' },
  { label: 'Vortex Tear Chain Mail of Giants', value: 'Vortex Tear Chain Mail of Giants' },
  { label: 'Vortex Tear Chain Mail of Rage', value: 'Vortex Tear Chain Mail of Rage' },
  { label: 'Vortex Tear Holy Chestplate of Vitriol', value: 'Vortex Tear Holy Chestplate of Vitriol' },
  { label: 'Vortex Tear Shirt of Protection', value: 'Vortex Tear Shirt of Protection' },
  { label: 'Vortex Tear Silk Robe of Detection', value: 'Vortex Tear Silk Robe of Detection' },
  { label: 'Vortex Whisper Holy Chestplate of the Fox', value: 'Vortex Whisper Holy Chestplate of the Fox' },
  { label: 'Woe Bender Demon Husk of Titans +1', value: 'Woe Bender Demon Husk of Titans +1' },
  { label: 'Woe Bender Ornate Chestplate of Reflection +1', value: 'Woe Bender Ornate Chestplate of Reflection +1' },
  { label: 'Woe Bender Ornate Chestplate of Titans +1', value: 'Woe Bender Ornate Chestplate of Titans +1' },
  { label: 'Woe Bite Hard Leather Armor of Enlightenment +1', value: 'Woe Bite Hard Leather Armor of Enlightenment +1' },
  { label: 'Woe Bite Ornate Chestplate of the Fox +1', value: 'Woe Bite Ornate Chestplate of the Fox +1' },
  { label: 'Woe Grasp Demon Husk of Brilliance +1', value: 'Woe Grasp Demon Husk of Brilliance +1' },
  { label: 'Woe Grasp Hard Leather Armor of Protection +1', value: 'Woe Grasp Hard Leather Armor of Protection +1' },
  { label: 'Woe Grasp Linen Robe of Detection +1', value: 'Woe Grasp Linen Robe of Detection +1' },
  { label: 'Woe Grasp Ring Mail of Detection +1', value: 'Woe Grasp Ring Mail of Detection +1' },
  { label: 'Woe Peak Demon Husk of Perfection +1', value: 'Woe Peak Demon Husk of Perfection +1' },
  { label: 'Woe Peak Linen Robe of Anger +1', value: 'Woe Peak Linen Robe of Anger +1' },
  { label: 'Woe Peak Linen Robe of Fury +1', value: 'Woe Peak Linen Robe of Fury +1' },
  { label: 'Woe Shout Hard Leather Armor of Skill +1', value: 'Woe Shout Hard Leather Armor of Skill +1' },
  { label: 'Woe Shout Linen Robe of the Twins +1', value: 'Woe Shout Linen Robe of the Twins +1' },
];
