export const heads = [
  { label: 'Hood', value: 'Hood' },
  { label: 'Ornate Helm', value: 'Ornate Helm' },
  { label: 'Great Helm', value: 'Great Helm' },
  { label: 'Divine Hood', value: 'Divine Hood' },
  { label: 'Helm', value: 'Helm' },
  { label: 'Linen Hood', value: 'Linen Hood' },
  { label: 'Crown', value: 'Crown' },
  { label: 'Cap', value: 'Cap' },
  { label: 'Ancient Helm', value: 'Ancient Helm' },
  { label: 'Demon Crown', value: 'Demon Crown' },
  { label: 'Leather Cap', value: 'Leather Cap' },
  { label: "Dragon's Crown", value: "Dragon's Crown" },
  { label: 'War Cap', value: 'War Cap' },
  { label: 'Full Helm', value: 'Full Helm' },
  { label: 'Silk Hood', value: 'Silk Hood' },
  { label: 'Cap of the Fox', value: 'Cap of the Fox' },
  { label: 'Full Helm of Detection', value: 'Full Helm of Detection' },
  { label: "Dragon's Crown of Fury", value: "Dragon's Crown of Fury" },
  { label: "Dragon's Crown of Protection", value: "Dragon's Crown of Protection" },
  { label: "Dragon's Crown of Detection", value: "Dragon's Crown of Detection" },
  { label: 'Full Helm of Giants', value: 'Full Helm of Giants' },
  { label: 'Ancient Helm of Reflection', value: 'Ancient Helm of Reflection' },
  { label: 'Silk Hood of Brilliance', value: 'Silk Hood of Brilliance' },
  { label: 'Full Helm of Vitriol', value: 'Full Helm of Vitriol' },
  { label: 'Silk Hood of Power', value: 'Silk Hood of Power' },
  { label: "Dragon's Crown of Enlightenment", value: "Dragon's Crown of Enlightenment" },
  { label: "Dragon's Crown of Reflection", value: "Dragon's Crown of Reflection" },
  { label: 'Ancient Helm of Detection', value: 'Ancient Helm of Detection' },
  { label: "Dragon's Crown of Power", value: "Dragon's Crown of Power" },
  { label: 'Silk Hood of Reflection', value: 'Silk Hood of Reflection' },
  { label: 'Ancient Helm of Fury', value: 'Ancient Helm of Fury' },
  { label: 'Cap of Power', value: 'Cap of Power' },
  { label: "Dragon's Crown of Perfection", value: "Dragon's Crown of Perfection" },
  { label: "Dragon's Crown of the Twins", value: "Dragon's Crown of the Twins" },
  { label: 'Ancient Helm of Protection', value: 'Ancient Helm of Protection' },
  { label: 'Silk Hood of Enlightenment', value: 'Silk Hood of Enlightenment' },
  { label: 'Full Helm of Brilliance', value: 'Full Helm of Brilliance' },
  { label: 'Full Helm of Reflection', value: 'Full Helm of Reflection' },
  { label: 'Ancient Helm of Anger', value: 'Ancient Helm of Anger' },
  { label: 'Silk Hood of the Fox', value: 'Silk Hood of the Fox' },
  { label: 'Great Helm of Anger', value: 'Great Helm of Anger' },
  { label: 'Cap of Perfection', value: 'Cap of Perfection' },
  { label: 'Full Helm of Fury', value: 'Full Helm of Fury' },
  { label: 'Cap of Detection', value: 'Cap of Detection' },
  { label: 'Cap of the Twins', value: 'Cap of the Twins' },
  { label: 'Cap of Vitriol', value: 'Cap of Vitriol' },
  { label: 'Cap of Giants', value: 'Cap of Giants' },
  { label: 'Cap of Titans', value: 'Cap of Titans' },
  { label: "Dragon's Crown of Brilliance", value: "Dragon's Crown of Brilliance" },
  { label: "Dragon's Crown of Vitriol", value: "Dragon's Crown of Vitriol" },
  { label: "Dragon's Crown of Giants", value: "Dragon's Crown of Giants" },
  { label: 'Linen Hood of Perfection', value: 'Linen Hood of Perfection' },
  { label: "Dragon's Crown of Anger", value: "Dragon's Crown of Anger" },
  { label: 'Ancient Helm of Rage', value: 'Ancient Helm of Rage' },
  { label: 'Linen Hood of Anger', value: 'Linen Hood of Anger' },
  { label: 'Silk Hood of Giants', value: 'Silk Hood of Giants' },
  { label: 'Silk Hood of Titans', value: 'Silk Hood of Titans' },
  { label: 'Silk Hood of Anger', value: 'Silk Hood of Anger' },
  { label: 'Silk Hood of Skill', value: 'Silk Hood of Skill' },
  { label: 'Ancient Helm of Enlightenment', value: 'Ancient Helm of Enlightenment' },
  { label: 'Ancient Helm of Perfection', value: 'Ancient Helm of Perfection' },
  { label: 'Divine Hood of Protection', value: 'Divine Hood of Protection' },
  { label: 'Divine Hood of Reflection', value: 'Divine Hood of Reflection' },
  { label: 'Leather Cap of the Twins', value: 'Leather Cap of the Twins' },
  { label: 'Ancient Helm of the Fox', value: 'Ancient Helm of the Fox' },
  { label: "Dragon's Crown of Rage", value: "Dragon's Crown of Rage" },
  { label: 'Silk Hood of Detection', value: 'Silk Hood of Detection' },
  { label: 'Silk Hood of the Twins', value: 'Silk Hood of the Twins' },
  { label: 'Demon Crown of Rage', value: 'Demon Crown of Rage' },
  { label: 'Great Helm of Skill', value: 'Great Helm of Skill' },
  { label: 'Leather Cap of Fury', value: 'Leather Cap of Fury' },
  { label: 'Cap of Protection', value: 'Cap of Protection' },
  { label: 'Full Helm of Rage', value: 'Full Helm of Rage' },
  { label: 'Cap of Anger', value: 'Cap of Anger' },
  { label: 'Cap of Fury', value: 'Cap of Fury' },
  { label: 'Cap of Rage', value: 'Cap of Rage' },
  { label: 'Full Helm of Enlightenment', value: 'Full Helm of Enlightenment' },
  { label: 'Ancient Helm of the Twins', value: 'Ancient Helm of the Twins' },
  { label: 'Demon Crown of Protection', value: 'Demon Crown of Protection' },
  { label: 'Great Helm of Perfection', value: 'Great Helm of Perfection' },
  { label: 'Leather Cap of Detection', value: 'Leather Cap of Detection' },
  { label: 'Linen Hood of Brilliance', value: 'Linen Hood of Brilliance' },
  { label: "Dragon's Crown of Skill", value: "Dragon's Crown of Skill" },
  { label: 'Ancient Helm of Giants', value: 'Ancient Helm of Giants' },
  { label: 'Divine Hood of Titans', value: 'Divine Hood of Titans' },
  { label: 'Cap of Enlightenment', value: 'Cap of Enlightenment' },
  { label: 'Linen Hood of Giants', value: 'Linen Hood of Giants' },
  { label: 'War Cap of Detection', value: 'War Cap of Detection' },
  { label: 'Crown of Perfection', value: 'Crown of Perfection' },
  { label: 'Full Helm of Skill', value: 'Full Helm of Skill' },
  { label: 'Cap of Brilliance', value: 'Cap of Brilliance' },
  { label: 'Silk Hood of Fury', value: 'Silk Hood of Fury' },
  { label: 'Crown of Anger', value: 'Crown of Anger' },
  { label: "Dragon's Crown of the Fox", value: "Dragon's Crown of the Fox" },
  { label: 'Divine Hood of Detection', value: 'Divine Hood of Detection' },
  { label: "Dragon's Crown of Titans", value: "Dragon's Crown of Titans" },
  { label: 'Linen Hood of Protection', value: 'Linen Hood of Protection' },
  { label: 'Full Helm of Perfection', value: 'Full Helm of Perfection' },
  { label: 'Full Helm of Protection', value: 'Full Helm of Protection' },
  { label: 'Silk Hood of Protection', value: 'Silk Hood of Protection' },
  { label: 'Ancient Helm of Power', value: 'Ancient Helm of Power' },
  { label: 'Ancient Helm of Skill', value: 'Ancient Helm of Skill' },
  { label: 'Great Helm of Giants', value: 'Great Helm of Giants' },
  { label: 'Silk Hood of Vitriol', value: 'Silk Hood of Vitriol' },
  { label: 'Full Helm of Titans', value: 'Full Helm of Titans' },
  { label: 'Linen Hood of Power', value: 'Linen Hood of Power' },
  { label: 'Full Helm of Power', value: 'Full Helm of Power' },
  { label: 'Linen Hood of Fury', value: 'Linen Hood of Fury' },
  { label: 'War Cap of Vitriol', value: 'War Cap of Vitriol' },
  { label: 'Hood of Giants', value: 'Hood of Giants' },
  { label: 'Hood of Skill', value: 'Hood of Skill' },
  { label: 'Ornate Helm of Perfection', value: 'Ornate Helm of Perfection' },
  { label: 'Great Helm of Reflection', value: 'Great Helm of Reflection' },
  { label: 'Linen Hood of Reflection', value: 'Linen Hood of Reflection' },
  { label: 'War Cap of Enlightenment', value: 'War Cap of Enlightenment' },
  { label: 'Linen Hood of the Twins', value: 'Linen Hood of the Twins' },
  { label: 'Crown of Enlightenment', value: 'Crown of Enlightenment' },
  { label: 'Divine Hood of Vitriol', value: 'Divine Hood of Vitriol' },
  { label: 'Full Helm of the Twins', value: 'Full Helm of the Twins' },
  { label: 'Divine Hood of Giants', value: 'Divine Hood of Giants' },
  { label: 'Great Helm of the Fox', value: 'Great Helm of the Fox' },
  { label: 'Leather Cap of Giants', value: 'Leather Cap of Giants' },
  { label: 'Demon Crown of Power', value: 'Demon Crown of Power' },
  { label: 'Divine Hood of Anger', value: 'Divine Hood of Anger' },
  { label: 'Full Helm of the Fox', value: 'Full Helm of the Fox' },
  { label: 'Leather Cap of Skill', value: 'Leather Cap of Skill' },
  { label: 'Linen Hood of Titans', value: 'Linen Hood of Titans' },
  { label: 'Ornate Helm of Anger', value: 'Ornate Helm of Anger' },
  { label: 'Ornate Helm of Power', value: 'Ornate Helm of Power' },
  { label: 'Demon Crown of Fury', value: 'Demon Crown of Fury' },
  { label: 'Divine Hood of Fury', value: 'Divine Hood of Fury' },
  { label: 'Ornate Helm of Rage', value: 'Ornate Helm of Rage' },
  { label: 'Full Helm of Anger', value: 'Full Helm of Anger' },
  { label: 'Cap of Reflection', value: 'Cap of Reflection' },
  { label: 'Helm of Detection', value: 'Helm of Detection' },
  { label: 'Helm of the Twins', value: 'Helm of the Twins' },
  { label: 'Silk Hood of Rage', value: 'Silk Hood of Rage' },
  { label: 'War Cap of Giants', value: 'War Cap of Giants' },
  { label: 'Helm of Vitriol', value: 'Helm of Vitriol' },
  { label: 'Hood of Titans', value: 'Hood of Titans' },
  { label: 'Demon Crown of Brilliance', value: 'Demon Crown of Brilliance' },
  { label: 'Divine Hood of Brilliance', value: 'Divine Hood of Brilliance' },
  { label: 'Leather Cap of Perfection', value: 'Leather Cap of Perfection' },
  { label: 'Ornate Helm of Brilliance', value: 'Ornate Helm of Brilliance' },
  { label: 'Ornate Helm of the Twins', value: 'Ornate Helm of the Twins' },
  { label: 'Ancient Helm of Vitriol', value: 'Ancient Helm of Vitriol' },
  { label: 'Great Helm of the Twins', value: 'Great Helm of the Twins' },
  { label: 'Divine Hood of the Fox', value: 'Divine Hood of the Fox' },
  { label: 'Ornate Helm of Vitriol', value: 'Ornate Helm of Vitriol' },
  { label: 'Demon Crown of Giants', value: 'Demon Crown of Giants' },
  { label: 'Demon Crown of Titans', value: 'Demon Crown of Titans' },
  { label: 'Leather Cap of Titans', value: 'Leather Cap of Titans' },
  { label: 'Linen Hood of Vitriol', value: 'Linen Hood of Vitriol' },
  { label: 'War Cap of Perfection', value: 'War Cap of Perfection' },
  { label: 'Leather Cap of Anger', value: 'Leather Cap of Anger' },
  { label: 'Crown of Protection', value: 'Crown of Protection' },
  { label: 'Great Helm of Power', value: 'Great Helm of Power' },
  { label: 'Linen Hood of Skill', value: 'Linen Hood of Skill' },
  { label: 'Crown of Detection', value: 'Crown of Detection' },
  { label: 'Helm of Protection', value: 'Helm of Protection' },
  { label: 'Crown of the Fox', value: 'Crown of the Fox' },
  { label: 'War Cap of Skill', value: 'War Cap of Skill' },
  { label: 'War Cap of Fury', value: 'War Cap of Fury' },
  { label: 'Crown of Rage', value: 'Crown of Rage' },
  { label: 'Helm of Power', value: 'Helm of Power' },
  { label: 'Helm of Rage', value: 'Helm of Rage' },
  { label: 'Demon Crown of Enlightenment', value: 'Demon Crown of Enlightenment' },
  { label: 'Divine Hood of Enlightenment', value: 'Divine Hood of Enlightenment' },
  { label: 'Leather Cap of Enlightenment', value: 'Leather Cap of Enlightenment' },
  { label: 'Great Helm of Enlightenment', value: 'Great Helm of Enlightenment' },
  { label: 'Linen Hood of Enlightenment', value: 'Linen Hood of Enlightenment' },
  { label: 'Demon Crown of Perfection', value: 'Demon Crown of Perfection' },
  { label: 'Demon Crown of Reflection', value: 'Demon Crown of Reflection' },
  { label: 'Leather Cap of Protection', value: 'Leather Cap of Protection' },
  { label: 'Great Helm of Detection', value: 'Great Helm of Detection' },
  { label: 'Linen Hood of Detection', value: 'Linen Hood of Detection' },
  { label: 'Ancient Helm of Titans', value: 'Ancient Helm of Titans' },
  { label: 'Demon Crown of the Fox', value: 'Demon Crown of the Fox' },
  { label: 'Leather Cap of Vitriol', value: 'Leather Cap of Vitriol' },
  { label: 'Ornate Helm of the Fox', value: 'Ornate Helm of the Fox' },
  { label: 'Great Helm of Vitriol', value: 'Great Helm of Vitriol' },
  { label: 'Hood of Enlightenment', value: 'Hood of Enlightenment' },
  { label: 'Linen Hood of the Fox', value: 'Linen Hood of the Fox' },
  { label: 'Ornate Helm of Giants', value: 'Ornate Helm of Giants' },
  { label: 'War Cap of Brilliance', value: 'War Cap of Brilliance' },
  { label: 'Divine Hood of Skill', value: 'Divine Hood of Skill' },
  { label: 'Great Helm of Titans', value: 'Great Helm of Titans' },
  { label: 'Leather Cap of Power', value: 'Leather Cap of Power' },
  { label: 'Ornate Helm of Skill', value: 'Ornate Helm of Skill' },
  { label: 'War Cap of the Twins', value: 'War Cap of the Twins' },
  { label: 'Divine Hood of Rage', value: 'Divine Hood of Rage' },
  { label: 'Ornate Helm of Fury', value: 'Ornate Helm of Fury' },
  { label: 'Crown of the Twins', value: 'Crown of the Twins' },
  { label: 'Helm of Perfection', value: 'Helm of Perfection' },
  { label: 'Helm of Reflection', value: 'Helm of Reflection' },
  { label: 'Hood of Perfection', value: 'Hood of Perfection' },
  { label: 'Hood of the Twins', value: 'Hood of the Twins' },
  { label: 'War Cap of Titans', value: 'War Cap of Titans' },
  { label: 'War Cap of Anger', value: 'War Cap of Anger' },
  { label: 'Crown of Giants', value: 'Crown of Giants' },
  { label: 'Hood of Vitriol', value: 'Hood of Vitriol' },
  { label: 'Crown of Skill', value: 'Crown of Skill' },
  { label: 'Helm of Skill', value: 'Helm of Skill' },
  { label: 'Hood of Power', value: 'Hood of Power' },
  { label: 'Cap of Skill', value: 'Cap of Skill' },
  { label: 'Hood of Fury', value: 'Hood of Fury' },
  { label: 'Ancient Helm of Brilliance', value: 'Ancient Helm of Brilliance' },
  { label: 'Leather Cap of Reflection', value: 'Leather Cap of Reflection' },
  { label: 'Ornate Helm of Reflection', value: 'Ornate Helm of Reflection' },
  { label: 'Demon Crown of the Twins', value: 'Demon Crown of the Twins' },
  { label: 'Divine Hood of the Twins', value: 'Divine Hood of the Twins' },
  { label: 'Silk Hood of Perfection', value: 'Silk Hood of Perfection' },
  { label: 'Helm of Enlightenment', value: 'Helm of Enlightenment' },
  { label: 'Ornate Helm of Titans', value: 'Ornate Helm of Titans' },
  { label: 'War Cap of Protection', value: 'War Cap of Protection' },
  { label: 'War Cap of Reflection', value: 'War Cap of Reflection' },
  { label: 'Demon Crown of Skill', value: 'Demon Crown of Skill' },
  { label: 'Divine Hood of Power', value: 'Divine Hood of Power' },
  { label: 'Crown of Brilliance', value: 'Crown of Brilliance' },
  { label: 'Leather Cap of Rage', value: 'Leather Cap of Rage' },
  { label: 'Great Helm of Rage', value: 'Great Helm of Rage' },
  { label: 'Hood of Brilliance', value: 'Hood of Brilliance' },
  { label: 'Hood of Protection', value: 'Hood of Protection' },
  { label: 'Linen Hood of Rage', value: 'Linen Hood of Rage' },
  { label: 'Crown of Titans', value: 'Crown of Titans' },
  { label: 'Helm of the Fox', value: 'Helm of the Fox' },
  { label: 'Hood of the Fox', value: 'Hood of the Fox' },
  { label: 'Hood of Rage', value: 'Hood of Rage' },
  { label: 'Tempest Shout Divine Hood of Detection +1', value: 'Tempest Shout Divine Hood of Detection +1' },
  { label: 'Dread Grasp Leather Cap of Detection +1', value: 'Dread Grasp Leather Cap of Detection +1' },
  { label: 'Kraken Moon Divine Hood of the Twins +1', value: 'Kraken Moon Divine Hood of the Twins +1' },
  { label: 'Victory Bender Divine Hood of Power +1', value: 'Victory Bender Divine Hood of Power +1' },
  { label: 'Woe Shout Demon Crown of Protection +1', value: 'Woe Shout Demon Crown of Protection +1' },
  { label: 'Behemoth Root Linen Hood of the Twins', value: 'Behemoth Root Linen Hood of the Twins' },
  { label: 'Carrion Whisper Ornate Helm of Power', value: 'Carrion Whisper Ornate Helm of Power' },
  { label: 'Apocalypse Sun Ornate Helm of Power', value: 'Apocalypse Sun Ornate Helm of Power' },
  { label: 'Maelstrom Roar Linen Hood of Titans', value: 'Maelstrom Roar Linen Hood of Titans' },
  { label: 'Mind Bender Great Helm of Titans +1', value: 'Mind Bender Great Helm of Titans +1' },
  { label: 'Soul Root Ornate Helm of Brilliance', value: 'Soul Root Ornate Helm of Brilliance' },
  { label: 'Victory Grasp Hood of Brilliance +1', value: 'Victory Grasp Hood of Brilliance +1' },
  { label: 'Blight Bite Great Helm of Power +1', value: 'Blight Bite Great Helm of Power +1' },
  { label: 'Foe Bender Divine Hood of Anger +1', value: 'Foe Bender Divine Hood of Anger +1' },
  { label: 'Rune Tear Ornate Helm of Detection', value: 'Rune Tear Ornate Helm of Detection' },
  { label: "Light's Tear Linen Hood of Giants", value: "Light's Tear Linen Hood of Giants" },
  { label: 'Shimmering Bite Hood of Titans +1', value: 'Shimmering Bite Hood of Titans +1' },
  { label: 'Death Whisper Helm of Reflection', value: 'Death Whisper Helm of Reflection' },
  { label: 'Rage Shout Hood of Protection +1', value: 'Rage Shout Hood of Protection +1' },
  { label: 'Death Glow Ornate Helm of Skill', value: 'Death Glow Ornate Helm of Skill' },
  { label: 'Woe Peak Great Helm of Anger +1', value: 'Woe Peak Great Helm of Anger +1' },
  { label: 'Dragon Tear Helm of Brilliance', value: 'Dragon Tear Helm of Brilliance' },
  { label: 'Victory Peak Hood of Power +1', value: 'Victory Peak Hood of Power +1' },
  { label: 'Ornate Helm of Enlightenment', value: 'Ornate Helm of Enlightenment' },
  { label: 'Ghoul Sun Crown of the Fox', value: 'Ghoul Sun Crown of the Fox' },
  { label: 'Divine Hood of Perfection', value: 'Divine Hood of Perfection' },
  { label: 'Ornate Helm of Protection', value: 'Ornate Helm of Protection' },
  { label: 'Demon Crown of Detection', value: 'Demon Crown of Detection' },
  { label: 'Great Helm of Brilliance', value: 'Great Helm of Brilliance' },
  { label: 'Havoc Roar Crown of Fury', value: 'Havoc Roar Crown of Fury' },
  { label: 'Havoc Root Crown of Rage', value: 'Havoc Root Crown of Rage' },
  { label: 'Ornate Helm of Detection', value: 'Ornate Helm of Detection' },
  { label: 'Demon Crown of Vitriol', value: 'Demon Crown of Vitriol' },
  { label: 'Leather Cap of the Fox', value: 'Leather Cap of the Fox' },
  { label: 'Demon Crown of Anger', value: 'Demon Crown of Anger' },
  { label: 'Crown of Reflection', value: 'Crown of Reflection' },
  { label: 'Great Helm of Fury', value: 'Great Helm of Fury' },
  { label: 'Helm of Brilliance', value: 'Helm of Brilliance' },
  { label: 'Hood of Reflection', value: 'Hood of Reflection' },
  { label: 'Hood of Detection', value: 'Hood of Detection' },
  { label: 'Crown of Vitriol', value: 'Crown of Vitriol' },
  { label: 'War Cap of Power', value: 'War Cap of Power' },
  { label: 'Helm of Giants', value: 'Helm of Giants' },
  { label: 'Helm of Titans', value: 'Helm of Titans' },
  { label: 'Crown of Fury', value: 'Crown of Fury' },
  { label: 'Helm of Fury', value: 'Helm of Fury' },
  { label: 'Armageddon Bender Divine Hood of Enlightenment +1', value: 'Armageddon Bender Divine Hood of Enlightenment +1' },
  { label: 'Cataclysm Bender Divine Hood of Enlightenment +1', value: 'Cataclysm Bender Divine Hood of Enlightenment +1' },
  { label: 'Armageddon Bender Demon Crown of Perfection +1', value: 'Armageddon Bender Demon Crown of Perfection +1' },
  { label: 'Corruption Bender Divine Hood of Perfection +1', value: 'Corruption Bender Divine Hood of Perfection +1' },
  { label: 'Armageddon Grasp Demon Crown of Protection +1', value: 'Armageddon Grasp Demon Crown of Protection +1' },
  { label: 'Armageddon Shout Leather Cap of Protection +1', value: 'Armageddon Shout Leather Cap of Protection +1' },
  { label: 'Blight Bender Leather Cap of Enlightenment +1', value: 'Blight Bender Leather Cap of Enlightenment +1' },
  { label: 'Brimstone Bite Great Helm of Enlightenment +1', value: 'Brimstone Bite Great Helm of Enlightenment +1' },
  { label: 'Corruption Shout Divine Hood of Protection +1', value: 'Corruption Shout Divine Hood of Protection +1' },
  { label: 'Armageddon Bite Leather Cap of Perfection +1', value: 'Armageddon Bite Leather Cap of Perfection +1' },
  { label: 'Armageddon Grasp Divine Hood of the Twins +1', value: 'Armageddon Grasp Divine Hood of the Twins +1' },
  { label: 'Armageddon Moon Leather Cap of Protection +1', value: 'Armageddon Moon Leather Cap of Protection +1' },
  { label: 'Armageddon Shout Great Helm of Brilliance +1', value: 'Armageddon Shout Great Helm of Brilliance +1' },
  { label: 'Brimstone Grasp Demon Crown of Brilliance +1', value: 'Brimstone Grasp Demon Crown of Brilliance +1' },
  { label: 'Brimstone Grasp Divine Hood of Brilliance +1', value: 'Brimstone Grasp Divine Hood of Brilliance +1' },
  { label: 'Brimstone Shout Demon Crown of Protection +1', value: 'Brimstone Shout Demon Crown of Protection +1' },
  { label: 'Cataclysm Grasp Divine Hood of Brilliance +1', value: 'Cataclysm Grasp Divine Hood of Brilliance +1' },
  { label: 'Eagle Bender Divine Hood of Enlightenment +1', value: 'Eagle Bender Divine Hood of Enlightenment +1' },
  { label: 'Armageddon Bender Leather Cap of the Fox +1', value: 'Armageddon Bender Leather Cap of the Fox +1' },
  { label: 'Brimstone Bite Leather Cap of Reflection +1', value: 'Brimstone Bite Leather Cap of Reflection +1' },
  { label: 'Brimstone Peak Demon Crown of Reflection +1', value: 'Brimstone Peak Demon Crown of Reflection +1' },
  { label: 'Cataclysm Moon Demon Crown of Brilliance +1', value: 'Cataclysm Moon Demon Crown of Brilliance +1' },
  { label: 'Cataclysm Peak Leather Cap of Perfection +1', value: 'Cataclysm Peak Leather Cap of Perfection +1' },
  { label: 'Cataclysm Shout Great Helm of Protection +1', value: 'Cataclysm Shout Great Helm of Protection +1' },
  { label: 'Corruption Moon Demon Crown of Detection +1', value: 'Corruption Moon Demon Crown of Detection +1' },
  { label: 'Corruption Moon Leather Cap of Detection +1', value: 'Corruption Moon Leather Cap of Detection +1' },
  { label: 'Dread Bender Great Helm of Enlightenment +1', value: 'Dread Bender Great Helm of Enlightenment +1' },
  { label: 'Grim Bender Divine Hood of Enlightenment +1', value: 'Grim Bender Divine Hood of Enlightenment +1' },
  { label: 'Maelstrom Whisper Ornate Helm of Perfection', value: 'Maelstrom Whisper Ornate Helm of Perfection' },
  { label: 'Mind Bender Divine Hood of Enlightenment +1', value: 'Mind Bender Divine Hood of Enlightenment +1' },
  { label: 'Oblivion Shout Divine Hood of Brilliance +1', value: 'Oblivion Shout Divine Hood of Brilliance +1' },
  { label: 'Apocalypse Sun Linen Hood of Enlightenment', value: 'Apocalypse Sun Linen Hood of Enlightenment' },
  { label: 'Armageddon Bender Leather Cap of Titans +1', value: 'Armageddon Bender Leather Cap of Titans +1' },
  { label: 'Armageddon Shout Divine Hood of Vitriol +1', value: 'Armageddon Shout Divine Hood of Vitriol +1' },
  { label: 'Demon Bite Leather Cap of Enlightenment +1', value: 'Demon Bite Leather Cap of Enlightenment +1' },
  { label: 'Eagle Bite Leather Cap of Enlightenment +1', value: 'Eagle Bite Leather Cap of Enlightenment +1' },
  { label: 'Honour Peak Great Helm of Enlightenment +1', value: 'Honour Peak Great Helm of Enlightenment +1' },
  { label: 'Kraken Bender Divine Hood of Perfection +1', value: 'Kraken Bender Divine Hood of Perfection +1' },
  { label: 'Mind Bender Great Helm of Enlightenment +1', value: 'Mind Bender Great Helm of Enlightenment +1' },
  { label: 'Oblivion Grasp Leather Cap of Detection +1', value: 'Oblivion Grasp Leather Cap of Detection +1' },
  { label: 'Oblivion Moon Demon Crown of Brilliance +1', value: 'Oblivion Moon Demon Crown of Brilliance +1' },
  { label: 'Oblivion Shout Divine Hood of Detection +1', value: 'Oblivion Shout Divine Hood of Detection +1' },
  { label: 'Armageddon Shout Leather Cap of Giants +1', value: 'Armageddon Shout Leather Cap of Giants +1' },
  { label: 'Blight Shout Divine Hood of Protection +1', value: 'Blight Shout Divine Hood of Protection +1' },
  { label: 'Bramble Whisper Ornate Helm of Reflection', value: 'Bramble Whisper Ornate Helm of Reflection' },
  { label: 'Carrion Roar Ornate Helm of Enlightenment', value: 'Carrion Roar Ornate Helm of Enlightenment' },
  { label: 'Cataclysm Shout Leather Cap of Vitriol +1', value: 'Cataclysm Shout Leather Cap of Vitriol +1' },
  { label: 'Corruption Moon Divine Hood of Vitriol +1', value: 'Corruption Moon Divine Hood of Vitriol +1' },
  { label: 'Demon Bender Demon Crown of Reflection +1', value: 'Demon Bender Demon Crown of Reflection +1' },
  { label: 'Eagle Bender Demon Crown of Perfection +1', value: 'Eagle Bender Demon Crown of Perfection +1' },
  { label: 'Foe Bender Great Helm of Enlightenment +1', value: 'Foe Bender Great Helm of Enlightenment +1' },
  { label: 'Mind Bite Demon Crown of Enlightenment +1', value: 'Mind Bite Demon Crown of Enlightenment +1' },
  { label: 'Oblivion Bender Leather Cap of the Fox +1', value: 'Oblivion Bender Leather Cap of the Fox +1' },
  { label: 'Oblivion Moon Demon Crown of the Twins +1', value: 'Oblivion Moon Demon Crown of the Twins +1' },
  { label: 'Armageddon Bite Demon Crown of Titans +1', value: 'Armageddon Bite Demon Crown of Titans +1' },
  { label: 'Armageddon Moon Divine Hood of Giants +1', value: 'Armageddon Moon Divine Hood of Giants +1' },
  { label: 'Blight Bite Divine Hood of Perfection +1', value: 'Blight Bite Divine Hood of Perfection +1' },
  { label: 'Blight Grasp Demon Crown of the Twins +1', value: 'Blight Grasp Demon Crown of the Twins +1' },
  { label: 'Bramble Whisper Linen Hood of Reflection', value: 'Bramble Whisper Linen Hood of Reflection' },
  { label: 'Brimstone Bender Leather Cap of Power +1', value: 'Brimstone Bender Leather Cap of Power +1' },
  { label: 'Carrion Roar Linen Hood of Enlightenment', value: 'Carrion Roar Linen Hood of Enlightenment' },
  { label: 'Cataclysm Grasp Divine Hood of Giants +1', value: 'Cataclysm Grasp Divine Hood of Giants +1' },
  { label: 'Cataclysm Grasp Leather Cap of Giants +1', value: 'Cataclysm Grasp Leather Cap of Giants +1' },
  { label: 'Cataclysm Moon Leather Cap of Vitriol +1', value: 'Cataclysm Moon Leather Cap of Vitriol +1' },
  { label: 'Cataclysm Peak Divine Hood of the Fox +1', value: 'Cataclysm Peak Divine Hood of the Fox +1' },
  { label: 'Demon Shout Leather Cap of Brilliance +1', value: 'Demon Shout Leather Cap of Brilliance +1' },
  { label: 'Dread Shout Demon Crown of Brilliance +1', value: 'Dread Shout Demon Crown of Brilliance +1' },
  { label: 'Eagle Bender Great Helm of Reflection +1', value: 'Eagle Bender Great Helm of Reflection +1' },
  { label: 'Eagle Grasp Leather Cap of Brilliance +1', value: 'Eagle Grasp Leather Cap of Brilliance +1' },
  { label: 'Foe Bite Divine Hood of Enlightenment +1', value: 'Foe Bite Divine Hood of Enlightenment +1' },
  { label: 'Gloom Grasp Demon Crown of Protection +1', value: 'Gloom Grasp Demon Crown of Protection +1' },
  { label: 'Honour Grasp Divine Hood of Detection +1', value: 'Honour Grasp Divine Hood of Detection +1' },
  { label: 'Honour Grasp Divine Hood of the Twins +1', value: 'Honour Grasp Divine Hood of the Twins +1' },
  { label: 'Hypnotic Sun Linen Hood of Enlightenment', value: 'Hypnotic Sun Linen Hood of Enlightenment' },
  { label: 'Mind Bender Demon Crown of Reflection +1', value: 'Mind Bender Demon Crown of Reflection +1' },
  { label: 'Mind Bender Divine Hood of Reflection +1', value: 'Mind Bender Divine Hood of Reflection +1' },
  { label: 'Mind Bender Leather Cap of Perfection +1', value: 'Mind Bender Leather Cap of Perfection +1' },
  { label: 'Mind Peak Great Helm of Enlightenment +1', value: 'Mind Peak Great Helm of Enlightenment +1' },
  { label: 'Apocalypse Sun Linen Hood of Reflection', value: 'Apocalypse Sun Linen Hood of Reflection' },
  { label: 'Armageddon Bite Great Helm of Titans +1', value: 'Armageddon Bite Great Helm of Titans +1' },
  { label: 'Armageddon Bite Leather Cap of Power +1', value: 'Armageddon Bite Leather Cap of Power +1' },
  { label: 'Behemoth Roar Ornate Helm of Reflection', value: 'Behemoth Roar Ornate Helm of Reflection' },
  { label: 'Behemoth Root Ornate Helm of Brilliance', value: 'Behemoth Root Ornate Helm of Brilliance' },
  { label: 'Blight Bite Great Helm of Reflection +1', value: 'Blight Bite Great Helm of Reflection +1' },
  { label: 'Brimstone Grasp Great Helm of Giants +1', value: 'Brimstone Grasp Great Helm of Giants +1' },
  { label: 'Brimstone Peak Demon Crown of Titans +1', value: 'Brimstone Peak Demon Crown of Titans +1' },
  { label: 'Brimstone Peak Divine Hood of Titans +1', value: 'Brimstone Peak Divine Hood of Titans +1' },
  { label: 'Cataclysm Shout Divine Hood of Skill +1', value: 'Cataclysm Shout Divine Hood of Skill +1' },
  { label: 'Corruption Bite Leather Cap of Anger +1', value: 'Corruption Bite Leather Cap of Anger +1' },
  { label: 'Corruption Moon Leather Cap of Skill +1', value: 'Corruption Moon Leather Cap of Skill +1' },
  { label: 'Demon Bite Demon Crown of Reflection +1', value: 'Demon Bite Demon Crown of Reflection +1' },
  { label: 'Demon Moon Demon Crown of Protection +1', value: 'Demon Moon Demon Crown of Protection +1' },
  { label: 'Demon Shout Great Helm of Protection +1', value: 'Demon Shout Great Helm of Protection +1' },
  { label: 'Dread Moon Demon Crown of Brilliance +1', value: 'Dread Moon Demon Crown of Brilliance +1' },
  { label: 'Dread Peak Demon Crown of Perfection +1', value: 'Dread Peak Demon Crown of Perfection +1' },
  { label: 'Dread Peak Divine Hood of Perfection +1', value: 'Dread Peak Divine Hood of Perfection +1' },
  { label: 'Eagle Bite Leather Cap of Reflection +1', value: 'Eagle Bite Leather Cap of Reflection +1' },
  { label: 'Eagle Grasp Demon Crown of the Twins +1', value: 'Eagle Grasp Demon Crown of the Twins +1' },
  { label: 'Eagle Moon Divine Hood of Brilliance +1', value: 'Eagle Moon Divine Hood of Brilliance +1' },
  { label: 'Gloom Moon Demon Crown of Protection +1', value: 'Gloom Moon Demon Crown of Protection +1' },
  { label: 'Gloom Shout Demon Crown of the Twins +1', value: 'Gloom Shout Demon Crown of the Twins +1' },
  { label: 'Hypnotic Glow Ornate Helm of Protection', value: 'Hypnotic Glow Ornate Helm of Protection' },
  { label: 'Hypnotic Root Ornate Helm of Brilliance', value: 'Hypnotic Root Ornate Helm of Brilliance' },
  { label: 'Kraken Moon Divine Hood of Detection +1', value: 'Kraken Moon Divine Hood of Detection +1' },
  { label: 'Maelstrom Glow Linen Hood of Brilliance', value: 'Maelstrom Glow Linen Hood of Brilliance' },
  { label: 'Morbid Whisper War Cap of Enlightenment', value: 'Morbid Whisper War Cap of Enlightenment' },
  { label: 'Oblivion Moon Demon Crown of Vitriol +1', value: 'Oblivion Moon Demon Crown of Vitriol +1' },
  { label: 'Oblivion Moon Leather Cap of Vitriol +1', value: 'Oblivion Moon Leather Cap of Vitriol +1' },
  { label: 'Oblivion Shout Divine Hood of Giants +1', value: 'Oblivion Shout Divine Hood of Giants +1' },
  { label: 'Apocalypse Roar Crown of Enlightenment', value: 'Apocalypse Roar Crown of Enlightenment' },
  { label: 'Armageddon Bite Demon Crown of Fury +1', value: 'Armageddon Bite Demon Crown of Fury +1' },
  { label: 'Armageddon Bite Great Helm of Anger +1', value: 'Armageddon Bite Great Helm of Anger +1' },
  { label: 'Behemoth Sun Ornate Helm of Perfection', value: 'Behemoth Sun Ornate Helm of Perfection' },
  { label: 'Behemoth Tear Linen Hood of Protection', value: 'Behemoth Tear Linen Hood of Protection' },
  { label: 'Behemoth Tear Ornate Helm of the Twins', value: 'Behemoth Tear Ornate Helm of the Twins' },
  { label: 'Bramble Glow Ornate Helm of Brilliance', value: 'Bramble Glow Ornate Helm of Brilliance' },
  { label: 'Brimstone Bite Leather Cap of Anger +1', value: 'Brimstone Bite Leather Cap of Anger +1' },
  { label: 'Brimstone Grasp Leather Cap of Rage +1', value: 'Brimstone Grasp Leather Cap of Rage +1' },
  { label: 'Brimstone Moon Leather Cap of Skill +1', value: 'Brimstone Moon Leather Cap of Skill +1' },
  { label: 'Brimstone Shout Divine Hood of Rage +1', value: 'Brimstone Shout Divine Hood of Rage +1' },
  { label: 'Carrion Root Ornate Helm of Brilliance', value: 'Carrion Root Ornate Helm of Brilliance' },
  { label: 'Cataclysm Grasp Great Helm of Skill +1', value: 'Cataclysm Grasp Great Helm of Skill +1' },
  { label: 'Cataclysm Peak Leather Cap of Anger +1', value: 'Cataclysm Peak Leather Cap of Anger +1' },
  { label: 'Cataclysm Peak Leather Cap of Power +1', value: 'Cataclysm Peak Leather Cap of Power +1' },
  { label: 'Corpse Sun Linen Hood of Enlightenment', value: 'Corpse Sun Linen Hood of Enlightenment' },
  { label: 'Corruption Peak Leather Cap of Fury +1', value: 'Corruption Peak Leather Cap of Fury +1' },
  { label: 'Demon Bender Demon Crown of the Fox +1', value: 'Demon Bender Demon Crown of the Fox +1' },
  { label: 'Demon Moon Demon Crown of Detection +1', value: 'Demon Moon Demon Crown of Detection +1' },
  { label: 'Demon Moon Great Helm of Protection +1', value: 'Demon Moon Great Helm of Protection +1' },
  { label: 'Eagle Bender Divine Hood of the Fox +1', value: 'Eagle Bender Divine Hood of the Fox +1' },
  { label: 'Foe Bender Great Helm of Perfection +1', value: 'Foe Bender Great Helm of Perfection +1' },
  { label: 'Foe Shout Demon Crown of Protection +1', value: 'Foe Shout Demon Crown of Protection +1' },
  { label: 'Gloom Bender Demon Crown of the Fox +1', value: 'Gloom Bender Demon Crown of the Fox +1' },
  { label: 'Grim Bite Divine Hood of Reflection +1', value: 'Grim Bite Divine Hood of Reflection +1' },
  { label: 'Grim Moon Demon Crown of Brilliance +1', value: 'Grim Moon Demon Crown of Brilliance +1' },
  { label: 'Grim Peak Leather Cap of Reflection +1', value: 'Grim Peak Leather Cap of Reflection +1' },
  { label: 'Grim Shout Leather Cap of the Twins +1', value: 'Grim Shout Leather Cap of the Twins +1' },
  { label: 'Hypnotic Roar Linen Hood of Perfection', value: 'Hypnotic Roar Linen Hood of Perfection' },
  { label: 'Hypnotic Whisper War Cap of Reflection', value: 'Hypnotic Whisper War Cap of Reflection' },
  { label: 'Kraken Bender Hood of Enlightenment +1', value: 'Kraken Bender Hood of Enlightenment +1' },
  { label: "Light's Glow Ornate Helm of Protection", value: "Light's Glow Ornate Helm of Protection" },
  { label: 'Oblivion Peak Demon Crown of Titans +1', value: 'Oblivion Peak Demon Crown of Titans +1' },
  { label: 'Apocalypse Glow War Cap of Brilliance', value: 'Apocalypse Glow War Cap of Brilliance' },
  { label: 'Apocalypse Roar Ornate Helm of Titans', value: 'Apocalypse Roar Ornate Helm of Titans' },
  { label: 'Armageddon Shout Hood of the Twins +1', value: 'Armageddon Shout Hood of the Twins +1' },
  { label: 'Behemoth Whisper Linen Hood of Titans', value: 'Behemoth Whisper Linen Hood of Titans' },
  { label: 'Blight Bender Divine Hood of Power +1', value: 'Blight Bender Divine Hood of Power +1' },
  { label: 'Blight Bender Leather Cap of Power +1', value: 'Blight Bender Leather Cap of Power +1' },
  { label: 'Blight Peak Leather Cap of the Fox +1', value: 'Blight Peak Leather Cap of the Fox +1' },
  { label: 'Bramble Glow Linen Hood of Brilliance', value: 'Bramble Glow Linen Hood of Brilliance' },
  { label: 'Bramble Roar Linen Hood of Reflection', value: 'Bramble Roar Linen Hood of Reflection' },
  { label: 'Bramble Root Ornate Helm of Detection', value: 'Bramble Root Ornate Helm of Detection' },
  { label: 'Brimstone Bite Demon Crown of Fury +1', value: 'Brimstone Bite Demon Crown of Fury +1' },
  { label: 'Brimstone Bite Great Helm of Power +1', value: 'Brimstone Bite Great Helm of Power +1' },
  { label: 'Carrion Whisper War Cap of Perfection', value: 'Carrion Whisper War Cap of Perfection' },
  { label: 'Cataclysm Moon Demon Crown of Rage +1', value: 'Cataclysm Moon Demon Crown of Rage +1' },
  { label: 'Cataclysm Moon Leather Cap of Rage +1', value: 'Cataclysm Moon Leather Cap of Rage +1' },
  { label: 'Corpse Root Ornate Helm of Brilliance', value: 'Corpse Root Ornate Helm of Brilliance' },
  { label: 'Corruption Shout Hood of Detection +1', value: 'Corruption Shout Hood of Detection +1' },
  { label: 'Demon Grasp Leather Cap of Vitriol +1', value: 'Demon Grasp Leather Cap of Vitriol +1' },
  { label: 'Demon Moon Great Helm of Detection +1', value: 'Demon Moon Great Helm of Detection +1' },
  { label: 'Dragon Root Ornate Helm of Brilliance', value: 'Dragon Root Ornate Helm of Brilliance' },
  { label: 'Dread Moon Great Helm of the Twins +1', value: 'Dread Moon Great Helm of the Twins +1' },
  { label: 'Dusk Roar Linen Hood of Enlightenment', value: 'Dusk Roar Linen Hood of Enlightenment' },
  { label: 'Eagle Grasp Demon Crown of Vitriol +1', value: 'Eagle Grasp Demon Crown of Vitriol +1' },
  { label: 'Fate Roar Linen Hood of Enlightenment', value: 'Fate Roar Linen Hood of Enlightenment' },
  { label: 'Fate Sun Ornate Helm of Enlightenment', value: 'Fate Sun Ornate Helm of Enlightenment' },
  { label: 'Grim Bite Great Helm of Perfection +1', value: 'Grim Bite Great Helm of Perfection +1' },
  { label: 'Honour Bender Demon Crown of Anger +1', value: 'Honour Bender Demon Crown of Anger +1' },
  { label: 'Honour Bender Demon Crown of Power +1', value: 'Honour Bender Demon Crown of Power +1' },
  { label: 'Hypnotic Sun Linen Hood of Perfection', value: 'Hypnotic Sun Linen Hood of Perfection' },
  { label: 'Hypnotic Sun War Cap of Enlightenment', value: 'Hypnotic Sun War Cap of Enlightenment' },
  { label: 'Kraken Bender Demon Crown of Power +1', value: 'Kraken Bender Demon Crown of Power +1' },
  { label: 'Kraken Bender Great Helm of Titans +1', value: 'Kraken Bender Great Helm of Titans +1' },
  { label: "Light's Whisper Linen Hood of the Fox", value: "Light's Whisper Linen Hood of the Fox" },
  { label: 'Morbid Glow Ornate Helm of Brilliance', value: 'Morbid Glow Ornate Helm of Brilliance' },
  { label: 'Oblivion Grasp Divine Hood of Rage +1', value: 'Oblivion Grasp Divine Hood of Rage +1' },
  { label: 'Blight Bender Leather Cap of Fury +1', value: 'Blight Bender Leather Cap of Fury +1' },
  { label: 'Blight Grasp Great Helm of Giants +1', value: 'Blight Grasp Great Helm of Giants +1' },
  { label: 'Blight Moon Demon Crown of Giants +1', value: 'Blight Moon Demon Crown of Giants +1' },
  { label: 'Blight Moon Divine Hood of Giants +1', value: 'Blight Moon Divine Hood of Giants +1' },
  { label: 'Brimstone Moon Great Helm of Rage +1', value: 'Brimstone Moon Great Helm of Rage +1' },
  { label: 'Cataclysm Bite Hood of Reflection +1', value: 'Cataclysm Bite Hood of Reflection +1' },
  { label: 'Corpse Roar Linen Hood of Reflection', value: 'Corpse Roar Linen Hood of Reflection' },
  { label: 'Corruption Moon Hood of the Twins +1', value: 'Corruption Moon Hood of the Twins +1' },
  { label: 'Death Tear Ornate Helm of Protection', value: 'Death Tear Ornate Helm of Protection' },
  { label: 'Demon Bender Demon Crown of Power +1', value: 'Demon Bender Demon Crown of Power +1' },
  { label: 'Dread Bite Demon Crown of the Fox +1', value: 'Dread Bite Demon Crown of the Fox +1' },
  { label: 'Eagle Bender Divine Hood of Power +1', value: 'Eagle Bender Divine Hood of Power +1' },
  { label: 'Foe Shout Great Helm of Detection +1', value: 'Foe Shout Great Helm of Detection +1' },
  { label: 'Ghoul Root Ornate Helm of Brilliance', value: 'Ghoul Root Ornate Helm of Brilliance' },
  { label: 'Ghoul Whisper Crown of Enlightenment', value: 'Ghoul Whisper Crown of Enlightenment' },
  { label: 'Golem Whisper Ornate Helm of the Fox', value: 'Golem Whisper Ornate Helm of the Fox' },
  { label: 'Grim Grasp Leather Cap of Vitriol +1', value: 'Grim Grasp Leather Cap of Vitriol +1' },
  { label: 'Havoc Root Ornate Helm of Protection', value: 'Havoc Root Ornate Helm of Protection' },
  { label: 'Hypnotic Whisper Linen Hood of Power', value: 'Hypnotic Whisper Linen Hood of Power' },
  { label: 'Kraken Bender Divine Hood of Fury +1', value: 'Kraken Bender Divine Hood of Fury +1' },
  { label: 'Kraken Grasp Demon Crown of Skill +1', value: 'Kraken Grasp Demon Crown of Skill +1' },
  { label: "Light's Tear Linen Hood of Detection", value: "Light's Tear Linen Hood of Detection" },
  { label: 'Maelstrom Roar Helm of Enlightenment', value: 'Maelstrom Roar Helm of Enlightenment' },
  { label: 'Maelstrom Roar War Cap of Perfection', value: 'Maelstrom Roar War Cap of Perfection' },
  { label: 'Maelstrom Tear Ornate Helm of Giants', value: 'Maelstrom Tear Ornate Helm of Giants' },
  { label: 'Mind Shout Leather Cap of Vitriol +1', value: 'Mind Shout Leather Cap of Vitriol +1' },
  { label: 'Morbid Roar Linen Hood of Perfection', value: 'Morbid Roar Linen Hood of Perfection' },
  { label: 'Morbid Roar War Cap of Enlightenment', value: 'Morbid Roar War Cap of Enlightenment' },
  { label: 'Oblivion Peak Demon Crown of Fury +1', value: 'Oblivion Peak Demon Crown of Fury +1' },
  { label: 'Apocalypse Roar Ornate Helm of Fury', value: 'Apocalypse Roar Ornate Helm of Fury' },
  { label: 'Apocalypse Whisper War Cap of Anger', value: 'Apocalypse Whisper War Cap of Anger' },
  { label: 'Apocalypse Whisper War Cap of Power', value: 'Apocalypse Whisper War Cap of Power' },
  { label: 'Blight Bite Leather Cap of Anger +1', value: 'Blight Bite Leather Cap of Anger +1' },
  { label: 'Blight Peak Demon Crown of Power +1', value: 'Blight Peak Demon Crown of Power +1' },
  { label: 'Blight Shout Demon Crown of Rage +1', value: 'Blight Shout Demon Crown of Rage +1' },
  { label: 'Bramble Whisper Crown of Reflection', value: 'Bramble Whisper Crown of Reflection' },
  { label: 'Bramble Whisper Linen Hood of Anger', value: 'Bramble Whisper Linen Hood of Anger' },
  { label: 'Brimstone Moon Hood of the Twins +1', value: 'Brimstone Moon Hood of the Twins +1' },
  { label: 'Corpse Sun Linen Hood of Reflection', value: 'Corpse Sun Linen Hood of Reflection' },
  { label: 'Demon Bender Great Helm of Anger +1', value: 'Demon Bender Great Helm of Anger +1' },
  { label: 'Demon Bender Great Helm of Power +1', value: 'Demon Bender Great Helm of Power +1' },
  { label: 'Demon Peak Divine Hood of Titans +1', value: 'Demon Peak Divine Hood of Titans +1' },
  { label: 'Demon Shout Demon Crown of Skill +1', value: 'Demon Shout Demon Crown of Skill +1' },
  { label: 'Dread Bender Great Helm of Power +1', value: 'Dread Bender Great Helm of Power +1' },
  { label: 'Dread Bite Divine Hood of Titans +1', value: 'Dread Bite Divine Hood of Titans +1' },
  { label: 'Dread Peak Hood of Enlightenment +1', value: 'Dread Peak Hood of Enlightenment +1' },
  { label: 'Dusk Glow Ornate Helm of Protection', value: 'Dusk Glow Ornate Helm of Protection' },
  { label: 'Dusk Root Ornate Helm of Brilliance', value: 'Dusk Root Ornate Helm of Brilliance' },
  { label: 'Eagle Bite Demon Crown of Titans +1', value: 'Eagle Bite Demon Crown of Titans +1' },
  { label: 'Eagle Grasp Great Helm of Giants +1', value: 'Eagle Grasp Great Helm of Giants +1' },
  { label: 'Eagle Shout Leather Cap of Skill +1', value: 'Eagle Shout Leather Cap of Skill +1' },
  { label: 'Fate Roar Ornate Helm of Reflection', value: 'Fate Roar Ornate Helm of Reflection' },
  { label: 'Fate Root Ornate Helm of Brilliance', value: 'Fate Root Ornate Helm of Brilliance' },
  { label: 'Foe Bender Demon Crown of Titans +1', value: 'Foe Bender Demon Crown of Titans +1' },
  { label: 'Ghoul Tear Ornate Helm of the Twins', value: 'Ghoul Tear Ornate Helm of the Twins' },
  { label: 'Gloom Peak Divine Hood of Titans +1', value: 'Gloom Peak Divine Hood of Titans +1' },
  { label: 'Gloom Peak Leather Cap of Titans +1', value: 'Gloom Peak Leather Cap of Titans +1' },
  { label: 'Grim Grasp Demon Crown of Giants +1', value: 'Grim Grasp Demon Crown of Giants +1' },
  { label: 'Havoc Root Linen Hood of Brilliance', value: 'Havoc Root Linen Hood of Brilliance' },
  { label: 'Havoc Root Linen Hood of Protection', value: 'Havoc Root Linen Hood of Protection' },
  { label: 'Havoc Whisper Linen Hood of the Fox', value: 'Havoc Whisper Linen Hood of the Fox' },
  { label: 'Honour Moon Demon Crown of Skill +1', value: 'Honour Moon Demon Crown of Skill +1' },
  { label: 'Kraken Moon Demon Crown of Skill +1', value: 'Kraken Moon Demon Crown of Skill +1' },
  { label: 'Kraken Shout Divine Hood of Rage +1', value: 'Kraken Shout Divine Hood of Rage +1' },
  { label: 'Maelstrom Tear Linen Hood of Giants', value: 'Maelstrom Tear Linen Hood of Giants' },
  { label: 'Mind Bender Divine Hood of Anger +1', value: 'Mind Bender Divine Hood of Anger +1' },
  { label: 'Morbid Tear Linen Hood of the Twins', value: 'Morbid Tear Linen Hood of the Twins' },
  { label: 'Pain Glow Ornate Helm of Protection', value: 'Pain Glow Ornate Helm of Protection' },
  { label: 'Apocalypse Glow Helm of Protection', value: 'Apocalypse Glow Helm of Protection' },
  { label: 'Apocalypse Roar War Cap of the Fox', value: 'Apocalypse Roar War Cap of the Fox' },
  { label: 'Apocalypse Tear Crown of the Twins', value: 'Apocalypse Tear Crown of the Twins' },
  { label: 'Blight Grasp Hood of Protection +1', value: 'Blight Grasp Hood of Protection +1' },
  { label: 'Bramble Glow War Cap of Protection', value: 'Bramble Glow War Cap of Protection' },
  { label: 'Bramble Tear War Cap of Protection', value: 'Bramble Tear War Cap of Protection' },
  { label: 'Corruption Peak Hood of the Fox +1', value: 'Corruption Peak Hood of the Fox +1' },
  { label: 'Death Sun Linen Hood of Reflection', value: 'Death Sun Linen Hood of Reflection' },
  { label: 'Death Sun War Cap of Enlightenment', value: 'Death Sun War Cap of Enlightenment' },
  { label: 'Demon Bite Demon Crown of Power +1', value: 'Demon Bite Demon Crown of Power +1' },
  { label: 'Demon Grasp Great Helm of Skill +1', value: 'Demon Grasp Great Helm of Skill +1' },
  { label: 'Dragon Roar Crown of Enlightenment', value: 'Dragon Roar Crown of Enlightenment' },
  { label: 'Dread Bender Hood of Perfection +1', value: 'Dread Bender Hood of Perfection +1' },
  { label: 'Dread Peak Leather Cap of Power +1', value: 'Dread Peak Leather Cap of Power +1' },
  { label: 'Dusk Tear Ornate Helm of Detection', value: 'Dusk Tear Ornate Helm of Detection' },
  { label: 'Eagle Bite Leather Cap of Anger +1', value: 'Eagle Bite Leather Cap of Anger +1' },
  { label: 'Eagle Moon Divine Hood of Skill +1', value: 'Eagle Moon Divine Hood of Skill +1' },
  { label: 'Eagle Moon Leather Cap of Skill +1', value: 'Eagle Moon Leather Cap of Skill +1' },
  { label: 'Fate Root Ornate Helm of the Twins', value: 'Fate Root Ornate Helm of the Twins' },
  { label: 'Fate Whisper Ornate Helm of Titans', value: 'Fate Whisper Ornate Helm of Titans' },
  { label: 'Ghoul Whisper Ornate Helm of Anger', value: 'Ghoul Whisper Ornate Helm of Anger' },
  { label: 'Gloom Grasp Great Helm of Skill +1', value: 'Gloom Grasp Great Helm of Skill +1' },
  { label: 'Golem Root Linen Hood of Detection', value: 'Golem Root Linen Hood of Detection' },
  { label: 'Golem Whisper Ornate Helm of Anger', value: 'Golem Whisper Ornate Helm of Anger' },
  { label: 'Grim Bender Divine Hood of Fury +1', value: 'Grim Bender Divine Hood of Fury +1' },
  { label: 'Grim Grasp Leather Cap of Skill +1', value: 'Grim Grasp Leather Cap of Skill +1' },
  { label: 'Grim Peak Divine Hood of Titans +1', value: 'Grim Peak Divine Hood of Titans +1' },
  { label: 'Grim Peak Great Helm of the Fox +1', value: 'Grim Peak Great Helm of the Fox +1' },
  { label: 'Grim Shout Demon Crown of Skill +1', value: 'Grim Shout Demon Crown of Skill +1' },
  { label: 'Honour Moon Leather Cap of Rage +1', value: 'Honour Moon Leather Cap of Rage +1' },
  { label: 'Hypnotic Sun War Cap of Perfection', value: 'Hypnotic Sun War Cap of Perfection' },
  { label: 'Kraken Bite Leather Cap of Fury +1', value: 'Kraken Bite Leather Cap of Fury +1' },
  { label: 'Kraken Grasp Hood of Brilliance +1', value: 'Kraken Grasp Hood of Brilliance +1' },
  { label: 'Kraken Grasp Hood of Protection +1', value: 'Kraken Grasp Hood of Protection +1' },
  { label: 'Kraken Peak Great Helm of Anger +1', value: 'Kraken Peak Great Helm of Anger +1' },
  { label: "Light's Glow Linen Hood of Vitriol", value: "Light's Glow Linen Hood of Vitriol" },
  { label: "Light's Root Linen Hood of Vitriol", value: "Light's Root Linen Hood of Vitriol" },
  { label: 'Maelstrom Roar Ornate Helm of Fury', value: 'Maelstrom Roar Ornate Helm of Fury' },
  { label: 'Mind Bite Divine Hood of Titans +1', value: 'Mind Bite Divine Hood of Titans +1' },
  { label: 'Mind Shout Leather Cap of Skill +1', value: 'Mind Shout Leather Cap of Skill +1' },
  { label: 'Morbid Root Ornate Helm of Vitriol', value: 'Morbid Root Ornate Helm of Vitriol' },
  { label: 'Morbid Whisper Linen Hood of Power', value: 'Morbid Whisper Linen Hood of Power' },
  { label: 'Armageddon Bite Hood of Titans +1', value: 'Armageddon Bite Hood of Titans +1' },
  { label: 'Blight Bite Great Helm of Fury +1', value: 'Blight Bite Great Helm of Fury +1' },
  { label: 'Blight Grasp Hood of Detection +1', value: 'Blight Grasp Hood of Detection +1' },
  { label: 'Bramble Glow Ornate Helm of Skill', value: 'Bramble Glow Ornate Helm of Skill' },
  { label: 'Brimstone Bender Hood of Power +1', value: 'Brimstone Bender Hood of Power +1' },
  { label: 'Carrion Glow Ornate Helm of Skill', value: 'Carrion Glow Ornate Helm of Skill' },
  { label: 'Carrion Glow War Cap of the Twins', value: 'Carrion Glow War Cap of the Twins' },
  { label: 'Corpse Root Ornate Helm of Giants', value: 'Corpse Root Ornate Helm of Giants' },
  { label: 'Demon Bite Leather Cap of Fury +1', value: 'Demon Bite Leather Cap of Fury +1' },
  { label: 'Demon Moon Leather Cap of Rage +1', value: 'Demon Moon Leather Cap of Rage +1' },
  { label: 'Demon Shout Great Helm of Rage +1', value: 'Demon Shout Great Helm of Rage +1' },
  { label: 'Dragon Root Ornate Helm of Giants', value: 'Dragon Root Ornate Helm of Giants' },
  { label: 'Dread Moon Divine Hood of Rage +1', value: 'Dread Moon Divine Hood of Rage +1' },
  { label: 'Eagle Grasp Great Helm of Rage +1', value: 'Eagle Grasp Great Helm of Rage +1' },
  { label: 'Eagle Shout Hood of Brilliance +1', value: 'Eagle Shout Hood of Brilliance +1' },
  { label: 'Ghoul Whisper Linen Hood of Power', value: 'Ghoul Whisper Linen Hood of Power' },
  { label: 'Gloom Bite Great Helm of Power +1', value: 'Gloom Bite Great Helm of Power +1' },
  { label: 'Gloom Grasp Hood of Brilliance +1', value: 'Gloom Grasp Hood of Brilliance +1' },
  { label: 'Gloom Moon Demon Crown of Rage +1', value: 'Gloom Moon Demon Crown of Rage +1' },
  { label: 'Gloom Peak Leather Cap of Fury +1', value: 'Gloom Peak Leather Cap of Fury +1' },
  { label: 'Golem Roar Crown of Enlightenment', value: 'Golem Roar Crown of Enlightenment' },
  { label: 'Golem Whisper Crown of Perfection', value: 'Golem Whisper Crown of Perfection' },
  { label: 'Golem Whisper Linen Hood of Anger', value: 'Golem Whisper Linen Hood of Anger' },
  { label: 'Golem Whisper Ornate Helm of Fury', value: 'Golem Whisper Ornate Helm of Fury' },
  { label: 'Grim Grasp Demon Crown of Rage +1', value: 'Grim Grasp Demon Crown of Rage +1' },
  { label: 'Grim Peak Great Helm of Titans +1', value: 'Grim Peak Great Helm of Titans +1' },
  { label: 'Hypnotic Tear Crown of Protection', value: 'Hypnotic Tear Crown of Protection' },
  { label: 'Kraken Shout Hood of the Twins +1', value: 'Kraken Shout Hood of the Twins +1' },
  { label: "Light's Glow Linen Hood of Giants", value: "Light's Glow Linen Hood of Giants" },
  { label: "Light's Tear Ornate Helm of Skill", value: "Light's Tear Ornate Helm of Skill" },
  { label: 'Maelstrom Tear Crown of the Twins', value: 'Maelstrom Tear Crown of the Twins' },
  { label: 'Maelstrom Tear Helm of Brilliance', value: 'Maelstrom Tear Helm of Brilliance' },
  { label: 'Mind Grasp Leather Cap of Rage +1', value: 'Mind Grasp Leather Cap of Rage +1' },
  { label: 'Mind Shout Great Helm of Skill +1', value: 'Mind Shout Great Helm of Skill +1' },
  { label: 'Morbid Roar Ornate Helm of Titans', value: 'Morbid Roar Ornate Helm of Titans' },
  { label: 'Morbid Tear Linen Hood of Vitriol', value: 'Morbid Tear Linen Hood of Vitriol' },
  { label: 'Oblivion Bender Hood of Titans +1', value: 'Oblivion Bender Hood of Titans +1' },
  { label: 'Apocalypse Glow Crown of Vitriol', value: 'Apocalypse Glow Crown of Vitriol' },
  { label: 'Behemoth Roar Linen Hood of Fury', value: 'Behemoth Roar Linen Hood of Fury' },
  { label: 'Behemoth Root Crown of the Twins', value: 'Behemoth Root Crown of the Twins' },
  { label: 'Behemoth Tear Helm of Brilliance', value: 'Behemoth Tear Helm of Brilliance' },
  { label: 'Bramble Roar Ornate Helm of Fury', value: 'Bramble Roar Ornate Helm of Fury' },
  { label: 'Bramble Tear Crown of Protection', value: 'Bramble Tear Crown of Protection' },
  { label: 'Carrion Roar Ornate Helm of Fury', value: 'Carrion Roar Ornate Helm of Fury' },
  { label: 'Carrion Root Ornate Helm of Rage', value: 'Carrion Root Ornate Helm of Rage' },
  { label: 'Cataclysm Bite Hood of Titans +1', value: 'Cataclysm Bite Hood of Titans +1' },
  { label: 'Cataclysm Grasp Hood of Skill +1', value: 'Cataclysm Grasp Hood of Skill +1' },
  { label: 'Cataclysm Shout Hood of Skill +1', value: 'Cataclysm Shout Hood of Skill +1' },
  { label: 'Corpse Sun Ornate Helm of Titans', value: 'Corpse Sun Ornate Helm of Titans' },
  { label: 'Corpse Tear War Cap of Detection', value: 'Corpse Tear War Cap of Detection' },
  { label: 'Corruption Peak Hood of Anger +1', value: 'Corruption Peak Hood of Anger +1' },
  { label: 'Dragon Sun War Cap of Perfection', value: 'Dragon Sun War Cap of Perfection' },
  { label: 'Dread Bite Great Helm of Fury +1', value: 'Dread Bite Great Helm of Fury +1' },
  { label: 'Eagle Shout Hood of Detection +1', value: 'Eagle Shout Hood of Detection +1' },
  { label: 'Ghoul Glow Ornate Helm of Giants', value: 'Ghoul Glow Ornate Helm of Giants' },
  { label: 'Golem Roar War Cap of Reflection', value: 'Golem Roar War Cap of Reflection' },
  { label: 'Golem Root War Cap of Brilliance', value: 'Golem Root War Cap of Brilliance' },
  { label: 'Golem Whisper Helm of Perfection', value: 'Golem Whisper Helm of Perfection' },
  { label: 'Golem Whisper Linen Hood of Fury', value: 'Golem Whisper Linen Hood of Fury' },
  { label: 'Havoc Roar Ornate Helm of Titans', value: 'Havoc Roar Ornate Helm of Titans' },
  { label: 'Hypnotic Glow War Cap of Vitriol', value: 'Hypnotic Glow War Cap of Vitriol' },
  { label: 'Hypnotic Roar Linen Hood of Fury', value: 'Hypnotic Roar Linen Hood of Fury' },
  { label: 'Hypnotic Root War Cap of Vitriol', value: 'Hypnotic Root War Cap of Vitriol' },
  { label: 'Hypnotic Sun Crown of Perfection', value: 'Hypnotic Sun Crown of Perfection' },
  { label: "Light's Glow Linen Hood of Skill", value: "Light's Glow Linen Hood of Skill" },
  { label: 'Mind Bite Great Helm of Anger +1', value: 'Mind Bite Great Helm of Anger +1' },
  { label: 'Morbid Glow Linen Hood of Giants', value: 'Morbid Glow Linen Hood of Giants' },
  { label: 'Apocalypse Roar War Cap of Fury', value: 'Apocalypse Roar War Cap of Fury' },
  { label: 'Apocalypse Root Crown of Giants', value: 'Apocalypse Root Crown of Giants' },
  { label: 'Apocalypse Tear War Cap of Rage', value: 'Apocalypse Tear War Cap of Rage' },
  { label: 'Behemoth Root War Cap of Giants', value: 'Behemoth Root War Cap of Giants' },
  { label: 'Behemoth Tear War Cap of Giants', value: 'Behemoth Tear War Cap of Giants' },
  { label: 'Bramble Roar Helm of Reflection', value: 'Bramble Roar Helm of Reflection' },
  { label: 'Bramble Root War Cap of Vitriol', value: 'Bramble Root War Cap of Vitriol' },
  { label: 'Bramble Sun Linen Hood of Anger', value: 'Bramble Sun Linen Hood of Anger' },
  { label: 'Bramble Whisper War Cap of Fury', value: 'Bramble Whisper War Cap of Fury' },
  { label: 'Carrion Roar Linen Hood of Fury', value: 'Carrion Roar Linen Hood of Fury' },
  { label: 'Carrion Whisper Helm of the Fox', value: 'Carrion Whisper Helm of the Fox' },
  { label: 'Corpse Roar Linen Hood of Power', value: 'Corpse Roar Linen Hood of Power' },
  { label: 'Corruption Peak Hood of Fury +1', value: 'Corruption Peak Hood of Fury +1' },
  { label: 'Death Root Ornate Helm of Skill', value: 'Death Root Ornate Helm of Skill' },
  { label: 'Dusk Whisper Helm of Reflection', value: 'Dusk Whisper Helm of Reflection' },
  { label: 'Eagle Bender Hood of the Fox +1', value: 'Eagle Bender Hood of the Fox +1' },
  { label: 'Eagle Moon Hood of the Twins +1', value: 'Eagle Moon Hood of the Twins +1' },
  { label: 'Fate Tear Linen Hood of Vitriol', value: 'Fate Tear Linen Hood of Vitriol' },
  { label: 'Fate Whisper Linen Hood of Fury', value: 'Fate Whisper Linen Hood of Fury' },
  { label: 'Foe Bite Leather Cap of Fury +1', value: 'Foe Bite Leather Cap of Fury +1' },
  { label: 'Ghoul Roar Ornate Helm of Power', value: 'Ghoul Roar Ornate Helm of Power' },
  { label: 'Ghoul Root War Cap of Detection', value: 'Ghoul Root War Cap of Detection' },
  { label: 'Ghoul Sun War Cap of Perfection', value: 'Ghoul Sun War Cap of Perfection' },
  { label: 'Golem Roar Ornate Helm of Power', value: 'Golem Roar Ornate Helm of Power' },
  { label: 'Grim Bite Great Helm of Fury +1', value: 'Grim Bite Great Helm of Fury +1' },
  { label: 'Grim Peak Hood of Reflection +1', value: 'Grim Peak Hood of Reflection +1' },
  { label: 'Grim Shout Hood of the Twins +1', value: 'Grim Shout Hood of the Twins +1' },
  { label: 'Havoc Roar Ornate Helm of Power', value: 'Havoc Roar Ornate Helm of Power' },
  { label: 'Honour Bender Hood of Titans +1', value: 'Honour Bender Hood of Titans +1' },
  { label: 'Honour Shout Hood of Vitriol +1', value: 'Honour Shout Hood of Vitriol +1' },
  { label: 'Morbid Glow Crown of Brilliance', value: 'Morbid Glow Crown of Brilliance' },
  { label: 'Oblivion Bite Hood of Titans +1', value: 'Oblivion Bite Hood of Titans +1' },
  { label: 'Pain Glow Ornate Helm of Giants', value: 'Pain Glow Ornate Helm of Giants' },
  { label: 'Blight Shout Hood of Giants +1', value: 'Blight Shout Hood of Giants +1' },
  { label: 'Carrion Glow War Cap of Giants', value: 'Carrion Glow War Cap of Giants' },
  { label: 'Carrion Sun Helm of Reflection', value: 'Carrion Sun Helm of Reflection' },
  { label: 'Corpse Tear Helm of Brilliance', value: 'Corpse Tear Helm of Brilliance' },
  { label: 'Death Glow Linen Hood of Skill', value: 'Death Glow Linen Hood of Skill' },
  { label: 'Death Root Crown of Brilliance', value: 'Death Root Crown of Brilliance' },
  { label: 'Dragon Tear Linen Hood of Rage', value: 'Dragon Tear Linen Hood of Rage' },
  { label: 'Dusk Roar Ornate Helm of Power', value: 'Dusk Roar Ornate Helm of Power' },
  { label: 'Fate Roar Linen Hood of Titans', value: 'Fate Roar Linen Hood of Titans' },
  { label: 'Fate Root Ornate Helm of Skill', value: 'Fate Root Ornate Helm of Skill' },
  { label: 'Ghoul Roar Crown of Perfection', value: 'Ghoul Roar Crown of Perfection' },
  { label: 'Ghoul Roar Crown of Reflection', value: 'Ghoul Roar Crown of Reflection' },
  { label: 'Ghoul Sun Ornate Helm of Anger', value: 'Ghoul Sun Ornate Helm of Anger' },
  { label: 'Golem Glow Crown of Brilliance', value: 'Golem Glow Crown of Brilliance' },
  { label: 'Golem Glow Linen Hood of Skill', value: 'Golem Glow Linen Hood of Skill' },
  { label: 'Havoc Glow Ornate Helm of Rage', value: 'Havoc Glow Ornate Helm of Rage' },
  { label: 'Havoc Tear Linen Hood of Skill', value: 'Havoc Tear Linen Hood of Skill' },
  { label: 'Honour Bender Hood of Anger +1', value: 'Honour Bender Hood of Anger +1' },
  { label: 'Kraken Bite Hood of the Fox +1', value: 'Kraken Bite Hood of the Fox +1' },
  { label: 'Morbid Glow Crown of the Twins', value: 'Morbid Glow Crown of the Twins' },
  { label: 'Morbid Whisper War Cap of Fury', value: 'Morbid Whisper War Cap of Fury' },
  { label: 'Apocalypse Root Helm of Skill', value: 'Apocalypse Root Helm of Skill' },
  { label: 'Behemoth Root War Cap of Rage', value: 'Behemoth Root War Cap of Rage' },
  { label: 'Blight Shout Hood of Skill +1', value: 'Blight Shout Hood of Skill +1' },
  { label: 'Bramble Root War Cap of Skill', value: 'Bramble Root War Cap of Skill' },
  { label: 'Carrion Roar War Cap of Power', value: 'Carrion Roar War Cap of Power' },
  { label: 'Corpse Glow War Cap of Giants', value: 'Corpse Glow War Cap of Giants' },
  { label: 'Dusk Whisper War Cap of Anger', value: 'Dusk Whisper War Cap of Anger' },
  { label: 'Dusk Whisper War Cap of Power', value: 'Dusk Whisper War Cap of Power' },
  { label: 'Eagle Grasp Hood of Giants +1', value: 'Eagle Grasp Hood of Giants +1' },
  { label: 'Foe Moon Hood of Detection +1', value: 'Foe Moon Hood of Detection +1' },
  { label: 'Gloom Grasp Hood of Giants +1', value: 'Gloom Grasp Hood of Giants +1' },
  { label: 'Gloom Peak Hood of the Fox +1', value: 'Gloom Peak Hood of the Fox +1' },
  { label: 'Golem Roar Helm of Perfection', value: 'Golem Roar Helm of Perfection' },
  { label: 'Golem Tear Crown of the Twins', value: 'Golem Tear Crown of the Twins' },
  { label: 'Grim Shout Hood of Vitriol +1', value: 'Grim Shout Hood of Vitriol +1' },
  { label: 'Havoc Root Helm of Protection', value: 'Havoc Root Helm of Protection' },
  { label: "Light's Roar War Cap of Power", value: "Light's Roar War Cap of Power" },
  { label: "Light's Whisper Helm of Power", value: "Light's Whisper Helm of Power" },
  { label: 'Maelstrom Sun War Cap of Fury', value: 'Maelstrom Sun War Cap of Fury' },
  { label: 'Mind Shout Hood of Vitriol +1', value: 'Mind Shout Hood of Vitriol +1' },
  { label: 'Morbid Tear Helm of the Twins', value: 'Morbid Tear Helm of the Twins' },
  { label: 'Blight Peak Hood of Anger +1', value: 'Blight Peak Hood of Anger +1' },
  { label: 'Blight Shout Hood of Rage +1', value: 'Blight Shout Hood of Rage +1' },
  { label: 'Bramble Glow Helm of Vitriol', value: 'Bramble Glow Helm of Vitriol' },
  { label: 'Bramble Root War Cap of Rage', value: 'Bramble Root War Cap of Rage' },
  { label: 'Bramble Sun War Cap of Power', value: 'Bramble Sun War Cap of Power' },
  { label: 'Carrion Sun Crown of the Fox', value: 'Carrion Sun Crown of the Fox' },
  { label: 'Carrion Whisper Helm of Fury', value: 'Carrion Whisper Helm of Fury' },
  { label: 'Death Root War Cap of Giants', value: 'Death Root War Cap of Giants' },
  { label: 'Death Whisper Crown of Anger', value: 'Death Whisper Crown of Anger' },
  { label: 'Dusk Roar Linen Hood of Fury', value: 'Dusk Roar Linen Hood of Fury' },
  { label: 'Golem Sun Helm of Reflection', value: 'Golem Sun Helm of Reflection' },
  { label: 'Golem Whisper Crown of Power', value: 'Golem Whisper Crown of Power' },
  { label: 'Havoc Glow Helm of Detection', value: 'Havoc Glow Helm of Detection' },
  { label: 'Hypnotic Roar Crown of Anger', value: 'Hypnotic Roar Crown of Anger' },
  { label: 'Hypnotic Roar Crown of Power', value: 'Hypnotic Roar Crown of Power' },
  { label: "Light's Glow Crown of Giants", value: "Light's Glow Crown of Giants" },
  { label: 'Maelstrom Root Helm of Skill', value: 'Maelstrom Root Helm of Skill' },
  { label: 'Mind Bender Hood of Power +1', value: 'Mind Bender Hood of Power +1' },
  { label: 'Mind Moon Hood of Vitriol +1', value: 'Mind Moon Hood of Vitriol +1' },
  { label: 'Morbid Roar Crown of the Fox', value: 'Morbid Roar Crown of the Fox' },
  { label: 'Carrion Glow Helm of Giants', value: 'Carrion Glow Helm of Giants' },
  { label: 'Carrion Roar Helm of Titans', value: 'Carrion Roar Helm of Titans' },
  { label: 'Corpse Roar War Cap of Fury', value: 'Corpse Roar War Cap of Fury' },
  { label: 'Corpse Root Crown of Giants', value: 'Corpse Root Crown of Giants' },
  { label: 'Demon Bite Hood of Power +1', value: 'Demon Bite Hood of Power +1' },
  { label: 'Dragon Glow Crown of Giants', value: 'Dragon Glow Crown of Giants' },
  { label: 'Dragon Tear Crown of Giants', value: 'Dragon Tear Crown of Giants' },
  { label: 'Dread Moon Hood of Skill +1', value: 'Dread Moon Hood of Skill +1' },
  { label: 'Fate Glow War Cap of Giants', value: 'Fate Glow War Cap of Giants' },
  { label: 'Fate Tear Helm of Detection', value: 'Fate Tear Helm of Detection' },
  { label: 'Foe Bender Hood of Anger +1', value: 'Foe Bender Hood of Anger +1' },
  { label: 'Ghoul Roar War Cap of Power', value: 'Ghoul Roar War Cap of Power' },
  { label: 'Ghoul Tear Crown of Vitriol', value: 'Ghoul Tear Crown of Vitriol' },
  { label: 'Gloom Shout Hood of Rage +1', value: 'Gloom Shout Hood of Rage +1' },
  { label: 'Grim Bender Hood of Fury +1', value: 'Grim Bender Hood of Fury +1' },
  { label: 'Mind Grasp Hood of Skill +1', value: 'Mind Grasp Hood of Skill +1' },
  { label: 'Morbid Root Crown of Giants', value: 'Morbid Root Crown of Giants' },
  { label: 'Morbid Tear Helm of Vitriol', value: 'Morbid Tear Helm of Vitriol' },
  { label: 'Death Glow Helm of Vitriol', value: 'Death Glow Helm of Vitriol' },
  { label: 'Death Root Helm of Vitriol', value: 'Death Root Helm of Vitriol' },
  { label: 'Demon Moon Hood of Rage +1', value: 'Demon Moon Hood of Rage +1' },
  { label: 'Dragon Root Crown of Skill', value: 'Dragon Root Crown of Skill' },
  { label: 'Dusk Glow Crown of Vitriol', value: 'Dusk Glow Crown of Vitriol' },
  { label: 'Dusk Roar War Cap of Anger', value: 'Dusk Roar War Cap of Anger' },
  { label: 'Fate Glow War Cap of Skill', value: 'Fate Glow War Cap of Skill' },
  { label: 'Fate Sun War Cap of Titans', value: 'Fate Sun War Cap of Titans' },
  { label: 'Golem Glow Crown of Giants', value: 'Golem Glow Crown of Giants' },
  { label: 'Golem Whisper Helm of Fury', value: 'Golem Whisper Helm of Fury' },
  { label: 'Havoc Roar Helm of the Fox', value: 'Havoc Roar Helm of the Fox' },
  { label: 'Hypnotic Tear Helm of Rage', value: 'Hypnotic Tear Helm of Rage' },
  { label: 'Carrion Tear Helm of Rage', value: 'Carrion Tear Helm of Rage' },
  { label: 'Death Root Helm of Giants', value: 'Death Root Helm of Giants' },
  { label: 'Dusk Roar Helm of the Fox', value: 'Dusk Roar Helm of the Fox' },
  { label: 'Dusk Roar War Cap of Fury', value: 'Dusk Roar War Cap of Fury' },
  { label: 'Dusk Tear Helm of Vitriol', value: 'Dusk Tear Helm of Vitriol' },
  { label: 'Fate Roar Helm of the Fox', value: 'Fate Roar Helm of the Fox' },
  { label: 'Ghoul Root Crown of Skill', value: 'Ghoul Root Crown of Skill' },
  { label: 'Golem Glow Helm of Giants', value: 'Golem Glow Helm of Giants' },
  { label: 'Golem Tear Helm of Giants', value: 'Golem Tear Helm of Giants' },
  { label: 'Grim Bite Hood of Fury +1', value: 'Grim Bite Hood of Fury +1' },
  { label: 'Leather Cap of Brilliance', value: 'Leather Cap of Brilliance' },
  { label: 'Mind Moon Hood of Rage +1', value: 'Mind Moon Hood of Rage +1' },
  { label: 'Morbid Sun Crown of Anger', value: 'Morbid Sun Crown of Anger' },
  { label: 'Corpse Tear Helm of Rage', value: 'Corpse Tear Helm of Rage' },
  { label: 'Dragon Root Helm of Rage', value: 'Dragon Root Helm of Rage' },
  { label: 'Dusk Glow Crown of Skill', value: 'Dusk Glow Crown of Skill' },
  { label: 'Fate Sun Crown of Titans', value: 'Fate Sun Crown of Titans' },
  { label: 'Ghoul Glow Crown of Rage', value: 'Ghoul Glow Crown of Rage' },
  { label: 'Ghoul Sun Crown of Anger', value: 'Ghoul Sun Crown of Anger' },
  { label: 'Ghoul Sun Helm of Titans', value: 'Ghoul Sun Helm of Titans' },
  { label: 'Great Helm of Protection', value: 'Great Helm of Protection' },
  { label: 'Morbid Sun Helm of Power', value: 'Morbid Sun Helm of Power' },
  { label: 'Dusk Glow Crown of Rage', value: 'Dusk Glow Crown of Rage' },
  { label: 'Ghoul Root Helm of Rage', value: 'Ghoul Root Helm of Rage' },
  { label: 'Golem Roar Helm of Fury', value: 'Golem Roar Helm of Fury' },
  { label: 'Golem Sun Crown of Fury', value: 'Golem Sun Crown of Fury' },
  { label: 'Havoc Roar Helm of Fury', value: 'Havoc Roar Helm of Fury' },
  { label: 'Pain Roar Crown of Fury', value: 'Pain Roar Crown of Fury' },
  { label: 'Fate Roar Helm of Fury', value: 'Fate Roar Helm of Fury' },
  { label: 'Crown of Power', value: 'Crown of Power' },
  { label: 'Helm of Anger', value: 'Helm of Anger' },
  { label: 'Hood of Anger', value: 'Hood of Anger' },
  { label: 'Pain Roar Linen Hood of Reflection', value: 'Pain Roar Linen Hood of Reflection' },
  { label: 'Pain Root Linen Hood of Detection', value: 'Pain Root Linen Hood of Detection' },
  { label: 'Pain Sun Crown of Titans', value: 'Pain Sun Crown of Titans' },
  { label: 'Pain Sun War Cap of Fury', value: 'Pain Sun War Cap of Fury' },
  { label: 'Pain Tear Crown of Rage', value: 'Pain Tear Crown of Rage' },
  { label: 'Pain Tear Helm of Rage', value: 'Pain Tear Helm of Rage' },
  { label: 'Pain Tear Linen Hood of the Twins', value: 'Pain Tear Linen Hood of the Twins' },
  { label: 'Pain Tear Ornate Helm of Skill', value: 'Pain Tear Ornate Helm of Skill' },
  { label: 'Pain Whisper Ornate Helm of Anger', value: 'Pain Whisper Ornate Helm of Anger' },
  { label: 'Pain Whisper Ornate Helm of Perfection', value: 'Pain Whisper Ornate Helm of Perfection' },
  { label: 'Pain Whisper War Cap of Titans', value: 'Pain Whisper War Cap of Titans' },
  { label: 'Pandemonium Bender Demon Crown of Fury +1', value: 'Pandemonium Bender Demon Crown of Fury +1' },
  { label: 'Pandemonium Bender Divine Hood of Anger +1', value: 'Pandemonium Bender Divine Hood of Anger +1' },
  { label: 'Pandemonium Bite Demon Crown of Perfection +1', value: 'Pandemonium Bite Demon Crown of Perfection +1' },
  { label: 'Pandemonium Bite Divine Hood of Titans +1', value: 'Pandemonium Bite Divine Hood of Titans +1' },
  { label: 'Pandemonium Grasp Demon Crown of Rage +1', value: 'Pandemonium Grasp Demon Crown of Rage +1' },
  { label: 'Pandemonium Grasp Hood of Rage +1', value: 'Pandemonium Grasp Hood of Rage +1' },
  { label: 'Pandemonium Grasp Leather Cap of Protection +1', value: 'Pandemonium Grasp Leather Cap of Protection +1' },
  { label: 'Pandemonium Grasp Leather Cap of Skill +1', value: 'Pandemonium Grasp Leather Cap of Skill +1' },
  { label: 'Pandemonium Moon Great Helm of Skill +1', value: 'Pandemonium Moon Great Helm of Skill +1' },
  { label: 'Pandemonium Moon Hood of Detection +1', value: 'Pandemonium Moon Hood of Detection +1' },
  { label: 'Pandemonium Peak Divine Hood of Fury +1', value: 'Pandemonium Peak Divine Hood of Fury +1' },
  { label: 'Pandemonium Peak Great Helm of Fury +1', value: 'Pandemonium Peak Great Helm of Fury +1' },
  { label: 'Pandemonium Peak Great Helm of the Fox +1', value: 'Pandemonium Peak Great Helm of the Fox +1' },
  { label: 'Pandemonium Peak Hood of Enlightenment +1', value: 'Pandemonium Peak Hood of Enlightenment +1' },
  { label: 'Pandemonium Shout Demon Crown of Giants +1', value: 'Pandemonium Shout Demon Crown of Giants +1' },
  { label: 'Pandemonium Shout Great Helm of the Twins +1', value: 'Pandemonium Shout Great Helm of the Twins +1' },
  { label: 'Plague Glow Crown of Giants', value: 'Plague Glow Crown of Giants' },
  { label: 'Plague Glow Crown of Protection', value: 'Plague Glow Crown of Protection' },
  { label: 'Plague Glow Crown of Skill', value: 'Plague Glow Crown of Skill' },
  { label: 'Plague Glow Crown of the Twins', value: 'Plague Glow Crown of the Twins' },
  { label: 'Plague Glow War Cap of Rage', value: 'Plague Glow War Cap of Rage' },
  { label: 'Plague Roar Helm of Enlightenment', value: 'Plague Roar Helm of Enlightenment' },
  { label: 'Plague Roar Linen Hood of Titans', value: 'Plague Roar Linen Hood of Titans' },
  { label: 'Plague Roar War Cap of Enlightenment', value: 'Plague Roar War Cap of Enlightenment' },
  { label: 'Plague Roar War Cap of Power', value: 'Plague Roar War Cap of Power' },
  { label: 'Plague Root Crown of Skill', value: 'Plague Root Crown of Skill' },
  { label: 'Plague Root Helm of Detection', value: 'Plague Root Helm of Detection' },
  { label: 'Plague Root Ornate Helm of the Twins', value: 'Plague Root Ornate Helm of the Twins' },
  { label: 'Plague Sun Ornate Helm of Anger', value: 'Plague Sun Ornate Helm of Anger' },
  { label: 'Plague Tear Linen Hood of Rage', value: 'Plague Tear Linen Hood of Rage' },
  { label: 'Plague Tear Linen Hood of Skill', value: 'Plague Tear Linen Hood of Skill' },
  { label: 'Plague Whisper Helm of Anger', value: 'Plague Whisper Helm of Anger' },
  { label: 'Rage Bender Demon Crown of Perfection +1', value: 'Rage Bender Demon Crown of Perfection +1' },
  { label: 'Rage Bite Divine Hood of Anger +1', value: 'Rage Bite Divine Hood of Anger +1' },
  { label: 'Rage Bite Leather Cap of Fury +1', value: 'Rage Bite Leather Cap of Fury +1' },
  { label: 'Rage Grasp Great Helm of the Twins +1', value: 'Rage Grasp Great Helm of the Twins +1' },
  { label: 'Rage Moon Demon Crown of Giants +1', value: 'Rage Moon Demon Crown of Giants +1' },
  { label: 'Rage Moon Demon Crown of the Twins +1', value: 'Rage Moon Demon Crown of the Twins +1' },
  { label: 'Rage Moon Divine Hood of Giants +1', value: 'Rage Moon Divine Hood of Giants +1' },
  { label: 'Rage Moon Divine Hood of Protection +1', value: 'Rage Moon Divine Hood of Protection +1' },
  { label: 'Rage Moon Hood of Skill +1', value: 'Rage Moon Hood of Skill +1' },
  { label: 'Rage Peak Demon Crown of Titans +1', value: 'Rage Peak Demon Crown of Titans +1' },
  { label: 'Rage Peak Hood of Enlightenment +1', value: 'Rage Peak Hood of Enlightenment +1' },
  { label: 'Rage Peak Hood of Perfection +1', value: 'Rage Peak Hood of Perfection +1' },
  { label: 'Rage Shout Hood of Brilliance +1', value: 'Rage Shout Hood of Brilliance +1' },
  { label: 'Rage Shout Leather Cap of Giants +1', value: 'Rage Shout Leather Cap of Giants +1' },
  { label: 'Rune Glow Helm of Brilliance', value: 'Rune Glow Helm of Brilliance' },
  { label: 'Rune Glow Ornate Helm of Skill', value: 'Rune Glow Ornate Helm of Skill' },
  { label: 'Rune Glow Ornate Helm of Vitriol', value: 'Rune Glow Ornate Helm of Vitriol' },
  { label: 'Rune Roar Linen Hood of Fury', value: 'Rune Roar Linen Hood of Fury' },
  { label: 'Rune Roar Ornate Helm of the Fox', value: 'Rune Roar Ornate Helm of the Fox' },
  { label: 'Rune Root Crown of the Twins', value: 'Rune Root Crown of the Twins' },
  { label: 'Rune Root Helm of Giants', value: 'Rune Root Helm of Giants' },
  { label: 'Rune Root Ornate Helm of Brilliance', value: 'Rune Root Ornate Helm of Brilliance' },
  { label: 'Rune Root War Cap of Brilliance', value: 'Rune Root War Cap of Brilliance' },
  { label: 'Rune Root War Cap of Giants', value: 'Rune Root War Cap of Giants' },
  { label: 'Rune Sun Crown of the Fox', value: 'Rune Sun Crown of the Fox' },
  { label: 'Rune Sun Helm of Enlightenment', value: 'Rune Sun Helm of Enlightenment' },
  { label: 'Rune Sun Helm of the Fox', value: 'Rune Sun Helm of the Fox' },
  { label: 'Rune Tear Helm of Vitriol', value: 'Rune Tear Helm of Vitriol' },
  { label: 'Rune Tear Linen Hood of Giants', value: 'Rune Tear Linen Hood of Giants' },
  { label: 'Rune Tear Ornate Helm of Giants', value: 'Rune Tear Ornate Helm of Giants' },
  { label: 'Rune Tear Ornate Helm of Vitriol', value: 'Rune Tear Ornate Helm of Vitriol' },
  { label: 'Rune Whisper Helm of Fury', value: 'Rune Whisper Helm of Fury' },
  { label: 'Rune Whisper Linen Hood of Titans', value: 'Rune Whisper Linen Hood of Titans' },
  { label: 'Shimmering Bender Divine Hood of Titans +1', value: 'Shimmering Bender Divine Hood of Titans +1' },
  { label: 'Shimmering Bender Great Helm of Perfection +1', value: 'Shimmering Bender Great Helm of Perfection +1' },
  { label: 'Shimmering Bender Hood of Enlightenment +1', value: 'Shimmering Bender Hood of Enlightenment +1' },
  { label: 'Shimmering Bender Hood of Reflection +1', value: 'Shimmering Bender Hood of Reflection +1' },
  { label: 'Shimmering Grasp Divine Hood of Brilliance +1', value: 'Shimmering Grasp Divine Hood of Brilliance +1' },
  { label: 'Shimmering Grasp Great Helm of the Twins +1', value: 'Shimmering Grasp Great Helm of the Twins +1' },
  { label: 'Shimmering Grasp Hood of Vitriol +1', value: 'Shimmering Grasp Hood of Vitriol +1' },
  { label: 'Shimmering Grasp Leather Cap of Protection +1', value: 'Shimmering Grasp Leather Cap of Protection +1' },
  { label: 'Shimmering Moon Demon Crown of Giants +1', value: 'Shimmering Moon Demon Crown of Giants +1' },
  { label: 'Shimmering Moon Hood of Vitriol +1', value: 'Shimmering Moon Hood of Vitriol +1' },
  { label: 'Shimmering Peak Great Helm of Perfection +1', value: 'Shimmering Peak Great Helm of Perfection +1' },
  { label: 'Shimmering Peak Hood of Power +1', value: 'Shimmering Peak Hood of Power +1' },
  { label: 'Shimmering Peak Leather Cap of Titans +1', value: 'Shimmering Peak Leather Cap of Titans +1' },
  { label: 'Skull Bender Divine Hood of Reflection +1', value: 'Skull Bender Divine Hood of Reflection +1' },
  { label: 'Skull Bender Great Helm of Titans +1', value: 'Skull Bender Great Helm of Titans +1' },
  { label: 'Skull Bender Leather Cap of Titans +1', value: 'Skull Bender Leather Cap of Titans +1' },
  { label: 'Skull Bite Divine Hood of Power +1', value: 'Skull Bite Divine Hood of Power +1' },
  { label: 'Skull Bite Hood of Perfection +1', value: 'Skull Bite Hood of Perfection +1' },
  { label: 'Skull Bite Leather Cap of Enlightenment +1', value: 'Skull Bite Leather Cap of Enlightenment +1' },
  { label: 'Skull Grasp Demon Crown of Detection +1', value: 'Skull Grasp Demon Crown of Detection +1' },
  { label: 'Skull Grasp Demon Crown of Skill +1', value: 'Skull Grasp Demon Crown of Skill +1' },
  { label: 'Skull Grasp Divine Hood of Vitriol +1', value: 'Skull Grasp Divine Hood of Vitriol +1' },
  { label: 'Skull Grasp Great Helm of Detection +1', value: 'Skull Grasp Great Helm of Detection +1' },
  { label: 'Skull Moon Leather Cap of Giants +1', value: 'Skull Moon Leather Cap of Giants +1' },
  { label: 'Skull Peak Leather Cap of Reflection +1', value: 'Skull Peak Leather Cap of Reflection +1' },
  { label: 'Skull Shout Demon Crown of Brilliance +1', value: 'Skull Shout Demon Crown of Brilliance +1' },
  { label: 'Skull Shout Divine Hood of Brilliance +1', value: 'Skull Shout Divine Hood of Brilliance +1' },
  { label: 'Skull Shout Divine Hood of Detection +1', value: 'Skull Shout Divine Hood of Detection +1' },
  { label: 'Skull Shout Great Helm of Giants +1', value: 'Skull Shout Great Helm of Giants +1' },
  { label: 'Skull Shout Great Helm of Skill +1', value: 'Skull Shout Great Helm of Skill +1' },
  { label: 'Skull Shout Hood of Vitriol +1', value: 'Skull Shout Hood of Vitriol +1' },
  { label: 'Skull Shout Leather Cap of Protection +1', value: 'Skull Shout Leather Cap of Protection +1' },
  { label: 'Sorrow Bender Hood of Titans +1', value: 'Sorrow Bender Hood of Titans +1' },
  { label: 'Sorrow Bender Leather Cap of the Fox +1', value: 'Sorrow Bender Leather Cap of the Fox +1' },
  { label: 'Sorrow Bite Divine Hood of Anger +1', value: 'Sorrow Bite Divine Hood of Anger +1' },
  { label: 'Sorrow Grasp Divine Hood of Brilliance +1', value: 'Sorrow Grasp Divine Hood of Brilliance +1' },
  { label: 'Sorrow Grasp Divine Hood of Vitriol +1', value: 'Sorrow Grasp Divine Hood of Vitriol +1' },
  { label: 'Sorrow Grasp Leather Cap of Skill +1', value: 'Sorrow Grasp Leather Cap of Skill +1' },
  { label: 'Sorrow Moon Demon Crown of Giants +1', value: 'Sorrow Moon Demon Crown of Giants +1' },
  { label: 'Sorrow Moon Hood of Detection +1', value: 'Sorrow Moon Hood of Detection +1' },
  { label: 'Sorrow Moon Hood of Protection +1', value: 'Sorrow Moon Hood of Protection +1' },
  { label: 'Sorrow Moon Hood of Rage +1', value: 'Sorrow Moon Hood of Rage +1' },
  { label: 'Sorrow Moon Leather Cap of Giants +1', value: 'Sorrow Moon Leather Cap of Giants +1' },
  { label: 'Sorrow Peak Divine Hood of the Fox +1', value: 'Sorrow Peak Divine Hood of the Fox +1' },
  { label: 'Sorrow Peak Leather Cap of Fury +1', value: 'Sorrow Peak Leather Cap of Fury +1' },
  { label: 'Sorrow Shout Demon Crown of Skill +1', value: 'Sorrow Shout Demon Crown of Skill +1' },
  { label: 'Sorrow Shout Divine Hood of Skill +1', value: 'Sorrow Shout Divine Hood of Skill +1' },
  { label: 'Sorrow Shout Great Helm of Skill +1', value: 'Sorrow Shout Great Helm of Skill +1' },
  { label: 'Sorrow Shout Leather Cap of Detection +1', value: 'Sorrow Shout Leather Cap of Detection +1' },
  { label: 'Soul Glow Crown of Detection', value: 'Soul Glow Crown of Detection' },
  { label: 'Soul Glow Crown of Giants', value: 'Soul Glow Crown of Giants' },
  { label: 'Soul Glow Helm of Vitriol', value: 'Soul Glow Helm of Vitriol' },
  { label: 'Soul Glow Ornate Helm of the Twins', value: 'Soul Glow Ornate Helm of the Twins' },
  { label: 'Soul Glow War Cap of Giants', value: 'Soul Glow War Cap of Giants' },
  { label: 'Soul Roar Linen Hood of Enlightenment', value: 'Soul Roar Linen Hood of Enlightenment' },
  { label: 'Soul Roar Linen Hood of Reflection', value: 'Soul Roar Linen Hood of Reflection' },
  { label: 'Soul Roar Ornate Helm of the Fox', value: 'Soul Roar Ornate Helm of the Fox' },
  { label: 'Soul Root Helm of Detection', value: 'Soul Root Helm of Detection' },
  { label: 'Soul Root Linen Hood of Detection', value: 'Soul Root Linen Hood of Detection' },
  { label: 'Soul Root Ornate Helm of Vitriol', value: 'Soul Root Ornate Helm of Vitriol' },
  { label: 'Soul Sun Crown of Fury', value: 'Soul Sun Crown of Fury' },
  { label: 'Soul Sun Crown of Reflection', value: 'Soul Sun Crown of Reflection' },
  { label: 'Soul Sun Helm of Titans', value: 'Soul Sun Helm of Titans' },
  { label: 'Soul Sun Linen Hood of Enlightenment', value: 'Soul Sun Linen Hood of Enlightenment' },
  { label: 'Soul Sun Ornate Helm of Anger', value: 'Soul Sun Ornate Helm of Anger' },
  { label: 'Soul Tear Crown of Detection', value: 'Soul Tear Crown of Detection' },
  { label: 'Soul Tear Helm of Detection', value: 'Soul Tear Helm of Detection' },
  { label: 'Soul Tear War Cap of Giants', value: 'Soul Tear War Cap of Giants' },
  { label: 'Soul Whisper Crown of Fury', value: 'Soul Whisper Crown of Fury' },
  { label: 'Soul Whisper Crown of Perfection', value: 'Soul Whisper Crown of Perfection' },
  { label: 'Soul Whisper Crown of Power', value: 'Soul Whisper Crown of Power' },
  { label: 'Soul Whisper Linen Hood of Fury', value: 'Soul Whisper Linen Hood of Fury' },
  { label: 'Soul Whisper Linen Hood of Power', value: 'Soul Whisper Linen Hood of Power' },
  { label: 'Soul Whisper Ornate Helm of Enlightenment', value: 'Soul Whisper Ornate Helm of Enlightenment' },
  { label: 'Storm Roar Crown of Titans', value: 'Storm Roar Crown of Titans' },
  { label: 'Storm Roar Helm of Perfection', value: 'Storm Roar Helm of Perfection' },
  { label: 'Storm Root Ornate Helm of Giants', value: 'Storm Root Ornate Helm of Giants' },
  { label: 'Storm Tear Crown of Giants', value: 'Storm Tear Crown of Giants' },
  { label: 'Storm Tear Crown of Rage', value: 'Storm Tear Crown of Rage' },
  { label: 'Storm Tear Linen Hood of Protection', value: 'Storm Tear Linen Hood of Protection' },
  { label: 'Storm Tear Ornate Helm of the Twins', value: 'Storm Tear Ornate Helm of the Twins' },
  { label: 'Storm Tear War Cap of Brilliance', value: 'Storm Tear War Cap of Brilliance' },
  { label: 'Storm Whisper War Cap of Power', value: 'Storm Whisper War Cap of Power' },
  { label: 'Tempest Bender Demon Crown of Titans +1', value: 'Tempest Bender Demon Crown of Titans +1' },
  { label: 'Tempest Bender Hood of Enlightenment +1', value: 'Tempest Bender Hood of Enlightenment +1' },
  { label: 'Tempest Bender Hood of the Fox +1', value: 'Tempest Bender Hood of the Fox +1' },
  { label: 'Tempest Bender Leather Cap of the Fox +1', value: 'Tempest Bender Leather Cap of the Fox +1' },
  { label: 'Tempest Bite Great Helm of Power +1', value: 'Tempest Bite Great Helm of Power +1' },
  { label: 'Tempest Grasp Divine Hood of Brilliance +1', value: 'Tempest Grasp Divine Hood of Brilliance +1' },
  { label: 'Tempest Grasp Great Helm of Detection +1', value: 'Tempest Grasp Great Helm of Detection +1' },
  { label: 'Tempest Grasp Great Helm of Skill +1', value: 'Tempest Grasp Great Helm of Skill +1' },
  { label: 'Tempest Moon Great Helm of Brilliance +1', value: 'Tempest Moon Great Helm of Brilliance +1' },
  { label: 'Tempest Moon Hood of Rage +1', value: 'Tempest Moon Hood of Rage +1' },
  { label: 'Tempest Peak Demon Crown of Reflection +1', value: 'Tempest Peak Demon Crown of Reflection +1' },
  { label: 'Tempest Peak Great Helm of Titans +1', value: 'Tempest Peak Great Helm of Titans +1' },
  { label: 'Tempest Peak Hood of Reflection +1', value: 'Tempest Peak Hood of Reflection +1' },
  { label: 'Tempest Peak Leather Cap of Enlightenment +1', value: 'Tempest Peak Leather Cap of Enlightenment +1' },
  { label: 'Tempest Peak Leather Cap of the Fox +1', value: 'Tempest Peak Leather Cap of the Fox +1' },
  { label: 'Tempest Shout Demon Crown of Detection +1', value: 'Tempest Shout Demon Crown of Detection +1' },
  { label: 'Tempest Shout Hood of Vitriol +1', value: 'Tempest Shout Hood of Vitriol +1' },
  { label: 'Vengeance Glow War Cap of Vitriol', value: 'Vengeance Glow War Cap of Vitriol' },
  { label: 'Vengeance Roar Crown of Perfection', value: 'Vengeance Roar Crown of Perfection' },
  { label: 'Vengeance Roar Helm of Enlightenment', value: 'Vengeance Roar Helm of Enlightenment' },
  { label: 'Vengeance Roar Helm of Power', value: 'Vengeance Roar Helm of Power' },
  { label: 'Vengeance Roar Helm of Titans', value: 'Vengeance Roar Helm of Titans' },
  { label: 'Vengeance Roar Linen Hood of Fury', value: 'Vengeance Roar Linen Hood of Fury' },
  { label: 'Vengeance Roar Linen Hood of Reflection', value: 'Vengeance Roar Linen Hood of Reflection' },
  { label: 'Vengeance Root Linen Hood of Brilliance', value: 'Vengeance Root Linen Hood of Brilliance' },
  { label: 'Vengeance Root War Cap of Rage', value: 'Vengeance Root War Cap of Rage' },
  { label: 'Vengeance Sun Crown of Anger', value: 'Vengeance Sun Crown of Anger' },
  { label: 'Vengeance Sun Helm of Anger', value: 'Vengeance Sun Helm of Anger' },
  { label: 'Vengeance Sun Helm of the Fox', value: 'Vengeance Sun Helm of the Fox' },
  { label: 'Vengeance Sun Ornate Helm of the Fox', value: 'Vengeance Sun Ornate Helm of the Fox' },
  { label: 'Vengeance Tear Crown of the Twins', value: 'Vengeance Tear Crown of the Twins' },
  { label: 'Vengeance Tear Crown of Vitriol', value: 'Vengeance Tear Crown of Vitriol' },
  { label: 'Vengeance Tear Helm of Rage', value: 'Vengeance Tear Helm of Rage' },
  { label: 'Vengeance Tear Helm of Skill', value: 'Vengeance Tear Helm of Skill' },
  { label: 'Vengeance Tear Linen Hood of Giants', value: 'Vengeance Tear Linen Hood of Giants' },
  { label: 'Vengeance Tear Linen Hood of Rage', value: 'Vengeance Tear Linen Hood of Rage' },
  { label: 'Vengeance Whisper Crown of Enlightenment', value: 'Vengeance Whisper Crown of Enlightenment' },
  { label: 'Victory Bender Demon Crown of Fury +1', value: 'Victory Bender Demon Crown of Fury +1' },
  { label: 'Victory Bite Demon Crown of Reflection +1', value: 'Victory Bite Demon Crown of Reflection +1' },
  { label: 'Victory Bite Divine Hood of Perfection +1', value: 'Victory Bite Divine Hood of Perfection +1' },
  { label: 'Victory Bite Great Helm of Perfection +1', value: 'Victory Bite Great Helm of Perfection +1' },
  { label: 'Victory Bite Great Helm of Titans +1', value: 'Victory Bite Great Helm of Titans +1' },
  { label: 'Victory Bite Hood of Titans +1', value: 'Victory Bite Hood of Titans +1' },
  { label: 'Victory Bite Leather Cap of Enlightenment +1', value: 'Victory Bite Leather Cap of Enlightenment +1' },
  { label: 'Victory Bite Leather Cap of Titans +1', value: 'Victory Bite Leather Cap of Titans +1' },
  { label: 'Victory Grasp Demon Crown of Vitriol +1', value: 'Victory Grasp Demon Crown of Vitriol +1' },
  { label: 'Victory Grasp Divine Hood of Giants +1', value: 'Victory Grasp Divine Hood of Giants +1' },
  { label: 'Victory Grasp Divine Hood of Rage +1', value: 'Victory Grasp Divine Hood of Rage +1' },
  { label: 'Victory Grasp Leather Cap of Skill +1', value: 'Victory Grasp Leather Cap of Skill +1' },
  { label: 'Victory Moon Hood of Detection +1', value: 'Victory Moon Hood of Detection +1' },
  { label: 'Victory Moon Hood of Vitriol +1', value: 'Victory Moon Hood of Vitriol +1' },
  { label: 'Victory Peak Demon Crown of Reflection +1', value: 'Victory Peak Demon Crown of Reflection +1' },
  { label: 'Victory Peak Divine Hood of Titans +1', value: 'Victory Peak Divine Hood of Titans +1' },
  { label: 'Victory Shout Demon Crown of Detection +1', value: 'Victory Shout Demon Crown of Detection +1' },
  { label: 'Victory Shout Divine Hood of Protection +1', value: 'Victory Shout Divine Hood of Protection +1' },
  { label: 'Victory Shout Great Helm of the Twins +1', value: 'Victory Shout Great Helm of the Twins +1' },
  { label: 'Victory Shout Hood of the Twins +1', value: 'Victory Shout Hood of the Twins +1' },
  { label: 'Vortex Glow Linen Hood of Brilliance', value: 'Vortex Glow Linen Hood of Brilliance' },
  { label: 'Vortex Glow Linen Hood of the Twins', value: 'Vortex Glow Linen Hood of the Twins' },
  { label: 'Vortex Glow Ornate Helm of the Twins', value: 'Vortex Glow Ornate Helm of the Twins' },
  { label: 'Vortex Glow War Cap of the Twins', value: 'Vortex Glow War Cap of the Twins' },
  { label: 'Vortex Roar Ornate Helm of Perfection', value: 'Vortex Roar Ornate Helm of Perfection' },
  { label: 'Vortex Roar Ornate Helm of Titans', value: 'Vortex Roar Ornate Helm of Titans' },
  { label: 'Vortex Root Ornate Helm of Giants', value: 'Vortex Root Ornate Helm of Giants' },
  { label: 'Vortex Sun Crown of Power', value: 'Vortex Sun Crown of Power' },
  { label: 'Vortex Whisper Crown of Fury', value: 'Vortex Whisper Crown of Fury' },
  { label: 'Vortex Whisper Crown of Titans', value: 'Vortex Whisper Crown of Titans' },
  { label: 'Vortex Whisper Helm of Anger', value: 'Vortex Whisper Helm of Anger' },
  { label: 'Vortex Whisper Helm of Enlightenment', value: 'Vortex Whisper Helm of Enlightenment' },
  { label: 'Vortex Whisper War Cap of Anger', value: 'Vortex Whisper War Cap of Anger' },
  { label: 'War Cap of Rage', value: 'War Cap of Rage' },
  { label: 'War Cap of the Fox', value: 'War Cap of the Fox' },
  { label: 'Woe Bender Leather Cap of Fury +1', value: 'Woe Bender Leather Cap of Fury +1' },
  { label: 'Woe Grasp Divine Hood of Detection +1', value: 'Woe Grasp Divine Hood of Detection +1' },
  { label: 'Woe Grasp Hood of the Twins +1', value: 'Woe Grasp Hood of the Twins +1' },
  { label: 'Woe Grasp Leather Cap of Protection +1', value: 'Woe Grasp Leather Cap of Protection +1' },
  { label: 'Woe Moon Divine Hood of the Twins +1', value: 'Woe Moon Divine Hood of the Twins +1' },
  { label: 'Woe Moon Great Helm of Giants +1', value: 'Woe Moon Great Helm of Giants +1' },
  { label: 'Woe Moon Hood of Rage +1', value: 'Woe Moon Hood of Rage +1' },
  { label: 'Woe Peak Hood of Power +1', value: 'Woe Peak Hood of Power +1' },
  { label: 'Woe Shout Great Helm of Brilliance +1', value: 'Woe Shout Great Helm of Brilliance +1' },
  { label: 'Woe Shout Hood of Giants +1', value: 'Woe Shout Hood of Giants +1' },
  { label: 'Woe Shout Leather Cap of the Twins +1', value: 'Woe Shout Leather Cap of the Twins +1' },
];
