export const waists = [
  { label: 'War Belt', value: 'War Belt' },
  { label: 'Heavy Belt', value: 'Heavy Belt' },
  { label: 'Wool Sash', value: 'Wool Sash' },
  { label: 'Silk Sash', value: 'Silk Sash' },
  { label: 'Linen Sash', value: 'Linen Sash' },
  { label: 'Ornate Belt', value: 'Ornate Belt' },
  { label: 'Plated Belt', value: 'Plated Belt' },
  { label: 'Dragonskin Belt', value: 'Dragonskin Belt' },
  { label: 'Brightsilk Sash', value: 'Brightsilk Sash' },
  { label: 'Leather Belt', value: 'Leather Belt' },
  { label: 'Demonhide Belt', value: 'Demonhide Belt' },
  { label: 'Studded Leather Belt', value: 'Studded Leather Belt' },
  { label: 'Sash', value: 'Sash' },
  { label: 'Hard Leather Belt', value: 'Hard Leather Belt' },
  { label: 'Mesh Belt', value: 'Mesh Belt' },
  { label: 'Dragonskin Belt of Enlightenment', value: 'Dragonskin Belt of Enlightenment' },
  { label: 'Leather Belt of Reflection', value: 'Leather Belt of Reflection' },
  { label: 'Wool Sash of Giants', value: 'Wool Sash of Giants' },
  { label: 'Ornate Belt of Perfection', value: 'Ornate Belt of Perfection' },
  { label: 'Leather Belt of Enlightenment', value: 'Leather Belt of Enlightenment' },
  { label: 'Leather Belt of Power', value: 'Leather Belt of Power' },
  { label: 'Dragonskin Belt of Brilliance', value: 'Dragonskin Belt of Brilliance' },
  { label: 'Wool Sash of Rage', value: 'Wool Sash of Rage' },
  { label: 'Dragonskin Belt of Vitriol', value: 'Dragonskin Belt of Vitriol' },
  { label: 'Leather Belt of Perfection', value: 'Leather Belt of Perfection' },
  { label: 'Leather Belt of Vitriol', value: 'Leather Belt of Vitriol' },
  { label: 'Leather Belt of Fury', value: 'Leather Belt of Fury' },
  { label: 'Ornate Belt of Skill', value: 'Ornate Belt of Skill' },
  { label: 'Mesh Belt of Titans', value: 'Mesh Belt of Titans' },
  { label: 'Ornate Belt of Fury', value: 'Ornate Belt of Fury' },
  { label: 'Mesh Belt of Anger', value: 'Mesh Belt of Anger' },
  { label: 'Wool Sash of Skill', value: 'Wool Sash of Skill' },
  { label: 'Dragonskin Belt of Protection', value: 'Dragonskin Belt of Protection' },
  { label: 'Leather Belt of Protection', value: 'Leather Belt of Protection' },
  { label: 'Ornate Belt of Brilliance', value: 'Ornate Belt of Brilliance' },
  { label: 'Dragonskin Belt of Anger', value: 'Dragonskin Belt of Anger' },
  { label: 'Ornate Belt of Detection', value: 'Ornate Belt of Detection' },
  { label: 'Mesh Belt of Brilliance', value: 'Mesh Belt of Brilliance' },
  { label: 'Wool Sash of Protection', value: 'Wool Sash of Protection' },
  { label: 'Leather Belt of Giants', value: 'Leather Belt of Giants' },
  { label: 'Wool Sash of the Twins', value: 'Wool Sash of the Twins' },
  { label: 'Leather Belt of Anger', value: 'Leather Belt of Anger' },
  { label: 'Wool Sash of Titans', value: 'Wool Sash of Titans' },
  { label: 'Mesh Belt of Rage', value: 'Mesh Belt of Rage' },
  { label: 'Dragonskin Belt of Perfection', value: 'Dragonskin Belt of Perfection' },
  { label: 'Dragonskin Belt of Detection', value: 'Dragonskin Belt of Detection' },
  { label: 'Dragonskin Belt of the Twins', value: 'Dragonskin Belt of the Twins' },
  { label: 'Hard Leather Belt of Vitriol', value: 'Hard Leather Belt of Vitriol' },
  { label: 'Plated Belt of Enlightenment', value: 'Plated Belt of Enlightenment' },
  { label: 'Wool Sash of Enlightenment', value: 'Wool Sash of Enlightenment' },
  { label: 'Dragonskin Belt of Giants', value: 'Dragonskin Belt of Giants' },
  { label: 'Hard Leather Belt of Rage', value: 'Hard Leather Belt of Rage' },
  { label: 'Leather Belt of Detection', value: 'Leather Belt of Detection' },
  { label: 'Ornate Belt of the Twins', value: 'Ornate Belt of the Twins' },
  { label: 'Mesh Belt of Perfection', value: 'Mesh Belt of Perfection' },
  { label: 'Silk Sash of Protection', value: 'Silk Sash of Protection' },
  { label: 'Mesh Belt of Detection', value: 'Mesh Belt of Detection' },
  { label: 'Ornate Belt of Titans', value: 'Ornate Belt of Titans' },
  { label: 'Mesh Belt of Giants', value: 'Mesh Belt of Giants' },
  { label: 'Silk Sash of Titans', value: 'Silk Sash of Titans' },
  { label: 'Wool Sash of Anger', value: 'Wool Sash of Anger' },
  { label: 'Brightsilk Sash of the Fox', value: 'Brightsilk Sash of the Fox' },
  { label: 'Hard Leather Belt of Power', value: 'Hard Leather Belt of Power' },
  { label: 'Hard Leather Belt of Skill', value: 'Hard Leather Belt of Skill' },
  { label: 'Leather Belt of Brilliance', value: 'Leather Belt of Brilliance' },
  { label: 'Plated Belt of Brilliance', value: 'Plated Belt of Brilliance' },
  { label: 'Dragonskin Belt of Skill', value: 'Dragonskin Belt of Skill' },
  { label: 'Linen Sash of Perfection', value: 'Linen Sash of Perfection' },
  { label: 'Dragonskin Belt of Fury', value: 'Dragonskin Belt of Fury' },
  { label: 'Leather Belt of the Fox', value: 'Leather Belt of the Fox' },
  { label: 'Mesh Belt of Reflection', value: 'Mesh Belt of Reflection' },
  { label: 'Silk Sash of Brilliance', value: 'Silk Sash of Brilliance' },
  { label: 'Wool Sash of Brilliance', value: 'Wool Sash of Brilliance' },
  { label: 'Leather Belt of Skill', value: 'Leather Belt of Skill' },
  { label: 'Ornate Belt of Giants', value: 'Ornate Belt of Giants' },
  { label: 'Mesh Belt of Vitriol', value: 'Mesh Belt of Vitriol' },
  { label: 'Ornate Belt of Rage', value: 'Ornate Belt of Rage' },
  { label: 'Brightsilk Sash of Vitriol', value: 'Brightsilk Sash of Vitriol' },
  { label: 'Mesh Belt of Enlightenment', value: 'Mesh Belt of Enlightenment' },
  { label: 'Dragonskin Belt of Power', value: 'Dragonskin Belt of Power' },
  { label: 'Linen Sash of Detection', value: 'Linen Sash of Detection' },
  { label: 'Demonhide Belt of Fury', value: 'Demonhide Belt of Fury' },
  { label: 'Leather Belt of Titans', value: 'Leather Belt of Titans' },
  { label: 'War Belt of Detection', value: 'War Belt of Detection' },
  { label: 'Mesh Belt of the Fox', value: 'Mesh Belt of the Fox' },
  { label: 'Ornate Belt of Power', value: 'Ornate Belt of Power' },
  { label: 'Linen Sash of Skill', value: 'Linen Sash of Skill' },
  { label: 'Mesh Belt of Fury', value: 'Mesh Belt of Fury' },
  { label: 'War Belt of Skill', value: 'War Belt of Skill' },
  { label: 'Sash of Rage', value: 'Sash of Rage' },
  { label: 'Hard Leather Belt of Perfection', value: 'Hard Leather Belt of Perfection' },
  { label: 'Hard Leather Belt of Protection', value: 'Hard Leather Belt of Protection' },
  { label: 'Hard Leather Belt of the Twins', value: 'Hard Leather Belt of the Twins' },
  { label: 'Studded Leather Belt of Power', value: 'Studded Leather Belt of Power' },
  { label: 'Studded Leather Belt of Skill', value: 'Studded Leather Belt of Skill' },
  { label: 'Brightsilk Sash of the Twins', value: 'Brightsilk Sash of the Twins' },
  { label: 'Ornate Belt of Enlightenment', value: 'Ornate Belt of Enlightenment' },
  { label: 'Dragonskin Belt of the Fox', value: 'Dragonskin Belt of the Fox' },
  { label: 'Dragonskin Belt of Titans', value: 'Dragonskin Belt of Titans' },
  { label: 'Leather Belt of the Twins', value: 'Leather Belt of the Twins' },
  { label: 'Demonhide Belt of Anger', value: 'Demonhide Belt of Anger' },
  { label: 'Linen Sash of the Twins', value: 'Linen Sash of the Twins' },
  { label: 'Mesh Belt of Protection', value: 'Mesh Belt of Protection' },
  { label: 'Mesh Belt of the Twins', value: 'Mesh Belt of the Twins' },
  { label: 'Ornate Belt of the Fox', value: 'Ornate Belt of the Fox' },
  { label: 'War Belt of Brilliance', value: 'War Belt of Brilliance' },
  { label: 'Linen Sash of the Fox', value: 'Linen Sash of the Fox' },
  { label: 'Ornate Belt of Anger', value: 'Ornate Belt of Anger' },
  { label: 'Wool Sash of Vitriol', value: 'Wool Sash of Vitriol' },
  { label: 'Plated Belt of Fury', value: 'Plated Belt of Fury' },
  { label: 'Mesh Belt of Skill', value: 'Mesh Belt of Skill' },
  { label: 'Sash of Protection', value: 'Sash of Protection' },
  { label: 'Silk Sash of Anger', value: 'Silk Sash of Anger' },
  { label: 'Silk Sash of Power', value: 'Silk Sash of Power' },
  { label: 'Wool Sash of Power', value: 'Wool Sash of Power' },
  { label: 'Silk Sash of Fury', value: 'Silk Sash of Fury' },
  { label: 'Silk Sash of Rage', value: 'Silk Sash of Rage' },
  { label: 'War Belt of Power', value: 'War Belt of Power' },
  { label: 'Sash of Anger', value: 'Sash of Anger' },
  { label: 'Hard Leather Belt of Enlightenment', value: 'Hard Leather Belt of Enlightenment' },
  { label: 'Studded Leather Belt of the Twins', value: 'Studded Leather Belt of the Twins' },
  { label: 'Studded Leather Belt of the Fox', value: 'Studded Leather Belt of the Fox' },
  { label: 'Studded Leather Belt of Titans', value: 'Studded Leather Belt of Titans' },
  { label: 'Brightsilk Sash of Reflection', value: 'Brightsilk Sash of Reflection' },
  { label: 'Studded Leather Belt of Anger', value: 'Studded Leather Belt of Anger' },
  { label: 'Demonhide Belt of the Twins', value: 'Demonhide Belt of the Twins' },
  { label: 'Hard Leather Belt of Anger', value: 'Hard Leather Belt of Anger' },
  { label: 'Brightsilk Sash of Anger', value: 'Brightsilk Sash of Anger' },
  { label: 'Brightsilk Sash of Skill', value: 'Brightsilk Sash of Skill' },
  { label: 'Brightsilk Sash of Fury', value: 'Brightsilk Sash of Fury' },
  { label: 'Brightsilk Sash of Rage', value: 'Brightsilk Sash of Rage' },
  { label: 'Demonhide Belt of Power', value: 'Demonhide Belt of Power' },
  { label: 'Heavy Belt of Detection', value: 'Heavy Belt of Detection' },
  { label: 'War Belt of Perfection', value: 'War Belt of Perfection' },
  { label: 'Plated Belt of Giants', value: 'Plated Belt of Giants' },
  { label: 'War Belt of the Twins', value: 'War Belt of the Twins' },
  { label: 'Heavy Belt of Titans', value: 'Heavy Belt of Titans' },
  { label: 'Leather Belt of Rage', value: 'Leather Belt of Rage' },
  { label: 'Wool Sash of the Fox', value: 'Wool Sash of the Fox' },
  { label: 'Heavy Belt of Skill', value: 'Heavy Belt of Skill' },
  { label: 'Sash of Perfection', value: 'Sash of Perfection' },
  { label: 'Wool Sash of Fury', value: 'Wool Sash of Fury' },
  { label: 'Studded Leather Belt of Enlightenment', value: 'Studded Leather Belt of Enlightenment' },
  { label: 'Studded Leather Belt of Perfection', value: 'Studded Leather Belt of Perfection' },
  { label: 'Studded Leather Belt of Protection', value: 'Studded Leather Belt of Protection' },
  { label: 'Hard Leather Belt of Detection', value: 'Hard Leather Belt of Detection' },
  { label: 'Studded Leather Belt of Giants', value: 'Studded Leather Belt of Giants' },
  { label: 'Brightsilk Sash of Brilliance', value: 'Brightsilk Sash of Brilliance' },
  { label: 'Brightsilk Sash of Protection', value: 'Brightsilk Sash of Protection' },
  { label: 'Brightsilk Sash of Detection', value: 'Brightsilk Sash of Detection' },
  { label: 'Studded Leather Belt of Fury', value: 'Studded Leather Belt of Fury' },
  { label: 'Studded Leather Belt of Rage', value: 'Studded Leather Belt of Rage' },
  { label: 'Demonhide Belt of Detection', value: 'Demonhide Belt of Detection' },
  { label: 'Ornate Belt of Protection', value: 'Ornate Belt of Protection' },
  { label: 'Ornate Belt of Reflection', value: 'Ornate Belt of Reflection' },
  { label: 'Demonhide Belt of Giants', value: 'Demonhide Belt of Giants' },
  { label: 'Heavy Belt of Perfection', value: 'Heavy Belt of Perfection' },
  { label: 'Plated Belt of Detection', value: 'Plated Belt of Detection' },
  { label: 'Demonhide Belt of Skill', value: 'Demonhide Belt of Skill' },
  { label: 'Dragonskin Belt of Rage', value: 'Dragonskin Belt of Rage' },
  { label: 'Wool Sash of Reflection', value: 'Wool Sash of Reflection' },
  { label: 'Demonhide Belt of Rage', value: 'Demonhide Belt of Rage' },
  { label: 'Ornate Belt of Vitriol', value: 'Ornate Belt of Vitriol' },
  { label: 'Plated Belt of Vitriol', value: 'Plated Belt of Vitriol' },
  { label: 'Wool Sash of Detection', value: 'Wool Sash of Detection' },
  { label: 'Heavy Belt of the Fox', value: 'Heavy Belt of the Fox' },
  { label: 'Linen Sash of Vitriol', value: 'Linen Sash of Vitriol' },
  { label: 'Heavy Belt of Anger', value: 'Heavy Belt of Anger' },
  { label: 'Heavy Belt of Power', value: 'Heavy Belt of Power' },
  { label: 'War Belt of Vitriol', value: 'War Belt of Vitriol' },
  { label: 'Heavy Belt of Fury', value: 'Heavy Belt of Fury' },
  { label: 'Sash of Brilliance', value: 'Sash of Brilliance' },
  { label: 'War Belt of Titans', value: 'War Belt of Titans' },
  { label: 'War Belt of Fury', value: 'War Belt of Fury' },
  { label: 'Studded Leather Belt of Brilliance', value: 'Studded Leather Belt of Brilliance' },
  { label: 'Hard Leather Belt of Brilliance', value: 'Hard Leather Belt of Brilliance' },
  { label: 'Studded Leather Belt of Vitriol', value: 'Studded Leather Belt of Vitriol' },
  { label: 'Brightsilk Sash of Perfection', value: 'Brightsilk Sash of Perfection' },
  { label: 'Dragonskin Belt of Reflection', value: 'Dragonskin Belt of Reflection' },
  { label: 'Demonhide Belt of Brilliance', value: 'Demonhide Belt of Brilliance' },
  { label: 'Demonhide Belt of Perfection', value: 'Demonhide Belt of Perfection' },
  { label: 'Demonhide Belt of Protection', value: 'Demonhide Belt of Protection' },
  { label: 'Demonhide Belt of Reflection', value: 'Demonhide Belt of Reflection' },
  { label: 'Hard Leather Belt of Titans', value: 'Hard Leather Belt of Titans' },
  { label: 'Heavy Belt of Enlightenment', value: 'Heavy Belt of Enlightenment' },
  { label: 'Silk Sash of Enlightenment', value: 'Silk Sash of Enlightenment' },
  { label: 'Plated Belt of Protection', value: 'Plated Belt of Protection' },
  { label: 'War Belt of Enlightenment', value: 'War Belt of Enlightenment' },
  { label: 'Brightsilk Sash of Power', value: 'Brightsilk Sash of Power' },
  { label: 'Heavy Belt of Brilliance', value: 'Heavy Belt of Brilliance' },
  { label: 'Heavy Belt of Protection', value: 'Heavy Belt of Protection' },
  { label: 'Linen Sash of Brilliance', value: 'Linen Sash of Brilliance' },
  { label: 'Plated Belt of the Twins', value: 'Plated Belt of the Twins' },
  { label: 'Heavy Belt of the Twins', value: 'Heavy Belt of the Twins' },
  { label: 'Silk Sash of Reflection', value: 'Silk Sash of Reflection' },
  { label: 'Wool Sash of Perfection', value: 'Wool Sash of Perfection' },
  { label: 'Plated Belt of the Fox', value: 'Plated Belt of the Fox' },
  { label: 'Silk Sash of the Twins', value: 'Silk Sash of the Twins' },
  { label: 'War Belt of Reflection', value: 'War Belt of Reflection' },
  { label: 'Plated Belt of Titans', value: 'Plated Belt of Titans' },
  { label: 'Linen Sash of Giants', value: 'Linen Sash of Giants' },
  { label: 'Plated Belt of Power', value: 'Plated Belt of Power' },
  { label: 'Silk Sash of Vitriol', value: 'Silk Sash of Vitriol' },
  { label: 'Mesh Belt of Power', value: 'Mesh Belt of Power' },
  { label: 'Sash of Detection', value: 'Sash of Detection' },
  { label: 'War Belt of Rage', value: 'War Belt of Rage' },
  { label: 'Sash of Giants', value: 'Sash of Giants' },
  { label: 'Sash of Titans', value: 'Sash of Titans' },
  { label: 'Sash of Power', value: 'Sash of Power' },
  { label: 'Tempest Peak Silk Sash of the Fox +1', value: 'Tempest Peak Silk Sash of the Fox +1' },
  { label: 'Studded Leather Belt of Detection', value: 'Studded Leather Belt of Detection' },
  { label: 'Hard Leather Belt of Reflection', value: 'Hard Leather Belt of Reflection' },
  { label: 'Ghoul Tear Heavy Belt of Rage', value: 'Ghoul Tear Heavy Belt of Rage' },
  { label: 'Demonhide Belt of the Fox', value: 'Demonhide Belt of the Fox' },
  { label: 'Hard Leather Belt of Fury', value: 'Hard Leather Belt of Fury' },
  { label: 'Demonhide Belt of Titans', value: 'Demonhide Belt of Titans' },
  { label: 'Linen Sash of Protection', value: 'Linen Sash of Protection' },
  { label: 'Linen Sash of Reflection', value: 'Linen Sash of Reflection' },
  { label: 'War Belt of Protection', value: 'War Belt of Protection' },
  { label: 'Heavy Belt of Vitriol', value: 'Heavy Belt of Vitriol' },
  { label: 'Sash of Enlightenment', value: 'Sash of Enlightenment' },
  { label: 'Linen Sash of Titans', value: 'Linen Sash of Titans' },
  { label: 'Plated Belt of Skill', value: 'Plated Belt of Skill' },
  { label: 'Silk Sash of the Fox', value: 'Silk Sash of the Fox' },
  { label: 'Linen Sash of Anger', value: 'Linen Sash of Anger' },
  { label: 'Linen Sash of Power', value: 'Linen Sash of Power' },
  { label: 'War Belt of the Fox', value: 'War Belt of the Fox' },
  { label: 'Heavy Belt of Rage', value: 'Heavy Belt of Rage' },
  { label: 'Sash of the Twins', value: 'Sash of the Twins' },
  { label: 'War Belt of Anger', value: 'War Belt of Anger' },
  { label: 'Sash of the Fox', value: 'Sash of the Fox' },
  { label: 'Sash of Vitriol', value: 'Sash of Vitriol' },
  { label: 'Sash of Fury', value: 'Sash of Fury' },
  { label: 'Pandemonium Bender Demonhide Belt of Anger +1', value: 'Pandemonium Bender Demonhide Belt of Anger +1' },
  { label: 'Victory Bite Plated Belt of Enlightenment +1', value: 'Victory Bite Plated Belt of Enlightenment +1' },
  { label: 'Foe Moon Hard Leather Belt of Detection +1', value: 'Foe Moon Hard Leather Belt of Detection +1' },
  { label: 'Bramble Root Studded Leather Belt of Rage', value: 'Bramble Root Studded Leather Belt of Rage' },
  { label: 'Skull Bender Demonhide Belt of Power +1', value: 'Skull Bender Demonhide Belt of Power +1' },
  { label: 'Hypnotic Roar Linen Sash of Reflection', value: 'Hypnotic Roar Linen Sash of Reflection' },
  { label: 'Golem Sun Linen Sash of Enlightenment', value: 'Golem Sun Linen Sash of Enlightenment' },
  { label: 'Shimmering Peak Silk Sash of Anger +1', value: 'Shimmering Peak Silk Sash of Anger +1' },
  { label: 'Havoc Whisper War Belt of Perfection', value: 'Havoc Whisper War Belt of Perfection' },
  { label: 'Apocalypse Glow Heavy Belt of Skill', value: 'Apocalypse Glow Heavy Belt of Skill' },
  { label: 'Golem Sun Brightsilk Sash of Anger', value: 'Golem Sun Brightsilk Sash of Anger' },
  { label: 'Havoc Roar Brightsilk Sash of Fury', value: 'Havoc Roar Brightsilk Sash of Fury' },
  { label: 'Studded Leather Belt of Reflection', value: 'Studded Leather Belt of Reflection' },
  { label: 'Carrion Roar Heavy Belt of Titans', value: 'Carrion Roar Heavy Belt of Titans' },
  { label: 'Demonhide Belt of Enlightenment', value: 'Demonhide Belt of Enlightenment' },
  { label: 'Pain Root War Belt of Vitriol', value: 'Pain Root War Belt of Vitriol' },
  { label: 'Dusk Sun Linen Sash of Anger', value: 'Dusk Sun Linen Sash of Anger' },
  { label: 'Hard Leather Belt of the Fox', value: 'Hard Leather Belt of the Fox' },
  { label: 'Foe Moon Sash of Vitriol +1', value: 'Foe Moon Sash of Vitriol +1' },
  { label: 'Linen Sash of Enlightenment', value: 'Linen Sash of Enlightenment' },
  { label: 'Plated Belt of Perfection', value: 'Plated Belt of Perfection' },
  { label: 'Heavy Belt of Reflection', value: 'Heavy Belt of Reflection' },
  { label: 'Silk Sash of Detection', value: 'Silk Sash of Detection' },
  { label: 'Heavy Belt of Giants', value: 'Heavy Belt of Giants' },
  { label: 'Silk Sash of Giants', value: 'Silk Sash of Giants' },
  { label: 'Linen Sash of Rage', value: 'Linen Sash of Rage' },
  { label: 'Sash of Reflection', value: 'Sash of Reflection' },
  { label: 'Sash of Skill', value: 'Sash of Skill' },
  { label: 'Maelstrom Whisper Studded Leather Belt of Perfection', value: 'Maelstrom Whisper Studded Leather Belt of Perfection' },
  { label: 'Cataclysm Bender Hard Leather Belt of Reflection +1', value: 'Cataclysm Bender Hard Leather Belt of Reflection +1' },
  { label: 'Pandemonium Peak Hard Leather Belt of Reflection +1', value: 'Pandemonium Peak Hard Leather Belt of Reflection +1' },
  { label: 'Apocalypse Glow Studded Leather Belt of Protection', value: 'Apocalypse Glow Studded Leather Belt of Protection' },
  { label: 'Cataclysm Grasp Hard Leather Belt of Brilliance +1', value: 'Cataclysm Grasp Hard Leather Belt of Brilliance +1' },
  { label: 'Corruption Shout Hard Leather Belt of Detection +1', value: 'Corruption Shout Hard Leather Belt of Detection +1' },
  { label: 'Blight Bite Hard Leather Belt of Enlightenment +1', value: 'Blight Bite Hard Leather Belt of Enlightenment +1' },
  { label: 'Bramble Sun Studded Leather Belt of Enlightenment', value: 'Bramble Sun Studded Leather Belt of Enlightenment' },
  { label: 'Corruption Bender Hard Leather Belt of the Fox +1', value: 'Corruption Bender Hard Leather Belt of the Fox +1' },
  { label: 'Corruption Bender Plated Belt of Enlightenment +1', value: 'Corruption Bender Plated Belt of Enlightenment +1' },
  { label: 'Dragon Whisper Studded Leather Belt of Perfection', value: 'Dragon Whisper Studded Leather Belt of Perfection' },
  { label: 'Grim Bender Hard Leather Belt of Enlightenment +1', value: 'Grim Bender Hard Leather Belt of Enlightenment +1' },
  { label: 'Honour Peak Hard Leather Belt of Enlightenment +1', value: 'Honour Peak Hard Leather Belt of Enlightenment +1' },
  { label: 'Maelstrom Roar Studded Leather Belt of Reflection', value: 'Maelstrom Roar Studded Leather Belt of Reflection' },
  { label: 'Pandemonium Shout Demonhide Belt of Brilliance +1', value: 'Pandemonium Shout Demonhide Belt of Brilliance +1' },
  { label: 'Armageddon Shout Demonhide Belt of Protection +1', value: 'Armageddon Shout Demonhide Belt of Protection +1' },
  { label: 'Behemoth Glow Studded Leather Belt of Brilliance', value: 'Behemoth Glow Studded Leather Belt of Brilliance' },
  { label: 'Behemoth Tear Studded Leather Belt of Protection', value: 'Behemoth Tear Studded Leather Belt of Protection' },
  { label: 'Behemoth Whisper Studded Leather Belt of the Fox', value: 'Behemoth Whisper Studded Leather Belt of the Fox' },
  { label: 'Demon Peak Hard Leather Belt of Enlightenment +1', value: 'Demon Peak Hard Leather Belt of Enlightenment +1' },
  { label: 'Dragon Sun Studded Leather Belt of Enlightenment', value: 'Dragon Sun Studded Leather Belt of Enlightenment' },
  { label: 'Gloom Peak Hard Leather Belt of Enlightenment +1', value: 'Gloom Peak Hard Leather Belt of Enlightenment +1' },
  { label: 'Havoc Roar Studded Leather Belt of Enlightenment', value: 'Havoc Roar Studded Leather Belt of Enlightenment' },
  { label: 'Honour Bender Demonhide Belt of Enlightenment +1', value: 'Honour Bender Demonhide Belt of Enlightenment +1' },
  { label: 'Maelstrom Sun Studded Leather Belt of Reflection', value: 'Maelstrom Sun Studded Leather Belt of Reflection' },
  { label: 'Oblivion Shout Hard Leather Belt of the Twins +1', value: 'Oblivion Shout Hard Leather Belt of the Twins +1' },
  { label: 'Pandemonium Moon Demonhide Belt of Protection +1', value: 'Pandemonium Moon Demonhide Belt of Protection +1' },
  { label: 'Apocalypse Root Studded Leather Belt of Vitriol', value: 'Apocalypse Root Studded Leather Belt of Vitriol' },
  { label: 'Armageddon Bender Hard Leather Belt of Power +1', value: 'Armageddon Bender Hard Leather Belt of Power +1' },
  { label: 'Bramble Roar Studded Leather Belt of Reflection', value: 'Bramble Roar Studded Leather Belt of Reflection' },
  { label: 'Brimstone Grasp Hard Leather Belt of Vitriol +1', value: 'Brimstone Grasp Hard Leather Belt of Vitriol +1' },
  { label: 'Carrion Root Studded Leather Belt of Brilliance', value: 'Carrion Root Studded Leather Belt of Brilliance' },
  { label: 'Corruption Bite Demonhide Belt of Perfection +1', value: 'Corruption Bite Demonhide Belt of Perfection +1' },
  { label: 'Corruption Bite Hard Leather Belt of the Fox +1', value: 'Corruption Bite Hard Leather Belt of the Fox +1' },
  { label: 'Honour Shout Hard Leather Belt of Protection +1', value: 'Honour Shout Hard Leather Belt of Protection +1' },
  { label: 'Hypnotic Glow Studded Leather Belt of the Twins', value: 'Hypnotic Glow Studded Leather Belt of the Twins' },
  { label: 'Kraken Grasp Hard Leather Belt of Protection +1', value: 'Kraken Grasp Hard Leather Belt of Protection +1' },
  { label: "Light's Glow Studded Leather Belt of Brilliance", value: "Light's Glow Studded Leather Belt of Brilliance" },
  { label: "Light's Roar Studded Leather Belt of Reflection", value: "Light's Roar Studded Leather Belt of Reflection" },
  { label: 'Pandemonium Grasp Hard Leather Belt of Skill +1', value: 'Pandemonium Grasp Hard Leather Belt of Skill +1' },
  { label: 'Pandemonium Shout Hard Leather Belt of Skill +1', value: 'Pandemonium Shout Hard Leather Belt of Skill +1' },
  { label: 'Blight Bite Hard Leather Belt of Perfection +1', value: 'Blight Bite Hard Leather Belt of Perfection +1' },
  { label: 'Blight Bite Hard Leather Belt of Reflection +1', value: 'Blight Bite Hard Leather Belt of Reflection +1' },
  { label: 'Cataclysm Shout Demonhide Belt of the Twins +1', value: 'Cataclysm Shout Demonhide Belt of the Twins +1' },
  { label: 'Foe Bite Hard Leather Belt of Enlightenment +1', value: 'Foe Bite Hard Leather Belt of Enlightenment +1' },
  { label: 'Honour Bite Hard Leather Belt of Reflection +1', value: 'Honour Bite Hard Leather Belt of Reflection +1' },
  { label: 'Kraken Grasp Hard Leather Belt of the Twins +1', value: 'Kraken Grasp Hard Leather Belt of the Twins +1' },
  { label: 'Apocalypse Glow Brightsilk Sash of Brilliance', value: 'Apocalypse Glow Brightsilk Sash of Brilliance' },
  { label: 'Armageddon Grasp Hard Leather Belt of Rage +1', value: 'Armageddon Grasp Hard Leather Belt of Rage +1' },
  { label: 'Armageddon Shout Plated Belt of Protection +1', value: 'Armageddon Shout Plated Belt of Protection +1' },
  { label: 'Blight Bender Plated Belt of Enlightenment +1', value: 'Blight Bender Plated Belt of Enlightenment +1' },
  { label: 'Brimstone Moon Hard Leather Belt of Giants +1', value: 'Brimstone Moon Hard Leather Belt of Giants +1' },
  { label: 'Cataclysm Bender Demonhide Belt of the Fox +1', value: 'Cataclysm Bender Demonhide Belt of the Fox +1' },
  { label: 'Corruption Bite Hard Leather Belt of Power +1', value: 'Corruption Bite Hard Leather Belt of Power +1' },
  { label: 'Corruption Grasp Plated Belt of Brilliance +1', value: 'Corruption Grasp Plated Belt of Brilliance +1' },
  { label: 'Corruption Peak Hard Leather Belt of Anger +1', value: 'Corruption Peak Hard Leather Belt of Anger +1' },
  { label: 'Death Glow Studded Leather Belt of Brilliance', value: 'Death Glow Studded Leather Belt of Brilliance' },
  { label: 'Death Tear Studded Leather Belt of Protection', value: 'Death Tear Studded Leather Belt of Protection' },
  { label: 'Demon Grasp Hard Leather Belt of the Twins +1', value: 'Demon Grasp Hard Leather Belt of the Twins +1' },
  { label: 'Dread Moon Hard Leather Belt of Brilliance +1', value: 'Dread Moon Hard Leather Belt of Brilliance +1' },
  { label: 'Eagle Moon Hard Leather Belt of Brilliance +1', value: 'Eagle Moon Hard Leather Belt of Brilliance +1' },
  { label: 'Gloom Bite Hard Leather Belt of Perfection +1', value: 'Gloom Bite Hard Leather Belt of Perfection +1' },
  { label: 'Gloom Moon Hard Leather Belt of Protection +1', value: 'Gloom Moon Hard Leather Belt of Protection +1' },
  { label: 'Gloom Peak Hard Leather Belt of Perfection +1', value: 'Gloom Peak Hard Leather Belt of Perfection +1' },
  { label: 'Grim Grasp Hard Leather Belt of Protection +1', value: 'Grim Grasp Hard Leather Belt of Protection +1' },
  { label: 'Pandemonium Bender Demonhide Belt of Power +1', value: 'Pandemonium Bender Demonhide Belt of Power +1' },
  { label: 'Pandemonium Bender Silk Sash of Reflection +1', value: 'Pandemonium Bender Silk Sash of Reflection +1' },
  { label: 'Pandemonium Peak Demonhide Belt of the Fox +1', value: 'Pandemonium Peak Demonhide Belt of the Fox +1' },
  { label: 'Apocalypse Sun Brightsilk Sash of Reflection', value: 'Apocalypse Sun Brightsilk Sash of Reflection' },
  { label: 'Armageddon Moon Hard Leather Belt of Rage +1', value: 'Armageddon Moon Hard Leather Belt of Rage +1' },
  { label: 'Bramble Glow Studded Leather Belt of Vitriol', value: 'Bramble Glow Studded Leather Belt of Vitriol' },
  { label: 'Bramble Tear Studded Leather Belt of Vitriol', value: 'Bramble Tear Studded Leather Belt of Vitriol' },
  { label: 'Cataclysm Moon Hard Leather Belt of Skill +1', value: 'Cataclysm Moon Hard Leather Belt of Skill +1' },
  { label: 'Corruption Bender Silk Sash of Perfection +1', value: 'Corruption Bender Silk Sash of Perfection +1' },
  { label: 'Corruption Bite Plated Belt of Reflection +1', value: 'Corruption Bite Plated Belt of Reflection +1' },
  { label: 'Corruption Peak Demonhide Belt of the Fox +1', value: 'Corruption Peak Demonhide Belt of the Fox +1' },
  { label: 'Eagle Moon Hard Leather Belt of the Twins +1', value: 'Eagle Moon Hard Leather Belt of the Twins +1' },
  { label: 'Fate Roar Studded Leather Belt of Perfection', value: 'Fate Roar Studded Leather Belt of Perfection' },
  { label: 'Gloom Bender Demonhide Belt of Reflection +1', value: 'Gloom Bender Demonhide Belt of Reflection +1' },
  { label: 'Grim Bite Hard Leather Belt of Reflection +1', value: 'Grim Bite Hard Leather Belt of Reflection +1' },
  { label: "Light's Tear Studded Leather Belt of Vitriol", value: "Light's Tear Studded Leather Belt of Vitriol" },
  { label: 'Maelstrom Tear Brightsilk Sash of Protection', value: 'Maelstrom Tear Brightsilk Sash of Protection' },
  { label: 'Oblivion Bender Plated Belt of Reflection +1', value: 'Oblivion Bender Plated Belt of Reflection +1' },
  { label: 'Pain Tear Studded Leather Belt of Brilliance', value: 'Pain Tear Studded Leather Belt of Brilliance' },
  { label: 'Pain Whisper Studded Leather Belt of the Fox', value: 'Pain Whisper Studded Leather Belt of the Fox' },
  { label: 'Pandemonium Grasp Silk Sash of Brilliance +1', value: 'Pandemonium Grasp Silk Sash of Brilliance +1' },
  { label: 'Armageddon Shout Silk Sash of Brilliance +1', value: 'Armageddon Shout Silk Sash of Brilliance +1' },
  { label: 'Behemoth Glow Brightsilk Sash of Protection', value: 'Behemoth Glow Brightsilk Sash of Protection' },
  { label: 'Blight Bite Demonhide Belt of Reflection +1', value: 'Blight Bite Demonhide Belt of Reflection +1' },
  { label: 'Blight Grasp Demonhide Belt of the Twins +1', value: 'Blight Grasp Demonhide Belt of the Twins +1' },
  { label: 'Bramble Glow Studded Leather Belt of Giants', value: 'Bramble Glow Studded Leather Belt of Giants' },
  { label: 'Brimstone Bender Demonhide Belt of Power +1', value: 'Brimstone Bender Demonhide Belt of Power +1' },
  { label: 'Brimstone Moon Plated Belt of Brilliance +1', value: 'Brimstone Moon Plated Belt of Brilliance +1' },
  { label: 'Carrion Sun Studded Leather Belt of the Fox', value: 'Carrion Sun Studded Leather Belt of the Fox' },
  { label: 'Cataclysm Grasp Plated Belt of Detection +1', value: 'Cataclysm Grasp Plated Belt of Detection +1' },
  { label: 'Corpse Roar Studded Leather Belt of the Fox', value: 'Corpse Roar Studded Leather Belt of the Fox' },
  { label: 'Dusk Glow Studded Leather Belt of the Twins', value: 'Dusk Glow Studded Leather Belt of the Twins' },
  { label: 'Dusk Sun Studded Leather Belt of Reflection', value: 'Dusk Sun Studded Leather Belt of Reflection' },
  { label: 'Eagle Shout Demonhide Belt of Protection +1', value: 'Eagle Shout Demonhide Belt of Protection +1' },
  { label: 'Gloom Grasp Demonhide Belt of Protection +1', value: 'Gloom Grasp Demonhide Belt of Protection +1' },
  { label: 'Honour Bender Silk Sash of Enlightenment +1', value: 'Honour Bender Silk Sash of Enlightenment +1' },
  { label: 'Honour Moon Demonhide Belt of Brilliance +1', value: 'Honour Moon Demonhide Belt of Brilliance +1' },
  { label: 'Hypnotic Root Studded Leather Belt of Skill', value: 'Hypnotic Root Studded Leather Belt of Skill' },
  { label: "Light's Sun Studded Leather Belt of the Fox", value: "Light's Sun Studded Leather Belt of the Fox" },
  { label: "Light's Whisper Linen Sash of Enlightenment", value: "Light's Whisper Linen Sash of Enlightenment" },
  { label: 'Armageddon Bite Silk Sash of Perfection +1', value: 'Armageddon Bite Silk Sash of Perfection +1' },
  { label: 'Behemoth Glow Brightsilk Sash of the Twins', value: 'Behemoth Glow Brightsilk Sash of the Twins' },
  { label: 'Blight Bite Hard Leather Belt of Titans +1', value: 'Blight Bite Hard Leather Belt of Titans +1' },
  { label: 'Bramble Glow Brightsilk Sash of Protection', value: 'Bramble Glow Brightsilk Sash of Protection' },
  { label: 'Bramble Roar Brightsilk Sash of Reflection', value: 'Bramble Roar Brightsilk Sash of Reflection' },
  { label: 'Bramble Roar Studded Leather Belt of Power', value: 'Bramble Roar Studded Leather Belt of Power' },
  { label: 'Carrion Roar Studded Leather Belt of Anger', value: 'Carrion Roar Studded Leather Belt of Anger' },
  { label: 'Corruption Grasp Demonhide Belt of Rage +1', value: 'Corruption Grasp Demonhide Belt of Rage +1' },
  { label: 'Corruption Shout Silk Sash of the Twins +1', value: 'Corruption Shout Silk Sash of the Twins +1' },
  { label: 'Demon Bender Silk Sash of Enlightenment +1', value: 'Demon Bender Silk Sash of Enlightenment +1' },
  { label: 'Demon Bite Demonhide Belt of Perfection +1', value: 'Demon Bite Demonhide Belt of Perfection +1' },
  { label: 'Demon Peak Plated Belt of Enlightenment +1', value: 'Demon Peak Plated Belt of Enlightenment +1' },
  { label: 'Dragon Root Studded Leather Belt of Giants', value: 'Dragon Root Studded Leather Belt of Giants' },
  { label: 'Dread Peak Demonhide Belt of Perfection +1', value: 'Dread Peak Demonhide Belt of Perfection +1' },
  { label: 'Dread Peak Plated Belt of Enlightenment +1', value: 'Dread Peak Plated Belt of Enlightenment +1' },
  { label: 'Eagle Bender Hard Leather Belt of Anger +1', value: 'Eagle Bender Hard Leather Belt of Anger +1' },
  { label: 'Eagle Peak Demonhide Belt of Reflection +1', value: 'Eagle Peak Demonhide Belt of Reflection +1' },
  { label: 'Eagle Shout Demonhide Belt of the Twins +1', value: 'Eagle Shout Demonhide Belt of the Twins +1' },
  { label: 'Fate Whisper Studded Leather Belt of Power', value: 'Fate Whisper Studded Leather Belt of Power' },
  { label: 'Grim Grasp Demonhide Belt of Protection +1', value: 'Grim Grasp Demonhide Belt of Protection +1' },
  { label: 'Honour Moon Demonhide Belt of Detection +1', value: 'Honour Moon Demonhide Belt of Detection +1' },
  { label: 'Hypnotic Glow Brightsilk Sash of the Twins', value: 'Hypnotic Glow Brightsilk Sash of the Twins' },
  { label: "Light's Roar Studded Leather Belt of Anger", value: "Light's Roar Studded Leather Belt of Anger" },
  { label: "Light's Roar Studded Leather Belt of Power", value: "Light's Roar Studded Leather Belt of Power" },
  { label: 'Mind Shout Hard Leather Belt of Vitriol +1', value: 'Mind Shout Hard Leather Belt of Vitriol +1' },
  { label: 'Oblivion Bender Demonhide Belt of Power +1', value: 'Oblivion Bender Demonhide Belt of Power +1' },
  { label: 'Oblivion Bite Plated Belt of Perfection +1', value: 'Oblivion Bite Plated Belt of Perfection +1' },
  { label: 'Oblivion Shout Plated Belt of Detection +1', value: 'Oblivion Shout Plated Belt of Detection +1' },
  { label: 'Pain Whisper Studded Leather Belt of Power', value: 'Pain Whisper Studded Leather Belt of Power' },
  { label: 'Pandemonium Moon Plated Belt of Vitriol +1', value: 'Pandemonium Moon Plated Belt of Vitriol +1' },
  { label: 'Pandemonium Peak Plated Belt of the Fox +1', value: 'Pandemonium Peak Plated Belt of the Fox +1' },
  { label: 'Armageddon Bite Plated Belt of the Fox +1', value: 'Armageddon Bite Plated Belt of the Fox +1' },
  { label: 'Behemoth Whisper Heavy Belt of Reflection', value: 'Behemoth Whisper Heavy Belt of Reflection' },
  { label: 'Blight Peak Hard Leather Belt of Anger +1', value: 'Blight Peak Hard Leather Belt of Anger +1' },
  { label: 'Carrion Roar Studded Leather Belt of Fury', value: 'Carrion Roar Studded Leather Belt of Fury' },
  { label: 'Carrion Tear Studded Leather Belt of Rage', value: 'Carrion Tear Studded Leather Belt of Rage' },
  { label: 'Cataclysm Bite Demonhide Belt of Anger +1', value: 'Cataclysm Bite Demonhide Belt of Anger +1' },
  { label: 'Cataclysm Bite Silk Sash of Perfection +1', value: 'Cataclysm Bite Silk Sash of Perfection +1' },
  { label: 'Cataclysm Moon Silk Sash of Protection +1', value: 'Cataclysm Moon Silk Sash of Protection +1' },
  { label: 'Cataclysm Shout Silk Sash of Detection +1', value: 'Cataclysm Shout Silk Sash of Detection +1' },
  { label: 'Corpse Glow Brightsilk Sash of Protection', value: 'Corpse Glow Brightsilk Sash of Protection' },
  { label: 'Corruption Moon Plated Belt of Vitriol +1', value: 'Corruption Moon Plated Belt of Vitriol +1' },
  { label: 'Death Glow Studded Leather Belt of Giants', value: 'Death Glow Studded Leather Belt of Giants' },
  { label: 'Death Roar Studded Leather Belt of Titans', value: 'Death Roar Studded Leather Belt of Titans' },
  { label: 'Demon Grasp Hard Leather Belt of Skill +1', value: 'Demon Grasp Hard Leather Belt of Skill +1' },
  { label: 'Dragon Glow Studded Leather Belt of Skill', value: 'Dragon Glow Studded Leather Belt of Skill' },
  { label: 'Dragon Roar Brightsilk Sash of Reflection', value: 'Dragon Roar Brightsilk Sash of Reflection' },
  { label: 'Dread Bender Demonhide Belt of the Fox +1', value: 'Dread Bender Demonhide Belt of the Fox +1' },
  { label: 'Eagle Bender Plated Belt of Perfection +1', value: 'Eagle Bender Plated Belt of Perfection +1' },
  { label: 'Gloom Bender Plated Belt of Reflection +1', value: 'Gloom Bender Plated Belt of Reflection +1' },
  { label: 'Golem Root Studded Leather Belt of Giants', value: 'Golem Root Studded Leather Belt of Giants' },
  { label: 'Havoc Root Studded Leather Belt of Giants', value: 'Havoc Root Studded Leather Belt of Giants' },
  { label: 'Honour Bite Hard Leather Belt of Anger +1', value: 'Honour Bite Hard Leather Belt of Anger +1' },
  { label: 'Honour Peak Silk Sash of Enlightenment +1', value: 'Honour Peak Silk Sash of Enlightenment +1' },
  { label: 'Kraken Grasp Plated Belt of Protection +1', value: 'Kraken Grasp Plated Belt of Protection +1' },
  { label: "Light's Root Studded Leather Belt of Rage", value: "Light's Root Studded Leather Belt of Rage" },
  { label: 'Mind Bite Plated Belt of Enlightenment +1', value: 'Mind Bite Plated Belt of Enlightenment +1' },
  { label: 'Mind Peak Plated Belt of Enlightenment +1', value: 'Mind Peak Plated Belt of Enlightenment +1' },
  { label: 'Morbid Root Brightsilk Sash of Protection', value: 'Morbid Root Brightsilk Sash of Protection' },
  { label: 'Plague Roar Brightsilk Sash of Reflection', value: 'Plague Roar Brightsilk Sash of Reflection' },
  { label: 'Plague Roar Studded Leather Belt of Anger', value: 'Plague Roar Studded Leather Belt of Anger' },
  { label: 'Plague Tear Brightsilk Sash of Protection', value: 'Plague Tear Brightsilk Sash of Protection' },
  { label: 'Plague Tear Studded Leather Belt of Skill', value: 'Plague Tear Studded Leather Belt of Skill' },
  { label: 'Armageddon Bender Plated Belt of Fury +1', value: 'Armageddon Bender Plated Belt of Fury +1' },
  { label: 'Armageddon Grasp Silk Sash of Vitriol +1', value: 'Armageddon Grasp Silk Sash of Vitriol +1' },
  { label: 'Behemoth Root Brightsilk Sash of Vitriol', value: 'Behemoth Root Brightsilk Sash of Vitriol' },
  { label: 'Brimstone Bender Plated Belt of Anger +1', value: 'Brimstone Bender Plated Belt of Anger +1' },
  { label: 'Brimstone Grasp Plated Belt of Giants +1', value: 'Brimstone Grasp Plated Belt of Giants +1' },
  { label: 'Carrion Sun Studded Leather Belt of Fury', value: 'Carrion Sun Studded Leather Belt of Fury' },
  { label: 'Corruption Bite Plated Belt of Titans +1', value: 'Corruption Bite Plated Belt of Titans +1' },
  { label: 'Death Tear Studded Leather Belt of Skill', value: 'Death Tear Studded Leather Belt of Skill' },
  { label: 'Dragon Sun Brightsilk Sash of Perfection', value: 'Dragon Sun Brightsilk Sash of Perfection' },
  { label: 'Dread Peak Silk Sash of Enlightenment +1', value: 'Dread Peak Silk Sash of Enlightenment +1' },
  { label: 'Dread Shout Hard Leather Belt of Rage +1', value: 'Dread Shout Hard Leather Belt of Rage +1' },
  { label: 'Eagle Grasp Plated Belt of Protection +1', value: 'Eagle Grasp Plated Belt of Protection +1' },
  { label: 'Fate Tear Studded Leather Belt of Giants', value: 'Fate Tear Studded Leather Belt of Giants' },
  { label: 'Foe Bite Demonhide Belt of Reflection +1', value: 'Foe Bite Demonhide Belt of Reflection +1' },
  { label: 'Foe Grasp Demonhide Belt of Detection +1', value: 'Foe Grasp Demonhide Belt of Detection +1' },
  { label: 'Gloom Peak Silk Sash of Enlightenment +1', value: 'Gloom Peak Silk Sash of Enlightenment +1' },
  { label: 'Golem Roar Studded Leather Belt of Anger', value: 'Golem Roar Studded Leather Belt of Anger' },
  { label: 'Golem Roar Studded Leather Belt of Power', value: 'Golem Roar Studded Leather Belt of Power' },
  { label: 'Grim Bender Plated Belt of Perfection +1', value: 'Grim Bender Plated Belt of Perfection +1' },
  { label: 'Grim Bite Hard Leather Belt of Titans +1', value: 'Grim Bite Hard Leather Belt of Titans +1' },
  { label: 'Havoc Roar Brightsilk Sash of Reflection', value: 'Havoc Roar Brightsilk Sash of Reflection' },
  { label: 'Havoc Root Studded Leather Belt of Skill', value: 'Havoc Root Studded Leather Belt of Skill' },
  { label: 'Havoc Tear Brightsilk Sash of Brilliance', value: 'Havoc Tear Brightsilk Sash of Brilliance' },
  { label: 'Honour Bite Hard Leather Belt of Fury +1', value: 'Honour Bite Hard Leather Belt of Fury +1' },
  { label: 'Honour Grasp Plated Belt of the Twins +1', value: 'Honour Grasp Plated Belt of the Twins +1' },
  { label: 'Kraken Moon Plated Belt of Protection +1', value: 'Kraken Moon Plated Belt of Protection +1' },
  { label: 'Kraken Peak Demonhide Belt of the Fox +1', value: 'Kraken Peak Demonhide Belt of the Fox +1' },
  { label: 'Kraken Peak Plated Belt of Perfection +1', value: 'Kraken Peak Plated Belt of Perfection +1' },
  { label: 'Kraken Shout Demonhide Belt of Giants +1', value: 'Kraken Shout Demonhide Belt of Giants +1' },
  { label: "Light's Whisper Heavy Belt of Reflection", value: "Light's Whisper Heavy Belt of Reflection" },
  { label: "Light's Whisper Linen Sash of Reflection", value: "Light's Whisper Linen Sash of Reflection" },
  { label: 'Maelstrom Whisper War Belt of Perfection', value: 'Maelstrom Whisper War Belt of Perfection' },
  { label: 'Mind Peak Hard Leather Belt of Titans +1', value: 'Mind Peak Hard Leather Belt of Titans +1' },
  { label: 'Morbid Root Studded Leather Belt of Rage', value: 'Morbid Root Studded Leather Belt of Rage' },
  { label: 'Morbid Tear Studded Leather Belt of Rage', value: 'Morbid Tear Studded Leather Belt of Rage' },
  { label: 'Oblivion Peak Silk Sash of Perfection +1', value: 'Oblivion Peak Silk Sash of Perfection +1' },
  { label: 'Pandemonium Bite Silk Sash of the Fox +1', value: 'Pandemonium Bite Silk Sash of the Fox +1' },
  { label: 'Pandemonium Peak Plated Belt of Power +1', value: 'Pandemonium Peak Plated Belt of Power +1' },
  { label: 'Apocalypse Glow Heavy Belt of the Twins', value: 'Apocalypse Glow Heavy Belt of the Twins' },
  { label: 'Apocalypse Sun Linen Sash of Perfection', value: 'Apocalypse Sun Linen Sash of Perfection' },
  { label: 'Apocalypse Whisper Heavy Belt of Titans', value: 'Apocalypse Whisper Heavy Belt of Titans' },
  { label: 'Armageddon Peak Plated Belt of Anger +1', value: 'Armageddon Peak Plated Belt of Anger +1' },
  { label: 'Armageddon Peak Plated Belt of Power +1', value: 'Armageddon Peak Plated Belt of Power +1' },
  { label: 'Blight Grasp Demonhide Belt of Skill +1', value: 'Blight Grasp Demonhide Belt of Skill +1' },
  { label: 'Carrion Sun Linen Sash of Enlightenment', value: 'Carrion Sun Linen Sash of Enlightenment' },
  { label: 'Death Whisper War Belt of Enlightenment', value: 'Death Whisper War Belt of Enlightenment' },
  { label: 'Demon Peak Plated Belt of Perfection +1', value: 'Demon Peak Plated Belt of Perfection +1' },
  { label: 'Dread Bender Silk Sash of Reflection +1', value: 'Dread Bender Silk Sash of Reflection +1' },
  { label: 'Dusk Tear Brightsilk Sash of Brilliance', value: 'Dusk Tear Brightsilk Sash of Brilliance' },
  { label: 'Eagle Grasp Demonhide Belt of Giants +1', value: 'Eagle Grasp Demonhide Belt of Giants +1' },
  { label: 'Eagle Moon Plated Belt of Brilliance +1', value: 'Eagle Moon Plated Belt of Brilliance +1' },
  { label: 'Gloom Grasp Demonhide Belt of Giants +1', value: 'Gloom Grasp Demonhide Belt of Giants +1' },
  { label: 'Gloom Peak Hard Leather Belt of Fury +1', value: 'Gloom Peak Hard Leather Belt of Fury +1' },
  { label: 'Golem Roar Studded Leather Belt of Fury', value: 'Golem Roar Studded Leather Belt of Fury' },
  { label: 'Havoc Sun Brightsilk Sash of Reflection', value: 'Havoc Sun Brightsilk Sash of Reflection' },
  { label: 'Havoc Sun Studded Leather Belt of Anger', value: 'Havoc Sun Studded Leather Belt of Anger' },
  { label: 'Honour Moon Plated Belt of the Twins +1', value: 'Honour Moon Plated Belt of the Twins +1' },
  { label: 'Hypnotic Glow Brightsilk Sash of Giants', value: 'Hypnotic Glow Brightsilk Sash of Giants' },
  { label: 'Maelstrom Tear Heavy Belt of Protection', value: 'Maelstrom Tear Heavy Belt of Protection' },
  { label: 'Mind Shout Plated Belt of Brilliance +1', value: 'Mind Shout Plated Belt of Brilliance +1' },
  { label: 'Pain Sun Studded Leather Belt of Titans', value: 'Pain Sun Studded Leather Belt of Titans' },
  { label: 'Apocalypse Glow War Belt of Brilliance', value: 'Apocalypse Glow War Belt of Brilliance' },
  { label: 'Apocalypse Root War Belt of Brilliance', value: 'Apocalypse Root War Belt of Brilliance' },
  { label: 'Corpse Roar Brightsilk Sash of the Fox', value: 'Corpse Roar Brightsilk Sash of the Fox' },
  { label: 'Death Sun Studded Leather Belt of Fury', value: 'Death Sun Studded Leather Belt of Fury' },
  { label: 'Death Whisper Brightsilk Sash of Power', value: 'Death Whisper Brightsilk Sash of Power' },
  { label: 'Death Whisper Heavy Belt of Reflection', value: 'Death Whisper Heavy Belt of Reflection' },
  { label: 'Demon Shout Demonhide Belt of Skill +1', value: 'Demon Shout Demonhide Belt of Skill +1' },
  { label: 'Dread Grasp Demonhide Belt of Skill +1', value: 'Dread Grasp Demonhide Belt of Skill +1' },
  { label: 'Eagle Shout Demonhide Belt of Skill +1', value: 'Eagle Shout Demonhide Belt of Skill +1' },
  { label: 'Foe Grasp Hard Leather Belt of Rage +1', value: 'Foe Grasp Hard Leather Belt of Rage +1' },
  { label: 'Ghoul Whisper Linen Sash of Perfection', value: 'Ghoul Whisper Linen Sash of Perfection' },
  { label: 'Gloom Moon Plated Belt of Detection +1', value: 'Gloom Moon Plated Belt of Detection +1' },
  { label: 'Golem Roar Heavy Belt of Enlightenment', value: 'Golem Roar Heavy Belt of Enlightenment' },
  { label: 'Golem Sun Studded Leather Belt of Fury', value: 'Golem Sun Studded Leather Belt of Fury' },
  { label: 'Grim Shout Demonhide Belt of Giants +1', value: 'Grim Shout Demonhide Belt of Giants +1' },
  { label: 'Havoc Roar Heavy Belt of Enlightenment', value: 'Havoc Roar Heavy Belt of Enlightenment' },
  { label: 'Havoc Whisper Linen Sash of Perfection', value: 'Havoc Whisper Linen Sash of Perfection' },
  { label: 'Hypnotic Root Linen Sash of Protection', value: 'Hypnotic Root Linen Sash of Protection' },
  { label: 'Kraken Shout Silk Sash of Detection +1', value: 'Kraken Shout Silk Sash of Detection +1' },
  { label: "Light's Roar War Belt of Enlightenment", value: "Light's Roar War Belt of Enlightenment" },
  { label: 'Maelstrom Glow Brightsilk Sash of Rage', value: 'Maelstrom Glow Brightsilk Sash of Rage' },
  { label: 'Maelstrom Roar Brightsilk Sash of Fury', value: 'Maelstrom Roar Brightsilk Sash of Fury' },
  { label: 'Maelstrom Sun Linen Sash of Reflection', value: 'Maelstrom Sun Linen Sash of Reflection' },
  { label: 'Mind Grasp Plated Belt of the Twins +1', value: 'Mind Grasp Plated Belt of the Twins +1' },
  { label: 'Mind Peak Hard Leather Belt of Fury +1', value: 'Mind Peak Hard Leather Belt of Fury +1' },
  { label: 'Mind Shout Demonhide Belt of Giants +1', value: 'Mind Shout Demonhide Belt of Giants +1' },
  { label: 'Oblivion Peak Plated Belt of Titans +1', value: 'Oblivion Peak Plated Belt of Titans +1' },
  { label: 'Oblivion Peak Sash of Enlightenment +1', value: 'Oblivion Peak Sash of Enlightenment +1' },
  { label: 'Pain Tear Brightsilk Sash of the Twins', value: 'Pain Tear Brightsilk Sash of the Twins' },
  { label: 'Pandemonium Peak Sash of Reflection +1', value: 'Pandemonium Peak Sash of Reflection +1' },
  { label: 'Pandemonium Peak Silk Sash of Power +1', value: 'Pandemonium Peak Silk Sash of Power +1' },
  { label: 'Armageddon Moon Silk Sash of Skill +1', value: 'Armageddon Moon Silk Sash of Skill +1' },
  { label: 'Behemoth Root Linen Sash of Detection', value: 'Behemoth Root Linen Sash of Detection' },
  { label: 'Blight Bite Plated Belt of the Fox +1', value: 'Blight Bite Plated Belt of the Fox +1' },
  { label: 'Blight Peak Plated Belt of the Fox +1', value: 'Blight Peak Plated Belt of the Fox +1' },
  { label: 'Bramble Glow Brightsilk Sash of Skill', value: 'Bramble Glow Brightsilk Sash of Skill' },
  { label: 'Bramble Root Brightsilk Sash of Skill', value: 'Bramble Root Brightsilk Sash of Skill' },
  { label: 'Bramble Whisper Linen Sash of the Fox', value: 'Bramble Whisper Linen Sash of the Fox' },
  { label: 'Brimstone Bite Silk Sash of Titans +1', value: 'Brimstone Bite Silk Sash of Titans +1' },
  { label: 'Brimstone Grasp Sash of Protection +1', value: 'Brimstone Grasp Sash of Protection +1' },
  { label: 'Carrion Glow Brightsilk Sash of Skill', value: 'Carrion Glow Brightsilk Sash of Skill' },
  { label: 'Carrion Roar Brightsilk Sash of Power', value: 'Carrion Roar Brightsilk Sash of Power' },
  { label: 'Cataclysm Grasp Silk Sash of Skill +1', value: 'Cataclysm Grasp Silk Sash of Skill +1' },
  { label: 'Corruption Bite Silk Sash of Anger +1', value: 'Corruption Bite Silk Sash of Anger +1' },
  { label: 'Corruption Peak Sash of Perfection +1', value: 'Corruption Peak Sash of Perfection +1' },
  { label: 'Dragon Glow Brightsilk Sash of Giants', value: 'Dragon Glow Brightsilk Sash of Giants' },
  { label: 'Dragon Sun Brightsilk Sash of the Fox', value: 'Dragon Sun Brightsilk Sash of the Fox' },
  { label: 'Dread Moon Silk Sash of Brilliance +1', value: 'Dread Moon Silk Sash of Brilliance +1' },
  { label: 'Dread Shout Plated Belt of Vitriol +1', value: 'Dread Shout Plated Belt of Vitriol +1' },
  { label: 'Eagle Shout Demonhide Belt of Rage +1', value: 'Eagle Shout Demonhide Belt of Rage +1' },
  { label: 'Ghoul Root Brightsilk Sash of Vitriol', value: 'Ghoul Root Brightsilk Sash of Vitriol' },
  { label: 'Gloom Bender Sash of Enlightenment +1', value: 'Gloom Bender Sash of Enlightenment +1' },
  { label: 'Gloom Bite Silk Sash of Reflection +1', value: 'Gloom Bite Silk Sash of Reflection +1' },
  { label: 'Gloom Peak Demonhide Belt of Power +1', value: 'Gloom Peak Demonhide Belt of Power +1' },
  { label: 'Havoc Tear Brightsilk Sash of Vitriol', value: 'Havoc Tear Brightsilk Sash of Vitriol' },
  { label: 'Honour Peak Demonhide Belt of Fury +1', value: 'Honour Peak Demonhide Belt of Fury +1' },
  { label: 'Honour Peak Plated Belt of the Fox +1', value: 'Honour Peak Plated Belt of the Fox +1' },
  { label: 'Hypnotic Whisper Linen Sash of Titans', value: 'Hypnotic Whisper Linen Sash of Titans' },
  { label: "Light's Tear Linen Sash of Brilliance", value: "Light's Tear Linen Sash of Brilliance" },
  { label: 'Maelstrom Whisper Heavy Belt of Anger', value: 'Maelstrom Whisper Heavy Belt of Anger' },
  { label: 'Mind Shout Silk Sash of Protection +1', value: 'Mind Shout Silk Sash of Protection +1' },
  { label: 'Morbid Root Brightsilk Sash of Giants', value: 'Morbid Root Brightsilk Sash of Giants' },
  { label: 'Morbid Whisper War Belt of Perfection', value: 'Morbid Whisper War Belt of Perfection' },
  { label: 'Pain Whisper Brightsilk Sash of Power', value: 'Pain Whisper Brightsilk Sash of Power' },
  { label: 'Behemoth Whisper Heavy Belt of Power', value: 'Behemoth Whisper Heavy Belt of Power' },
  { label: 'Bramble Glow Heavy Belt of the Twins', value: 'Bramble Glow Heavy Belt of the Twins' },
  { label: 'Bramble Root Linen Sash of Detection', value: 'Bramble Root Linen Sash of Detection' },
  { label: 'Carrion Root Heavy Belt of the Twins', value: 'Carrion Root Heavy Belt of the Twins' },
  { label: 'Cataclysm Moon Silk Sash of Skill +1', value: 'Cataclysm Moon Silk Sash of Skill +1' },
  { label: 'Cataclysm Peak Silk Sash of Anger +1', value: 'Cataclysm Peak Silk Sash of Anger +1' },
  { label: 'Death Whisper War Belt of Reflection', value: 'Death Whisper War Belt of Reflection' },
  { label: 'Demon Moon Demonhide Belt of Rage +1', value: 'Demon Moon Demonhide Belt of Rage +1' },
  { label: 'Dragon Glow Brightsilk Sash of Skill', value: 'Dragon Glow Brightsilk Sash of Skill' },
  { label: 'Dragon Tear Brightsilk Sash of Skill', value: 'Dragon Tear Brightsilk Sash of Skill' },
  { label: 'Dragon Tear Heavy Belt of Brilliance', value: 'Dragon Tear Heavy Belt of Brilliance' },
  { label: 'Grim Grasp Plated Belt of Vitriol +1', value: 'Grim Grasp Plated Belt of Vitriol +1' },
  { label: 'Havoc Roar War Belt of Enlightenment', value: 'Havoc Roar War Belt of Enlightenment' },
  { label: 'Hypnotic Roar War Belt of Perfection', value: 'Hypnotic Roar War Belt of Perfection' },
  { label: 'Kraken Bender Silk Sash of Titans +1', value: 'Kraken Bender Silk Sash of Titans +1' },
  { label: "Light's Glow Heavy Belt of Detection", value: "Light's Glow Heavy Belt of Detection" },
  { label: "Light's Sun Heavy Belt of Reflection", value: "Light's Sun Heavy Belt of Reflection" },
  { label: 'Maelstrom Glow Linen Sash of Vitriol', value: 'Maelstrom Glow Linen Sash of Vitriol' },
  { label: 'Maelstrom Root War Belt of Detection', value: 'Maelstrom Root War Belt of Detection' },
  { label: 'Mind Peak Demonhide Belt of Power +1', value: 'Mind Peak Demonhide Belt of Power +1' },
  { label: 'Morbid Root Heavy Belt of Protection', value: 'Morbid Root Heavy Belt of Protection' },
  { label: 'Pain Roar Brightsilk Sash of the Fox', value: 'Pain Roar Brightsilk Sash of the Fox' },
  { label: 'Plague Whisper Heavy Belt of the Fox', value: 'Plague Whisper Heavy Belt of the Fox' },
  { label: 'Plague Whisper Linen Sash of the Fox', value: 'Plague Whisper Linen Sash of the Fox' },
  { label: 'Apocalypse Roar Linen Sash of Anger', value: 'Apocalypse Roar Linen Sash of Anger' },
  { label: 'Apocalypse Root Heavy Belt of Skill', value: 'Apocalypse Root Heavy Belt of Skill' },
  { label: 'Apocalypse Sun Linen Sash of Titans', value: 'Apocalypse Sun Linen Sash of Titans' },
  { label: 'Behemoth Sun War Belt of Perfection', value: 'Behemoth Sun War Belt of Perfection' },
  { label: 'Behemoth Whisper Heavy Belt of Fury', value: 'Behemoth Whisper Heavy Belt of Fury' },
  { label: 'Blight Bender Silk Sash of Anger +1', value: 'Blight Bender Silk Sash of Anger +1' },
  { label: 'Bramble Glow War Belt of Brilliance', value: 'Bramble Glow War Belt of Brilliance' },
  { label: 'Bramble Whisper Heavy Belt of Power', value: 'Bramble Whisper Heavy Belt of Power' },
  { label: 'Brimstone Bender Sash of the Fox +1', value: 'Brimstone Bender Sash of the Fox +1' },
  { label: 'Carrion Root War Belt of Protection', value: 'Carrion Root War Belt of Protection' },
  { label: 'Carrion Whisper Heavy Belt of Anger', value: 'Carrion Whisper Heavy Belt of Anger' },
  { label: 'Death Roar Heavy Belt of Reflection', value: 'Death Roar Heavy Belt of Reflection' },
  { label: 'Demon Moon Plated Belt of Giants +1', value: 'Demon Moon Plated Belt of Giants +1' },
  { label: 'Dragon Tear Linen Sash of the Twins', value: 'Dragon Tear Linen Sash of the Twins' },
  { label: 'Ghoul Glow Linen Sash of Brilliance', value: 'Ghoul Glow Linen Sash of Brilliance' },
  { label: 'Ghoul Glow Linen Sash of Protection', value: 'Ghoul Glow Linen Sash of Protection' },
  { label: 'Ghoul Tear Brightsilk Sash of Skill', value: 'Ghoul Tear Brightsilk Sash of Skill' },
  { label: 'Gloom Bite Sash of Enlightenment +1', value: 'Gloom Bite Sash of Enlightenment +1' },
  { label: 'Golem Roar Brightsilk Sash of Anger', value: 'Golem Roar Brightsilk Sash of Anger' },
  { label: 'Golem Roar Heavy Belt of Reflection', value: 'Golem Roar Heavy Belt of Reflection' },
  { label: 'Golem Root Linen Sash of Protection', value: 'Golem Root Linen Sash of Protection' },
  { label: 'Havoc Roar Heavy Belt of Reflection', value: 'Havoc Roar Heavy Belt of Reflection' },
  { label: 'Hypnotic Roar Heavy Belt of the Fox', value: 'Hypnotic Roar Heavy Belt of the Fox' },
  { label: 'Kraken Bender Silk Sash of Anger +1', value: 'Kraken Bender Silk Sash of Anger +1' },
  { label: "Light's Glow War Belt of Brilliance", value: "Light's Glow War Belt of Brilliance" },
  { label: "Light's Whisper Heavy Belt of Anger", value: "Light's Whisper Heavy Belt of Anger" },
  { label: "Light's Whisper Heavy Belt of Power", value: "Light's Whisper Heavy Belt of Power" },
  { label: 'Mind Grasp Plated Belt of Giants +1', value: 'Mind Grasp Plated Belt of Giants +1' },
  { label: 'Mind Moon Silk Sash of the Twins +1', value: 'Mind Moon Silk Sash of the Twins +1' },
  { label: 'Morbid Root Linen Sash of Detection', value: 'Morbid Root Linen Sash of Detection' },
  { label: 'Morbid Sun Linen Sash of Reflection', value: 'Morbid Sun Linen Sash of Reflection' },
  { label: 'Pain Glow Brightsilk Sash of Giants', value: 'Pain Glow Brightsilk Sash of Giants' },
  { label: 'Pandemonium Peak Sash of the Fox +1', value: 'Pandemonium Peak Sash of the Fox +1' },
  { label: 'Plague Glow Heavy Belt of Detection', value: 'Plague Glow Heavy Belt of Detection' },
  { label: 'Plague Sun Heavy Belt of Reflection', value: 'Plague Sun Heavy Belt of Reflection' },
  { label: 'Apocalypse Tear War Belt of Giants', value: 'Apocalypse Tear War Belt of Giants' },
  { label: 'Blight Grasp Silk Sash of Skill +1', value: 'Blight Grasp Silk Sash of Skill +1' },
  { label: 'Blight Shout Silk Sash of Skill +1', value: 'Blight Shout Silk Sash of Skill +1' },
  { label: 'Bramble Tear War Belt of Detection', value: 'Bramble Tear War Belt of Detection' },
  { label: 'Carrion Glow War Belt of Detection', value: 'Carrion Glow War Belt of Detection' },
  { label: 'Carrion Root War Belt of Detection', value: 'Carrion Root War Belt of Detection' },
  { label: 'Corruption Peak Sash of the Fox +1', value: 'Corruption Peak Sash of the Fox +1' },
  { label: 'Death Glow Heavy Belt of Detection', value: 'Death Glow Heavy Belt of Detection' },
  { label: 'Death Whisper Linen Sash of Titans', value: 'Death Whisper Linen Sash of Titans' },
  { label: 'Demon Bender Sash of Perfection +1', value: 'Demon Bender Sash of Perfection +1' },
  { label: 'Demon Bender Sash of Reflection +1', value: 'Demon Bender Sash of Reflection +1' },
  { label: 'Demon Grasp Silk Sash of Giants +1', value: 'Demon Grasp Silk Sash of Giants +1' },
  { label: 'Dusk Roar Linen Sash of Reflection', value: 'Dusk Roar Linen Sash of Reflection' },
  { label: 'Dusk Root Heavy Belt of Protection', value: 'Dusk Root Heavy Belt of Protection' },
  { label: 'Dusk Tear Heavy Belt of Protection', value: 'Dusk Tear Heavy Belt of Protection' },
  { label: 'Fate Sun War Belt of Enlightenment', value: 'Fate Sun War Belt of Enlightenment' },
  { label: 'Ghoul Root Heavy Belt of Detection', value: 'Ghoul Root Heavy Belt of Detection' },
  { label: 'Gloom Grasp Plated Belt of Rage +1', value: 'Gloom Grasp Plated Belt of Rage +1' },
  { label: 'Grim Peak Sash of Enlightenment +1', value: 'Grim Peak Sash of Enlightenment +1' },
  { label: 'Havoc Sun Heavy Belt of Perfection', value: 'Havoc Sun Heavy Belt of Perfection' },
  { label: 'Havoc Tear Linen Sash of Detection', value: 'Havoc Tear Linen Sash of Detection' },
  { label: 'Hypnotic Whisper War Belt of Anger', value: 'Hypnotic Whisper War Belt of Anger' },
  { label: 'Hypnotic Whisper War Belt of Power', value: 'Hypnotic Whisper War Belt of Power' },
  { label: "Light's Whisper Linen Sash of Fury", value: "Light's Whisper Linen Sash of Fury" },
  { label: 'Mind Bite Sash of Enlightenment +1', value: 'Mind Bite Sash of Enlightenment +1' },
  { label: 'Morbid Whisper Linen Sash of Power', value: 'Morbid Whisper Linen Sash of Power' },
  { label: 'Pain Glow Heavy Belt of Brilliance', value: 'Pain Glow Heavy Belt of Brilliance' },
  { label: 'Pain Root Heavy Belt of Brilliance', value: 'Pain Root Heavy Belt of Brilliance' },
  { label: 'Pain Tear Heavy Belt of Protection', value: 'Pain Tear Heavy Belt of Protection' },
  { label: 'Plague Whisper Heavy Belt of Anger', value: 'Plague Whisper Heavy Belt of Anger' },
  { label: 'Apocalypse Sun War Belt of Titans', value: 'Apocalypse Sun War Belt of Titans' },
  { label: 'Apocalypse Tear War Belt of Skill', value: 'Apocalypse Tear War Belt of Skill' },
  { label: 'Blight Bite Sash of Perfection +1', value: 'Blight Bite Sash of Perfection +1' },
  { label: 'Blight Bite Silk Sash of Anger +1', value: 'Blight Bite Silk Sash of Anger +1' },
  { label: 'Bramble Glow Heavy Belt of Giants', value: 'Bramble Glow Heavy Belt of Giants' },
  { label: 'Carrion Root Linen Sash of Giants', value: 'Carrion Root Linen Sash of Giants' },
  { label: 'Carrion Whisper War Belt of Anger', value: 'Carrion Whisper War Belt of Anger' },
  { label: 'Corpse Tear Heavy Belt of Vitriol', value: 'Corpse Tear Heavy Belt of Vitriol' },
  { label: 'Corpse Tear War Belt of the Twins', value: 'Corpse Tear War Belt of the Twins' },
  { label: 'Corpse Whisper Heavy Belt of Fury', value: 'Corpse Whisper Heavy Belt of Fury' },
  { label: 'Corruption Shout Sash of Skill +1', value: 'Corruption Shout Sash of Skill +1' },
  { label: 'Demon Bender Silk Sash of Fury +1', value: 'Demon Bender Silk Sash of Fury +1' },
  { label: 'Demon Grasp Sash of Protection +1', value: 'Demon Grasp Sash of Protection +1' },
  { label: 'Dragon Roar Heavy Belt of the Fox', value: 'Dragon Roar Heavy Belt of the Fox' },
  { label: 'Dragon Sun War Belt of Perfection', value: 'Dragon Sun War Belt of Perfection' },
  { label: 'Dread Grasp Sash of Brilliance +1', value: 'Dread Grasp Sash of Brilliance +1' },
  { label: 'Dusk Glow Heavy Belt of Detection', value: 'Dusk Glow Heavy Belt of Detection' },
  { label: 'Dusk Glow Heavy Belt of the Twins', value: 'Dusk Glow Heavy Belt of the Twins' },
  { label: 'Dusk Tear Heavy Belt of Detection', value: 'Dusk Tear Heavy Belt of Detection' },
  { label: 'Fate Sun Heavy Belt of Perfection', value: 'Fate Sun Heavy Belt of Perfection' },
  { label: 'Foe Bite Sash of Enlightenment +1', value: 'Foe Bite Sash of Enlightenment +1' },
  { label: 'Foe Shout Silk Sash of Vitriol +1', value: 'Foe Shout Silk Sash of Vitriol +1' },
  { label: 'Ghoul Glow War Belt of Protection', value: 'Ghoul Glow War Belt of Protection' },
  { label: 'Ghoul Whisper Linen Sash of Anger', value: 'Ghoul Whisper Linen Sash of Anger' },
  { label: 'Gloom Moon Plated Belt of Rage +1', value: 'Gloom Moon Plated Belt of Rage +1' },
  { label: 'Gloom Shout Sash of Protection +1', value: 'Gloom Shout Sash of Protection +1' },
  { label: 'Golem Glow War Belt of Protection', value: 'Golem Glow War Belt of Protection' },
  { label: 'Grim Bite Plated Belt of Power +1', value: 'Grim Bite Plated Belt of Power +1' },
  { label: 'Havoc Roar War Belt of Perfection', value: 'Havoc Roar War Belt of Perfection' },
  { label: 'Havoc Whisper Heavy Belt of Anger', value: 'Havoc Whisper Heavy Belt of Anger' },
  { label: 'Havoc Whisper Linen Sash of Anger', value: 'Havoc Whisper Linen Sash of Anger' },
  { label: 'Honour Grasp Sash of the Twins +1', value: 'Honour Grasp Sash of the Twins +1' },
  { label: 'Honour Shout Silk Sash of Rage +1', value: 'Honour Shout Silk Sash of Rage +1' },
  { label: 'Hypnotic Roar Linen Sash of Power', value: 'Hypnotic Roar Linen Sash of Power' },
  { label: 'Kraken Shout Sash of Detection +1', value: 'Kraken Shout Sash of Detection +1' },
  { label: "Light's Whisper War Belt of Anger", value: "Light's Whisper War Belt of Anger" },
  { label: 'Pain Glow Brightsilk Sash of Rage', value: 'Pain Glow Brightsilk Sash of Rage' },
  { label: 'Pandemonium Bite Sash of Anger +1', value: 'Pandemonium Bite Sash of Anger +1' },
  { label: 'Plague Root Heavy Belt of Vitriol', value: 'Plague Root Heavy Belt of Vitriol' },
  { label: 'Plague Sun War Belt of Perfection', value: 'Plague Sun War Belt of Perfection' },
  { label: 'Plague Tear War Belt of the Twins', value: 'Plague Tear War Belt of the Twins' },
  { label: 'Blight Bite Silk Sash of Fury +1', value: 'Blight Bite Silk Sash of Fury +1' },
  { label: 'Blight Moon Sash of Detection +1', value: 'Blight Moon Sash of Detection +1' },
  { label: 'Bramble Glow Linen Sash of Skill', value: 'Bramble Glow Linen Sash of Skill' },
  { label: 'Bramble Roar Heavy Belt of Power', value: 'Bramble Roar Heavy Belt of Power' },
  { label: 'Brightsilk Sash of Enlightenment', value: 'Brightsilk Sash of Enlightenment' },
  { label: 'Carrion Whisper War Belt of Fury', value: 'Carrion Whisper War Belt of Fury' },
  { label: 'Corpse Glow Linen Sash of Giants', value: 'Corpse Glow Linen Sash of Giants' },
  { label: 'Corruption Bite Sash of Anger +1', value: 'Corruption Bite Sash of Anger +1' },
  { label: 'Corruption Moon Sash of Skill +1', value: 'Corruption Moon Sash of Skill +1' },
  { label: 'Demon Bite Silk Sash of Power +1', value: 'Demon Bite Silk Sash of Power +1' },
  { label: 'Demon Peak Sash of Perfection +1', value: 'Demon Peak Sash of Perfection +1' },
  { label: 'Dragon Whisper War Belt of Power', value: 'Dragon Whisper War Belt of Power' },
  { label: 'Dread Grasp Silk Sash of Rage +1', value: 'Dread Grasp Silk Sash of Rage +1' },
  { label: 'Dread Peak Sash of Perfection +1', value: 'Dread Peak Sash of Perfection +1' },
  { label: 'Eagle Shout Sash of the Twins +1', value: 'Eagle Shout Sash of the Twins +1' },
  { label: 'Ghoul Root War Belt of Detection', value: 'Ghoul Root War Belt of Detection' },
  { label: 'Gloom Peak Silk Sash of Power +1', value: 'Gloom Peak Silk Sash of Power +1' },
  { label: 'Golem Roar Linen Sash of the Fox', value: 'Golem Roar Linen Sash of the Fox' },
  { label: 'Golem Root Heavy Belt of Vitriol', value: 'Golem Root Heavy Belt of Vitriol' },
  { label: 'Golem Whisper Heavy Belt of Fury', value: 'Golem Whisper Heavy Belt of Fury' },
  { label: 'Grim Bite Silk Sash of Titans +1', value: 'Grim Bite Silk Sash of Titans +1' },
  { label: 'Kraken Peak Silk Sash of Fury +1', value: 'Kraken Peak Silk Sash of Fury +1' },
  { label: "Light's Roar War Belt of the Fox", value: "Light's Roar War Belt of the Fox" },
  { label: "Light's Tear War Belt of Vitriol", value: "Light's Tear War Belt of Vitriol" },
  { label: 'Maelstrom Root War Belt of Skill', value: 'Maelstrom Root War Belt of Skill' },
  { label: 'Morbid Tear Linen Sash of Giants', value: 'Morbid Tear Linen Sash of Giants' },
  { label: 'Oblivion Moon Sash of Vitriol +1', value: 'Oblivion Moon Sash of Vitriol +1' },
  { label: 'Plague Sun Heavy Belt of the Fox', value: 'Plague Sun Heavy Belt of the Fox' },
  { label: 'Armageddon Bite Sash of Fury +1', value: 'Armageddon Bite Sash of Fury +1' },
  { label: 'Armageddon Peak Sash of Fury +1', value: 'Armageddon Peak Sash of Fury +1' },
  { label: 'Behemoth Roar War Belt of Power', value: 'Behemoth Roar War Belt of Power' },
  { label: 'Carrion Roar Heavy Belt of Fury', value: 'Carrion Roar Heavy Belt of Fury' },
  { label: 'Corpse Root War Belt of Vitriol', value: 'Corpse Root War Belt of Vitriol' },
  { label: 'Death Glow Heavy Belt of Giants', value: 'Death Glow Heavy Belt of Giants' },
  { label: 'Death Whisper War Belt of Anger', value: 'Death Whisper War Belt of Anger' },
  { label: 'Dusk Root War Belt of the Twins', value: 'Dusk Root War Belt of the Twins' },
  { label: 'Fate Roar Heavy Belt of the Fox', value: 'Fate Roar Heavy Belt of the Fox' },
  { label: 'Fate Root War Belt of the Twins', value: 'Fate Root War Belt of the Twins' },
  { label: 'Foe Bite Plated Belt of Fury +1', value: 'Foe Bite Plated Belt of Fury +1' },
  { label: 'Ghoul Glow Heavy Belt of Giants', value: 'Ghoul Glow Heavy Belt of Giants' },
  { label: 'Havoc Roar Linen Sash of Titans', value: 'Havoc Roar Linen Sash of Titans' },
  { label: 'Havoc Root Heavy Belt of Giants', value: 'Havoc Root Heavy Belt of Giants' },
  { label: 'Hypnotic Sun War Belt of Titans', value: 'Hypnotic Sun War Belt of Titans' },
  { label: "Light's Root Heavy Belt of Rage", value: "Light's Root Heavy Belt of Rage" },
  { label: 'Mind Moon Sash of Brilliance +1', value: 'Mind Moon Sash of Brilliance +1' },
  { label: 'Morbid Root War Belt of Vitriol', value: 'Morbid Root War Belt of Vitriol' },
  { label: 'Morbid Whisper War Belt of Fury', value: 'Morbid Whisper War Belt of Fury' },
  { label: 'Blight Moon Sash of Vitriol +1', value: 'Blight Moon Sash of Vitriol +1' },
  { label: 'Death Roar Heavy Belt of Anger', value: 'Death Roar Heavy Belt of Anger' },
  { label: 'Demon Grasp Sash of Vitriol +1', value: 'Demon Grasp Sash of Vitriol +1' },
  { label: 'Demon Shout Sash of Vitriol +1', value: 'Demon Shout Sash of Vitriol +1' },
  { label: 'Dragon Roar Heavy Belt of Fury', value: 'Dragon Roar Heavy Belt of Fury' },
  { label: 'Dusk Root Linen Sash of Giants', value: 'Dusk Root Linen Sash of Giants' },
  { label: 'Ghoul Tear Heavy Belt of Skill', value: 'Ghoul Tear Heavy Belt of Skill' },
  { label: 'Havoc Tear Heavy Belt of Skill', value: 'Havoc Tear Heavy Belt of Skill' },
  { label: 'Morbid Glow Heavy Belt of Rage', value: 'Morbid Glow Heavy Belt of Rage' },
  { label: 'Morbid Sun War Belt of the Fox', value: 'Morbid Sun War Belt of the Fox' },
  { label: 'Oblivion Moon Sash of Skill +1', value: 'Oblivion Moon Sash of Skill +1' },
  { label: 'Plague Glow Heavy Belt of Rage', value: 'Plague Glow Heavy Belt of Rage' },
  { label: 'Plague Root War Belt of Giants', value: 'Plague Root War Belt of Giants' },
  { label: 'Plague Sun Linen Sash of Power', value: 'Plague Sun Linen Sash of Power' },
  { label: 'Plague Tear War Belt of Giants', value: 'Plague Tear War Belt of Giants' },
  { label: 'Bramble Tear War Belt of Rage', value: 'Bramble Tear War Belt of Rage' },
  { label: 'Corpse Sun War Belt of Titans', value: 'Corpse Sun War Belt of Titans' },
  { label: 'Death Roar Heavy Belt of Fury', value: 'Death Roar Heavy Belt of Fury' },
  { label: 'Death Sun Heavy Belt of Power', value: 'Death Sun Heavy Belt of Power' },
  { label: 'Demon Bender Sash of Power +1', value: 'Demon Bender Sash of Power +1' },
  { label: 'Fate Root Linen Sash of Skill', value: 'Fate Root Linen Sash of Skill' },
  { label: 'Fate Root War Belt of Vitriol', value: 'Fate Root War Belt of Vitriol' },
  { label: 'Ghoul Sun Heavy Belt of Power', value: 'Ghoul Sun Heavy Belt of Power' },
  { label: 'Ghoul Sun Linen Sash of Anger', value: 'Ghoul Sun Linen Sash of Anger' },
  { label: 'Gloom Bite Sash of the Fox +1', value: 'Gloom Bite Sash of the Fox +1' },
  { label: 'Gloom Peak Sash of the Fox +1', value: 'Gloom Peak Sash of the Fox +1' },
  { label: 'Golem Roar Linen Sash of Fury', value: 'Golem Roar Linen Sash of Fury' },
  { label: 'Morbid Glow War Belt of Skill', value: 'Morbid Glow War Belt of Skill' },
  { label: 'Pain Glow Heavy Belt of Skill', value: 'Pain Glow Heavy Belt of Skill' },
  { label: 'Blight Bite Sash of Power +1', value: 'Blight Bite Sash of Power +1' },
  { label: 'Carrion Sun War Belt of Fury', value: 'Carrion Sun War Belt of Fury' },
  { label: 'Dragon Root War Belt of Rage', value: 'Dragon Root War Belt of Rage' },
  { label: 'Dread Bender Sash of Fury +1', value: 'Dread Bender Sash of Fury +1' },
  { label: 'Eagle Moon Sash of Giants +1', value: 'Eagle Moon Sash of Giants +1' },
  { label: 'Fate Roar War Belt of Titans', value: 'Fate Roar War Belt of Titans' },
  { label: 'Fate Sun War Belt of the Fox', value: 'Fate Sun War Belt of the Fox' },
  { label: 'Kraken Peak Sash of Anger +1', value: 'Kraken Peak Sash of Anger +1' },
  { label: 'Mind Grasp Sash of Giants +1', value: 'Mind Grasp Sash of Giants +1' },
  { label: 'Morbid Sun War Belt of Anger', value: 'Morbid Sun War Belt of Anger' },
  { label: 'Pain Root War Belt of Giants', value: 'Pain Root War Belt of Giants' },
  { label: 'Death Root War Belt of Rage', value: 'Death Root War Belt of Rage' },
  { label: 'Demon Bite Sash of Power +1', value: 'Demon Bite Sash of Power +1' },
  { label: 'Dread Bite Sash of Power +1', value: 'Dread Bite Sash of Power +1' },
  { label: 'Dread Moon Sash of Skill +1', value: 'Dread Moon Sash of Skill +1' },
  { label: 'Dread Peak Sash of Power +1', value: 'Dread Peak Sash of Power +1' },
  { label: 'Hard Leather Belt of Giants', value: 'Hard Leather Belt of Giants' },
  { label: 'Havoc Tear War Belt of Rage', value: 'Havoc Tear War Belt of Rage' },
  { label: 'Pain Roar War Belt of Power', value: 'Pain Roar War Belt of Power' },
  { label: 'Eagle Peak Sash of Fury +1', value: 'Eagle Peak Sash of Fury +1' },
  { label: 'Brightsilk Sash of Giants', value: 'Brightsilk Sash of Giants' },
  { label: 'Brightsilk Sash of Titans', value: 'Brightsilk Sash of Titans' },
  { label: 'Demonhide Belt of Vitriol', value: 'Demonhide Belt of Vitriol' },
  { label: 'Foe Grasp Sash of Rage +1', value: 'Foe Grasp Sash of Rage +1' },
  { label: 'Linen Sash of Fury', value: 'Linen Sash of Fury' },
  { label: 'Plated Belt of Reflection', value: 'Plated Belt of Reflection' },
  { label: 'Rage Bender Plated Belt of Perfection +1', value: 'Rage Bender Plated Belt of Perfection +1' },
  { label: 'Rage Bite Demonhide Belt of Power +1', value: 'Rage Bite Demonhide Belt of Power +1' },
  { label: 'Rage Bite Silk Sash of Perfection +1', value: 'Rage Bite Silk Sash of Perfection +1' },
  { label: 'Rage Bite Silk Sash of Titans +1', value: 'Rage Bite Silk Sash of Titans +1' },
  { label: 'Rage Grasp Silk Sash of Giants +1', value: 'Rage Grasp Silk Sash of Giants +1' },
  { label: 'Rage Moon Demonhide Belt of Rage +1', value: 'Rage Moon Demonhide Belt of Rage +1' },
  { label: 'Rage Moon Demonhide Belt of Vitriol +1', value: 'Rage Moon Demonhide Belt of Vitriol +1' },
  { label: 'Rage Moon Silk Sash of Skill +1', value: 'Rage Moon Silk Sash of Skill +1' },
  { label: 'Rage Moon Silk Sash of the Twins +1', value: 'Rage Moon Silk Sash of the Twins +1' },
  { label: 'Rage Peak Sash of Anger +1', value: 'Rage Peak Sash of Anger +1' },
  { label: 'Rage Shout Hard Leather Belt of the Twins +1', value: 'Rage Shout Hard Leather Belt of the Twins +1' },
  { label: 'Rage Shout Sash of Protection +1', value: 'Rage Shout Sash of Protection +1' },
  { label: 'Rage Shout Silk Sash of Vitriol +1', value: 'Rage Shout Silk Sash of Vitriol +1' },
  { label: 'Rune Glow Brightsilk Sash of the Twins', value: 'Rune Glow Brightsilk Sash of the Twins' },
  { label: 'Rune Glow Studded Leather Belt of Brilliance', value: 'Rune Glow Studded Leather Belt of Brilliance' },
  { label: 'Rune Roar Brightsilk Sash of Titans', value: 'Rune Roar Brightsilk Sash of Titans' },
  { label: 'Rune Roar Studded Leather Belt of Power', value: 'Rune Roar Studded Leather Belt of Power' },
  { label: 'Rune Roar Studded Leather Belt of the Fox', value: 'Rune Roar Studded Leather Belt of the Fox' },
  { label: 'Rune Roar Studded Leather Belt of Titans', value: 'Rune Roar Studded Leather Belt of Titans' },
  { label: 'Rune Sun Linen Sash of Reflection', value: 'Rune Sun Linen Sash of Reflection' },
  { label: 'Rune Sun Studded Leather Belt of Enlightenment', value: 'Rune Sun Studded Leather Belt of Enlightenment' },
  { label: 'Rune Tear Linen Sash of Skill', value: 'Rune Tear Linen Sash of Skill' },
  { label: 'Rune Tear Studded Leather Belt of Giants', value: 'Rune Tear Studded Leather Belt of Giants' },
  { label: 'Rune Tear Studded Leather Belt of Protection', value: 'Rune Tear Studded Leather Belt of Protection' },
  { label: 'Rune Tear Studded Leather Belt of Skill', value: 'Rune Tear Studded Leather Belt of Skill' },
  { label: 'Rune Whisper Brightsilk Sash of Anger', value: 'Rune Whisper Brightsilk Sash of Anger' },
  { label: 'Shimmering Bender Demonhide Belt of Enlightenment +1', value: 'Shimmering Bender Demonhide Belt of Enlightenment +1' },
  { label: 'Shimmering Bender Hard Leather Belt of Perfection +1', value: 'Shimmering Bender Hard Leather Belt of Perfection +1' },
  { label: 'Shimmering Bender Silk Sash of Titans +1', value: 'Shimmering Bender Silk Sash of Titans +1' },
  { label: 'Shimmering Bite Demonhide Belt of Enlightenment +1', value: 'Shimmering Bite Demonhide Belt of Enlightenment +1' },
  { label: 'Shimmering Bite Demonhide Belt of Perfection +1', value: 'Shimmering Bite Demonhide Belt of Perfection +1' },
  { label: 'Shimmering Bite Sash of Enlightenment +1', value: 'Shimmering Bite Sash of Enlightenment +1' },
  { label: 'Shimmering Grasp Plated Belt of the Twins +1', value: 'Shimmering Grasp Plated Belt of the Twins +1' },
  { label: 'Shimmering Grasp Silk Sash of Skill +1', value: 'Shimmering Grasp Silk Sash of Skill +1' },
  { label: 'Shimmering Moon Demonhide Belt of Rage +1', value: 'Shimmering Moon Demonhide Belt of Rage +1' },
  { label: 'Shimmering Moon Hard Leather Belt of Vitriol +1', value: 'Shimmering Moon Hard Leather Belt of Vitriol +1' },
  { label: 'Shimmering Moon Plated Belt of Brilliance +1', value: 'Shimmering Moon Plated Belt of Brilliance +1' },
  { label: 'Silk Sash of Perfection', value: 'Silk Sash of Perfection' },
  { label: 'Silk Sash of Skill', value: 'Silk Sash of Skill' },
  { label: 'Skull Bender Demonhide Belt of Fury +1', value: 'Skull Bender Demonhide Belt of Fury +1' },
  { label: 'Skull Bender Hard Leather Belt of Power +1', value: 'Skull Bender Hard Leather Belt of Power +1' },
  { label: 'Skull Bender Sash of Power +1', value: 'Skull Bender Sash of Power +1' },
  { label: 'Skull Bender Sash of Titans +1', value: 'Skull Bender Sash of Titans +1' },
  { label: 'Skull Bite Plated Belt of Perfection +1', value: 'Skull Bite Plated Belt of Perfection +1' },
  { label: 'Skull Bite Sash of Enlightenment +1', value: 'Skull Bite Sash of Enlightenment +1' },
  { label: 'Skull Bite Sash of Perfection +1', value: 'Skull Bite Sash of Perfection +1' },
  { label: 'Skull Bite Silk Sash of Perfection +1', value: 'Skull Bite Silk Sash of Perfection +1' },
  { label: 'Skull Grasp Plated Belt of Protection +1', value: 'Skull Grasp Plated Belt of Protection +1' },
  { label: 'Skull Grasp Silk Sash of Giants +1', value: 'Skull Grasp Silk Sash of Giants +1' },
  { label: 'Skull Moon Demonhide Belt of Detection +1', value: 'Skull Moon Demonhide Belt of Detection +1' },
  { label: 'Skull Moon Demonhide Belt of Rage +1', value: 'Skull Moon Demonhide Belt of Rage +1' },
  { label: 'Skull Moon Plated Belt of Brilliance +1', value: 'Skull Moon Plated Belt of Brilliance +1' },
  { label: 'Skull Moon Plated Belt of Detection +1', value: 'Skull Moon Plated Belt of Detection +1' },
  { label: 'Skull Moon Plated Belt of Protection +1', value: 'Skull Moon Plated Belt of Protection +1' },
  { label: 'Skull Moon Sash of Detection +1', value: 'Skull Moon Sash of Detection +1' },
  { label: 'Skull Moon Sash of Rage +1', value: 'Skull Moon Sash of Rage +1' },
  { label: 'Skull Peak Hard Leather Belt of Power +1', value: 'Skull Peak Hard Leather Belt of Power +1' },
  { label: 'Sorrow Bender Hard Leather Belt of Anger +1', value: 'Sorrow Bender Hard Leather Belt of Anger +1' },
  { label: 'Sorrow Bite Sash of Fury +1', value: 'Sorrow Bite Sash of Fury +1' },
  { label: 'Sorrow Bite Silk Sash of Fury +1', value: 'Sorrow Bite Silk Sash of Fury +1' },
  { label: 'Sorrow Bite Silk Sash of Power +1', value: 'Sorrow Bite Silk Sash of Power +1' },
  { label: 'Sorrow Grasp Hard Leather Belt of Brilliance +1', value: 'Sorrow Grasp Hard Leather Belt of Brilliance +1' },
  { label: 'Sorrow Grasp Sash of Giants +1', value: 'Sorrow Grasp Sash of Giants +1' },
  { label: 'Sorrow Grasp Silk Sash of Protection +1', value: 'Sorrow Grasp Silk Sash of Protection +1' },
  { label: 'Sorrow Moon Plated Belt of Rage +1', value: 'Sorrow Moon Plated Belt of Rage +1' },
  { label: 'Sorrow Moon Sash of Brilliance +1', value: 'Sorrow Moon Sash of Brilliance +1' },
  { label: 'Sorrow Moon Sash of Vitriol +1', value: 'Sorrow Moon Sash of Vitriol +1' },
  { label: 'Sorrow Moon Silk Sash of Detection +1', value: 'Sorrow Moon Silk Sash of Detection +1' },
  { label: 'Sorrow Peak Demonhide Belt of Perfection +1', value: 'Sorrow Peak Demonhide Belt of Perfection +1' },
  { label: 'Sorrow Peak Hard Leather Belt of Titans +1', value: 'Sorrow Peak Hard Leather Belt of Titans +1' },
  { label: 'Sorrow Peak Silk Sash of Fury +1', value: 'Sorrow Peak Silk Sash of Fury +1' },
  { label: 'Sorrow Shout Demonhide Belt of Skill +1', value: 'Sorrow Shout Demonhide Belt of Skill +1' },
  { label: 'Sorrow Shout Hard Leather Belt of Detection +1', value: 'Sorrow Shout Hard Leather Belt of Detection +1' },
  { label: 'Sorrow Shout Hard Leather Belt of Rage +1', value: 'Sorrow Shout Hard Leather Belt of Rage +1' },
  { label: 'Sorrow Shout Hard Leather Belt of the Twins +1', value: 'Sorrow Shout Hard Leather Belt of the Twins +1' },
  { label: 'Soul Glow Brightsilk Sash of Vitriol', value: 'Soul Glow Brightsilk Sash of Vitriol' },
  { label: 'Soul Glow Studded Leather Belt of Rage', value: 'Soul Glow Studded Leather Belt of Rage' },
  { label: 'Soul Roar Heavy Belt of Anger', value: 'Soul Roar Heavy Belt of Anger' },
  { label: 'Soul Root Heavy Belt of Protection', value: 'Soul Root Heavy Belt of Protection' },
  { label: 'Soul Sun Brightsilk Sash of Reflection', value: 'Soul Sun Brightsilk Sash of Reflection' },
  { label: 'Soul Sun Heavy Belt of the Fox', value: 'Soul Sun Heavy Belt of the Fox' },
  { label: 'Soul Sun Studded Leather Belt of Enlightenment', value: 'Soul Sun Studded Leather Belt of Enlightenment' },
  { label: 'Soul Tear Brightsilk Sash of Skill', value: 'Soul Tear Brightsilk Sash of Skill' },
  { label: 'Soul Tear Linen Sash of Detection', value: 'Soul Tear Linen Sash of Detection' },
  { label: 'Soul Tear Linen Sash of Vitriol', value: 'Soul Tear Linen Sash of Vitriol' },
  { label: 'Soul Whisper Heavy Belt of Enlightenment', value: 'Soul Whisper Heavy Belt of Enlightenment' },
  { label: 'Soul Whisper Heavy Belt of Reflection', value: 'Soul Whisper Heavy Belt of Reflection' },
  { label: 'Soul Whisper War Belt of Anger', value: 'Soul Whisper War Belt of Anger' },
  { label: 'Storm Glow Heavy Belt of Rage', value: 'Storm Glow Heavy Belt of Rage' },
  { label: 'Storm Glow Linen Sash of Brilliance', value: 'Storm Glow Linen Sash of Brilliance' },
  { label: 'Storm Glow Linen Sash of Skill', value: 'Storm Glow Linen Sash of Skill' },
  { label: 'Storm Roar Brightsilk Sash of Power', value: 'Storm Roar Brightsilk Sash of Power' },
  { label: 'Storm Root Studded Leather Belt of Giants', value: 'Storm Root Studded Leather Belt of Giants' },
  { label: 'Storm Root Studded Leather Belt of Rage', value: 'Storm Root Studded Leather Belt of Rage' },
  { label: 'Storm Sun Brightsilk Sash of Titans', value: 'Storm Sun Brightsilk Sash of Titans' },
  { label: 'Storm Sun Heavy Belt of Titans', value: 'Storm Sun Heavy Belt of Titans' },
  { label: 'Storm Tear Brightsilk Sash of Detection', value: 'Storm Tear Brightsilk Sash of Detection' },
  { label: 'Storm Tear Heavy Belt of Giants', value: 'Storm Tear Heavy Belt of Giants' },
  { label: 'Storm Tear Heavy Belt of Vitriol', value: 'Storm Tear Heavy Belt of Vitriol' },
  { label: 'Storm Tear Studded Leather Belt of Giants', value: 'Storm Tear Studded Leather Belt of Giants' },
  { label: 'Storm Whisper Heavy Belt of the Fox', value: 'Storm Whisper Heavy Belt of the Fox' },
  { label: 'Storm Whisper Linen Sash of Enlightenment', value: 'Storm Whisper Linen Sash of Enlightenment' },
  { label: 'Storm Whisper War Belt of Reflection', value: 'Storm Whisper War Belt of Reflection' },
  { label: 'Tempest Bender Demonhide Belt of Anger +1', value: 'Tempest Bender Demonhide Belt of Anger +1' },
  { label: 'Tempest Bender Sash of Power +1', value: 'Tempest Bender Sash of Power +1' },
  { label: 'Tempest Bender Sash of Reflection +1', value: 'Tempest Bender Sash of Reflection +1' },
  { label: 'Tempest Bender Silk Sash of Reflection +1', value: 'Tempest Bender Silk Sash of Reflection +1' },
  { label: 'Tempest Bite Sash of Reflection +1', value: 'Tempest Bite Sash of Reflection +1' },
  { label: 'Tempest Bite Silk Sash of Enlightenment +1', value: 'Tempest Bite Silk Sash of Enlightenment +1' },
  { label: 'Tempest Grasp Demonhide Belt of Rage +1', value: 'Tempest Grasp Demonhide Belt of Rage +1' },
  { label: 'Tempest Grasp Hard Leather Belt of Protection +1', value: 'Tempest Grasp Hard Leather Belt of Protection +1' },
  { label: 'Tempest Grasp Sash of the Twins +1', value: 'Tempest Grasp Sash of the Twins +1' },
  { label: 'Tempest Moon Demonhide Belt of Detection +1', value: 'Tempest Moon Demonhide Belt of Detection +1' },
  { label: 'Tempest Moon Sash of Giants +1', value: 'Tempest Moon Sash of Giants +1' },
  { label: 'Tempest Peak Hard Leather Belt of Power +1', value: 'Tempest Peak Hard Leather Belt of Power +1' },
  { label: 'Tempest Peak Silk Sash of Fury +1', value: 'Tempest Peak Silk Sash of Fury +1' },
  { label: 'Tempest Shout Plated Belt of Brilliance +1', value: 'Tempest Shout Plated Belt of Brilliance +1' },
  { label: 'Tempest Shout Plated Belt of Rage +1', value: 'Tempest Shout Plated Belt of Rage +1' },
  { label: 'Tempest Shout Silk Sash of Detection +1', value: 'Tempest Shout Silk Sash of Detection +1' },
  { label: 'Vengeance Glow Studded Leather Belt of Brilliance', value: 'Vengeance Glow Studded Leather Belt of Brilliance' },
  { label: 'Vengeance Glow War Belt of Vitriol', value: 'Vengeance Glow War Belt of Vitriol' },
  { label: 'Vengeance Roar Brightsilk Sash of Perfection', value: 'Vengeance Roar Brightsilk Sash of Perfection' },
  { label: 'Vengeance Roar Brightsilk Sash of the Fox', value: 'Vengeance Roar Brightsilk Sash of the Fox' },
  { label: 'Vengeance Roar Linen Sash of Titans', value: 'Vengeance Roar Linen Sash of Titans' },
  { label: 'Vengeance Roar Studded Leather Belt of Reflection', value: 'Vengeance Roar Studded Leather Belt of Reflection' },
  { label: 'Vengeance Roar War Belt of Enlightenment', value: 'Vengeance Roar War Belt of Enlightenment' },
  { label: 'Vengeance Roar War Belt of Titans', value: 'Vengeance Roar War Belt of Titans' },
  { label: 'Vengeance Root Studded Leather Belt of Giants', value: 'Vengeance Root Studded Leather Belt of Giants' },
  { label: 'Vengeance Root War Belt of Rage', value: 'Vengeance Root War Belt of Rage' },
  { label: 'Vengeance Sun Brightsilk Sash of Fury', value: 'Vengeance Sun Brightsilk Sash of Fury' },
  { label: 'Vengeance Sun Heavy Belt of Enlightenment', value: 'Vengeance Sun Heavy Belt of Enlightenment' },
  { label: 'Vengeance Sun War Belt of Enlightenment', value: 'Vengeance Sun War Belt of Enlightenment' },
  { label: 'Vengeance Tear War Belt of the Twins', value: 'Vengeance Tear War Belt of the Twins' },
  { label: 'Vengeance Tear War Belt of Vitriol', value: 'Vengeance Tear War Belt of Vitriol' },
  { label: 'Vengeance Whisper Heavy Belt of Anger', value: 'Vengeance Whisper Heavy Belt of Anger' },
  { label: 'Vengeance Whisper Heavy Belt of Power', value: 'Vengeance Whisper Heavy Belt of Power' },
  { label: 'Vengeance Whisper War Belt of Enlightenment', value: 'Vengeance Whisper War Belt of Enlightenment' },
  { label: 'Victory Bender Hard Leather Belt of Power +1', value: 'Victory Bender Hard Leather Belt of Power +1' },
  { label: 'Victory Bite Sash of Anger +1', value: 'Victory Bite Sash of Anger +1' },
  { label: 'Victory Grasp Demonhide Belt of Vitriol +1', value: 'Victory Grasp Demonhide Belt of Vitriol +1' },
  { label: 'Victory Grasp Plated Belt of Vitriol +1', value: 'Victory Grasp Plated Belt of Vitriol +1' },
  { label: 'Victory Grasp Silk Sash of Detection +1', value: 'Victory Grasp Silk Sash of Detection +1' },
  { label: 'Victory Grasp Silk Sash of Giants +1', value: 'Victory Grasp Silk Sash of Giants +1' },
  { label: 'Victory Grasp Silk Sash of Skill +1', value: 'Victory Grasp Silk Sash of Skill +1' },
  { label: 'Victory Moon Demonhide Belt of the Twins +1', value: 'Victory Moon Demonhide Belt of the Twins +1' },
  { label: 'Victory Moon Plated Belt of Vitriol +1', value: 'Victory Moon Plated Belt of Vitriol +1' },
  { label: 'Victory Moon Silk Sash of Skill +1', value: 'Victory Moon Silk Sash of Skill +1' },
  { label: 'Victory Peak Demonhide Belt of Fury +1', value: 'Victory Peak Demonhide Belt of Fury +1' },
  { label: 'Victory Peak Demonhide Belt of Titans +1', value: 'Victory Peak Demonhide Belt of Titans +1' },
  { label: 'Victory Peak Plated Belt of Fury +1', value: 'Victory Peak Plated Belt of Fury +1' },
  { label: 'Victory Peak Plated Belt of Titans +1', value: 'Victory Peak Plated Belt of Titans +1' },
  { label: 'Victory Peak Sash of Titans +1', value: 'Victory Peak Sash of Titans +1' },
  { label: 'Victory Peak Silk Sash of Reflection +1', value: 'Victory Peak Silk Sash of Reflection +1' },
  { label: 'Victory Shout Demonhide Belt of Skill +1', value: 'Victory Shout Demonhide Belt of Skill +1' },
  { label: 'Victory Shout Plated Belt of Vitriol +1', value: 'Victory Shout Plated Belt of Vitriol +1' },
  { label: 'Vortex Glow War Belt of Vitriol', value: 'Vortex Glow War Belt of Vitriol' },
  { label: 'Vortex Roar Brightsilk Sash of Fury', value: 'Vortex Roar Brightsilk Sash of Fury' },
  { label: 'Vortex Roar War Belt of Anger', value: 'Vortex Roar War Belt of Anger' },
  { label: 'Vortex Root Brightsilk Sash of Brilliance', value: 'Vortex Root Brightsilk Sash of Brilliance' },
  { label: 'Vortex Root Studded Leather Belt of Giants', value: 'Vortex Root Studded Leather Belt of Giants' },
  { label: 'Vortex Sun War Belt of Perfection', value: 'Vortex Sun War Belt of Perfection' },
  { label: 'Vortex Tear Brightsilk Sash of Giants', value: 'Vortex Tear Brightsilk Sash of Giants' },
  { label: 'Vortex Tear Heavy Belt of Brilliance', value: 'Vortex Tear Heavy Belt of Brilliance' },
  { label: 'Vortex Tear Heavy Belt of the Twins', value: 'Vortex Tear Heavy Belt of the Twins' },
  { label: 'Vortex Tear Heavy Belt of Vitriol', value: 'Vortex Tear Heavy Belt of Vitriol' },
  { label: 'Vortex Tear Studded Leather Belt of Skill', value: 'Vortex Tear Studded Leather Belt of Skill' },
  { label: 'Vortex Tear War Belt of Vitriol', value: 'Vortex Tear War Belt of Vitriol' },
  { label: 'Vortex Whisper Studded Leather Belt of Perfection', value: 'Vortex Whisper Studded Leather Belt of Perfection' },
  { label: 'Vortex Whisper Studded Leather Belt of the Fox', value: 'Vortex Whisper Studded Leather Belt of the Fox' },
  { label: 'Vortex Whisper War Belt of Enlightenment', value: 'Vortex Whisper War Belt of Enlightenment' },
  { label: 'War Belt of Giants', value: 'War Belt of Giants' },
  { label: 'Woe Bite Demonhide Belt of Enlightenment +1', value: 'Woe Bite Demonhide Belt of Enlightenment +1' },
  { label: 'Woe Bite Demonhide Belt of Perfection +1', value: 'Woe Bite Demonhide Belt of Perfection +1' },
  { label: 'Woe Bite Plated Belt of Anger +1', value: 'Woe Bite Plated Belt of Anger +1' },
  { label: 'Woe Bite Silk Sash of Enlightenment +1', value: 'Woe Bite Silk Sash of Enlightenment +1' },
  { label: 'Woe Grasp Demonhide Belt of Skill +1', value: 'Woe Grasp Demonhide Belt of Skill +1' },
  { label: 'Woe Grasp Sash of Skill +1', value: 'Woe Grasp Sash of Skill +1' },
  { label: 'Woe Moon Demonhide Belt of Giants +1', value: 'Woe Moon Demonhide Belt of Giants +1' },
  { label: 'Woe Moon Demonhide Belt of the Twins +1', value: 'Woe Moon Demonhide Belt of the Twins +1' },
  { label: 'Woe Moon Hard Leather Belt of Vitriol +1', value: 'Woe Moon Hard Leather Belt of Vitriol +1' },
  { label: 'Woe Moon Plated Belt of Protection +1', value: 'Woe Moon Plated Belt of Protection +1' },
  { label: 'Woe Peak Hard Leather Belt of Reflection +1', value: 'Woe Peak Hard Leather Belt of Reflection +1' },
  { label: 'Woe Peak Plated Belt of Perfection +1', value: 'Woe Peak Plated Belt of Perfection +1' },
  { label: 'Woe Peak Sash of Anger +1', value: 'Woe Peak Sash of Anger +1' },
  { label: 'Woe Peak Silk Sash of Anger +1', value: 'Woe Peak Silk Sash of Anger +1' },
  { label: 'Woe Peak Silk Sash of Titans +1', value: 'Woe Peak Silk Sash of Titans +1' },
  { label: 'Woe Shout Demonhide Belt of Giants +1', value: 'Woe Shout Demonhide Belt of Giants +1' },
  { label: 'Woe Shout Demonhide Belt of Protection +1', value: 'Woe Shout Demonhide Belt of Protection +1' },
  { label: 'Woe Shout Demonhide Belt of the Twins +1', value: 'Woe Shout Demonhide Belt of the Twins +1' },
  { label: 'Woe Shout Plated Belt of Detection +1', value: 'Woe Shout Plated Belt of Detection +1' },
  { label: 'Woe Shout Sash of Detection +1', value: 'Woe Shout Sash of Detection +1' },
  { label: 'Woe Shout Sash of Skill +1', value: 'Woe Shout Sash of Skill +1' },
];
