export const feet = [
  { label: 'Chain Boots', value: 'Chain Boots' },
  { label: 'Linen Shoes', value: 'Linen Shoes' },
  { label: 'Divine Slippers', value: 'Divine Slippers' },
  { label: 'Wool Shoes', value: 'Wool Shoes' },
  { label: 'Greaves', value: 'Greaves' },
  { label: 'Studded Leather Boots', value: 'Studded Leather Boots' },
  { label: 'Leather Boots', value: 'Leather Boots' },
  { label: 'Shoes', value: 'Shoes' },
  { label: 'Holy Greaves', value: 'Holy Greaves' },
  { label: 'Dragonskin Boots', value: 'Dragonskin Boots' },
  { label: 'Demonhide Boots', value: 'Demonhide Boots' },
  { label: 'Ornate Greaves', value: 'Ornate Greaves' },
  { label: 'Silk Slippers', value: 'Silk Slippers' },
  { label: 'Hard Leather Boots', value: 'Hard Leather Boots' },
  { label: 'Heavy Boots', value: 'Heavy Boots' },
  { label: 'Dragonskin Boots of Detection', value: 'Dragonskin Boots of Detection' },
  { label: 'Dragonskin Boots of Fury', value: 'Dragonskin Boots of Fury' },
  { label: 'Chain Boots of Detection', value: 'Chain Boots of Detection' },
  { label: 'Leather Boots of Enlightenment', value: 'Leather Boots of Enlightenment' },
  { label: 'Leather Boots of Detection', value: 'Leather Boots of Detection' },
  { label: 'Wool Shoes of Giants', value: 'Wool Shoes of Giants' },
  { label: 'Leather Boots of Protection', value: 'Leather Boots of Protection' },
  { label: 'Chain Boots of Perfection', value: 'Chain Boots of Perfection' },
  { label: 'Dragonskin Boots of Rage', value: 'Dragonskin Boots of Rage' },
  { label: 'Holy Greaves of Skill', value: 'Holy Greaves of Skill' },
  { label: 'Wool Shoes of Vitriol', value: 'Wool Shoes of Vitriol' },
  { label: 'Dragonskin Boots of Reflection', value: 'Dragonskin Boots of Reflection' },
  { label: 'Leather Boots of Brilliance', value: 'Leather Boots of Brilliance' },
  { label: 'Holy Greaves of Perfection', value: 'Holy Greaves of Perfection' },
  { label: 'Dragonskin Boots of Anger', value: 'Dragonskin Boots of Anger' },
  { label: 'Wool Shoes of the Twins', value: 'Wool Shoes of the Twins' },
  { label: 'Holy Greaves of Power', value: 'Holy Greaves of Power' },
  { label: 'Holy Greaves of Fury', value: 'Holy Greaves of Fury' },
  { label: 'Holy Greaves of Enlightenment', value: 'Holy Greaves of Enlightenment' },
  { label: 'Chain Boots of Reflection', value: 'Chain Boots of Reflection' },
  { label: 'Leather Boots of the Fox', value: 'Leather Boots of the Fox' },
  { label: 'Leather Boots of Anger', value: 'Leather Boots of Anger' },
  { label: 'Chain Boots of Giants', value: 'Chain Boots of Giants' },
  { label: 'Shoes of Brilliance', value: 'Shoes of Brilliance' },
  { label: 'Wool Shoes of Brilliance', value: 'Wool Shoes of Brilliance' },
  { label: 'Holy Greaves of Vitriol', value: 'Holy Greaves of Vitriol' },
  { label: 'Leather Boots of Fury', value: 'Leather Boots of Fury' },
  { label: 'Wool Shoes of the Fox', value: 'Wool Shoes of the Fox' },
  { label: 'Chain Boots of Anger', value: 'Chain Boots of Anger' },
  { label: 'Chain Boots of Fury', value: 'Chain Boots of Fury' },
  { label: 'Wool Shoes of Anger', value: 'Wool Shoes of Anger' },
  { label: 'Wool Shoes of Rage', value: 'Wool Shoes of Rage' },
  { label: 'Dragonskin Boots of Enlightenment', value: 'Dragonskin Boots of Enlightenment' },
  { label: 'Dragonskin Boots of Perfection', value: 'Dragonskin Boots of Perfection' },
  { label: 'Chain Boots of Enlightenment', value: 'Chain Boots of Enlightenment' },
  { label: 'Dragonskin Boots of Vitriol', value: 'Dragonskin Boots of Vitriol' },
  { label: 'Dragonskin Boots of Titans', value: 'Dragonskin Boots of Titans' },
  { label: 'Chain Boots of Protection', value: 'Chain Boots of Protection' },
  { label: 'Heavy Boots of Brilliance', value: 'Heavy Boots of Brilliance' },
  { label: 'Leather Boots of Vitriol', value: 'Leather Boots of Vitriol' },
  { label: 'Holy Greaves of the Fox', value: 'Holy Greaves of the Fox' },
  { label: 'Chain Boots of the Fox', value: 'Chain Boots of the Fox' },
  { label: 'Chain Boots of Skill', value: 'Chain Boots of Skill' },
  { label: 'Dragonskin Boots of Brilliance', value: 'Dragonskin Boots of Brilliance' },
  { label: 'Dragonskin Boots of Protection', value: 'Dragonskin Boots of Protection' },
  { label: 'Demonhide Boots of Brilliance', value: 'Demonhide Boots of Brilliance' },
  { label: 'Dragonskin Boots of the Twins', value: 'Dragonskin Boots of the Twins' },
  { label: 'Wool Shoes of Enlightenment', value: 'Wool Shoes of Enlightenment' },
  { label: 'Dragonskin Boots of Giants', value: 'Dragonskin Boots of Giants' },
  { label: 'Holy Greaves of Brilliance', value: 'Holy Greaves of Brilliance' },
  { label: 'Holy Greaves of Reflection', value: 'Holy Greaves of Reflection' },
  { label: 'Chain Boots of Brilliance', value: 'Chain Boots of Brilliance' },
  { label: 'Ornate Greaves of the Fox', value: 'Ornate Greaves of the Fox' },
  { label: 'Wool Shoes of Perfection', value: 'Wool Shoes of Perfection' },
  { label: 'Chain Boots of Vitriol', value: 'Chain Boots of Vitriol' },
  { label: 'Holy Greaves of Titans', value: 'Holy Greaves of Titans' },
  { label: 'Chain Boots of Titans', value: 'Chain Boots of Titans' },
  { label: 'Holy Greaves of Anger', value: 'Holy Greaves of Anger' },
  { label: 'Holy Greaves of Rage', value: 'Holy Greaves of Rage' },
  { label: 'Chain Boots of Rage', value: 'Chain Boots of Rage' },
  { label: 'Wool Shoes of Fury', value: 'Wool Shoes of Fury' },
  { label: 'Studded Leather Boots of Brilliance', value: 'Studded Leather Boots of Brilliance' },
  { label: 'Demonhide Boots of Perfection', value: 'Demonhide Boots of Perfection' },
  { label: 'Demonhide Boots of Detection', value: 'Demonhide Boots of Detection' },
  { label: 'Leather Boots of Perfection', value: 'Leather Boots of Perfection' },
  { label: 'Leather Boots of Reflection', value: 'Leather Boots of Reflection' },
  { label: 'Holy Greaves of Protection', value: 'Holy Greaves of Protection' },
  { label: 'Leather Boots of the Twins', value: 'Leather Boots of the Twins' },
  { label: 'Silk Slippers of Detection', value: 'Silk Slippers of Detection' },
  { label: 'Dragonskin Boots of Skill', value: 'Dragonskin Boots of Skill' },
  { label: 'Holy Greaves of the Twins', value: 'Holy Greaves of the Twins' },
  { label: 'Wool Shoes of Protection', value: 'Wool Shoes of Protection' },
  { label: 'Wool Shoes of Reflection', value: 'Wool Shoes of Reflection' },
  { label: 'Leather Boots of Giants', value: 'Leather Boots of Giants' },
  { label: 'Ornate Greaves of Fury', value: 'Ornate Greaves of Fury' },
  { label: 'Greaves of Perfection', value: 'Greaves of Perfection' },
  { label: 'Chain Boots of Power', value: 'Chain Boots of Power' },
  { label: 'Wool Shoes of Power', value: 'Wool Shoes of Power' },
  { label: 'Silk Slippers of Enlightenment', value: 'Silk Slippers of Enlightenment' },
  { label: 'Divine Slippers of Brilliance', value: 'Divine Slippers of Brilliance' },
  { label: 'Divine Slippers of the Twins', value: 'Divine Slippers of the Twins' },
  { label: 'Heavy Boots of Enlightenment', value: 'Heavy Boots of Enlightenment' },
  { label: 'Dragonskin Boots of the Fox', value: 'Dragonskin Boots of the Fox' },
  { label: 'Hard Leather Boots of Anger', value: 'Hard Leather Boots of Anger' },
  { label: 'Divine Slippers of Giants', value: 'Divine Slippers of Giants' },
  { label: 'Dragonskin Boots of Power', value: 'Dragonskin Boots of Power' },
  { label: 'Heavy Boots of Protection', value: 'Heavy Boots of Protection' },
  { label: 'Divine Slippers of Anger', value: 'Divine Slippers of Anger' },
  { label: 'Heavy Boots of Detection', value: 'Heavy Boots of Detection' },
  { label: 'Linen Shoes of the Twins', value: 'Linen Shoes of the Twins' },
  { label: 'Ornate Greaves of Titans', value: 'Ornate Greaves of Titans' },
  { label: 'Silk Slippers of Giants', value: 'Silk Slippers of Giants' },
  { label: 'Leather Boots of Skill', value: 'Leather Boots of Skill' },
  { label: 'Wool Shoes of Titans', value: 'Wool Shoes of Titans' },
  { label: 'Linen Shoes of Rage', value: 'Linen Shoes of Rage' },
  { label: 'Wool Shoes of Skill', value: 'Wool Shoes of Skill' },
  { label: 'Shoes of the Twins', value: 'Shoes of the Twins' },
  { label: 'Studded Leather Boots of Detection', value: 'Studded Leather Boots of Detection' },
  { label: 'Hard Leather Boots of Detection', value: 'Hard Leather Boots of Detection' },
  { label: 'Studded Leather Boots of Anger', value: 'Studded Leather Boots of Anger' },
  { label: 'Demonhide Boots of Protection', value: 'Demonhide Boots of Protection' },
  { label: 'Demonhide Boots of Reflection', value: 'Demonhide Boots of Reflection' },
  { label: 'Divine Slippers of Reflection', value: 'Divine Slippers of Reflection' },
  { label: 'Ornate Greaves of Reflection', value: 'Ornate Greaves of Reflection' },
  { label: 'Silk Slippers of Perfection', value: 'Silk Slippers of Perfection' },
  { label: 'Divine Slippers of the Fox', value: 'Divine Slippers of the Fox' },
  { label: 'Hard Leather Boots of Rage', value: 'Hard Leather Boots of Rage' },
  { label: 'Ornate Greaves of Giants', value: 'Ornate Greaves of Giants' },
  { label: 'Silk Slippers of the Fox', value: 'Silk Slippers of the Fox' },
  { label: 'Heavy Boots of the Fox', value: 'Heavy Boots of the Fox' },
  { label: 'Heavy Boots of Vitriol', value: 'Heavy Boots of Vitriol' },
  { label: 'Holy Greaves of Giants', value: 'Holy Greaves of Giants' },
  { label: 'Silk Slippers of Power', value: 'Silk Slippers of Power' },
  { label: 'Greaves of Reflection', value: 'Greaves of Reflection' },
  { label: 'Heavy Boots of Titans', value: 'Heavy Boots of Titans' },
  { label: 'Linen Shoes of Titans', value: 'Linen Shoes of Titans' },
  { label: 'Silk Slippers of Rage', value: 'Silk Slippers of Rage' },
  { label: 'Heavy Boots of Skill', value: 'Heavy Boots of Skill' },
  { label: 'Shoes of Reflection', value: 'Shoes of Reflection' },
  { label: 'Greaves of the Fox', value: 'Greaves of the Fox' },
  { label: 'Greaves of Giants', value: 'Greaves of Giants' },
  { label: 'Greaves of Titans', value: 'Greaves of Titans' },
  { label: 'Shoes of Titans', value: 'Shoes of Titans' },
  { label: 'Shoes of Power', value: 'Shoes of Power' },
  { label: 'Studded Leather Boots of Perfection', value: 'Studded Leather Boots of Perfection' },
  { label: 'Hard Leather Boots of Protection', value: 'Hard Leather Boots of Protection' },
  { label: 'Studded Leather Boots of the Fox', value: 'Studded Leather Boots of the Fox' },
  { label: 'Studded Leather Boots of Power', value: 'Studded Leather Boots of Power' },
  { label: 'Divine Slippers of Perfection', value: 'Divine Slippers of Perfection' },
  { label: 'Hard Leather Boots of Titans', value: 'Hard Leather Boots of Titans' },
  { label: 'Hard Leather Boots of Skill', value: 'Hard Leather Boots of Skill' },
  { label: 'Silk Slippers of Brilliance', value: 'Silk Slippers of Brilliance' },
  { label: 'Silk Slippers of the Twins', value: 'Silk Slippers of the Twins' },
  { label: 'Demonhide Boots of Giants', value: 'Demonhide Boots of Giants' },
  { label: 'Divine Slippers of Titans', value: 'Divine Slippers of Titans' },
  { label: 'Chain Boots of the Twins', value: 'Chain Boots of the Twins' },
  { label: 'Demonhide Boots of Fury', value: 'Demonhide Boots of Fury' },
  { label: 'Leather Boots of Titans', value: 'Leather Boots of Titans' },
  { label: 'Ornate Greaves of Anger', value: 'Ornate Greaves of Anger' },
  { label: 'Ornate Greaves of Power', value: 'Ornate Greaves of Power' },
  { label: 'Wool Shoes of Detection', value: 'Wool Shoes of Detection' },
  { label: 'Greaves of Protection', value: 'Greaves of Protection' },
  { label: 'Silk Slippers of Fury', value: 'Silk Slippers of Fury' },
  { label: 'Greaves of Detection', value: 'Greaves of Detection' },
  { label: 'Greaves of the Twins', value: 'Greaves of the Twins' },
  { label: 'Heavy Boots of Power', value: 'Heavy Boots of Power' },
  { label: 'Linen Shoes of Power', value: 'Linen Shoes of Power' },
  { label: 'Linen Shoes of Skill', value: 'Linen Shoes of Skill' },
  { label: 'Greaves of Anger', value: 'Greaves of Anger' },
  { label: 'Shoes of Giants', value: 'Shoes of Giants' },
  { label: 'Shoes of Anger', value: 'Shoes of Anger' },
  { label: 'Studded Leather Boots of Protection', value: 'Studded Leather Boots of Protection' },
  { label: 'Studded Leather Boots of Reflection', value: 'Studded Leather Boots of Reflection' },
  { label: 'Studded Leather Boots of the Twins', value: 'Studded Leather Boots of the Twins' },
  { label: 'Studded Leather Boots of Vitriol', value: 'Studded Leather Boots of Vitriol' },
  { label: 'Studded Leather Boots of Giants', value: 'Studded Leather Boots of Giants' },
  { label: 'Studded Leather Boots of Skill', value: 'Studded Leather Boots of Skill' },
  { label: 'Hard Leather Boots of the Fox', value: 'Hard Leather Boots of the Fox' },
  { label: 'Studded Leather Boots of Rage', value: 'Studded Leather Boots of Rage' },
  { label: 'Demonhide Boots of the Twins', value: 'Demonhide Boots of the Twins' },
  { label: 'Ornate Greaves of Protection', value: 'Ornate Greaves of Protection' },
  { label: 'Hard Leather Boots of Power', value: 'Hard Leather Boots of Power' },
  { label: 'Ornate Greaves of the Twins', value: 'Ornate Greaves of the Twins' },
  { label: 'Demonhide Boots of the Fox', value: 'Demonhide Boots of the Fox' },
  { label: 'Demonhide Boots of Vitriol', value: 'Demonhide Boots of Vitriol' },
  { label: 'Divine Slippers of Vitriol', value: 'Divine Slippers of Vitriol' },
  { label: 'Hard Leather Boots of Fury', value: 'Hard Leather Boots of Fury' },
  { label: 'Heavy Boots of Perfection', value: 'Heavy Boots of Perfection' },
  { label: 'Holy Greaves of Detection', value: 'Holy Greaves of Detection' },
  { label: 'Linen Shoes of Protection', value: 'Linen Shoes of Protection' },
  { label: 'Linen Shoes of Reflection', value: 'Linen Shoes of Reflection' },
  { label: 'Ornate Greaves of Vitriol', value: 'Ornate Greaves of Vitriol' },
  { label: 'Greaves of Enlightenment', value: 'Greaves of Enlightenment' },
  { label: 'Linen Shoes of Detection', value: 'Linen Shoes of Detection' },
  { label: 'Demonhide Boots of Rage', value: 'Demonhide Boots of Rage' },
  { label: 'Divine Slippers of Fury', value: 'Divine Slippers of Fury' },
  { label: 'Ornate Greaves of Skill', value: 'Ornate Greaves of Skill' },
  { label: 'Silk Slippers of Titans', value: 'Silk Slippers of Titans' },
  { label: 'Leather Boots of Power', value: 'Leather Boots of Power' },
  { label: 'Linen Shoes of Vitriol', value: 'Linen Shoes of Vitriol' },
  { label: 'Silk Slippers of Anger', value: 'Silk Slippers of Anger' },
  { label: 'Leather Boots of Rage', value: 'Leather Boots of Rage' },
  { label: 'Heavy Boots of Anger', value: 'Heavy Boots of Anger' },
  { label: 'Linen Shoes of Anger', value: 'Linen Shoes of Anger' },
  { label: 'Heavy Boots of Fury', value: 'Heavy Boots of Fury' },
  { label: 'Shoes of Detection', value: 'Shoes of Detection' },
  { label: 'Greaves of Skill', value: 'Greaves of Skill' },
  { label: 'Shoes of the Fox', value: 'Shoes of the Fox' },
  { label: 'Greaves of Fury', value: 'Greaves of Fury' },
  { label: 'Shoes of Skill', value: 'Shoes of Skill' },
  { label: 'Shoes of Fury', value: 'Shoes of Fury' },
  { label: 'Hard Leather Boots of Enlightenment', value: 'Hard Leather Boots of Enlightenment' },
  { label: 'Hard Leather Boots of Brilliance', value: 'Hard Leather Boots of Brilliance' },
  { label: 'Hard Leather Boots of Reflection', value: 'Hard Leather Boots of Reflection' },
  { label: 'Ornate Greaves of Enlightenment', value: 'Ornate Greaves of Enlightenment' },
  { label: 'Studded Leather Boots of Titans', value: 'Studded Leather Boots of Titans' },
  { label: 'Hard Leather Boots of Vitriol', value: 'Hard Leather Boots of Vitriol' },
  { label: 'Ornate Greaves of Brilliance', value: 'Ornate Greaves of Brilliance' },
  { label: 'Ornate Greaves of Perfection', value: 'Ornate Greaves of Perfection' },
  { label: 'Silk Slippers of Protection', value: 'Silk Slippers of Protection' },
  { label: 'Silk Slippers of Reflection', value: 'Silk Slippers of Reflection' },
  { label: 'Heavy Boots of Reflection', value: 'Heavy Boots of Reflection' },
  { label: 'Linen Shoes of Brilliance', value: 'Linen Shoes of Brilliance' },
  { label: 'Divine Slippers of Skill', value: 'Divine Slippers of Skill' },
  { label: 'Heavy Boots of the Twins', value: 'Heavy Boots of the Twins' },
  { label: 'Silk Slippers of Vitriol', value: 'Silk Slippers of Vitriol' },
  { label: 'Divine Slippers of Rage', value: 'Divine Slippers of Rage' },
  { label: 'Linen Shoes of the Fox', value: 'Linen Shoes of the Fox' },
  { label: 'Silk Slippers of Skill', value: 'Silk Slippers of Skill' },
  { label: 'Heavy Boots of Giants', value: 'Heavy Boots of Giants' },
  { label: 'Linen Shoes of Giants', value: 'Linen Shoes of Giants' },
  { label: 'Shoes of Protection', value: 'Shoes of Protection' },
  { label: 'Greaves of Power', value: 'Greaves of Power' },
  { label: 'Pandemonium Shout Silk Slippers of Detection +1', value: 'Pandemonium Shout Silk Slippers of Detection +1' },
  { label: 'Sorrow Peak Hard Leather Boots of Perfection +1', value: 'Sorrow Peak Hard Leather Boots of Perfection +1' },
  { label: 'Vortex Sun Studded Leather Boots of Reflection', value: 'Vortex Sun Studded Leather Boots of Reflection' },
  { label: 'Plague Root Studded Leather Boots of Vitriol', value: 'Plague Root Studded Leather Boots of Vitriol' },
  { label: 'Corruption Bender Greaves of Reflection +1', value: 'Corruption Bender Greaves of Reflection +1' },
  { label: 'Soul Tear Studded Leather Boots of Vitriol', value: 'Soul Tear Studded Leather Boots of Vitriol' },
  { label: 'Eagle Grasp Silk Slippers of Detection +1', value: 'Eagle Grasp Silk Slippers of Detection +1' },
  { label: 'Apocalypse Tear Divine Slippers of Skill', value: 'Apocalypse Tear Divine Slippers of Skill' },
  { label: 'Cataclysm Moon Silk Slippers of Rage +1', value: 'Cataclysm Moon Silk Slippers of Rage +1' },
  { label: 'Death Sun Divine Slippers of Perfection', value: 'Death Sun Divine Slippers of Perfection' },
  { label: 'Golem Whisper Heavy Boots of Reflection', value: 'Golem Whisper Heavy Boots of Reflection' },
  { label: 'Golem Whisper Ornate Greaves of the Fox', value: 'Golem Whisper Ornate Greaves of the Fox' },
  { label: 'Hypnotic Whisper Ornate Greaves of Fury', value: 'Hypnotic Whisper Ornate Greaves of Fury' },
  { label: "Light's Whisper Divine Slippers of Fury", value: "Light's Whisper Divine Slippers of Fury" },
  { label: 'Hypnotic Tear Divine Slippers of Skill', value: 'Hypnotic Tear Divine Slippers of Skill' },
  { label: 'Morbid Roar Divine Slippers of the Fox', value: 'Morbid Roar Divine Slippers of the Fox' },
  { label: 'Havoc Roar Heavy Boots of Reflection', value: 'Havoc Roar Heavy Boots of Reflection' },
  { label: 'Pandemonium Peak Shoes of the Fox +1', value: 'Pandemonium Peak Shoes of the Fox +1' },
  { label: 'Maelstrom Sun Linen Shoes of Fury', value: 'Maelstrom Sun Linen Shoes of Fury' },
  { label: 'Corpse Roar Linen Shoes of Anger', value: 'Corpse Roar Linen Shoes of Anger' },
  { label: 'Death Sun Heavy Boots of the Fox', value: 'Death Sun Heavy Boots of the Fox' },
  { label: 'Demonhide Boots of Enlightenment', value: 'Demonhide Boots of Enlightenment' },
  { label: 'Divine Slippers of Enlightenment', value: 'Divine Slippers of Enlightenment' },
  { label: 'Hard Leather Boots of Perfection', value: 'Hard Leather Boots of Perfection' },
  { label: 'Hard Leather Boots of the Twins', value: 'Hard Leather Boots of the Twins' },
  { label: 'Studded Leather Boots of Fury', value: 'Studded Leather Boots of Fury' },
  { label: 'Divine Slippers of Detection', value: 'Divine Slippers of Detection' },
  { label: 'Hard Leather Boots of Giants', value: 'Hard Leather Boots of Giants' },
  { label: 'Linen Shoes of Enlightenment', value: 'Linen Shoes of Enlightenment' },
  { label: 'Grim Peak Shoes of Anger +1', value: 'Grim Peak Shoes of Anger +1' },
  { label: 'Demonhide Boots of Titans', value: 'Demonhide Boots of Titans' },
  { label: 'Linen Shoes of Perfection', value: 'Linen Shoes of Perfection' },
  { label: 'Demonhide Boots of Skill', value: 'Demonhide Boots of Skill' },
  { label: 'Divine Slippers of Power', value: 'Divine Slippers of Power' },
  { label: 'Ornate Greaves of Rage', value: 'Ornate Greaves of Rage' },
  { label: 'Shoes of Enlightenment', value: 'Shoes of Enlightenment' },
  { label: 'Heavy Boots of Rage', value: 'Heavy Boots of Rage' },
  { label: 'Shoes of Perfection', value: 'Shoes of Perfection' },
  { label: 'Greaves of Vitriol', value: 'Greaves of Vitriol' },
  { label: 'Shoes of Vitriol', value: 'Shoes of Vitriol' },
  { label: 'Greaves of Rage', value: 'Greaves of Rage' },
  { label: 'Shoes of Rage', value: 'Shoes of Rage' },
  { label: 'Pandemonium Bender Hard Leather Boots of Perfection +1', value: 'Pandemonium Bender Hard Leather Boots of Perfection +1' },
  { label: 'Apocalypse Sun Studded Leather Boots of Enlightenment', value: 'Apocalypse Sun Studded Leather Boots of Enlightenment' },
  { label: 'Death Whisper Studded Leather Boots of Enlightenment', value: 'Death Whisper Studded Leather Boots of Enlightenment' },
  { label: 'Kraken Bender Hard Leather Boots of Enlightenment +1', value: 'Kraken Bender Hard Leather Boots of Enlightenment +1' },
  { label: 'Maelstrom Sun Studded Leather Boots of Enlightenment', value: 'Maelstrom Sun Studded Leather Boots of Enlightenment' },
  { label: 'Apocalypse Tear Studded Leather Boots of Protection', value: 'Apocalypse Tear Studded Leather Boots of Protection' },
  { label: 'Bramble Whisper Studded Leather Boots of Perfection', value: 'Bramble Whisper Studded Leather Boots of Perfection' },
  { label: 'Carrion Roar Studded Leather Boots of Enlightenment', value: 'Carrion Roar Studded Leather Boots of Enlightenment' },
  { label: 'Carrion Whisper Studded Leather Boots of Reflection', value: 'Carrion Whisper Studded Leather Boots of Reflection' },
  { label: 'Corruption Bite Hard Leather Boots of Perfection +1', value: 'Corruption Bite Hard Leather Boots of Perfection +1' },
  { label: 'Dread Bender Hard Leather Boots of Enlightenment +1', value: 'Dread Bender Hard Leather Boots of Enlightenment +1' },
  { label: 'Apocalypse Glow Studded Leather Boots of Detection', value: 'Apocalypse Glow Studded Leather Boots of Detection' },
  { label: 'Apocalypse Sun Studded Leather Boots of Perfection', value: 'Apocalypse Sun Studded Leather Boots of Perfection' },
  { label: 'Blight Peak Hard Leather Boots of Enlightenment +1', value: 'Blight Peak Hard Leather Boots of Enlightenment +1' },
  { label: 'Carrion Sun Studded Leather Boots of Enlightenment', value: 'Carrion Sun Studded Leather Boots of Enlightenment' },
  { label: 'Cataclysm Moon Hard Leather Boots of Protection +1', value: 'Cataclysm Moon Hard Leather Boots of Protection +1' },
  { label: 'Cataclysm Peak Hard Leather Boots of Reflection +1', value: 'Cataclysm Peak Hard Leather Boots of Reflection +1' },
  { label: 'Corruption Moon Hard Leather Boots of Detection +1', value: 'Corruption Moon Hard Leather Boots of Detection +1' },
  { label: 'Morbid Whisper Studded Leather Boots of Reflection', value: 'Morbid Whisper Studded Leather Boots of Reflection' },
  { label: 'Dread Bite Hard Leather Boots of Enlightenment +1', value: 'Dread Bite Hard Leather Boots of Enlightenment +1' },
  { label: 'Eagle Bite Hard Leather Boots of Enlightenment +1', value: 'Eagle Bite Hard Leather Boots of Enlightenment +1' },
  { label: 'Honour Bender Hard Leather Boots of Reflection +1', value: 'Honour Bender Hard Leather Boots of Reflection +1' },
  { label: 'Hypnotic Tear Studded Leather Boots of Protection', value: 'Hypnotic Tear Studded Leather Boots of Protection' },
  { label: 'Maelstrom Sun Studded Leather Boots of Perfection', value: 'Maelstrom Sun Studded Leather Boots of Perfection' },
  { label: 'Armageddon Shout Demonhide Boots of the Twins +1', value: 'Armageddon Shout Demonhide Boots of the Twins +1' },
  { label: 'Behemoth Glow Studded Leather Boots of the Twins', value: 'Behemoth Glow Studded Leather Boots of the Twins' },
  { label: 'Behemoth Whisper Ornate Greaves of Enlightenment', value: 'Behemoth Whisper Ornate Greaves of Enlightenment' },
  { label: 'Behemoth Whisper Studded Leather Boots of Titans', value: 'Behemoth Whisper Studded Leather Boots of Titans' },
  { label: 'Blight Grasp Hard Leather Boots of Protection +1', value: 'Blight Grasp Hard Leather Boots of Protection +1' },
  { label: 'Brimstone Bender Hard Leather Boots of Titans +1', value: 'Brimstone Bender Hard Leather Boots of Titans +1' },
  { label: 'Brimstone Shout Hard Leather Boots of Vitriol +1', value: 'Brimstone Shout Hard Leather Boots of Vitriol +1' },
  { label: 'Carrion Root Studded Leather Boots of Brilliance', value: 'Carrion Root Studded Leather Boots of Brilliance' },
  { label: 'Carrion Tear Studded Leather Boots of Brilliance', value: 'Carrion Tear Studded Leather Boots of Brilliance' },
  { label: 'Cataclysm Grasp Hard Leather Boots of Vitriol +1', value: 'Cataclysm Grasp Hard Leather Boots of Vitriol +1' },
  { label: 'Corruption Bite Hard Leather Boots of the Fox +1', value: 'Corruption Bite Hard Leather Boots of the Fox +1' },
  { label: 'Corruption Moon Hard Leather Boots of Vitriol +1', value: 'Corruption Moon Hard Leather Boots of Vitriol +1' },
  { label: 'Hypnotic Root Studded Leather Boots of the Twins', value: 'Hypnotic Root Studded Leather Boots of the Twins' },
  { label: "Light's Glow Studded Leather Boots of Protection", value: "Light's Glow Studded Leather Boots of Protection" },
  { label: "Light's Roar Studded Leather Boots of Perfection", value: "Light's Roar Studded Leather Boots of Perfection" },
  { label: 'Pandemonium Moon Demonhide Boots of the Twins +1', value: 'Pandemonium Moon Demonhide Boots of the Twins +1' },
  { label: 'Armageddon Bender Demonhide Boots of the Fox +1', value: 'Armageddon Bender Demonhide Boots of the Fox +1' },
  { label: 'Blight Bite Hard Leather Boots of Reflection +1', value: 'Blight Bite Hard Leather Boots of Reflection +1' },
  { label: 'Brimstone Bender Hard Leather Boots of Anger +1', value: 'Brimstone Bender Hard Leather Boots of Anger +1' },
  { label: 'Brimstone Bender Silk Slippers of Perfection +1', value: 'Brimstone Bender Silk Slippers of Perfection +1' },
  { label: 'Brimstone Grasp Demonhide Boots of the Twins +1', value: 'Brimstone Grasp Demonhide Boots of the Twins +1' },
  { label: 'Cataclysm Bender Hard Leather Boots of Power +1', value: 'Cataclysm Bender Hard Leather Boots of Power +1' },
  { label: 'Cataclysm Bender Silk Slippers of Perfection +1', value: 'Cataclysm Bender Silk Slippers of Perfection +1' },
  { label: 'Demon Grasp Hard Leather Boots of Protection +1', value: 'Demon Grasp Hard Leather Boots of Protection +1' },
  { label: 'Dragon Tear Studded Leather Boots of Protection', value: 'Dragon Tear Studded Leather Boots of Protection' },
  { label: 'Dragon Whisper Divine Slippers of Enlightenment', value: 'Dragon Whisper Divine Slippers of Enlightenment' },
  { label: 'Dread Shout Hard Leather Boots of Protection +1', value: 'Dread Shout Hard Leather Boots of Protection +1' },
  { label: 'Honour Bite Demonhide Boots of Enlightenment +1', value: 'Honour Bite Demonhide Boots of Enlightenment +1' },
  { label: 'Honour Bite Hard Leather Boots of Reflection +1', value: 'Honour Bite Hard Leather Boots of Reflection +1' },
  { label: 'Honour Moon Hard Leather Boots of Brilliance +1', value: 'Honour Moon Hard Leather Boots of Brilliance +1' },
  { label: 'Kraken Bender Silk Slippers of Enlightenment +1', value: 'Kraken Bender Silk Slippers of Enlightenment +1' },
  { label: 'Morbid Whisper Divine Slippers of Enlightenment', value: 'Morbid Whisper Divine Slippers of Enlightenment' },
  { label: 'Pain Sun Studded Leather Boots of Enlightenment', value: 'Pain Sun Studded Leather Boots of Enlightenment' },
  { label: 'Pandemonium Bite Silk Slippers of Reflection +1', value: 'Pandemonium Bite Silk Slippers of Reflection +1' },
  { label: 'Armageddon Bite Silk Slippers of Perfection +1', value: 'Armageddon Bite Silk Slippers of Perfection +1' },
  { label: 'Armageddon Shout Silk Slippers of Detection +1', value: 'Armageddon Shout Silk Slippers of Detection +1' },
  { label: 'Corruption Bite Silk Slippers of Reflection +1', value: 'Corruption Bite Silk Slippers of Reflection +1' },
  { label: 'Death Tear Studded Leather Boots of Brilliance', value: 'Death Tear Studded Leather Boots of Brilliance' },
  { label: 'Dragon Sun Studded Leather Boots of Reflection', value: 'Dragon Sun Studded Leather Boots of Reflection' },
  { label: 'Dragon Whisper Studded Leather Boots of Titans', value: 'Dragon Whisper Studded Leather Boots of Titans' },
  { label: 'Dread Shout Hard Leather Boots of the Twins +1', value: 'Dread Shout Hard Leather Boots of the Twins +1' },
  { label: 'Eagle Moon Hard Leather Boots of Protection +1', value: 'Eagle Moon Hard Leather Boots of Protection +1' },
  { label: 'Havoc Root Studded Leather Boots of Protection', value: 'Havoc Root Studded Leather Boots of Protection' },
  { label: 'Armageddon Bender Greaves of Enlightenment +1', value: 'Armageddon Bender Greaves of Enlightenment +1' },
  { label: 'Behemoth Roar Ornate Greaves of Enlightenment', value: 'Behemoth Roar Ornate Greaves of Enlightenment' },
  { label: 'Behemoth Whisper Heavy Boots of Enlightenment', value: 'Behemoth Whisper Heavy Boots of Enlightenment' },
  { label: 'Brimstone Grasp Hard Leather Boots of Rage +1', value: 'Brimstone Grasp Hard Leather Boots of Rage +1' },
  { label: 'Corruption Peak Demonhide Boots of the Fox +1', value: 'Corruption Peak Demonhide Boots of the Fox +1' },
  { label: 'Death Glow Studded Leather Boots of the Twins', value: 'Death Glow Studded Leather Boots of the Twins' },
  { label: 'Death Tear Studded Leather Boots of Detection', value: 'Death Tear Studded Leather Boots of Detection' },
  { label: 'Demon Bender Demonhide Boots of Perfection +1', value: 'Demon Bender Demonhide Boots of Perfection +1' },
  { label: 'Dusk Root Studded Leather Boots of Protection', value: 'Dusk Root Studded Leather Boots of Protection' },
  { label: 'Ghoul Whisper Studded Leather Boots of Titans', value: 'Ghoul Whisper Studded Leather Boots of Titans' },
  { label: 'Golem Glow Studded Leather Boots of Detection', value: 'Golem Glow Studded Leather Boots of Detection' },
  { label: 'Golem Tear Studded Leather Boots of the Twins', value: 'Golem Tear Studded Leather Boots of the Twins' },
  { label: 'Grim Bender Silk Slippers of Enlightenment +1', value: 'Grim Bender Silk Slippers of Enlightenment +1' },
  { label: 'Havoc Glow Studded Leather Boots of Detection', value: 'Havoc Glow Studded Leather Boots of Detection' },
  { label: 'Havoc Sun Studded Leather Boots of Perfection', value: 'Havoc Sun Studded Leather Boots of Perfection' },
  { label: 'Hypnotic Glow Studded Leather Boots of Giants', value: 'Hypnotic Glow Studded Leather Boots of Giants' },
  { label: 'Kraken Shout Hard Leather Boots of Vitriol +1', value: 'Kraken Shout Hard Leather Boots of Vitriol +1' },
  { label: "Light's Roar Divine Slippers of Enlightenment", value: "Light's Roar Divine Slippers of Enlightenment" },
  { label: 'Maelstrom Sun Ornate Greaves of Enlightenment', value: 'Maelstrom Sun Ornate Greaves of Enlightenment' },
  { label: 'Oblivion Moon Demonhide Boots of the Twins +1', value: 'Oblivion Moon Demonhide Boots of the Twins +1' },
  { label: 'Oblivion Shout Hard Leather Boots of Skill +1', value: 'Oblivion Shout Hard Leather Boots of Skill +1' },
  { label: 'Apocalypse Glow Divine Slippers of Detection', value: 'Apocalypse Glow Divine Slippers of Detection' },
  { label: 'Apocalypse Tear Ornate Greaves of Protection', value: 'Apocalypse Tear Ornate Greaves of Protection' },
  { label: 'Blight Bite Demonhide Boots of Perfection +1', value: 'Blight Bite Demonhide Boots of Perfection +1' },
  { label: 'Blight Grasp Demonhide Boots of Detection +1', value: 'Blight Grasp Demonhide Boots of Detection +1' },
  { label: 'Blight Grasp Hard Leather Boots of Giants +1', value: 'Blight Grasp Hard Leather Boots of Giants +1' },
  { label: 'Bramble Whisper Ornate Greaves of Perfection', value: 'Bramble Whisper Ornate Greaves of Perfection' },
  { label: 'Carrion Whisper Linen Shoes of Enlightenment', value: 'Carrion Whisper Linen Shoes of Enlightenment' },
  { label: 'Cataclysm Bender Silk Slippers of the Fox +1', value: 'Cataclysm Bender Silk Slippers of the Fox +1' },
  { label: 'Corruption Shout Silk Slippers of Vitriol +1', value: 'Corruption Shout Silk Slippers of Vitriol +1' },
  { label: 'Demon Shout Demonhide Boots of Protection +1', value: 'Demon Shout Demonhide Boots of Protection +1' },
  { label: 'Demon Shout Hard Leather Boots of Vitriol +1', value: 'Demon Shout Hard Leather Boots of Vitriol +1' },
  { label: 'Dragon Roar Divine Slippers of Enlightenment', value: 'Dragon Roar Divine Slippers of Enlightenment' },
  { label: 'Dread Grasp Hard Leather Boots of Vitriol +1', value: 'Dread Grasp Hard Leather Boots of Vitriol +1' },
  { label: 'Dread Shout Demonhide Boots of Protection +1', value: 'Dread Shout Demonhide Boots of Protection +1' },
  { label: 'Dusk Glow Studded Leather Boots of Detection', value: 'Dusk Glow Studded Leather Boots of Detection' },
  { label: 'Dusk Tear Studded Leather Boots of the Twins', value: 'Dusk Tear Studded Leather Boots of the Twins' },
  { label: 'Foe Grasp Hard Leather Boots of the Twins +1', value: 'Foe Grasp Hard Leather Boots of the Twins +1' },
  { label: 'Foe Peak Hard Leather Boots of Reflection +1', value: 'Foe Peak Hard Leather Boots of Reflection +1' },
  { label: 'Gloom Bite Silk Slippers of Enlightenment +1', value: 'Gloom Bite Silk Slippers of Enlightenment +1' },
  { label: 'Grim Bender Demonhide Boots of Perfection +1', value: 'Grim Bender Demonhide Boots of Perfection +1' },
  { label: 'Havoc Whisper Studded Leather Boots of Anger', value: 'Havoc Whisper Studded Leather Boots of Anger' },
  { label: 'Honour Grasp Demonhide Boots of the Twins +1', value: 'Honour Grasp Demonhide Boots of the Twins +1' },
  { label: 'Honour Moon Demonhide Boots of Protection +1', value: 'Honour Moon Demonhide Boots of Protection +1' },
  { label: 'Kraken Bender Hard Leather Boots of Anger +1', value: 'Kraken Bender Hard Leather Boots of Anger +1' },
  { label: 'Kraken Bite Demonhide Boots of Reflection +1', value: 'Kraken Bite Demonhide Boots of Reflection +1' },
  { label: 'Maelstrom Root Divine Slippers of Brilliance', value: 'Maelstrom Root Divine Slippers of Brilliance' },
  { label: 'Maelstrom Root Divine Slippers of Protection', value: 'Maelstrom Root Divine Slippers of Protection' },
  { label: 'Mind Moon Hard Leather Boots of the Twins +1', value: 'Mind Moon Hard Leather Boots of the Twins +1' },
  { label: 'Morbid Whisper Divine Slippers of Perfection', value: 'Morbid Whisper Divine Slippers of Perfection' },
  { label: 'Oblivion Bender Demonhide Boots of Titans +1', value: 'Oblivion Bender Demonhide Boots of Titans +1' },
  { label: 'Oblivion Bite Hard Leather Boots of Anger +1', value: 'Oblivion Bite Hard Leather Boots of Anger +1' },
  { label: 'Oblivion Grasp Silk Slippers of the Twins +1', value: 'Oblivion Grasp Silk Slippers of the Twins +1' },
  { label: 'Oblivion Moon Silk Slippers of Brilliance +1', value: 'Oblivion Moon Silk Slippers of Brilliance +1' },
  { label: 'Pandemonium Bite Greaves of Enlightenment +1', value: 'Pandemonium Bite Greaves of Enlightenment +1' },
  { label: 'Pandemonium Grasp Demonhide Boots of Rage +1', value: 'Pandemonium Grasp Demonhide Boots of Rage +1' },
  { label: 'Apocalypse Tear Ornate Greaves of the Twins', value: 'Apocalypse Tear Ornate Greaves of the Twins' },
  { label: 'Armageddon Shout Silk Slippers of Giants +1', value: 'Armageddon Shout Silk Slippers of Giants +1' },
  { label: 'Behemoth Glow Divine Slippers of Protection', value: 'Behemoth Glow Divine Slippers of Protection' },
  { label: 'Behemoth Glow Studded Leather Boots of Rage', value: 'Behemoth Glow Studded Leather Boots of Rage' },
  { label: 'Blight Shout Silk Slippers of Protection +1', value: 'Blight Shout Silk Slippers of Protection +1' },
  { label: 'Brimstone Grasp Silk Slippers of Vitriol +1', value: 'Brimstone Grasp Silk Slippers of Vitriol +1' },
  { label: 'Cataclysm Grasp Silk Slippers of Vitriol +1', value: 'Cataclysm Grasp Silk Slippers of Vitriol +1' },
  { label: 'Cataclysm Shout Demonhide Boots of Skill +1', value: 'Cataclysm Shout Demonhide Boots of Skill +1' },
  { label: 'Cataclysm Shout Silk Slippers of Vitriol +1', value: 'Cataclysm Shout Silk Slippers of Vitriol +1' },
  { label: 'Corpse Whisper Ornate Greaves of Reflection', value: 'Corpse Whisper Ornate Greaves of Reflection' },
  { label: 'Corruption Bender Silk Slippers of Anger +1', value: 'Corruption Bender Silk Slippers of Anger +1' },
  { label: 'Corruption Moon Silk Slippers of Vitriol +1', value: 'Corruption Moon Silk Slippers of Vitriol +1' },
  { label: 'Corruption Peak Greaves of Enlightenment +1', value: 'Corruption Peak Greaves of Enlightenment +1' },
  { label: 'Death Whisper Studded Leather Boots of Fury', value: 'Death Whisper Studded Leather Boots of Fury' },
  { label: 'Demon Bender Hard Leather Boots of Power +1', value: 'Demon Bender Hard Leather Boots of Power +1' },
  { label: 'Demon Shout Demonhide Boots of the Twins +1', value: 'Demon Shout Demonhide Boots of the Twins +1' },
  { label: 'Dragon Sun Studded Leather Boots of the Fox', value: 'Dragon Sun Studded Leather Boots of the Fox' },
  { label: 'Dragon Whisper Linen Shoes of Enlightenment', value: 'Dragon Whisper Linen Shoes of Enlightenment' },
  { label: 'Dread Grasp Demonhide Boots of the Twins +1', value: 'Dread Grasp Demonhide Boots of the Twins +1' },
  { label: 'Eagle Moon Demonhide Boots of Brilliance +1', value: 'Eagle Moon Demonhide Boots of Brilliance +1' },
  { label: 'Gloom Grasp Demonhide Boots of Detection +1', value: 'Gloom Grasp Demonhide Boots of Detection +1' },
  { label: 'Gloom Peak Hard Leather Boots of the Fox +1', value: 'Gloom Peak Hard Leather Boots of the Fox +1' },
  { label: 'Golem Tear Studded Leather Boots of Vitriol', value: 'Golem Tear Studded Leather Boots of Vitriol' },
  { label: 'Golem Whisper Divine Slippers of Reflection', value: 'Golem Whisper Divine Slippers of Reflection' },
  { label: 'Grim Shout Demonhide Boots of Brilliance +1', value: 'Grim Shout Demonhide Boots of Brilliance +1' },
  { label: 'Havoc Glow Studded Leather Boots of Vitriol', value: 'Havoc Glow Studded Leather Boots of Vitriol' },
  { label: 'Kraken Grasp Silk Slippers of Protection +1', value: 'Kraken Grasp Silk Slippers of Protection +1' },
  { label: 'Maelstrom Glow Divine Slippers of the Twins', value: 'Maelstrom Glow Divine Slippers of the Twins' },
  { label: 'Maelstrom Sun Divine Slippers of Reflection', value: 'Maelstrom Sun Divine Slippers of Reflection' },
  { label: 'Morbid Sun Divine Slippers of Enlightenment', value: 'Morbid Sun Divine Slippers of Enlightenment' },
  { label: 'Oblivion Peak Demonhide Boots of the Fox +1', value: 'Oblivion Peak Demonhide Boots of the Fox +1' },
  { label: 'Pandemonium Bender Greaves of Perfection +1', value: 'Pandemonium Bender Greaves of Perfection +1' },
  { label: 'Pandemonium Bite Demonhide Boots of Fury +1', value: 'Pandemonium Bite Demonhide Boots of Fury +1' },
  { label: 'Pandemonium Bite Silk Slippers of Titans +1', value: 'Pandemonium Bite Silk Slippers of Titans +1' },
  { label: 'Pandemonium Peak Demonhide Boots of Fury +1', value: 'Pandemonium Peak Demonhide Boots of Fury +1' },
  { label: 'Behemoth Sun Divine Slippers of Perfection', value: 'Behemoth Sun Divine Slippers of Perfection' },
  { label: 'Blight Bite Silk Slippers of Reflection +1', value: 'Blight Bite Silk Slippers of Reflection +1' },
  { label: 'Blight Grasp Silk Slippers of Detection +1', value: 'Blight Grasp Silk Slippers of Detection +1' },
  { label: 'Bramble Glow Divine Slippers of Brilliance', value: 'Bramble Glow Divine Slippers of Brilliance' },
  { label: 'Bramble Root Divine Slippers of Brilliance', value: 'Bramble Root Divine Slippers of Brilliance' },
  { label: 'Brimstone Shout Silk Slippers of Giants +1', value: 'Brimstone Shout Silk Slippers of Giants +1' },
  { label: 'Cataclysm Bender Shoes of Enlightenment +1', value: 'Cataclysm Bender Shoes of Enlightenment +1' },
  { label: 'Cataclysm Bender Silk Slippers of Anger +1', value: 'Cataclysm Bender Silk Slippers of Anger +1' },
  { label: 'Cataclysm Moon Silk Slippers of Vitriol +1', value: 'Cataclysm Moon Silk Slippers of Vitriol +1' },
  { label: 'Death Roar Studded Leather Boots of Titans', value: 'Death Roar Studded Leather Boots of Titans' },
  { label: 'Death Sun Divine Slippers of Enlightenment', value: 'Death Sun Divine Slippers of Enlightenment' },
  { label: 'Death Whisper Ornate Greaves of Reflection', value: 'Death Whisper Ornate Greaves of Reflection' },
  { label: 'Eagle Grasp Silk Slippers of Protection +1', value: 'Eagle Grasp Silk Slippers of Protection +1' },
  { label: 'Eagle Peak Hard Leather Boots of Titans +1', value: 'Eagle Peak Hard Leather Boots of Titans +1' },
  { label: 'Gloom Grasp Silk Slippers of Protection +1', value: 'Gloom Grasp Silk Slippers of Protection +1' },
  { label: 'Golem Roar Studded Leather Boots of Titans', value: 'Golem Roar Studded Leather Boots of Titans' },
  { label: 'Golem Whisper Heavy Boots of Enlightenment', value: 'Golem Whisper Heavy Boots of Enlightenment' },
  { label: 'Golem Whisper Linen Shoes of Enlightenment', value: 'Golem Whisper Linen Shoes of Enlightenment' },
  { label: 'Honour Shout Hard Leather Boots of Rage +1', value: 'Honour Shout Hard Leather Boots of Rage +1' },
  { label: 'Hypnotic Sun Studded Leather Boots of Fury', value: 'Hypnotic Sun Studded Leather Boots of Fury' },
  { label: 'Hypnotic Tear Ornate Greaves of Protection', value: 'Hypnotic Tear Ornate Greaves of Protection' },
  { label: 'Kraken Shout Demonhide Boots of Vitriol +1', value: 'Kraken Shout Demonhide Boots of Vitriol +1' },
  { label: "Light's Tear Studded Leather Boots of Rage", value: "Light's Tear Studded Leather Boots of Rage" },
  { label: 'Maelstrom Glow Ornate Greaves of the Twins', value: 'Maelstrom Glow Ornate Greaves of the Twins' },
  { label: 'Maelstrom Sun Ornate Greaves of Perfection', value: 'Maelstrom Sun Ornate Greaves of Perfection' },
  { label: 'Mind Shout Hard Leather Boots of Giants +1', value: 'Mind Shout Hard Leather Boots of Giants +1' },
  { label: 'Pandemonium Peak Silk Slippers of Power +1', value: 'Pandemonium Peak Silk Slippers of Power +1' },
  { label: 'Apocalypse Roar Divine Slippers of Titans', value: 'Apocalypse Roar Divine Slippers of Titans' },
  { label: 'Apocalypse Root Linen Shoes of Protection', value: 'Apocalypse Root Linen Shoes of Protection' },
  { label: 'Apocalypse Tear Linen Shoes of Brilliance', value: 'Apocalypse Tear Linen Shoes of Brilliance' },
  { label: 'Behemoth Sun Ornate Greaves of Reflection', value: 'Behemoth Sun Ornate Greaves of Reflection' },
  { label: 'Blight Peak Demonhide Boots of the Fox +1', value: 'Blight Peak Demonhide Boots of the Fox +1' },
  { label: 'Bramble Glow Divine Slippers of the Twins', value: 'Bramble Glow Divine Slippers of the Twins' },
  { label: 'Bramble Tear Divine Slippers of the Twins', value: 'Bramble Tear Divine Slippers of the Twins' },
  { label: 'Bramble Tear Ornate Greaves of Protection', value: 'Bramble Tear Ornate Greaves of Protection' },
  { label: 'Brimstone Peak Silk Slippers of Titans +1', value: 'Brimstone Peak Silk Slippers of Titans +1' },
  { label: 'Carrion Glow Ornate Greaves of Protection', value: 'Carrion Glow Ornate Greaves of Protection' },
  { label: 'Carrion Whisper Heavy Boots of Perfection', value: 'Carrion Whisper Heavy Boots of Perfection' },
  { label: 'Carrion Whisper Linen Shoes of Perfection', value: 'Carrion Whisper Linen Shoes of Perfection' },
  { label: 'Carrion Whisper Ornate Greaves of the Fox', value: 'Carrion Whisper Ornate Greaves of the Fox' },
  { label: 'Death Tear Studded Leather Boots of Skill', value: 'Death Tear Studded Leather Boots of Skill' },
  { label: 'Demon Bite Hard Leather Boots of Anger +1', value: 'Demon Bite Hard Leather Boots of Anger +1' },
  { label: 'Demon Moon Hard Leather Boots of Skill +1', value: 'Demon Moon Hard Leather Boots of Skill +1' },
  { label: 'Dread Shout Silk Slippers of Detection +1', value: 'Dread Shout Silk Slippers of Detection +1' },
  { label: 'Eagle Moon Silk Slippers of Protection +1', value: 'Eagle Moon Silk Slippers of Protection +1' },
  { label: 'Fate Glow Studded Leather Boots of Giants', value: 'Fate Glow Studded Leather Boots of Giants' },
  { label: 'Foe Bite Demonhide Boots of Reflection +1', value: 'Foe Bite Demonhide Boots of Reflection +1' },
  { label: 'Foe Moon Hard Leather Boots of Vitriol +1', value: 'Foe Moon Hard Leather Boots of Vitriol +1' },
  { label: 'Gloom Bite Silk Slippers of Perfection +1', value: 'Gloom Bite Silk Slippers of Perfection +1' },
  { label: 'Golem Roar Studded Leather Boots of Anger', value: 'Golem Roar Studded Leather Boots of Anger' },
  { label: 'Grim Bender Demonhide Boots of the Fox +1', value: 'Grim Bender Demonhide Boots of the Fox +1' },
  { label: 'Havoc Roar Studded Leather Boots of Power', value: 'Havoc Roar Studded Leather Boots of Power' },
  { label: 'Kraken Bender Demonhide Boots of Anger +1', value: 'Kraken Bender Demonhide Boots of Anger +1' },
  { label: "Light's Tear Divine Slippers of the Twins", value: "Light's Tear Divine Slippers of the Twins" },
  { label: "Light's Whisper Divine Slippers of Titans", value: "Light's Whisper Divine Slippers of Titans" },
  { label: 'Morbid Roar Studded Leather Boots of Fury', value: 'Morbid Roar Studded Leather Boots of Fury' },
  { label: 'Oblivion Grasp Demonhide Boots of Rage +1', value: 'Oblivion Grasp Demonhide Boots of Rage +1' },
  { label: 'Pandemonium Bite Silk Slippers of Fury +1', value: 'Pandemonium Bite Silk Slippers of Fury +1' },
  { label: 'Pandemonium Moon Silk Slippers of Rage +1', value: 'Pandemonium Moon Silk Slippers of Rage +1' },
  { label: 'Apocalypse Root Heavy Boots of the Twins', value: 'Apocalypse Root Heavy Boots of the Twins' },
  { label: 'Armageddon Bender Shoes of Perfection +1', value: 'Armageddon Bender Shoes of Perfection +1' },
  { label: 'Behemoth Glow Divine Slippers of Vitriol', value: 'Behemoth Glow Divine Slippers of Vitriol' },
  { label: 'Behemoth Whisper Divine Slippers of Fury', value: 'Behemoth Whisper Divine Slippers of Fury' },
  { label: 'Blight Grasp Silk Slippers of Vitriol +1', value: 'Blight Grasp Silk Slippers of Vitriol +1' },
  { label: 'Carrion Sun Ornate Greaves of Perfection', value: 'Carrion Sun Ornate Greaves of Perfection' },
  { label: 'Corpse Glow Ornate Greaves of Protection', value: 'Corpse Glow Ornate Greaves of Protection' },
  { label: 'Corruption Bite Greaves of Reflection +1', value: 'Corruption Bite Greaves of Reflection +1' },
  { label: 'Corruption Grasp Greaves of the Twins +1', value: 'Corruption Grasp Greaves of the Twins +1' },
  { label: 'Demon Bender Greaves of Enlightenment +1', value: 'Demon Bender Greaves of Enlightenment +1' },
  { label: 'Dread Bender Greaves of Enlightenment +1', value: 'Dread Bender Greaves of Enlightenment +1' },
  { label: 'Ghoul Roar Divine Slippers of Reflection', value: 'Ghoul Roar Divine Slippers of Reflection' },
  { label: 'Gloom Moon Hard Leather Boots of Rage +1', value: 'Gloom Moon Hard Leather Boots of Rage +1' },
  { label: 'Gloom Peak Demonhide Boots of the Fox +1', value: 'Gloom Peak Demonhide Boots of the Fox +1' },
  { label: 'Golem Sun Studded Leather Boots of Anger', value: 'Golem Sun Studded Leather Boots of Anger' },
  { label: 'Honour Bender Demonhide Boots of Fury +1', value: 'Honour Bender Demonhide Boots of Fury +1' },
  { label: 'Honour Bite Demonhide Boots of Titans +1', value: 'Honour Bite Demonhide Boots of Titans +1' },
  { label: 'Hypnotic Roar Divine Slippers of the Fox', value: 'Hypnotic Roar Divine Slippers of the Fox' },
  { label: 'Kraken Bender Silk Slippers of Titans +1', value: 'Kraken Bender Silk Slippers of Titans +1' },
  { label: "Light's Sun Ornate Greaves of Perfection", value: "Light's Sun Ornate Greaves of Perfection" },
  { label: "Light's Tear Ornate Greaves of Detection", value: "Light's Tear Ornate Greaves of Detection" },
  { label: 'Maelstrom Glow Heavy Boots of Protection', value: 'Maelstrom Glow Heavy Boots of Protection' },
  { label: 'Maelstrom Tear Linen Shoes of Brilliance', value: 'Maelstrom Tear Linen Shoes of Brilliance' },
  { label: 'Mind Moon Hard Leather Boots of Skill +1', value: 'Mind Moon Hard Leather Boots of Skill +1' },
  { label: 'Morbid Root Ornate Greaves of Brilliance', value: 'Morbid Root Ornate Greaves of Brilliance' },
  { label: 'Morbid Sun Divine Slippers of Reflection', value: 'Morbid Sun Divine Slippers of Reflection' },
  { label: 'Apocalypse Whisper Heavy Boots of Anger', value: 'Apocalypse Whisper Heavy Boots of Anger' },
  { label: 'Armageddon Moon Greaves of Detection +1', value: 'Armageddon Moon Greaves of Detection +1' },
  { label: 'Behemoth Root Heavy Boots of Protection', value: 'Behemoth Root Heavy Boots of Protection' },
  { label: 'Bramble Whisper Ornate Greaves of Power', value: 'Bramble Whisper Ornate Greaves of Power' },
  { label: 'Brimstone Grasp Greaves of Detection +1', value: 'Brimstone Grasp Greaves of Detection +1' },
  { label: 'Carrion Root Divine Slippers of Vitriol', value: 'Carrion Root Divine Slippers of Vitriol' },
  { label: 'Cataclysm Bender Shoes of Reflection +1', value: 'Cataclysm Bender Shoes of Reflection +1' },
  { label: 'Death Root Ornate Greaves of Protection', value: 'Death Root Ornate Greaves of Protection' },
  { label: 'Demon Shout Silk Slippers of Vitriol +1', value: 'Demon Shout Silk Slippers of Vitriol +1' },
  { label: 'Dread Grasp Silk Slippers of Vitriol +1', value: 'Dread Grasp Silk Slippers of Vitriol +1' },
  { label: 'Dread Shout Demonhide Boots of Skill +1', value: 'Dread Shout Demonhide Boots of Skill +1' },
  { label: 'Dusk Sun Studded Leather Boots of Power', value: 'Dusk Sun Studded Leather Boots of Power' },
  { label: 'Eagle Bite Demonhide Boots of Titans +1', value: 'Eagle Bite Demonhide Boots of Titans +1' },
  { label: 'Fate Sun Studded Leather Boots of Power', value: 'Fate Sun Studded Leather Boots of Power' },
  { label: 'Foe Grasp Silk Slippers of the Twins +1', value: 'Foe Grasp Silk Slippers of the Twins +1' },
  { label: 'Ghoul Roar Ornate Greaves of Perfection', value: 'Ghoul Roar Ornate Greaves of Perfection' },
  { label: 'Gloom Bite Demonhide Boots of Titans +1', value: 'Gloom Bite Demonhide Boots of Titans +1' },
  { label: 'Golem Glow Divine Slippers of Detection', value: 'Golem Glow Divine Slippers of Detection' },
  { label: 'Havoc Glow Divine Slippers of Detection', value: 'Havoc Glow Divine Slippers of Detection' },
  { label: 'Havoc Root Divine Slippers of the Twins', value: 'Havoc Root Divine Slippers of the Twins' },
  { label: 'Havoc Sun Divine Slippers of Perfection', value: 'Havoc Sun Divine Slippers of Perfection' },
  { label: 'Havoc Whisper Linen Shoes of Perfection', value: 'Havoc Whisper Linen Shoes of Perfection' },
  { label: 'Honour Bite Greaves of Enlightenment +1', value: 'Honour Bite Greaves of Enlightenment +1' },
  { label: 'Honour Grasp Demonhide Boots of Rage +1', value: 'Honour Grasp Demonhide Boots of Rage +1' },
  { label: 'Hypnotic Root Heavy Boots of Brilliance', value: 'Hypnotic Root Heavy Boots of Brilliance' },
  { label: 'Hypnotic Root Linen Shoes of Brilliance', value: 'Hypnotic Root Linen Shoes of Brilliance' },
  { label: 'Kraken Bite Silk Slippers of the Fox +1', value: 'Kraken Bite Silk Slippers of the Fox +1' },
  { label: 'Kraken Shout Silk Slippers of Giants +1', value: 'Kraken Shout Silk Slippers of Giants +1' },
  { label: "Light's Root Divine Slippers of Vitriol", value: "Light's Root Divine Slippers of Vitriol" },
  { label: 'Maelstrom Roar Divine Slippers of Power', value: 'Maelstrom Roar Divine Slippers of Power' },
  { label: 'Morbid Sun Ornate Greaves of Perfection', value: 'Morbid Sun Ornate Greaves of Perfection' },
  { label: 'Morbid Tear Ornate Greaves of Detection', value: 'Morbid Tear Ornate Greaves of Detection' },
  { label: 'Pain Sun Studded Leather Boots of Anger', value: 'Pain Sun Studded Leather Boots of Anger' },
  { label: 'Pandemonium Bite Shoes of Perfection +1', value: 'Pandemonium Bite Shoes of Perfection +1' },
  { label: 'Apocalypse Root Heavy Boots of Vitriol', value: 'Apocalypse Root Heavy Boots of Vitriol' },
  { label: 'Apocalypse Sun Divine Slippers of Fury', value: 'Apocalypse Sun Divine Slippers of Fury' },
  { label: 'Apocalypse Whisper Heavy Boots of Fury', value: 'Apocalypse Whisper Heavy Boots of Fury' },
  { label: 'Armageddon Grasp Greaves of Vitriol +1', value: 'Armageddon Grasp Greaves of Vitriol +1' },
  { label: 'Armageddon Moon Shoes of Brilliance +1', value: 'Armageddon Moon Shoes of Brilliance +1' },
  { label: 'Armageddon Moon Shoes of Protection +1', value: 'Armageddon Moon Shoes of Protection +1' },
  { label: 'Behemoth Sun Linen Shoes of Reflection', value: 'Behemoth Sun Linen Shoes of Reflection' },
  { label: 'Blight Bender Silk Slippers of Fury +1', value: 'Blight Bender Silk Slippers of Fury +1' },
  { label: 'Bramble Roar Divine Slippers of Titans', value: 'Bramble Roar Divine Slippers of Titans' },
  { label: 'Bramble Root Divine Slippers of Giants', value: 'Bramble Root Divine Slippers of Giants' },
  { label: 'Bramble Tear Linen Shoes of Protection', value: 'Bramble Tear Linen Shoes of Protection' },
  { label: 'Bramble Whisper Heavy Boots of the Fox', value: 'Bramble Whisper Heavy Boots of the Fox' },
  { label: 'Brimstone Bender Greaves of the Fox +1', value: 'Brimstone Bender Greaves of the Fox +1' },
  { label: 'Carrion Root Heavy Boots of Protection', value: 'Carrion Root Heavy Boots of Protection' },
  { label: 'Corpse Roar Divine Slippers of the Fox', value: 'Corpse Roar Divine Slippers of the Fox' },
  { label: 'Corpse Whisper Divine Slippers of Fury', value: 'Corpse Whisper Divine Slippers of Fury' },
  { label: 'Corruption Shout Shoes of the Twins +1', value: 'Corruption Shout Shoes of the Twins +1' },
  { label: 'Death Glow Ornate Greaves of Detection', value: 'Death Glow Ornate Greaves of Detection' },
  { label: 'Death Root Ornate Greaves of Detection', value: 'Death Root Ornate Greaves of Detection' },
  { label: 'Death Sun Heavy Boots of Enlightenment', value: 'Death Sun Heavy Boots of Enlightenment' },
  { label: 'Death Whisper Divine Slippers of Anger', value: 'Death Whisper Divine Slippers of Anger' },
  { label: 'Demon Grasp Silk Slippers of Giants +1', value: 'Demon Grasp Silk Slippers of Giants +1' },
  { label: 'Dragon Roar Divine Slippers of the Fox', value: 'Dragon Roar Divine Slippers of the Fox' },
  { label: 'Dread Bite Demonhide Boots of Anger +1', value: 'Dread Bite Demonhide Boots of Anger +1' },
  { label: 'Dusk Glow Divine Slippers of the Twins', value: 'Dusk Glow Divine Slippers of the Twins' },
  { label: 'Eagle Bender Silk Slippers of Anger +1', value: 'Eagle Bender Silk Slippers of Anger +1' },
  { label: 'Eagle Shout Demonhide Boots of Rage +1', value: 'Eagle Shout Demonhide Boots of Rage +1' },
  { label: 'Fate Roar Ornate Greaves of Perfection', value: 'Fate Roar Ornate Greaves of Perfection' },
  { label: 'Fate Whisper Ornate Greaves of the Fox', value: 'Fate Whisper Ornate Greaves of the Fox' },
  { label: 'Foe Bite Demonhide Boots of the Fox +1', value: 'Foe Bite Demonhide Boots of the Fox +1' },
  { label: 'Foe Peak Demonhide Boots of the Fox +1', value: 'Foe Peak Demonhide Boots of the Fox +1' },
  { label: 'Ghoul Whisper Divine Slippers of Anger', value: 'Ghoul Whisper Divine Slippers of Anger' },
  { label: 'Gloom Bender Silk Slippers of Anger +1', value: 'Gloom Bender Silk Slippers of Anger +1' },
  { label: 'Golem Whisper Divine Slippers of Anger', value: 'Golem Whisper Divine Slippers of Anger' },
  { label: 'Grim Shout Silk Slippers of Vitriol +1', value: 'Grim Shout Silk Slippers of Vitriol +1' },
  { label: 'Honour Peak Demonhide Boots of Fury +1', value: 'Honour Peak Demonhide Boots of Fury +1' },
  { label: "Light's Root Ornate Greaves of Vitriol", value: "Light's Root Ornate Greaves of Vitriol" },
  { label: "Light's Tear Heavy Boots of Protection", value: "Light's Tear Heavy Boots of Protection" },
  { label: 'Maelstrom Tear Divine Slippers of Rage', value: 'Maelstrom Tear Divine Slippers of Rage' },
  { label: 'Mind Bite Demonhide Boots of Titans +1', value: 'Mind Bite Demonhide Boots of Titans +1' },
  { label: 'Mind Grasp Demonhide Boots of Skill +1', value: 'Mind Grasp Demonhide Boots of Skill +1' },
  { label: 'Morbid Whisper Divine Slippers of Fury', value: 'Morbid Whisper Divine Slippers of Fury' },
  { label: 'Pandemonium Bender Greaves of Power +1', value: 'Pandemonium Bender Greaves of Power +1' },
  { label: 'Pandemonium Peak Greaves of the Fox +1', value: 'Pandemonium Peak Greaves of the Fox +1' },
  { label: 'Armageddon Peak Greaves of the Fox +1', value: 'Armageddon Peak Greaves of the Fox +1' },
  { label: 'Behemoth Roar Divine Slippers of Fury', value: 'Behemoth Roar Divine Slippers of Fury' },
  { label: 'Bramble Sun Linen Shoes of Reflection', value: 'Bramble Sun Linen Shoes of Reflection' },
  { label: 'Brimstone Shout Shoes of Detection +1', value: 'Brimstone Shout Shoes of Detection +1' },
  { label: 'Carrion Tear Heavy Boots of the Twins', value: 'Carrion Tear Heavy Boots of the Twins' },
  { label: 'Carrion Tear Linen Shoes of Detection', value: 'Carrion Tear Linen Shoes of Detection' },
  { label: 'Corpse Roar Linen Shoes of Perfection', value: 'Corpse Roar Linen Shoes of Perfection' },
  { label: 'Corpse Tear Linen Shoes of Brilliance', value: 'Corpse Tear Linen Shoes of Brilliance' },
  { label: 'Corpse Whisper Heavy Boots of the Fox', value: 'Corpse Whisper Heavy Boots of the Fox' },
  { label: 'Demon Grasp Silk Slippers of Skill +1', value: 'Demon Grasp Silk Slippers of Skill +1' },
  { label: 'Dragon Glow Linen Shoes of Brilliance', value: 'Dragon Glow Linen Shoes of Brilliance' },
  { label: 'Dragon Root Heavy Boots of Protection', value: 'Dragon Root Heavy Boots of Protection' },
  { label: 'Eagle Bite Demonhide Boots of Fury +1', value: 'Eagle Bite Demonhide Boots of Fury +1' },
  { label: 'Eagle Moon Silk Slippers of Giants +1', value: 'Eagle Moon Silk Slippers of Giants +1' },
  { label: 'Eagle Peak Silk Slippers of Titans +1', value: 'Eagle Peak Silk Slippers of Titans +1' },
  { label: 'Foe Shout Demonhide Boots of Skill +1', value: 'Foe Shout Demonhide Boots of Skill +1' },
  { label: 'Golem Glow Divine Slippers of Vitriol', value: 'Golem Glow Divine Slippers of Vitriol' },
  { label: 'Grim Bite Demonhide Boots of Anger +1', value: 'Grim Bite Demonhide Boots of Anger +1' },
  { label: 'Grim Grasp Silk Slippers of Giants +1', value: 'Grim Grasp Silk Slippers of Giants +1' },
  { label: 'Kraken Bite Shoes of Enlightenment +1', value: 'Kraken Bite Shoes of Enlightenment +1' },
  { label: "Light's Root Linen Shoes of the Twins", value: "Light's Root Linen Shoes of the Twins" },
  { label: "Light's Tear Ornate Greaves of Giants", value: "Light's Tear Ornate Greaves of Giants" },
  { label: 'Maelstrom Glow Ornate Greaves of Rage', value: 'Maelstrom Glow Ornate Greaves of Rage' },
  { label: 'Mind Grasp Silk Slippers of Giants +1', value: 'Mind Grasp Silk Slippers of Giants +1' },
  { label: 'Mind Moon Silk Slippers of Vitriol +1', value: 'Mind Moon Silk Slippers of Vitriol +1' },
  { label: 'Mind Peak Demonhide Boots of Anger +1', value: 'Mind Peak Demonhide Boots of Anger +1' },
  { label: 'Morbid Roar Linen Shoes of Perfection', value: 'Morbid Roar Linen Shoes of Perfection' },
  { label: 'Oblivion Grasp Shoes of Protection +1', value: 'Oblivion Grasp Shoes of Protection +1' },
  { label: 'Pandemonium Bender Greaves of Fury +1', value: 'Pandemonium Bender Greaves of Fury +1' },
  { label: 'Pandemonium Grasp Greaves of Skill +1', value: 'Pandemonium Grasp Greaves of Skill +1' },
  { label: 'Blight Bite Silk Slippers of Fury +1', value: 'Blight Bite Silk Slippers of Fury +1' },
  { label: 'Bramble Roar Ornate Greaves of Power', value: 'Bramble Roar Ornate Greaves of Power' },
  { label: 'Corruption Peak Greaves of Titans +1', value: 'Corruption Peak Greaves of Titans +1' },
  { label: 'Demon Bite Silk Slippers of Power +1', value: 'Demon Bite Silk Slippers of Power +1' },
  { label: 'Dragon Whisper Linen Shoes of Titans', value: 'Dragon Whisper Linen Shoes of Titans' },
  { label: 'Dread Shout Greaves of Protection +1', value: 'Dread Shout Greaves of Protection +1' },
  { label: 'Dusk Whisper Ornate Greaves of Power', value: 'Dusk Whisper Ornate Greaves of Power' },
  { label: 'Eagle Peak Silk Slippers of Power +1', value: 'Eagle Peak Silk Slippers of Power +1' },
  { label: 'Foe Moon Demonhide Boots of Skill +1', value: 'Foe Moon Demonhide Boots of Skill +1' },
  { label: 'Foe Moon Silk Slippers of Vitriol +1', value: 'Foe Moon Silk Slippers of Vitriol +1' },
  { label: 'Gloom Peak Shoes of Enlightenment +1', value: 'Gloom Peak Shoes of Enlightenment +1' },
  { label: 'Golem Sun Divine Slippers of the Fox', value: 'Golem Sun Divine Slippers of the Fox' },
  { label: 'Havoc Roar Heavy Boots of Perfection', value: 'Havoc Roar Heavy Boots of Perfection' },
  { label: 'Havoc Root Linen Shoes of Protection', value: 'Havoc Root Linen Shoes of Protection' },
  { label: 'Honour Bender Shoes of Perfection +1', value: 'Honour Bender Shoes of Perfection +1' },
  { label: 'Honour Peak Silk Slippers of Fury +1', value: 'Honour Peak Silk Slippers of Fury +1' },
  { label: 'Hypnotic Roar Linen Shoes of the Fox', value: 'Hypnotic Roar Linen Shoes of the Fox' },
  { label: 'Hypnotic Root Heavy Boots of Vitriol', value: 'Hypnotic Root Heavy Boots of Vitriol' },
  { label: 'Maelstrom Roar Linen Shoes of Titans', value: 'Maelstrom Roar Linen Shoes of Titans' },
  { label: 'Morbid Glow Divine Slippers of Skill', value: 'Morbid Glow Divine Slippers of Skill' },
  { label: 'Morbid Glow Heavy Boots of Detection', value: 'Morbid Glow Heavy Boots of Detection' },
  { label: 'Pandemonium Grasp Shoes of Giants +1', value: 'Pandemonium Grasp Shoes of Giants +1' },
  { label: 'Armageddon Bender Shoes of Power +1', value: 'Armageddon Bender Shoes of Power +1' },
  { label: 'Armageddon Moon Shoes of Vitriol +1', value: 'Armageddon Moon Shoes of Vitriol +1' },
  { label: 'Brimstone Bender Greaves of Fury +1', value: 'Brimstone Bender Greaves of Fury +1' },
  { label: 'Brimstone Shout Shoes of Vitriol +1', value: 'Brimstone Shout Shoes of Vitriol +1' },
  { label: 'Carrion Tear Linen Shoes of Vitriol', value: 'Carrion Tear Linen Shoes of Vitriol' },
  { label: 'Death Root Heavy Boots of Detection', value: 'Death Root Heavy Boots of Detection' },
  { label: 'Death Sun Heavy Boots of Perfection', value: 'Death Sun Heavy Boots of Perfection' },
  { label: 'Demon Bite Greaves of Reflection +1', value: 'Demon Bite Greaves of Reflection +1' },
  { label: 'Demon Peak Greaves of Reflection +1', value: 'Demon Peak Greaves of Reflection +1' },
  { label: 'Dragon Whisper Linen Shoes of Anger', value: 'Dragon Whisper Linen Shoes of Anger' },
  { label: 'Dread Bite Silk Slippers of Fury +1', value: 'Dread Bite Silk Slippers of Fury +1' },
  { label: 'Dread Grasp Greaves of the Twins +1', value: 'Dread Grasp Greaves of the Twins +1' },
  { label: 'Dread Moon Greaves of Protection +1', value: 'Dread Moon Greaves of Protection +1' },
  { label: 'Dusk Glow Heavy Boots of Brilliance', value: 'Dusk Glow Heavy Boots of Brilliance' },
  { label: 'Eagle Peak Greaves of Reflection +1', value: 'Eagle Peak Greaves of Reflection +1' },
  { label: 'Fate Glow Heavy Boots of Protection', value: 'Fate Glow Heavy Boots of Protection' },
  { label: 'Fate Glow Linen Shoes of Brilliance', value: 'Fate Glow Linen Shoes of Brilliance' },
  { label: 'Ghoul Glow Divine Slippers of Skill', value: 'Ghoul Glow Divine Slippers of Skill' },
  { label: 'Ghoul Sun Heavy Boots of Reflection', value: 'Ghoul Sun Heavy Boots of Reflection' },
  { label: 'Gloom Bender Shoes of Reflection +1', value: 'Gloom Bender Shoes of Reflection +1' },
  { label: 'Grim Grasp Greaves of Brilliance +1', value: 'Grim Grasp Greaves of Brilliance +1' },
  { label: 'Honour Grasp Shoes of Protection +1', value: 'Honour Grasp Shoes of Protection +1' },
  { label: 'Hypnotic Root Heavy Boots of Giants', value: 'Hypnotic Root Heavy Boots of Giants' },
  { label: 'Kraken Shout Shoes of Protection +1', value: 'Kraken Shout Shoes of Protection +1' },
  { label: 'Mind Grasp Greaves of Brilliance +1', value: 'Mind Grasp Greaves of Brilliance +1' },
  { label: 'Mind Peak Silk Slippers of Anger +1', value: 'Mind Peak Silk Slippers of Anger +1' },
  { label: 'Morbid Glow Ornate Greaves of Skill', value: 'Morbid Glow Ornate Greaves of Skill' },
  { label: 'Behemoth Roar Linen Shoes of Anger', value: 'Behemoth Roar Linen Shoes of Anger' },
  { label: 'Blight Peak Shoes of Reflection +1', value: 'Blight Peak Shoes of Reflection +1' },
  { label: 'Blight Shout Greaves of Vitriol +1', value: 'Blight Shout Greaves of Vitriol +1' },
  { label: 'Bramble Roar Heavy Boots of Titans', value: 'Bramble Roar Heavy Boots of Titans' },
  { label: 'Cataclysm Peak Greaves of Power +1', value: 'Cataclysm Peak Greaves of Power +1' },
  { label: 'Corpse Glow Linen Shoes of Vitriol', value: 'Corpse Glow Linen Shoes of Vitriol' },
  { label: 'Corpse Tear Linen Shoes of Vitriol', value: 'Corpse Tear Linen Shoes of Vitriol' },
  { label: 'Corruption Bender Shoes of Fury +1', value: 'Corruption Bender Shoes of Fury +1' },
  { label: 'Corruption Moon Shoes of Giants +1', value: 'Corruption Moon Shoes of Giants +1' },
  { label: 'Corruption Peak Shoes of Titans +1', value: 'Corruption Peak Shoes of Titans +1' },
  { label: 'Death Root Ornate Greaves of Skill', value: 'Death Root Ornate Greaves of Skill' },
  { label: 'Death Sun Ornate Greaves of Titans', value: 'Death Sun Ornate Greaves of Titans' },
  { label: 'Dragon Root Ornate Greaves of Rage', value: 'Dragon Root Ornate Greaves of Rage' },
  { label: 'Eagle Moon Greaves of the Twins +1', value: 'Eagle Moon Greaves of the Twins +1' },
  { label: 'Fate Sun Heavy Boots of Perfection', value: 'Fate Sun Heavy Boots of Perfection' },
  { label: 'Fate Sun Linen Shoes of Reflection', value: 'Fate Sun Linen Shoes of Reflection' },
  { label: 'Fate Whisper Linen Shoes of Titans', value: 'Fate Whisper Linen Shoes of Titans' },
  { label: 'Foe Bite Silk Slippers of Anger +1', value: 'Foe Bite Silk Slippers of Anger +1' },
  { label: 'Ghoul Glow Ornate Greaves of Skill', value: 'Ghoul Glow Ornate Greaves of Skill' },
  { label: 'Grim Bite Greaves of Reflection +1', value: 'Grim Bite Greaves of Reflection +1' },
  { label: 'Grim Grasp Greaves of Detection +1', value: 'Grim Grasp Greaves of Detection +1' },
  { label: 'Hypnotic Sun Linen Shoes of Titans', value: 'Hypnotic Sun Linen Shoes of Titans' },
  { label: 'Kraken Grasp Greaves of Vitriol +1', value: 'Kraken Grasp Greaves of Vitriol +1' },
  { label: 'Kraken Moon Shoes of Brilliance +1', value: 'Kraken Moon Shoes of Brilliance +1' },
  { label: 'Mind Bender Shoes of Perfection +1', value: 'Mind Bender Shoes of Perfection +1' },
  { label: 'Morbid Sun Ornate Greaves of Anger', value: 'Morbid Sun Ornate Greaves of Anger' },
  { label: 'Oblivion Peak Greaves of Titans +1', value: 'Oblivion Peak Greaves of Titans +1' },
  { label: 'Pain Roar Divine Slippers of Power', value: 'Pain Roar Divine Slippers of Power' },
  { label: 'Bramble Roar Heavy Boots of Power', value: 'Bramble Roar Heavy Boots of Power' },
  { label: 'Bramble Root Heavy Boots of Skill', value: 'Bramble Root Heavy Boots of Skill' },
  { label: 'Carrion Roar Heavy Boots of Anger', value: 'Carrion Roar Heavy Boots of Anger' },
  { label: 'Carrion Sun Linen Shoes of Titans', value: 'Carrion Sun Linen Shoes of Titans' },
  { label: 'Corruption Grasp Shoes of Rage +1', value: 'Corruption Grasp Shoes of Rage +1' },
  { label: 'Death Root Heavy Boots of Vitriol', value: 'Death Root Heavy Boots of Vitriol' },
  { label: 'Demon Moon Shoes of Brilliance +1', value: 'Demon Moon Shoes of Brilliance +1' },
  { label: 'Demon Peak Shoes of Perfection +1', value: 'Demon Peak Shoes of Perfection +1' },
  { label: 'Dusk Roar Ornate Greaves of Power', value: 'Dusk Roar Ornate Greaves of Power' },
  { label: 'Dusk Sun Divine Slippers of Anger', value: 'Dusk Sun Divine Slippers of Anger' },
  { label: 'Dusk Whisper Linen Shoes of Anger', value: 'Dusk Whisper Linen Shoes of Anger' },
  { label: 'Fate Roar Divine Slippers of Fury', value: 'Fate Roar Divine Slippers of Fury' },
  { label: 'Foe Bite Greaves of Perfection +1', value: 'Foe Bite Greaves of Perfection +1' },
  { label: 'Golem Sun Ornate Greaves of Power', value: 'Golem Sun Ornate Greaves of Power' },
  { label: 'Hypnotic Roar Linen Shoes of Fury', value: 'Hypnotic Roar Linen Shoes of Fury' },
  { label: 'Hypnotic Tear Heavy Boots of Rage', value: 'Hypnotic Tear Heavy Boots of Rage' },
  { label: "Light's Glow Heavy Boots of Skill", value: "Light's Glow Heavy Boots of Skill" },
  { label: "Light's Glow Linen Shoes of Skill", value: "Light's Glow Linen Shoes of Skill" },
  { label: "Light's Roar Linen Shoes of Power", value: "Light's Roar Linen Shoes of Power" },
  { label: 'Pain Sun Divine Slippers of Anger', value: 'Pain Sun Divine Slippers of Anger' },
  { label: 'Armageddon Peak Shoes of Fury +1', value: 'Armageddon Peak Shoes of Fury +1' },
  { label: 'Brimstone Moon Shoes of Skill +1', value: 'Brimstone Moon Shoes of Skill +1' },
  { label: 'Carrion Sun Heavy Boots of Anger', value: 'Carrion Sun Heavy Boots of Anger' },
  { label: 'Carrion Sun Heavy Boots of Power', value: 'Carrion Sun Heavy Boots of Power' },
  { label: 'Corpse Roar Heavy Boots of Power', value: 'Corpse Roar Heavy Boots of Power' },
  { label: 'Corpse Roar Linen Shoes of Power', value: 'Corpse Roar Linen Shoes of Power' },
  { label: 'Demon Bender Greaves of Anger +1', value: 'Demon Bender Greaves of Anger +1' },
  { label: 'Dragon Roar Linen Shoes of Anger', value: 'Dragon Roar Linen Shoes of Anger' },
  { label: 'Dread Shout Greaves of Giants +1', value: 'Dread Shout Greaves of Giants +1' },
  { label: 'Eagle Bite Greaves of the Fox +1', value: 'Eagle Bite Greaves of the Fox +1' },
  { label: 'Eagle Peak Greaves of the Fox +1', value: 'Eagle Peak Greaves of the Fox +1' },
  { label: 'Fate Root Ornate Greaves of Rage', value: 'Fate Root Ornate Greaves of Rage' },
  { label: 'Ghoul Sun Heavy Boots of the Fox', value: 'Ghoul Sun Heavy Boots of the Fox' },
  { label: 'Ghoul Sun Linen Shoes of the Fox', value: 'Ghoul Sun Linen Shoes of the Fox' },
  { label: 'Ghoul Tear Linen Shoes of Giants', value: 'Ghoul Tear Linen Shoes of Giants' },
  { label: 'Golem Sun Linen Shoes of the Fox', value: 'Golem Sun Linen Shoes of the Fox' },
  { label: 'Morbid Roar Heavy Boots of Anger', value: 'Morbid Roar Heavy Boots of Anger' },
  { label: 'Morbid Sun Heavy Boots of Titans', value: 'Morbid Sun Heavy Boots of Titans' },
  { label: 'Pain Glow Heavy Boots of Vitriol', value: 'Pain Glow Heavy Boots of Vitriol' },
  { label: 'Pain Whisper Linen Shoes of Fury', value: 'Pain Whisper Linen Shoes of Fury' },
  { label: 'Dusk Glow Linen Shoes of Giants', value: 'Dusk Glow Linen Shoes of Giants' },
  { label: 'Eagle Peak Greaves of Titans +1', value: 'Eagle Peak Greaves of Titans +1' },
  { label: 'Foe Bender Greaves of Titans +1', value: 'Foe Bender Greaves of Titans +1' },
  { label: 'Foe Grasp Greaves of Vitriol +1', value: 'Foe Grasp Greaves of Vitriol +1' },
  { label: 'Foe Moon Shoes of Protection +1', value: 'Foe Moon Shoes of Protection +1' },
  { label: 'Foe Peak Shoes of Reflection +1', value: 'Foe Peak Shoes of Reflection +1' },
  { label: 'Golem Roar Heavy Boots of Power', value: 'Golem Roar Heavy Boots of Power' },
  { label: 'Havoc Roar Linen Shoes of Anger', value: 'Havoc Roar Linen Shoes of Anger' },
  { label: 'Havoc Sun Heavy Boots of Titans', value: 'Havoc Sun Heavy Boots of Titans' },
  { label: 'Honour Moon Greaves of Skill +1', value: 'Honour Moon Greaves of Skill +1' },
  { label: 'Honour Moon Shoes of Vitriol +1', value: 'Honour Moon Shoes of Vitriol +1' },
  { label: 'Honour Peak Greaves of Anger +1', value: 'Honour Peak Greaves of Anger +1' },
  { label: 'Mind Peak Greaves of the Fox +1', value: 'Mind Peak Greaves of the Fox +1' },
  { label: 'Corpse Sun Heavy Boots of Fury', value: 'Corpse Sun Heavy Boots of Fury' },
  { label: 'Dread Bite Shoes of the Fox +1', value: 'Dread Bite Shoes of the Fox +1' },
  { label: 'Eagle Grasp Greaves of Rage +1', value: 'Eagle Grasp Greaves of Rage +1' },
  { label: 'Eagle Peak Shoes of the Fox +1', value: 'Eagle Peak Shoes of the Fox +1' },
  { label: 'Ghoul Sun Heavy Boots of Anger', value: 'Ghoul Sun Heavy Boots of Anger' },
  { label: 'Gloom Shout Greaves of Rage +1', value: 'Gloom Shout Greaves of Rage +1' },
  { label: 'Havoc Glow Linen Shoes of Rage', value: 'Havoc Glow Linen Shoes of Rage' },
  { label: 'Havoc Root Linen Shoes of Rage', value: 'Havoc Root Linen Shoes of Rage' },
  { label: 'Pain Root Linen Shoes of Skill', value: 'Pain Root Linen Shoes of Skill' },
  { label: 'Demon Moon Greaves of Rage +1', value: 'Demon Moon Greaves of Rage +1' },
  { label: 'Demon Peak Shoes of Titans +1', value: 'Demon Peak Shoes of Titans +1' },
  { label: 'Divine Slippers of Protection', value: 'Divine Slippers of Protection' },
  { label: 'Dread Bite Shoes of Titans +1', value: 'Dread Bite Shoes of Titans +1' },
  { label: 'Dusk Glow Linen Shoes of Rage', value: 'Dusk Glow Linen Shoes of Rage' },
  { label: 'Eagle Shout Shoes of Skill +1', value: 'Eagle Shout Shoes of Skill +1' },
  { label: 'Grim Peak Greaves of Anger +1', value: 'Grim Peak Greaves of Anger +1' },
  { label: 'Havoc Sun Linen Shoes of Fury', value: 'Havoc Sun Linen Shoes of Fury' },
  { label: 'Honour Peak Shoes of Power +1', value: 'Honour Peak Shoes of Power +1' },
  { label: 'Mind Peak Greaves of Anger +1', value: 'Mind Peak Greaves of Anger +1' },
  { label: 'Demon Shout Shoes of Rage +1', value: 'Demon Shout Shoes of Rage +1' },
  { label: 'Mind Peak Greaves of Fury +1', value: 'Mind Peak Greaves of Fury +1' },
  { label: 'Pain Sun Linen Shoes of Fury', value: 'Pain Sun Linen Shoes of Fury' },
  { label: 'Demon Peak Shoes of Fury +1', value: 'Demon Peak Shoes of Fury +1' },
  { label: 'Dread Peak Shoes of Fury +1', value: 'Dread Peak Shoes of Fury +1' },
  { label: 'Eagle Moon Shoes of Rage +1', value: 'Eagle Moon Shoes of Rage +1' },
  { label: 'Foe Bite Greaves of Fury +1', value: 'Foe Bite Greaves of Fury +1' },
  { label: 'Foe Moon Greaves of Rage +1', value: 'Foe Moon Greaves of Rage +1' },
  { label: 'Mind Grasp Shoes of Rage +1', value: 'Mind Grasp Shoes of Rage +1' },
  { label: 'Ornate Greaves of Detection', value: 'Ornate Greaves of Detection' },
  { label: 'Foe Shout Shoes of Rage +1', value: 'Foe Shout Shoes of Rage +1' },
  { label: 'Demonhide Boots of Anger', value: 'Demonhide Boots of Anger' },
  { label: 'Demonhide Boots of Power', value: 'Demonhide Boots of Power' },
  { label: 'Greaves of Brilliance', value: 'Greaves of Brilliance' },
  { label: 'Linen Shoes of Fury', value: 'Linen Shoes of Fury' },
  { label: 'Pandemonium Shout Demonhide Boots of Brilliance +1', value: 'Pandemonium Shout Demonhide Boots of Brilliance +1' },
  { label: 'Pandemonium Shout Hard Leather Boots of Detection +1', value: 'Pandemonium Shout Hard Leather Boots of Detection +1' },
  { label: 'Plague Glow Ornate Greaves of Protection', value: 'Plague Glow Ornate Greaves of Protection' },
  { label: 'Plague Roar Linen Shoes of Anger', value: 'Plague Roar Linen Shoes of Anger' },
  { label: 'Plague Roar Linen Shoes of Perfection', value: 'Plague Roar Linen Shoes of Perfection' },
  { label: 'Plague Root Linen Shoes of Rage', value: 'Plague Root Linen Shoes of Rage' },
  { label: 'Plague Sun Divine Slippers of the Fox', value: 'Plague Sun Divine Slippers of the Fox' },
  { label: 'Plague Sun Linen Shoes of Enlightenment', value: 'Plague Sun Linen Shoes of Enlightenment' },
  { label: 'Plague Sun Studded Leather Boots of Perfection', value: 'Plague Sun Studded Leather Boots of Perfection' },
  { label: 'Plague Tear Heavy Boots of Brilliance', value: 'Plague Tear Heavy Boots of Brilliance' },
  { label: 'Plague Tear Heavy Boots of Skill', value: 'Plague Tear Heavy Boots of Skill' },
  { label: 'Plague Tear Linen Shoes of Giants', value: 'Plague Tear Linen Shoes of Giants' },
  { label: 'Plague Tear Linen Shoes of Protection', value: 'Plague Tear Linen Shoes of Protection' },
  { label: 'Plague Tear Ornate Greaves of Detection', value: 'Plague Tear Ornate Greaves of Detection' },
  { label: 'Plague Tear Studded Leather Boots of Protection', value: 'Plague Tear Studded Leather Boots of Protection' },
  { label: 'Plague Whisper Heavy Boots of Perfection', value: 'Plague Whisper Heavy Boots of Perfection' },
  { label: 'Plague Whisper Ornate Greaves of Enlightenment', value: 'Plague Whisper Ornate Greaves of Enlightenment' },
  { label: 'Rage Bender Greaves of the Fox +1', value: 'Rage Bender Greaves of the Fox +1' },
  { label: 'Rage Bender Shoes of Perfection +1', value: 'Rage Bender Shoes of Perfection +1' },
  { label: 'Rage Bender Shoes of Power +1', value: 'Rage Bender Shoes of Power +1' },
  { label: 'Rage Bender Shoes of Reflection +1', value: 'Rage Bender Shoes of Reflection +1' },
  { label: 'Rage Bite Demonhide Boots of Fury +1', value: 'Rage Bite Demonhide Boots of Fury +1' },
  { label: 'Rage Bite Demonhide Boots of Perfection +1', value: 'Rage Bite Demonhide Boots of Perfection +1' },
  { label: 'Rage Bite Greaves of Perfection +1', value: 'Rage Bite Greaves of Perfection +1' },
  { label: 'Rage Bite Hard Leather Boots of Power +1', value: 'Rage Bite Hard Leather Boots of Power +1' },
  { label: 'Rage Bite Silk Slippers of Titans +1', value: 'Rage Bite Silk Slippers of Titans +1' },
  { label: 'Rage Grasp Greaves of Giants +1', value: 'Rage Grasp Greaves of Giants +1' },
  { label: 'Rage Grasp Shoes of Giants +1', value: 'Rage Grasp Shoes of Giants +1' },
  { label: 'Rage Grasp Shoes of Rage +1', value: 'Rage Grasp Shoes of Rage +1' },
  { label: 'Rage Moon Hard Leather Boots of Skill +1', value: 'Rage Moon Hard Leather Boots of Skill +1' },
  { label: 'Rage Peak Greaves of Power +1', value: 'Rage Peak Greaves of Power +1' },
  { label: 'Rage Peak Hard Leather Boots of Anger +1', value: 'Rage Peak Hard Leather Boots of Anger +1' },
  { label: 'Rage Peak Hard Leather Boots of the Fox +1', value: 'Rage Peak Hard Leather Boots of the Fox +1' },
  { label: 'Rage Shout Hard Leather Boots of Protection +1', value: 'Rage Shout Hard Leather Boots of Protection +1' },
  { label: 'Rage Shout Hard Leather Boots of Vitriol +1', value: 'Rage Shout Hard Leather Boots of Vitriol +1' },
  { label: 'Rune Glow Divine Slippers of Protection', value: 'Rune Glow Divine Slippers of Protection' },
  { label: 'Rune Glow Divine Slippers of Skill', value: 'Rune Glow Divine Slippers of Skill' },
  { label: 'Rune Glow Linen Shoes of Protection', value: 'Rune Glow Linen Shoes of Protection' },
  { label: 'Rune Glow Ornate Greaves of Skill', value: 'Rune Glow Ornate Greaves of Skill' },
  { label: 'Rune Glow Studded Leather Boots of Protection', value: 'Rune Glow Studded Leather Boots of Protection' },
  { label: 'Rune Root Ornate Greaves of Brilliance', value: 'Rune Root Ornate Greaves of Brilliance' },
  { label: 'Rune Root Ornate Greaves of Skill', value: 'Rune Root Ornate Greaves of Skill' },
  { label: 'Rune Sun Divine Slippers of Perfection', value: 'Rune Sun Divine Slippers of Perfection' },
  { label: 'Rune Sun Linen Shoes of the Fox', value: 'Rune Sun Linen Shoes of the Fox' },
  { label: 'Rune Sun Ornate Greaves of Anger', value: 'Rune Sun Ornate Greaves of Anger' },
  { label: 'Rune Tear Heavy Boots of Vitriol', value: 'Rune Tear Heavy Boots of Vitriol' },
  { label: 'Rune Tear Studded Leather Boots of Skill', value: 'Rune Tear Studded Leather Boots of Skill' },
  { label: 'Rune Whisper Divine Slippers of Perfection', value: 'Rune Whisper Divine Slippers of Perfection' },
  { label: 'Shimmering Bender Shoes of Perfection +1', value: 'Shimmering Bender Shoes of Perfection +1' },
  { label: 'Shimmering Bender Silk Slippers of Fury +1', value: 'Shimmering Bender Silk Slippers of Fury +1' },
  { label: 'Shimmering Bender Silk Slippers of Perfection +1', value: 'Shimmering Bender Silk Slippers of Perfection +1' },
  { label: 'Shimmering Bite Greaves of Reflection +1', value: 'Shimmering Bite Greaves of Reflection +1' },
  { label: 'Shimmering Bite Hard Leather Boots of Fury +1', value: 'Shimmering Bite Hard Leather Boots of Fury +1' },
  { label: 'Shimmering Bite Shoes of Reflection +1', value: 'Shimmering Bite Shoes of Reflection +1' },
  { label: 'Shimmering Bite Shoes of Titans +1', value: 'Shimmering Bite Shoes of Titans +1' },
  { label: 'Shimmering Bite Silk Slippers of Enlightenment +1', value: 'Shimmering Bite Silk Slippers of Enlightenment +1' },
  { label: 'Shimmering Moon Silk Slippers of Rage +1', value: 'Shimmering Moon Silk Slippers of Rage +1' },
  { label: 'Shimmering Peak Demonhide Boots of Anger +1', value: 'Shimmering Peak Demonhide Boots of Anger +1' },
  { label: 'Shimmering Peak Demonhide Boots of Perfection +1', value: 'Shimmering Peak Demonhide Boots of Perfection +1' },
  { label: 'Shimmering Peak Demonhide Boots of Reflection +1', value: 'Shimmering Peak Demonhide Boots of Reflection +1' },
  { label: 'Shimmering Peak Demonhide Boots of Titans +1', value: 'Shimmering Peak Demonhide Boots of Titans +1' },
  { label: 'Shimmering Peak Shoes of Anger +1', value: 'Shimmering Peak Shoes of Anger +1' },
  { label: 'Shimmering Shout Hard Leather Boots of Detection +1', value: 'Shimmering Shout Hard Leather Boots of Detection +1' },
  { label: 'Shimmering Shout Silk Slippers of Skill +1', value: 'Shimmering Shout Silk Slippers of Skill +1' },
  { label: 'Skull Bender Demonhide Boots of Enlightenment +1', value: 'Skull Bender Demonhide Boots of Enlightenment +1' },
  { label: 'Skull Bender Greaves of Enlightenment +1', value: 'Skull Bender Greaves of Enlightenment +1' },
  { label: 'Skull Bender Hard Leather Boots of Power +1', value: 'Skull Bender Hard Leather Boots of Power +1' },
  { label: 'Skull Bender Shoes of Fury +1', value: 'Skull Bender Shoes of Fury +1' },
  { label: 'Skull Bite Hard Leather Boots of Perfection +1', value: 'Skull Bite Hard Leather Boots of Perfection +1' },
  { label: 'Skull Bite Hard Leather Boots of Reflection +1', value: 'Skull Bite Hard Leather Boots of Reflection +1' },
  { label: 'Skull Bite Hard Leather Boots of the Fox +1', value: 'Skull Bite Hard Leather Boots of the Fox +1' },
  { label: 'Skull Bite Silk Slippers of Reflection +1', value: 'Skull Bite Silk Slippers of Reflection +1' },
  { label: 'Skull Grasp Greaves of the Twins +1', value: 'Skull Grasp Greaves of the Twins +1' },
  { label: 'Skull Grasp Silk Slippers of Vitriol +1', value: 'Skull Grasp Silk Slippers of Vitriol +1' },
  { label: 'Skull Moon Hard Leather Boots of Protection +1', value: 'Skull Moon Hard Leather Boots of Protection +1' },
  { label: 'Skull Moon Hard Leather Boots of Skill +1', value: 'Skull Moon Hard Leather Boots of Skill +1' },
  { label: 'Skull Moon Shoes of Detection +1', value: 'Skull Moon Shoes of Detection +1' },
  { label: 'Skull Peak Hard Leather Boots of Perfection +1', value: 'Skull Peak Hard Leather Boots of Perfection +1' },
  { label: 'Skull Peak Hard Leather Boots of the Fox +1', value: 'Skull Peak Hard Leather Boots of the Fox +1' },
  { label: 'Skull Peak Shoes of Titans +1', value: 'Skull Peak Shoes of Titans +1' },
  { label: 'Skull Peak Silk Slippers of Perfection +1', value: 'Skull Peak Silk Slippers of Perfection +1' },
  { label: 'Skull Shout Demonhide Boots of Vitriol +1', value: 'Skull Shout Demonhide Boots of Vitriol +1' },
  { label: 'Skull Shout Greaves of Protection +1', value: 'Skull Shout Greaves of Protection +1' },
  { label: 'Skull Shout Hard Leather Boots of Skill +1', value: 'Skull Shout Hard Leather Boots of Skill +1' },
  { label: 'Skull Shout Shoes of Skill +1', value: 'Skull Shout Shoes of Skill +1' },
  { label: 'Skull Shout Shoes of Vitriol +1', value: 'Skull Shout Shoes of Vitriol +1' },
  { label: 'Sorrow Bender Shoes of the Fox +1', value: 'Sorrow Bender Shoes of the Fox +1' },
  { label: 'Sorrow Bender Silk Slippers of Enlightenment +1', value: 'Sorrow Bender Silk Slippers of Enlightenment +1' },
  { label: 'Sorrow Bite Shoes of Anger +1', value: 'Sorrow Bite Shoes of Anger +1' },
  { label: 'Sorrow Grasp Demonhide Boots of Detection +1', value: 'Sorrow Grasp Demonhide Boots of Detection +1' },
  { label: 'Sorrow Grasp Greaves of Giants +1', value: 'Sorrow Grasp Greaves of Giants +1' },
  { label: 'Sorrow Grasp Hard Leather Boots of Skill +1', value: 'Sorrow Grasp Hard Leather Boots of Skill +1' },
  { label: 'Sorrow Grasp Hard Leather Boots of the Twins +1', value: 'Sorrow Grasp Hard Leather Boots of the Twins +1' },
  { label: 'Sorrow Grasp Shoes of Giants +1', value: 'Sorrow Grasp Shoes of Giants +1' },
  { label: 'Sorrow Grasp Silk Slippers of the Twins +1', value: 'Sorrow Grasp Silk Slippers of the Twins +1' },
  { label: 'Sorrow Moon Demonhide Boots of Giants +1', value: 'Sorrow Moon Demonhide Boots of Giants +1' },
  { label: 'Sorrow Moon Hard Leather Boots of Rage +1', value: 'Sorrow Moon Hard Leather Boots of Rage +1' },
  { label: 'Sorrow Moon Shoes of Protection +1', value: 'Sorrow Moon Shoes of Protection +1' },
  { label: 'Sorrow Peak Shoes of Enlightenment +1', value: 'Sorrow Peak Shoes of Enlightenment +1' },
  { label: 'Sorrow Peak Shoes of Fury +1', value: 'Sorrow Peak Shoes of Fury +1' },
  { label: 'Sorrow Peak Shoes of the Fox +1', value: 'Sorrow Peak Shoes of the Fox +1' },
  { label: 'Sorrow Shout Demonhide Boots of Giants +1', value: 'Sorrow Shout Demonhide Boots of Giants +1' },
  { label: 'Sorrow Shout Demonhide Boots of Rage +1', value: 'Sorrow Shout Demonhide Boots of Rage +1' },
  { label: 'Sorrow Shout Hard Leather Boots of Protection +1', value: 'Sorrow Shout Hard Leather Boots of Protection +1' },
  { label: 'Sorrow Shout Shoes of Skill +1', value: 'Sorrow Shout Shoes of Skill +1' },
  { label: 'Soul Glow Heavy Boots of Protection', value: 'Soul Glow Heavy Boots of Protection' },
  { label: 'Soul Roar Ornate Greaves of the Fox', value: 'Soul Roar Ornate Greaves of the Fox' },
  { label: 'Soul Root Divine Slippers of Detection', value: 'Soul Root Divine Slippers of Detection' },
  { label: 'Soul Root Ornate Greaves of Protection', value: 'Soul Root Ornate Greaves of Protection' },
  { label: 'Soul Sun Heavy Boots of Reflection', value: 'Soul Sun Heavy Boots of Reflection' },
  { label: 'Soul Sun Ornate Greaves of Anger', value: 'Soul Sun Ornate Greaves of Anger' },
  { label: 'Soul Tear Heavy Boots of Giants', value: 'Soul Tear Heavy Boots of Giants' },
  { label: 'Soul Tear Linen Shoes of the Twins', value: 'Soul Tear Linen Shoes of the Twins' },
  { label: 'Storm Glow Heavy Boots of Skill', value: 'Storm Glow Heavy Boots of Skill' },
  { label: 'Storm Roar Heavy Boots of Enlightenment', value: 'Storm Roar Heavy Boots of Enlightenment' },
  { label: 'Storm Root Divine Slippers of the Twins', value: 'Storm Root Divine Slippers of the Twins' },
  { label: 'Storm Root Heavy Boots of Brilliance', value: 'Storm Root Heavy Boots of Brilliance' },
  { label: 'Storm Root Linen Shoes of Giants', value: 'Storm Root Linen Shoes of Giants' },
  { label: 'Storm Sun Heavy Boots of Titans', value: 'Storm Sun Heavy Boots of Titans' },
  { label: 'Storm Sun Linen Shoes of Perfection', value: 'Storm Sun Linen Shoes of Perfection' },
  { label: 'Storm Sun Studded Leather Boots of Anger', value: 'Storm Sun Studded Leather Boots of Anger' },
  { label: 'Storm Tear Ornate Greaves of Giants', value: 'Storm Tear Ornate Greaves of Giants' },
  { label: 'Storm Whisper Divine Slippers of Power', value: 'Storm Whisper Divine Slippers of Power' },
  { label: 'Storm Whisper Heavy Boots of Enlightenment', value: 'Storm Whisper Heavy Boots of Enlightenment' },
  { label: 'Storm Whisper Studded Leather Boots of Perfection', value: 'Storm Whisper Studded Leather Boots of Perfection' },
  { label: 'Studded Leather Boots of Enlightenment', value: 'Studded Leather Boots of Enlightenment' },
  { label: 'Tempest Bender Demonhide Boots of Enlightenment +1', value: 'Tempest Bender Demonhide Boots of Enlightenment +1' },
  { label: 'Tempest Bender Greaves of Power +1', value: 'Tempest Bender Greaves of Power +1' },
  { label: 'Tempest Bender Silk Slippers of Anger +1', value: 'Tempest Bender Silk Slippers of Anger +1' },
  { label: 'Tempest Bite Silk Slippers of Enlightenment +1', value: 'Tempest Bite Silk Slippers of Enlightenment +1' },
  { label: 'Tempest Grasp Shoes of Rage +1', value: 'Tempest Grasp Shoes of Rage +1' },
  { label: 'Tempest Grasp Silk Slippers of Rage +1', value: 'Tempest Grasp Silk Slippers of Rage +1' },
  { label: 'Tempest Moon Hard Leather Boots of Brilliance +1', value: 'Tempest Moon Hard Leather Boots of Brilliance +1' },
  { label: 'Tempest Moon Shoes of Rage +1', value: 'Tempest Moon Shoes of Rage +1' },
  { label: 'Tempest Moon Silk Slippers of Brilliance +1', value: 'Tempest Moon Silk Slippers of Brilliance +1' },
  { label: 'Tempest Moon Silk Slippers of Skill +1', value: 'Tempest Moon Silk Slippers of Skill +1' },
  { label: 'Tempest Moon Silk Slippers of the Twins +1', value: 'Tempest Moon Silk Slippers of the Twins +1' },
  { label: 'Tempest Peak Greaves of Enlightenment +1', value: 'Tempest Peak Greaves of Enlightenment +1' },
  { label: 'Tempest Peak Greaves of Power +1', value: 'Tempest Peak Greaves of Power +1' },
  { label: 'Tempest Peak Shoes of Reflection +1', value: 'Tempest Peak Shoes of Reflection +1' },
  { label: 'Tempest Peak Silk Slippers of Reflection +1', value: 'Tempest Peak Silk Slippers of Reflection +1' },
  { label: 'Tempest Shout Greaves of Brilliance +1', value: 'Tempest Shout Greaves of Brilliance +1' },
  { label: 'Vengeance Glow Divine Slippers of the Twins', value: 'Vengeance Glow Divine Slippers of the Twins' },
  { label: 'Vengeance Glow Heavy Boots of Skill', value: 'Vengeance Glow Heavy Boots of Skill' },
  { label: 'Vengeance Roar Divine Slippers of Reflection', value: 'Vengeance Roar Divine Slippers of Reflection' },
  { label: 'Vengeance Roar Linen Shoes of Enlightenment', value: 'Vengeance Roar Linen Shoes of Enlightenment' },
  { label: 'Vengeance Roar Studded Leather Boots of the Fox', value: 'Vengeance Roar Studded Leather Boots of the Fox' },
  { label: 'Vengeance Root Studded Leather Boots of Detection', value: 'Vengeance Root Studded Leather Boots of Detection' },
  { label: 'Vengeance Sun Studded Leather Boots of Anger', value: 'Vengeance Sun Studded Leather Boots of Anger' },
  { label: 'Vengeance Sun Studded Leather Boots of the Fox', value: 'Vengeance Sun Studded Leather Boots of the Fox' },
  { label: 'Vengeance Tear Divine Slippers of Giants', value: 'Vengeance Tear Divine Slippers of Giants' },
  { label: 'Vengeance Tear Ornate Greaves of Protection', value: 'Vengeance Tear Ornate Greaves of Protection' },
  { label: 'Vengeance Tear Ornate Greaves of Rage', value: 'Vengeance Tear Ornate Greaves of Rage' },
  { label: 'Vengeance Tear Ornate Greaves of Vitriol', value: 'Vengeance Tear Ornate Greaves of Vitriol' },
  { label: 'Vengeance Whisper Heavy Boots of Power', value: 'Vengeance Whisper Heavy Boots of Power' },
  { label: 'Vengeance Whisper Ornate Greaves of Titans', value: 'Vengeance Whisper Ornate Greaves of Titans' },
  { label: 'Vengeance Whisper Studded Leather Boots of Perfection', value: 'Vengeance Whisper Studded Leather Boots of Perfection' },
  { label: 'Victory Bender Demonhide Boots of the Fox +1', value: 'Victory Bender Demonhide Boots of the Fox +1' },
  { label: 'Victory Bender Shoes of Enlightenment +1', value: 'Victory Bender Shoes of Enlightenment +1' },
  { label: 'Victory Grasp Shoes of Brilliance +1', value: 'Victory Grasp Shoes of Brilliance +1' },
  { label: 'Victory Peak Greaves of Enlightenment +1', value: 'Victory Peak Greaves of Enlightenment +1' },
  { label: 'Victory Peak Hard Leather Boots of Titans +1', value: 'Victory Peak Hard Leather Boots of Titans +1' },
  { label: 'Victory Shout Demonhide Boots of Giants +1', value: 'Victory Shout Demonhide Boots of Giants +1' },
  { label: 'Victory Shout Demonhide Boots of Protection +1', value: 'Victory Shout Demonhide Boots of Protection +1' },
  { label: 'Victory Shout Greaves of Rage +1', value: 'Victory Shout Greaves of Rage +1' },
  { label: 'Victory Shout Silk Slippers of Rage +1', value: 'Victory Shout Silk Slippers of Rage +1' },
  { label: 'Vortex Glow Heavy Boots of Rage', value: 'Vortex Glow Heavy Boots of Rage' },
  { label: 'Vortex Roar Heavy Boots of Anger', value: 'Vortex Roar Heavy Boots of Anger' },
  { label: 'Vortex Roar Heavy Boots of the Fox', value: 'Vortex Roar Heavy Boots of the Fox' },
  { label: 'Vortex Roar Linen Shoes of Power', value: 'Vortex Roar Linen Shoes of Power' },
  { label: 'Vortex Roar Ornate Greaves of Anger', value: 'Vortex Roar Ornate Greaves of Anger' },
  { label: 'Vortex Sun Ornate Greaves of Anger', value: 'Vortex Sun Ornate Greaves of Anger' },
  { label: 'Vortex Sun Studded Leather Boots of Enlightenment', value: 'Vortex Sun Studded Leather Boots of Enlightenment' },
  { label: 'Vortex Tear Divine Slippers of Vitriol', value: 'Vortex Tear Divine Slippers of Vitriol' },
  { label: 'Vortex Whisper Divine Slippers of the Fox', value: 'Vortex Whisper Divine Slippers of the Fox' },
  { label: 'Vortex Whisper Heavy Boots of Perfection', value: 'Vortex Whisper Heavy Boots of Perfection' },
  { label: 'Vortex Whisper Linen Shoes of Fury', value: 'Vortex Whisper Linen Shoes of Fury' },
  { label: 'Vortex Whisper Studded Leather Boots of Anger', value: 'Vortex Whisper Studded Leather Boots of Anger' },
  { label: 'Woe Bender Demonhide Boots of the Fox +1', value: 'Woe Bender Demonhide Boots of the Fox +1' },
  { label: 'Woe Bender Shoes of the Fox +1', value: 'Woe Bender Shoes of the Fox +1' },
  { label: 'Woe Bender Silk Slippers of Titans +1', value: 'Woe Bender Silk Slippers of Titans +1' },
  { label: 'Woe Bite Hard Leather Boots of Fury +1', value: 'Woe Bite Hard Leather Boots of Fury +1' },
  { label: 'Woe Grasp Demonhide Boots of Protection +1', value: 'Woe Grasp Demonhide Boots of Protection +1' },
  { label: 'Woe Grasp Silk Slippers of Detection +1', value: 'Woe Grasp Silk Slippers of Detection +1' },
  { label: 'Woe Grasp Silk Slippers of Vitriol +1', value: 'Woe Grasp Silk Slippers of Vitriol +1' },
  { label: 'Woe Moon Greaves of Protection +1', value: 'Woe Moon Greaves of Protection +1' },
  { label: 'Woe Moon Greaves of Rage +1', value: 'Woe Moon Greaves of Rage +1' },
  { label: 'Woe Moon Shoes of the Twins +1', value: 'Woe Moon Shoes of the Twins +1' },
  { label: 'Woe Moon Shoes of Vitriol +1', value: 'Woe Moon Shoes of Vitriol +1' },
  { label: 'Woe Peak Greaves of Fury +1', value: 'Woe Peak Greaves of Fury +1' },
  { label: 'Woe Peak Silk Slippers of Reflection +1', value: 'Woe Peak Silk Slippers of Reflection +1' },
  { label: 'Woe Shout Greaves of the Twins +1', value: 'Woe Shout Greaves of the Twins +1' },
  { label: 'Woe Shout Silk Slippers of Brilliance +1', value: 'Woe Shout Silk Slippers of Brilliance +1' },
];
