export const hands = [
  { label: 'Studded Leather Gloves', value: 'Studded Leather Gloves' },
  { label: 'Silk Gloves', value: 'Silk Gloves' },
  { label: 'Heavy Gloves', value: 'Heavy Gloves' },
  { label: 'Linen Gloves', value: 'Linen Gloves' },
  { label: 'Dragonskin Gloves', value: 'Dragonskin Gloves' },
  { label: 'Chain Gloves', value: 'Chain Gloves' },
  { label: 'Holy Gauntlets', value: 'Holy Gauntlets' },
  { label: 'Divine Gloves', value: 'Divine Gloves' },
  { label: 'Wool Gloves', value: 'Wool Gloves' },
  { label: 'Gauntlets', value: 'Gauntlets' },
  { label: 'Ornate Gauntlets', value: 'Ornate Gauntlets' },
  { label: 'Leather Gloves', value: 'Leather Gloves' },
  { label: 'Hard Leather Gloves', value: 'Hard Leather Gloves' },
  { label: "Demon's Hands", value: "Demon's Hands" },
  { label: 'Gloves', value: 'Gloves' },
  { label: 'Holy Gauntlets of Giants', value: 'Holy Gauntlets of Giants' },
  { label: 'Leather Gloves of Anger', value: 'Leather Gloves of Anger' },
  { label: 'Chain Gloves of Perfection', value: 'Chain Gloves of Perfection' },
  { label: 'Wool Gloves of the Twins', value: 'Wool Gloves of the Twins' },
  { label: 'Wool Gloves of Titans', value: 'Wool Gloves of Titans' },
  { label: 'Leather Gloves of Enlightenment', value: 'Leather Gloves of Enlightenment' },
  { label: 'Holy Gauntlets of Perfection', value: 'Holy Gauntlets of Perfection' },
  { label: 'Holy Gauntlets of Titans', value: 'Holy Gauntlets of Titans' },
  { label: 'Holy Gauntlets of Skill', value: 'Holy Gauntlets of Skill' },
  { label: 'Dragonskin Gloves of the Twins', value: 'Dragonskin Gloves of the Twins' },
  { label: 'Holy Gauntlets of Detection', value: 'Holy Gauntlets of Detection' },
  { label: 'Leather Gloves of the Fox', value: 'Leather Gloves of the Fox' },
  { label: 'Wool Gloves of Detection', value: 'Wool Gloves of Detection' },
  { label: 'Wool Gloves of Anger', value: 'Wool Gloves of Anger' },
  { label: 'Leather Gloves of Protection', value: 'Leather Gloves of Protection' },
  { label: 'Holy Gauntlets of the Twins', value: 'Holy Gauntlets of the Twins' },
  { label: 'Leather Gloves of the Twins', value: 'Leather Gloves of the Twins' },
  { label: 'Holy Gauntlets of Vitriol', value: 'Holy Gauntlets of Vitriol' },
  { label: 'Wool Gloves of Protection', value: 'Wool Gloves of Protection' },
  { label: 'Leather Gloves of Giants', value: 'Leather Gloves of Giants' },
  { label: 'Leather Gloves of Titans', value: 'Leather Gloves of Titans' },
  { label: 'Holy Gauntlets of Rage', value: 'Holy Gauntlets of Rage' },
  { label: 'Wool Gloves of Giants', value: 'Wool Gloves of Giants' },
  { label: 'Gloves of Brilliance', value: 'Gloves of Brilliance' },
  { label: 'Dragonskin Gloves of the Fox', value: 'Dragonskin Gloves of the Fox' },
  { label: 'Dragonskin Gloves of Vitriol', value: 'Dragonskin Gloves of Vitriol' },
  { label: 'Holy Gauntlets of Protection', value: 'Holy Gauntlets of Protection' },
  { label: 'Holy Gauntlets of Reflection', value: 'Holy Gauntlets of Reflection' },
  { label: 'Leather Gloves of Perfection', value: 'Leather Gloves of Perfection' },
  { label: 'Dragonskin Gloves of Power', value: 'Dragonskin Gloves of Power' },
  { label: 'Dragonskin Gloves of Rage', value: 'Dragonskin Gloves of Rage' },
  { label: 'Holy Gauntlets of Fury', value: 'Holy Gauntlets of Fury' },
  { label: 'Chain Gloves of Anger', value: 'Chain Gloves of Anger' },
  { label: 'Wool Gloves of Skill', value: 'Wool Gloves of Skill' },
  { label: 'Dragonskin Gloves of Brilliance', value: 'Dragonskin Gloves of Brilliance' },
  { label: 'Dragonskin Gloves of Detection', value: 'Dragonskin Gloves of Detection' },
  { label: 'Chain Gloves of Enlightenment', value: 'Chain Gloves of Enlightenment' },
  { label: 'Leather Gloves of Brilliance', value: 'Leather Gloves of Brilliance' },
  { label: 'Dragonskin Gloves of Titans', value: 'Dragonskin Gloves of Titans' },
  { label: 'Dragonskin Gloves of Skill', value: 'Dragonskin Gloves of Skill' },
  { label: 'Wool Gloves of Brilliance', value: 'Wool Gloves of Brilliance' },
  { label: 'Wool Gloves of Perfection', value: 'Wool Gloves of Perfection' },
  { label: 'Wool Gloves of Reflection', value: 'Wool Gloves of Reflection' },
  { label: 'Chain Gloves of Vitriol', value: 'Chain Gloves of Vitriol' },
  { label: 'Holy Gauntlets of Anger', value: 'Holy Gauntlets of Anger' },
  { label: 'Chain Gloves of Giants', value: 'Chain Gloves of Giants' },
  { label: 'Chain Gloves of Power', value: 'Chain Gloves of Power' },
  { label: 'Gauntlets of Anger', value: 'Gauntlets of Anger' },
  { label: 'Studded Leather Gloves of Perfection', value: 'Studded Leather Gloves of Perfection' },
  { label: 'Hard Leather Gloves of the Twins', value: 'Hard Leather Gloves of the Twins' },
  { label: 'Dragonskin Gloves of Perfection', value: 'Dragonskin Gloves of Perfection' },
  { label: 'Studded Leather Gloves of Fury', value: 'Studded Leather Gloves of Fury' },
  { label: 'Hard Leather Gloves of Giants', value: 'Hard Leather Gloves of Giants' },
  { label: 'Hard Leather Gloves of Skill', value: 'Hard Leather Gloves of Skill' },
  { label: 'Holy Gauntlets of Brilliance', value: 'Holy Gauntlets of Brilliance' },
  { label: 'Leather Gloves of Reflection', value: 'Leather Gloves of Reflection' },
  { label: 'Chain Gloves of the Fox', value: 'Chain Gloves of the Fox' },
  { label: "Demon's Hands of Titans", value: "Demon's Hands of Titans" },
  { label: 'Gauntlets of Protection', value: 'Gauntlets of Protection' },
  { label: 'Holy Gauntlets of Power', value: 'Holy Gauntlets of Power' },
  { label: 'Leather Gloves of Skill', value: 'Leather Gloves of Skill' },
  { label: 'Linen Gloves of the Fox', value: 'Linen Gloves of the Fox' },
  { label: 'Gauntlets of the Twins', value: 'Gauntlets of the Twins' },
  { label: 'Leather Gloves of Rage', value: 'Leather Gloves of Rage' },
  { label: 'Silk Gloves of Vitriol', value: 'Silk Gloves of Vitriol' },
  { label: 'Divine Gloves of Fury', value: 'Divine Gloves of Fury' },
  { label: 'Wool Gloves of Power', value: 'Wool Gloves of Power' },
  { label: 'Wool Gloves of Fury', value: 'Wool Gloves of Fury' },
  { label: 'Hard Leather Gloves of Enlightenment', value: 'Hard Leather Gloves of Enlightenment' },
  { label: 'Hard Leather Gloves of Reflection', value: 'Hard Leather Gloves of Reflection' },
  { label: 'Dragonskin Gloves of Reflection', value: 'Dragonskin Gloves of Reflection' },
  { label: 'Holy Gauntlets of Enlightenment', value: 'Holy Gauntlets of Enlightenment' },
  { label: 'Ornate Gauntlets of Perfection', value: 'Ornate Gauntlets of Perfection' },
  { label: 'Divine Gloves of Protection', value: 'Divine Gloves of Protection' },
  { label: 'Hard Leather Gloves of Rage', value: 'Hard Leather Gloves of Rage' },
  { label: 'Ornate Gauntlets of the Fox', value: 'Ornate Gauntlets of the Fox' },
  { label: 'Linen Gloves of Perfection', value: 'Linen Gloves of Perfection' },
  { label: 'Chain Gloves of Detection', value: 'Chain Gloves of Detection' },
  { label: 'Holy Gauntlets of the Fox', value: 'Holy Gauntlets of the Fox' },
  { label: 'Leather Gloves of Vitriol', value: 'Leather Gloves of Vitriol' },
  { label: 'Silk Gloves of Brilliance', value: 'Silk Gloves of Brilliance' },
  { label: 'Leather Gloves of Power', value: 'Leather Gloves of Power' },
  { label: "Demon's Hands of Rage", value: "Demon's Hands of Rage" },
  { label: 'Heavy Gloves of Power', value: 'Heavy Gloves of Power' },
  { label: 'Heavy Gloves of Skill', value: 'Heavy Gloves of Skill' },
  { label: 'Silk Gloves of Giants', value: 'Silk Gloves of Giants' },
  { label: 'Chain Gloves of Rage', value: 'Chain Gloves of Rage' },
  { label: 'Linen Gloves of Fury', value: 'Linen Gloves of Fury' },
  { label: 'Gauntlets of Giants', value: 'Gauntlets of Giants' },
  { label: 'Gloves of Titans', value: 'Gloves of Titans' },
  { label: 'Gloves of Rage', value: 'Gloves of Rage' },
  { label: 'Hard Leather Gloves of Perfection', value: 'Hard Leather Gloves of Perfection' },
  { label: 'Hard Leather Gloves of Protection', value: 'Hard Leather Gloves of Protection' },
  { label: 'Hard Leather Gloves of Detection', value: 'Hard Leather Gloves of Detection' },
  { label: 'Studded Leather Gloves of Giants', value: 'Studded Leather Gloves of Giants' },
  { label: 'Dragonskin Gloves of Protection', value: 'Dragonskin Gloves of Protection' },
  { label: 'Wool Gloves of Enlightenment', value: 'Wool Gloves of Enlightenment' },
  { label: 'Hard Leather Gloves of Fury', value: 'Hard Leather Gloves of Fury' },
  { label: 'Leather Gloves of Detection', value: 'Leather Gloves of Detection' },
  { label: 'Ornate Gauntlets of Vitriol', value: 'Ornate Gauntlets of Vitriol' },
  { label: 'Chain Gloves of Brilliance', value: 'Chain Gloves of Brilliance' },
  { label: 'Chain Gloves of Reflection', value: 'Chain Gloves of Reflection' },
  { label: "Demon's Hands of the Twins", value: "Demon's Hands of the Twins" },
  { label: 'Heavy Gloves of Brilliance', value: 'Heavy Gloves of Brilliance' },
  { label: 'Heavy Gloves of Protection', value: 'Heavy Gloves of Protection' },
  { label: 'Ornate Gauntlets of Titans', value: 'Ornate Gauntlets of Titans' },
  { label: 'Chain Gloves of the Twins', value: 'Chain Gloves of the Twins' },
  { label: 'Dragonskin Gloves of Fury', value: 'Dragonskin Gloves of Fury' },
  { label: 'Silk Gloves of Protection', value: 'Silk Gloves of Protection' },
  { label: 'Ornate Gauntlets of Fury', value: 'Ornate Gauntlets of Fury' },
  { label: "Demon's Hands of Skill", value: "Demon's Hands of Skill" },
  { label: 'Wool Gloves of Vitriol', value: 'Wool Gloves of Vitriol' },
  { label: 'Linen Gloves of Power', value: 'Linen Gloves of Power' },
  { label: 'Linen Gloves of Skill', value: 'Linen Gloves of Skill' },
  { label: 'Chain Gloves of Fury', value: 'Chain Gloves of Fury' },
  { label: 'Gauntlets of the Fox', value: 'Gauntlets of the Fox' },
  { label: 'Heavy Gloves of Rage', value: 'Heavy Gloves of Rage' },
  { label: 'Silk Gloves of Anger', value: 'Silk Gloves of Anger' },
  { label: 'Gauntlets of Titans', value: 'Gauntlets of Titans' },
  { label: 'Wool Gloves of Rage', value: 'Wool Gloves of Rage' },
  { label: 'Gloves of Giants', value: 'Gloves of Giants' },
  { label: 'Gloves of Power', value: 'Gloves of Power' },
  { label: 'Gloves of Fury', value: 'Gloves of Fury' },
  { label: 'Studded Leather Gloves of the Twins', value: 'Studded Leather Gloves of the Twins' },
  { label: 'Ornate Gauntlets of Protection', value: 'Ornate Gauntlets of Protection' },
  { label: 'Ornate Gauntlets of Reflection', value: 'Ornate Gauntlets of Reflection' },
  { label: 'Studded Leather Gloves of Rage', value: 'Studded Leather Gloves of Rage' },
  { label: 'Hard Leather Gloves of Titans', value: 'Hard Leather Gloves of Titans' },
  { label: 'Heavy Gloves of Enlightenment', value: 'Heavy Gloves of Enlightenment' },
  { label: 'Ornate Gauntlets of Detection', value: 'Ornate Gauntlets of Detection' },
  { label: 'Ornate Gauntlets of the Twins', value: 'Ornate Gauntlets of the Twins' },
  { label: 'Hard Leather Gloves of Anger', value: 'Hard Leather Gloves of Anger' },
  { label: 'Silk Gloves of Enlightenment', value: 'Silk Gloves of Enlightenment' },
  { label: "Demon's Hands of Brilliance", value: "Demon's Hands of Brilliance" },
  { label: "Demon's Hands of Perfection", value: "Demon's Hands of Perfection" },
  { label: 'Divine Gloves of Perfection', value: 'Divine Gloves of Perfection' },
  { label: 'Divine Gloves of Reflection', value: 'Divine Gloves of Reflection' },
  { label: "Demon's Hands of Detection", value: "Demon's Hands of Detection" },
  { label: 'Divine Gloves of the Twins', value: 'Divine Gloves of the Twins' },
  { label: 'Dragonskin Gloves of Anger', value: 'Dragonskin Gloves of Anger' },
  { label: 'Gauntlets of Enlightenment', value: 'Gauntlets of Enlightenment' },
  { label: 'Linen Gloves of Brilliance', value: 'Linen Gloves of Brilliance' },
  { label: 'Linen Gloves of Detection', value: 'Linen Gloves of Detection' },
  { label: 'Ornate Gauntlets of Anger', value: 'Ornate Gauntlets of Anger' },
  { label: 'Silk Gloves of Perfection', value: 'Silk Gloves of Perfection' },
  { label: 'Silk Gloves of Reflection', value: 'Silk Gloves of Reflection' },
  { label: 'Divine Gloves of the Fox', value: 'Divine Gloves of the Fox' },
  { label: 'Divine Gloves of Giants', value: 'Divine Gloves of Giants' },
  { label: 'Gloves of Enlightenment', value: 'Gloves of Enlightenment' },
  { label: 'Heavy Gloves of the Fox', value: 'Heavy Gloves of the Fox' },
  { label: 'Divine Gloves of Skill', value: 'Divine Gloves of Skill' },
  { label: 'Leather Gloves of Fury', value: 'Leather Gloves of Fury' },
  { label: 'Wool Gloves of the Fox', value: 'Wool Gloves of the Fox' },
  { label: 'Chain Gloves of Skill', value: 'Chain Gloves of Skill' },
  { label: 'Silk Gloves of Titans', value: 'Silk Gloves of Titans' },
  { label: 'Gauntlets of Vitriol', value: 'Gauntlets of Vitriol' },
  { label: 'Silk Gloves of Fury', value: 'Silk Gloves of Fury' },
  { label: 'Gauntlets of Rage', value: 'Gauntlets of Rage' },
  { label: 'Studded Leather Gloves of Brilliance', value: 'Studded Leather Gloves of Brilliance' },
  { label: 'Studded Leather Gloves of Protection', value: 'Studded Leather Gloves of Protection' },
  { label: 'Studded Leather Gloves of Reflection', value: 'Studded Leather Gloves of Reflection' },
  { label: 'Studded Leather Gloves of Detection', value: 'Studded Leather Gloves of Detection' },
  { label: 'Ornate Gauntlets of Enlightenment', value: 'Ornate Gauntlets of Enlightenment' },
  { label: 'Studded Leather Gloves of the Fox', value: 'Studded Leather Gloves of the Fox' },
  { label: 'Studded Leather Gloves of Anger', value: 'Studded Leather Gloves of Anger' },
  { label: 'Hard Leather Gloves of the Fox', value: 'Hard Leather Gloves of the Fox' },
  { label: 'Ornate Gauntlets of Brilliance', value: 'Ornate Gauntlets of Brilliance' },
  { label: 'Hard Leather Gloves of Power', value: 'Hard Leather Gloves of Power' },
  { label: 'Dragonskin Gloves of Giants', value: 'Dragonskin Gloves of Giants' },
  { label: 'Heavy Gloves of Perfection', value: 'Heavy Gloves of Perfection' },
  { label: 'Linen Gloves of Reflection', value: 'Linen Gloves of Reflection' },
  { label: 'Heavy Gloves of the Twins', value: 'Heavy Gloves of the Twins' },
  { label: 'Linen Gloves of the Twins', value: 'Linen Gloves of the Twins' },
  { label: 'Ornate Gauntlets of Skill', value: 'Ornate Gauntlets of Skill' },
  { label: "Demon's Hands of the Fox", value: "Demon's Hands of the Fox" },
  { label: 'Divine Gloves of Vitriol', value: 'Divine Gloves of Vitriol' },
  { label: "Demon's Hands of Giants", value: "Demon's Hands of Giants" },
  { label: 'Divine Gloves of Titans', value: 'Divine Gloves of Titans' },
  { label: 'Gauntlets of Brilliance', value: 'Gauntlets of Brilliance' },
  { label: 'Heavy Gloves of Vitriol', value: 'Heavy Gloves of Vitriol' },
  { label: 'Chain Gloves of Titans', value: 'Chain Gloves of Titans' },
  { label: 'Divine Gloves of Anger', value: 'Divine Gloves of Anger' },
  { label: 'Divine Gloves of Power', value: 'Divine Gloves of Power' },
  { label: 'Linen Gloves of Giants', value: 'Linen Gloves of Giants' },
  { label: 'Linen Gloves of Titans', value: 'Linen Gloves of Titans' },
  { label: 'Silk Gloves of the Fox', value: 'Silk Gloves of the Fox' },
  { label: 'Gloves of Protection', value: 'Gloves of Protection' },
  { label: 'Gloves of Reflection', value: 'Gloves of Reflection' },
  { label: 'Linen Gloves of Rage', value: 'Linen Gloves of Rage' },
  { label: 'Gloves of Detection', value: 'Gloves of Detection' },
  { label: 'Gauntlets of Power', value: 'Gauntlets of Power' },
  { label: 'Gauntlets of Skill', value: 'Gauntlets of Skill' },
  { label: 'Gloves of the Fox', value: 'Gloves of the Fox' },
  { label: 'Studded Leather Gloves of Enlightenment', value: 'Studded Leather Gloves of Enlightenment' },
  { label: 'Dragonskin Gloves of Enlightenment', value: 'Dragonskin Gloves of Enlightenment' },
  { label: 'Studded Leather Gloves of Power', value: 'Studded Leather Gloves of Power' },
  { label: "Demon's Hands of Enlightenment", value: "Demon's Hands of Enlightenment" },
  { label: 'Hard Leather Gloves of Vitriol', value: 'Hard Leather Gloves of Vitriol' },
  { label: "Demon's Hands of Protection", value: "Demon's Hands of Protection" },
  { label: "Demon's Hands of Reflection", value: "Demon's Hands of Reflection" },
  { label: 'Chain Gloves of Protection', value: 'Chain Gloves of Protection' },
  { label: 'Divine Gloves of Detection', value: 'Divine Gloves of Detection' },
  { label: 'Heavy Gloves of Detection', value: 'Heavy Gloves of Detection' },
  { label: 'Ornate Gauntlets of Power', value: 'Ornate Gauntlets of Power' },
  { label: "Demon's Hands of Power", value: "Demon's Hands of Power" },
  { label: 'Gauntlets of Detection', value: 'Gauntlets of Detection' },
  { label: 'Heavy Gloves of Giants', value: 'Heavy Gloves of Giants' },
  { label: 'Heavy Gloves of Titans', value: 'Heavy Gloves of Titans' },
  { label: 'Divine Gloves of Rage', value: 'Divine Gloves of Rage' },
  { label: 'Linen Gloves of Anger', value: 'Linen Gloves of Anger' },
  { label: 'Gloves of Perfection', value: 'Gloves of Perfection' },
  { label: 'Silk Gloves of Power', value: 'Silk Gloves of Power' },
  { label: 'Gloves of Vitriol', value: 'Gloves of Vitriol' },
  { label: 'Victory Bender Hard Leather Gloves of Enlightenment +1', value: 'Victory Bender Hard Leather Gloves of Enlightenment +1' },
  { label: 'Demon Shout Hard Leather Gloves of Brilliance +1', value: 'Demon Shout Hard Leather Gloves of Brilliance +1' },
  { label: 'Skull Shout Hard Leather Gloves of Protection +1', value: 'Skull Shout Hard Leather Gloves of Protection +1' },
  { label: 'Victory Moon Hard Leather Gloves of the Twins +1', value: 'Victory Moon Hard Leather Gloves of the Twins +1' },
  { label: 'Apocalypse Glow Studded Leather Gloves of Rage', value: 'Apocalypse Glow Studded Leather Gloves of Rage' },
  { label: "Shimmering Bite Demon's Hands of Perfection +1", value: "Shimmering Bite Demon's Hands of Perfection +1" },
  { label: "Shimmering Bite Demon's Hands of Reflection +1", value: "Shimmering Bite Demon's Hands of Reflection +1" },
  { label: 'Fate Root Studded Leather Gloves of the Twins', value: 'Fate Root Studded Leather Gloves of the Twins' },
  { label: 'Tempest Peak Hard Leather Gloves of Titans +1', value: 'Tempest Peak Hard Leather Gloves of Titans +1' },
  { label: "Kraken Bender Demon's Hands of Perfection +1", value: "Kraken Bender Demon's Hands of Perfection +1" },
  { label: 'Bramble Glow Ornate Gauntlets of Protection', value: 'Bramble Glow Ornate Gauntlets of Protection' },
  { label: "Kraken Grasp Demon's Hands of Protection +1", value: "Kraken Grasp Demon's Hands of Protection +1" },
  { label: "Light's Tear Ornate Gauntlets of Brilliance", value: "Light's Tear Ornate Gauntlets of Brilliance" },
  { label: "Shimmering Moon Demon's Hands of Vitriol +1", value: "Shimmering Moon Demon's Hands of Vitriol +1" },
  { label: 'Kraken Bite Hard Leather Gloves of Fury +1', value: 'Kraken Bite Hard Leather Gloves of Fury +1' },
  { label: "Pandemonium Peak Demon's Hands of Power +1", value: "Pandemonium Peak Demon's Hands of Power +1" },
  { label: 'Rage Bender Hard Leather Gloves of Fury +1', value: 'Rage Bender Hard Leather Gloves of Fury +1' },
  { label: 'Morbid Roar Heavy Gloves of Enlightenment', value: 'Morbid Roar Heavy Gloves of Enlightenment' },
  { label: 'Kraken Moon Silk Gloves of Brilliance +1', value: 'Kraken Moon Silk Gloves of Brilliance +1' },
  { label: 'Shimmering Moon Gauntlets of Giants +1', value: 'Shimmering Moon Gauntlets of Giants +1' },
  { label: 'Dread Grasp Gauntlets of Detection +1', value: 'Dread Grasp Gauntlets of Detection +1' },
  { label: 'Dread Peak Gloves of Enlightenment +1', value: 'Dread Peak Gloves of Enlightenment +1' },
  { label: 'Maelstrom Tear Divine Gloves of Skill', value: 'Maelstrom Tear Divine Gloves of Skill' },
  { label: 'Tempest Grasp Gloves of Protection +1', value: 'Tempest Grasp Gloves of Protection +1' },
  { label: "Gloom Peak Demon's Hands of Anger +1", value: "Gloom Peak Demon's Hands of Anger +1" },
  { label: 'Rune Glow Heavy Gloves of Protection', value: 'Rune Glow Heavy Gloves of Protection' },
  { label: 'Tempest Moon Gloves of Brilliance +1', value: 'Tempest Moon Gloves of Brilliance +1' },
  { label: 'Corpse Tear Divine Gloves of Giants', value: 'Corpse Tear Divine Gloves of Giants' },
  { label: 'Foe Bender Silk Gloves of Titans +1', value: 'Foe Bender Silk Gloves of Titans +1' },
  { label: 'Oblivion Bender Gloves of Titans +1', value: 'Oblivion Bender Gloves of Titans +1' },
  { label: 'Dread Shout Gloves of the Twins +1', value: 'Dread Shout Gloves of the Twins +1' },
  { label: 'Kraken Peak Silk Gloves of Fury +1', value: 'Kraken Peak Silk Gloves of Fury +1' },
  { label: 'Plague Sun Divine Gloves of Titans', value: 'Plague Sun Divine Gloves of Titans' },
  { label: 'Skull Bite Gauntlets of the Fox +1', value: 'Skull Bite Gauntlets of the Fox +1' },
  { label: 'Grim Bender Gauntlets of Power +1', value: 'Grim Bender Gauntlets of Power +1' },
  { label: 'Hard Leather Gloves of Brilliance', value: 'Hard Leather Gloves of Brilliance' },
  { label: 'Studded Leather Gloves of Vitriol', value: 'Studded Leather Gloves of Vitriol' },
  { label: 'Woe Peak Gloves of Reflection +1', value: 'Woe Peak Gloves of Reflection +1' },
  { label: 'Studded Leather Gloves of Skill', value: 'Studded Leather Gloves of Skill' },
  { label: 'Divine Gloves of Enlightenment', value: 'Divine Gloves of Enlightenment' },
  { label: 'Linen Gloves of Enlightenment', value: 'Linen Gloves of Enlightenment' },
  { label: 'Heavy Gloves of Reflection', value: 'Heavy Gloves of Reflection' },
  { label: 'Linen Gloves of Protection', value: 'Linen Gloves of Protection' },
  { label: "Demon's Hands of Vitriol", value: "Demon's Hands of Vitriol" },
  { label: 'Silk Gloves of Detection', value: 'Silk Gloves of Detection' },
  { label: 'Silk Gloves of the Twins', value: 'Silk Gloves of the Twins' },
  { label: 'Gauntlets of Reflection', value: 'Gauntlets of Reflection' },
  { label: 'Linen Gloves of Vitriol', value: 'Linen Gloves of Vitriol' },
  { label: "Demon's Hands of Anger", value: "Demon's Hands of Anger" },
  { label: "Demon's Hands of Fury", value: "Demon's Hands of Fury" },
  { label: 'Heavy Gloves of Anger', value: 'Heavy Gloves of Anger' },
  { label: 'Heavy Gloves of Fury', value: 'Heavy Gloves of Fury' },
  { label: 'Silk Gloves of Skill', value: 'Silk Gloves of Skill' },
  { label: 'Gloves of the Twins', value: 'Gloves of the Twins' },
  { label: 'Gloves of Anger', value: 'Gloves of Anger' },
  { label: 'Gloves of Skill', value: 'Gloves of Skill' },
  { label: 'Behemoth Whisper Studded Leather Gloves of Enlightenment', value: 'Behemoth Whisper Studded Leather Gloves of Enlightenment' },
  { label: 'Bramble Whisper Studded Leather Gloves of Enlightenment', value: 'Bramble Whisper Studded Leather Gloves of Enlightenment' },
  { label: 'Pandemonium Grasp Hard Leather Gloves of Brilliance +1', value: 'Pandemonium Grasp Hard Leather Gloves of Brilliance +1' },
  { label: 'Pandemonium Shout Hard Leather Gloves of Brilliance +1', value: 'Pandemonium Shout Hard Leather Gloves of Brilliance +1' },
  { label: 'Apocalypse Root Studded Leather Gloves of Protection', value: 'Apocalypse Root Studded Leather Gloves of Protection' },
  { label: 'Fate Whisper Studded Leather Gloves of Enlightenment', value: 'Fate Whisper Studded Leather Gloves of Enlightenment' },
  { label: 'Pandemonium Bender Hard Leather Gloves of Titans +1', value: 'Pandemonium Bender Hard Leather Gloves of Titans +1' },
  { label: 'Corruption Bender Hard Leather Gloves of Titans +1', value: 'Corruption Bender Hard Leather Gloves of Titans +1' },
  { label: 'Death Whisper Studded Leather Gloves of Reflection', value: 'Death Whisper Studded Leather Gloves of Reflection' },
  { label: 'Demon Bite Hard Leather Gloves of Enlightenment +1', value: 'Demon Bite Hard Leather Gloves of Enlightenment +1' },
  { label: 'Honour Bender Hard Leather Gloves of Perfection +1', value: 'Honour Bender Hard Leather Gloves of Perfection +1' },
  { label: 'Hypnotic Glow Studded Leather Gloves of Protection', value: 'Hypnotic Glow Studded Leather Gloves of Protection' },
  { label: 'Hypnotic Tear Studded Leather Gloves of Brilliance', value: 'Hypnotic Tear Studded Leather Gloves of Brilliance' },
  { label: 'Maelstrom Glow Studded Leather Gloves of the Twins', value: 'Maelstrom Glow Studded Leather Gloves of the Twins' },
  { label: 'Oblivion Bite Hard Leather Gloves of Reflection +1', value: 'Oblivion Bite Hard Leather Gloves of Reflection +1' },
  { label: 'Pandemonium Moon Hard Leather Gloves of Vitriol +1', value: 'Pandemonium Moon Hard Leather Gloves of Vitriol +1' },
  { label: 'Bramble Glow Studded Leather Gloves of Brilliance', value: 'Bramble Glow Studded Leather Gloves of Brilliance' },
  { label: 'Bramble Glow Studded Leather Gloves of Protection', value: 'Bramble Glow Studded Leather Gloves of Protection' },
  { label: 'Brimstone Bender Hard Leather Gloves of Titans +1', value: 'Brimstone Bender Hard Leather Gloves of Titans +1' },
  { label: 'Corruption Bender Silk Gloves of Enlightenment +1', value: 'Corruption Bender Silk Gloves of Enlightenment +1' },
  { label: 'Corruption Grasp Hard Leather Gloves of Giants +1', value: 'Corruption Grasp Hard Leather Gloves of Giants +1' },
  { label: "Light's Whisper Ornate Gauntlets of Enlightenment", value: "Light's Whisper Ornate Gauntlets of Enlightenment" },
  { label: 'Armageddon Bite Hard Leather Gloves of Titans +1', value: 'Armageddon Bite Hard Leather Gloves of Titans +1' },
  { label: 'Armageddon Shout Hard Leather Gloves of Skill +1', value: 'Armageddon Shout Hard Leather Gloves of Skill +1' },
  { label: "Brimstone Peak Demon's Hands of Enlightenment +1", value: "Brimstone Peak Demon's Hands of Enlightenment +1" },
  { label: 'Cataclysm Bender Hard Leather Gloves of Power +1', value: 'Cataclysm Bender Hard Leather Gloves of Power +1' },
  { label: 'Cataclysm Grasp Hard Leather Gloves of Giants +1', value: 'Cataclysm Grasp Hard Leather Gloves of Giants +1' },
  { label: 'Cataclysm Shout Hard Leather Gloves of Giants +1', value: 'Cataclysm Shout Hard Leather Gloves of Giants +1' },
  { label: 'Dragon Root Studded Leather Gloves of Brilliance', value: 'Dragon Root Studded Leather Gloves of Brilliance' },
  { label: 'Dread Grasp Hard Leather Gloves of Protection +1', value: 'Dread Grasp Hard Leather Gloves of Protection +1' },
  { label: 'Fate Sun Studded Leather Gloves of Enlightenment', value: 'Fate Sun Studded Leather Gloves of Enlightenment' },
  { label: 'Honour Moon Hard Leather Gloves of Brilliance +1', value: 'Honour Moon Hard Leather Gloves of Brilliance +1' },
  { label: 'Honour Shout Hard Leather Gloves of Detection +1', value: 'Honour Shout Hard Leather Gloves of Detection +1' },
  { label: 'Kraken Peak Hard Leather Gloves of Perfection +1', value: 'Kraken Peak Hard Leather Gloves of Perfection +1' },
  { label: "Pandemonium Grasp Demon's Hands of Protection +1", value: "Pandemonium Grasp Demon's Hands of Protection +1" },
  { label: 'Plague Glow Studded Leather Gloves of Brilliance', value: 'Plague Glow Studded Leather Gloves of Brilliance' },
  { label: 'Corruption Peak Hard Leather Gloves of Power +1', value: 'Corruption Peak Hard Leather Gloves of Power +1' },
  { label: 'Death Root Studded Leather Gloves of Protection', value: 'Death Root Studded Leather Gloves of Protection' },
  { label: 'Dragon Sun Studded Leather Gloves of Perfection', value: 'Dragon Sun Studded Leather Gloves of Perfection' },
  { label: 'Eagle Moon Hard Leather Gloves of Brilliance +1', value: 'Eagle Moon Hard Leather Gloves of Brilliance +1' },
  { label: 'Grim Grasp Hard Leather Gloves of Brilliance +1', value: 'Grim Grasp Hard Leather Gloves of Brilliance +1' },
  { label: 'Havoc Roar Studded Leather Gloves of Reflection', value: 'Havoc Roar Studded Leather Gloves of Reflection' },
  { label: 'Morbid Sun Studded Leather Gloves of Reflection', value: 'Morbid Sun Studded Leather Gloves of Reflection' },
  { label: "Pandemonium Moon Demon's Hands of Protection +1", value: "Pandemonium Moon Demon's Hands of Protection +1" },
  { label: "Pandemonium Shout Demon's Hands of Detection +1", value: "Pandemonium Shout Demon's Hands of Detection +1" },
  { label: 'Apocalypse Roar Ornate Gauntlets of Reflection', value: 'Apocalypse Roar Ornate Gauntlets of Reflection' },
  { label: 'Apocalypse Whisper Divine Gloves of Reflection', value: 'Apocalypse Whisper Divine Gloves of Reflection' },
  { label: "Armageddon Peak Demon's Hands of Perfection +1", value: "Armageddon Peak Demon's Hands of Perfection +1" },
  { label: 'Carrion Roar Ornate Gauntlets of Enlightenment', value: 'Carrion Roar Ornate Gauntlets of Enlightenment' },
  { label: 'Cataclysm Peak Hard Leather Gloves of Power +1', value: 'Cataclysm Peak Hard Leather Gloves of Power +1' },
  { label: "Cataclysm Shout Demon's Hands of Protection +1", value: "Cataclysm Shout Demon's Hands of Protection +1" },
  { label: "Corruption Bite Demon's Hands of Reflection +1", value: "Corruption Bite Demon's Hands of Reflection +1" },
  { label: "Corruption Moon Demon's Hands of Protection +1", value: "Corruption Moon Demon's Hands of Protection +1" },
  { label: 'Dread Moon Hard Leather Gloves of Detection +1', value: 'Dread Moon Hard Leather Gloves of Detection +1' },
  { label: 'Dusk Roar Studded Leather Gloves of Perfection', value: 'Dusk Roar Studded Leather Gloves of Perfection' },
  { label: 'Dusk Roar Studded Leather Gloves of Reflection', value: 'Dusk Roar Studded Leather Gloves of Reflection' },
  { label: 'Dusk Tear Studded Leather Gloves of Brilliance', value: 'Dusk Tear Studded Leather Gloves of Brilliance' },
  { label: 'Dusk Whisper Studded Leather Gloves of the Fox', value: 'Dusk Whisper Studded Leather Gloves of the Fox' },
  { label: 'Ghoul Whisper Studded Leather Gloves of Titans', value: 'Ghoul Whisper Studded Leather Gloves of Titans' },
  { label: 'Havoc Tear Studded Leather Gloves of Detection', value: 'Havoc Tear Studded Leather Gloves of Detection' },
  { label: 'Honour Shout Hard Leather Gloves of Vitriol +1', value: 'Honour Shout Hard Leather Gloves of Vitriol +1' },
  { label: 'Hypnotic Sun Ornate Gauntlets of Enlightenment', value: 'Hypnotic Sun Ornate Gauntlets of Enlightenment' },
  { label: 'Apocalypse Glow Ornate Gauntlets of the Twins', value: 'Apocalypse Glow Ornate Gauntlets of the Twins' },
  { label: 'Apocalypse Sun Ornate Gauntlets of Reflection', value: 'Apocalypse Sun Ornate Gauntlets of Reflection' },
  { label: 'Apocalypse Tear Ornate Gauntlets of the Twins', value: 'Apocalypse Tear Ornate Gauntlets of the Twins' },
  { label: "Armageddon Bender Demon's Hands of the Fox +1", value: "Armageddon Bender Demon's Hands of the Fox +1" },
  { label: 'Behemoth Sun Studded Leather Gloves of Titans', value: 'Behemoth Sun Studded Leather Gloves of Titans' },
  { label: "Blight Bite Demon's Hands of Enlightenment +1", value: "Blight Bite Demon's Hands of Enlightenment +1" },
  { label: 'Blight Shout Hard Leather Gloves of Giants +1', value: 'Blight Shout Hard Leather Gloves of Giants +1' },
  { label: 'Bramble Glow Studded Leather Gloves of Giants', value: 'Bramble Glow Studded Leather Gloves of Giants' },
  { label: 'Cataclysm Moon Hard Leather Gloves of Rage +1', value: 'Cataclysm Moon Hard Leather Gloves of Rage +1' },
  { label: 'Dusk Glow Studded Leather Gloves of the Twins', value: 'Dusk Glow Studded Leather Gloves of the Twins' },
  { label: 'Eagle Grasp Hard Leather Gloves of Vitriol +1', value: 'Eagle Grasp Hard Leather Gloves of Vitriol +1' },
  { label: 'Fate Glow Studded Leather Gloves of the Twins', value: 'Fate Glow Studded Leather Gloves of the Twins' },
  { label: 'Foe Grasp Hard Leather Gloves of Detection +1', value: 'Foe Grasp Hard Leather Gloves of Detection +1' },
  { label: 'Foe Moon Hard Leather Gloves of Brilliance +1', value: 'Foe Moon Hard Leather Gloves of Brilliance +1' },
  { label: 'Grim Moon Hard Leather Gloves of Detection +1', value: 'Grim Moon Hard Leather Gloves of Detection +1' },
  { label: 'Honour Moon Hard Leather Gloves of Vitriol +1', value: 'Honour Moon Hard Leather Gloves of Vitriol +1' },
  { label: 'Kraken Bender Hard Leather Gloves of Power +1', value: 'Kraken Bender Hard Leather Gloves of Power +1' },
  { label: "Light's Whisper Linen Gloves of Enlightenment", value: "Light's Whisper Linen Gloves of Enlightenment" },
  { label: 'Maelstrom Tear Studded Leather Gloves of Rage', value: 'Maelstrom Tear Studded Leather Gloves of Rage' },
  { label: "Mind Bender Demon's Hands of Enlightenment +1", value: "Mind Bender Demon's Hands of Enlightenment +1" },
  { label: 'Oblivion Bite Silk Gloves of Enlightenment +1', value: 'Oblivion Bite Silk Gloves of Enlightenment +1' },
  { label: 'Oblivion Moon Hard Leather Gloves of Skill +1', value: 'Oblivion Moon Hard Leather Gloves of Skill +1' },
  { label: 'Oblivion Peak Hard Leather Gloves of Anger +1', value: 'Oblivion Peak Hard Leather Gloves of Anger +1' },
  { label: "Pandemonium Grasp Demon's Hands of Vitriol +1", value: "Pandemonium Grasp Demon's Hands of Vitriol +1" },
  { label: 'Armageddon Bite Silk Gloves of Reflection +1', value: 'Armageddon Bite Silk Gloves of Reflection +1' },
  { label: 'Armageddon Moon Silk Gloves of Protection +1', value: 'Armageddon Moon Silk Gloves of Protection +1' },
  { label: 'Death Whisper Ornate Gauntlets of Perfection', value: 'Death Whisper Ornate Gauntlets of Perfection' },
  { label: 'Dread Bite Hard Leather Gloves of the Fox +1', value: 'Dread Bite Hard Leather Gloves of the Fox +1' },
  { label: 'Dread Shout Hard Leather Gloves of Giants +1', value: 'Dread Shout Hard Leather Gloves of Giants +1' },
  { label: 'Ghoul Glow Studded Leather Gloves of Vitriol', value: 'Ghoul Glow Studded Leather Gloves of Vitriol' },
  { label: 'Gloom Bender Hard Leather Gloves of Power +1', value: 'Gloom Bender Hard Leather Gloves of Power +1' },
  { label: 'Golem Whisper Divine Gloves of Enlightenment', value: 'Golem Whisper Divine Gloves of Enlightenment' },
  { label: 'Havoc Roar Studded Leather Gloves of the Fox', value: 'Havoc Roar Studded Leather Gloves of the Fox' },
  { label: 'Havoc Whisper Ornate Gauntlets of Reflection', value: 'Havoc Whisper Ornate Gauntlets of Reflection' },
  { label: 'Honour Moon Hard Leather Gloves of Giants +1', value: 'Honour Moon Hard Leather Gloves of Giants +1' },
  { label: 'Honour Peak Hard Leather Gloves of Titans +1', value: 'Honour Peak Hard Leather Gloves of Titans +1' },
  { label: 'Maelstrom Sun Ornate Gauntlets of Reflection', value: 'Maelstrom Sun Ornate Gauntlets of Reflection' },
  { label: 'Mind Shout Hard Leather Gloves of Vitriol +1', value: 'Mind Shout Hard Leather Gloves of Vitriol +1' },
  { label: 'Plague Roar Studded Leather Gloves of Titans', value: 'Plague Roar Studded Leather Gloves of Titans' },
  { label: 'Apocalypse Root Divine Gloves of Brilliance', value: 'Apocalypse Root Divine Gloves of Brilliance' },
  { label: "Armageddon Grasp Demon's Hands of Giants +1", value: "Armageddon Grasp Demon's Hands of Giants +1" },
  { label: 'Carrion Sun Studded Leather Gloves of Power', value: 'Carrion Sun Studded Leather Gloves of Power' },
  { label: 'Corruption Moon Silk Gloves of Detection +1', value: 'Corruption Moon Silk Gloves of Detection +1' },
  { label: "Corruption Peak Demon's Hands of the Fox +1", value: "Corruption Peak Demon's Hands of the Fox +1" },
  { label: 'Dusk Roar Studded Leather Gloves of the Fox', value: 'Dusk Roar Studded Leather Gloves of the Fox' },
  { label: 'Fate Whisper Ornate Gauntlets of Reflection', value: 'Fate Whisper Ornate Gauntlets of Reflection' },
  { label: 'Ghoul Glow Studded Leather Gloves of Giants', value: 'Ghoul Glow Studded Leather Gloves of Giants' },
  { label: 'Grim Bender Hard Leather Gloves of Anger +1', value: 'Grim Bender Hard Leather Gloves of Anger +1' },
  { label: 'Honour Bite Hard Leather Gloves of Anger +1', value: 'Honour Bite Hard Leather Gloves of Anger +1' },
  { label: "Light's Whisper Divine Gloves of Perfection", value: "Light's Whisper Divine Gloves of Perfection" },
  { label: 'Mind Shout Hard Leather Gloves of Giants +1', value: 'Mind Shout Hard Leather Gloves of Giants +1' },
  { label: 'Morbid Root Studded Leather Gloves of Skill', value: 'Morbid Root Studded Leather Gloves of Skill' },
  { label: "Oblivion Moon Demon's Hands of the Twins +1", value: "Oblivion Moon Demon's Hands of the Twins +1" },
  { label: 'Pandemonium Bite Gauntlets of Perfection +1', value: 'Pandemonium Bite Gauntlets of Perfection +1' },
  { label: 'Apocalypse Root Divine Gloves of the Twins', value: 'Apocalypse Root Divine Gloves of the Twins' },
  { label: 'Apocalypse Root Heavy Gloves of Brilliance', value: 'Apocalypse Root Heavy Gloves of Brilliance' },
  { label: 'Apocalypse Root Heavy Gloves of Protection', value: 'Apocalypse Root Heavy Gloves of Protection' },
  { label: 'Apocalypse Root Linen Gloves of Brilliance', value: 'Apocalypse Root Linen Gloves of Brilliance' },
  { label: 'Apocalypse Tear Linen Gloves of Brilliance', value: 'Apocalypse Tear Linen Gloves of Brilliance' },
  { label: 'Armageddon Peak Gauntlets of Reflection +1', value: 'Armageddon Peak Gauntlets of Reflection +1' },
  { label: "Brimstone Shout Demon's Hands of Giants +1", value: "Brimstone Shout Demon's Hands of Giants +1" },
  { label: 'Brimstone Shout Gauntlets of Protection +1', value: 'Brimstone Shout Gauntlets of Protection +1' },
  { label: 'Carrion Sun Divine Gloves of Enlightenment', value: 'Carrion Sun Divine Gloves of Enlightenment' },
  { label: 'Carrion Tear Ornate Gauntlets of Detection', value: 'Carrion Tear Ornate Gauntlets of Detection' },
  { label: "Cataclysm Bender Demon's Hands of Power +1", value: "Cataclysm Bender Demon's Hands of Power +1" },
  { label: 'Cataclysm Bender Silk Gloves of the Fox +1', value: 'Cataclysm Bender Silk Gloves of the Fox +1' },
  { label: "Cataclysm Bite Demon's Hands of the Fox +1", value: "Cataclysm Bite Demon's Hands of the Fox +1" },
  { label: 'Corpse Roar Studded Leather Gloves of Fury', value: 'Corpse Roar Studded Leather Gloves of Fury' },
  { label: 'Corpse Sun Studded Leather Gloves of Anger', value: 'Corpse Sun Studded Leather Gloves of Anger' },
  { label: 'Corpse Tear Ornate Gauntlets of Protection', value: 'Corpse Tear Ornate Gauntlets of Protection' },
  { label: 'Corpse Whisper Ornate Gauntlets of the Fox', value: 'Corpse Whisper Ornate Gauntlets of the Fox' },
  { label: 'Death Glow Studded Leather Gloves of Skill', value: 'Death Glow Studded Leather Gloves of Skill' },
  { label: 'Demon Peak Hard Leather Gloves of Anger +1', value: 'Demon Peak Hard Leather Gloves of Anger +1' },
  { label: 'Dragon Glow Ornate Gauntlets of Protection', value: 'Dragon Glow Ornate Gauntlets of Protection' },
  { label: 'Dragon Root Ornate Gauntlets of Brilliance', value: 'Dragon Root Ornate Gauntlets of Brilliance' },
  { label: 'Dragon Root Studded Leather Gloves of Rage', value: 'Dragon Root Studded Leather Gloves of Rage' },
  { label: 'Dread Bite Silk Gloves of Enlightenment +1', value: 'Dread Bite Silk Gloves of Enlightenment +1' },
  { label: 'Eagle Grasp Hard Leather Gloves of Rage +1', value: 'Eagle Grasp Hard Leather Gloves of Rage +1' },
  { label: 'Gloom Bite Hard Leather Gloves of Power +1', value: 'Gloom Bite Hard Leather Gloves of Power +1' },
  { label: 'Honour Bender Silk Gloves of Perfection +1', value: 'Honour Bender Silk Gloves of Perfection +1' },
  { label: "Light's Whisper Linen Gloves of Perfection", value: "Light's Whisper Linen Gloves of Perfection" },
  { label: 'Maelstrom Root Divine Gloves of Protection', value: 'Maelstrom Root Divine Gloves of Protection' },
  { label: 'Mind Bite Hard Leather Gloves of Titans +1', value: 'Mind Bite Hard Leather Gloves of Titans +1' },
  { label: 'Oblivion Bender Gauntlets of Reflection +1', value: 'Oblivion Bender Gauntlets of Reflection +1' },
  { label: 'Pain Glow Studded Leather Gloves of Giants', value: 'Pain Glow Studded Leather Gloves of Giants' },
  { label: 'Pain Root Studded Leather Gloves of Giants', value: 'Pain Root Studded Leather Gloves of Giants' },
  { label: 'Plague Glow Ornate Gauntlets of Brilliance', value: 'Plague Glow Ornate Gauntlets of Brilliance' },
  { label: 'Plague Sun Studded Leather Gloves of Power', value: 'Plague Sun Studded Leather Gloves of Power' },
  { label: 'Apocalypse Glow Linen Gloves of the Twins', value: 'Apocalypse Glow Linen Gloves of the Twins' },
  { label: 'Apocalypse Root Heavy Gloves of the Twins', value: 'Apocalypse Root Heavy Gloves of the Twins' },
  { label: 'Apocalypse Root Linen Gloves of the Twins', value: 'Apocalypse Root Linen Gloves of the Twins' },
  { label: 'Apocalypse Sun Heavy Gloves of Reflection', value: 'Apocalypse Sun Heavy Gloves of Reflection' },
  { label: "Armageddon Moon Demon's Hands of Skill +1", value: "Armageddon Moon Demon's Hands of Skill +1" },
  { label: 'Armageddon Shout Silk Gloves of Giants +1', value: 'Armageddon Shout Silk Gloves of Giants +1' },
  { label: 'Behemoth Tear Ornate Gauntlets of Vitriol', value: 'Behemoth Tear Ornate Gauntlets of Vitriol' },
  { label: 'Brimstone Bender Silk Gloves of Titans +1', value: 'Brimstone Bender Silk Gloves of Titans +1' },
  { label: "Brimstone Shout Demon's Hands of Skill +1", value: "Brimstone Shout Demon's Hands of Skill +1" },
  { label: "Cataclysm Bite Demon's Hands of Titans +1", value: "Cataclysm Bite Demon's Hands of Titans +1" },
  { label: 'Corpse Whisper Linen Gloves of Reflection', value: 'Corpse Whisper Linen Gloves of Reflection' },
  { label: 'Dragon Tear Ornate Gauntlets of Detection', value: 'Dragon Tear Ornate Gauntlets of Detection' },
  { label: 'Dread Bender Silk Gloves of Perfection +1', value: 'Dread Bender Silk Gloves of Perfection +1' },
  { label: 'Fate Roar Studded Leather Gloves of Anger', value: 'Fate Roar Studded Leather Gloves of Anger' },
  { label: 'Ghoul Glow Ornate Gauntlets of Protection', value: 'Ghoul Glow Ornate Gauntlets of Protection' },
  { label: 'Ghoul Roar Studded Leather Gloves of Fury', value: 'Ghoul Roar Studded Leather Gloves of Fury' },
  { label: 'Ghoul Root Ornate Gauntlets of Brilliance', value: 'Ghoul Root Ornate Gauntlets of Brilliance' },
  { label: "Gloom Bite Demon's Hands of Reflection +1", value: "Gloom Bite Demon's Hands of Reflection +1" },
  { label: "Gloom Shout Demon's Hands of Detection +1", value: "Gloom Shout Demon's Hands of Detection +1" },
  { label: 'Golem Glow Ornate Gauntlets of Brilliance', value: 'Golem Glow Ornate Gauntlets of Brilliance' },
  { label: 'Golem Tear Ornate Gauntlets of Brilliance', value: 'Golem Tear Ornate Gauntlets of Brilliance' },
  { label: 'Grim Bite Hard Leather Gloves of Power +1', value: 'Grim Bite Hard Leather Gloves of Power +1' },
  { label: 'Havoc Whisper Ornate Gauntlets of the Fox', value: 'Havoc Whisper Ornate Gauntlets of the Fox' },
  { label: 'Hypnotic Roar Ornate Gauntlets of the Fox', value: 'Hypnotic Roar Ornate Gauntlets of the Fox' },
  { label: 'Maelstrom Roar Linen Gloves of Perfection', value: 'Maelstrom Roar Linen Gloves of Perfection' },
  { label: 'Morbid Sun Studded Leather Gloves of Fury', value: 'Morbid Sun Studded Leather Gloves of Fury' },
  { label: 'Morbid Whisper Linen Gloves of Reflection', value: 'Morbid Whisper Linen Gloves of Reflection' },
  { label: "Pandemonium Bite Demon's Hands of Fury +1", value: "Pandemonium Bite Demon's Hands of Fury +1" },
  { label: 'Pandemonium Shout Gauntlets of Vitriol +1', value: 'Pandemonium Shout Gauntlets of Vitriol +1' },
  { label: 'Apocalypse Roar Divine Gloves of the Fox', value: 'Apocalypse Roar Divine Gloves of the Fox' },
  { label: 'Armageddon Grasp Gloves of Brilliance +1', value: 'Armageddon Grasp Gloves of Brilliance +1' },
  { label: 'Armageddon Shout Gauntlets of Vitriol +1', value: 'Armageddon Shout Gauntlets of Vitriol +1' },
  { label: 'Behemoth Glow Heavy Gloves of Brilliance', value: 'Behemoth Glow Heavy Gloves of Brilliance' },
  { label: 'Behemoth Roar Linen Gloves of Reflection', value: 'Behemoth Roar Linen Gloves of Reflection' },
  { label: 'Behemoth Whisper Linen Gloves of the Fox', value: 'Behemoth Whisper Linen Gloves of the Fox' },
  { label: 'Blight Moon Silk Gloves of Protection +1', value: 'Blight Moon Silk Gloves of Protection +1' },
  { label: "Brimstone Bite Demon's Hands of Power +1", value: "Brimstone Bite Demon's Hands of Power +1" },
  { label: "Brimstone Peak Demon's Hands of Anger +1", value: "Brimstone Peak Demon's Hands of Anger +1" },
  { label: 'Carrion Glow Divine Gloves of Protection', value: 'Carrion Glow Divine Gloves of Protection' },
  { label: 'Cataclysm Bender Gloves of Reflection +1', value: 'Cataclysm Bender Gloves of Reflection +1' },
  { label: 'Cataclysm Peak Silk Gloves of the Fox +1', value: 'Cataclysm Peak Silk Gloves of the Fox +1' },
  { label: 'Corruption Grasp Gauntlets of Vitriol +1', value: 'Corruption Grasp Gauntlets of Vitriol +1' },
  { label: 'Corruption Moon Silk Gloves of Giants +1', value: 'Corruption Moon Silk Gloves of Giants +1' },
  { label: 'Death Sun Studded Leather Gloves of Fury', value: 'Death Sun Studded Leather Gloves of Fury' },
  { label: "Demon Bender Demon's Hands of the Fox +1", value: "Demon Bender Demon's Hands of the Fox +1" },
  { label: 'Demon Grasp Silk Gloves of Brilliance +1', value: 'Demon Grasp Silk Gloves of Brilliance +1' },
  { label: 'Dread Shout Silk Gloves of Brilliance +1', value: 'Dread Shout Silk Gloves of Brilliance +1' },
  { label: 'Dusk Root Studded Leather Gloves of Rage', value: 'Dusk Root Studded Leather Gloves of Rage' },
  { label: 'Ghoul Sun Divine Gloves of Enlightenment', value: 'Ghoul Sun Divine Gloves of Enlightenment' },
  { label: 'Golem Roar Heavy Gloves of Enlightenment', value: 'Golem Roar Heavy Gloves of Enlightenment' },
  { label: 'Golem Tear Ornate Gauntlets of the Twins', value: 'Golem Tear Ornate Gauntlets of the Twins' },
  { label: "Grim Moon Demon's Hands of Protection +1", value: "Grim Moon Demon's Hands of Protection +1" },
  { label: 'Havoc Sun Ornate Gauntlets of Perfection', value: 'Havoc Sun Ornate Gauntlets of Perfection' },
  { label: 'Havoc Whisper Heavy Gloves of Reflection', value: 'Havoc Whisper Heavy Gloves of Reflection' },
  { label: 'Hypnotic Tear Divine Gloves of Detection', value: 'Hypnotic Tear Divine Gloves of Detection' },
  { label: 'Hypnotic Tear Ornate Gauntlets of Giants', value: 'Hypnotic Tear Ornate Gauntlets of Giants' },
  { label: "Light's Glow Divine Gloves of Brilliance", value: "Light's Glow Divine Gloves of Brilliance" },
  { label: 'Maelstrom Root Linen Gloves of Detection', value: 'Maelstrom Root Linen Gloves of Detection' },
  { label: 'Maelstrom Whisper Heavy Gloves of Titans', value: 'Maelstrom Whisper Heavy Gloves of Titans' },
  { label: 'Mind Bender Silk Gloves of Perfection +1', value: 'Mind Bender Silk Gloves of Perfection +1' },
  { label: "Mind Moon Demon's Hands of Protection +1", value: "Mind Moon Demon's Hands of Protection +1" },
  { label: 'Oblivion Bite Gloves of Enlightenment +1', value: 'Oblivion Bite Gloves of Enlightenment +1' },
  { label: 'Oblivion Grasp Gauntlets of the Twins +1', value: 'Oblivion Grasp Gauntlets of the Twins +1' },
  { label: 'Oblivion Peak Gauntlets of Reflection +1', value: 'Oblivion Peak Gauntlets of Reflection +1' },
  { label: "Oblivion Shout Demon's Hands of Skill +1", value: "Oblivion Shout Demon's Hands of Skill +1" },
  { label: 'Pain Glow Ornate Gauntlets of Protection', value: 'Pain Glow Ornate Gauntlets of Protection' },
  { label: 'Pain Glow Studded Leather Gloves of Rage', value: 'Pain Glow Studded Leather Gloves of Rage' },
  { label: 'Pain Roar Ornate Gauntlets of Perfection', value: 'Pain Roar Ornate Gauntlets of Perfection' },
  { label: 'Pain Root Ornate Gauntlets of Brilliance', value: 'Pain Root Ornate Gauntlets of Brilliance' },
  { label: 'Pandemonium Moon Gloves of Brilliance +1', value: 'Pandemonium Moon Gloves of Brilliance +1' },
  { label: 'Apocalypse Glow Divine Gloves of Giants', value: 'Apocalypse Glow Divine Gloves of Giants' },
  { label: 'Apocalypse Whisper Heavy Gloves of Fury', value: 'Apocalypse Whisper Heavy Gloves of Fury' },
  { label: 'Armageddon Moon Gauntlets of Vitriol +1', value: 'Armageddon Moon Gauntlets of Vitriol +1' },
  { label: 'Behemoth Glow Linen Gloves of the Twins', value: 'Behemoth Glow Linen Gloves of the Twins' },
  { label: 'Behemoth Sun Heavy Gloves of Perfection', value: 'Behemoth Sun Heavy Gloves of Perfection' },
  { label: "Blight Grasp Demon's Hands of Giants +1", value: "Blight Grasp Demon's Hands of Giants +1" },
  { label: 'Bramble Glow Linen Gloves of Brilliance', value: 'Bramble Glow Linen Gloves of Brilliance' },
  { label: 'Carrion Glow Ornate Gauntlets of Giants', value: 'Carrion Glow Ornate Gauntlets of Giants' },
  { label: 'Carrion Roar Linen Gloves of Reflection', value: 'Carrion Roar Linen Gloves of Reflection' },
  { label: 'Carrion Root Heavy Gloves of Brilliance', value: 'Carrion Root Heavy Gloves of Brilliance' },
  { label: 'Cataclysm Shout Gloves of Brilliance +1', value: 'Cataclysm Shout Gloves of Brilliance +1' },
  { label: 'Corruption Bender Gauntlets of Power +1', value: 'Corruption Bender Gauntlets of Power +1' },
  { label: 'Corruption Bite Gloves of Reflection +1', value: 'Corruption Bite Gloves of Reflection +1' },
  { label: 'Death Whisper Ornate Gauntlets of Anger', value: 'Death Whisper Ornate Gauntlets of Anger' },
  { label: 'Demon Bender Gloves of Enlightenment +1', value: 'Demon Bender Gloves of Enlightenment +1' },
  { label: 'Demon Shout Silk Gloves of the Twins +1', value: 'Demon Shout Silk Gloves of the Twins +1' },
  { label: 'Dread Grasp Silk Gloves of Detection +1', value: 'Dread Grasp Silk Gloves of Detection +1' },
  { label: 'Eagle Bite Silk Gloves of Perfection +1', value: 'Eagle Bite Silk Gloves of Perfection +1' },
  { label: 'Eagle Grasp Silk Gloves of the Twins +1', value: 'Eagle Grasp Silk Gloves of the Twins +1' },
  { label: "Eagle Shout Demon's Hands of Vitriol +1", value: "Eagle Shout Demon's Hands of Vitriol +1" },
  { label: 'Fate Whisper Heavy Gloves of Reflection', value: 'Fate Whisper Heavy Gloves of Reflection' },
  { label: 'Foe Bite Hard Leather Gloves of Fury +1', value: 'Foe Bite Hard Leather Gloves of Fury +1' },
  { label: "Foe Moon Demon's Hands of Brilliance +1", value: "Foe Moon Demon's Hands of Brilliance +1" },
  { label: "Gloom Bender Demon's Hands of Titans +1", value: "Gloom Bender Demon's Hands of Titans +1" },
  { label: 'Golem Sun Linen Gloves of Enlightenment', value: 'Golem Sun Linen Gloves of Enlightenment' },
  { label: 'Havoc Whisper Ornate Gauntlets of Power', value: 'Havoc Whisper Ornate Gauntlets of Power' },
  { label: 'Hypnotic Tear Ornate Gauntlets of Skill', value: 'Hypnotic Tear Ornate Gauntlets of Skill' },
  { label: 'Kraken Bender Silk Gloves of the Fox +1', value: 'Kraken Bender Silk Gloves of the Fox +1' },
  { label: "Light's Sun Divine Gloves of Perfection", value: "Light's Sun Divine Gloves of Perfection" },
  { label: "Light's Tear Linen Gloves of Brilliance", value: "Light's Tear Linen Gloves of Brilliance" },
  { label: "Light's Tear Linen Gloves of Protection", value: "Light's Tear Linen Gloves of Protection" },
  { label: 'Maelstrom Root Divine Gloves of Vitriol', value: 'Maelstrom Root Divine Gloves of Vitriol' },
  { label: 'Mind Peak Gauntlets of Enlightenment +1', value: 'Mind Peak Gauntlets of Enlightenment +1' },
  { label: 'Morbid Glow Ornate Gauntlets of Vitriol', value: 'Morbid Glow Ornate Gauntlets of Vitriol' },
  { label: 'Oblivion Bender Silk Gloves of Anger +1', value: 'Oblivion Bender Silk Gloves of Anger +1' },
  { label: 'Oblivion Moon Gauntlets of the Twins +1', value: 'Oblivion Moon Gauntlets of the Twins +1' },
  { label: 'Pandemonium Moon Silk Gloves of Rage +1', value: 'Pandemonium Moon Silk Gloves of Rage +1' },
  { label: 'Pandemonium Peak Silk Gloves of Fury +1', value: 'Pandemonium Peak Silk Gloves of Fury +1' },
  { label: 'Plague Root Divine Gloves of Brilliance', value: 'Plague Root Divine Gloves of Brilliance' },
  { label: 'Plague Whisper Divine Gloves of the Fox', value: 'Plague Whisper Divine Gloves of the Fox' },
  { label: 'Plague Whisper Ornate Gauntlets of Fury', value: 'Plague Whisper Ornate Gauntlets of Fury' },
  { label: 'Behemoth Whisper Heavy Gloves of Anger', value: 'Behemoth Whisper Heavy Gloves of Anger' },
  { label: 'Behemoth Whisper Heavy Gloves of Power', value: 'Behemoth Whisper Heavy Gloves of Power' },
  { label: "Blight Bender Demon's Hands of Fury +1", value: "Blight Bender Demon's Hands of Fury +1" },
  { label: 'Blight Peak Gauntlets of Reflection +1', value: 'Blight Peak Gauntlets of Reflection +1' },
  { label: 'Bramble Glow Heavy Gloves of the Twins', value: 'Bramble Glow Heavy Gloves of the Twins' },
  { label: 'Brimstone Peak Gloves of Reflection +1', value: 'Brimstone Peak Gloves of Reflection +1' },
  { label: 'Cataclysm Bite Silk Gloves of Anger +1', value: 'Cataclysm Bite Silk Gloves of Anger +1' },
  { label: 'Cataclysm Peak Gloves of Perfection +1', value: 'Cataclysm Peak Gloves of Perfection +1' },
  { label: 'Cataclysm Shout Gauntlets of Giants +1', value: 'Cataclysm Shout Gauntlets of Giants +1' },
  { label: 'Dragon Roar Linen Gloves of Perfection', value: 'Dragon Roar Linen Gloves of Perfection' },
  { label: 'Dragon Roar Linen Gloves of Reflection', value: 'Dragon Roar Linen Gloves of Reflection' },
  { label: 'Dragon Root Divine Gloves of Detection', value: 'Dragon Root Divine Gloves of Detection' },
  { label: 'Dragon Tear Heavy Gloves of Protection', value: 'Dragon Tear Heavy Gloves of Protection' },
  { label: "Eagle Moon Demon's Hands of Vitriol +1", value: "Eagle Moon Demon's Hands of Vitriol +1" },
  { label: 'Foe Shout Silk Gloves of Protection +1', value: 'Foe Shout Silk Gloves of Protection +1' },
  { label: "Gloom Bender Demon's Hands of Anger +1", value: "Gloom Bender Demon's Hands of Anger +1" },
  { label: "Gloom Bender Demon's Hands of Power +1", value: "Gloom Bender Demon's Hands of Power +1" },
  { label: 'Golem Roar Divine Gloves of Reflection', value: 'Golem Roar Divine Gloves of Reflection' },
  { label: 'Golem Root Divine Gloves of Brilliance', value: 'Golem Root Divine Gloves of Brilliance' },
  { label: 'Havoc Whisper Ornate Gauntlets of Fury', value: 'Havoc Whisper Ornate Gauntlets of Fury' },
  { label: 'Honour Bender Silk Gloves of Titans +1', value: 'Honour Bender Silk Gloves of Titans +1' },
  { label: 'Honour Peak Gauntlets of Perfection +1', value: 'Honour Peak Gauntlets of Perfection +1' },
  { label: 'Hypnotic Sun Ornate Gauntlets of Anger', value: 'Hypnotic Sun Ornate Gauntlets of Anger' },
  { label: 'Hypnotic Tear Ornate Gauntlets of Rage', value: 'Hypnotic Tear Ornate Gauntlets of Rage' },
  { label: 'Kraken Peak Gauntlets of Reflection +1', value: 'Kraken Peak Gauntlets of Reflection +1' },
  { label: 'Maelstrom Root Heavy Gloves of Vitriol', value: 'Maelstrom Root Heavy Gloves of Vitriol' },
  { label: 'Morbid Tear Heavy Gloves of Brilliance', value: 'Morbid Tear Heavy Gloves of Brilliance' },
  { label: 'Pain Sun Heavy Gloves of Enlightenment', value: 'Pain Sun Heavy Gloves of Enlightenment' },
  { label: 'Pandemonium Moon Gauntlets of Skill +1', value: 'Pandemonium Moon Gauntlets of Skill +1' },
  { label: 'Apocalypse Roar Linen Gloves of Power', value: 'Apocalypse Roar Linen Gloves of Power' },
  { label: 'Armageddon Grasp Gauntlets of Rage +1', value: 'Armageddon Grasp Gauntlets of Rage +1' },
  { label: 'Armageddon Grasp Gloves of Vitriol +1', value: 'Armageddon Grasp Gloves of Vitriol +1' },
  { label: 'Brimstone Bite Gauntlets of Titans +1', value: 'Brimstone Bite Gauntlets of Titans +1' },
  { label: 'Carrion Whisper Divine Gloves of Fury', value: 'Carrion Whisper Divine Gloves of Fury' },
  { label: 'Corpse Tear Heavy Gloves of the Twins', value: 'Corpse Tear Heavy Gloves of the Twins' },
  { label: 'Dragon Root Linen Gloves of the Twins', value: 'Dragon Root Linen Gloves of the Twins' },
  { label: 'Eagle Grasp Gauntlets of the Twins +1', value: 'Eagle Grasp Gauntlets of the Twins +1' },
  { label: 'Foe Grasp Silk Gloves of the Twins +1', value: 'Foe Grasp Silk Gloves of the Twins +1' },
  { label: 'Foe Moon Silk Gloves of Protection +1', value: 'Foe Moon Silk Gloves of Protection +1' },
  { label: 'Ghoul Glow Heavy Gloves of Brilliance', value: 'Ghoul Glow Heavy Gloves of Brilliance' },
  { label: 'Ghoul Root Divine Gloves of the Twins', value: 'Ghoul Root Divine Gloves of the Twins' },
  { label: "Gloom Shout Demon's Hands of Skill +1", value: "Gloom Shout Demon's Hands of Skill +1" },
  { label: 'Golem Glow Divine Gloves of Detection', value: 'Golem Glow Divine Gloves of Detection' },
  { label: 'Golem Glow Heavy Gloves of Protection', value: 'Golem Glow Heavy Gloves of Protection' },
  { label: 'Golem Glow Linen Gloves of Protection', value: 'Golem Glow Linen Gloves of Protection' },
  { label: 'Golem Root Heavy Gloves of Brilliance', value: 'Golem Root Heavy Gloves of Brilliance' },
  { label: "Grim Grasp Demon's Hands of Giants +1", value: "Grim Grasp Demon's Hands of Giants +1" },
  { label: 'Havoc Glow Divine Gloves of Detection', value: 'Havoc Glow Divine Gloves of Detection' },
  { label: 'Havoc Root Linen Gloves of Protection', value: 'Havoc Root Linen Gloves of Protection' },
  { label: 'Havoc Tear Divine Gloves of Detection', value: 'Havoc Tear Divine Gloves of Detection' },
  { label: 'Honour Bender Gloves of Perfection +1', value: 'Honour Bender Gloves of Perfection +1' },
  { label: 'Kraken Bender Silk Gloves of Power +1', value: 'Kraken Bender Silk Gloves of Power +1' },
  { label: 'Kraken Bite Silk Gloves of the Fox +1', value: 'Kraken Bite Silk Gloves of the Fox +1' },
  { label: 'Kraken Grasp Silk Gloves of Giants +1', value: 'Kraken Grasp Silk Gloves of Giants +1' },
  { label: 'Kraken Moon Gauntlets of Detection +1', value: 'Kraken Moon Gauntlets of Detection +1' },
  { label: "Light's Whisper Heavy Gloves of Anger", value: "Light's Whisper Heavy Gloves of Anger" },
  { label: 'Morbid Sun Heavy Gloves of Perfection', value: 'Morbid Sun Heavy Gloves of Perfection' },
  { label: 'Morbid Whisper Divine Gloves of Anger', value: 'Morbid Whisper Divine Gloves of Anger' },
  { label: 'Oblivion Peak Gauntlets of the Fox +1', value: 'Oblivion Peak Gauntlets of the Fox +1' },
  { label: 'Pandemonium Moon Gauntlets of Rage +1', value: 'Pandemonium Moon Gauntlets of Rage +1' },
  { label: 'Plague Glow Linen Gloves of Detection', value: 'Plague Glow Linen Gloves of Detection' },
  { label: 'Plague Tear Heavy Gloves of Detection', value: 'Plague Tear Heavy Gloves of Detection' },
  { label: 'Behemoth Roar Linen Gloves of Titans', value: 'Behemoth Roar Linen Gloves of Titans' },
  { label: 'Bramble Root Divine Gloves of Giants', value: 'Bramble Root Divine Gloves of Giants' },
  { label: 'Brimstone Grasp Gauntlets of Rage +1', value: 'Brimstone Grasp Gauntlets of Rage +1' },
  { label: 'Brimstone Moon Gauntlets of Skill +1', value: 'Brimstone Moon Gauntlets of Skill +1' },
  { label: 'Carrion Sun Ornate Gauntlets of Fury', value: 'Carrion Sun Ornate Gauntlets of Fury' },
  { label: 'Carrion Whisper Linen Gloves of Fury', value: 'Carrion Whisper Linen Gloves of Fury' },
  { label: 'Cataclysm Peak Gauntlets of Anger +1', value: 'Cataclysm Peak Gauntlets of Anger +1' },
  { label: 'Corpse Whisper Linen Gloves of Anger', value: 'Corpse Whisper Linen Gloves of Anger' },
  { label: 'Corruption Moon Gloves of Vitriol +1', value: 'Corruption Moon Gloves of Vitriol +1' },
  { label: 'Death Root Heavy Gloves of Detection', value: 'Death Root Heavy Gloves of Detection' },
  { label: "Demon Grasp Demon's Hands of Rage +1", value: "Demon Grasp Demon's Hands of Rage +1" },
  { label: "Demon Moon Demon's Hands of Skill +1", value: "Demon Moon Demon's Hands of Skill +1" },
  { label: 'Dragon Glow Divine Gloves of Vitriol', value: 'Dragon Glow Divine Gloves of Vitriol' },
  { label: 'Dread Bender Gloves of Reflection +1', value: 'Dread Bender Gloves of Reflection +1' },
  { label: 'Dusk Roar Linen Gloves of Perfection', value: 'Dusk Roar Linen Gloves of Perfection' },
  { label: 'Eagle Bender Gloves of Reflection +1', value: 'Eagle Bender Gloves of Reflection +1' },
  { label: 'Fate Roar Linen Gloves of Perfection', value: 'Fate Roar Linen Gloves of Perfection' },
  { label: "Foe Bender Demon's Hands of Anger +1", value: "Foe Bender Demon's Hands of Anger +1" },
  { label: "Foe Bender Demon's Hands of Power +1", value: "Foe Bender Demon's Hands of Power +1" },
  { label: 'Ghoul Glow Linen Gloves of Detection', value: 'Ghoul Glow Linen Gloves of Detection' },
  { label: 'Ghoul Root Heavy Gloves of Detection', value: 'Ghoul Root Heavy Gloves of Detection' },
  { label: 'Ghoul Root Linen Gloves of Detection', value: 'Ghoul Root Linen Gloves of Detection' },
  { label: 'Ghoul Tear Heavy Gloves of Detection', value: 'Ghoul Tear Heavy Gloves of Detection' },
  { label: 'Ghoul Whisper Linen Gloves of Titans', value: 'Ghoul Whisper Linen Gloves of Titans' },
  { label: 'Gloom Bender Gloves of Perfection +1', value: 'Gloom Bender Gloves of Perfection +1' },
  { label: 'Golem Sun Linen Gloves of Reflection', value: 'Golem Sun Linen Gloves of Reflection' },
  { label: "Grim Grasp Demon's Hands of Skill +1", value: "Grim Grasp Demon's Hands of Skill +1" },
  { label: "Grim Shout Demon's Hands of Skill +1", value: "Grim Shout Demon's Hands of Skill +1" },
  { label: 'Havoc Tear Heavy Gloves of the Twins', value: 'Havoc Tear Heavy Gloves of the Twins' },
  { label: 'Kraken Bender Silk Gloves of Fury +1', value: 'Kraken Bender Silk Gloves of Fury +1' },
  { label: "Light's Roar Heavy Gloves of the Fox", value: "Light's Roar Heavy Gloves of the Fox" },
  { label: 'Maelstrom Tear Heavy Gloves of Skill', value: 'Maelstrom Tear Heavy Gloves of Skill' },
  { label: "Mind Grasp Demon's Hands of Skill +1", value: "Mind Grasp Demon's Hands of Skill +1" },
  { label: 'Mind Peak Gloves of Enlightenment +1', value: 'Mind Peak Gloves of Enlightenment +1' },
  { label: 'Morbid Whisper Linen Gloves of Anger', value: 'Morbid Whisper Linen Gloves of Anger' },
  { label: 'Pain Roar Ornate Gauntlets of Titans', value: 'Pain Roar Ornate Gauntlets of Titans' },
  { label: 'Pain Root Divine Gloves of the Twins', value: 'Pain Root Divine Gloves of the Twins' },
  { label: 'Pandemonium Grasp Gloves of Skill +1', value: 'Pandemonium Grasp Gloves of Skill +1' },
  { label: 'Plague Tear Divine Gloves of Vitriol', value: 'Plague Tear Divine Gloves of Vitriol' },
  { label: 'Armageddon Bender Gloves of Fury +1', value: 'Armageddon Bender Gloves of Fury +1' },
  { label: 'Behemoth Glow Heavy Gloves of Skill', value: 'Behemoth Glow Heavy Gloves of Skill' },
  { label: 'Behemoth Root Heavy Gloves of Skill', value: 'Behemoth Root Heavy Gloves of Skill' },
  { label: 'Behemoth Sun Divine Gloves of Power', value: 'Behemoth Sun Divine Gloves of Power' },
  { label: 'Blight Bite Gloves of Reflection +1', value: 'Blight Bite Gloves of Reflection +1' },
  { label: 'Blight Peak Silk Gloves of Anger +1', value: 'Blight Peak Silk Gloves of Anger +1' },
  { label: 'Carrion Root Divine Gloves of Skill', value: 'Carrion Root Divine Gloves of Skill' },
  { label: 'Carrion Tear Heavy Gloves of Giants', value: 'Carrion Tear Heavy Gloves of Giants' },
  { label: 'Carrion Tear Linen Gloves of Giants', value: 'Carrion Tear Linen Gloves of Giants' },
  { label: 'Corpse Tear Heavy Gloves of Vitriol', value: 'Corpse Tear Heavy Gloves of Vitriol' },
  { label: 'Corpse Whisper Linen Gloves of Fury', value: 'Corpse Whisper Linen Gloves of Fury' },
  { label: 'Death Tear Divine Gloves of Vitriol', value: 'Death Tear Divine Gloves of Vitriol' },
  { label: 'Demon Grasp Gauntlets of Vitriol +1', value: 'Demon Grasp Gauntlets of Vitriol +1' },
  { label: "Demon Moon Demon's Hands of Rage +1", value: "Demon Moon Demon's Hands of Rage +1" },
  { label: 'Dragon Roar Heavy Gloves of the Fox', value: 'Dragon Roar Heavy Gloves of the Fox' },
  { label: 'Dread Bender Gauntlets of Titans +1', value: 'Dread Bender Gauntlets of Titans +1' },
  { label: "Eagle Moon Demon's Hands of Rage +1", value: "Eagle Moon Demon's Hands of Rage +1" },
  { label: 'Fate Root Heavy Gloves of Detection', value: 'Fate Root Heavy Gloves of Detection' },
  { label: 'Fate Sun Heavy Gloves of Perfection', value: 'Fate Sun Heavy Gloves of Perfection' },
  { label: 'Fate Sun Linen Gloves of Reflection', value: 'Fate Sun Linen Gloves of Reflection' },
  { label: "Foe Bite Demon's Hands of Titans +1", value: "Foe Bite Demon's Hands of Titans +1" },
  { label: 'Foe Moon Gauntlets of Brilliance +1', value: 'Foe Moon Gauntlets of Brilliance +1' },
  { label: 'Foe Peak Gauntlets of Perfection +1', value: 'Foe Peak Gauntlets of Perfection +1' },
  { label: 'Golem Glow Ornate Gauntlets of Rage', value: 'Golem Glow Ornate Gauntlets of Rage' },
  { label: 'Grim Bite Silk Gloves of the Fox +1', value: 'Grim Bite Silk Gloves of the Fox +1' },
  { label: 'Honour Bite Gloves of Reflection +1', value: 'Honour Bite Gloves of Reflection +1' },
  { label: 'Honour Grasp Gauntlets of Giants +1', value: 'Honour Grasp Gauntlets of Giants +1' },
  { label: 'Kraken Grasp Gauntlets of Giants +1', value: 'Kraken Grasp Gauntlets of Giants +1' },
  { label: 'Kraken Peak Gloves of Reflection +1', value: 'Kraken Peak Gloves of Reflection +1' },
  { label: "Light's Roar Divine Gloves of Anger", value: "Light's Roar Divine Gloves of Anger" },
  { label: "Light's Roar Linen Gloves of Titans", value: "Light's Roar Linen Gloves of Titans" },
  { label: "Light's Sun Heavy Gloves of the Fox", value: "Light's Sun Heavy Gloves of the Fox" },
  { label: 'Maelstrom Sun Linen Gloves of Anger', value: 'Maelstrom Sun Linen Gloves of Anger' },
  { label: 'Mind Bender Gloves of Perfection +1', value: 'Mind Bender Gloves of Perfection +1' },
  { label: 'Morbid Roar Heavy Gloves of the Fox', value: 'Morbid Roar Heavy Gloves of the Fox' },
  { label: 'Oblivion Peak Gauntlets of Anger +1', value: 'Oblivion Peak Gauntlets of Anger +1' },
  { label: 'Oblivion Shout Gloves of Vitriol +1', value: 'Oblivion Shout Gloves of Vitriol +1' },
  { label: 'Pain Glow Linen Gloves of Detection', value: 'Pain Glow Linen Gloves of Detection' },
  { label: 'Pain Whisper Divine Gloves of Power', value: 'Pain Whisper Divine Gloves of Power' },
  { label: 'Pain Whisper Linen Gloves of Titans', value: 'Pain Whisper Linen Gloves of Titans' },
  { label: 'Pandemonium Moon Gloves of Skill +1', value: 'Pandemonium Moon Gloves of Skill +1' },
  { label: 'Armageddon Grasp Gloves of Rage +1', value: 'Armageddon Grasp Gloves of Rage +1' },
  { label: 'Carrion Roar Heavy Gloves of Power', value: 'Carrion Roar Heavy Gloves of Power' },
  { label: 'Carrion Roar Linen Gloves of Anger', value: 'Carrion Roar Linen Gloves of Anger' },
  { label: 'Carrion Tear Heavy Gloves of Skill', value: 'Carrion Tear Heavy Gloves of Skill' },
  { label: 'Cataclysm Bite Gloves of Titans +1', value: 'Cataclysm Bite Gloves of Titans +1' },
  { label: 'Corpse Glow Linen Gloves of Giants', value: 'Corpse Glow Linen Gloves of Giants' },
  { label: 'Corpse Roar Divine Gloves of Anger', value: 'Corpse Roar Divine Gloves of Anger' },
  { label: 'Corruption Bite Gloves of Anger +1', value: 'Corruption Bite Gloves of Anger +1' },
  { label: 'Death Roar Linen Gloves of the Fox', value: 'Death Roar Linen Gloves of the Fox' },
  { label: 'Death Root Linen Gloves of Vitriol', value: 'Death Root Linen Gloves of Vitriol' },
  { label: 'Death Sun Ornate Gauntlets of Fury', value: 'Death Sun Ornate Gauntlets of Fury' },
  { label: 'Death Tear Divine Gloves of Giants', value: 'Death Tear Divine Gloves of Giants' },
  { label: 'Demon Bender Gauntlets of Anger +1', value: 'Demon Bender Gauntlets of Anger +1' },
  { label: 'Dragon Sun Linen Gloves of the Fox', value: 'Dragon Sun Linen Gloves of the Fox' },
  { label: 'Dread Peak Gloves of Perfection +1', value: 'Dread Peak Gloves of Perfection +1' },
  { label: 'Dusk Root Divine Gloves of Vitriol', value: 'Dusk Root Divine Gloves of Vitriol' },
  { label: 'Dusk Sun Ornate Gauntlets of Power', value: 'Dusk Sun Ornate Gauntlets of Power' },
  { label: 'Eagle Grasp Gloves of the Twins +1', value: 'Eagle Grasp Gloves of the Twins +1' },
  { label: 'Eagle Peak Silk Gloves of Anger +1', value: 'Eagle Peak Silk Gloves of Anger +1' },
  { label: 'Eagle Shout Gauntlets of Giants +1', value: 'Eagle Shout Gauntlets of Giants +1' },
  { label: 'Foe Bender Silk Gloves of Anger +1', value: 'Foe Bender Silk Gloves of Anger +1' },
  { label: 'Grim Bender Gauntlets of Titans +1', value: 'Grim Bender Gauntlets of Titans +1' },
  { label: 'Hypnotic Sun Linen Gloves of Anger', value: 'Hypnotic Sun Linen Gloves of Anger' },
  { label: "Light's Sun Divine Gloves of Power", value: "Light's Sun Divine Gloves of Power" },
  { label: 'Mind Moon Silk Gloves of Giants +1', value: 'Mind Moon Silk Gloves of Giants +1' },
  { label: 'Morbid Glow Divine Gloves of Skill', value: 'Morbid Glow Divine Gloves of Skill' },
  { label: 'Pain Glow Divine Gloves of Vitriol', value: 'Pain Glow Divine Gloves of Vitriol' },
  { label: 'Pain Sun Ornate Gauntlets of Power', value: 'Pain Sun Ornate Gauntlets of Power' },
  { label: 'Blight Grasp Gloves of Vitriol +1', value: 'Blight Grasp Gloves of Vitriol +1' },
  { label: 'Corpse Roar Linen Gloves of Anger', value: 'Corpse Roar Linen Gloves of Anger' },
  { label: 'Corpse Roar Linen Gloves of Power', value: 'Corpse Roar Linen Gloves of Power' },
  { label: 'Demon Peak Silk Gloves of Fury +1', value: 'Demon Peak Silk Gloves of Fury +1' },
  { label: 'Dragon Sun Divine Gloves of Power', value: 'Dragon Sun Divine Gloves of Power' },
  { label: 'Fate Glow Divine Gloves of Giants', value: 'Fate Glow Divine Gloves of Giants' },
  { label: 'Foe Bender Silk Gloves of Fury +1', value: 'Foe Bender Silk Gloves of Fury +1' },
  { label: 'Foe Grasp Gloves of Brilliance +1', value: 'Foe Grasp Gloves of Brilliance +1' },
  { label: 'Ghoul Root Divine Gloves of Skill', value: 'Ghoul Root Divine Gloves of Skill' },
  { label: 'Gloom Grasp Gauntlets of Skill +1', value: 'Gloom Grasp Gauntlets of Skill +1' },
  { label: 'Golem Tear Divine Gloves of Skill', value: 'Golem Tear Divine Gloves of Skill' },
  { label: 'Havoc Roar Linen Gloves of Titans', value: 'Havoc Roar Linen Gloves of Titans' },
  { label: 'Kraken Moon Gauntlets of Skill +1', value: 'Kraken Moon Gauntlets of Skill +1' },
  { label: 'Mind Bite Gloves of Perfection +1', value: 'Mind Bite Gloves of Perfection +1' },
  { label: 'Mind Peak Gloves of Perfection +1', value: 'Mind Peak Gloves of Perfection +1' },
  { label: 'Mind Peak Gloves of Reflection +1', value: 'Mind Peak Gloves of Reflection +1' },
  { label: 'Mind Shout Silk Gloves of Rage +1', value: 'Mind Shout Silk Gloves of Rage +1' },
  { label: 'Morbid Sun Divine Gloves of Anger', value: 'Morbid Sun Divine Gloves of Anger' },
  { label: 'Morbid Tear Divine Gloves of Rage', value: 'Morbid Tear Divine Gloves of Rage' },
  { label: 'Plague Glow Divine Gloves of Rage', value: 'Plague Glow Divine Gloves of Rage' },
  { label: 'Plague Root Divine Gloves of Rage', value: 'Plague Root Divine Gloves of Rage' },
  { label: 'Plague Sun Divine Gloves of Anger', value: 'Plague Sun Divine Gloves of Anger' },
  { label: 'Plague Sun Divine Gloves of Power', value: 'Plague Sun Divine Gloves of Power' },
  { label: 'Cataclysm Bite Gloves of Fury +1', value: 'Cataclysm Bite Gloves of Fury +1' },
  { label: 'Corpse Sun Linen Gloves of Power', value: 'Corpse Sun Linen Gloves of Power' },
  { label: 'Death Roar Divine Gloves of Fury', value: 'Death Roar Divine Gloves of Fury' },
  { label: 'Dread Shout Gloves of Vitriol +1', value: 'Dread Shout Gloves of Vitriol +1' },
  { label: 'Dusk Roar Divine Gloves of Anger', value: 'Dusk Roar Divine Gloves of Anger' },
  { label: 'Foe Bender Gauntlets of Anger +1', value: 'Foe Bender Gauntlets of Anger +1' },
  { label: 'Foe Grasp Gloves of Detection +1', value: 'Foe Grasp Gloves of Detection +1' },
  { label: 'Gloom Bite Gauntlets of Power +1', value: 'Gloom Bite Gauntlets of Power +1' },
  { label: 'Havoc Roar Linen Gloves of Anger', value: 'Havoc Roar Linen Gloves of Anger' },
  { label: 'Morbid Root Heavy Gloves of Rage', value: 'Morbid Root Heavy Gloves of Rage' },
  { label: 'Oblivion Peak Gloves of Power +1', value: 'Oblivion Peak Gloves of Power +1' },
  { label: 'Pain Sun Linen Gloves of the Fox', value: 'Pain Sun Linen Gloves of the Fox' },
  { label: 'Plague Glow Linen Gloves of Rage', value: 'Plague Glow Linen Gloves of Rage' },
  { label: 'Plague Roar Linen Gloves of Fury', value: 'Plague Roar Linen Gloves of Fury' },
  { label: 'Blight Bender Gloves of Fury +1', value: 'Blight Bender Gloves of Fury +1' },
  { label: 'Death Sun Linen Gloves of Anger', value: 'Death Sun Linen Gloves of Anger' },
  { label: 'Dragon Sun Heavy Gloves of Fury', value: 'Dragon Sun Heavy Gloves of Fury' },
  { label: 'Fate Roar Heavy Gloves of Anger', value: 'Fate Roar Heavy Gloves of Anger' },
  { label: 'Fate Tear Heavy Gloves of Skill', value: 'Fate Tear Heavy Gloves of Skill' },
  { label: 'Gloom Bender Gloves of Power +1', value: 'Gloom Bender Gloves of Power +1' },
  { label: 'Gloom Shout Gloves of Giants +1', value: 'Gloom Shout Gloves of Giants +1' },
  { label: 'Grim Bender Gloves of Titans +1', value: 'Grim Bender Gloves of Titans +1' },
  { label: 'Grim Shout Gloves of Vitriol +1', value: 'Grim Shout Gloves of Vitriol +1' },
  { label: 'Honour Bite Gloves of Titans +1', value: 'Honour Bite Gloves of Titans +1' },
  { label: 'Honour Grasp Gloves of Skill +1', value: 'Honour Grasp Gloves of Skill +1' },
  { label: 'Oblivion Bite Gloves of Fury +1', value: 'Oblivion Bite Gloves of Fury +1' },
  { label: 'Plague Sun Heavy Gloves of Fury', value: 'Plague Sun Heavy Gloves of Fury' },
  { label: 'Blight Shout Gloves of Rage +1', value: 'Blight Shout Gloves of Rage +1' },
  { label: 'Dread Shout Gloves of Skill +1', value: 'Dread Shout Gloves of Skill +1' },
  { label: 'Dusk Glow Heavy Gloves of Rage', value: 'Dusk Glow Heavy Gloves of Rage' },
  { label: 'Dusk Roar Linen Gloves of Fury', value: 'Dusk Roar Linen Gloves of Fury' },
  { label: 'Dusk Sun Heavy Gloves of Power', value: 'Dusk Sun Heavy Gloves of Power' },
  { label: 'Foe Moon Gauntlets of Skill +1', value: 'Foe Moon Gauntlets of Skill +1' },
  { label: 'Gloom Bite Gloves of Titans +1', value: 'Gloom Bite Gloves of Titans +1' },
  { label: 'Honour Shout Gloves of Rage +1', value: 'Honour Shout Gloves of Rage +1' },
  { label: 'Mind Bite Gauntlets of Fury +1', value: 'Mind Bite Gauntlets of Fury +1' },
  { label: 'Pain Roar Heavy Gloves of Fury', value: 'Pain Roar Heavy Gloves of Fury' },
  { label: 'Demon Peak Gloves of Anger +1', value: 'Demon Peak Gloves of Anger +1' },
  { label: 'Dread Peak Gloves of Anger +1', value: 'Dread Peak Gloves of Anger +1' },
  { label: 'Kraken Bite Gloves of Fury +1', value: 'Kraken Bite Gloves of Fury +1' },
  { label: 'Pain Sun Linen Gloves of Fury', value: 'Pain Sun Linen Gloves of Fury' },
  { label: 'Dread Bite Gloves of Fury +1', value: 'Dread Bite Gloves of Fury +1' },
  { label: 'Mind Shout Gloves of Rage +1', value: 'Mind Shout Gloves of Rage +1' },
  { label: 'Divine Gloves of Brilliance', value: 'Divine Gloves of Brilliance' },
  { label: 'Ornate Gauntlets of Giants', value: 'Ornate Gauntlets of Giants' },
  { label: 'Gauntlets of Perfection', value: 'Gauntlets of Perfection' },
  { label: 'Gauntlets of Fury', value: 'Gauntlets of Fury' },
  { label: 'Plague Whisper Ornate Gauntlets of Perfection', value: 'Plague Whisper Ornate Gauntlets of Perfection' },
  { label: 'Plague Whisper Ornate Gauntlets of Titans', value: 'Plague Whisper Ornate Gauntlets of Titans' },
  { label: "Rage Bender Demon's Hands of Fury +1", value: "Rage Bender Demon's Hands of Fury +1" },
  { label: 'Rage Bender Gauntlets of Anger +1', value: 'Rage Bender Gauntlets of Anger +1' },
  { label: 'Rage Bite Gauntlets of the Fox +1', value: 'Rage Bite Gauntlets of the Fox +1' },
  { label: 'Rage Bite Gauntlets of Titans +1', value: 'Rage Bite Gauntlets of Titans +1' },
  { label: 'Rage Bite Silk Gloves of Power +1', value: 'Rage Bite Silk Gloves of Power +1' },
  { label: 'Rage Grasp Gauntlets of Detection +1', value: 'Rage Grasp Gauntlets of Detection +1' },
  { label: 'Rage Grasp Gloves of Brilliance +1', value: 'Rage Grasp Gloves of Brilliance +1' },
  { label: "Rage Moon Demon's Hands of Detection +1", value: "Rage Moon Demon's Hands of Detection +1" },
  { label: 'Rage Moon Gauntlets of Giants +1', value: 'Rage Moon Gauntlets of Giants +1' },
  { label: 'Rage Moon Gauntlets of Skill +1', value: 'Rage Moon Gauntlets of Skill +1' },
  { label: 'Rage Moon Silk Gloves of Detection +1', value: 'Rage Moon Silk Gloves of Detection +1' },
  { label: 'Rage Moon Silk Gloves of Giants +1', value: 'Rage Moon Silk Gloves of Giants +1' },
  { label: 'Rage Peak Gloves of Anger +1', value: 'Rage Peak Gloves of Anger +1' },
  { label: 'Rage Peak Hard Leather Gloves of Reflection +1', value: 'Rage Peak Hard Leather Gloves of Reflection +1' },
  { label: 'Rage Peak Silk Gloves of Anger +1', value: 'Rage Peak Silk Gloves of Anger +1' },
  { label: 'Rage Shout Gauntlets of Giants +1', value: 'Rage Shout Gauntlets of Giants +1' },
  { label: 'Rage Shout Gauntlets of Skill +1', value: 'Rage Shout Gauntlets of Skill +1' },
  { label: 'Rage Shout Hard Leather Gloves of Rage +1', value: 'Rage Shout Hard Leather Gloves of Rage +1' },
  { label: 'Rune Glow Divine Gloves of Skill', value: 'Rune Glow Divine Gloves of Skill' },
  { label: 'Rune Glow Linen Gloves of Rage', value: 'Rune Glow Linen Gloves of Rage' },
  { label: 'Rune Roar Linen Gloves of Fury', value: 'Rune Roar Linen Gloves of Fury' },
  { label: 'Rune Roar Linen Gloves of Power', value: 'Rune Roar Linen Gloves of Power' },
  { label: 'Rune Root Heavy Gloves of the Twins', value: 'Rune Root Heavy Gloves of the Twins' },
  { label: 'Rune Root Ornate Gauntlets of Detection', value: 'Rune Root Ornate Gauntlets of Detection' },
  { label: 'Rune Sun Divine Gloves of Perfection', value: 'Rune Sun Divine Gloves of Perfection' },
  { label: 'Rune Sun Heavy Gloves of Perfection', value: 'Rune Sun Heavy Gloves of Perfection' },
  { label: 'Rune Sun Linen Gloves of Perfection', value: 'Rune Sun Linen Gloves of Perfection' },
  { label: 'Rune Sun Linen Gloves of Reflection', value: 'Rune Sun Linen Gloves of Reflection' },
  { label: 'Rune Sun Linen Gloves of the Fox', value: 'Rune Sun Linen Gloves of the Fox' },
  { label: 'Rune Sun Ornate Gauntlets of Power', value: 'Rune Sun Ornate Gauntlets of Power' },
  { label: 'Rune Sun Studded Leather Gloves of Perfection', value: 'Rune Sun Studded Leather Gloves of Perfection' },
  { label: 'Rune Tear Heavy Gloves of Skill', value: 'Rune Tear Heavy Gloves of Skill' },
  { label: 'Rune Tear Linen Gloves of the Twins', value: 'Rune Tear Linen Gloves of the Twins' },
  { label: 'Rune Tear Ornate Gauntlets of Giants', value: 'Rune Tear Ornate Gauntlets of Giants' },
  { label: 'Rune Tear Studded Leather Gloves of Rage', value: 'Rune Tear Studded Leather Gloves of Rage' },
  { label: 'Rune Tear Studded Leather Gloves of the Twins', value: 'Rune Tear Studded Leather Gloves of the Twins' },
  { label: 'Rune Whisper Heavy Gloves of Anger', value: 'Rune Whisper Heavy Gloves of Anger' },
  { label: 'Shimmering Bender Gauntlets of the Fox +1', value: 'Shimmering Bender Gauntlets of the Fox +1' },
  { label: 'Shimmering Bender Hard Leather Gloves of the Fox +1', value: 'Shimmering Bender Hard Leather Gloves of the Fox +1' },
  { label: 'Shimmering Bite Silk Gloves of Titans +1', value: 'Shimmering Bite Silk Gloves of Titans +1' },
  { label: 'Shimmering Grasp Hard Leather Gloves of Detection +1', value: 'Shimmering Grasp Hard Leather Gloves of Detection +1' },
  { label: 'Shimmering Grasp Hard Leather Gloves of Skill +1', value: 'Shimmering Grasp Hard Leather Gloves of Skill +1' },
  { label: 'Shimmering Moon Gauntlets of Vitriol +1', value: 'Shimmering Moon Gauntlets of Vitriol +1' },
  { label: 'Shimmering Peak Gauntlets of the Fox +1', value: 'Shimmering Peak Gauntlets of the Fox +1' },
  { label: 'Shimmering Peak Gauntlets of Titans +1', value: 'Shimmering Peak Gauntlets of Titans +1' },
  { label: 'Shimmering Peak Gloves of Enlightenment +1', value: 'Shimmering Peak Gloves of Enlightenment +1' },
  { label: 'Shimmering Shout Gauntlets of Detection +1', value: 'Shimmering Shout Gauntlets of Detection +1' },
  { label: 'Shimmering Shout Hard Leather Gloves of the Twins +1', value: 'Shimmering Shout Hard Leather Gloves of the Twins +1' },
  { label: 'Shimmering Shout Silk Gloves of Skill +1', value: 'Shimmering Shout Silk Gloves of Skill +1' },
  { label: 'Shimmering Shout Silk Gloves of Vitriol +1', value: 'Shimmering Shout Silk Gloves of Vitriol +1' },
  { label: 'Silk Gloves of Rage', value: 'Silk Gloves of Rage' },
  { label: 'Skull Bender Hard Leather Gloves of Titans +1', value: 'Skull Bender Hard Leather Gloves of Titans +1' },
  { label: 'Skull Bite Gloves of Enlightenment +1', value: 'Skull Bite Gloves of Enlightenment +1' },
  { label: 'Skull Bite Hard Leather Gloves of Fury +1', value: 'Skull Bite Hard Leather Gloves of Fury +1' },
  { label: 'Skull Bite Silk Gloves of Enlightenment +1', value: 'Skull Bite Silk Gloves of Enlightenment +1' },
  { label: 'Skull Grasp Gauntlets of Giants +1', value: 'Skull Grasp Gauntlets of Giants +1' },
  { label: 'Skull Grasp Gloves of Brilliance +1', value: 'Skull Grasp Gloves of Brilliance +1' },
  { label: 'Skull Grasp Gloves of Protection +1', value: 'Skull Grasp Gloves of Protection +1' },
  { label: "Skull Moon Demon's Hands of Detection +1", value: "Skull Moon Demon's Hands of Detection +1" },
  { label: "Skull Moon Demon's Hands of Giants +1", value: "Skull Moon Demon's Hands of Giants +1" },
  { label: "Skull Moon Demon's Hands of Protection +1", value: "Skull Moon Demon's Hands of Protection +1" },
  { label: 'Skull Moon Gauntlets of Brilliance +1', value: 'Skull Moon Gauntlets of Brilliance +1' },
  { label: 'Skull Moon Hard Leather Gloves of Brilliance +1', value: 'Skull Moon Hard Leather Gloves of Brilliance +1' },
  { label: 'Skull Peak Gloves of Power +1', value: 'Skull Peak Gloves of Power +1' },
  { label: 'Skull Peak Hard Leather Gloves of the Fox +1', value: 'Skull Peak Hard Leather Gloves of the Fox +1' },
  { label: 'Skull Peak Silk Gloves of Enlightenment +1', value: 'Skull Peak Silk Gloves of Enlightenment +1' },
  { label: 'Skull Shout Gauntlets of Brilliance +1', value: 'Skull Shout Gauntlets of Brilliance +1' },
  { label: 'Sorrow Bender Gauntlets of Perfection +1', value: 'Sorrow Bender Gauntlets of Perfection +1' },
  { label: 'Sorrow Bender Gloves of Fury +1', value: 'Sorrow Bender Gloves of Fury +1' },
  { label: 'Sorrow Bender Silk Gloves of Reflection +1', value: 'Sorrow Bender Silk Gloves of Reflection +1' },
  { label: 'Sorrow Bite Gauntlets of Fury +1', value: 'Sorrow Bite Gauntlets of Fury +1' },
  { label: 'Sorrow Bite Silk Gloves of Anger +1', value: 'Sorrow Bite Silk Gloves of Anger +1' },
  { label: 'Sorrow Bite Silk Gloves of the Fox +1', value: 'Sorrow Bite Silk Gloves of the Fox +1' },
  { label: "Sorrow Grasp Demon's Hands of Protection +1", value: "Sorrow Grasp Demon's Hands of Protection +1" },
  { label: 'Sorrow Grasp Gauntlets of Giants +1', value: 'Sorrow Grasp Gauntlets of Giants +1' },
  { label: 'Sorrow Grasp Hard Leather Gloves of Skill +1', value: 'Sorrow Grasp Hard Leather Gloves of Skill +1' },
  { label: "Sorrow Moon Demon's Hands of Brilliance +1", value: "Sorrow Moon Demon's Hands of Brilliance +1" },
  { label: 'Sorrow Moon Hard Leather Gloves of Protection +1', value: 'Sorrow Moon Hard Leather Gloves of Protection +1' },
  { label: "Sorrow Peak Demon's Hands of Enlightenment +1", value: "Sorrow Peak Demon's Hands of Enlightenment +1" },
  { label: 'Sorrow Shout Gloves of Skill +1', value: 'Sorrow Shout Gloves of Skill +1' },
  { label: 'Soul Glow Ornate Gauntlets of Detection', value: 'Soul Glow Ornate Gauntlets of Detection' },
  { label: 'Soul Glow Ornate Gauntlets of Rage', value: 'Soul Glow Ornate Gauntlets of Rage' },
  { label: 'Soul Roar Linen Gloves of Titans', value: 'Soul Roar Linen Gloves of Titans' },
  { label: 'Soul Root Linen Gloves of Detection', value: 'Soul Root Linen Gloves of Detection' },
  { label: 'Soul Root Linen Gloves of the Twins', value: 'Soul Root Linen Gloves of the Twins' },
  { label: 'Soul Sun Divine Gloves of Enlightenment', value: 'Soul Sun Divine Gloves of Enlightenment' },
  { label: 'Soul Sun Divine Gloves of Power', value: 'Soul Sun Divine Gloves of Power' },
  { label: 'Soul Sun Studded Leather Gloves of Enlightenment', value: 'Soul Sun Studded Leather Gloves of Enlightenment' },
  { label: 'Soul Tear Divine Gloves of Giants', value: 'Soul Tear Divine Gloves of Giants' },
  { label: 'Soul Tear Heavy Gloves of the Twins', value: 'Soul Tear Heavy Gloves of the Twins' },
  { label: 'Soul Whisper Linen Gloves of Fury', value: 'Soul Whisper Linen Gloves of Fury' },
  { label: 'Soul Whisper Linen Gloves of Power', value: 'Soul Whisper Linen Gloves of Power' },
  { label: 'Storm Glow Heavy Gloves of Protection', value: 'Storm Glow Heavy Gloves of Protection' },
  { label: 'Storm Glow Linen Gloves of Detection', value: 'Storm Glow Linen Gloves of Detection' },
  { label: 'Storm Glow Ornate Gauntlets of Giants', value: 'Storm Glow Ornate Gauntlets of Giants' },
  { label: 'Storm Roar Heavy Gloves of Perfection', value: 'Storm Roar Heavy Gloves of Perfection' },
  { label: 'Storm Roar Ornate Gauntlets of Anger', value: 'Storm Roar Ornate Gauntlets of Anger' },
  { label: 'Storm Root Divine Gloves of Protection', value: 'Storm Root Divine Gloves of Protection' },
  { label: 'Storm Root Heavy Gloves of Rage', value: 'Storm Root Heavy Gloves of Rage' },
  { label: 'Storm Root Ornate Gauntlets of Rage', value: 'Storm Root Ornate Gauntlets of Rage' },
  { label: 'Storm Sun Heavy Gloves of Perfection', value: 'Storm Sun Heavy Gloves of Perfection' },
  { label: 'Storm Sun Heavy Gloves of the Fox', value: 'Storm Sun Heavy Gloves of the Fox' },
  { label: 'Storm Sun Ornate Gauntlets of the Fox', value: 'Storm Sun Ornate Gauntlets of the Fox' },
  { label: 'Storm Sun Studded Leather Gloves of Reflection', value: 'Storm Sun Studded Leather Gloves of Reflection' },
  { label: 'Storm Tear Heavy Gloves of Skill', value: 'Storm Tear Heavy Gloves of Skill' },
  { label: 'Storm Tear Ornate Gauntlets of Protection', value: 'Storm Tear Ornate Gauntlets of Protection' },
  { label: 'Storm Whisper Heavy Gloves of Anger', value: 'Storm Whisper Heavy Gloves of Anger' },
  { label: 'Storm Whisper Heavy Gloves of Perfection', value: 'Storm Whisper Heavy Gloves of Perfection' },
  { label: 'Storm Whisper Ornate Gauntlets of Titans', value: 'Storm Whisper Ornate Gauntlets of Titans' },
  { label: 'Storm Whisper Studded Leather Gloves of Perfection', value: 'Storm Whisper Studded Leather Gloves of Perfection' },
  { label: 'Studded Leather Gloves of Titans', value: 'Studded Leather Gloves of Titans' },
  { label: 'Tempest Bender Gauntlets of Enlightenment +1', value: 'Tempest Bender Gauntlets of Enlightenment +1' },
  { label: 'Tempest Bender Hard Leather Gloves of Anger +1', value: 'Tempest Bender Hard Leather Gloves of Anger +1' },
  { label: 'Tempest Bender Silk Gloves of Perfection +1', value: 'Tempest Bender Silk Gloves of Perfection +1' },
  { label: 'Tempest Bender Silk Gloves of Reflection +1', value: 'Tempest Bender Silk Gloves of Reflection +1' },
  { label: 'Tempest Bite Gloves of Fury +1', value: 'Tempest Bite Gloves of Fury +1' },
  { label: 'Tempest Bite Silk Gloves of Fury +1', value: 'Tempest Bite Silk Gloves of Fury +1' },
  { label: 'Tempest Bite Silk Gloves of Titans +1', value: 'Tempest Bite Silk Gloves of Titans +1' },
  { label: 'Tempest Grasp Gauntlets of Rage +1', value: 'Tempest Grasp Gauntlets of Rage +1' },
  { label: 'Tempest Grasp Gloves of Giants +1', value: 'Tempest Grasp Gloves of Giants +1' },
  { label: 'Tempest Grasp Hard Leather Gloves of Brilliance +1', value: 'Tempest Grasp Hard Leather Gloves of Brilliance +1' },
  { label: 'Tempest Grasp Hard Leather Gloves of Rage +1', value: 'Tempest Grasp Hard Leather Gloves of Rage +1' },
  { label: "Tempest Moon Demon's Hands of Skill +1", value: "Tempest Moon Demon's Hands of Skill +1" },
  { label: 'Tempest Moon Silk Gloves of Rage +1', value: 'Tempest Moon Silk Gloves of Rage +1' },
  { label: "Tempest Peak Demon's Hands of Fury +1", value: "Tempest Peak Demon's Hands of Fury +1" },
  { label: 'Tempest Peak Gauntlets of Enlightenment +1', value: 'Tempest Peak Gauntlets of Enlightenment +1' },
  { label: 'Tempest Peak Silk Gloves of Titans +1', value: 'Tempest Peak Silk Gloves of Titans +1' },
  { label: 'Tempest Shout Gloves of Brilliance +1', value: 'Tempest Shout Gloves of Brilliance +1' },
  { label: 'Vengeance Glow Heavy Gloves of Skill', value: 'Vengeance Glow Heavy Gloves of Skill' },
  { label: 'Vengeance Glow Heavy Gloves of Vitriol', value: 'Vengeance Glow Heavy Gloves of Vitriol' },
  { label: 'Vengeance Roar Divine Gloves of Power', value: 'Vengeance Roar Divine Gloves of Power' },
  { label: 'Vengeance Roar Divine Gloves of the Fox', value: 'Vengeance Roar Divine Gloves of the Fox' },
  { label: 'Vengeance Roar Ornate Gauntlets of Reflection', value: 'Vengeance Roar Ornate Gauntlets of Reflection' },
  { label: 'Vengeance Root Divine Gloves of Brilliance', value: 'Vengeance Root Divine Gloves of Brilliance' },
  { label: 'Vengeance Root Ornate Gauntlets of Giants', value: 'Vengeance Root Ornate Gauntlets of Giants' },
  { label: 'Vengeance Root Studded Leather Gloves of Vitriol', value: 'Vengeance Root Studded Leather Gloves of Vitriol' },
  { label: 'Vengeance Tear Divine Gloves of Protection', value: 'Vengeance Tear Divine Gloves of Protection' },
  { label: 'Vengeance Tear Heavy Gloves of Giants', value: 'Vengeance Tear Heavy Gloves of Giants' },
  { label: 'Vengeance Tear Ornate Gauntlets of the Twins', value: 'Vengeance Tear Ornate Gauntlets of the Twins' },
  { label: 'Vengeance Tear Studded Leather Gloves of Vitriol', value: 'Vengeance Tear Studded Leather Gloves of Vitriol' },
  { label: 'Vengeance Whisper Heavy Gloves of Power', value: 'Vengeance Whisper Heavy Gloves of Power' },
  { label: 'Vengeance Whisper Linen Gloves of Anger', value: 'Vengeance Whisper Linen Gloves of Anger' },
  { label: 'Vengeance Whisper Linen Gloves of Fury', value: 'Vengeance Whisper Linen Gloves of Fury' },
  { label: 'Vengeance Whisper Ornate Gauntlets of Power', value: 'Vengeance Whisper Ornate Gauntlets of Power' },
  { label: 'Victory Bender Gauntlets of Enlightenment +1', value: 'Victory Bender Gauntlets of Enlightenment +1' },
  { label: 'Victory Bender Silk Gloves of Power +1', value: 'Victory Bender Silk Gloves of Power +1' },
  { label: 'Victory Bite Gauntlets of Power +1', value: 'Victory Bite Gauntlets of Power +1' },
  { label: 'Victory Grasp Gauntlets of Giants +1', value: 'Victory Grasp Gauntlets of Giants +1' },
  { label: 'Victory Grasp Gloves of Protection +1', value: 'Victory Grasp Gloves of Protection +1' },
  { label: 'Victory Grasp Gloves of the Twins +1', value: 'Victory Grasp Gloves of the Twins +1' },
  { label: 'Victory Grasp Silk Gloves of Brilliance +1', value: 'Victory Grasp Silk Gloves of Brilliance +1' },
  { label: 'Victory Grasp Silk Gloves of Rage +1', value: 'Victory Grasp Silk Gloves of Rage +1' },
  { label: "Victory Moon Demon's Hands of the Twins +1", value: "Victory Moon Demon's Hands of the Twins +1" },
  { label: "Victory Moon Demon's Hands of Vitriol +1", value: "Victory Moon Demon's Hands of Vitriol +1" },
  { label: 'Victory Moon Gauntlets of the Twins +1', value: 'Victory Moon Gauntlets of the Twins +1' },
  { label: 'Victory Moon Gauntlets of Vitriol +1', value: 'Victory Moon Gauntlets of Vitriol +1' },
  { label: 'Victory Moon Gloves of Giants +1', value: 'Victory Moon Gloves of Giants +1' },
  { label: 'Victory Moon Hard Leather Gloves of Giants +1', value: 'Victory Moon Hard Leather Gloves of Giants +1' },
  { label: "Victory Peak Demon's Hands of the Fox +1", value: "Victory Peak Demon's Hands of the Fox +1" },
  { label: 'Victory Peak Gloves of Enlightenment +1', value: 'Victory Peak Gloves of Enlightenment +1' },
  { label: 'Victory Peak Gloves of Perfection +1', value: 'Victory Peak Gloves of Perfection +1' },
  { label: 'Victory Peak Gloves of Titans +1', value: 'Victory Peak Gloves of Titans +1' },
  { label: 'Victory Peak Hard Leather Gloves of Fury +1', value: 'Victory Peak Hard Leather Gloves of Fury +1' },
  { label: 'Victory Peak Hard Leather Gloves of the Fox +1', value: 'Victory Peak Hard Leather Gloves of the Fox +1' },
  { label: "Victory Shout Demon's Hands of Brilliance +1", value: "Victory Shout Demon's Hands of Brilliance +1" },
  { label: "Victory Shout Demon's Hands of Rage +1", value: "Victory Shout Demon's Hands of Rage +1" },
  { label: 'Victory Shout Gauntlets of Skill +1', value: 'Victory Shout Gauntlets of Skill +1' },
  { label: 'Victory Shout Gloves of Giants +1', value: 'Victory Shout Gloves of Giants +1' },
  { label: 'Vortex Glow Divine Gloves of Brilliance', value: 'Vortex Glow Divine Gloves of Brilliance' },
  { label: 'Vortex Glow Divine Gloves of Vitriol', value: 'Vortex Glow Divine Gloves of Vitriol' },
  { label: 'Vortex Glow Heavy Gloves of Giants', value: 'Vortex Glow Heavy Gloves of Giants' },
  { label: 'Vortex Glow Linen Gloves of Rage', value: 'Vortex Glow Linen Gloves of Rage' },
  { label: 'Vortex Glow Linen Gloves of Vitriol', value: 'Vortex Glow Linen Gloves of Vitriol' },
  { label: 'Vortex Glow Ornate Gauntlets of Detection', value: 'Vortex Glow Ornate Gauntlets of Detection' },
  { label: 'Vortex Glow Studded Leather Gloves of the Twins', value: 'Vortex Glow Studded Leather Gloves of the Twins' },
  { label: 'Vortex Roar Heavy Gloves of the Fox', value: 'Vortex Roar Heavy Gloves of the Fox' },
  { label: 'Vortex Roar Linen Gloves of Power', value: 'Vortex Roar Linen Gloves of Power' },
  { label: 'Vortex Roar Ornate Gauntlets of Enlightenment', value: 'Vortex Roar Ornate Gauntlets of Enlightenment' },
  { label: 'Vortex Roar Ornate Gauntlets of Reflection', value: 'Vortex Roar Ornate Gauntlets of Reflection' },
  { label: 'Vortex Root Heavy Gloves of Brilliance', value: 'Vortex Root Heavy Gloves of Brilliance' },
  { label: 'Vortex Root Linen Gloves of Detection', value: 'Vortex Root Linen Gloves of Detection' },
  { label: 'Vortex Root Linen Gloves of Vitriol', value: 'Vortex Root Linen Gloves of Vitriol' },
  { label: 'Vortex Root Ornate Gauntlets of Vitriol', value: 'Vortex Root Ornate Gauntlets of Vitriol' },
  { label: 'Vortex Sun Divine Gloves of Anger', value: 'Vortex Sun Divine Gloves of Anger' },
  { label: 'Vortex Whisper Heavy Gloves of Anger', value: 'Vortex Whisper Heavy Gloves of Anger' },
  { label: 'Vortex Whisper Heavy Gloves of Reflection', value: 'Vortex Whisper Heavy Gloves of Reflection' },
  { label: 'Woe Bender Gauntlets of the Fox +1', value: 'Woe Bender Gauntlets of the Fox +1' },
  { label: 'Woe Bender Gloves of Titans +1', value: 'Woe Bender Gloves of Titans +1' },
  { label: 'Woe Bender Hard Leather Gloves of Anger +1', value: 'Woe Bender Hard Leather Gloves of Anger +1' },
  { label: 'Woe Bite Gauntlets of Power +1', value: 'Woe Bite Gauntlets of Power +1' },
  { label: 'Woe Bite Gloves of Reflection +1', value: 'Woe Bite Gloves of Reflection +1' },
  { label: 'Woe Bite Silk Gloves of Enlightenment +1', value: 'Woe Bite Silk Gloves of Enlightenment +1' },
  { label: 'Woe Bite Silk Gloves of Reflection +1', value: 'Woe Bite Silk Gloves of Reflection +1' },
  { label: 'Woe Bite Silk Gloves of Titans +1', value: 'Woe Bite Silk Gloves of Titans +1' },
  { label: 'Woe Grasp Gauntlets of Detection +1', value: 'Woe Grasp Gauntlets of Detection +1' },
  { label: 'Woe Grasp Gauntlets of Vitriol +1', value: 'Woe Grasp Gauntlets of Vitriol +1' },
  { label: 'Woe Grasp Gloves of the Twins +1', value: 'Woe Grasp Gloves of the Twins +1' },
  { label: "Woe Moon Demon's Hands of Detection +1", value: "Woe Moon Demon's Hands of Detection +1" },
  { label: 'Woe Moon Gauntlets of Detection +1', value: 'Woe Moon Gauntlets of Detection +1' },
  { label: 'Woe Moon Gauntlets of Rage +1', value: 'Woe Moon Gauntlets of Rage +1' },
  { label: 'Woe Moon Gloves of Vitriol +1', value: 'Woe Moon Gloves of Vitriol +1' },
  { label: 'Woe Moon Silk Gloves of Rage +1', value: 'Woe Moon Silk Gloves of Rage +1' },
  { label: 'Woe Moon Silk Gloves of the Twins +1', value: 'Woe Moon Silk Gloves of the Twins +1' },
  { label: 'Woe Moon Silk Gloves of Vitriol +1', value: 'Woe Moon Silk Gloves of Vitriol +1' },
  { label: 'Woe Peak Gauntlets of Perfection +1', value: 'Woe Peak Gauntlets of Perfection +1' },
  { label: 'Woe Peak Gloves of Fury +1', value: 'Woe Peak Gloves of Fury +1' },
  { label: 'Woe Peak Hard Leather Gloves of Fury +1', value: 'Woe Peak Hard Leather Gloves of Fury +1' },
  { label: 'Woe Peak Silk Gloves of Reflection +1', value: 'Woe Peak Silk Gloves of Reflection +1' },
  { label: "Woe Shout Demon's Hands of Protection +1", value: "Woe Shout Demon's Hands of Protection +1" },
  { label: 'Woe Shout Gauntlets of Brilliance +1', value: 'Woe Shout Gauntlets of Brilliance +1' },
  { label: 'Woe Shout Gauntlets of Protection +1', value: 'Woe Shout Gauntlets of Protection +1' },
  { label: 'Woe Shout Gauntlets of Vitriol +1', value: 'Woe Shout Gauntlets of Vitriol +1' },
  { label: 'Woe Shout Gloves of Brilliance +1', value: 'Woe Shout Gloves of Brilliance +1' },
  { label: 'Woe Shout Silk Gloves of Skill +1', value: 'Woe Shout Silk Gloves of Skill +1' },
];
