export const necks = [
  { label: 'Pendant', value: 'Pendant' },
  { label: 'Necklace', value: 'Necklace' },
  { label: 'Amulet', value: 'Amulet' },
  { label: 'Necklace of Fury', value: 'Necklace of Fury' },
  { label: 'Necklace of Protection', value: 'Necklace of Protection' },
  { label: 'Necklace of Power', value: 'Necklace of Power' },
  { label: 'Necklace of Brilliance', value: 'Necklace of Brilliance' },
  { label: 'Necklace of Skill', value: 'Necklace of Skill' },
  { label: 'Necklace of the Fox', value: 'Necklace of the Fox' },
  { label: 'Necklace of Giants', value: 'Necklace of Giants' },
  { label: 'Necklace of Titans', value: 'Necklace of Titans' },
  { label: 'Necklace of Enlightenment', value: 'Necklace of Enlightenment' },
  { label: 'Necklace of Reflection', value: 'Necklace of Reflection' },
  { label: 'Necklace of Detection', value: 'Necklace of Detection' },
  { label: 'Necklace of Perfection', value: 'Necklace of Perfection' },
  { label: 'Necklace of Vitriol', value: 'Necklace of Vitriol' },
  { label: 'Necklace of Rage', value: 'Necklace of Rage' },
  { label: 'Necklace of the Twins', value: 'Necklace of the Twins' },
  { label: 'Necklace of Anger', value: 'Necklace of Anger' },
  { label: 'Pendant of Detection', value: 'Pendant of Detection' },
  { label: 'Pendant of Titans', value: 'Pendant of Titans' },
  { label: 'Amulet of Enlightenment', value: 'Amulet of Enlightenment' },
  { label: 'Pendant of the Fox', value: 'Pendant of the Fox' },
  { label: 'Amulet of Titans', value: 'Amulet of Titans' },
  { label: 'Amulet of Detection', value: 'Amulet of Detection' },
  { label: 'Pendant of Enlightenment', value: 'Pendant of Enlightenment' },
  { label: 'Amulet of Reflection', value: 'Amulet of Reflection' },
  { label: 'Pendant of Giants', value: 'Pendant of Giants' },
  { label: 'Pendant of Anger', value: 'Pendant of Anger' },
  { label: 'Amulet of Skill', value: 'Amulet of Skill' },
  { label: 'Pendant of Fury', value: 'Pendant of Fury' },
  { label: 'Pendant of Protection', value: 'Pendant of Protection' },
  { label: 'Pendant of Vitriol', value: 'Pendant of Vitriol' },
  { label: 'Amulet of Vitriol', value: 'Amulet of Vitriol' },
  { label: 'Pendant of Power', value: 'Pendant of Power' },
  { label: 'Pendant of Reflection', value: 'Pendant of Reflection' },
  { label: 'Pendant of Skill', value: 'Pendant of Skill' },
  { label: 'Amulet of Fury', value: 'Amulet of Fury' },
  { label: 'Amulet of the Twins', value: 'Amulet of the Twins' },
  { label: 'Amulet of Giants', value: 'Amulet of Giants' },
  { label: 'Amulet of Anger', value: 'Amulet of Anger' },
  { label: 'Amulet of Power', value: 'Amulet of Power' },
  { label: 'Pendant of Rage', value: 'Pendant of Rage' },
  { label: 'Amulet of Rage', value: 'Amulet of Rage' },
  { label: 'Pendant of Perfection', value: 'Pendant of Perfection' },
  { label: 'Amulet of the Fox', value: 'Amulet of the Fox' },
  { label: 'Pendant of Brilliance', value: 'Pendant of Brilliance' },
  { label: 'Amulet of Perfection', value: 'Amulet of Perfection' },
  { label: 'Amulet of Protection', value: 'Amulet of Protection' },
  { label: 'Pendant of the Twins', value: 'Pendant of the Twins' },
  { label: 'Amulet of Brilliance', value: 'Amulet of Brilliance' },
  { label: 'Oblivion Bender Pendant of Reflection +1', value: 'Oblivion Bender Pendant of Reflection +1' },
  { label: 'Brimstone Moon Pendant of Detection +1', value: 'Brimstone Moon Pendant of Detection +1' },
  { label: 'Pandemonium Bite Pendant of Anger +1', value: 'Pandemonium Bite Pendant of Anger +1' },
  { label: 'Armageddon Peak Pendant of Fury +1', value: 'Armageddon Peak Pendant of Fury +1' },
  { label: 'Grim Bite Pendant of Perfection +1', value: 'Grim Bite Pendant of Perfection +1' },
  { label: 'Dread Bite Pendant of Power +1', value: 'Dread Bite Pendant of Power +1' },
  { label: 'Havoc Sun Amulet of Reflection', value: 'Havoc Sun Amulet of Reflection' },
  { label: 'Dread Moon Pendant of Rage +1', value: 'Dread Moon Pendant of Rage +1' },
  { label: 'Vengeance Root Amulet of Rage', value: 'Vengeance Root Amulet of Rage' },
  { label: 'Oblivion Bender Pendant of Enlightenment +1', value: 'Oblivion Bender Pendant of Enlightenment +1' },
  { label: 'Pandemonium Grasp Pendant of Brilliance +1', value: 'Pandemonium Grasp Pendant of Brilliance +1' },
  { label: 'Armageddon Grasp Pendant of Brilliance +1', value: 'Armageddon Grasp Pendant of Brilliance +1' },
  { label: 'Shimmering Bite Pendant of Perfection +1', value: 'Shimmering Bite Pendant of Perfection +1' },
  { label: 'Shimmering Moon Pendant of Detection +1', value: 'Shimmering Moon Pendant of Detection +1' },
  { label: 'Corruption Bender Pendant of Titans +1', value: 'Corruption Bender Pendant of Titans +1' },
  { label: 'Gloom Bite Pendant of Enlightenment +1', value: 'Gloom Bite Pendant of Enlightenment +1' },
  { label: 'Oblivion Grasp Pendant of Detection +1', value: 'Oblivion Grasp Pendant of Detection +1' },
  { label: 'Shimmering Shout Pendant of Vitriol +1', value: 'Shimmering Shout Pendant of Vitriol +1' },
  { label: 'Vengeance Roar Amulet of Enlightenment', value: 'Vengeance Roar Amulet of Enlightenment' },
  { label: 'Pandemonium Peak Pendant of Titans +1', value: 'Pandemonium Peak Pendant of Titans +1' },
  { label: 'Apocalypse Glow Amulet of Brilliance', value: 'Apocalypse Glow Amulet of Brilliance' },
  { label: 'Corruption Peak Pendant of Titans +1', value: 'Corruption Peak Pendant of Titans +1' },
  { label: 'Kraken Bite Pendant of Reflection +1', value: 'Kraken Bite Pendant of Reflection +1' },
  { label: 'Kraken Moon Pendant of Protection +1', value: 'Kraken Moon Pendant of Protection +1' },
  { label: 'Oblivion Bender Pendant of Titans +1', value: 'Oblivion Bender Pendant of Titans +1' },
  { label: 'Sorrow Moon Pendant of Protection +1', value: 'Sorrow Moon Pendant of Protection +1' },
  { label: 'Dread Peak Pendant of Perfection +1', value: 'Dread Peak Pendant of Perfection +1' },
  { label: 'Eagle Bite Pendant of Reflection +1', value: 'Eagle Bite Pendant of Reflection +1' },
  { label: 'Gloom Bite Pendant of Reflection +1', value: 'Gloom Bite Pendant of Reflection +1' },
  { label: 'Grim Shout Pendant of Brilliance +1', value: 'Grim Shout Pendant of Brilliance +1' },
  { label: 'Honour Moon Pendant of Detection +1', value: 'Honour Moon Pendant of Detection +1' },
  { label: 'Maelstrom Roar Amulet of Perfection', value: 'Maelstrom Roar Amulet of Perfection' },
  { label: 'Oblivion Peak Pendant of the Fox +1', value: 'Oblivion Peak Pendant of the Fox +1' },
  { label: 'Skull Bite Pendant of Perfection +1', value: 'Skull Bite Pendant of Perfection +1' },
  { label: 'Vortex Whisper Amulet of Perfection', value: 'Vortex Whisper Amulet of Perfection' },
  { label: 'Cataclysm Bite Pendant of Power +1', value: 'Cataclysm Bite Pendant of Power +1' },
  { label: 'Dread Moon Pendant of the Twins +1', value: 'Dread Moon Pendant of the Twins +1' },
  { label: 'Foe Grasp Pendant of Brilliance +1', value: 'Foe Grasp Pendant of Brilliance +1' },
  { label: 'Vengeance Root Amulet of Detection', value: 'Vengeance Root Amulet of Detection' },
  { label: 'Blight Bite Pendant of the Fox +1', value: 'Blight Bite Pendant of the Fox +1' },
  { label: 'Demon Shout Pendant of Vitriol +1', value: 'Demon Shout Pendant of Vitriol +1' },
  { label: 'Gloom Bender Pendant of Titans +1', value: 'Gloom Bender Pendant of Titans +1' },
  { label: 'Kraken Bender Pendant of Anger +1', value: 'Kraken Bender Pendant of Anger +1' },
  { label: "Light's Glow Amulet of Brilliance", value: "Light's Glow Amulet of Brilliance" },
  { label: "Light's Tear Amulet of Brilliance", value: "Light's Tear Amulet of Brilliance" },
  { label: 'Soul Whisper Amulet of Perfection', value: 'Soul Whisper Amulet of Perfection' },
  { label: 'Storm Sun Amulet of Enlightenment', value: 'Storm Sun Amulet of Enlightenment' },
  { label: 'Victory Shout Pendant of Skill +1', value: 'Victory Shout Pendant of Skill +1' },
  { label: 'Woe Moon Pendant of Brilliance +1', value: 'Woe Moon Pendant of Brilliance +1' },
  { label: 'Carrion Glow Amulet of Detection', value: 'Carrion Glow Amulet of Detection' },
  { label: 'Eagle Grasp Pendant of Giants +1', value: 'Eagle Grasp Pendant of Giants +1' },
  { label: 'Morbid Tear Amulet of Brilliance', value: 'Morbid Tear Amulet of Brilliance' },
  { label: 'Rune Sun Amulet of Enlightenment', value: 'Rune Sun Amulet of Enlightenment' },
  { label: 'Victory Grasp Pendant of Rage +1', value: 'Victory Grasp Pendant of Rage +1' },
  { label: 'Apocalypse Sun Amulet of Titans', value: 'Apocalypse Sun Amulet of Titans' },
  { label: 'Blight Shout Pendant of Rage +1', value: 'Blight Shout Pendant of Rage +1' },
  { label: 'Death Glow Amulet of Brilliance', value: 'Death Glow Amulet of Brilliance' },
  { label: 'Grim Shout Pendant of Giants +1', value: 'Grim Shout Pendant of Giants +1' },
  { label: 'Honour Grasp Pendant of Rage +1', value: 'Honour Grasp Pendant of Rage +1' },
  { label: 'Hypnotic Roar Amulet of the Fox', value: 'Hypnotic Roar Amulet of the Fox' },
  { label: 'Hypnotic Tear Amulet of Vitriol', value: 'Hypnotic Tear Amulet of Vitriol' },
  { label: 'Morbid Glow Amulet of the Twins', value: 'Morbid Glow Amulet of the Twins' },
  { label: 'Morbid Sun Amulet of Perfection', value: 'Morbid Sun Amulet of Perfection' },
  { label: 'Plague Sun Amulet of Reflection', value: 'Plague Sun Amulet of Reflection' },
  { label: 'Tempest Moon Pendant of Rage +1', value: 'Tempest Moon Pendant of Rage +1' },
  { label: 'Victory Bite Pendant of Fury +1', value: 'Victory Bite Pendant of Fury +1' },
  { label: 'Vortex Sun Amulet of Reflection', value: 'Vortex Sun Amulet of Reflection' },
  { label: 'Behemoth Sun Amulet of the Fox', value: 'Behemoth Sun Amulet of the Fox' },
  { label: 'Death Glow Amulet of Detection', value: 'Death Glow Amulet of Detection' },
  { label: 'Ghoul Sun Amulet of Reflection', value: 'Ghoul Sun Amulet of Reflection' },
  { label: 'Golem Root Amulet of Detection', value: 'Golem Root Amulet of Detection' },
  { label: 'Hypnotic Sun Amulet of the Fox', value: 'Hypnotic Sun Amulet of the Fox' },
  { label: 'Morbid Whisper Amulet of Power', value: 'Morbid Whisper Amulet of Power' },
  { label: 'Skull Grasp Pendant of Rage +1', value: 'Skull Grasp Pendant of Rage +1' },
  { label: 'Sorrow Moon Pendant of Rage +1', value: 'Sorrow Moon Pendant of Rage +1' },
  { label: 'Soul Roar Amulet of Perfection', value: 'Soul Roar Amulet of Perfection' },
  { label: 'Vengeance Roar Amulet of Anger', value: 'Vengeance Roar Amulet of Anger' },
  { label: 'Vortex Whisper Amulet of Anger', value: 'Vortex Whisper Amulet of Anger' },
  { label: 'Woe Shout Pendant of Giants +1', value: 'Woe Shout Pendant of Giants +1' },
  { label: 'Corpse Glow Amulet of Vitriol', value: 'Corpse Glow Amulet of Vitriol' },
  { label: 'Fate Sun Amulet of Perfection', value: 'Fate Sun Amulet of Perfection' },
  { label: 'Foe Grasp Pendant of Skill +1', value: 'Foe Grasp Pendant of Skill +1' },
  { label: 'Morbid Root Amulet of Vitriol', value: 'Morbid Root Amulet of Vitriol' },
  { label: 'Rune Root Amulet of the Twins', value: 'Rune Root Amulet of the Twins' },
  { label: 'Rune Whisper Amulet of Titans', value: 'Rune Whisper Amulet of Titans' },
  { label: 'Bramble Tear Amulet of Skill', value: 'Bramble Tear Amulet of Skill' },
  { label: 'Dragon Roar Amulet of Titans', value: 'Dragon Roar Amulet of Titans' },
  { label: 'Dragon Sun Amulet of the Fox', value: 'Dragon Sun Amulet of the Fox' },
  { label: 'Fate Whisper Amulet of Power', value: 'Fate Whisper Amulet of Power' },
  { label: 'Foe Grasp Pendant of Rage +1', value: 'Foe Grasp Pendant of Rage +1' },
  { label: 'Grim Moon Pendant of Rage +1', value: 'Grim Moon Pendant of Rage +1' },
  { label: 'Rage Bite Pendant of Fury +1', value: 'Rage Bite Pendant of Fury +1' },
  { label: 'Vengeance Sun Amulet of Fury', value: 'Vengeance Sun Amulet of Fury' },
  { label: 'Woe Peak Pendant of Anger +1', value: 'Woe Peak Pendant of Anger +1' },
  { label: 'Dragon Roar Amulet of Anger', value: 'Dragon Roar Amulet of Anger' },
  { label: 'Dusk Roar Amulet of the Fox', value: 'Dusk Roar Amulet of the Fox' },
  { label: 'Dusk Roar Amulet of Titans', value: 'Dusk Roar Amulet of Titans' },
  { label: 'Havoc Roar Amulet of Power', value: 'Havoc Roar Amulet of Power' },
  { label: 'Plague Tear Amulet of Rage', value: 'Plague Tear Amulet of Rage' },
  { label: 'Rune Tear Amulet of Giants', value: 'Rune Tear Amulet of Giants' },
  { label: 'Soul Tear Amulet of Giants', value: 'Soul Tear Amulet of Giants' },
  { label: 'Ghoul Roar Amulet of Fury', value: 'Ghoul Roar Amulet of Fury' },
  { label: 'Armageddon Bender Pendant of Enlightenment +1', value: 'Armageddon Bender Pendant of Enlightenment +1' },
  { label: 'Corruption Bender Pendant of Enlightenment +1', value: 'Corruption Bender Pendant of Enlightenment +1' },
  { label: 'Shimmering Bender Pendant of Enlightenment +1', value: 'Shimmering Bender Pendant of Enlightenment +1' },
  { label: 'Pandemonium Peak Pendant of Enlightenment +1', value: 'Pandemonium Peak Pendant of Enlightenment +1' },
  { label: 'Armageddon Peak Pendant of Enlightenment +1', value: 'Armageddon Peak Pendant of Enlightenment +1' },
  { label: 'Shimmering Bite Pendant of Enlightenment +1', value: 'Shimmering Bite Pendant of Enlightenment +1' },
  { label: 'Apocalypse Whisper Amulet of Enlightenment', value: 'Apocalypse Whisper Amulet of Enlightenment' },
  { label: 'Armageddon Bender Pendant of Reflection +1', value: 'Armageddon Bender Pendant of Reflection +1' },
  { label: 'Cataclysm Peak Pendant of Enlightenment +1', value: 'Cataclysm Peak Pendant of Enlightenment +1' },
  { label: 'Pandemonium Shout Pendant of Brilliance +1', value: 'Pandemonium Shout Pendant of Brilliance +1' },
  { label: 'Armageddon Grasp Pendant of Protection +1', value: 'Armageddon Grasp Pendant of Protection +1' },
  { label: 'Armageddon Shout Pendant of Brilliance +1', value: 'Armageddon Shout Pendant of Brilliance +1' },
  { label: 'Corruption Grasp Pendant of Protection +1', value: 'Corruption Grasp Pendant of Protection +1' },
  { label: 'Oblivion Peak Pendant of Enlightenment +1', value: 'Oblivion Peak Pendant of Enlightenment +1' },
  { label: 'Pandemonium Grasp Pendant of Detection +1', value: 'Pandemonium Grasp Pendant of Detection +1' },
  { label: 'Shimmering Shout Pendant of Brilliance +1', value: 'Shimmering Shout Pendant of Brilliance +1' },
  { label: 'Armageddon Peak Pendant of Reflection +1', value: 'Armageddon Peak Pendant of Reflection +1' },
  { label: 'Brimstone Grasp Pendant of Brilliance +1', value: 'Brimstone Grasp Pendant of Brilliance +1' },
  { label: 'Brimstone Shout Pendant of Brilliance +1', value: 'Brimstone Shout Pendant of Brilliance +1' },
  { label: 'Cataclysm Grasp Pendant of Protection +1', value: 'Cataclysm Grasp Pendant of Protection +1' },
  { label: 'Cataclysm Shout Pendant of Protection +1', value: 'Cataclysm Shout Pendant of Protection +1' },
  { label: 'Corruption Shout Pendant of the Twins +1', value: 'Corruption Shout Pendant of the Twins +1' },
  { label: 'Pandemonium Bender Pendant of the Fox +1', value: 'Pandemonium Bender Pendant of the Fox +1' },
  { label: 'Shimmering Bite Pendant of Reflection +1', value: 'Shimmering Bite Pendant of Reflection +1' },
  { label: 'Shimmering Peak Pendant of Reflection +1', value: 'Shimmering Peak Pendant of Reflection +1' },
  { label: 'Shimmering Shout Pendant of the Twins +1', value: 'Shimmering Shout Pendant of the Twins +1' },
  { label: 'Tempest Peak Pendant of Enlightenment +1', value: 'Tempest Peak Pendant of Enlightenment +1' },
  { label: 'Apocalypse Whisper Amulet of Reflection', value: 'Apocalypse Whisper Amulet of Reflection' },
  { label: 'Armageddon Bender Pendant of the Fox +1', value: 'Armageddon Bender Pendant of the Fox +1' },
  { label: 'Armageddon Moon Pendant of the Twins +1', value: 'Armageddon Moon Pendant of the Twins +1' },
  { label: 'Cataclysm Moon Pendant of Protection +1', value: 'Cataclysm Moon Pendant of Protection +1' },
  { label: 'Cataclysm Peak Pendant of Reflection +1', value: 'Cataclysm Peak Pendant of Reflection +1' },
  { label: 'Corruption Moon Pendant of Detection +1', value: 'Corruption Moon Pendant of Detection +1' },
  { label: 'Kraken Bite Pendant of Enlightenment +1', value: 'Kraken Bite Pendant of Enlightenment +1' },
  { label: 'Oblivion Shout Pendant of Protection +1', value: 'Oblivion Shout Pendant of Protection +1' },
  { label: 'Sorrow Peak Pendant of Enlightenment +1', value: 'Sorrow Peak Pendant of Enlightenment +1' },
  { label: 'Blight Bender Pendant of Reflection +1', value: 'Blight Bender Pendant of Reflection +1' },
  { label: 'Brimstone Moon Pendant of the Twins +1', value: 'Brimstone Moon Pendant of the Twins +1' },
  { label: 'Cataclysm Moon Pendant of Detection +1', value: 'Cataclysm Moon Pendant of Detection +1' },
  { label: 'Demon Bite Pendant of Enlightenment +1', value: 'Demon Bite Pendant of Enlightenment +1' },
  { label: 'Demon Peak Pendant of Enlightenment +1', value: 'Demon Peak Pendant of Enlightenment +1' },
  { label: 'Dragon Whisper Amulet of Enlightenment', value: 'Dragon Whisper Amulet of Enlightenment' },
  { label: 'Eagle Bite Pendant of Enlightenment +1', value: 'Eagle Bite Pendant of Enlightenment +1' },
  { label: 'Kraken Bender Pendant of Perfection +1', value: 'Kraken Bender Pendant of Perfection +1' },
  { label: 'Maelstrom Roar Amulet of Enlightenment', value: 'Maelstrom Roar Amulet of Enlightenment' },
  { label: 'Morbid Whisper Amulet of Enlightenment', value: 'Morbid Whisper Amulet of Enlightenment' },
  { label: 'Oblivion Peak Pendant of Reflection +1', value: 'Oblivion Peak Pendant of Reflection +1' },
  { label: 'Pandemonium Bender Pendant of Anger +1', value: 'Pandemonium Bender Pendant of Anger +1' },
  { label: 'Pandemonium Moon Pendant of Vitriol +1', value: 'Pandemonium Moon Pendant of Vitriol +1' },
  { label: 'Shimmering Grasp Pendant of Vitriol +1', value: 'Shimmering Grasp Pendant of Vitriol +1' },
  { label: 'Skull Peak Pendant of Enlightenment +1', value: 'Skull Peak Pendant of Enlightenment +1' },
  { label: 'Victory Shout Pendant of Brilliance +1', value: 'Victory Shout Pendant of Brilliance +1' },
  { label: 'Armageddon Moon Pendant of Vitriol +1', value: 'Armageddon Moon Pendant of Vitriol +1' },
  { label: 'Armageddon Peak Pendant of the Fox +1', value: 'Armageddon Peak Pendant of the Fox +1' },
  { label: 'Cataclysm Grasp Pendant of Vitriol +1', value: 'Cataclysm Grasp Pendant of Vitriol +1' },
  { label: 'Corruption Bender Pendant of Power +1', value: 'Corruption Bender Pendant of Power +1' },
  { label: 'Corruption Peak Pendant of the Fox +1', value: 'Corruption Peak Pendant of the Fox +1' },
  { label: 'Demon Bender Pendant of Reflection +1', value: 'Demon Bender Pendant of Reflection +1' },
  { label: 'Dread Bender Pendant of Perfection +1', value: 'Dread Bender Pendant of Perfection +1' },
  { label: 'Dread Bender Pendant of Reflection +1', value: 'Dread Bender Pendant of Reflection +1' },
  { label: 'Ghoul Whisper Amulet of Enlightenment', value: 'Ghoul Whisper Amulet of Enlightenment' },
  { label: 'Golem Whisper Amulet of Enlightenment', value: 'Golem Whisper Amulet of Enlightenment' },
  { label: 'Grim Bite Pendant of Enlightenment +1', value: 'Grim Bite Pendant of Enlightenment +1' },
  { label: 'Honour Grasp Pendant of Brilliance +1', value: 'Honour Grasp Pendant of Brilliance +1' },
  { label: 'Hypnotic Whisper Amulet of Reflection', value: 'Hypnotic Whisper Amulet of Reflection' },
  { label: 'Kraken Shout Pendant of Brilliance +1', value: 'Kraken Shout Pendant of Brilliance +1' },
  { label: 'Mind Bite Pendant of Enlightenment +1', value: 'Mind Bite Pendant of Enlightenment +1' },
  { label: 'Pandemonium Shout Pendant of Skill +1', value: 'Pandemonium Shout Pendant of Skill +1' },
  { label: 'Shimmering Bender Pendant of Power +1', value: 'Shimmering Bender Pendant of Power +1' },
  { label: 'Storm Whisper Amulet of Enlightenment', value: 'Storm Whisper Amulet of Enlightenment' },
  { label: 'Tempest Grasp Pendant of Detection +1', value: 'Tempest Grasp Pendant of Detection +1' },
  { label: 'Tempest Grasp Pendant of the Twins +1', value: 'Tempest Grasp Pendant of the Twins +1' },
  { label: 'Tempest Peak Pendant of Reflection +1', value: 'Tempest Peak Pendant of Reflection +1' },
  { label: 'Victory Moon Pendant of Brilliance +1', value: 'Victory Moon Pendant of Brilliance +1' },
  { label: 'Victory Peak Pendant of Perfection +1', value: 'Victory Peak Pendant of Perfection +1' },
  { label: 'Victory Shout Pendant of Detection +1', value: 'Victory Shout Pendant of Detection +1' },
  { label: 'Victory Shout Pendant of the Twins +1', value: 'Victory Shout Pendant of the Twins +1' },
  { label: 'Apocalypse Tear Amulet of Protection', value: 'Apocalypse Tear Amulet of Protection' },
  { label: 'Apocalypse Whisper Amulet of the Fox', value: 'Apocalypse Whisper Amulet of the Fox' },
  { label: 'Armageddon Bite Pendant of Titans +1', value: 'Armageddon Bite Pendant of Titans +1' },
  { label: 'Blight Bite Pendant of Perfection +1', value: 'Blight Bite Pendant of Perfection +1' },
  { label: 'Blight Bite Pendant of Reflection +1', value: 'Blight Bite Pendant of Reflection +1' },
  { label: 'Blight Peak Pendant of Reflection +1', value: 'Blight Peak Pendant of Reflection +1' },
  { label: 'Blight Shout Pendant of Detection +1', value: 'Blight Shout Pendant of Detection +1' },
  { label: 'Bramble Roar Amulet of Enlightenment', value: 'Bramble Roar Amulet of Enlightenment' },
  { label: 'Bramble Whisper Amulet of Perfection', value: 'Bramble Whisper Amulet of Perfection' },
  { label: 'Brimstone Bite Pendant of the Fox +1', value: 'Brimstone Bite Pendant of the Fox +1' },
  { label: 'Cataclysm Bite Pendant of the Fox +1', value: 'Cataclysm Bite Pendant of the Fox +1' },
  { label: 'Cataclysm Grasp Pendant of Giants +1', value: 'Cataclysm Grasp Pendant of Giants +1' },
  { label: 'Dread Shout Pendant of Protection +1', value: 'Dread Shout Pendant of Protection +1' },
  { label: 'Eagle Shout Pendant of Protection +1', value: 'Eagle Shout Pendant of Protection +1' },
  { label: 'Gloom Grasp Pendant of Protection +1', value: 'Gloom Grasp Pendant of Protection +1' },
  { label: 'Grim Bender Pendant of Perfection +1', value: 'Grim Bender Pendant of Perfection +1' },
  { label: 'Honour Grasp Pendant of the Twins +1', value: 'Honour Grasp Pendant of the Twins +1' },
  { label: 'Honour Shout Pendant of Detection +1', value: 'Honour Shout Pendant of Detection +1' },
  { label: 'Kraken Grasp Pendant of Detection +1', value: 'Kraken Grasp Pendant of Detection +1' },
  { label: 'Kraken Peak Pendant of Reflection +1', value: 'Kraken Peak Pendant of Reflection +1' },
  { label: 'Kraken Shout Pendant of Detection +1', value: 'Kraken Shout Pendant of Detection +1' },
  { label: 'Kraken Shout Pendant of the Twins +1', value: 'Kraken Shout Pendant of the Twins +1' },
  { label: "Light's Roar Amulet of Enlightenment", value: "Light's Roar Amulet of Enlightenment" },
  { label: "Light's Whisper Amulet of Reflection", value: "Light's Whisper Amulet of Reflection" },
  { label: 'Mind Bender Pendant of Perfection +1', value: 'Mind Bender Pendant of Perfection +1' },
  { label: 'Pandemonium Moon Pendant of Skill +1', value: 'Pandemonium Moon Pendant of Skill +1' },
  { label: 'Pandemonium Peak Pendant of Anger +1', value: 'Pandemonium Peak Pendant of Anger +1' },
  { label: 'Rage Bender Pendant of Perfection +1', value: 'Rage Bender Pendant of Perfection +1' },
  { label: 'Shimmering Bender Pendant of Fury +1', value: 'Shimmering Bender Pendant of Fury +1' },
  { label: 'Shimmering Shout Pendant of Skill +1', value: 'Shimmering Shout Pendant of Skill +1' },
  { label: 'Sorrow Bite Pendant of Reflection +1', value: 'Sorrow Bite Pendant of Reflection +1' },
  { label: 'Soul Whisper Amulet of Enlightenment', value: 'Soul Whisper Amulet of Enlightenment' },
  { label: 'Tempest Moon Pendant of the Twins +1', value: 'Tempest Moon Pendant of the Twins +1' },
  { label: 'Apocalypse Glow Amulet of Detection', value: 'Apocalypse Glow Amulet of Detection' },
  { label: 'Apocalypse Glow Amulet of the Twins', value: 'Apocalypse Glow Amulet of the Twins' },
  { label: 'Apocalypse Root Amulet of the Twins', value: 'Apocalypse Root Amulet of the Twins' },
  { label: 'Apocalypse Tear Amulet of Detection', value: 'Apocalypse Tear Amulet of Detection' },
  { label: 'Armageddon Bite Pendant of Power +1', value: 'Armageddon Bite Pendant of Power +1' },
  { label: 'Armageddon Peak Pendant of Anger +1', value: 'Armageddon Peak Pendant of Anger +1' },
  { label: 'Armageddon Shout Pendant of Rage +1', value: 'Armageddon Shout Pendant of Rage +1' },
  { label: 'Blight Bender Pendant of the Fox +1', value: 'Blight Bender Pendant of the Fox +1' },
  { label: 'Carrion Sun Amulet of Enlightenment', value: 'Carrion Sun Amulet of Enlightenment' },
  { label: 'Cataclysm Bender Pendant of Fury +1', value: 'Cataclysm Bender Pendant of Fury +1' },
  { label: 'Cataclysm Grasp Pendant of Skill +1', value: 'Cataclysm Grasp Pendant of Skill +1' },
  { label: 'Corpse Whisper Amulet of Perfection', value: 'Corpse Whisper Amulet of Perfection' },
  { label: 'Corruption Bite Pendant of Power +1', value: 'Corruption Bite Pendant of Power +1' },
  { label: 'Corruption Shout Pendant of Rage +1', value: 'Corruption Shout Pendant of Rage +1' },
  { label: 'Demon Bite Pendant of Reflection +1', value: 'Demon Bite Pendant of Reflection +1' },
  { label: 'Demon Peak Pendant of Reflection +1', value: 'Demon Peak Pendant of Reflection +1' },
  { label: 'Demon Shout Pendant of the Twins +1', value: 'Demon Shout Pendant of the Twins +1' },
  { label: 'Dragon Roar Amulet of Enlightenment', value: 'Dragon Roar Amulet of Enlightenment' },
  { label: 'Eagle Bite Pendant of Perfection +1', value: 'Eagle Bite Pendant of Perfection +1' },
  { label: 'Eagle Grasp Pendant of the Twins +1', value: 'Eagle Grasp Pendant of the Twins +1' },
  { label: 'Eagle Moon Pendant of Brilliance +1', value: 'Eagle Moon Pendant of Brilliance +1' },
  { label: 'Gloom Grasp Pendant of Detection +1', value: 'Gloom Grasp Pendant of Detection +1' },
  { label: 'Gloom Moon Pendant of Brilliance +1', value: 'Gloom Moon Pendant of Brilliance +1' },
  { label: 'Gloom Shout Pendant of Detection +1', value: 'Gloom Shout Pendant of Detection +1' },
  { label: 'Grim Grasp Pendant of Protection +1', value: 'Grim Grasp Pendant of Protection +1' },
  { label: "Light's Sun Amulet of Enlightenment", value: "Light's Sun Amulet of Enlightenment" },
  { label: 'Maelstrom Tear Amulet of Brilliance', value: 'Maelstrom Tear Amulet of Brilliance' },
  { label: 'Mind Shout Pendant of Brilliance +1', value: 'Mind Shout Pendant of Brilliance +1' },
  { label: 'Morbid Whisper Amulet of Perfection', value: 'Morbid Whisper Amulet of Perfection' },
  { label: 'Oblivion Bender Pendant of Power +1', value: 'Oblivion Bender Pendant of Power +1' },
  { label: 'Oblivion Moon Pendant of Vitriol +1', value: 'Oblivion Moon Pendant of Vitriol +1' },
  { label: 'Pandemonium Peak Pendant of Fury +1', value: 'Pandemonium Peak Pendant of Fury +1' },
  { label: 'Plague Whisper Amulet of Perfection', value: 'Plague Whisper Amulet of Perfection' },
  { label: 'Plague Whisper Amulet of Reflection', value: 'Plague Whisper Amulet of Reflection' },
  { label: 'Rage Shout Pendant of Brilliance +1', value: 'Rage Shout Pendant of Brilliance +1' },
  { label: 'Shimmering Bite Pendant of Power +1', value: 'Shimmering Bite Pendant of Power +1' },
  { label: 'Skull Grasp Pendant of Detection +1', value: 'Skull Grasp Pendant of Detection +1' },
  { label: 'Sorrow Moon Pendant of Detection +1', value: 'Sorrow Moon Pendant of Detection +1' },
  { label: 'Sorrow Moon Pendant of the Twins +1', value: 'Sorrow Moon Pendant of the Twins +1' },
  { label: 'Tempest Bender Pendant of Titans +1', value: 'Tempest Bender Pendant of Titans +1' },
  { label: 'Tempest Shout Pendant of Vitriol +1', value: 'Tempest Shout Pendant of Vitriol +1' },
  { label: 'Vengeance Glow Amulet of Brilliance', value: 'Vengeance Glow Amulet of Brilliance' },
  { label: 'Vengeance Root Amulet of Brilliance', value: 'Vengeance Root Amulet of Brilliance' },
  { label: 'Vengeance Root Amulet of Protection', value: 'Vengeance Root Amulet of Protection' },
  { label: 'Victory Grasp Pendant of Vitriol +1', value: 'Victory Grasp Pendant of Vitriol +1' },
  { label: 'Victory Shout Pendant of Vitriol +1', value: 'Victory Shout Pendant of Vitriol +1' },
  { label: 'Armageddon Moon Pendant of Rage +1', value: 'Armageddon Moon Pendant of Rage +1' },
  { label: 'Behemoth Root Amulet of Brilliance', value: 'Behemoth Root Amulet of Brilliance' },
  { label: 'Behemoth Root Amulet of Protection', value: 'Behemoth Root Amulet of Protection' },
  { label: 'Blight Bender Pendant of Titans +1', value: 'Blight Bender Pendant of Titans +1' },
  { label: 'Blight Shout Pendant of Vitriol +1', value: 'Blight Shout Pendant of Vitriol +1' },
  { label: 'Brimstone Bite Pendant of Anger +1', value: 'Brimstone Bite Pendant of Anger +1' },
  { label: 'Brimstone Moon Pendant of Skill +1', value: 'Brimstone Moon Pendant of Skill +1' },
  { label: 'Cataclysm Moon Pendant of Skill +1', value: 'Cataclysm Moon Pendant of Skill +1' },
  { label: 'Corruption Bite Pendant of Fury +1', value: 'Corruption Bite Pendant of Fury +1' },
  { label: 'Demon Bender Pendant of the Fox +1', value: 'Demon Bender Pendant of the Fox +1' },
  { label: 'Demon Moon Pendant of Detection +1', value: 'Demon Moon Pendant of Detection +1' },
  { label: 'Demon Moon Pendant of the Twins +1', value: 'Demon Moon Pendant of the Twins +1' },
  { label: 'Golem Whisper Amulet of Perfection', value: 'Golem Whisper Amulet of Perfection' },
  { label: 'Grim Bite Pendant of Reflection +1', value: 'Grim Bite Pendant of Reflection +1' },
  { label: 'Honour Bender Pendant of Titans +1', value: 'Honour Bender Pendant of Titans +1' },
  { label: 'Honour Grasp Pendant of Vitriol +1', value: 'Honour Grasp Pendant of Vitriol +1' },
  { label: 'Honour Shout Pendant of Vitriol +1', value: 'Honour Shout Pendant of Vitriol +1' },
  { label: 'Hypnotic Glow Amulet of Protection', value: 'Hypnotic Glow Amulet of Protection' },
  { label: 'Kraken Grasp Pendant of Vitriol +1', value: 'Kraken Grasp Pendant of Vitriol +1' },
  { label: 'Maelstrom Glow Amulet of the Twins', value: 'Maelstrom Glow Amulet of the Twins' },
  { label: 'Maelstrom Sun Amulet of Perfection', value: 'Maelstrom Sun Amulet of Perfection' },
  { label: 'Mind Peak Pendant of Reflection +1', value: 'Mind Peak Pendant of Reflection +1' },
  { label: 'Mind Shout Pendant of Detection +1', value: 'Mind Shout Pendant of Detection +1' },
  { label: 'Oblivion Peak Pendant of Titans +1', value: 'Oblivion Peak Pendant of Titans +1' },
  { label: 'Rage Bite Pendant of Perfection +1', value: 'Rage Bite Pendant of Perfection +1' },
  { label: 'Shimmering Moon Pendant of Rage +1', value: 'Shimmering Moon Pendant of Rage +1' },
  { label: 'Shimmering Peak Pendant of Fury +1', value: 'Shimmering Peak Pendant of Fury +1' },
  { label: 'Skull Moon Pendant of Detection +1', value: 'Skull Moon Pendant of Detection +1' },
  { label: 'Tempest Bender Pendant of Power +1', value: 'Tempest Bender Pendant of Power +1' },
  { label: 'Tempest Moon Pendant of Vitriol +1', value: 'Tempest Moon Pendant of Vitriol +1' },
  { label: 'Tempest Peak Pendant of the Fox +1', value: 'Tempest Peak Pendant of the Fox +1' },
  { label: 'Vengeance Glow Amulet of Detection', value: 'Vengeance Glow Amulet of Detection' },
  { label: 'Victory Bender Pendant of Power +1', value: 'Victory Bender Pendant of Power +1' },
  { label: 'Victory Moon Pendant of Vitriol +1', value: 'Victory Moon Pendant of Vitriol +1' },
  { label: 'Vortex Sun Amulet of Enlightenment', value: 'Vortex Sun Amulet of Enlightenment' },
  { label: 'Woe Grasp Pendant of Brilliance +1', value: 'Woe Grasp Pendant of Brilliance +1' },
  { label: 'Behemoth Tear Amulet of the Twins', value: 'Behemoth Tear Amulet of the Twins' },
  { label: 'Blight Bender Pendant of Power +1', value: 'Blight Bender Pendant of Power +1' },
  { label: 'Blight Moon Pendant of Vitriol +1', value: 'Blight Moon Pendant of Vitriol +1' },
  { label: 'Bramble Glow Amulet of Brilliance', value: 'Bramble Glow Amulet of Brilliance' },
  { label: 'Bramble Roar Amulet of Perfection', value: 'Bramble Roar Amulet of Perfection' },
  { label: 'Brimstone Bite Pendant of Fury +1', value: 'Brimstone Bite Pendant of Fury +1' },
  { label: 'Brimstone Moon Pendant of Rage +1', value: 'Brimstone Moon Pendant of Rage +1' },
  { label: 'Carrion Roar Amulet of Perfection', value: 'Carrion Roar Amulet of Perfection' },
  { label: 'Death Sun Amulet of Enlightenment', value: 'Death Sun Amulet of Enlightenment' },
  { label: 'Demon Grasp Pendant of Vitriol +1', value: 'Demon Grasp Pendant of Vitriol +1' },
  { label: 'Dread Bender Pendant of Titans +1', value: 'Dread Bender Pendant of Titans +1' },
  { label: 'Eagle Grasp Pendant of Vitriol +1', value: 'Eagle Grasp Pendant of Vitriol +1' },
  { label: 'Foe Peak Pendant of Perfection +1', value: 'Foe Peak Pendant of Perfection +1' },
  { label: 'Foe Shout Pendant of Detection +1', value: 'Foe Shout Pendant of Detection +1' },
  { label: 'Hypnotic Root Amulet of Detection', value: 'Hypnotic Root Amulet of Detection' },
  { label: 'Hypnotic Sun Amulet of Perfection', value: 'Hypnotic Sun Amulet of Perfection' },
  { label: 'Hypnotic Tear Amulet of Detection', value: 'Hypnotic Tear Amulet of Detection' },
  { label: 'Hypnotic Whisper Amulet of Titans', value: 'Hypnotic Whisper Amulet of Titans' },
  { label: 'Kraken Peak Pendant of the Fox +1', value: 'Kraken Peak Pendant of the Fox +1' },
  { label: "Light's Roar Amulet of Reflection", value: "Light's Roar Amulet of Reflection" },
  { label: "Light's Root Amulet of Protection", value: "Light's Root Amulet of Protection" },
  { label: "Light's Tear Amulet of Protection", value: "Light's Tear Amulet of Protection" },
  { label: 'Mind Bender Pendant of the Fox +1', value: 'Mind Bender Pendant of the Fox +1' },
  { label: 'Mind Moon Pendant of Detection +1', value: 'Mind Moon Pendant of Detection +1' },
  { label: 'Mind Moon Pendant of the Twins +1', value: 'Mind Moon Pendant of the Twins +1' },
  { label: 'Oblivion Bite Pendant of Anger +1', value: 'Oblivion Bite Pendant of Anger +1' },
  { label: 'Oblivion Bite Pendant of Power +1', value: 'Oblivion Bite Pendant of Power +1' },
  { label: 'Oblivion Grasp Pendant of Rage +1', value: 'Oblivion Grasp Pendant of Rage +1' },
  { label: 'Oblivion Moon Pendant of Skill +1', value: 'Oblivion Moon Pendant of Skill +1' },
  { label: 'Pain Roar Amulet of Enlightenment', value: 'Pain Roar Amulet of Enlightenment' },
  { label: 'Rune Whisper Amulet of Perfection', value: 'Rune Whisper Amulet of Perfection' },
  { label: 'Sorrow Grasp Pendant of Giants +1', value: 'Sorrow Grasp Pendant of Giants +1' },
  { label: 'Sorrow Shout Pendant of Giants +1', value: 'Sorrow Shout Pendant of Giants +1' },
  { label: 'Tempest Moon Pendant of Giants +1', value: 'Tempest Moon Pendant of Giants +1' },
  { label: 'Woe Bite Pendant of Reflection +1', value: 'Woe Bite Pendant of Reflection +1' },
  { label: 'Woe Grasp Pendant of Detection +1', value: 'Woe Grasp Pendant of Detection +1' },
  { label: 'Woe Grasp Pendant of the Twins +1', value: 'Woe Grasp Pendant of the Twins +1' },
  { label: 'Woe Peak Pendant of Perfection +1', value: 'Woe Peak Pendant of Perfection +1' },
  { label: 'Apocalypse Glow Amulet of Giants', value: 'Apocalypse Glow Amulet of Giants' },
  { label: 'Blight Bender Pendant of Fury +1', value: 'Blight Bender Pendant of Fury +1' },
  { label: 'Blight Bite Pendant of Titans +1', value: 'Blight Bite Pendant of Titans +1' },
  { label: 'Bramble Glow Amulet of Detection', value: 'Bramble Glow Amulet of Detection' },
  { label: 'Bramble Sun Amulet of Perfection', value: 'Bramble Sun Amulet of Perfection' },
  { label: 'Bramble Sun Amulet of Reflection', value: 'Bramble Sun Amulet of Reflection' },
  { label: 'Carrion Root Amulet of the Twins', value: 'Carrion Root Amulet of the Twins' },
  { label: 'Corpse Tear Amulet of Protection', value: 'Corpse Tear Amulet of Protection' },
  { label: 'Demon Bender Pendant of Power +1', value: 'Demon Bender Pendant of Power +1' },
  { label: 'Demon Bite Pendant of the Fox +1', value: 'Demon Bite Pendant of the Fox +1' },
  { label: 'Demon Peak Pendant of the Fox +1', value: 'Demon Peak Pendant of the Fox +1' },
  { label: 'Dragon Roar Amulet of Perfection', value: 'Dragon Roar Amulet of Perfection' },
  { label: 'Dragon Root Amulet of Brilliance', value: 'Dragon Root Amulet of Brilliance' },
  { label: 'Dread Peak Pendant of the Fox +1', value: 'Dread Peak Pendant of the Fox +1' },
  { label: 'Foe Bender Pendant of the Fox +1', value: 'Foe Bender Pendant of the Fox +1' },
  { label: 'Gloom Bender Pendant of Anger +1', value: 'Gloom Bender Pendant of Anger +1' },
  { label: 'Gloom Bender Pendant of Power +1', value: 'Gloom Bender Pendant of Power +1' },
  { label: 'Gloom Bite Pendant of the Fox +1', value: 'Gloom Bite Pendant of the Fox +1' },
  { label: 'Honour Bender Pendant of Fury +1', value: 'Honour Bender Pendant of Fury +1' },
  { label: 'Honour Grasp Pendant of Skill +1', value: 'Honour Grasp Pendant of Skill +1' },
  { label: 'Honour Shout Pendant of Skill +1', value: 'Honour Shout Pendant of Skill +1' },
  { label: 'Hypnotic Whisper Amulet of Power', value: 'Hypnotic Whisper Amulet of Power' },
  { label: 'Kraken Bender Pendant of Fury +1', value: 'Kraken Bender Pendant of Fury +1' },
  { label: 'Kraken Grasp Pendant of Skill +1', value: 'Kraken Grasp Pendant of Skill +1' },
  { label: 'Kraken Shout Pendant of Skill +1', value: 'Kraken Shout Pendant of Skill +1' },
  { label: "Light's Glow Amulet of the Twins", value: "Light's Glow Amulet of the Twins" },
  { label: "Light's Sun Amulet of Reflection", value: "Light's Sun Amulet of Reflection" },
  { label: "Light's Tear Amulet of Detection", value: "Light's Tear Amulet of Detection" },
  { label: "Light's Tear Amulet of the Twins", value: "Light's Tear Amulet of the Twins" },
  { label: 'Maelstrom Tear Amulet of Vitriol', value: 'Maelstrom Tear Amulet of Vitriol' },
  { label: 'Mind Grasp Pendant of Vitriol +1', value: 'Mind Grasp Pendant of Vitriol +1' },
  { label: 'Morbid Root Amulet of Brilliance', value: 'Morbid Root Amulet of Brilliance' },
  { label: 'Plague Glow Amulet of Brilliance', value: 'Plague Glow Amulet of Brilliance' },
  { label: 'Skull Bender Pendant of Power +1', value: 'Skull Bender Pendant of Power +1' },
  { label: 'Skull Bite Pendant of the Fox +1', value: 'Skull Bite Pendant of the Fox +1' },
  { label: 'Skull Shout Pendant of Giants +1', value: 'Skull Shout Pendant of Giants +1' },
  { label: 'Sorrow Moon Pendant of Giants +1', value: 'Sorrow Moon Pendant of Giants +1' },
  { label: 'Sorrow Peak Pendant of Titans +1', value: 'Sorrow Peak Pendant of Titans +1' },
  { label: 'Vengeance Root Amulet of Vitriol', value: 'Vengeance Root Amulet of Vitriol' },
  { label: 'Vengeance Tear Amulet of Vitriol', value: 'Vengeance Tear Amulet of Vitriol' },
  { label: 'Victory Moon Pendant of Skill +1', value: 'Victory Moon Pendant of Skill +1' },
  { label: 'Vortex Glow Amulet of Protection', value: 'Vortex Glow Amulet of Protection' },
  { label: 'Vortex Roar Amulet of Perfection', value: 'Vortex Roar Amulet of Perfection' },
  { label: 'Vortex Tear Amulet of Protection', value: 'Vortex Tear Amulet of Protection' },
  { label: 'Vortex Whisper Amulet of the Fox', value: 'Vortex Whisper Amulet of the Fox' },
  { label: 'Apocalypse Tear Amulet of Skill', value: 'Apocalypse Tear Amulet of Skill' },
  { label: 'Behemoth Roar Amulet of the Fox', value: 'Behemoth Roar Amulet of the Fox' },
  { label: 'Blight Bite Pendant of Power +1', value: 'Blight Bite Pendant of Power +1' },
  { label: 'Carrion Whisper Amulet of Power', value: 'Carrion Whisper Amulet of Power' },
  { label: 'Death Glow Amulet of Protection', value: 'Death Glow Amulet of Protection' },
  { label: 'Death Root Amulet of Brilliance', value: 'Death Root Amulet of Brilliance' },
  { label: 'Death Whisper Amulet of the Fox', value: 'Death Whisper Amulet of the Fox' },
  { label: 'Demon Peak Pendant of Titans +1', value: 'Demon Peak Pendant of Titans +1' },
  { label: 'Demon Shout Pendant of Skill +1', value: 'Demon Shout Pendant of Skill +1' },
  { label: 'Dragon Glow Amulet of Detection', value: 'Dragon Glow Amulet of Detection' },
  { label: 'Dragon Tear Amulet of the Twins', value: 'Dragon Tear Amulet of the Twins' },
  { label: 'Dragon Whisper Amulet of Titans', value: 'Dragon Whisper Amulet of Titans' },
  { label: 'Dread Bender Pendant of Fury +1', value: 'Dread Bender Pendant of Fury +1' },
  { label: 'Dread Grasp Pendant of Skill +1', value: 'Dread Grasp Pendant of Skill +1' },
  { label: 'Dread Moon Pendant of Giants +1', value: 'Dread Moon Pendant of Giants +1' },
  { label: 'Ghoul Root Amulet of Brilliance', value: 'Ghoul Root Amulet of Brilliance' },
  { label: 'Ghoul Tear Amulet of Protection', value: 'Ghoul Tear Amulet of Protection' },
  { label: 'Gloom Bite Pendant of Titans +1', value: 'Gloom Bite Pendant of Titans +1' },
  { label: 'Gloom Peak Pendant of Titans +1', value: 'Gloom Peak Pendant of Titans +1' },
  { label: 'Golem Glow Amulet of Brilliance', value: 'Golem Glow Amulet of Brilliance' },
  { label: 'Golem Tear Amulet of Protection', value: 'Golem Tear Amulet of Protection' },
  { label: 'Golem Whisper Amulet of the Fox', value: 'Golem Whisper Amulet of the Fox' },
  { label: 'Grim Bender Pendant of Power +1', value: 'Grim Bender Pendant of Power +1' },
  { label: 'Grim Grasp Pendant of Giants +1', value: 'Grim Grasp Pendant of Giants +1' },
  { label: 'Havoc Roar Amulet of Reflection', value: 'Havoc Roar Amulet of Reflection' },
  { label: 'Havoc Tear Amulet of Brilliance', value: 'Havoc Tear Amulet of Brilliance' },
  { label: 'Honour Bite Pendant of Power +1', value: 'Honour Bite Pendant of Power +1' },
  { label: 'Honour Peak Pendant of Anger +1', value: 'Honour Peak Pendant of Anger +1' },
  { label: 'Kraken Peak Pendant of Anger +1', value: 'Kraken Peak Pendant of Anger +1' },
  { label: 'Mind Bender Pendant of Power +1', value: 'Mind Bender Pendant of Power +1' },
  { label: 'Mind Bite Pendant of the Fox +1', value: 'Mind Bite Pendant of the Fox +1' },
  { label: 'Morbid Whisper Amulet of Titans', value: 'Morbid Whisper Amulet of Titans' },
  { label: 'Plague Tear Amulet of the Twins', value: 'Plague Tear Amulet of the Twins' },
  { label: 'Rage Bite Pendant of the Fox +1', value: 'Rage Bite Pendant of the Fox +1' },
  { label: 'Rage Shout Pendant of Giants +1', value: 'Rage Shout Pendant of Giants +1' },
  { label: 'Skull Grasp Pendant of Skill +1', value: 'Skull Grasp Pendant of Skill +1' },
  { label: 'Skull Peak Pendant of Titans +1', value: 'Skull Peak Pendant of Titans +1' },
  { label: 'Skull Shout Pendant of Skill +1', value: 'Skull Shout Pendant of Skill +1' },
  { label: 'Sorrow Peak Pendant of Anger +1', value: 'Sorrow Peak Pendant of Anger +1' },
  { label: 'Sorrow Shout Pendant of Rage +1', value: 'Sorrow Shout Pendant of Rage +1' },
  { label: 'Storm Glow Amulet of Protection', value: 'Storm Glow Amulet of Protection' },
  { label: 'Storm Roar Amulet of Perfection', value: 'Storm Roar Amulet of Perfection' },
  { label: 'Tempest Peak Pendant of Fury +1', value: 'Tempest Peak Pendant of Fury +1' },
  { label: 'Vengeance Glow Amulet of Giants', value: 'Vengeance Glow Amulet of Giants' },
  { label: 'Vengeance Roar Amulet of Titans', value: 'Vengeance Roar Amulet of Titans' },
  { label: 'Vengeance Root Amulet of Giants', value: 'Vengeance Root Amulet of Giants' },
  { label: 'Victory Moon Pendant of Rage +1', value: 'Victory Moon Pendant of Rage +1' },
  { label: 'Victory Peak Pendant of Fury +1', value: 'Victory Peak Pendant of Fury +1' },
  { label: 'Apocalypse Glow Amulet of Rage', value: 'Apocalypse Glow Amulet of Rage' },
  { label: 'Bramble Glow Amulet of Vitriol', value: 'Bramble Glow Amulet of Vitriol' },
  { label: 'Bramble Whisper Amulet of Fury', value: 'Bramble Whisper Amulet of Fury' },
  { label: 'Carrion Tear Amulet of Vitriol', value: 'Carrion Tear Amulet of Vitriol' },
  { label: 'Death Root Amulet of the Twins', value: 'Death Root Amulet of the Twins' },
  { label: 'Demon Grasp Pendant of Rage +1', value: 'Demon Grasp Pendant of Rage +1' },
  { label: 'Demon Shout Pendant of Rage +1', value: 'Demon Shout Pendant of Rage +1' },
  { label: 'Dragon Whisper Amulet of Power', value: 'Dragon Whisper Amulet of Power' },
  { label: 'Dread Peak Pendant of Power +1', value: 'Dread Peak Pendant of Power +1' },
  { label: 'Dusk Glow Amulet of Brilliance', value: 'Dusk Glow Amulet of Brilliance' },
  { label: 'Dusk Root Amulet of Protection', value: 'Dusk Root Amulet of Protection' },
  { label: 'Dusk Tear Amulet of Brilliance', value: 'Dusk Tear Amulet of Brilliance' },
  { label: 'Dusk Tear Amulet of Protection', value: 'Dusk Tear Amulet of Protection' },
  { label: 'Dusk Whisper Amulet of the Fox', value: 'Dusk Whisper Amulet of the Fox' },
  { label: 'Eagle Grasp Pendant of Rage +1', value: 'Eagle Grasp Pendant of Rage +1' },
  { label: 'Eagle Peak Pendant of Anger +1', value: 'Eagle Peak Pendant of Anger +1' },
  { label: 'Fate Glow Amulet of Protection', value: 'Fate Glow Amulet of Protection' },
  { label: 'Fate Root Amulet of Protection', value: 'Fate Root Amulet of Protection' },
  { label: 'Ghoul Glow Amulet of the Twins', value: 'Ghoul Glow Amulet of the Twins' },
  { label: 'Gloom Grasp Pendant of Rage +1', value: 'Gloom Grasp Pendant of Rage +1' },
  { label: 'Gloom Peak Pendant of Anger +1', value: 'Gloom Peak Pendant of Anger +1' },
  { label: 'Golem Sun Amulet of Perfection', value: 'Golem Sun Amulet of Perfection' },
  { label: 'Golem Sun Amulet of Reflection', value: 'Golem Sun Amulet of Reflection' },
  { label: 'Golem Whisper Amulet of Titans', value: 'Golem Whisper Amulet of Titans' },
  { label: 'Grim Peak Pendant of Titans +1', value: 'Grim Peak Pendant of Titans +1' },
  { label: 'Grim Shout Pendant of Skill +1', value: 'Grim Shout Pendant of Skill +1' },
  { label: 'Havoc Glow Amulet of the Twins', value: 'Havoc Glow Amulet of the Twins' },
  { label: 'Havoc Whisper Amulet of Titans', value: 'Havoc Whisper Amulet of Titans' },
  { label: 'Honour Bite Pendant of Fury +1', value: 'Honour Bite Pendant of Fury +1' },
  { label: 'Honour Peak Pendant of Fury +1', value: 'Honour Peak Pendant of Fury +1' },
  { label: 'Hypnotic Tear Amulet of Giants', value: 'Hypnotic Tear Amulet of Giants' },
  { label: "Light's Tear Amulet of Vitriol", value: "Light's Tear Amulet of Vitriol" },
  { label: 'Maelstrom Root Amulet of Skill', value: 'Maelstrom Root Amulet of Skill' },
  { label: 'Mind Peak Pendant of Titans +1', value: 'Mind Peak Pendant of Titans +1' },
  { label: 'Mind Shout Pendant of Skill +1', value: 'Mind Shout Pendant of Skill +1' },
  { label: 'Pain Glow Amulet of Protection', value: 'Pain Glow Amulet of Protection' },
  { label: 'Pain Root Amulet of Brilliance', value: 'Pain Root Amulet of Brilliance' },
  { label: 'Plague Whisper Amulet of Anger', value: 'Plague Whisper Amulet of Anger' },
  { label: 'Plague Whisper Amulet of Power', value: 'Plague Whisper Amulet of Power' },
  { label: 'Rage Moon Pendant of Giants +1', value: 'Rage Moon Pendant of Giants +1' },
  { label: 'Rune Roar Amulet of Reflection', value: 'Rune Roar Amulet of Reflection' },
  { label: 'Rune Tear Amulet of Brilliance', value: 'Rune Tear Amulet of Brilliance' },
  { label: 'Skull Bite Pendant of Power +1', value: 'Skull Bite Pendant of Power +1' },
  { label: 'Skull Moon Pendant of Skill +1', value: 'Skull Moon Pendant of Skill +1' },
  { label: 'Skull Peak Pendant of Power +1', value: 'Skull Peak Pendant of Power +1' },
  { label: 'Sorrow Bite Pendant of Fury +1', value: 'Sorrow Bite Pendant of Fury +1' },
  { label: 'Storm Root Amulet of the Twins', value: 'Storm Root Amulet of the Twins' },
  { label: 'Storm Sun Amulet of Perfection', value: 'Storm Sun Amulet of Perfection' },
  { label: 'Storm Tear Amulet of Detection', value: 'Storm Tear Amulet of Detection' },
  { label: 'Vengeance Root Amulet of Skill', value: 'Vengeance Root Amulet of Skill' },
  { label: 'Vengeance Sun Amulet of Titans', value: 'Vengeance Sun Amulet of Titans' },
  { label: 'Woe Bender Pendant of Anger +1', value: 'Woe Bender Pendant of Anger +1' },
  { label: 'Woe Bender Pendant of Power +1', value: 'Woe Bender Pendant of Power +1' },
  { label: 'Apocalypse Sun Amulet of Fury', value: 'Apocalypse Sun Amulet of Fury' },
  { label: 'Behemoth Glow Amulet of Skill', value: 'Behemoth Glow Amulet of Skill' },
  { label: 'Behemoth Sun Amulet of Titans', value: 'Behemoth Sun Amulet of Titans' },
  { label: 'Bramble Glow Amulet of Giants', value: 'Bramble Glow Amulet of Giants' },
  { label: 'Bramble Sun Amulet of the Fox', value: 'Bramble Sun Amulet of the Fox' },
  { label: 'Bramble Tear Amulet of Giants', value: 'Bramble Tear Amulet of Giants' },
  { label: 'Carrion Root Amulet of Giants', value: 'Carrion Root Amulet of Giants' },
  { label: 'Demon Peak Pendant of Fury +1', value: 'Demon Peak Pendant of Fury +1' },
  { label: 'Dusk Glow Amulet of Detection', value: 'Dusk Glow Amulet of Detection' },
  { label: 'Dusk Root Amulet of Detection', value: 'Dusk Root Amulet of Detection' },
  { label: 'Dusk Whisper Amulet of Titans', value: 'Dusk Whisper Amulet of Titans' },
  { label: 'Eagle Bite Pendant of Fury +1', value: 'Eagle Bite Pendant of Fury +1' },
  { label: 'Fate Glow Amulet of Detection', value: 'Fate Glow Amulet of Detection' },
  { label: 'Fate Root Amulet of the Twins', value: 'Fate Root Amulet of the Twins' },
  { label: 'Fate Sun Amulet of Reflection', value: 'Fate Sun Amulet of Reflection' },
  { label: 'Foe Bender Pendant of Fury +1', value: 'Foe Bender Pendant of Fury +1' },
  { label: 'Gloom Peak Pendant of Fury +1', value: 'Gloom Peak Pendant of Fury +1' },
  { label: 'Grim Bite Pendant of Power +1', value: 'Grim Bite Pendant of Power +1' },
  { label: 'Grim Peak Pendant of Anger +1', value: 'Grim Peak Pendant of Anger +1' },
  { label: 'Grim Peak Pendant of Power +1', value: 'Grim Peak Pendant of Power +1' },
  { label: 'Grim Shout Pendant of Rage +1', value: 'Grim Shout Pendant of Rage +1' },
  { label: 'Havoc Whisper Amulet of Anger', value: 'Havoc Whisper Amulet of Anger' },
  { label: 'Hypnotic Roar Amulet of Power', value: 'Hypnotic Roar Amulet of Power' },
  { label: "Light's Tear Amulet of Giants", value: "Light's Tear Amulet of Giants" },
  { label: 'Maelstrom Glow Amulet of Rage', value: 'Maelstrom Glow Amulet of Rage' },
  { label: 'Maelstrom Roar Amulet of Fury', value: 'Maelstrom Roar Amulet of Fury' },
  { label: 'Mind Bite Pendant of Power +1', value: 'Mind Bite Pendant of Power +1' },
  { label: 'Mind Peak Pendant of Anger +1', value: 'Mind Peak Pendant of Anger +1' },
  { label: 'Morbid Tear Amulet of Vitriol', value: 'Morbid Tear Amulet of Vitriol' },
  { label: 'Pain Sun Amulet of Perfection', value: 'Pain Sun Amulet of Perfection' },
  { label: 'Pain Tear Amulet of Detection', value: 'Pain Tear Amulet of Detection' },
  { label: 'Pain Whisper Amulet of Titans', value: 'Pain Whisper Amulet of Titans' },
  { label: 'Plague Roar Amulet of the Fox', value: 'Plague Roar Amulet of the Fox' },
  { label: 'Rage Bite Pendant of Power +1', value: 'Rage Bite Pendant of Power +1' },
  { label: 'Rage Grasp Pendant of Rage +1', value: 'Rage Grasp Pendant of Rage +1' },
  { label: 'Rage Peak Pendant of Power +1', value: 'Rage Peak Pendant of Power +1' },
  { label: 'Rune Glow Amulet of Detection', value: 'Rune Glow Amulet of Detection' },
  { label: 'Soul Glow Amulet of the Twins', value: 'Soul Glow Amulet of the Twins' },
  { label: 'Storm Whisper Amulet of Power', value: 'Storm Whisper Amulet of Power' },
  { label: 'Vengeance Glow Amulet of Rage', value: 'Vengeance Glow Amulet of Rage' },
  { label: 'Vengeance Sun Amulet of Power', value: 'Vengeance Sun Amulet of Power' },
  { label: 'Vengeance Tear Amulet of Rage', value: 'Vengeance Tear Amulet of Rage' },
  { label: 'Vortex Root Amulet of Vitriol', value: 'Vortex Root Amulet of Vitriol' },
  { label: 'Woe Peak Pendant of Titans +1', value: 'Woe Peak Pendant of Titans +1' },
  { label: 'Woe Shout Pendant of Skill +1', value: 'Woe Shout Pendant of Skill +1' },
  { label: 'Behemoth Glow Amulet of Rage', value: 'Behemoth Glow Amulet of Rage' },
  { label: 'Bramble Roar Amulet of Anger', value: 'Bramble Roar Amulet of Anger' },
  { label: 'Bramble Sun Amulet of Titans', value: 'Bramble Sun Amulet of Titans' },
  { label: 'Carrion Root Amulet of Skill', value: 'Carrion Root Amulet of Skill' },
  { label: 'Death Glow Amulet of Vitriol', value: 'Death Glow Amulet of Vitriol' },
  { label: 'Death Roar Amulet of the Fox', value: 'Death Roar Amulet of the Fox' },
  { label: 'Dragon Glow Amulet of Giants', value: 'Dragon Glow Amulet of Giants' },
  { label: 'Dragon Root Amulet of Giants', value: 'Dragon Root Amulet of Giants' },
  { label: 'Dragon Tear Amulet of Giants', value: 'Dragon Tear Amulet of Giants' },
  { label: 'Dusk Whisper Amulet of Anger', value: 'Dusk Whisper Amulet of Anger' },
  { label: 'Dusk Whisper Amulet of Power', value: 'Dusk Whisper Amulet of Power' },
  { label: 'Fate Whisper Amulet of Anger', value: 'Fate Whisper Amulet of Anger' },
  { label: 'Foe Peak Pendant of Anger +1', value: 'Foe Peak Pendant of Anger +1' },
  { label: 'Foe Peak Pendant of Power +1', value: 'Foe Peak Pendant of Power +1' },
  { label: 'Foe Shout Pendant of Rage +1', value: 'Foe Shout Pendant of Rage +1' },
  { label: 'Ghoul Whisper Amulet of Fury', value: 'Ghoul Whisper Amulet of Fury' },
  { label: 'Golem Roar Amulet of the Fox', value: 'Golem Roar Amulet of the Fox' },
  { label: 'Grim Peak Pendant of Fury +1', value: 'Grim Peak Pendant of Fury +1' },
  { label: 'Hypnotic Root Amulet of Rage', value: 'Hypnotic Root Amulet of Rage' },
  { label: 'Hypnotic Sun Amulet of Anger', value: 'Hypnotic Sun Amulet of Anger' },
  { label: "Light's Roar Amulet of Power", value: "Light's Roar Amulet of Power" },
  { label: "Light's Sun Amulet of Titans", value: "Light's Sun Amulet of Titans" },
  { label: 'Mind Bite Pendant of Fury +1', value: 'Mind Bite Pendant of Fury +1' },
  { label: 'Mind Peak Pendant of Fury +1', value: 'Mind Peak Pendant of Fury +1' },
  { label: 'Morbid Glow Amulet of Giants', value: 'Morbid Glow Amulet of Giants' },
  { label: 'Plague Glow Amulet of Giants', value: 'Plague Glow Amulet of Giants' },
  { label: 'Storm Glow Amulet of Vitriol', value: 'Storm Glow Amulet of Vitriol' },
  { label: 'Storm Root Amulet of Vitriol', value: 'Storm Root Amulet of Vitriol' },
  { label: 'Vortex Tear Amulet of Giants', value: 'Vortex Tear Amulet of Giants' },
  { label: 'Behemoth Sun Amulet of Fury', value: 'Behemoth Sun Amulet of Fury' },
  { label: 'Bramble Glow Amulet of Rage', value: 'Bramble Glow Amulet of Rage' },
  { label: 'Bramble Sun Amulet of Anger', value: 'Bramble Sun Amulet of Anger' },
  { label: 'Bramble Tear Amulet of Rage', value: 'Bramble Tear Amulet of Rage' },
  { label: 'Carrion Glow Amulet of Rage', value: 'Carrion Glow Amulet of Rage' },
  { label: 'Carrion Roar Amulet of Fury', value: 'Carrion Roar Amulet of Fury' },
  { label: 'Carrion Root Amulet of Rage', value: 'Carrion Root Amulet of Rage' },
  { label: 'Carrion Tear Amulet of Rage', value: 'Carrion Tear Amulet of Rage' },
  { label: 'Corpse Roar Amulet of Anger', value: 'Corpse Roar Amulet of Anger' },
  { label: 'Corpse Root Amulet of Skill', value: 'Corpse Root Amulet of Skill' },
  { label: 'Death Glow Amulet of Giants', value: 'Death Glow Amulet of Giants' },
  { label: 'Death Roar Amulet of Titans', value: 'Death Roar Amulet of Titans' },
  { label: 'Dragon Glow Amulet of Skill', value: 'Dragon Glow Amulet of Skill' },
  { label: 'Dragon Roar Amulet of Power', value: 'Dragon Roar Amulet of Power' },
  { label: 'Dragon Root Amulet of Skill', value: 'Dragon Root Amulet of Skill' },
  { label: 'Dusk Tear Amulet of Vitriol', value: 'Dusk Tear Amulet of Vitriol' },
  { label: 'Fate Glow Amulet of Vitriol', value: 'Fate Glow Amulet of Vitriol' },
  { label: 'Ghoul Tear Amulet of Giants', value: 'Ghoul Tear Amulet of Giants' },
  { label: 'Golem Sun Amulet of the Fox', value: 'Golem Sun Amulet of the Fox' },
  { label: "Light's Roar Amulet of Fury", value: "Light's Roar Amulet of Fury" },
  { label: 'Pain Root Amulet of Vitriol', value: 'Pain Root Amulet of Vitriol' },
  { label: 'Pain Tear Amulet of Vitriol', value: 'Pain Tear Amulet of Vitriol' },
  { label: 'Plague Roar Amulet of Power', value: 'Plague Roar Amulet of Power' },
  { label: 'Plague Tear Amulet of Skill', value: 'Plague Tear Amulet of Skill' },
  { label: 'Rune Whisper Amulet of Fury', value: 'Rune Whisper Amulet of Fury' },
  { label: 'Soul Glow Amulet of Vitriol', value: 'Soul Glow Amulet of Vitriol' },
  { label: 'Storm Glow Amulet of Giants', value: 'Storm Glow Amulet of Giants' },
  { label: 'Vortex Roar Amulet of Power', value: 'Vortex Roar Amulet of Power' },
  { label: 'Woe Bite Pendant of Fury +1', value: 'Woe Bite Pendant of Fury +1' },
  { label: 'Corpse Tear Amulet of Rage', value: 'Corpse Tear Amulet of Rage' },
  { label: 'Dragon Root Amulet of Rage', value: 'Dragon Root Amulet of Rage' },
  { label: 'Dragon Sun Amulet of Anger', value: 'Dragon Sun Amulet of Anger' },
  { label: 'Dusk Sun Amulet of the Fox', value: 'Dusk Sun Amulet of the Fox' },
  { label: 'Ghoul Glow Amulet of Skill', value: 'Ghoul Glow Amulet of Skill' },
  { label: 'Ghoul Root Amulet of Skill', value: 'Ghoul Root Amulet of Skill' },
  { label: 'Havoc Sun Amulet of Titans', value: 'Havoc Sun Amulet of Titans' },
  { label: 'Morbid Roar Amulet of Fury', value: 'Morbid Roar Amulet of Fury' },
  { label: 'Morbid Root Amulet of Rage', value: 'Morbid Root Amulet of Rage' },
  { label: 'Morbid Sun Amulet of Anger', value: 'Morbid Sun Amulet of Anger' },
  { label: 'Pain Glow Amulet of Giants', value: 'Pain Glow Amulet of Giants' },
  { label: 'Pain Root Amulet of Giants', value: 'Pain Root Amulet of Giants' },
  { label: 'Rune Roar Amulet of Titans', value: 'Rune Roar Amulet of Titans' },
  { label: 'Rune Sun Amulet of the Fox', value: 'Rune Sun Amulet of the Fox' },
  { label: 'Soul Roar Amulet of Titans', value: 'Soul Roar Amulet of Titans' },
  { label: 'Soul Root Amulet of Giants', value: 'Soul Root Amulet of Giants' },
  { label: 'Soul Sun Amulet of the Fox', value: 'Soul Sun Amulet of the Fox' },
  { label: 'Storm Glow Amulet of Skill', value: 'Storm Glow Amulet of Skill' },
  { label: 'Vortex Roar Amulet of Fury', value: 'Vortex Roar Amulet of Fury' },
  { label: 'Vortex Tear Amulet of Rage', value: 'Vortex Tear Amulet of Rage' },
  { label: 'Dusk Roar Amulet of Power', value: 'Dusk Roar Amulet of Power' },
  { label: 'Ghoul Sun Amulet of Anger', value: 'Ghoul Sun Amulet of Anger' },
  { label: 'Ghoul Tear Amulet of Rage', value: 'Ghoul Tear Amulet of Rage' },
  { label: 'Golem Root Amulet of Rage', value: 'Golem Root Amulet of Rage' },
  { label: 'Golem Sun Amulet of Anger', value: 'Golem Sun Amulet of Anger' },
  { label: 'Golem Tear Amulet of Rage', value: 'Golem Tear Amulet of Rage' },
  { label: 'Havoc Roar Amulet of Fury', value: 'Havoc Roar Amulet of Fury' },
  { label: 'Havoc Sun Amulet of Power', value: 'Havoc Sun Amulet of Power' },
  { label: 'Havoc Tear Amulet of Rage', value: 'Havoc Tear Amulet of Rage' },
  { label: 'Pain Roar Amulet of Anger', value: 'Pain Roar Amulet of Anger' },
  { label: 'Rune Roar Amulet of Anger', value: 'Rune Roar Amulet of Anger' },
  { label: 'Rune Roar Amulet of Power', value: 'Rune Roar Amulet of Power' },
  { label: 'Rune Root Amulet of Skill', value: 'Rune Root Amulet of Skill' },
  { label: 'Rune Tear Amulet of Skill', value: 'Rune Tear Amulet of Skill' },
  { label: 'Soul Glow Amulet of Skill', value: 'Soul Glow Amulet of Skill' },
  { label: 'Soul Sun Amulet of Titans', value: 'Soul Sun Amulet of Titans' },
  { label: 'Storm Roar Amulet of Fury', value: 'Storm Roar Amulet of Fury' },
  { label: 'Vortex Sun Amulet of Fury', value: 'Vortex Sun Amulet of Fury' },
  { label: 'Death Sun Amulet of Fury', value: 'Death Sun Amulet of Fury' },
  { label: 'Dusk Sun Amulet of Power', value: 'Dusk Sun Amulet of Power' },
  { label: 'Dusk Tear Amulet of Rage', value: 'Dusk Tear Amulet of Rage' },
  { label: 'Fate Roar Amulet of Fury', value: 'Fate Roar Amulet of Fury' },
  { label: 'Rune Glow Amulet of Rage', value: 'Rune Glow Amulet of Rage' },
  { label: 'Rune Roar Amulet of Fury', value: 'Rune Roar Amulet of Fury' },
  { label: 'Soul Tear Amulet of Rage', value: 'Soul Tear Amulet of Rage' },
  { label: 'Dusk Sun Amulet of Fury', value: 'Dusk Sun Amulet of Fury' },
  { label: 'Fate Sun Amulet of Fury', value: 'Fate Sun Amulet of Fury' },
];
