export const rings = [
  { label: 'Silver Ring', value: 'Silver Ring' },
  { label: 'Bronze Ring', value: 'Bronze Ring' },
  { label: 'Platinum Ring', value: 'Platinum Ring' },
  { label: 'Titanium Ring', value: 'Titanium Ring' },
  { label: 'Gold Ring', value: 'Gold Ring' },
  { label: 'Titanium Ring of Power', value: 'Titanium Ring of Power' },
  { label: 'Silver Ring of Protection', value: 'Silver Ring of Protection' },
  { label: 'Platinum Ring of Reflection', value: 'Platinum Ring of Reflection' },
  { label: 'Platinum Ring of Anger', value: 'Platinum Ring of Anger' },
  { label: 'Titanium Ring of Titans', value: 'Titanium Ring of Titans' },
  { label: 'Silver Ring of the Fox', value: 'Silver Ring of the Fox' },
  { label: 'Gold Ring of Giants', value: 'Gold Ring of Giants' },
  { label: 'Titanium Ring of Brilliance', value: 'Titanium Ring of Brilliance' },
  { label: 'Titanium Ring of Giants', value: 'Titanium Ring of Giants' },
  { label: 'Platinum Ring of Vitriol', value: 'Platinum Ring of Vitriol' },
  { label: 'Titanium Ring of Vitriol', value: 'Titanium Ring of Vitriol' },
  { label: 'Bronze Ring of Vitriol', value: 'Bronze Ring of Vitriol' },
  { label: 'Silver Ring of Rage', value: 'Silver Ring of Rage' },
  { label: 'Bronze Ring of Protection', value: 'Bronze Ring of Protection' },
  { label: 'Silver Ring of Anger', value: 'Silver Ring of Anger' },
  { label: 'Platinum Ring of Brilliance', value: 'Platinum Ring of Brilliance' },
  { label: 'Silver Ring of the Twins', value: 'Silver Ring of the Twins' },
  { label: 'Gold Ring of Power', value: 'Gold Ring of Power' },
  { label: 'Platinum Ring of Detection', value: 'Platinum Ring of Detection' },
  { label: 'Platinum Ring of the Twins', value: 'Platinum Ring of the Twins' },
  { label: 'Gold Ring of Perfection', value: 'Gold Ring of Perfection' },
  { label: 'Platinum Ring of Titans', value: 'Platinum Ring of Titans' },
  { label: 'Titanium Ring of Anger', value: 'Titanium Ring of Anger' },
  { label: 'Bronze Ring of Power', value: 'Bronze Ring of Power' },
  { label: 'Silver Ring of Power', value: 'Silver Ring of Power' },
  { label: 'Gold Ring of Fury', value: 'Gold Ring of Fury' },
  { label: 'Titanium Ring of Perfection', value: 'Titanium Ring of Perfection' },
  { label: 'Bronze Ring of Perfection', value: 'Bronze Ring of Perfection' },
  { label: 'Silver Ring of Reflection', value: 'Silver Ring of Reflection' },
  { label: 'Bronze Ring of Detection', value: 'Bronze Ring of Detection' },
  { label: 'Platinum Ring of Giants', value: 'Platinum Ring of Giants' },
  { label: 'Bronze Ring of the Fox', value: 'Bronze Ring of the Fox' },
  { label: 'Titanium Ring of Fury', value: 'Titanium Ring of Fury' },
  { label: 'Gold Ring of Anger', value: 'Gold Ring of Anger' },
  { label: 'Platinum Ring of Protection', value: 'Platinum Ring of Protection' },
  { label: 'Titanium Ring of Reflection', value: 'Titanium Ring of Reflection' },
  { label: 'Platinum Ring of the Fox', value: 'Platinum Ring of the Fox' },
  { label: 'Platinum Ring of Power', value: 'Platinum Ring of Power' },
  { label: 'Titanium Ring of Skill', value: 'Titanium Ring of Skill' },
  { label: 'Gold Ring of Vitriol', value: 'Gold Ring of Vitriol' },
  { label: 'Silver Ring of Fury', value: 'Silver Ring of Fury' },
  { label: 'Platinum Ring of Enlightenment', value: 'Platinum Ring of Enlightenment' },
  { label: 'Titanium Ring of the Twins', value: 'Titanium Ring of the Twins' },
  { label: 'Silver Ring of Titans', value: 'Silver Ring of Titans' },
  { label: 'Bronze Ring of Skill', value: 'Bronze Ring of Skill' },
  { label: 'Bronze Ring of Fury', value: 'Bronze Ring of Fury' },
  { label: 'Gold Ring of Skill', value: 'Gold Ring of Skill' },
  { label: 'Gold Ring of Rage', value: 'Gold Ring of Rage' },
  { label: 'Bronze Ring of Enlightenment', value: 'Bronze Ring of Enlightenment' },
  { label: 'Titanium Ring of the Fox', value: 'Titanium Ring of the Fox' },
  { label: 'Gold Ring of the Twins', value: 'Gold Ring of the Twins' },
  { label: 'Platinum Ring of Skill', value: 'Platinum Ring of Skill' },
  { label: 'Silver Ring of Giants', value: 'Silver Ring of Giants' },
  { label: 'Bronze Ring of Anger', value: 'Bronze Ring of Anger' },
  { label: 'Gold Ring of the Fox', value: 'Gold Ring of the Fox' },
  { label: 'Silver Ring of Skill', value: 'Silver Ring of Skill' },
  { label: 'Bronze Ring of Rage', value: 'Bronze Ring of Rage' },
  { label: 'Gold Ring of Titans', value: 'Gold Ring of Titans' },
  { label: 'Titanium Ring of Enlightenment', value: 'Titanium Ring of Enlightenment' },
  { label: 'Bronze Ring of Brilliance', value: 'Bronze Ring of Brilliance' },
  { label: 'Bronze Ring of Reflection', value: 'Bronze Ring of Reflection' },
  { label: 'Bronze Ring of the Twins', value: 'Bronze Ring of the Twins' },
  { label: 'Titanium Ring of Rage', value: 'Titanium Ring of Rage' },
  { label: 'Titanium Ring of Detection', value: 'Titanium Ring of Detection' },
  { label: 'Silver Ring of Detection', value: 'Silver Ring of Detection' },
  { label: 'Gold Ring of Brilliance', value: 'Gold Ring of Brilliance' },
  { label: 'Gold Ring of Protection', value: 'Gold Ring of Protection' },
  { label: 'Gold Ring of Reflection', value: 'Gold Ring of Reflection' },
  { label: 'Silver Ring of Vitriol', value: 'Silver Ring of Vitriol' },
  { label: 'Bronze Ring of Giants', value: 'Bronze Ring of Giants' },
  { label: 'Platinum Ring of Fury', value: 'Platinum Ring of Fury' },
  { label: 'Platinum Ring of Rage', value: 'Platinum Ring of Rage' },
  { label: 'Platinum Ring of Perfection', value: 'Platinum Ring of Perfection' },
  { label: 'Silver Ring of Brilliance', value: 'Silver Ring of Brilliance' },
  { label: 'Silver Ring of Perfection', value: 'Silver Ring of Perfection' },
  { label: 'Gold Ring of Detection', value: 'Gold Ring of Detection' },
  { label: 'Bronze Ring of Titans', value: 'Bronze Ring of Titans' },
  { label: 'Gold Ring of Enlightenment', value: 'Gold Ring of Enlightenment' },
  { label: 'Titanium Ring of Protection', value: 'Titanium Ring of Protection' },
  { label: 'Silver Ring of Enlightenment', value: 'Silver Ring of Enlightenment' },
  { label: 'Sorrow Peak Titanium Ring of Enlightenment +1', value: 'Sorrow Peak Titanium Ring of Enlightenment +1' },
  { label: 'Corruption Peak Silver Ring of the Fox +1', value: 'Corruption Peak Silver Ring of the Fox +1' },
  { label: 'Blight Bender Gold Ring of Perfection +1', value: 'Blight Bender Gold Ring of Perfection +1' },
  { label: 'Brimstone Bite Platinum Ring of Power +1', value: 'Brimstone Bite Platinum Ring of Power +1' },
  { label: 'Mind Bender Silver Ring of Perfection +1', value: 'Mind Bender Silver Ring of Perfection +1' },
  { label: 'Oblivion Peak Gold Ring of Perfection +1', value: 'Oblivion Peak Gold Ring of Perfection +1' },
  { label: 'Plague Roar Silver Ring of Enlightenment', value: 'Plague Roar Silver Ring of Enlightenment' },
  { label: 'Blight Grasp Titanium Ring of Giants +1', value: 'Blight Grasp Titanium Ring of Giants +1' },
  { label: 'Mind Moon Platinum Ring of the Twins +1', value: 'Mind Moon Platinum Ring of the Twins +1' },
  { label: 'Skull Bite Bronze Ring of Perfection +1', value: 'Skull Bite Bronze Ring of Perfection +1' },
  { label: 'Dragon Glow Platinum Ring of the Twins', value: 'Dragon Glow Platinum Ring of the Twins' },
  { label: 'Skull Moon Bronze Ring of Detection +1', value: 'Skull Moon Bronze Ring of Detection +1' },
  { label: 'Skull Shout Gold Ring of Brilliance +1', value: 'Skull Shout Gold Ring of Brilliance +1' },
  { label: 'Gloom Grasp Gold Ring of Detection +1', value: 'Gloom Grasp Gold Ring of Detection +1' },
  { label: 'Rage Bender Titanium Ring of Power +1', value: 'Rage Bender Titanium Ring of Power +1' },
  { label: 'Pain Glow Platinum Ring of Detection', value: 'Pain Glow Platinum Ring of Detection' },
  { label: 'Maelstrom Root Bronze Ring of Skill', value: 'Maelstrom Root Bronze Ring of Skill' },
  { label: 'Pain Roar Titanium Ring of the Fox', value: 'Pain Roar Titanium Ring of the Fox' },
  { label: 'Woe Bender Silver Ring of Anger +1', value: 'Woe Bender Silver Ring of Anger +1' },
  { label: 'Ghoul Glow Gold Ring of Detection', value: 'Ghoul Glow Gold Ring of Detection' },
  { label: 'Grim Peak Silver Ring of Power +1', value: 'Grim Peak Silver Ring of Power +1' },
  { label: 'Mind Shout Bronze Ring of Rage +1', value: 'Mind Shout Bronze Ring of Rage +1' },
  { label: 'Morbid Tear Platinum Ring of Rage', value: 'Morbid Tear Platinum Ring of Rage' },
  { label: 'Soul Glow Titanium Ring of Giants', value: 'Soul Glow Titanium Ring of Giants' },
  { label: 'Foe Peak Silver Ring of Power +1', value: 'Foe Peak Silver Ring of Power +1' },
  { label: 'Armageddon Bender Titanium Ring of Enlightenment +1', value: 'Armageddon Bender Titanium Ring of Enlightenment +1' },
  { label: 'Brimstone Bender Titanium Ring of Enlightenment +1', value: 'Brimstone Bender Titanium Ring of Enlightenment +1' },
  { label: 'Armageddon Peak Platinum Ring of Enlightenment +1', value: 'Armageddon Peak Platinum Ring of Enlightenment +1' },
  { label: 'Corruption Bender Silver Ring of Enlightenment +1', value: 'Corruption Bender Silver Ring of Enlightenment +1' },
  { label: 'Corruption Peak Titanium Ring of Enlightenment +1', value: 'Corruption Peak Titanium Ring of Enlightenment +1' },
  { label: 'Armageddon Bender Platinum Ring of Reflection +1', value: 'Armageddon Bender Platinum Ring of Reflection +1' },
  { label: 'Cataclysm Peak Platinum Ring of Enlightenment +1', value: 'Cataclysm Peak Platinum Ring of Enlightenment +1' },
  { label: 'Corruption Bender Titanium Ring of Reflection +1', value: 'Corruption Bender Titanium Ring of Reflection +1' },
  { label: 'Pandemonium Bite Bronze Ring of Enlightenment +1', value: 'Pandemonium Bite Bronze Ring of Enlightenment +1' },
  { label: 'Apocalypse Whisper Bronze Ring of Enlightenment', value: 'Apocalypse Whisper Bronze Ring of Enlightenment' },
  { label: 'Corruption Grasp Titanium Ring of Protection +1', value: 'Corruption Grasp Titanium Ring of Protection +1' },
  { label: 'Oblivion Bite Titanium Ring of Enlightenment +1', value: 'Oblivion Bite Titanium Ring of Enlightenment +1' },
  { label: 'Oblivion Peak Platinum Ring of Enlightenment +1', value: 'Oblivion Peak Platinum Ring of Enlightenment +1' },
  { label: 'Pandemonium Shout Platinum Ring of the Twins +1', value: 'Pandemonium Shout Platinum Ring of the Twins +1' },
  { label: 'Sorrow Bender Platinum Ring of Enlightenment +1', value: 'Sorrow Bender Platinum Ring of Enlightenment +1' },
  { label: 'Brimstone Grasp Titanium Ring of Protection +1', value: 'Brimstone Grasp Titanium Ring of Protection +1' },
  { label: 'Cataclysm Shout Platinum Ring of Protection +1', value: 'Cataclysm Shout Platinum Ring of Protection +1' },
  { label: 'Corruption Bite Titanium Ring of Reflection +1', value: 'Corruption Bite Titanium Ring of Reflection +1' },
  { label: 'Corruption Grasp Platinum Ring of Detection +1', value: 'Corruption Grasp Platinum Ring of Detection +1' },
  { label: "Light's Whisper Platinum Ring of Enlightenment", value: "Light's Whisper Platinum Ring of Enlightenment" },
  { label: 'Oblivion Bender Platinum Ring of Reflection +1', value: 'Oblivion Bender Platinum Ring of Reflection +1' },
  { label: 'Shimmering Peak Platinum Ring of Perfection +1', value: 'Shimmering Peak Platinum Ring of Perfection +1' },
  { label: 'Armageddon Moon Titanium Ring of the Twins +1', value: 'Armageddon Moon Titanium Ring of the Twins +1' },
  { label: 'Brimstone Bite Platinum Ring of Reflection +1', value: 'Brimstone Bite Platinum Ring of Reflection +1' },
  { label: 'Brimstone Moon Titanium Ring of Brilliance +1', value: 'Brimstone Moon Titanium Ring of Brilliance +1' },
  { label: 'Brimstone Peak Titanium Ring of Reflection +1', value: 'Brimstone Peak Titanium Ring of Reflection +1' },
  { label: 'Cataclysm Peak Titanium Ring of Reflection +1', value: 'Cataclysm Peak Titanium Ring of Reflection +1' },
  { label: 'Kraken Peak Titanium Ring of Enlightenment +1', value: 'Kraken Peak Titanium Ring of Enlightenment +1' },
  { label: 'Oblivion Shout Platinum Ring of Protection +1', value: 'Oblivion Shout Platinum Ring of Protection +1' },
  { label: 'Pandemonium Shout Bronze Ring of Detection +1', value: 'Pandemonium Shout Bronze Ring of Detection +1' },
  { label: 'Armageddon Moon Bronze Ring of Brilliance +1', value: 'Armageddon Moon Bronze Ring of Brilliance +1' },
  { label: 'Behemoth Whisper Platinum Ring of Reflection', value: 'Behemoth Whisper Platinum Ring of Reflection' },
  { label: 'Behemoth Whisper Titanium Ring of Reflection', value: 'Behemoth Whisper Titanium Ring of Reflection' },
  { label: 'Cataclysm Moon Titanium Ring of Detection +1', value: 'Cataclysm Moon Titanium Ring of Detection +1' },
  { label: 'Corruption Bender Gold Ring of Reflection +1', value: 'Corruption Bender Gold Ring of Reflection +1' },
  { label: 'Corruption Grasp Platinum Ring of Vitriol +1', value: 'Corruption Grasp Platinum Ring of Vitriol +1' },
  { label: 'Corruption Grasp Silver Ring of Detection +1', value: 'Corruption Grasp Silver Ring of Detection +1' },
  { label: 'Corruption Moon Silver Ring of Brilliance +1', value: 'Corruption Moon Silver Ring of Brilliance +1' },
  { label: 'Eagle Bender Bronze Ring of Enlightenment +1', value: 'Eagle Bender Bronze Ring of Enlightenment +1' },
  { label: 'Hypnotic Whisper Platinum Ring of Perfection', value: 'Hypnotic Whisper Platinum Ring of Perfection' },
  { label: 'Oblivion Shout Titanium Ring of the Twins +1', value: 'Oblivion Shout Titanium Ring of the Twins +1' },
  { label: 'Pandemonium Bender Platinum Ring of Anger +1', value: 'Pandemonium Bender Platinum Ring of Anger +1' },
  { label: 'Pandemonium Bite Platinum Ring of the Fox +1', value: 'Pandemonium Bite Platinum Ring of the Fox +1' },
  { label: 'Pandemonium Grasp Platinum Ring of Giants +1', value: 'Pandemonium Grasp Platinum Ring of Giants +1' },
  { label: 'Pandemonium Moon Titanium Ring of Vitriol +1', value: 'Pandemonium Moon Titanium Ring of Vitriol +1' },
  { label: 'Shimmering Bender Titanium Ring of Titans +1', value: 'Shimmering Bender Titanium Ring of Titans +1' },
  { label: 'Shimmering Shout Titanium Ring of Vitriol +1', value: 'Shimmering Shout Titanium Ring of Vitriol +1' },
  { label: 'Skull Bender Silver Ring of Enlightenment +1', value: 'Skull Bender Silver Ring of Enlightenment +1' },
  { label: 'Tempest Grasp Titanium Ring of Protection +1', value: 'Tempest Grasp Titanium Ring of Protection +1' },
  { label: 'Apocalypse Root Platinum Ring of Brilliance', value: 'Apocalypse Root Platinum Ring of Brilliance' },
  { label: 'Apocalypse Root Titanium Ring of Brilliance', value: 'Apocalypse Root Titanium Ring of Brilliance' },
  { label: 'Armageddon Moon Platinum Ring of Vitriol +1', value: 'Armageddon Moon Platinum Ring of Vitriol +1' },
  { label: 'Brimstone Grasp Silver Ring of the Twins +1', value: 'Brimstone Grasp Silver Ring of the Twins +1' },
  { label: 'Brimstone Shout Silver Ring of the Twins +1', value: 'Brimstone Shout Silver Ring of the Twins +1' },
  { label: 'Cataclysm Shout Bronze Ring of the Twins +1', value: 'Cataclysm Shout Bronze Ring of the Twins +1' },
  { label: 'Corruption Grasp Platinum Ring of Giants +1', value: 'Corruption Grasp Platinum Ring of Giants +1' },
  { label: 'Corruption Moon Titanium Ring of Vitriol +1', value: 'Corruption Moon Titanium Ring of Vitriol +1' },
  { label: 'Dragon Whisper Silver Ring of Enlightenment', value: 'Dragon Whisper Silver Ring of Enlightenment' },
  { label: 'Maelstrom Whisper Silver Ring of Reflection', value: 'Maelstrom Whisper Silver Ring of Reflection' },
  { label: 'Oblivion Grasp Bronze Ring of Brilliance +1', value: 'Oblivion Grasp Bronze Ring of Brilliance +1' },
  { label: 'Pandemonium Bite Gold Ring of Perfection +1', value: 'Pandemonium Bite Gold Ring of Perfection +1' },
  { label: 'Pandemonium Bite Gold Ring of Reflection +1', value: 'Pandemonium Bite Gold Ring of Reflection +1' },
  { label: 'Pandemonium Shout Bronze Ring of Vitriol +1', value: 'Pandemonium Shout Bronze Ring of Vitriol +1' },
  { label: 'Rune Whisper Titanium Ring of Enlightenment', value: 'Rune Whisper Titanium Ring of Enlightenment' },
  { label: 'Skull Bender Titanium Ring of Reflection +1', value: 'Skull Bender Titanium Ring of Reflection +1' },
  { label: 'Soul Whisper Platinum Ring of Enlightenment', value: 'Soul Whisper Platinum Ring of Enlightenment' },
  { label: 'Soul Whisper Titanium Ring of Enlightenment', value: 'Soul Whisper Titanium Ring of Enlightenment' },
  { label: 'Tempest Bite Platinum Ring of Perfection +1', value: 'Tempest Bite Platinum Ring of Perfection +1' },
  { label: 'Tempest Peak Platinum Ring of Perfection +1', value: 'Tempest Peak Platinum Ring of Perfection +1' },
  { label: 'Apocalypse Root Titanium Ring of Detection', value: 'Apocalypse Root Titanium Ring of Detection' },
  { label: 'Apocalypse Whisper Platinum Ring of Titans', value: 'Apocalypse Whisper Platinum Ring of Titans' },
  { label: 'Armageddon Grasp Gold Ring of Detection +1', value: 'Armageddon Grasp Gold Ring of Detection +1' },
  { label: 'Armageddon Moon Platinum Ring of Giants +1', value: 'Armageddon Moon Platinum Ring of Giants +1' },
  { label: 'Armageddon Peak Gold Ring of Perfection +1', value: 'Armageddon Peak Gold Ring of Perfection +1' },
  { label: 'Blight Moon Titanium Ring of Brilliance +1', value: 'Blight Moon Titanium Ring of Brilliance +1' },
  { label: 'Brimstone Grasp Gold Ring of Brilliance +1', value: 'Brimstone Grasp Gold Ring of Brilliance +1' },
  { label: 'Brimstone Grasp Titanium Ring of Giants +1', value: 'Brimstone Grasp Titanium Ring of Giants +1' },
  { label: 'Brimstone Moon Silver Ring of Detection +1', value: 'Brimstone Moon Silver Ring of Detection +1' },
  { label: 'Brimstone Shout Titanium Ring of Giants +1', value: 'Brimstone Shout Titanium Ring of Giants +1' },
  { label: 'Carrion Whisper Gold Ring of Enlightenment', value: 'Carrion Whisper Gold Ring of Enlightenment' },
  { label: 'Cataclysm Peak Platinum Ring of the Fox +1', value: 'Cataclysm Peak Platinum Ring of the Fox +1' },
  { label: 'Corruption Shout Silver Ring of Vitriol +1', value: 'Corruption Shout Silver Ring of Vitriol +1' },
  { label: 'Demon Grasp Titanium Ring of Brilliance +1', value: 'Demon Grasp Titanium Ring of Brilliance +1' },
  { label: 'Dread Bite Bronze Ring of Enlightenment +1', value: 'Dread Bite Bronze Ring of Enlightenment +1' },
  { label: 'Dread Grasp Platinum Ring of Protection +1', value: 'Dread Grasp Platinum Ring of Protection +1' },
  { label: 'Dread Shout Platinum Ring of Protection +1', value: 'Dread Shout Platinum Ring of Protection +1' },
  { label: 'Foe Bite Platinum Ring of Enlightenment +1', value: 'Foe Bite Platinum Ring of Enlightenment +1' },
  { label: 'Honour Bite Titanium Ring of Perfection +1', value: 'Honour Bite Titanium Ring of Perfection +1' },
  { label: 'Honour Grasp Platinum Ring of the Twins +1', value: 'Honour Grasp Platinum Ring of the Twins +1' },
  { label: 'Kraken Bite Platinum Ring of Reflection +1', value: 'Kraken Bite Platinum Ring of Reflection +1' },
  { label: 'Kraken Shout Platinum Ring of the Twins +1', value: 'Kraken Shout Platinum Ring of the Twins +1' },
  { label: "Light's Sun Platinum Ring of Enlightenment", value: "Light's Sun Platinum Ring of Enlightenment" },
  { label: 'Maelstrom Sun Bronze Ring of Enlightenment', value: 'Maelstrom Sun Bronze Ring of Enlightenment' },
  { label: 'Maelstrom Sun Silver Ring of Enlightenment', value: 'Maelstrom Sun Silver Ring of Enlightenment' },
  { label: 'Morbid Roar Platinum Ring of Enlightenment', value: 'Morbid Roar Platinum Ring of Enlightenment' },
  { label: 'Oblivion Bite Silver Ring of Reflection +1', value: 'Oblivion Bite Silver Ring of Reflection +1' },
  { label: 'Oblivion Shout Bronze Ring of Detection +1', value: 'Oblivion Shout Bronze Ring of Detection +1' },
  { label: 'Oblivion Shout Bronze Ring of the Twins +1', value: 'Oblivion Shout Bronze Ring of the Twins +1' },
  { label: 'Pandemonium Bender Gold Ring of the Fox +1', value: 'Pandemonium Bender Gold Ring of the Fox +1' },
  { label: 'Pandemonium Moon Platinum Ring of Skill +1', value: 'Pandemonium Moon Platinum Ring of Skill +1' },
  { label: 'Pandemonium Shout Titanium Ring of Rage +1', value: 'Pandemonium Shout Titanium Ring of Rage +1' },
  { label: 'Rage Bender Platinum Ring of Perfection +1', value: 'Rage Bender Platinum Ring of Perfection +1' },
  { label: 'Skull Grasp Titanium Ring of Brilliance +1', value: 'Skull Grasp Titanium Ring of Brilliance +1' },
  { label: 'Skull Shout Titanium Ring of Brilliance +1', value: 'Skull Shout Titanium Ring of Brilliance +1' },
  { label: 'Sorrow Bender Silver Ring of Reflection +1', value: 'Sorrow Bender Silver Ring of Reflection +1' },
  { label: 'Tempest Moon Platinum Ring of the Twins +1', value: 'Tempest Moon Platinum Ring of the Twins +1' },
  { label: 'Vengeance Glow Titanium Ring of Protection', value: 'Vengeance Glow Titanium Ring of Protection' },
  { label: 'Apocalypse Roar Bronze Ring of Reflection', value: 'Apocalypse Roar Bronze Ring of Reflection' },
  { label: 'Apocalypse Root Bronze Ring of Protection', value: 'Apocalypse Root Bronze Ring of Protection' },
  { label: 'Apocalypse Whisper Titanium Ring of Anger', value: 'Apocalypse Whisper Titanium Ring of Anger' },
  { label: 'Armageddon Bite Platinum Ring of Anger +1', value: 'Armageddon Bite Platinum Ring of Anger +1' },
  { label: 'Behemoth Root Platinum Ring of Protection', value: 'Behemoth Root Platinum Ring of Protection' },
  { label: 'Blight Moon Titanium Ring of the Twins +1', value: 'Blight Moon Titanium Ring of the Twins +1' },
  { label: 'Brimstone Moon Platinum Ring of Giants +1', value: 'Brimstone Moon Platinum Ring of Giants +1' },
  { label: 'Brimstone Peak Gold Ring of Reflection +1', value: 'Brimstone Peak Gold Ring of Reflection +1' },
  { label: 'Cataclysm Bite Titanium Ring of Titans +1', value: 'Cataclysm Bite Titanium Ring of Titans +1' },
  { label: 'Cataclysm Grasp Platinum Ring of Skill +1', value: 'Cataclysm Grasp Platinum Ring of Skill +1' },
  { label: 'Cataclysm Moon Platinum Ring of Giants +1', value: 'Cataclysm Moon Platinum Ring of Giants +1' },
  { label: 'Cataclysm Shout Gold Ring of Detection +1', value: 'Cataclysm Shout Gold Ring of Detection +1' },
  { label: 'Corruption Bender Silver Ring of Anger +1', value: 'Corruption Bender Silver Ring of Anger +1' },
  { label: 'Corruption Bite Titanium Ring of Power +1', value: 'Corruption Bite Titanium Ring of Power +1' },
  { label: 'Corruption Grasp Platinum Ring of Rage +1', value: 'Corruption Grasp Platinum Ring of Rage +1' },
  { label: 'Demon Bender Silver Ring of Perfection +1', value: 'Demon Bender Silver Ring of Perfection +1' },
  { label: 'Demon Bite Titanium Ring of Perfection +1', value: 'Demon Bite Titanium Ring of Perfection +1' },
  { label: 'Dread Shout Titanium Ring of Detection +1', value: 'Dread Shout Titanium Ring of Detection +1' },
  { label: 'Eagle Moon Platinum Ring of Protection +1', value: 'Eagle Moon Platinum Ring of Protection +1' },
  { label: 'Gloom Bite Titanium Ring of Perfection +1', value: 'Gloom Bite Titanium Ring of Perfection +1' },
  { label: 'Gloom Peak Platinum Ring of Reflection +1', value: 'Gloom Peak Platinum Ring of Reflection +1' },
  { label: 'Gloom Shout Titanium Ring of the Twins +1', value: 'Gloom Shout Titanium Ring of the Twins +1' },
  { label: 'Golem Whisper Titanium Ring of Perfection', value: 'Golem Whisper Titanium Ring of Perfection' },
  { label: 'Grim Bender Gold Ring of Enlightenment +1', value: 'Grim Bender Gold Ring of Enlightenment +1' },
  { label: 'Honour Peak Gold Ring of Enlightenment +1', value: 'Honour Peak Gold Ring of Enlightenment +1' },
  { label: 'Hypnotic Glow Titanium Ring of Brilliance', value: 'Hypnotic Glow Titanium Ring of Brilliance' },
  { label: 'Hypnotic Glow Titanium Ring of Protection', value: 'Hypnotic Glow Titanium Ring of Protection' },
  { label: 'Hypnotic Root Titanium Ring of Brilliance', value: 'Hypnotic Root Titanium Ring of Brilliance' },
  { label: 'Hypnotic Root Titanium Ring of Protection', value: 'Hypnotic Root Titanium Ring of Protection' },
  { label: "Light's Roar Silver Ring of Enlightenment", value: "Light's Roar Silver Ring of Enlightenment" },
  { label: 'Maelstrom Root Platinum Ring of Detection', value: 'Maelstrom Root Platinum Ring of Detection' },
  { label: 'Maelstrom Tear Platinum Ring of the Twins', value: 'Maelstrom Tear Platinum Ring of the Twins' },
  { label: 'Maelstrom Whisper Gold Ring of Perfection', value: 'Maelstrom Whisper Gold Ring of Perfection' },
  { label: 'Mind Grasp Platinum Ring of Brilliance +1', value: 'Mind Grasp Platinum Ring of Brilliance +1' },
  { label: 'Oblivion Moon Silver Ring of Detection +1', value: 'Oblivion Moon Silver Ring of Detection +1' },
  { label: 'Oblivion Shout Platinum Ring of Giants +1', value: 'Oblivion Shout Platinum Ring of Giants +1' },
  { label: 'Rage Peak Bronze Ring of Enlightenment +1', value: 'Rage Peak Bronze Ring of Enlightenment +1' },
  { label: 'Shimmering Bite Bronze Ring of the Fox +1', value: 'Shimmering Bite Bronze Ring of the Fox +1' },
  { label: 'Shimmering Moon Silver Ring of Vitriol +1', value: 'Shimmering Moon Silver Ring of Vitriol +1' },
  { label: 'Shimmering Peak Titanium Ring of Anger +1', value: 'Shimmering Peak Titanium Ring of Anger +1' },
  { label: 'Shimmering Shout Bronze Ring of Giants +1', value: 'Shimmering Shout Bronze Ring of Giants +1' },
  { label: 'Skull Grasp Titanium Ring of Detection +1', value: 'Skull Grasp Titanium Ring of Detection +1' },
  { label: 'Sorrow Moon Titanium Ring of Detection +1', value: 'Sorrow Moon Titanium Ring of Detection +1' },
  { label: 'Sorrow Peak Gold Ring of Enlightenment +1', value: 'Sorrow Peak Gold Ring of Enlightenment +1' },
  { label: 'Sorrow Shout Bronze Ring of Brilliance +1', value: 'Sorrow Shout Bronze Ring of Brilliance +1' },
  { label: 'Tempest Shout Silver Ring of the Twins +1', value: 'Tempest Shout Silver Ring of the Twins +1' },
  { label: 'Apocalypse Whisper Bronze Ring of Titans', value: 'Apocalypse Whisper Bronze Ring of Titans' },
  { label: 'Armageddon Shout Gold Ring of Vitriol +1', value: 'Armageddon Shout Gold Ring of Vitriol +1' },
  { label: 'Behemoth Sun Platinum Ring of Perfection', value: 'Behemoth Sun Platinum Ring of Perfection' },
  { label: 'Behemoth Tear Titanium Ring of Detection', value: 'Behemoth Tear Titanium Ring of Detection' },
  { label: 'Blight Grasp Silver Ring of Detection +1', value: 'Blight Grasp Silver Ring of Detection +1' },
  { label: 'Bramble Roar Titanium Ring of Perfection', value: 'Bramble Roar Titanium Ring of Perfection' },
  { label: 'Bramble Sun Silver Ring of Enlightenment', value: 'Bramble Sun Silver Ring of Enlightenment' },
  { label: 'Brimstone Bender Gold Ring of the Fox +1', value: 'Brimstone Bender Gold Ring of the Fox +1' },
  { label: 'Brimstone Bender Silver Ring of Anger +1', value: 'Brimstone Bender Silver Ring of Anger +1' },
  { label: 'Brimstone Moon Platinum Ring of Skill +1', value: 'Brimstone Moon Platinum Ring of Skill +1' },
  { label: 'Brimstone Moon Silver Ring of Vitriol +1', value: 'Brimstone Moon Silver Ring of Vitriol +1' },
  { label: 'Brimstone Peak Titanium Ring of Anger +1', value: 'Brimstone Peak Titanium Ring of Anger +1' },
  { label: 'Carrion Roar Platinum Ring of Reflection', value: 'Carrion Roar Platinum Ring of Reflection' },
  { label: 'Carrion Tear Platinum Ring of Protection', value: 'Carrion Tear Platinum Ring of Protection' },
  { label: 'Cataclysm Moon Bronze Ring of Vitriol +1', value: 'Cataclysm Moon Bronze Ring of Vitriol +1' },
  { label: 'Cataclysm Moon Gold Ring of Detection +1', value: 'Cataclysm Moon Gold Ring of Detection +1' },
  { label: 'Cataclysm Peak Titanium Ring of Anger +1', value: 'Cataclysm Peak Titanium Ring of Anger +1' },
  { label: 'Cataclysm Shout Silver Ring of Giants +1', value: 'Cataclysm Shout Silver Ring of Giants +1' },
  { label: 'Corpse Roar Silver Ring of Enlightenment', value: 'Corpse Roar Silver Ring of Enlightenment' },
  { label: 'Corruption Grasp Silver Ring of Skill +1', value: 'Corruption Grasp Silver Ring of Skill +1' },
  { label: 'Demon Grasp Silver Ring of Protection +1', value: 'Demon Grasp Silver Ring of Protection +1' },
  { label: 'Dragon Whisper Silver Ring of Reflection', value: 'Dragon Whisper Silver Ring of Reflection' },
  { label: 'Eagle Bender Platinum Ring of the Fox +1', value: 'Eagle Bender Platinum Ring of the Fox +1' },
  { label: 'Gloom Peak Gold Ring of Enlightenment +1', value: 'Gloom Peak Gold Ring of Enlightenment +1' },
  { label: 'Grim Shout Platinum Ring of Detection +1', value: 'Grim Shout Platinum Ring of Detection +1' },
  { label: 'Honour Moon Bronze Ring of Brilliance +1', value: 'Honour Moon Bronze Ring of Brilliance +1' },
  { label: 'Honour Shout Bronze Ring of Detection +1', value: 'Honour Shout Bronze Ring of Detection +1' },
  { label: 'Kraken Bite Silver Ring of Perfection +1', value: 'Kraken Bite Silver Ring of Perfection +1' },
  { label: 'Kraken Grasp Platinum Ring of Vitriol +1', value: 'Kraken Grasp Platinum Ring of Vitriol +1' },
  { label: 'Kraken Shout Titanium Ring of Vitriol +1', value: 'Kraken Shout Titanium Ring of Vitriol +1' },
  { label: 'Maelstrom Glow Silver Ring of Protection', value: 'Maelstrom Glow Silver Ring of Protection' },
  { label: 'Mind Grasp Titanium Ring of the Twins +1', value: 'Mind Grasp Titanium Ring of the Twins +1' },
  { label: 'Morbid Roar Bronze Ring of Enlightenment', value: 'Morbid Roar Bronze Ring of Enlightenment' },
  { label: 'Morbid Whisper Silver Ring of Perfection', value: 'Morbid Whisper Silver Ring of Perfection' },
  { label: 'Oblivion Grasp Titanium Ring of Skill +1', value: 'Oblivion Grasp Titanium Ring of Skill +1' },
  { label: 'Oblivion Shout Bronze Ring of Vitriol +1', value: 'Oblivion Shout Bronze Ring of Vitriol +1' },
  { label: 'Pandemonium Bite Silver Ring of Power +1', value: 'Pandemonium Bite Silver Ring of Power +1' },
  { label: 'Pandemonium Grasp Bronze Ring of Rage +1', value: 'Pandemonium Grasp Bronze Ring of Rage +1' },
  { label: 'Pandemonium Shout Gold Ring of Giants +1', value: 'Pandemonium Shout Gold Ring of Giants +1' },
  { label: 'Rage Grasp Titanium Ring of the Twins +1', value: 'Rage Grasp Titanium Ring of the Twins +1' },
  { label: 'Skull Moon Titanium Ring of Detection +1', value: 'Skull Moon Titanium Ring of Detection +1' },
  { label: 'Sorrow Bite Silver Ring of Perfection +1', value: 'Sorrow Bite Silver Ring of Perfection +1' },
  { label: 'Sorrow Grasp Silver Ring of the Twins +1', value: 'Sorrow Grasp Silver Ring of the Twins +1' },
  { label: 'Sorrow Peak Bronze Ring of Reflection +1', value: 'Sorrow Peak Bronze Ring of Reflection +1' },
  { label: 'Tempest Bender Titanium Ring of Anger +1', value: 'Tempest Bender Titanium Ring of Anger +1' },
  { label: 'Tempest Moon Bronze Ring of Detection +1', value: 'Tempest Moon Bronze Ring of Detection +1' },
  { label: 'Tempest Moon Platinum Ring of Vitriol +1', value: 'Tempest Moon Platinum Ring of Vitriol +1' },
  { label: 'Tempest Peak Platinum Ring of the Fox +1', value: 'Tempest Peak Platinum Ring of the Fox +1' },
  { label: 'Apocalypse Root Titanium Ring of Giants', value: 'Apocalypse Root Titanium Ring of Giants' },
  { label: 'Apocalypse Whisper Bronze Ring of Power', value: 'Apocalypse Whisper Bronze Ring of Power' },
  { label: 'Apocalypse Whisper Silver Ring of Power', value: 'Apocalypse Whisper Silver Ring of Power' },
  { label: 'Bramble Glow Platinum Ring of the Twins', value: 'Bramble Glow Platinum Ring of the Twins' },
  { label: 'Brimstone Moon Silver Ring of Giants +1', value: 'Brimstone Moon Silver Ring of Giants +1' },
  { label: 'Carrion Root Platinum Ring of Detection', value: 'Carrion Root Platinum Ring of Detection' },
  { label: 'Carrion Tear Titanium Ring of Detection', value: 'Carrion Tear Titanium Ring of Detection' },
  { label: 'Carrion Whisper Gold Ring of Reflection', value: 'Carrion Whisper Gold Ring of Reflection' },
  { label: 'Cataclysm Peak Titanium Ring of Fury +1', value: 'Cataclysm Peak Titanium Ring of Fury +1' },
  { label: 'Corpse Roar Platinum Ring of Perfection', value: 'Corpse Roar Platinum Ring of Perfection' },
  { label: 'Corpse Tear Titanium Ring of Protection', value: 'Corpse Tear Titanium Ring of Protection' },
  { label: 'Corruption Grasp Gold Ring of Giants +1', value: 'Corruption Grasp Gold Ring of Giants +1' },
  { label: 'Corruption Peak Silver Ring of Anger +1', value: 'Corruption Peak Silver Ring of Anger +1' },
  { label: 'Death Roar Bronze Ring of Enlightenment', value: 'Death Roar Bronze Ring of Enlightenment' },
  { label: 'Demon Grasp Bronze Ring of the Twins +1', value: 'Demon Grasp Bronze Ring of the Twins +1' },
  { label: 'Demon Shout Silver Ring of Detection +1', value: 'Demon Shout Silver Ring of Detection +1' },
  { label: 'Demon Shout Silver Ring of the Twins +1', value: 'Demon Shout Silver Ring of the Twins +1' },
  { label: 'Dragon Sun Bronze Ring of Enlightenment', value: 'Dragon Sun Bronze Ring of Enlightenment' },
  { label: 'Dragon Sun Silver Ring of Enlightenment', value: 'Dragon Sun Silver Ring of Enlightenment' },
  { label: 'Dragon Tear Titanium Ring of Brilliance', value: 'Dragon Tear Titanium Ring of Brilliance' },
  { label: 'Dread Bender Gold Ring of Perfection +1', value: 'Dread Bender Gold Ring of Perfection +1' },
  { label: 'Dread Grasp Silver Ring of Detection +1', value: 'Dread Grasp Silver Ring of Detection +1' },
  { label: 'Dread Moon Bronze Ring of Protection +1', value: 'Dread Moon Bronze Ring of Protection +1' },
  { label: 'Eagle Bender Titanium Ring of Titans +1', value: 'Eagle Bender Titanium Ring of Titans +1' },
  { label: 'Fate Sun Platinum Ring of Enlightenment', value: 'Fate Sun Platinum Ring of Enlightenment' },
  { label: 'Foe Bender Silver Ring of Reflection +1', value: 'Foe Bender Silver Ring of Reflection +1' },
  { label: 'Foe Peak Titanium Ring of Reflection +1', value: 'Foe Peak Titanium Ring of Reflection +1' },
  { label: 'Gloom Peak Silver Ring of Reflection +1', value: 'Gloom Peak Silver Ring of Reflection +1' },
  { label: 'Havoc Whisper Silver Ring of Reflection', value: 'Havoc Whisper Silver Ring of Reflection' },
  { label: 'Honour Bender Titanium Ring of Power +1', value: 'Honour Bender Titanium Ring of Power +1' },
  { label: 'Honour Bite Platinum Ring of the Fox +1', value: 'Honour Bite Platinum Ring of the Fox +1' },
  { label: 'Honour Moon Bronze Ring of Detection +1', value: 'Honour Moon Bronze Ring of Detection +1' },
  { label: 'Kraken Peak Platinum Ring of the Fox +1', value: 'Kraken Peak Platinum Ring of the Fox +1' },
  { label: "Light's Root Titanium Ring of Detection", value: "Light's Root Titanium Ring of Detection" },
  { label: "Light's Sun Titanium Ring of Perfection", value: "Light's Sun Titanium Ring of Perfection" },
  { label: 'Maelstrom Root Platinum Ring of Vitriol', value: 'Maelstrom Root Platinum Ring of Vitriol' },
  { label: 'Maelstrom Root Silver Ring of Detection', value: 'Maelstrom Root Silver Ring of Detection' },
  { label: 'Maelstrom Whisper Platinum Ring of Fury', value: 'Maelstrom Whisper Platinum Ring of Fury' },
  { label: 'Morbid Root Platinum Ring of Protection', value: 'Morbid Root Platinum Ring of Protection' },
  { label: 'Oblivion Grasp Bronze Ring of Giants +1', value: 'Oblivion Grasp Bronze Ring of Giants +1' },
  { label: 'Oblivion Shout Bronze Ring of Giants +1', value: 'Oblivion Shout Bronze Ring of Giants +1' },
  { label: 'Shimmering Bender Gold Ring of Power +1', value: 'Shimmering Bender Gold Ring of Power +1' },
  { label: 'Shimmering Grasp Gold Ring of Giants +1', value: 'Shimmering Grasp Gold Ring of Giants +1' },
  { label: 'Shimmering Peak Silver Ring of Power +1', value: 'Shimmering Peak Silver Ring of Power +1' },
  { label: 'Skull Shout Bronze Ring of Detection +1', value: 'Skull Shout Bronze Ring of Detection +1' },
  { label: 'Skull Shout Silver Ring of the Twins +1', value: 'Skull Shout Silver Ring of the Twins +1' },
  { label: 'Sorrow Bender Bronze Ring of the Fox +1', value: 'Sorrow Bender Bronze Ring of the Fox +1' },
  { label: 'Sorrow Bender Titanium Ring of Power +1', value: 'Sorrow Bender Titanium Ring of Power +1' },
  { label: 'Soul Sun Platinum Ring of Enlightenment', value: 'Soul Sun Platinum Ring of Enlightenment' },
  { label: 'Storm Whisper Bronze Ring of Perfection', value: 'Storm Whisper Bronze Ring of Perfection' },
  { label: 'Storm Whisper Bronze Ring of Reflection', value: 'Storm Whisper Bronze Ring of Reflection' },
  { label: 'Tempest Grasp Platinum Ring of Skill +1', value: 'Tempest Grasp Platinum Ring of Skill +1' },
  { label: 'Apocalypse Glow Platinum Ring of Skill', value: 'Apocalypse Glow Platinum Ring of Skill' },
  { label: 'Behemoth Roar Titanium Ring of the Fox', value: 'Behemoth Roar Titanium Ring of the Fox' },
  { label: 'Behemoth Sun Bronze Ring of Reflection', value: 'Behemoth Sun Bronze Ring of Reflection' },
  { label: 'Behemoth Tear Silver Ring of the Twins', value: 'Behemoth Tear Silver Ring of the Twins' },
  { label: 'Behemoth Tear Titanium Ring of Vitriol', value: 'Behemoth Tear Titanium Ring of Vitriol' },
  { label: 'Blight Grasp Bronze Ring of Vitriol +1', value: 'Blight Grasp Bronze Ring of Vitriol +1' },
  { label: 'Blight Grasp Gold Ring of the Twins +1', value: 'Blight Grasp Gold Ring of the Twins +1' },
  { label: 'Bramble Glow Silver Ring of Protection', value: 'Bramble Glow Silver Ring of Protection' },
  { label: 'Bramble Sun Gold Ring of Enlightenment', value: 'Bramble Sun Gold Ring of Enlightenment' },
  { label: 'Brimstone Bite Gold Ring of the Fox +1', value: 'Brimstone Bite Gold Ring of the Fox +1' },
  { label: 'Brimstone Peak Gold Ring of the Fox +1', value: 'Brimstone Peak Gold Ring of the Fox +1' },
  { label: 'Carrion Glow Bronze Ring of Brilliance', value: 'Carrion Glow Bronze Ring of Brilliance' },
  { label: 'Cataclysm Peak Gold Ring of the Fox +1', value: 'Cataclysm Peak Gold Ring of the Fox +1' },
  { label: 'Corpse Whisper Gold Ring of Perfection', value: 'Corpse Whisper Gold Ring of Perfection' },
  { label: 'Corruption Moon Gold Ring of Giants +1', value: 'Corruption Moon Gold Ring of Giants +1' },
  { label: 'Death Root Platinum Ring of Protection', value: 'Death Root Platinum Ring of Protection' },
  { label: 'Demon Moon Platinum Ring of Vitriol +1', value: 'Demon Moon Platinum Ring of Vitriol +1' },
  { label: 'Dragon Glow Titanium Ring of Detection', value: 'Dragon Glow Titanium Ring of Detection' },
  { label: 'Dread Bender Platinum Ring of Anger +1', value: 'Dread Bender Platinum Ring of Anger +1' },
  { label: 'Dread Bender Platinum Ring of Power +1', value: 'Dread Bender Platinum Ring of Power +1' },
  { label: 'Dread Peak Titanium Ring of the Fox +1', value: 'Dread Peak Titanium Ring of the Fox +1' },
  { label: 'Dread Shout Gold Ring of Protection +1', value: 'Dread Shout Gold Ring of Protection +1' },
  { label: 'Eagle Shout Gold Ring of Brilliance +1', value: 'Eagle Shout Gold Ring of Brilliance +1' },
  { label: 'Foe Moon Platinum Ring of Detection +1', value: 'Foe Moon Platinum Ring of Detection +1' },
  { label: 'Foe Shout Bronze Ring of Brilliance +1', value: 'Foe Shout Bronze Ring of Brilliance +1' },
  { label: 'Ghoul Glow Titanium Ring of Brilliance', value: 'Ghoul Glow Titanium Ring of Brilliance' },
  { label: 'Ghoul Roar Titanium Ring of Perfection', value: 'Ghoul Roar Titanium Ring of Perfection' },
  { label: 'Ghoul Sun Silver Ring of Enlightenment', value: 'Ghoul Sun Silver Ring of Enlightenment' },
  { label: 'Golem Root Platinum Ring of Brilliance', value: 'Golem Root Platinum Ring of Brilliance' },
  { label: 'Honour Moon Gold Ring of Protection +1', value: 'Honour Moon Gold Ring of Protection +1' },
  { label: 'Honour Moon Platinum Ring of Giants +1', value: 'Honour Moon Platinum Ring of Giants +1' },
  { label: 'Hypnotic Root Titanium Ring of Vitriol', value: 'Hypnotic Root Titanium Ring of Vitriol' },
  { label: 'Hypnotic Sun Silver Ring of Perfection', value: 'Hypnotic Sun Silver Ring of Perfection' },
  { label: 'Hypnotic Tear Bronze Ring of Detection', value: 'Hypnotic Tear Bronze Ring of Detection' },
  { label: 'Kraken Bite Gold Ring of Reflection +1', value: 'Kraken Bite Gold Ring of Reflection +1' },
  { label: 'Kraken Shout Platinum Ring of Skill +1', value: 'Kraken Shout Platinum Ring of Skill +1' },
  { label: 'Kraken Shout Titanium Ring of Skill +1', value: 'Kraken Shout Titanium Ring of Skill +1' },
  { label: "Light's Root Silver Ring of Brilliance", value: "Light's Root Silver Ring of Brilliance" },
  { label: 'Maelstrom Roar Platinum Ring of Titans', value: 'Maelstrom Roar Platinum Ring of Titans' },
  { label: 'Maelstrom Whisper Bronze Ring of Anger', value: 'Maelstrom Whisper Bronze Ring of Anger' },
  { label: 'Maelstrom Whisper Gold Ring of the Fox', value: 'Maelstrom Whisper Gold Ring of the Fox' },
  { label: 'Mind Bite Bronze Ring of Reflection +1', value: 'Mind Bite Bronze Ring of Reflection +1' },
  { label: 'Mind Grasp Titanium Ring of Vitriol +1', value: 'Mind Grasp Titanium Ring of Vitriol +1' },
  { label: 'Morbid Root Titanium Ring of Detection', value: 'Morbid Root Titanium Ring of Detection' },
  { label: 'Oblivion Bite Platinum Ring of Fury +1', value: 'Oblivion Bite Platinum Ring of Fury +1' },
  { label: 'Pain Whisper Bronze Ring of Perfection', value: 'Pain Whisper Bronze Ring of Perfection' },
  { label: 'Plague Glow Platinum Ring of Detection', value: 'Plague Glow Platinum Ring of Detection' },
  { label: 'Skull Bender Silver Ring of the Fox +1', value: 'Skull Bender Silver Ring of the Fox +1' },
  { label: 'Skull Moon Bronze Ring of the Twins +1', value: 'Skull Moon Bronze Ring of the Twins +1' },
  { label: 'Sorrow Bender Bronze Ring of Titans +1', value: 'Sorrow Bender Bronze Ring of Titans +1' },
  { label: 'Sorrow Grasp Silver Ring of Vitriol +1', value: 'Sorrow Grasp Silver Ring of Vitriol +1' },
  { label: 'Sorrow Moon Gold Ring of Brilliance +1', value: 'Sorrow Moon Gold Ring of Brilliance +1' },
  { label: 'Soul Whisper Bronze Ring of Perfection', value: 'Soul Whisper Bronze Ring of Perfection' },
  { label: 'Behemoth Roar Titanium Ring of Titans', value: 'Behemoth Roar Titanium Ring of Titans' },
  { label: 'Blight Bender Gold Ring of the Fox +1', value: 'Blight Bender Gold Ring of the Fox +1' },
  { label: 'Blight Bender Silver Ring of Power +1', value: 'Blight Bender Silver Ring of Power +1' },
  { label: 'Blight Moon Gold Ring of the Twins +1', value: 'Blight Moon Gold Ring of the Twins +1' },
  { label: 'Bramble Glow Silver Ring of the Twins', value: 'Bramble Glow Silver Ring of the Twins' },
  { label: 'Bramble Roar Titanium Ring of the Fox', value: 'Bramble Roar Titanium Ring of the Fox' },
  { label: 'Bramble Root Bronze Ring of the Twins', value: 'Bramble Root Bronze Ring of the Twins' },
  { label: 'Bramble Root Silver Ring of Detection', value: 'Bramble Root Silver Ring of Detection' },
  { label: 'Brimstone Grasp Gold Ring of Skill +1', value: 'Brimstone Grasp Gold Ring of Skill +1' },
  { label: 'Carrion Sun Silver Ring of Perfection', value: 'Carrion Sun Silver Ring of Perfection' },
  { label: 'Carrion Whisper Silver Ring of Titans', value: 'Carrion Whisper Silver Ring of Titans' },
  { label: 'Corpse Roar Silver Ring of Perfection', value: 'Corpse Roar Silver Ring of Perfection' },
  { label: 'Death Tear Platinum Ring of Detection', value: 'Death Tear Platinum Ring of Detection' },
  { label: 'Dragon Roar Silver Ring of Reflection', value: 'Dragon Roar Silver Ring of Reflection' },
  { label: 'Dusk Roar Platinum Ring of Perfection', value: 'Dusk Roar Platinum Ring of Perfection' },
  { label: 'Dusk Sun Silver Ring of Enlightenment', value: 'Dusk Sun Silver Ring of Enlightenment' },
  { label: 'Dusk Tear Titanium Ring of Brilliance', value: 'Dusk Tear Titanium Ring of Brilliance' },
  { label: 'Eagle Peak Gold Ring of Reflection +1', value: 'Eagle Peak Gold Ring of Reflection +1' },
  { label: 'Eagle Shout Gold Ring of Detection +1', value: 'Eagle Shout Gold Ring of Detection +1' },
  { label: 'Fate Tear Titanium Ring of Brilliance', value: 'Fate Tear Titanium Ring of Brilliance' },
  { label: 'Foe Grasp Silver Ring of the Twins +1', value: 'Foe Grasp Silver Ring of the Twins +1' },
  { label: 'Ghoul Sun Platinum Ring of Perfection', value: 'Ghoul Sun Platinum Ring of Perfection' },
  { label: 'Gloom Grasp Gold Ring of the Twins +1', value: 'Gloom Grasp Gold Ring of the Twins +1' },
  { label: 'Gloom Grasp Silver Ring of Vitriol +1', value: 'Gloom Grasp Silver Ring of Vitriol +1' },
  { label: 'Golem Sun Platinum Ring of Reflection', value: 'Golem Sun Platinum Ring of Reflection' },
  { label: 'Grim Bender Silver Ring of the Fox +1', value: 'Grim Bender Silver Ring of the Fox +1' },
  { label: 'Grim Bender Titanium Ring of Power +1', value: 'Grim Bender Titanium Ring of Power +1' },
  { label: 'Grim Grasp Platinum Ring of Giants +1', value: 'Grim Grasp Platinum Ring of Giants +1' },
  { label: 'Havoc Tear Titanium Ring of the Twins', value: 'Havoc Tear Titanium Ring of the Twins' },
  { label: 'Honour Moon Titanium Ring of Skill +1', value: 'Honour Moon Titanium Ring of Skill +1' },
  { label: 'Honour Peak Platinum Ring of Anger +1', value: 'Honour Peak Platinum Ring of Anger +1' },
  { label: 'Hypnotic Root Gold Ring of Protection', value: 'Hypnotic Root Gold Ring of Protection' },
  { label: 'Kraken Peak Platinum Ring of Power +1', value: 'Kraken Peak Platinum Ring of Power +1' },
  { label: 'Kraken Shout Platinum Ring of Rage +1', value: 'Kraken Shout Platinum Ring of Rage +1' },
  { label: 'Kraken Shout Silver Ring of Giants +1', value: 'Kraken Shout Silver Ring of Giants +1' },
  { label: "Light's Glow Titanium Ring of Vitriol", value: "Light's Glow Titanium Ring of Vitriol" },
  { label: "Light's Roar Platinum Ring of the Fox", value: "Light's Roar Platinum Ring of the Fox" },
  { label: 'Mind Grasp Gold Ring of Protection +1', value: 'Mind Grasp Gold Ring of Protection +1' },
  { label: 'Mind Grasp Platinum Ring of Giants +1', value: 'Mind Grasp Platinum Ring of Giants +1' },
  { label: 'Mind Shout Gold Ring of Protection +1', value: 'Mind Shout Gold Ring of Protection +1' },
  { label: 'Morbid Glow Silver Ring of Brilliance', value: 'Morbid Glow Silver Ring of Brilliance' },
  { label: 'Morbid Roar Bronze Ring of Reflection', value: 'Morbid Roar Bronze Ring of Reflection' },
  { label: 'Morbid Tear Bronze Ring of Protection', value: 'Morbid Tear Bronze Ring of Protection' },
  { label: 'Morbid Whisper Bronze Ring of the Fox', value: 'Morbid Whisper Bronze Ring of the Fox' },
  { label: 'Morbid Whisper Titanium Ring of Power', value: 'Morbid Whisper Titanium Ring of Power' },
  { label: 'Oblivion Moon Gold Ring of Vitriol +1', value: 'Oblivion Moon Gold Ring of Vitriol +1' },
  { label: 'Pain Glow Titanium Ring of Brilliance', value: 'Pain Glow Titanium Ring of Brilliance' },
  { label: 'Pain Whisper Titanium Ring of the Fox', value: 'Pain Whisper Titanium Ring of the Fox' },
  { label: 'Pandemonium Moon Gold Ring of Rage +1', value: 'Pandemonium Moon Gold Ring of Rage +1' },
  { label: 'Plague Roar Silver Ring of Reflection', value: 'Plague Roar Silver Ring of Reflection' },
  { label: 'Plague Root Silver Ring of Brilliance', value: 'Plague Root Silver Ring of Brilliance' },
  { label: 'Rune Root Titanium Ring of Protection', value: 'Rune Root Titanium Ring of Protection' },
  { label: 'Shimmering Peak Gold Ring of Anger +1', value: 'Shimmering Peak Gold Ring of Anger +1' },
  { label: 'Skull Shout Gold Ring of the Twins +1', value: 'Skull Shout Gold Ring of the Twins +1' },
  { label: 'Sorrow Bender Gold Ring of the Fox +1', value: 'Sorrow Bender Gold Ring of the Fox +1' },
  { label: 'Sorrow Bite Bronze Ring of the Fox +1', value: 'Sorrow Bite Bronze Ring of the Fox +1' },
  { label: 'Soul Sun Silver Ring of Enlightenment', value: 'Soul Sun Silver Ring of Enlightenment' },
  { label: 'Tempest Bender Silver Ring of Fury +1', value: 'Tempest Bender Silver Ring of Fury +1' },
  { label: 'Tempest Moon Platinum Ring of Rage +1', value: 'Tempest Moon Platinum Ring of Rage +1' },
  { label: 'Tempest Peak Platinum Ring of Fury +1', value: 'Tempest Peak Platinum Ring of Fury +1' },
  { label: 'Vengeance Glow Silver Ring of Vitriol', value: 'Vengeance Glow Silver Ring of Vitriol' },
  { label: 'Behemoth Sun Platinum Ring of Titans', value: 'Behemoth Sun Platinum Ring of Titans' },
  { label: 'Blight Peak Bronze Ring of Titans +1', value: 'Blight Peak Bronze Ring of Titans +1' },
  { label: 'Blight Shout Gold Ring of Vitriol +1', value: 'Blight Shout Gold Ring of Vitriol +1' },
  { label: 'Carrion Root Gold Ring of Protection', value: 'Carrion Root Gold Ring of Protection' },
  { label: 'Carrion Sun Platinum Ring of the Fox', value: 'Carrion Sun Platinum Ring of the Fox' },
  { label: 'Carrion Sun Titanium Ring of the Fox', value: 'Carrion Sun Titanium Ring of the Fox' },
  { label: 'Cataclysm Shout Gold Ring of Rage +1', value: 'Cataclysm Shout Gold Ring of Rage +1' },
  { label: 'Corpse Root Bronze Ring of the Twins', value: 'Corpse Root Bronze Ring of the Twins' },
  { label: 'Corpse Sun Bronze Ring of Reflection', value: 'Corpse Sun Bronze Ring of Reflection' },
  { label: 'Corpse Tear Silver Ring of the Twins', value: 'Corpse Tear Silver Ring of the Twins' },
  { label: 'Corpse Whisper Titanium Ring of Fury', value: 'Corpse Whisper Titanium Ring of Fury' },
  { label: 'Death Glow Silver Ring of Protection', value: 'Death Glow Silver Ring of Protection' },
  { label: 'Demon Bite Titanium Ring of Power +1', value: 'Demon Bite Titanium Ring of Power +1' },
  { label: 'Demon Moon Bronze Ring of Vitriol +1', value: 'Demon Moon Bronze Ring of Vitriol +1' },
  { label: 'Demon Peak Platinum Ring of Power +1', value: 'Demon Peak Platinum Ring of Power +1' },
  { label: 'Dragon Glow Bronze Ring of the Twins', value: 'Dragon Glow Bronze Ring of the Twins' },
  { label: 'Dragon Glow Silver Ring of the Twins', value: 'Dragon Glow Silver Ring of the Twins' },
  { label: 'Dread Moon Bronze Ring of Vitriol +1', value: 'Dread Moon Bronze Ring of Vitriol +1' },
  { label: 'Dread Moon Gold Ring of the Twins +1', value: 'Dread Moon Gold Ring of the Twins +1' },
  { label: 'Dread Moon Titanium Ring of Skill +1', value: 'Dread Moon Titanium Ring of Skill +1' },
  { label: 'Dusk Tear Titanium Ring of the Twins', value: 'Dusk Tear Titanium Ring of the Twins' },
  { label: 'Eagle Bite Platinum Ring of Anger +1', value: 'Eagle Bite Platinum Ring of Anger +1' },
  { label: 'Eagle Peak Platinum Ring of Anger +1', value: 'Eagle Peak Platinum Ring of Anger +1' },
  { label: 'Eagle Peak Titanium Ring of Power +1', value: 'Eagle Peak Titanium Ring of Power +1' },
  { label: 'Fate Sun Platinum Ring of Perfection', value: 'Fate Sun Platinum Ring of Perfection' },
  { label: 'Foe Bite Platinum Ring of the Fox +1', value: 'Foe Bite Platinum Ring of the Fox +1' },
  { label: 'Foe Peak Titanium Ring of the Fox +1', value: 'Foe Peak Titanium Ring of the Fox +1' },
  { label: 'Ghoul Tear Silver Ring of Brilliance', value: 'Ghoul Tear Silver Ring of Brilliance' },
  { label: 'Gloom Grasp Bronze Ring of Giants +1', value: 'Gloom Grasp Bronze Ring of Giants +1' },
  { label: 'Gloom Moon Bronze Ring of Vitriol +1', value: 'Gloom Moon Bronze Ring of Vitriol +1' },
  { label: 'Gloom Peak Bronze Ring of the Fox +1', value: 'Gloom Peak Bronze Ring of the Fox +1' },
  { label: 'Grim Grasp Platinum Ring of Skill +1', value: 'Grim Grasp Platinum Ring of Skill +1' },
  { label: 'Grim Grasp Silver Ring of Vitriol +1', value: 'Grim Grasp Silver Ring of Vitriol +1' },
  { label: 'Grim Grasp Titanium Ring of Skill +1', value: 'Grim Grasp Titanium Ring of Skill +1' },
  { label: 'Grim Moon Gold Ring of Protection +1', value: 'Grim Moon Gold Ring of Protection +1' },
  { label: 'Grim Peak Gold Ring of Perfection +1', value: 'Grim Peak Gold Ring of Perfection +1' },
  { label: 'Grim Peak Titanium Ring of Titans +1', value: 'Grim Peak Titanium Ring of Titans +1' },
  { label: 'Havoc Glow Bronze Ring of Protection', value: 'Havoc Glow Bronze Ring of Protection' },
  { label: 'Havoc Roar Bronze Ring of Perfection', value: 'Havoc Roar Bronze Ring of Perfection' },
  { label: 'Havoc Root Silver Ring of Brilliance', value: 'Havoc Root Silver Ring of Brilliance' },
  { label: 'Honour Peak Bronze Ring of Titans +1', value: 'Honour Peak Bronze Ring of Titans +1' },
  { label: 'Honour Peak Platinum Ring of Fury +1', value: 'Honour Peak Platinum Ring of Fury +1' },
  { label: 'Hypnotic Roar Titanium Ring of Power', value: 'Hypnotic Roar Titanium Ring of Power' },
  { label: 'Hypnotic Sun Platinum Ring of Titans', value: 'Hypnotic Sun Platinum Ring of Titans' },
  { label: 'Hypnotic Tear Titanium Ring of Skill', value: 'Hypnotic Tear Titanium Ring of Skill' },
  { label: 'Kraken Bite Titanium Ring of Fury +1', value: 'Kraken Bite Titanium Ring of Fury +1' },
  { label: 'Kraken Peak Titanium Ring of Fury +1', value: 'Kraken Peak Titanium Ring of Fury +1' },
  { label: 'Maelstrom Roar Titanium Ring of Fury', value: 'Maelstrom Roar Titanium Ring of Fury' },
  { label: 'Mind Bender Silver Ring of Titans +1', value: 'Mind Bender Silver Ring of Titans +1' },
  { label: 'Mind Grasp Bronze Ring of Vitriol +1', value: 'Mind Grasp Bronze Ring of Vitriol +1' },
  { label: 'Morbid Glow Titanium Ring of Vitriol', value: 'Morbid Glow Titanium Ring of Vitriol' },
  { label: 'Morbid Root Bronze Ring of Detection', value: 'Morbid Root Bronze Ring of Detection' },
  { label: 'Morbid Sun Bronze Ring of Perfection', value: 'Morbid Sun Bronze Ring of Perfection' },
  { label: 'Morbid Sun Silver Ring of Reflection', value: 'Morbid Sun Silver Ring of Reflection' },
  { label: 'Morbid Tear Titanium Ring of Vitriol', value: 'Morbid Tear Titanium Ring of Vitriol' },
  { label: 'Oblivion Moon Silver Ring of Rage +1', value: 'Oblivion Moon Silver Ring of Rage +1' },
  { label: 'Pain Roar Gold Ring of Enlightenment', value: 'Pain Roar Gold Ring of Enlightenment' },
  { label: 'Pain Sun Platinum Ring of Perfection', value: 'Pain Sun Platinum Ring of Perfection' },
  { label: 'Pain Whisper Titanium Ring of Titans', value: 'Pain Whisper Titanium Ring of Titans' },
  { label: 'Plague Glow Silver Ring of the Twins', value: 'Plague Glow Silver Ring of the Twins' },
  { label: 'Plague Roar Titanium Ring of the Fox', value: 'Plague Roar Titanium Ring of the Fox' },
  { label: 'Rage Bite Platinum Ring of Titans +1', value: 'Rage Bite Platinum Ring of Titans +1' },
  { label: 'Rage Peak Gold Ring of Reflection +1', value: 'Rage Peak Gold Ring of Reflection +1' },
  { label: 'Rune Roar Gold Ring of Enlightenment', value: 'Rune Roar Gold Ring of Enlightenment' },
  { label: 'Rune Root Platinum Ring of Detection', value: 'Rune Root Platinum Ring of Detection' },
  { label: 'Rune Tear Platinum Ring of Detection', value: 'Rune Tear Platinum Ring of Detection' },
  { label: 'Rune Whisper Platinum Ring of Titans', value: 'Rune Whisper Platinum Ring of Titans' },
  { label: 'Sorrow Bite Silver Ring of Titans +1', value: 'Sorrow Bite Silver Ring of Titans +1' },
  { label: 'Sorrow Grasp Silver Ring of Skill +1', value: 'Sorrow Grasp Silver Ring of Skill +1' },
  { label: 'Soul Glow Titanium Ring of the Twins', value: 'Soul Glow Titanium Ring of the Twins' },
  { label: 'Soul Root Titanium Ring of the Twins', value: 'Soul Root Titanium Ring of the Twins' },
  { label: 'Soul Sun Platinum Ring of Reflection', value: 'Soul Sun Platinum Ring of Reflection' },
  { label: 'Storm Root Bronze Ring of Protection', value: 'Storm Root Bronze Ring of Protection' },
  { label: 'Storm Whisper Titanium Ring of Power', value: 'Storm Whisper Titanium Ring of Power' },
  { label: 'Tempest Peak Bronze Ring of Anger +1', value: 'Tempest Peak Bronze Ring of Anger +1' },
  { label: 'Tempest Peak Silver Ring of Power +1', value: 'Tempest Peak Silver Ring of Power +1' },
  { label: 'Apocalypse Roar Gold Ring of Titans', value: 'Apocalypse Roar Gold Ring of Titans' },
  { label: 'Apocalypse Sun Bronze Ring of Power', value: 'Apocalypse Sun Bronze Ring of Power' },
  { label: 'Behemoth Root Bronze Ring of Giants', value: 'Behemoth Root Bronze Ring of Giants' },
  { label: 'Blight Bite Silver Ring of Anger +1', value: 'Blight Bite Silver Ring of Anger +1' },
  { label: 'Bramble Roar Titanium Ring of Power', value: 'Bramble Roar Titanium Ring of Power' },
  { label: 'Carrion Tear Silver Ring of Vitriol', value: 'Carrion Tear Silver Ring of Vitriol' },
  { label: 'Corpse Glow Gold Ring of Brilliance', value: 'Corpse Glow Gold Ring of Brilliance' },
  { label: 'Death Roar Platinum Ring of the Fox', value: 'Death Roar Platinum Ring of the Fox' },
  { label: 'Death Sun Bronze Ring of Perfection', value: 'Death Sun Bronze Ring of Perfection' },
  { label: 'Demon Bender Silver Ring of Fury +1', value: 'Demon Bender Silver Ring of Fury +1' },
  { label: 'Demon Shout Silver Ring of Skill +1', value: 'Demon Shout Silver Ring of Skill +1' },
  { label: 'Dread Grasp Bronze Ring of Skill +1', value: 'Dread Grasp Bronze Ring of Skill +1' },
  { label: 'Eagle Bite Bronze Ring of Titans +1', value: 'Eagle Bite Bronze Ring of Titans +1' },
  { label: 'Fate Root Silver Ring of Protection', value: 'Fate Root Silver Ring of Protection' },
  { label: 'Fate Tear Bronze Ring of Brilliance', value: 'Fate Tear Bronze Ring of Brilliance' },
  { label: 'Foe Grasp Platinum Ring of Skill +1', value: 'Foe Grasp Platinum Ring of Skill +1' },
  { label: 'Ghoul Sun Silver Ring of Perfection', value: 'Ghoul Sun Silver Ring of Perfection' },
  { label: 'Ghoul Sun Silver Ring of Reflection', value: 'Ghoul Sun Silver Ring of Reflection' },
  { label: 'Ghoul Tear Bronze Ring of Detection', value: 'Ghoul Tear Bronze Ring of Detection' },
  { label: 'Gloom Moon Platinum Ring of Rage +1', value: 'Gloom Moon Platinum Ring of Rage +1' },
  { label: 'Golem Glow Bronze Ring of Detection', value: 'Golem Glow Bronze Ring of Detection' },
  { label: 'Golem Glow Platinum Ring of Vitriol', value: 'Golem Glow Platinum Ring of Vitriol' },
  { label: 'Golem Roar Platinum Ring of the Fox', value: 'Golem Roar Platinum Ring of the Fox' },
  { label: 'Golem Root Silver Ring of the Twins', value: 'Golem Root Silver Ring of the Twins' },
  { label: 'Grim Bite Silver Ring of the Fox +1', value: 'Grim Bite Silver Ring of the Fox +1' },
  { label: 'Havoc Tear Bronze Ring of Detection', value: 'Havoc Tear Bronze Ring of Detection' },
  { label: 'Hypnotic Tear Platinum Ring of Rage', value: 'Hypnotic Tear Platinum Ring of Rage' },
  { label: 'Hypnotic Whisper Gold Ring of Anger', value: 'Hypnotic Whisper Gold Ring of Anger' },
  { label: 'Kraken Grasp Silver Ring of Rage +1', value: 'Kraken Grasp Silver Ring of Rage +1' },
  { label: 'Kraken Peak Silver Ring of Anger +1', value: 'Kraken Peak Silver Ring of Anger +1' },
  { label: 'Maelstrom Root Silver Ring of Skill', value: 'Maelstrom Root Silver Ring of Skill' },
  { label: 'Maelstrom Sun Titanium Ring of Fury', value: 'Maelstrom Sun Titanium Ring of Fury' },
  { label: 'Morbid Root Gold Ring of Protection', value: 'Morbid Root Gold Ring of Protection' },
  { label: 'Morbid Root Platinum Ring of Giants', value: 'Morbid Root Platinum Ring of Giants' },
  { label: 'Morbid Whisper Bronze Ring of Power', value: 'Morbid Whisper Bronze Ring of Power' },
  { label: 'Pain Glow Bronze Ring of Protection', value: 'Pain Glow Bronze Ring of Protection' },
  { label: 'Pain Whisper Platinum Ring of Power', value: 'Pain Whisper Platinum Ring of Power' },
  { label: 'Plague Glow Gold Ring of Protection', value: 'Plague Glow Gold Ring of Protection' },
  { label: 'Plague Glow Platinum Ring of Giants', value: 'Plague Glow Platinum Ring of Giants' },
  { label: 'Rage Bite Titanium Ring of Power +1', value: 'Rage Bite Titanium Ring of Power +1' },
  { label: 'Rage Grasp Silver Ring of Giants +1', value: 'Rage Grasp Silver Ring of Giants +1' },
  { label: 'Rage Moon Silver Ring of Vitriol +1', value: 'Rage Moon Silver Ring of Vitriol +1' },
  { label: 'Rune Roar Bronze Ring of Perfection', value: 'Rune Roar Bronze Ring of Perfection' },
  { label: 'Rune Sun Gold Ring of Enlightenment', value: 'Rune Sun Gold Ring of Enlightenment' },
  { label: 'Rune Whisper Titanium Ring of Power', value: 'Rune Whisper Titanium Ring of Power' },
  { label: 'Skull Bender Bronze Ring of Fury +1', value: 'Skull Bender Bronze Ring of Fury +1' },
  { label: 'Skull Bite Titanium Ring of Fury +1', value: 'Skull Bite Titanium Ring of Fury +1' },
  { label: 'Skull Peak Titanium Ring of Fury +1', value: 'Skull Peak Titanium Ring of Fury +1' },
  { label: 'Soul Roar Bronze Ring of Reflection', value: 'Soul Roar Bronze Ring of Reflection' },
  { label: 'Storm Sun Bronze Ring of Perfection', value: 'Storm Sun Bronze Ring of Perfection' },
  { label: 'Tempest Bender Gold Ring of Fury +1', value: 'Tempest Bender Gold Ring of Fury +1' },
  { label: 'Behemoth Roar Silver Ring of Power', value: 'Behemoth Roar Silver Ring of Power' },
  { label: 'Behemoth Sun Platinum Ring of Fury', value: 'Behemoth Sun Platinum Ring of Fury' },
  { label: 'Blight Shout Gold Ring of Skill +1', value: 'Blight Shout Gold Ring of Skill +1' },
  { label: 'Carrion Glow Bronze Ring of Giants', value: 'Carrion Glow Bronze Ring of Giants' },
  { label: 'Corpse Glow Bronze Ring of Vitriol', value: 'Corpse Glow Bronze Ring of Vitriol' },
  { label: 'Corpse Root Titanium Ring of Skill', value: 'Corpse Root Titanium Ring of Skill' },
  { label: 'Corpse Sun Gold Ring of Perfection', value: 'Corpse Sun Gold Ring of Perfection' },
  { label: 'Demon Moon Bronze Ring of Skill +1', value: 'Demon Moon Bronze Ring of Skill +1' },
  { label: 'Dragon Whisper Silver Ring of Fury', value: 'Dragon Whisper Silver Ring of Fury' },
  { label: 'Dread Bite Silver Ring of Power +1', value: 'Dread Bite Silver Ring of Power +1' },
  { label: 'Dread Shout Bronze Ring of Rage +1', value: 'Dread Shout Bronze Ring of Rage +1' },
  { label: 'Fate Root Platinum Ring of Vitriol', value: 'Fate Root Platinum Ring of Vitriol' },
  { label: 'Foe Bite Bronze Ring of the Fox +1', value: 'Foe Bite Bronze Ring of the Fox +1' },
  { label: 'Ghoul Root Gold Ring of Protection', value: 'Ghoul Root Gold Ring of Protection' },
  { label: 'Ghoul Sun Titanium Ring of the Fox', value: 'Ghoul Sun Titanium Ring of the Fox' },
  { label: 'Ghoul Whisper Silver Ring of Power', value: 'Ghoul Whisper Silver Ring of Power' },
  { label: 'Gloom Moon Bronze Ring of Skill +1', value: 'Gloom Moon Bronze Ring of Skill +1' },
  { label: 'Golem Roar Gold Ring of Reflection', value: 'Golem Roar Gold Ring of Reflection' },
  { label: 'Golem Roar Platinum Ring of Titans', value: 'Golem Roar Platinum Ring of Titans' },
  { label: 'Golem Roar Titanium Ring of Titans', value: 'Golem Roar Titanium Ring of Titans' },
  { label: 'Golem Whisper Bronze Ring of Anger', value: 'Golem Whisper Bronze Ring of Anger' },
  { label: 'Havoc Glow Gold Ring of Brilliance', value: 'Havoc Glow Gold Ring of Brilliance' },
  { label: 'Havoc Whisper Gold Ring of the Fox', value: 'Havoc Whisper Gold Ring of the Fox' },
  { label: 'Kraken Bite Silver Ring of Fury +1', value: 'Kraken Bite Silver Ring of Fury +1' },
  { label: "Light's Glow Titanium Ring of Rage", value: "Light's Glow Titanium Ring of Rage" },
  { label: "Light's Roar Bronze Ring of Titans", value: "Light's Roar Bronze Ring of Titans" },
  { label: "Light's Sun Silver Ring of the Fox", value: "Light's Sun Silver Ring of the Fox" },
  { label: "Light's Tear Titanium Ring of Rage", value: "Light's Tear Titanium Ring of Rage" },
  { label: 'Maelstrom Roar Gold Ring of Titans', value: 'Maelstrom Roar Gold Ring of Titans' },
  { label: 'Mind Bite Titanium Ring of Fury +1', value: 'Mind Bite Titanium Ring of Fury +1' },
  { label: 'Mind Moon Titanium Ring of Rage +1', value: 'Mind Moon Titanium Ring of Rage +1' },
  { label: 'Mind Shout Gold Ring of Vitriol +1', value: 'Mind Shout Gold Ring of Vitriol +1' },
  { label: 'Mind Shout Silver Ring of Skill +1', value: 'Mind Shout Silver Ring of Skill +1' },
  { label: 'Morbid Glow Gold Ring of the Twins', value: 'Morbid Glow Gold Ring of the Twins' },
  { label: 'Pain Root Platinum Ring of Vitriol', value: 'Pain Root Platinum Ring of Vitriol' },
  { label: 'Plague Roar Platinum Ring of Power', value: 'Plague Roar Platinum Ring of Power' },
  { label: 'Plague Roar Titanium Ring of Anger', value: 'Plague Roar Titanium Ring of Anger' },
  { label: 'Plague Root Silver Ring of Vitriol', value: 'Plague Root Silver Ring of Vitriol' },
  { label: 'Rage Moon Bronze Ring of Giants +1', value: 'Rage Moon Bronze Ring of Giants +1' },
  { label: 'Rune Root Platinum Ring of Vitriol', value: 'Rune Root Platinum Ring of Vitriol' },
  { label: 'Rune Sun Silver Ring of Reflection', value: 'Rune Sun Silver Ring of Reflection' },
  { label: 'Rune Tear Silver Ring of the Twins', value: 'Rune Tear Silver Ring of the Twins' },
  { label: 'Skull Bite Bronze Ring of Power +1', value: 'Skull Bite Bronze Ring of Power +1' },
  { label: 'Soul Glow Silver Ring of the Twins', value: 'Soul Glow Silver Ring of the Twins' },
  { label: 'Soul Root Silver Ring of the Twins', value: 'Soul Root Silver Ring of the Twins' },
  { label: 'Soul Root Titanium Ring of Vitriol', value: 'Soul Root Titanium Ring of Vitriol' },
  { label: 'Soul Tear Silver Ring of Detection', value: 'Soul Tear Silver Ring of Detection' },
  { label: 'Storm Roar Gold Ring of Perfection', value: 'Storm Roar Gold Ring of Perfection' },
  { label: 'Tempest Bite Gold Ring of Anger +1', value: 'Tempest Bite Gold Ring of Anger +1' },
  { label: 'Tempest Grasp Gold Ring of Rage +1', value: 'Tempest Grasp Gold Ring of Rage +1' },
  { label: 'Vengeance Roar Bronze Ring of Fury', value: 'Vengeance Roar Bronze Ring of Fury' },
  { label: 'Blight Peak Gold Ring of Power +1', value: 'Blight Peak Gold Ring of Power +1' },
  { label: 'Bramble Glow Bronze Ring of Skill', value: 'Bramble Glow Bronze Ring of Skill' },
  { label: 'Bramble Sun Platinum Ring of Fury', value: 'Bramble Sun Platinum Ring of Fury' },
  { label: 'Carrion Roar Silver Ring of Power', value: 'Carrion Roar Silver Ring of Power' },
  { label: 'Corpse Glow Platinum Ring of Rage', value: 'Corpse Glow Platinum Ring of Rage' },
  { label: 'Corpse Whisper Gold Ring of Anger', value: 'Corpse Whisper Gold Ring of Anger' },
  { label: 'Death Glow Silver Ring of Vitriol', value: 'Death Glow Silver Ring of Vitriol' },
  { label: 'Dragon Roar Silver Ring of Titans', value: 'Dragon Roar Silver Ring of Titans' },
  { label: 'Eagle Grasp Gold Ring of Skill +1', value: 'Eagle Grasp Gold Ring of Skill +1' },
  { label: 'Fate Roar Gold Ring of Reflection', value: 'Fate Roar Gold Ring of Reflection' },
  { label: 'Fate Root Platinum Ring of Giants', value: 'Fate Root Platinum Ring of Giants' },
  { label: 'Foe Peak Silver Ring of Titans +1', value: 'Foe Peak Silver Ring of Titans +1' },
  { label: 'Foe Peak Titanium Ring of Fury +1', value: 'Foe Peak Titanium Ring of Fury +1' },
  { label: 'Ghoul Whisper Silver Ring of Fury', value: 'Ghoul Whisper Silver Ring of Fury' },
  { label: 'Gloom Grasp Gold Ring of Skill +1', value: 'Gloom Grasp Gold Ring of Skill +1' },
  { label: 'Golem Glow Platinum Ring of Skill', value: 'Golem Glow Platinum Ring of Skill' },
  { label: 'Golem Root Gold Ring of the Twins', value: 'Golem Root Gold Ring of the Twins' },
  { label: 'Havoc Glow Bronze Ring of Vitriol', value: 'Havoc Glow Bronze Ring of Vitriol' },
  { label: 'Honour Bite Gold Ring of Power +1', value: 'Honour Bite Gold Ring of Power +1' },
  { label: 'Hypnotic Tear Bronze Ring of Rage', value: 'Hypnotic Tear Bronze Ring of Rage' },
  { label: 'Kraken Bite Gold Ring of Anger +1', value: 'Kraken Bite Gold Ring of Anger +1' },
  { label: "Light's Sun Bronze Ring of Titans", value: "Light's Sun Bronze Ring of Titans" },
  { label: 'Mind Bite Bronze Ring of Anger +1', value: 'Mind Bite Bronze Ring of Anger +1' },
  { label: 'Mind Moon Silver Ring of Skill +1', value: 'Mind Moon Silver Ring of Skill +1' },
  { label: 'Mind Peak Silver Ring of Anger +1', value: 'Mind Peak Silver Ring of Anger +1' },
  { label: 'Morbid Glow Silver Ring of Giants', value: 'Morbid Glow Silver Ring of Giants' },
  { label: 'Morbid Tear Silver Ring of Giants', value: 'Morbid Tear Silver Ring of Giants' },
  { label: 'Pain Glow Gold Ring of Protection', value: 'Pain Glow Gold Ring of Protection' },
  { label: 'Pain Tear Gold Ring of Protection', value: 'Pain Tear Gold Ring of Protection' },
  { label: 'Pain Tear Titanium Ring of Giants', value: 'Pain Tear Titanium Ring of Giants' },
  { label: 'Pain Whisper Silver Ring of Anger', value: 'Pain Whisper Silver Ring of Anger' },
  { label: 'Plague Root Platinum Ring of Rage', value: 'Plague Root Platinum Ring of Rage' },
  { label: 'Rage Shout Bronze Ring of Rage +1', value: 'Rage Shout Bronze Ring of Rage +1' },
  { label: 'Storm Glow Gold Ring of Detection', value: 'Storm Glow Gold Ring of Detection' },
  { label: 'Storm Roar Platinum Ring of Anger', value: 'Storm Roar Platinum Ring of Anger' },
  { label: 'Storm Root Silver Ring of Vitriol', value: 'Storm Root Silver Ring of Vitriol' },
  { label: 'Storm Whisper Gold Ring of Titans', value: 'Storm Whisper Gold Ring of Titans' },
  { label: 'Apocalypse Sun Gold Ring of Fury', value: 'Apocalypse Sun Gold Ring of Fury' },
  { label: 'Carrion Roar Bronze Ring of Fury', value: 'Carrion Roar Bronze Ring of Fury' },
  { label: 'Carrion Tear Gold Ring of Giants', value: 'Carrion Tear Gold Ring of Giants' },
  { label: 'Corpse Sun Bronze Ring of Titans', value: 'Corpse Sun Bronze Ring of Titans' },
  { label: 'Death Glow Platinum Ring of Rage', value: 'Death Glow Platinum Ring of Rage' },
  { label: 'Death Sun Bronze Ring of the Fox', value: 'Death Sun Bronze Ring of the Fox' },
  { label: 'Death Sun Platinum Ring of Power', value: 'Death Sun Platinum Ring of Power' },
  { label: 'Death Tear Titanium Ring of Rage', value: 'Death Tear Titanium Ring of Rage' },
  { label: 'Demon Moon Gold Ring of Skill +1', value: 'Demon Moon Gold Ring of Skill +1' },
  { label: 'Dragon Roar Gold Ring of the Fox', value: 'Dragon Roar Gold Ring of the Fox' },
  { label: 'Dragon Sun Titanium Ring of Fury', value: 'Dragon Sun Titanium Ring of Fury' },
  { label: 'Dusk Tear Gold Ring of the Twins', value: 'Dusk Tear Gold Ring of the Twins' },
  { label: 'Eagle Peak Gold Ring of Anger +1', value: 'Eagle Peak Gold Ring of Anger +1' },
  { label: 'Fate Root Titanium Ring of Skill', value: 'Fate Root Titanium Ring of Skill' },
  { label: 'Fate Sun Gold Ring of Reflection', value: 'Fate Sun Gold Ring of Reflection' },
  { label: 'Ghoul Roar Titanium Ring of Fury', value: 'Ghoul Roar Titanium Ring of Fury' },
  { label: 'Golem Tear Titanium Ring of Rage', value: 'Golem Tear Titanium Ring of Rage' },
  { label: 'Havoc Root Silver Ring of Giants', value: 'Havoc Root Silver Ring of Giants' },
  { label: 'Havoc Tear Bronze Ring of Giants', value: 'Havoc Tear Bronze Ring of Giants' },
  { label: 'Hypnotic Roar Gold Ring of Anger', value: 'Hypnotic Roar Gold Ring of Anger' },
  { label: "Light's Glow Gold Ring of Giants", value: "Light's Glow Gold Ring of Giants" },
  { label: 'Morbid Whisper Gold Ring of Fury', value: 'Morbid Whisper Gold Ring of Fury' },
  { label: 'Pain Roar Titanium Ring of Power', value: 'Pain Roar Titanium Ring of Power' },
  { label: 'Rage Bender Gold Ring of Fury +1', value: 'Rage Bender Gold Ring of Fury +1' },
  { label: 'Rage Bite Gold Ring of Titans +1', value: 'Rage Bite Gold Ring of Titans +1' },
  { label: 'Rage Bite Silver Ring of Fury +1', value: 'Rage Bite Silver Ring of Fury +1' },
  { label: 'Rune Glow Bronze Ring of Vitriol', value: 'Rune Glow Bronze Ring of Vitriol' },
  { label: 'Rune Glow Gold Ring of Detection', value: 'Rune Glow Gold Ring of Detection' },
  { label: 'Rune Root Titanium Ring of Skill', value: 'Rune Root Titanium Ring of Skill' },
  { label: 'Rune Tear Bronze Ring of Vitriol', value: 'Rune Tear Bronze Ring of Vitriol' },
  { label: 'Soul Roar Titanium Ring of Power', value: 'Soul Roar Titanium Ring of Power' },
  { label: 'Soul Root Bronze Ring of Vitriol', value: 'Soul Root Bronze Ring of Vitriol' },
  { label: 'Soul Root Platinum Ring of Skill', value: 'Soul Root Platinum Ring of Skill' },
  { label: 'Soul Tear Gold Ring of the Twins', value: 'Soul Tear Gold Ring of the Twins' },
  { label: 'Soul Whisper Gold Ring of Titans', value: 'Soul Whisper Gold Ring of Titans' },
  { label: 'Corpse Tear Silver Ring of Rage', value: 'Corpse Tear Silver Ring of Rage' },
  { label: 'Death Sun Bronze Ring of Titans', value: 'Death Sun Bronze Ring of Titans' },
  { label: 'Dread Bite Gold Ring of Fury +1', value: 'Dread Bite Gold Ring of Fury +1' },
  { label: 'Dusk Glow Titanium Ring of Rage', value: 'Dusk Glow Titanium Ring of Rage' },
  { label: 'Eagle Peak Gold Ring of Fury +1', value: 'Eagle Peak Gold Ring of Fury +1' },
  { label: 'Fate Glow Bronze Ring of Giants', value: 'Fate Glow Bronze Ring of Giants' },
  { label: 'Fate Root Bronze Ring of Giants', value: 'Fate Root Bronze Ring of Giants' },
  { label: 'Fate Sun Platinum Ring of Anger', value: 'Fate Sun Platinum Ring of Anger' },
  { label: 'Golem Root Bronze Ring of Skill', value: 'Golem Root Bronze Ring of Skill' },
  { label: 'Golem Sun Silver Ring of Titans', value: 'Golem Sun Silver Ring of Titans' },
  { label: 'Golem Whisper Gold Ring of Fury', value: 'Golem Whisper Gold Ring of Fury' },
  { label: 'Havoc Sun Titanium Ring of Fury', value: 'Havoc Sun Titanium Ring of Fury' },
  { label: 'Hypnotic Sun Gold Ring of Power', value: 'Hypnotic Sun Gold Ring of Power' },
  { label: "Light's Sun Gold Ring of Titans", value: "Light's Sun Gold Ring of Titans" },
  { label: 'Mind Bite Gold Ring of Power +1', value: 'Mind Bite Gold Ring of Power +1' },
  { label: 'Mind Peak Gold Ring of Anger +1', value: 'Mind Peak Gold Ring of Anger +1' },
  { label: 'Mind Shout Gold Ring of Rage +1', value: 'Mind Shout Gold Ring of Rage +1' },
  { label: 'Pain Glow Bronze Ring of Giants', value: 'Pain Glow Bronze Ring of Giants' },
  { label: 'Pain Root Titanium Ring of Rage', value: 'Pain Root Titanium Ring of Rage' },
  { label: 'Plague Glow Gold Ring of Giants', value: 'Plague Glow Gold Ring of Giants' },
  { label: 'Rage Moon Gold Ring of Skill +1', value: 'Rage Moon Gold Ring of Skill +1' },
  { label: 'Rune Sun Silver Ring of the Fox', value: 'Rune Sun Silver Ring of the Fox' },
  { label: 'Soul Roar Bronze Ring of Titans', value: 'Soul Roar Bronze Ring of Titans' },
  { label: 'Soul Roar Silver Ring of Titans', value: 'Soul Roar Silver Ring of Titans' },
  { label: 'Soul Tear Bronze Ring of Giants', value: 'Soul Tear Bronze Ring of Giants' },
  { label: 'Soul Whisper Gold Ring of Anger', value: 'Soul Whisper Gold Ring of Anger' },
  { label: 'Storm Glow Silver Ring of Skill', value: 'Storm Glow Silver Ring of Skill' },
  { label: 'Storm Tear Bronze Ring of Skill', value: 'Storm Tear Bronze Ring of Skill' },
  { label: 'Corpse Root Gold Ring of Skill', value: 'Corpse Root Gold Ring of Skill' },
  { label: 'Death Root Silver Ring of Rage', value: 'Death Root Silver Ring of Rage' },
  { label: 'Death Tear Gold Ring of Giants', value: 'Death Tear Gold Ring of Giants' },
  { label: 'Dragon Glow Gold Ring of Skill', value: 'Dragon Glow Gold Ring of Skill' },
  { label: 'Dragon Roar Gold Ring of Power', value: 'Dragon Roar Gold Ring of Power' },
  { label: 'Fate Sun Bronze Ring of Titans', value: 'Fate Sun Bronze Ring of Titans' },
  { label: 'Fate Tear Bronze Ring of Skill', value: 'Fate Tear Bronze Ring of Skill' },
  { label: 'Fate Tear Silver Ring of Skill', value: 'Fate Tear Silver Ring of Skill' },
  { label: 'Ghoul Glow Gold Ring of Giants', value: 'Ghoul Glow Gold Ring of Giants' },
  { label: 'Golem Sun Silver Ring of Anger', value: 'Golem Sun Silver Ring of Anger' },
  { label: 'Havoc Roar Bronze Ring of Fury', value: 'Havoc Roar Bronze Ring of Fury' },
  { label: "Light's Roar Gold Ring of Fury", value: "Light's Roar Gold Ring of Fury" },
  { label: "Light's Sun Gold Ring of Power", value: "Light's Sun Gold Ring of Power" },
  { label: 'Rune Roar Bronze Ring of Power', value: 'Rune Roar Bronze Ring of Power' },
  { label: 'Soul Glow Gold Ring of Vitriol', value: 'Soul Glow Gold Ring of Vitriol' },
  { label: 'Storm Root Bronze Ring of Rage', value: 'Storm Root Bronze Ring of Rage' },
  { label: 'Corpse Roar Gold Ring of Fury', value: 'Corpse Roar Gold Ring of Fury' },
  { label: 'Dragon Glow Gold Ring of Rage', value: 'Dragon Glow Gold Ring of Rage' },
  { label: 'Fate Glow Bronze Ring of Rage', value: 'Fate Glow Bronze Ring of Rage' },
  { label: 'Fate Roar Silver Ring of Fury', value: 'Fate Roar Silver Ring of Fury' },
  { label: 'Morbid Tear Gold Ring of Rage', value: 'Morbid Tear Gold Ring of Rage' },
  { label: 'Pain Tear Gold Ring of Giants', value: 'Pain Tear Gold Ring of Giants' },
  { label: 'Plague Root Gold Ring of Rage', value: 'Plague Root Gold Ring of Rage' },
  { label: 'Rune Root Silver Ring of Rage', value: 'Rune Root Silver Ring of Rage' },
  { label: 'Rune Sun Silver Ring of Anger', value: 'Rune Sun Silver Ring of Anger' },
  { label: 'Fate Sun Gold Ring of Titans', value: 'Fate Sun Gold Ring of Titans' },
  { label: 'Havoc Glow Gold Ring of Rage', value: 'Havoc Glow Gold Ring of Rage' },
  { label: 'Pain Tear Gold Ring of Rage', value: 'Pain Tear Gold Ring of Rage' },
  { label: 'Soul Root Gold Ring of Rage', value: 'Soul Root Gold Ring of Rage' },
  { label: 'Soul Sun Gold Ring of Fury', value: 'Soul Sun Gold Ring of Fury' },
  { label: 'Vengeance Roar Gold Ring of Titans', value: 'Vengeance Roar Gold Ring of Titans' },
  { label: 'Vengeance Roar Platinum Ring of Titans', value: 'Vengeance Roar Platinum Ring of Titans' },
  { label: 'Vengeance Roar Silver Ring of Enlightenment', value: 'Vengeance Roar Silver Ring of Enlightenment' },
  { label: 'Vengeance Root Gold Ring of Protection', value: 'Vengeance Root Gold Ring of Protection' },
  { label: 'Vengeance Root Titanium Ring of Giants', value: 'Vengeance Root Titanium Ring of Giants' },
  { label: 'Vengeance Sun Gold Ring of Fury', value: 'Vengeance Sun Gold Ring of Fury' },
  { label: 'Vengeance Sun Titanium Ring of the Fox', value: 'Vengeance Sun Titanium Ring of the Fox' },
  { label: 'Vengeance Tear Bronze Ring of Detection', value: 'Vengeance Tear Bronze Ring of Detection' },
  { label: 'Vengeance Tear Platinum Ring of Detection', value: 'Vengeance Tear Platinum Ring of Detection' },
  { label: 'Vengeance Tear Titanium Ring of Giants', value: 'Vengeance Tear Titanium Ring of Giants' },
  { label: 'Vengeance Whisper Platinum Ring of Fury', value: 'Vengeance Whisper Platinum Ring of Fury' },
  { label: 'Victory Bender Bronze Ring of Fury +1', value: 'Victory Bender Bronze Ring of Fury +1' },
  { label: 'Victory Bender Bronze Ring of Power +1', value: 'Victory Bender Bronze Ring of Power +1' },
  { label: 'Victory Bender Bronze Ring of Reflection +1', value: 'Victory Bender Bronze Ring of Reflection +1' },
  { label: 'Victory Bender Gold Ring of Anger +1', value: 'Victory Bender Gold Ring of Anger +1' },
  { label: 'Victory Bite Bronze Ring of Anger +1', value: 'Victory Bite Bronze Ring of Anger +1' },
  { label: 'Victory Bite Silver Ring of Power +1', value: 'Victory Bite Silver Ring of Power +1' },
  { label: 'Victory Grasp Silver Ring of Rage +1', value: 'Victory Grasp Silver Ring of Rage +1' },
  { label: 'Victory Grasp Titanium Ring of Rage +1', value: 'Victory Grasp Titanium Ring of Rage +1' },
  { label: 'Victory Grasp Titanium Ring of Skill +1', value: 'Victory Grasp Titanium Ring of Skill +1' },
  { label: 'Victory Grasp Titanium Ring of the Twins +1', value: 'Victory Grasp Titanium Ring of the Twins +1' },
  { label: 'Victory Grasp Titanium Ring of Vitriol +1', value: 'Victory Grasp Titanium Ring of Vitriol +1' },
  { label: 'Victory Moon Silver Ring of Rage +1', value: 'Victory Moon Silver Ring of Rage +1' },
  { label: 'Victory Peak Bronze Ring of Fury +1', value: 'Victory Peak Bronze Ring of Fury +1' },
  { label: 'Victory Peak Silver Ring of Anger +1', value: 'Victory Peak Silver Ring of Anger +1' },
  { label: 'Victory Peak Silver Ring of Fury +1', value: 'Victory Peak Silver Ring of Fury +1' },
  { label: 'Victory Peak Silver Ring of the Fox +1', value: 'Victory Peak Silver Ring of the Fox +1' },
  { label: 'Victory Shout Platinum Ring of Vitriol +1', value: 'Victory Shout Platinum Ring of Vitriol +1' },
  { label: 'Vortex Glow Gold Ring of Detection', value: 'Vortex Glow Gold Ring of Detection' },
  { label: 'Vortex Glow Platinum Ring of Detection', value: 'Vortex Glow Platinum Ring of Detection' },
  { label: 'Vortex Glow Platinum Ring of the Twins', value: 'Vortex Glow Platinum Ring of the Twins' },
  { label: 'Vortex Glow Titanium Ring of Vitriol', value: 'Vortex Glow Titanium Ring of Vitriol' },
  { label: 'Vortex Root Titanium Ring of the Twins', value: 'Vortex Root Titanium Ring of the Twins' },
  { label: 'Vortex Sun Platinum Ring of Perfection', value: 'Vortex Sun Platinum Ring of Perfection' },
  { label: 'Vortex Sun Silver Ring of Perfection', value: 'Vortex Sun Silver Ring of Perfection' },
  { label: 'Vortex Tear Silver Ring of Giants', value: 'Vortex Tear Silver Ring of Giants' },
  { label: 'Vortex Tear Titanium Ring of Rage', value: 'Vortex Tear Titanium Ring of Rage' },
  { label: 'Vortex Whisper Silver Ring of Titans', value: 'Vortex Whisper Silver Ring of Titans' },
  { label: 'Woe Bite Silver Ring of Anger +1', value: 'Woe Bite Silver Ring of Anger +1' },
  { label: 'Woe Moon Silver Ring of Vitriol +1', value: 'Woe Moon Silver Ring of Vitriol +1' },
  { label: 'Woe Peak Gold Ring of Perfection +1', value: 'Woe Peak Gold Ring of Perfection +1' },
  { label: 'Woe Peak Platinum Ring of Anger +1', value: 'Woe Peak Platinum Ring of Anger +1' },
  { label: 'Woe Shout Bronze Ring of Giants +1', value: 'Woe Shout Bronze Ring of Giants +1' },
  { label: 'Woe Shout Bronze Ring of the Twins +1', value: 'Woe Shout Bronze Ring of the Twins +1' },
  { label: 'Woe Shout Silver Ring of Vitriol +1', value: 'Woe Shout Silver Ring of Vitriol +1' },
];
